### ISSUE TITLE
Smaller MessageKit View height

### ISSUE THREAD

**Issue by mrousavy** [MessageKit/MessageKit#1000]
When using an embeddable content view (in my example inside the Pulley bottom drawer with a height of ~55% of the screen) the message input bar is not shown.

I've tested it by presenting the same messagekit viewcontroller in fullscreen which shows the message input bar, so in the drawer view it must be rendered outside of the screen.

Does anyone know how I can fix this? Do I have to set special constraints so it knows where the UIView ends?

**Comment by nathantannar4** [comment]
The input view is an InputAccessoryView thus your view controller needs to be the first responder and it's InputAccessoryView should return the `MessagesViewController.inputAccessoryView`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mrousavy** [comment]
Apparently the view was not the first responder.
The MessageInputBar appeared once I forced the view to become the first responder (`self.becomeFirstResponder()`).
