### ISSUE TITLE
SenderType protocol. Rename id.

### ISSUE THREAD

**Issue by NikKovIos** [MessageKit/MessageKit#1003]
Hello, i'm using the 3.0.0-beta version and there the Sender become SenderType protocol with value `id`.
In my app i need 3 entities to fit this protocol and they already have the `id` var with Int extension. In that case i either to
1) Create own Sender entity that fits SenderType and transform my 3 to it first.
2) Rename my entity's id and implement the protocol's id , then is not convenience.
3) Ignore the deprecated message for Sender class from MessageKit.

My suggestion to rename SenderType's `id` to `chatID` or something like that.

**Comment by nathantannar4** [comment]
What is your current `id` extension? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NikKovIos** [comment]
Current is Int. Btw, I use realm to store it.

**Comment by nathantannar4** [comment]
Alright, but if it's an extension I presume it's not critical to your data model and the type could be changed? I believe most ids are strings in the form of a UUID which is why it's the way it is. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NikKovIos** [comment]
The id can be a string, even bool, but it's better to leave the framework flexible. I can change it to String, but app i already tailored to id as Int value (equitation). For example, guys, who create backend could be very... special and send int value.

**Comment by NikKovIos** [comment]
So, what about implementing?

**Comment by nathantannar4** [comment]
Yea, I'll change it to `senderId` but it will remain a string

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NikKovIos** [comment]
@nathantannar4 great, thx!

**Comment by nathantannar4** [comment]
Done

**Comment by asn111** [comment]
Hi , i need to know how do we set this senderType to my currentSender. I am stuck in here, 
```extension ChatViewController : SenderType {
    var senderId: String {
        return loginUserProfile.userId
    }
     var displayName: String {
        return loginUserProfile.fullName
    }   
}

extension ChatViewController : MessagesDataSource {
    func currentSender() -> SenderType {
        return SenderType.self as! SenderType
    }
}

**Comment by nathantannar4** [comment]
SenderType is a protocol. Confirm your user to it and then you can just return `loginUserProfile`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by asn111** [comment]
> SenderType is a protocol. Confirm your user to it and then you can just return `loginUserProfile`
> 
> Sent with [GitHawk](http://githawk.com)

hi, I did not get what you meant by confirm your user,  am I doing it wrongly?

**Comment by nathantannar4** [comment]
Sorry autocorrect, **conform** to the `SenderType` protocol. This means your loginUserProfile class should have a senderId and displayName get property

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by asn111** [comment]
Okay got it, but I am having another problem now :( 
when I send chat message, my bubbles are switching there sides like if I am the sender as per my logic i will be on right , but my chat bubbles keep switching as i start messaging, this wasn't happening when I was using sender struct.
have a look in image. thanks for your support
![IMG_6F8E9717D292-1](https://user-images.githubusercontent.com/8926549/57549760-d8fbd600-737d-11e9-88e5-f638c1ac1baa.jpeg)

**Comment by nathantannar4** [comment]
Review your logic in `func messageStyle(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> MessageStyle`

**Comment by asn111** [comment]
I have created this object which conforming MessageType 

```
extension ChatMessageObject : MessageType {
    var sender: SenderType {
        // here I did this before, publisher is the id where I am comparing in messageStyle.
       // now what I have to put in here. 
        return Sender(id: publisher, displayName: "")

    }
    var messageId: String {
        return ""
    }
    
    var sentDate: Date {
        return Date()
    }
    
    var kind: MessageKind {
        return .text(message)
    }  
}```

//I did something like this but it did not worked.

```extension ChatMessageObject : SenderType {
    var senderId: String {
        return publisher
    }
    
    var displayName: String {
        return ""
    }
}```

**Comment by asn111** [comment]
Okay I got it, I have to change my logic, thanks a lot for your time :)
