### ISSUE TITLE
Enlarge image when the user taps on it

### ISSUE THREAD

**Issue by zoufishanmehdi** [MessageKit/MessageKit#1005]
What version of MessageKit are you using?
2.0.0.
What version of iOS are you running on?
12.1
What version of Swift are you running on?
4.2
What device(s) are you testing on? Are these simulators?
iPhone 7

Hi,

Is there a way to enlarge the image when the user taps on it and dismiss it when the user taps on it again? I would like the users to somehow see the entire image. I would really appreciate any input on this. Thank you!

**Comment by nathantannar4** [comment]
This functionality is not built into the library. You will need to use the cell selection delegate methods that show when a message bubble was tapped to present your enlarged image controller/view

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
