### ISSUE TITLE
how to create many different custom cell type

### ISSUE THREAD

**Issue by chunxige** [MessageKit/MessageKit#1007]

**Comment by nathantannar4** [comment]
Please see the example project for how to use custom cells. If you have a more specific question please first check to see if it has been asked before

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chunxige** [comment]
i see the example ,and it only can resolve single cell type

**Comment by blinkuz** [comment]
I have the same question, since according to the example I could implement a custom cell type but I do not know how it would be to create several in my case I have 4 types of personalized messages with their own UI and independent functionalities.

**Comment by nathantannar4** [comment]
.custom takes Any as it's associated type. You would have to cast that inner type to your custom model to determine the cell. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chunxige** [comment]
thanks @nathantannar4

**Comment by blinkuz** [comment]
> thanks @nathantannar4

Could you implement it? If so, can you share some example code to do it?

**Comment by Joseph-Sam** [comment]
I'm not following the response here. When trying to add more than custom cell in "cellForItemAt" I'm seeing the error:
Binary operator '==' cannot be applied to operands of type 'MessageKind' 
Thank you.
