### ISSUE TITLE
Collectionview CRASH for invalid number of sections!

### ISSUE THREAD

**Issue by Michele404** [MessageKit/MessageKit#1008]
I got this crash randomly when I try to open the keyboard

*** Assertion failure in -[MessageKit.MessagesCollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore/UIKit-3698.94.14/UICollectionView.m:6104

 *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of sections.  The number of sections contained in the collection view after the update (0) must be equal to the number of sections contained in the collection view before the update (18), plus or minus the number of sections inserted or deleted (0 inserted, 0 deleted).'

How can I fix??

**Comment by nathantannar4** [comment]
Looks like you are deleting cells without actually deleting the model. This isnt MessageKit specific you should look up how to correctly insert/delete cells from a collection view. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
