### ISSUE TITLE
Missing documentation for custom cells

### ISSUE THREAD

**Issue by whoyawn** [MessageKit/MessageKit#1011]
- What version of MessageKit are you using? 2.0

The documentation for the `custom` case in `MessageKit/Sources/Models/MessageKind.swift` is incomplete and/or outdated. The example app overrides `UICollectionViewDataSource.collectionView(_:cellForItem:)` and subclasses `MessagesCollectionViewFlowLayout`, which matches the documentation before #879.

I can add in additional documentation to match the example app, but is the way in the documentation also valid? (Current documentation below)

```
/// - Note: Using this case requires that you implement the following methods and handle this case:
///   - MessagesDataSource: customCell(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> UICollectionViewCell
///   - MessagesLayoutDelegate: customCellSizeCalculator(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> CellSizeCalculator
```

Having more documentation would make this a lot more clear.

**Comment by whoyawn** [comment]
Thoughts?

**Comment by nathantannar4** [comment]
Sorry for the delay. The documention defines the preferred way of implementing custom cells as it provides an easier API. Its really the example app that's outdated and still shows the old (but still valid) method

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
