### ISSUE TITLE
MessageInputBar get's dismissed when MessageViewController is embedded in UINavigationController and is used as an ChildViewController

### ISSUE THREAD

**Issue by Dwayne28** [MessageKit/MessageKit#1012]
### General Information

- MessageKit Version:
2.0.0

- iOS Version(s):
11.0

- Swift Version:
4.0

- Devices/Simulators:
Both only iPhone

- Reproducible in ChatExample? (Yes/No):
Yes, if you add the MessageViewController as Child like this (inside of another ViewController).
```
let messageVC = MessagesViewController()
let navVC = UINavigationController(rootViewController: messageVC)
addChildViewController(navVC)
view.addSubview(navVC)
navVC.view.frame = CGRect(x: 0, y: 0, width: view.bounds.size.width, height: view.bounds.size.height)
navVC.didMove(toParentViewController: self)
```
### What happened?

The MessageInputBar animates down offscreen when I swipe down or touch between (sendButton and TextField) or when I swipe down on the NavigationBar.

### What did you expect to happen?

The MessageInputBar to remain visible, even if I Touch or Swipe somewhere.

### My Question

How can I fix this to behave like when it's not used as a Child?

What I found out is that when I observe Keyboard events like:
- UIKeyboardDidHideNotification

And I set the ```becomeFirstResponder``` again the MessageInputBar comes back, but always with an animation. It moves down and a second after this it will come back. 

When I use:
- UIKeyboardWillHideNotification
and set ```becomeFirstResponder``` again it doesn't work at all. I tried to delay it with Dispatch.async.main. But then I have the same effect as with UIKeyboardDidHideNotification.

Where do I need to set the becomeFirstResponder again or any other thing that will do the trick?

**Comment by nathantannar4** [comment]
The MessagesViewController needs to be the first responder. Try looking at the chat example project first to ensure you have correctly set up a child view controller to work with an input accessory view

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
You could try setting the InputAccessoryView of the parent view controller to the message input bar as well. Don't forget canBecomeFirstResponder

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Dwayne28** [comment]
Works thanks
