### ISSUE TITLE
Avatar being displayed when an image is added, despite avaar being hidden

### ISSUE THREAD

**Issue by hariravi** [MessageKit/MessageKit#1015]
![IMG_FD8C7442717C-1](https://user-images.githubusercontent.com/965144/54223655-32967000-44b5-11e9-9ecf-dd83d0037244.jpeg)

- What version of MessageKit are you using?
Using MessageKit (2.0.0)
- What version of iOS are you running on?
12.1.4
- What version of Swift are you running on?
swift 4.2
- What device(s) are you testing on? Are these simulators?
iphone7, iphone X, real devices
- Is the issue you're experiencing reproducable in the example app?
Yes

Hi All, I seem to be unable to hide the avatar view when dealing with photos, see attached image! On the example app as well (a photo also attached), I am unable to hide the avatar view (on my app, it properly hides for text, but not images). Thank you very much for creating a great tool, it is allowing me to develop my app! Below is the code I use to hide the avatar.

```
extension MKViewController: MessagesLayoutDelegate {
    func heightForLocation(message: MessageType,
                           at indexPath: IndexPath,
                           with maxWidth: CGFloat,
                           in messagesCollectionView: MessagesCollectionView) -> CGFloat {

        return 0
    }

    func avatarSize(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> CGSize {
        return .zero
    }
}

// And my message object declaration, conforms to MessageType
struct Member {
    let name: String
}

struct Message {
    let member: Member
    let text: String
    let messageId: String
    let time: Int
    var image:UIImage? = nil
}

extension Message: MessageType {
    var sender: Sender {
        return Sender(id: member.name, displayName: member.name)
    }

    var sentDate: Date {
        return Date()
    }

    var kind: MessageKind {
        if image != nil {
            return .photo(image!)
        } else {
            return .text(text)
        }
    }
}

extension UIImage: MediaItem {
    public var url: URL? { return nil }
    public var image: UIImage? { return self }
    public var placeholderImage: UIImage { return self }
    public var size: CGSize { return  CGSize(width: 240, height: 240) }
}

```

Thank you very much again, really appreciate you guys!

**Comment by hariravi** [comment]
Sorry, the example image, I forgot to add this in my initial post.

![IMG_47E89DBE6A19-1](https://user-images.githubusercontent.com/965144/54224720-58bd0f80-44b7-11e9-8348-d604520926c5.jpeg)

**Comment by nathantannar4** [comment]
You need to set the avatar size through 
```
let layout = messagesCollectionView.collectionViewLayout as? MessagesCollectionViewFlowLayout
layout?.setMessageIncomingAvatarSize
```

**Comment by hariravi** [comment]
Thank you very much for your response Mr. Tannar!

I actually include the following in viewDidLoad().
```
        if let layout = messagesCollectionView.collectionViewLayout as? MessagesCollectionViewFlowLayout {
            layout.textMessageSizeCalculator.outgoingAvatarSize = .zero
            layout.textMessageSizeCalculator.incomingAvatarSize = .zero
            layout.setMessageIncomingAvatarSize(.zero)
        }
```
But the problem still persists (and the ? avatar is only for the image, for the text there is no avatar visible).

Thank you again for your help!

**Comment by hariravi** [comment]
Hi Nathan, sorry to bother you, any update on this!? Am building a cool messaging application, trying to give users the ability to send photos, but I am unable to solve the ? avatar issue.

Thanks,
Hari

**Comment by hariravi** [comment]
Just one more screenshot, does anyone else have this problem? The avatars are missing (as intended) for the purely text messages, but they are still showing up for images only ...

![IMG_E240347058D6-1](https://user-images.githubusercontent.com/965144/54408393-fcb4df80-469e-11e9-8fe7-9046c19d80ef.jpeg)

**Comment by nathantannar4** [comment]
From your code you only ever set incoming Avatar size, but in your screenshot that's an outgoing message. You forgot `setMessageOutgoingAvatarSize`  which I show in the example project

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hariravi** [comment]
Sorry about this, silly mistake on my end, thank you again!

**Comment by nathantannar4** [comment]
All good 😄

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
