### ISSUE TITLE
I can't run on real device.

### ISSUE THREAD

**Issue by MourinhoLove** [MessageKit/MessageKit#1016]
When I ran the demo, I found that I could not run on the real device.

**Comment by MourinhoLove** [comment]
But simulator can

**Comment by grd888** [comment]
Did you change the Bundle Identifier to your own ?

**Comment by MourinhoLove** [comment]
> Did you change the Bundle Identifier to your own ?

Yes. I am running on my device by changing the Bundle Identifier.

**Comment by MourinhoLove** [comment]
> Did you change the Bundle Identifier to your own ?

The project was compiled successfully. But when running, it prompts "Could not launch "ChatExample""

**Comment by MourinhoLove** [comment]
> Did you change the Bundle Identifier to your own ?

I know the reason. Because "Debug Executable"
