### ISSUE TITLE
The messageInputBar overlaps the last message(messageKit 3.0.0 beta)

### ISSUE THREAD

**Issue by xxjldh** [MessageKit/MessageKit#1020]
- What version of MessageKit are you using?
   ➡️MessageKit (3.0.0-beta)➡️InputBarAccessoryView (4.2.1)
   (Quick fix for #993 )
- What version of iOS are you running on?
   ➡️real device iPhone 7 Plus  version:10.3.2
- What version of Swift are you running on?
   ➡️Version:10.1(10B61)
- Is the issue you're experiencing reproducable in the example app?
   ➡️yes

I  download it from MessageKit(3.0.0 beta quick fix for #993 ) branch  and run directly on a real device.
The problem  happened when I opened the keyboard and closed the keyboard.

When the app just started, it was in a normal state.
![IMG_2522](https://user-images.githubusercontent.com/13329392/54861299-402bdf80-4d6a-11e9-83e6-82c3b6a8eeef.PNG)

When I first opened the keyboard, the interface was still normal.
![IMG_2523](https://user-images.githubusercontent.com/13329392/54861296-3609e100-4d6a-11e9-8424-c8cc87a5b467.PNG)

And then when I closed the keyboard, it was abnormal.The last message was covered by the messageInputBar.
![IMG_2524](https://user-images.githubusercontent.com/13329392/54861304-5e91db00-4d6a-11e9-810b-4203b60ff392.PNG)

How can I solve the problem?

**Comment by nathantannar4** [comment]
Thanks, this is a bug I am fixing

**Comment by nathantannar4** [comment]
I couldn't reproduce this with the example, is this reproducible with the standard iOS keyboard? I see you are using a 3rd party one

**Comment by xxjldh** [comment]
Thanks for your reply.

I have deleted 3rd party iOS keyboard and I tried with the standard iOS keyboard this time, but the problem still happened as the video url below. 

https://youtu.be/nbPWpuewb68

My iOS device info below.

![IMG_2534](https://user-images.githubusercontent.com/13329392/54878310-325f8280-4e6e-11e9-96d6-cd682bfe5720.JPG)

**Comment by nathantannar4** [comment]
@xxjldh You closed this? Did you find the issue on your end?

**Comment by xxjldh** [comment]
Sorry,I wrongly clicked "Close and comment" and now I reopen the issue.
My question is still unsolved, still need your help.

**Comment by nathantannar4** [comment]
Which model of I iPhone are you using? When I try with my iPhone X I have no issue

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by xxjldh** [comment]
Today I also tried on my iPhone 6 Plus( version 10.3(14E27) ),this problem(when I closed the keyboard, the last message bubble was covered by the messageinputBar ) also happened. The same problem also happened on iPhone 7 Plus ( version 10.3.2(14F89) last time I tried).
I guessed the problem is related to the iPhone version between 10.3 and 10.3.2 ?
Because I tried it on anther real device (iPhone 6s version 12.1.4 , iPhone 7 Plus  version 12.1.4 ),**it has no problem**(I have four real devices with three different versions).

**Comment by nathantannar4** [comment]
Oh no what did Apple change 😓

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by xxjldh** [comment]
I think I have solved this problem.
Here is the log file( problem unsolved status ) I ran on the iPhone 7 Plus version 10.3.2 .
[7p-10.3.2-add-0.txt](https://github.com/MessageKit/MessageKit/files/3026110/7p-10.3.2-add-0.txt)

I found that sometimes intersection.maxY equals 735.9999999999999, but not the screen height 736. So when I closed the keyboard ,the last time (from log's 49 lines)  the program ran into `intersection.isNull || intersection.maxY < messagesCollectionView.frame.maxY` branch( log's 54 line ). So the  **intersection.height** is not added. 

My solution is changing `intersection.isNull || intersection.maxY < messagesCollectionView.frame.maxY ` to `intersection.isNull || (messagesCollectionView.frame.maxY - intersection.maxY) > 0.001` ,when I closed the keyboard it ran into `intersection.isNull || intersection.maxY < messagesCollectionView.frame.maxY`'s **else branch** and the **intersection.height** was added. I tested the code on my real device 7 Plus (version 10.3.2) and another device 6 Plus (version 10.3), it has no problem.

**Comment by nathantannar4** [comment]
@xxjldh Nice debugging, I would be open to testing this in a PR if you would like to make this a contribution? Please also ensure that it will work on iOS > 11

**Comment by yavuzaytekin** [comment]
Hello fellows,
If you still see this bug, i have workaround for you. 
This worked for me.

```
var isTyping = false

override func viewDidLoad() {
	super.viewDidLoad()
        NotificationCenter.default.addObserver(self,
                                               selector: #selector(inputTextViewDidBeginEditing),
                                               name: UITextView.textDidBeginEditingNotification, object: messageInputBar.inputTextView)
        NotificationCenter.default.addObserver(self,
                                               selector: #selector(inputTextViewDidEndEditing),
                                               name: UITextView.textDidEndEditingNotification, object: messageInputBar.inputTextView)
        NotificationCenter.default.addObserver(self,
                                               selector: #selector(keyboardFrameChanged),
                                               name: UIResponder.keyboardDidChangeFrameNotification, object: nil)
	}

@objc func keyboardFrameChanged(_ notification: Notification) {
        if let keyboardFrame = notification.userInfo?["UIKeyboardFrameEndUserInfoKey"] as? NSValue {
            if isTyping {
                messagesCollectionView.contentInset.bottom = keyboardFrame.cgRectValue.height
            } else {
                messagesCollectionView.contentInset.bottom = messageInputBar.frame.height
            }
            guard isLastSectionVisible() else { return }
            messagesCollectionView.scrollToBottom(animated: true)
        }
    }

@objc func inputTextViewDidBeginEditing() {
        isTyping = true
    }

@objc func inputTextViewDidEndEditing() {
        isTyping = false
    }
```
