### ISSUE TITLE
How can I change the send button's width? I'd like to change the text to german, but then it gets truncated in the middle...

### ISSUE THREAD

**Issue by haemi** [MessageKit/MessageKit#1023]
- What version of MessageKit are you using?
2.0.0

- What version of iOS are you running on?
latest stable version

- What version of Swift are you running on?
4.2

- What device(s) are you testing on? Are these simulators?
Simulator and iPhone Xs Max

- Is the issue you're experiencing reproducable in the example app?
yes

What's the best way to localize the "send" button? I change the text within `viewDidLoad` of my MessagesViewController-subclass, but the width-property is ignored:

```
        messageInputBar.sendButton.configure {
                $0.setSize(CGSize(width: 370, height: 36), animated: false)
                $0.isEnabled = false
                $0.title = "Senden"
                $0.tintColor = UIColor.blue
                $0.setTitleColor(UIColor.green, for: .normal)
                $0.setTitleColor(UIColor(white: 0.8, alpha: 1), for: .disabled)
                $0.titleLabel?.font = UIFont.systemFont(ofSize: 15, weight: .bold)
            }.onTouchUpInside {
                $0.messageInputBar?.didSelectSendButton()
        }
```

Now my send button reads "Se...en"

**Comment by nathantannar4** [comment]
You need to also set the right stack view width so it has enough room for the button

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by haemi** [comment]
awesome, thanks!

**Comment by ljs19923** [comment]
How did you do that?
