### ISSUE TITLE
Broken cells layout

### ISSUE THREAD

**Issue by nmnikitsin** [MessageKit/MessageKit#1026]
Hi all. I have faced one issue in the cell's layout. Sometimes when a UICollection contains numerous messages from one sender layout looks broken. Sorry for so abstract description of the issue, but can't find out concrete reproducing steps.

Tested on iPhone 5s (iOS 12.1.3) 

Thanks

**Comment by nathantannar4** [comment]
Please define "broken" and perhaps add some screenshots

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
