### ISSUE TITLE
[Question] MessageKit Example - Draggable MessagesViewController

### ISSUE THREAD

**Issue by ghost** [MessageKit/MessageKit#1028]
MessageKit is awesome, and I've been playing around with the example. I have a basic question about transitions and am a little stumped.

In the MessageKit example, you can swipe right and drag the MessagesViewController. If the threshold is big enough, the MessagesViewController is popped to the previous screen. 

**Question: Where in the code is this handled?**

[Here](https://youtu.be/_4pRFxwsosw) is what I am talking about

I've looked through the example multiple times and cannot seem to find any specific PanGesture references.

Thank you for your time!

**Comment by nathantannar4** [comment]
@ASpicyHamburger That's standard `UINavigationController` behaviour

**Comment by ghost** [comment]
Ah, that makes sense. Thought it was custom!

Trying to wean myself off of Storyboard and do everything programmatically. Thank you for the quick reply, I appreciate it.
