### ISSUE TITLE
swipe down the inputBar to bottom with a bottomStackView 

### ISSUE THREAD

**Issue by xxjldh** [MessageKit/MessageKit#1029]
I added a bottomView to the bottomStackView. How can I swipe down the inputBar with a bottomStackView to the screen's bottom.
![Simulator Screen Shot - iPhone 8 Plus 11 0 - 2019-03-30 at 13 43 08](https://user-images.githubusercontent.com/13329392/55284237-51e63600-53ad-11e9-8823-a4f5d29c602e.png)

result screen:
![Simulator Screen Shot - iPhone 8 Plus 11 0 - 2019-03-30 at 13 42 56](https://user-images.githubusercontent.com/13329392/55284257-aee1ec00-53ad-11e9-9185-496c4f3d355d.png)

My current idea is to add `messageInputBar.bottomStackView.arrangedSubviews.first?.removeFromSuperview()` to someone method when I swiped down the inputBar.

Can you give me some advice? Thanks.

**Comment by nathantannar4** [comment]
You are probably going to want to use a `UISwipeGeasture`. You wouldn't need to remove it as a subview, you could just give it a height constraint and animate the constant between 0 and X to show/hide it. For extra flair I would animate the alpha as well

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
