### ISSUE TITLE
Migrate to Swift 5 please

### ISSUE THREAD

**Issue by DanielReyesDev** [MessageKit/MessageKit#1030]

**Comment by nathantannar4** [comment]
Yes, I will try to release 3.0.0 ASAP, there will be two branches, the main on Swift 5 and another on Swift 4.2 but with the updated features. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by acib708** [comment]
thank youuuu

**Comment by JianTing-Li** [comment]
Hello, may I know approximately when 3.0.0 that supports Swift 5 will be released?

**Comment by nathantannar4** [comment]
I can try to put together a beta2 release this weekend with a branch in Swift 5

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JianTing-Li** [comment]
When I pod install, it only installs the 2.0.0 version. How do I update it to the 3.0.0 beta version to try it out?

**Comment by nathantannar4** [comment]
You need to specify the branch name, I don't have the exact syntax memorized but a quick google search will tell you. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JianTing-Li** [comment]
Thanks, I got it.

**Comment by nathantannar4** [comment]
@JianTing-Li @DanielReyesDev @acib708 I released a Swift 5 build. Haven't pushed it to cocoa pods yet because I want the Swift 4.2 to be the default that people update too.

`pod 'MessageKit', :git => 'https://github.com/MessageKit/MessageKit.git', :tag => '3.0.0-beta-swift5'`
