### ISSUE TITLE
Is it possible to apply style to custom cells?

### ISSUE THREAD

**Issue by SergeyGamayunov** [MessageKit/MessageKit#1033]
Hi!

I want to add my custom view inside bubble. I understand that I have to create my own custom cell class and implement both `func customCell(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView)` and `func customCellSizeCalculator(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView)`. 

But it makes style disappear, so I don't have tails and bubbles. I thought about adding custom view as image subview at `configureMediaMessageImageView` but it seems to me over-engineered. 

Also I thought about override `func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath)` and customise cell right there. 

However, I still hope that we can just simply provide custom view to embed it inside regular bubble.

**Comment by nathantannar4** [comment]
So if you use a custom cell then ALL the configuration needs to be done when you return that custom cell. So you would need to apply the bubble style yourself when you return the cell. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SergeyGamayunov** [comment]
> So if you use a custom cell then ALL the configuration needs to be done when you return that custom cell

Yes, I certainly understand mechanism but I just don't agree with it :)

Every chat could probably have a various cell types and many, many of them will have to be with bubble style. Just imagine:

- Share message
- Forward message
- Contact message
- Message with file

And since we already have pretty convenient way to embed image inside bubble we IMHO should be able to add custom view instead of that imageView, apply bubble and tail style and maybe provide specific size for this custom view.

**Comment by nathantannar4** [comment]
While I see where you are coming from, the MessageKit library has no idea what custom cell you are returning is. There is no guarantee that it has a message bubble as we allow for any `UICollectionViewCell` to be returned. Using custom cells means you are fully responsible for the appearance as it is custom. We cannot make automatic changes as we could end up changing something that is unwanted. 

I think it should be simple enough to set the style you want when returning your custom cell. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by blinkuz** [comment]
@nathantannar4 Is there any documentation or example showing how simple or complex it can be to create a custom design for a custom cell?

**Comment by nathantannar4** [comment]
Yes in the ChatExample I made a simple custom cell. Have you looked at it?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JulienKode** [comment]
You can also take a look at: 

- https://github.com/MessageKit/MessageKit/issues/686
- https://stackoverflow.com/questions/56958482/how-to-create-custom-cell-with-messagekit/57165876#57165876
- https://github.com/MessageKit/MessageKit/issues/945
