### ISSUE TITLE
Coredata support for MessageKit

### ISSUE THREAD

**Issue by gumdal** [MessageKit/MessageKit#1034]
#Messagekit Coredata Support 

I had a requirement to persist the messages using native Coredata framework in the device. Since MessageKit does not support it by default, I started with a fork of MessageKit and I have achieved whatever is necessary for me.

This is my fork: https://github.com/gumdal/MessageKit. All changes are in the `development` branch.

I further wanted to contribute it back to MessageKit, so I created a pull request #1024, however, as I understand that the maintainers want to keep the repository clean with only UI layer development which in my opinion is a wise decision. At the same time, there would be many people who might want to use this and further build on it. This is an invite for people who want to extend and build further on it.

An outlook onto the features currently built in the fork:

- Support persisting of chat messages, users and message kind using Coredata wrapper classes.

**Comment by SD10** [comment]
Hey @gumdal, awesome work!! Unfortunately, I think that MessageKit should remain agnostic towards any sort of persistence layer or framework.

You can read more about our [vision for the project](https://github.com/MessageKit/MessageKit/blob/master/VISION.md)

**Comment by wertpoiu** [comment]
> #Messagekit Coredata Support
> 
> I had a requirement to persist the messages using native Coredata framework in the device. Since MessageKit does not support it by default, I started with a fork of MessageKit and I have achieved whatever is necessary for me.
> 
> This is my fork: https://github.com/gumdal/MessageKit. All changes are in the `development` branch.
> 
> I further wanted to contribute it back to MessageKit, so I created a pull request #1024, however, as I understand that the maintainers want to keep the repository clean with only UI layer development which in my opinion is a wise decision. At the same time, there would be many people who might want to use this and further build on it. This is an invite for people who want to extend and build further on it.
> 
> An outlook onto the features currently built in the fork:
> 
> * Support persisting of chat messages, users and message kind using Coredata wrapper classes.

how did you manage coredata to work with messagekit?

**Comment by gumdal** [comment]
> how did you manage coredata to work with messagekit?

I was able to fork and plug in Coredata into it. Although the project is bit old and I haven't maintained it since I used it once in my main project. I believe it should not be a challenge to get it up and running though. Please see the forked project which I mentioned above. I have documented it and also have sample application for the same.

Edit: I also updated the ReadME in master branch so that it points out to the right branch (development) for Coredata related code and documentation.

**Comment by braamBeresford** [comment]
> 
> 
> > how did you manage coredata to work with messagekit?
> 
> I was able to fork and plug in Coredata into it. Although the project is bit old and I haven't maintained it since I used it once in my main project. I believe it should not be a challenge to get it up and running though. Please see the forked project which I mentioned above. I have documented it and also have sample application for the same.
> 
> Edit: I also updated the ReadME in master branch so that it points out to the right branch (development) for Coredata related code and documentation.

Hi @gumdal ,
I can't seem to find the MessageKit.xcdatamodelId file in your repo, am I missing something?

Braam

**Comment by gumdal** [comment]
> > > how did you manage coredata to work with messagekit?
> > 
> > 
> > I was able to fork and plug in Coredata into it. Although the project is bit old and I haven't maintained it since I used it once in my main project. I believe it should not be a challenge to get it up and running though. Please see the forked project which I mentioned above. I have documented it and also have sample application for the same.
> > Edit: I also updated the ReadME in master branch so that it points out to the right branch (development) for Coredata related code and documentation.
> 
> Hi @gumdal ,
> I can't seem to find the MessageKit.xcdatamodelId file in your repo, am I missing something?
> 
> Braam

Hi @braamBeresford,

Sorry for delayed response. Code related to coredata is in a different branch. Please see my "Coredata" section of Readme. Extract for you over here:

Core data support has been added in "development" branch of this fork: https://github.com/gumdal/MessageKit/tree/development Documentation for the same can be found here: https://github.com/gumdal/MessageKit/blob/development/Documentation/Coredata.md The sample application in this source has been updated to include coredata support for demo purpose: https://github.com/gumdal/MessageKit/tree/development/Example

Thanks,
Raj Pawan Gumdal

**Comment by braamBeresford** [comment]
> > > > how did you manage coredata to work with messagekit?
> > > 
> > > 
> > > I was able to fork and plug in Coredata into it. Although the project is bit old and I haven't maintained it since I used it once in my main project. I believe it should not be a challenge to get it up and running though. Please see the forked project which I mentioned above. I have documented it and also have sample application for the same.
> > > Edit: I also updated the ReadME in master branch so that it points out to the right branch (development) for Coredata related code and documentation.
> > 
> > 
> > Hi @gumdal ,
> > I can't seem to find the MessageKit.xcdatamodelId file in your repo, am I missing something?
> > Braam
> 
> Hi @braamBeresford,
> 
> Sorry for delayed response. Code related to coredata is in a different branch. Please see my "Coredata" section of Readme. Extract for you over here:
> 
> Core data support has been added in "development" branch of this fork: https://github.com/gumdal/MessageKit/tree/development Documentation for the same can be found here: https://github.com/gumdal/MessageKit/blob/development/Documentation/Coredata.md The sample application in this source has been updated to include coredata support for demo purpose: https://github.com/gumdal/MessageKit/tree/development/Example
> 
> Thanks,
> Raj Pawan Gumdal

@gumdal,
I was being an idiot and missed a file that was right in front of me!

Thanks for the help,
Braam

**Comment by gumdal** [comment]
Hi Braam,

That's fine. Thanks for dropping by the repo though. It is not maintained
since couple of years now, but still I feel the codebase should be
relevant. If you feel it can be enhanced or if you happened to extend and
enhance the code then please do raise a Pull Request back.

Thanks,
Raj Pawan Gumdal
