### ISSUE TITLE
Looking for a migration path from cellTopLabelAlignment former delegate method of MessagesLayoutDelegate

### ISSUE THREAD

**Issue by crspybits** [MessageKit/MessageKit#1041]
I'm migrating my usage of MessageKit from 0.13.5 to 2.0.0. In my current code (from 0.13.5), I have a delegate method of `MessagesLayoutDelegate`:

```
    func cellTopLabelAlignment(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> LabelAlignment {
        if isFromCurrentSender(message: message) {
            return .messageTrailing(UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 10))
        } else {
            return .messageLeading(UIEdgeInsets(top: 0, left: 10, bottom: 0, right: 0))
        }
    }
```

I asked a question about this on SO (and am finally getting to the migration!)-- 
https://stackoverflow.com/questions/52583843/migration-to-1-0-0-messagekit-cocoapod-with-messageslayoutdelegate?rq=1

Unfortunately, it looks like in the interrim the delegate method `cellTopLabelAlignment` has been removed. Unfortunately also it looks like the change log (https://github.com/MessageKit/MessageKit/blob/master/CHANGELOG.md) doesn't mention this removal of `cellTopLabelAlignment`.

Can you please suggest a migration path to replace this usage of `cellTopLabelAlignment`?
Thanks!

- What version of MessageKit are you using?
I'm migrating to 2.0.0 from 0.13.5

- What version of iOS are you running on?
12.1

- What version of Swift are you running on?
4.2

- What device(s) are you testing on? Are these simulators?
Simulators currently.

- Is the issue you're experiencing reproducable in the example app?
This is an issue, based on a migration.

**Comment by crspybits** [comment]
Well, I've got my code working again without use of this delegate method, so looks like it's not needed any more?

**Comment by nathantannar4** [comment]
All of the alignment has migrated to the `MessageCollectionViewLayout`. We have convenience methods like `setOutgoingMessageCellTopLabelAlignment(...)` that you can set in your view did load. The reason for this was to enforce a static layout so we could make optimizations knowing that a label alignment cannot change without first invalidating the layout.

**Comment by crspybits** [comment]
Cool. Thanks :).
