### ISSUE TITLE
Can a gesture recognizer be added to a custom cell correctly?  

### ISSUE THREAD

**Issue by clay-mindoula** [MessageKit/MessageKit#1042]
I have added a gesture to my custom view / cell and it's working. But I'm wondering with a bit more work I can add via the framework such that:
```
func didTapMessage(in cell: MessageCollectionViewCell) { ... }
```
works for custom cells?

**Comment by nathantannar4** [comment]
So that is a `MessageCellDelegate` function. Your custom cell would need to have a weak var delegate of that type that you set to the `MessagesCollectionView.messageCellDelegate`. See `MessageContentCell` and just do the same as we do it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by clay-mindoula** [comment]
For the next guy:

Add this to your custom cell:
```
class FileAttachmentCustomCell: MessageCollectionViewCell 
    open weak var delegate: MessageCellDelegate?
    ...
```
```
    open func configure(with message: MessageType, at indexPath: IndexPath, and messagesCollectionView: MessagesCollectionView) {
        delegate = messagesCollectionView.messageCellDelegate
        let tap: UITapGestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(handleTapGesture(_:)))
        tap.cancelsTouchesInView = false
        fileAttachmentView.addGestureRecognizer(tap)
   ...
```
@objc open func handleTapGesture(_ gesture: UIGestureRecognizer) {
        delegate?.didTapMessage(in: self)
    }
```

**Comment by nathantannar4** [comment]
I'll leave open so this is easier to find

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by clay-mindoula** [comment]
noted!
