### ISSUE TITLE
Keys for address components for didSelectAddress delegate method

### ISSUE THREAD

**Issue by crspybits** [MessageKit/MessageKit#1043]
With version 2.0.0 of MesageKit, I'm using the `didSelectAddress` delegate method of `MessageCellDelegate`. Digging into the code, I see that the keys for `addressComponents` are `NSTextCheckingKey`'s. In my case, I need to geocode the address so I need to rebuild the address components into a string that makes sense to a geocoder. Here's what I have:

```
    func didSelectAddress(_ addressComponents: [String : String]) {
        // It's not documented, but the keys are from NSTextCheckingKey. Having to do some machinations to get just a simple address string again to geocode it.
        let keys = [NSTextCheckingKey.street.rawValue, NSTextCheckingKey.city.rawValue, NSTextCheckingKey.state.rawValue, NSTextCheckingKey.zip.rawValue]
        var address = ""
        
        for key in keys {
            if let value = addressComponents[key] {
                if address.count > 0 {
                    address += ", "
                }
                
                address += value
            }
        }
        
        guard address.count > 0 else {
            return
        }
    
        AddressNavigation.navigate(to: address, using: self)
    }
```

Any chance to add a parameter to the delegate method that is just the original address string from the text? Or at least to make it clear in the code/docs where the keys come from so I can depend on this? Thanks!

**Comment by nathantannar4** [comment]
Can you give me an example of how your original string is different than your reconstructed string?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by crspybits** [comment]
Hey, thanks for the quick response. This is not quite my concern. My concern is more along the lines of the undocumented nature of the keys. Since I had to dig into the code to figure out what the keys are, it makes me think they might easily change in the future.  Of course, having the original address string in the delegate method parameter would bypass these concerns completely.

Another way to resolve this would be to give an array of key, value pairs and not a dictionary. Where the ordering in a standard address sequence is preserved in the key/value ordering of the array. E.g.,
[("Street", "123 Happy Lane"), ("City", "San Francisco"), ("State", "CA")]
The issue I'm having with a dictionary in this context is that the keys are not ordered.

**Comment by nathantannar4** [comment]
What about something like this branch: `improvements/address-selection`

```swift
public enum AddressComponent {
    case name(String)
    case jobTitle(String)
    case organization(String)
    case street(String)
    case city(String)
    case state(String)
    case zip(String)
    case country(String)
    ...
}
```

**Comment by crspybits** [comment]
That can certainly work. Thanks!

**Comment by crspybits** [comment]
That's an aggressive stale bot! :). Is there more action you need from me?

**Comment by nathantannar4** [comment]
😂 No, I'll be including the change in a future release

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
