### ISSUE TITLE
ImageView size in media cell is ZERO

### ISSUE THREAD

**Issue by AhmedMohamedAllam** [MessageKit/MessageKit#1044]

**Comment by AhmedMohamedAllam** [comment]
<img width="547" alt="Screen Shot 2019-04-07 at 9 44 53 PM" src="https://user-images.githubusercontent.com/15079215/55688954-0b7d7200-597f-11e9-9200-0990e6182a47.png">

**Comment by nathantannar4** [comment]
What value are you using for `MediaItem.size` that your message conforms too? You need to tell it what dimensions you want. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
