### ISSUE TITLE
How to change sendButton frame?

### ISSUE THREAD

**Issue by wongzigii** [MessageKit/MessageKit#1049]
Is there any way to change sendButton's frame to make

sendButton's centerY == inputTextView.centerY ?

![image](https://user-images.githubusercontent.com/7384288/55949609-91eaca00-5c85-11e9-9b42-d835c52f8f94.png)

FYI: I've tried resizing its frame in the configure closure, but it still not works.

**Comment by nathantannar4** [comment]
You need to set the size so that it's at least as tall as your text view with no text. `sendbutton.setSize(..)`
Note that if you want to make it wider, you will also need to increase the width of the right stack view

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wongzigii** [comment]
@nathantannar4 I want to keep the origin sendButton size and move it a little bit upper to make their centerYs equal.

**Comment by nathantannar4** [comment]
@wongzigii try setting the right stack view to have a .vertical axis and then

`setStackViewItems([messageInputBar.sendButton, .fixedSpace(18)], forStack: .right, animated: false)`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wongzigii** [comment]
@nathantannar4 setting .vertical will cause the stack's height *grow* as well as input text view. :(

![image](https://user-images.githubusercontent.com/7384288/56023974-a68c9800-5d41-11e9-9838-84c9d50984cd.png)

Is there any property to set the max height of the stackview?

**Comment by nathantannar4** [comment]
@wongzigii you just have to add the height constraint yourself. It needs to be the total height of the button and your spacing. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by braindrain92** [comment]
I had this same issue. You can create a subview with a button and add it to the messageInputBar. This is my code:

        ```
let myBtnView = UIButton(type: .custom)
        myBtnView.frame = CGRect(x: 329, y: 12, width: 30, height: 30)
        myBtnView.backgroundColor = .green
        myBtnView.setImage(UIImage(named:"name_here"), for: .normal)
        myBtnView.imageView?.contentMode = .scaleAspectFit
        myBtnView.makeCircle()
        myBtnView.imageEdgeInsets = UIEdgeInsets(top: 5, left: 5, bottom: 5, right: 5)
        myBtnView.addTarget(self, action: #selector(func_here), for: .touchUpInside)
        messageInputBar.addSubview(myBtnView)
```

**Comment by FelixFalkovsky** [comment]
`//MARK: Send Button

    func configureMessageInputBar() {
        messageInputBar.delegate = self
        messageInputBar.inputTextView.tintColor = .black
        messageInputBar.sendButton.backgroundColor = .blue
        messageInputBar.sendButton.title = "Senden"
        messageInputBar.sendButton.setTitleColor(.black, for: .normal)
        messageInputBar.sendButton.setSize(CGSize(width: 120, height: 36), animated: false)
        messageInputBar.setRightStackViewWidthConstant(to: 120.0, animated: false)  <- size
        messageInputBar.sendButton.setTitleColor(
            UIColor.black.withAlphaComponent(0.3),
            for: .highlighted
        )
    }`
