### ISSUE TITLE
Can you change the play icon in the videos?

### ISSUE THREAD

**Issue by blinkuz** [MessageKit/MessageKit#1051]
- What version of MessageKit are you using?
2.0
- What version of iOS are you running on?
12
- What version of Swift are you running on?
4.2
- What device(s) are you testing on? Are these simulators?
Iphone 6
- Is the issue you're experiencing reproducable in the example app?
yes

Is it possible to change the play button in the videos? for example, a download or loading icon.

Check the examples and I did not find anything related to the topic.

**Comment by nathantannar4** [comment]
You would have to override `cellForRowAt` and try to capture the cell when the message kind is a media item. Then you could make some changes. 

Else you would have to implement a subclass of the cell and in `cellForRowAt` return your custom cell for videos. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by blinkuz** [comment]
But the property of the play is created programmatically or is it an image? I ask it to know what to do after having captured the cell of the video type since it has been difficult for me to create the custom cells.

**Comment by nathantannar4** [comment]
I believe it is an image. It's all open source so you can check it out I'm sure that would answer more questions like that 😀

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by daniv3r** [comment]
@blinkuz Hi!
Do you have a solution?
