### ISSUE TITLE
LeftStackView displays elements differently after presenting UIAlertController.

### ISSUE THREAD

**Issue by pikor** [MessageKit/MessageKit#1052]
- What version of MessageKit are you using?
2.0.0. I also tested and this issue occurs on 3.0.0-beta-swift4-2

- What version of iOS are you running on?
12.1
- What version of Swift are you running on?
4.2
- What device(s) are you testing on? Are these simulators?
XR, simulator.
XS, device.
- Is the issue you're experiencing reproducable in the example app?
Yes, in both 2.0.0 and 3.0.0-beta-swift4-2 versions.

Take a look at position of `leftStackView` especially how far it is from text input.
![before](https://user-images.githubusercontent.com/5917582/56196513-421a5300-6037-11e9-81cb-0445b3050602.png)

Now if I present some alert after clicking on `leftStackView` item
![alert](https://user-images.githubusercontent.com/5917582/56196551-552d2300-6037-11e9-8824-3610c0790c4a.png)

then after dismissing that alert, `leftItemStackView` is noticeably closer to the text field.
![after](https://user-images.githubusercontent.com/5917582/56196631-7e4db380-6037-11e9-801c-1a04587291bf.png)

Screenshots are from version 3.0.0-beta-swift4-2. Almost the same happens on 2.0.0, but  it seems to me that only rightmost element is moved towards the text field.

This is how I set up left items in example app

```
      func configureMessageInputBar() {
        messageInputBar.delegate = self
        messageInputBar.inputTextView.tintColor = .primaryColor
        messageInputBar.sendButton.tintColor = .primaryColor
        configureLeftItems()
    }
    
    private func configureLeftItems() {
        let menuItems = items.map { makeButton($0) }
        messageInputBar.setStackViewItems(menuItems, forStack: .left, animated: false)
        messageInputBar.setLeftStackViewWidthConstant(to: (leftItemsViewWidth), animated: true)
    }

    private func makeButton(_ item: XXInputItem) -> InputBarButtonItem {
        return InputBarButtonItem()
            .configure {
                $0.sizeToFit()
                $0.spacing = .fixed(spacingBetweenItems)
                $0.image = item.image()
                $0.tintColor = item.colour()
                $0.setSize(CGSize(width: defaultItemSize, height: defaultItemSize), animated: false)
                $0.backgroundColor = .clear
            }.onTouchUpInside { [weak self] _ in
                let alert = UIAlertController(title: "👋", message: "👩‍💻", preferredStyle: .alert)
                let okAction = UIAlertAction(title: "OK", style: .destructive, handler: { _ in
                    self?.dismiss(animated: true, completion: nil)
                })
                alert.addAction(okAction)
                self?.present(alert, animated: true, completion: nil)
            }
    }
```

`XXInputItem` is just simple enum that allows me to make items easier
```
enum XXInputItem {
    case gallery
    case location
    case camera
    
    func image() -> UIImage {
        switch self {
        case .gallery :
            return #imageLiteral(resourceName: "ic_appstore")
        case .location:
            return#imageLiteral(resourceName: "ic_at")
        case .camera:
            return #imageLiteral(resourceName: "ic_hashtag")
        }
    }
}
```

Before posting this issue I tried to debug it, but without luck unfortunately. Despite `messageInputBar` is of type `InputBarAccessoryView` neither my `print("here's something useful")` nor breakpoints worked. And the view debugger wasn't helpful either, so I didn't manage to compare properties of `leftStackView`.

<img width="429" alt="Zrzut ekranu 2019-04-16 o 11 19 13" src="https://user-images.githubusercontent.com/5917582/56197649-8c9ccf00-6039-11e9-90bc-9d1c69dcdee5.png">

Let me know if I can help somehow with fixing this issue, and thank you for your work, MessageKit is a great library!

**Comment by nathantannar4** [comment]
@pikor Sorry I'm having trouble noticing where the difference is. Can you please attach a focused side by side comparison showing where the difference is?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lpbaptista** [comment]
@nathantannar4 the icons appear to have a different padding/margin after the pop-up is dismissed.
![Screen Shot 2019-05-03 at 00 27 03](https://user-images.githubusercontent.com/5098853/57112944-42566600-6d3a-11e9-8111-db714e55db47.png)
![Screen Shot 2019-05-03 at 00 27 12](https://user-images.githubusercontent.com/5098853/57112945-42eefc80-6d3a-11e9-8624-14e2e7ccabd3.png)

**Comment by nathantannar4** [comment]
Try removing your `sizeToFit` call, that shouldn't be there 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pikor** [comment]
@nathantannar4 thank you for your suggestion and sorry for replying after few days. I did what you've suggested and I removed `sizeToFit`. So the code that creates a button is as follows:

```
    private func makeButton(named: String) -> InputBarButtonItem {
        return InputBarButtonItem()
            .configure {
                $0.spacing = .fixed(10)
                $0.image = UIImage(named: named)?.withRenderingMode(.alwaysTemplate)
                $0.setSize(CGSize(width: 25, height: 25), animated: false)
                $0.tintColor = UIColor(white: 0.8, alpha: 1)
            }.onSelected {
                $0.tintColor = .primaryColor
            }.onDeselected {
                $0.tintColor = UIColor(white: 0.8, alpha: 1)
            }.onTouchUpInside { _ in
                print("Item Tapped")
        }
    }
```
![inputBarItems](https://user-images.githubusercontent.com/5917582/57220275-f71eaa80-6ffa-11e9-92af-5d93d124b389.png)
Any hints how to debug this issue?

**Comment by nathantannar4** [comment]
Hmm, @pikor what are you setting the "LeftStackViewWidthConstant" to? I tried to reproduce but no luck when I use 3 items of size 25x25 and a width constant of 105 (since 10 spacing each = 30 pt extra)

**Comment by nathantannar4** [comment]
Also, in your `configureLeftItems` you shouldn't animate the constant setting since its probably in `viewDidLoad`

**Comment by pikor** [comment]
@nathantannar4 thank you! What helped me was setting animated to `false` in `        messageInputBar.setLeftStackViewWidthConstant(to: (leftItemsViewWidth), animated: true)`
and setting `spacing = .fixed(spacingBetweenItems)` in `InputBarButtonItem` to 0. I notice that if it's bigger than 0, Auto Layout complains that width constraint is ambiguous. Setting to 0 solved that problem of icon changing its position.
