### ISSUE TITLE
How do you assign the Send action to a UIButton?

### ISSUE THREAD

**Issue by braindrain92** [MessageKit/MessageKit#1053]
How can you assign the send function from the SendButton to another button?

**Comment by braindrain92** [comment]
Answering my own question for others. I created a UIButton and added it to the inputBar as a subview. Here is the code I used to create the button:

>         let mySendBtn = UIButton(type: .custom)
>         mySendBtn.frame = CGRect(x: 329, y: 12, width: 30, height: 30)
>         mySendBtn.backgroundColor = .grey
>         mySendBtn.setImage(UIImage(named:"Push"), for: .normal)
>         mySendBtn.imageView?.contentMode = .scaleAspectFit
>         mySendBtn.makeCircle()
>         mySendBtn.imageEdgeInsets = UIEdgeInsets(top: 5, left: 5, bottom: 5, right: 5)
>         mySendBtn.addTarget(self, action: #selector(sendPressed(sender:)), for: .touchUpInside)
>         messageInputBar.addSubview(mySendBtn)
> 
>     @objc func sendPressed(sender: UIButton) {
>         sender.backgroundColor = ColorPresets.appleSendBlue
>         messagesCollectionView.scrollToBottom()
> 
>         // add send func here
>         messageInputBar.didSelectSendButton()
>     }

**Comment by nathantannar4** [comment]
@braindrain92 any specific reason you decided against using an InputBarButtonItem and placing it in an InputStackView?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by braindrain92** [comment]
Great question. I was having issues centering the InputBarButton inside the textfield, so I added the button as a subview and set the location using .frame.

**Comment by nathantannar4** [comment]
@braindrain92 try https://github.com/nathantannar4/InputBarAccessoryView/blob/master/Example/Example/InputBarExamples/iMessageInputBar.swift

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
