### ISSUE TITLE
Add padding to inputTextView?

### ISSUE THREAD

**Issue by braindrain92** [MessageKit/MessageKit#1054]
How can you add insets / padding to the messageInputBar.inputTextView?

Typically for a UITextField you can do something like: 
`let paddingView = UIView(frame: CGRectMake(0, 0, 15, self.myTextField.frame.height))
myTextField.leftView = paddingView;
myTextField.leftViewMode = UITextFieldViewMode.Always`

inputTextView does not have .leftView or .leftViewMode. What is the best way to add padding?

**Comment by nathantannar4** [comment]
It it a UITextView subclass so it has `textContainerInset` to apply inner padding 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by braindrain92** [comment]
Thanks, Nathan!
