### ISSUE TITLE
How to get touch on buttons created within a custom cell?

### ISSUE THREAD

**Issue by blinkuz** [MessageKit/MessageKit#1055]
What version of MessageKit are you using?
2.0
What version of iOS are you running on?
12
What version of Swift are you running on?
4.2
What device(s) are you testing on? Are these simulators?
Iphone 6
Is the issue you're experiencing reproducable in the example app?
yes

I just created a custom cell in a xib with 2 buttons, each of them must perform an action taking data from my message model but I can not find a way to detect the touch in each of them and execute X action using the same indexPath .

Search through the list of issues but I found nothing about the subject.

**Comment by nathantannar4** [comment]
With 3.0.0 you can override the touch behavior of a cell, have you tried doing that?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by blinkuz** [comment]
I have not tried yet, leave a little aside the development of the app chat but I'll go back to it again thanks for informing

**Comment by vincenzo-favara** [comment]
Any update here?, I created an issue, please have a look: https://github.com/MessageKit/MessageKit/issues/1227
