### ISSUE TITLE
How to Create Document Download Bubble.

### ISSUE THREAD

**Issue by jayanpatidar** [MessageKit/MessageKit#1057]
i want to make document download bubble in chatting.

I have to use custom cell by subclassing MessageContentCell because we need the same layout for all message type. but in git example they use existing message types(i.e text, location ex.) and for custom cell they provide a solution by creating via UICollectionView cell but in this solution need to add other view (avatar, time)
```
import UIKit
import MessageKit

class FileMessageCell: MessageContentCell {
    open var fileName = UILabel()
    open var fileSize = UILabel()
    open var downloadButton = UIButton()
    open var stackView = UIStackView()
    let view = UIView()
    
    open override func setupSubviews() {
        super.setupSubviews()
        self.messageTopLabel.isHidden = true
        setupConstraints()
    }
    
    /// Responsible for setting up the constraints of the cell's subviews.
    open func setupConstraints() {
        _fillSuperview()
    }
    func _fillSuperview() {
   
        fileName.text = "Fitness Test Result.pdf"
        downloadButton.setTitle("Download", for: .normal)
        fileSize.text = "1.02 mb"
        
        fileName.textColor = .white
        fileSize.textColor = .white
        fileName.font = UIFont.systemFont(ofSize: 16, weight: UIFont.Weight(rawValue: 4))
        fileSize.font = UIFont.systemFont(ofSize: 16)
        downloadButton.backgroundColor = .primaryColor
        
        self.stackView.addArrangedSubview(fileName)
        self.stackView.addArrangedSubview(fileSize)
        self.stackView.addArrangedSubview(downloadButton)
        self.stackView.alignment = .fill
        self.stackView.axis = .vertical
        self.stackView.spacing = 10
        self.stackView.distribution = .fillProportionally
        stackView.isLayoutMarginsRelativeArrangement = true
        stackView.directionalLayoutMargins = NSDirectionalEdgeInsets(top: 0, leading: 20, bottom: 0, trailing: 20)
        
        messageContainerView.translatesAutoresizingMaskIntoConstraints = false
        messageContainerView.addSubview(view)
        
        view.backgroundColor = .primaryColor
        view.translatesAutoresizingMaskIntoConstraints = false
        
        messageContainerView.leadingAnchor.constraint(equalTo: contentView.leadingAnchor,
                                      constant: 0).isActive = true
        messageContainerView.trailingAnchor.constraint(equalTo: contentView.trailingAnchor,
                                       constant: 0).isActive = true
        messageContainerView.bottomAnchor.constraint(equalTo: contentView.bottomAnchor,
                                     constant: 0).isActive = true
        messageContainerView.topAnchor.constraint(equalTo: contentView.topAnchor,
                                                     constant: 0).isActive = true
        messageContainerView.backgroundColor = .red
        
        addConstaints(leadingOffset: 0, trailingOffset: 0, bottomOffset: 0)
        
    }
    
    func addConstaints(leadingOffset: CGFloat, trailingOffset: CGFloat, bottomOffset: CGFloat) {
        
        view.backgroundColor = .primaryColor
        view.translatesAutoresizingMaskIntoConstraints = false
        
        view.leadingAnchor.constraint(equalTo: messageContainerView.leadingAnchor,
                                      constant: leadingOffset).isActive = true
        
        view.trailingAnchor.constraint(equalTo: messageContainerView.trailingAnchor,
                                       constant: trailingOffset).isActive = true
        view.bottomAnchor.constraint(equalTo: messageContainerView.bottomAnchor,
                                     constant: bottomOffset).isActive = true
        view.heightAnchor.constraint(equalToConstant: 90).isActive = true
        view.addSubview(self.stackView)
        
        self.stackView.translatesAutoresizingMaskIntoConstraints = false
        self.stackView.leadingAnchor.constraint(equalTo: view.leadingAnchor,
                                                constant: 0).isActive = true
        self.stackView.trailingAnchor.constraint(equalTo: view.trailingAnchor,
                                                 constant: 0).isActive = true
        self.stackView.centerYAnchor.constraint(equalTo: view.centerYAnchor,
                                                constant: 0).isActive = true
    }
    
    func addConstaints(height: CGFloat, width: CGFloat) {
        heightAnchor.constraint(equalToConstant: height).isActive = true
        widthAnchor.constraint(equalToConstant: width).isActive = true
    }
}
```
when i use subclassing MessageContentCell and make custom MessageType MockMessage and make all properties for that but not showing the bubble and inside content only i can see is the avatar image when reload the CollectionView.

and i am using Custom cell that is subclassing of UICollectionViewCell that also not make proper chat bubble for document download.

**Comment by nathantannar4** [comment]
@bellway where are you adding your new cell's subviews to the cell's view?

**Comment by jayanpatidar** [comment]
1. Add Properties for labels, button, stakview & UIView.
2. Overrride function *func setupSubviews()* and inside this function i calling *func setupConstraints()* and inside this fuction calling *func _fillSuperview()*.
3. in function *func _fillSuperview()* provide size, text and etc things on button and labels than all label & button are added on a SatckView and that StackView add on UIview in *func addConstaints(leadingOffset: CGFloat, trailingOffset: CGFloat, bottomOffset: CGFloat)*.
4. and that view hold all properties is added on  *messageContainerView* in *func _fillSuperview()*.
5. that messageContainerView is not generate on cell, thats why inside added view, label & button are not showing on cell .
```
    func _fillSuperview() {
   
        fileName.text = "Fitness Test Result.pdf"
        downloadButton.setTitle("Download", for: .normal)
        fileSize.text = "1.02 mb"
        
        .....
        .....
        //1. added properties on stack view.
        self.stackView.addArrangedSubview(fileName)
        self.stackView.addArrangedSubview(fileSize)
        self.stackView.addArrangedSubview(downloadButton)

        .....
        .....
        
     //3. Add UIView on messageContainerView.
        messageContainerView.translatesAutoresizingMaskIntoConstraints = false
        messageContainerView.addSubview(view)
        
        .....
        .....
        
        addConstaints(leadingOffset: 0, trailingOffset: 0, bottomOffset: 0)
        
    }
    
    func addConstaints(leadingOffset: CGFloat, trailingOffset: CGFloat, bottomOffset: CGFloat) {
        
        .....
        .....
       // 2. add stackview on UIView.
        view.heightAnchor.constraint(equalToConstant: 90).isActive = true
        view.addSubview(self.stackView)

        .....
        .....
    }

 ```

**Call cell on collection view to show custom kind messages(file download bubble).**

```
public override func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        
        guard let messagesDataSource = messagesCollectionView.messagesDataSource else {
            fatalError("Ouch. nil data source for messages")
        }

        let message = messagesDataSource.messageForItem(at: indexPath, in: messagesCollectionView)
        // Call FileMessageCell  for custom kind message to show on collection view. 
        if case .custom = message.kind {
            
            let cell = messagesCollectionView.dequeueReusableCell(FileMessageCell.self, for: indexPath)
            cell.configure(with: message, at: indexPath, and: messagesCollectionView)
            return cell
        } 

     ......
     ......
        guard  let cell = super.collectionView(collectionView, cellForItemAt: indexPath) as? MessageContentCell else {
            fatalError("Ouch. nil data source for messages")
        }
        ........
       ......
        return cell
    }
```

Note:- check commented statements for refrence

**Comment by nathantannar4** [comment]
From what I can see it looks like you are adding constraints incorrectly. Never is messageContainerView given constraints and you should not be putting a constraints on the cell itself. 

You should start over and only change a few things at a time, verify it works correctly before moving on.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jayanpatidar** [comment]
@nathantannar4 **i do not think it's a constraints issue if i just add the property without constraints and just provide the frame than should show messageContainerView and properties inside it in the cell but  messageContainerView  is not generate on cell i can show you in view hierarchy when show custom kind message in UICollectionView **


![Screenshot 2019-04-26 at 10 13 03 AM](httpss://user-images.githubusercontent.com/47847659/56784027-39cad080-680c-11e9-8182-981a4ffabb8e.png)

**in this picture you can see messageContainerView not generate because this cell is call when message kind is type custom.**


![Screenshot 2019-04-26 at 10 13 21 AM](httpss://user-images.githubusercontent.com/47847659/56784030-3cc5c100-680c-11e9-814b-41dce1ee9fcc.png)


**and look when message kind in location, photo or Video than i get the messageContainerView on cell.**


![Screenshot 2019-04-26 at 10 12 36 AM](httpss://user-images.githubusercontent.com/47847659/56784395-de99dd80-680d-11e9-8942-8eb47ff672ef.png)
![Screenshot 2019-04-26 at 10 12 25 AM](httpss://user-images.githubusercontent.com/47847659/56784398-e063a100-680d-11e9-86fe-d69bde462d7d.png)

**and in your MessageContentCell.swift file you write this comment, so can i make my custom bubble with subclassing with MessageContentCell ? if yes than how can i make?, if no, than any other solution for this?**.
```
   /// A subclass of `MessageCollectionViewCell` used to display text, media, and location messages.
open class MessageContentCell: MessageCollectionViewCell {...}
```

**so i just want to know how can i make download file type bubble. 
only for reference see this image bubble ui maybe changed according to requirement.**

![Screenshot 2019-04-26 at 10 40 28 AM](httpss://user-images.githubusercontent.com/47847659/56784773-dd69b000-680f-11e9-9b52-804f792ceb0c.png)

**Comment by nathantannar4** [comment]
@bellway when using custom cells you are responsible for all of the layout. The messageContainerView will not layout on its own. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
