### ISSUE TITLE
becomeFirstResponder() not being called

### ISSUE THREAD

**Issue by braindrain92** [MessageKit/MessageKit#1059]
Using the latest version of MessageKit, Xcode, and Swift. I am having trouble calling         becomeFirstResponder() in the MessageKit Example project. 

I have tried adding becomeFirstResponder() to the viewDidAppear() of ChatViewController and MessagesViewController to no success. 

Is anyone else having this issue, and is there a fix?

**Comment by AlexeyShevchenko** [comment]
if you're about showing keyboard try this one:
```
override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)
    
    messageInputBar.inputTextView.becomeFirstResponder()
}
```

**Comment by braindrain92** [comment]
Ugh. No luck. Is it working in your MessageKit Example project?

**Comment by nathantannar4** [comment]
Do you have your simulator connected to your hardware keyboard? becomeFirstResponder returns a bool, have you checked what it returns? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
