### ISSUE TITLE
Input bar recursively sets text/calculates size of its height of its inputTextView when truncated to its text count.

### ISSUE THREAD

**Issue by whoyawn** [MessageKit/MessageKit#1061]
- What version of MessageKit are you using? 2.0.0 and 3.0.0 beta
- What version of iOS are you running on? iOS 12.2
- What version of Swift are you running on? 4.2
- What device(s) are you testing on? Are these simulators? iPhone XR Simulator + Device
- Is the issue you're experiencing reproducible in the example app? Yes

```swift
// MARK: - MessageInputBarDelegate/InputBarAccessoryViewDelegate

     func inputBar(_ inputBar: InputBarAccessoryView, textViewTextDidChangeTo text: String) {
        print(text.count)
        if text.count >= 10 {
            inputBar.inputTextView.text = String(text.prefix(10)) // or anything greater than 10
        }
    }
```

Console at the if statement:
```
10
10
10
10
10
10
...
```

Crashes here:
```swift
// InputBarAccessoryView.swift in 3.0.0 beta and MessageInputBar.swift in 2.0.0
    public var requiredInputTextViewHeight: CGFloat {
        guard middleContentView == inputTextView else {
            return middleContentView?.intrinsicContentSize.height ?? 0
        }
        let maxTextViewSize = CGSize(width: inputTextView.bounds.width, height: .greatestFiniteMagnitude)
        return inputTextView.sizeThatFits(maxTextViewSize).height.rounded(.down) // EXC_BAD_ACCESS
    }
```

When I set the string to its substring of its current count (or higher), the text box tries to calculate the text view's size, then crashes.

Using this string API also crashes if we keep constantly typing as it truncates:

```
...
let index = text.index(text.startIndex, offsetBy: 10)
let mySubstring = text[..<index]
inputBar.inputTextView.text = String(mySubstring)
```

If we truncate the text to a number that is lower that its current count, it does not crash. Anything at the count and higher leads to a crash.

**Comment by nathantannar4** [comment]
@whoyawn If you change the text in `textViewTextDidChangeTo` it will cause `textViewTextDidChangeTo` to fire again, and then since you keep changing it to the same thing you are creating an infinite loop. I believe the bug would be the infinite loop you create. 

For comparison, that's like calling `UITableView.reloadData()` inside one of your `UITableViewDataSource` methods. Your phone quickly runs out of memory
