### ISSUE TITLE
*private* var layoutManager in MessageLabel.

### ISSUE THREAD

**Issue by or-else** [MessageKit/MessageKit#1062]
Is there a particular reason why `layoutManager` in `MessageLabel` is declared `private`?

https://github.com/MessageKit/MessageKit/blob/master/Sources/Views/MessageLabel.swift#L31

My message content is `NSAttrubutedString` which sometimes has a custom attribute. The attribute requires overriding text container's layout manager for proper display. It seems like the only way for me to show the text is to create a custom view and an almost verbatim copy of MessageLabel.swift just to get access to `layoutManager`.

What is the problem that MessageKit authors are solving by declaring `layoutManager` private? 

Thanks!

**Comment by nathantannar4** [comment]
Much like `UILabel` where you cannot modify the `layoutManager` we followed that same pattern. It's not that it solves a problem but more prevents unintended use.

> For example, we allow modification, you use custom attributes which effects the calculated layout size of the message bubble and then file a bug with us stating that its calculating the size incorrectly. 

What attribute are you needing to modify to get the display you want?

**Comment by or-else** [comment]
I need text to appear as a button, i.e. I need background with rounded corners.

**Comment by or-else** [comment]
> Much like UILabel where you cannot modify the layoutManager we followed that same pattern

You subclassed UILabel and added layoutManager because you probably found the stock UILabel deficient in this particular respect. So, I suppose, you disagreed with Apple's pattern?

**Comment by nathantannar4** [comment]
No it was for performance reasons. 

What layout property would you need to changes? For those they are just attributed string attributes

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by or-else** [comment]
My layout manager overrides `drawBackground(forGlyphRange glyphsToShow: NSRange, at origin: CGPoint)`. And I need to use that custom layout manager instead of the stock one.

**Comment by or-else** [comment]
Re: performance - it's declared `lazy`, how does it affect performance if it's not called?

**Comment by nathantannar4** [comment]
If you have a layout manager that overrides a draw function then it being public wouldn't help your situation. I think the correct approach is would be to override the text message cell returned for attributed string message kinds. 

Lazy has nothing to do with the performance boosts, it allows us to control rendering more finely. See the class and you'll see why. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by or-else** [comment]
> If you have a layout manager that overrides a draw function then it being public wouldn't help your situation.

Why not? If there were a public setter it most certainly would.

> override the text message cell returned for attributed string message kinds

Yes, and it would require copy-pasting a lot of code. Which is what I'm trying to avoid.

> Lazy has nothing to do with the performance boosts, it allows us to control rendering more finely

I don't understand what you mean.

**Comment by nathantannar4** [comment]
> Why not? If there were a public setter it most certainly would.

You would have to set this every time in `cellForRowAt` before returning the cell which would be very inefficient. 

I am sorry but you are going to need to subclass the cell and return your subclassed version. The idea of keeping it private is to prevent unintended modifications that would break the layout. I don't think that is a very big ask for the kind of customization you want.

**Comment by or-else** [comment]
Ok, thanks.
