### ISSUE TITLE
add view for new message 

### ISSUE THREAD

**Issue by shireeshMs** [MessageKit/MessageKit#1064]

**Comment by shireeshMs** [comment]
Hello,
I want to add a view or button that should tell me that i have recieved new message .
Please let me know how to do 
I am sharing screenshot that might help my requirement to get uderstood 

![IMG_2726](https://user-images.githubusercontent.com/37240061/57058794-70529080-6ccf-11e9-85af-7ca4267b5e9e.jpg)

As in the above screenshot we can see there are 188 newly message came in chat ,this is the same thing i wanted to implement

**Comment by nathantannar4** [comment]
I would add a subview to the view controllers view that is in front of the MessagesCollectionView. As for the finer details, it's up to you to determine how to implement it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
