### ISSUE TITLE
Swipe in a bubble like whatsapp to reply a message

### ISSUE THREAD

**Issue by jordigallenmediquo** [MessageKit/MessageKit#1065]
Hi guys,

Is it possible to answer another message like Whatsap does in IOS? 
In other words, doing a lateral “swipe” on the bubble message we want to answer? 
Basically what I want is:
- Make the lateral displacement of the message cell with animation. how does Whatshap
- And then insert a header to the input bar with a view of the message that we are answering.
Basically the behavior that Whatshap does.

This video shows what I want to develop:

https://youtu.be/DgsYAJtz74U?t=136

Thanks :)

**Comment by nathantannar4** [comment]
I would attempt something like that with the following:
1. You need to add some gesture recognizers to each cell so you could transform the view left/right to slide the cell. 
2. Make some container view that can hold the swiped message and put it in the top stack view (this part is pretty easy)

That's a high level approach that you could take. Allowing cells to be swiped is the more challenging part.

Open to collaborating and working it into MessageKit as a feature if you can get a prototype working

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fukemy** [comment]
if u want to develope this feature, u need register your custom gesture in 
```
public override func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> 
```

look like i did:
```
let cell = super.collectionView(collectionView, cellForItemAt: indexPath) as! MessageContentCell
        let panGestureRecognizer = UIPanGestureRecognizer(target: self, action: #selector(panGestureCellAction))
        panGestureRecognizer.delegate = self
        cell.contentView.addGestureRecognizer(panGestureRecognizer)
        cell.messageTimestampLabel.isHidden = false
        reconfigSeenUser(messageList[indexPath.section], cell)
        return cell
```
