### ISSUE TITLE
Typing indicator documentation

### ISSUE THREAD

**Issue by NTruchaud** [MessageKit/MessageKit#1066]
- What version of MessageKit are you using?
3.0.0-beta-swift4-2
- What version of Swift are you running on?
Swift 4.2
- What device(s) are you testing on? Are these simulators?
iPhone 8

Hi there,
First of all, thank you a lot for your great work.
I just wanted to know if there were any documentation on how to implement the typing indicator in swift.

Thanks you !

**Comment by nathantannar4** [comment]
@NTruchaud did you find information that helped you? I do have the source code documented but I dont have an additional *.md file.

**Comment by NTruchaud** [comment]
I found what I needed in the example, thank you for your answer :) If anyone need help just tell me I'll share some code !

**Comment by seable-cmcy** [comment]
@NTruchaud can you share your code with the typing indicator? It would help a lot

**Comment by hovermind** [comment]
@NTruchaud  Share the code, as you promised

**Comment by cpellet** [comment]
I've been using this, hope it helps someone
![image](https://user-images.githubusercontent.com/18552249/81069415-2142cb00-8ee2-11ea-8683-d723bc7d6756.png)

**Comment by ensenyourit** [comment]
> I found what I needed in the example, thank you for your answer :) If anyone need help just tell me I'll share some code !

Can you share code with me ?
