### ISSUE TITLE
how can change messageInputBar semanticContentAttribute to support forceRightToLeft for Arabic language 

### ISSUE THREAD

**Issue by HagerGamal95** [MessageKit/MessageKit#1068]

**Comment by HagerGamal95** [comment]
Dear all , 
I want to change semanticContentAttribute to support Arabic language so I did that :
1 - in AppDelegate :  
       UIView.appearance().semanticContentAttribute = .forceRightToLeft
2 - in configureMessageInputBar function  :  
       messageInputBar.semanticContentAttribute = .forceRightToLeft

nothing of those work to change messageInputBar direction

**Comment by nathantannar4** [comment]
@HagerGamal95 
// RTL Support
```swift
messageInputBar.inputTextView.textAlignment = .right
messageInputBar.inputTextView.placeholderLabel.textAlignment = .right
```
You will need to adjust the send button to the opposite stack view as well if thats what you would like/

**Comment by HagerGamal95** [comment]
@nathantannar4  thanks for replay 👍 
yes I need to adjust the send button to the opposite stack view as you said I did that : 
 messageInputBar.setStackViewItems([messageInputBar.sendButton], forStack: .left, animated: false)
the send button disappeared , how can I adjust the "messageInputBar.inputTextView" to the right ??

**Comment by HagerGamal95** [comment]
### here is my code : 
![Screen Shot 2019-05-09 at 2 47 24 AM](https://user-images.githubusercontent.com/36477659/57419973-551ede00-7205-11e9-807a-474f7ee9b54b.png)
### the result : 
### 1- placeholder textAlignment didn't flip to right 
### 2 - send button disappeared
![Simulator Screen Shot - iPhone XR - 2019-05-09 at 02 49 02](https://user-images.githubusercontent.com/36477659/57420071-edb55e00-7205-11e9-95cd-6b5ee8e98740.png)

**Comment by nathantannar4** [comment]
You need to set the width constant of each stack view. `setLeftStackViewWidthConstant`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by HagerGamal95** [comment]
@nathantannar4 thank you this worked for me but still i have a problem in : 
messageInputBar.inputTextView.placeholderLabel.textAlignment = .right
 the placeholder textAlignment didn't flip to right

**Comment by nathantannar4** [comment]
Are you on v3.0.0? I'm not sure if MessageInputBar, used in 2.0.0, has RTL. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by HagerGamal95** [comment]
![Screen Shot 2019-05-11 at 8 12 08 PM](https://user-images.githubusercontent.com/36477659/57573520-1b2e2180-7429-11e9-8fe2-8e1603a3b5e1.png)
yes , i'm still stuck in this problem 
also I tried to make the width of label for placeholder equal the width of inputTextView but it didn't work still label wrapped in it's content 
 
![Simulator Screen Shot - iPhone XR - 2019-05-11 at 20 16 51](https://user-images.githubusercontent.com/36477659/57573556-c4751780-7429-11e9-968a-b5b572cc6a5f.png)

**Comment by nathantannar4** [comment]
Are you using the autocomplete manager?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
