### ISSUE TITLE
Bubbles aren't showing for Swift 5

### ISSUE THREAD

**Issue by ZaneH** [MessageKit/MessageKit#1072]
- What version of MessageKit are you using?
3.0.0-beta

- What version of iOS are you running on?
iOS 12.1.2

- What version of Swift are you running on?
Swift 5

- What device(s) are you testing on? Are these simulators?
iPhone XR simulator & a XR physical device

- Is the issue you're experiencing reproducable in the example app?
Unfortunately not 😢

In short; the bubbles simply aren't showing at all. I've implemented the following stubs:
```
avatarSize(for:at:in:)
backgroundColor(for:at:in:)
cellTopLabelAttributedText(for:at:)
currentSender()
footerViewSize(for:in:)
headerViewSize(for:in:)
heightForLocation(message:at:with:in:)
messageForItem(at:in:)
messageStyle(for:at:in)
numberOfSections(in:)
```

I've followed every tutorial that exists, I've side-by-side compared my code with the working example code, I've even done the normal sanity checks like making sure my Storyboard is actually using the MessagesViewController and that all of the delegates are set.

I imagine this has something to do with the 3.0.0 branch; but Idrk.

Let me know if there's anything else I can include. Thanks 🙏

EDIT: Here's my Podfile entry as well:
```
pod 'MessageKit', :git => 'https://github.com/MessageKit/MessageKit.git', :branch => '3.0.0-beta-swift5'
```

I've also tried
```
pod 'MessageKit', :git => 'https://github.com/MessageKit/MessageKit.git', :branch => '3.0.0-swift5'
```

**Comment by nathantannar4** [comment]
That sounds very strange! I will take a look when I have a free moment

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ZaneH** [comment]
Any update?

We're about to launch a beta tomorrow 😰

**Comment by ZaneH** [comment]
It was all my fault. Problem solved.

**Comment by nathantannar4** [comment]
@ZaneH what was it?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ZaneH** [comment]
###### my datasource

**Comment by nathantannar4** [comment]
Oh that's why I couldn't reproduce. I thought you meant the image asset for the bubble wasn't rendering so all you saw was text

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
