### ISSUE TITLE
Message InputBar Attachment Adding button plus functionality.

### ISSUE THREAD

**Issue by asn111** [MessageKit/MessageKit#1074]
- What version of MessageKit are you using?
v2.0
- What version of iOS are you running on?
v 12.1
- What version of Swift are you running on?
v 4.2
- What device(s) are you testing on? Are these simulators?
iphone 6
- Is the issue you're experiencing reproducible in the example app?
Its not an issue its more of a question.

Hi thank you guys for this awesome library, i have been using MessageKit since 3 months, now that my client wants to have images in messages, i don't find any thing in `InputBarAccessoryView` class. where i can add custom button for this or any default attachment button, would any of you care to guide me to how to complete this, thank you in advance.

**Comment by nathantannar4** [comment]
Your question is how to add a button to the input bar? Have you looked at the emaple project, there are numerous examples that could help you. You just need to and an `InputItem` to one of the stack views. You can also enable image paste support in the `InputTextView`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by asn111** [comment]
yes that is my question, and thank you for response, I had looked in to example project in [here](https://github.com/MessageKit/MessageKit) but doesn't found any thing, `InputItem` in `InputBarAccessoryView` right ?

**Comment by nathantannar4** [comment]
It's in the example project. Make sure your looking at the `InputBarAccessoryView` repo example. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by asn111** [comment]
oh my bad, I will look into that thanks for quick response. Appreciated.

**Comment by asn111** [comment]
Hi , need assistance please i am doing this to add a button on inputbar, but its not working, 
`        let button = InputBarButtonItem()
        button.setSize(CGSize(width: 36, height: 36), animated: false)
        button.setImage(#imageLiteral(resourceName: "camera").withRenderingMode(.alwaysTemplate), for: .normal)
        button.imageView?.contentMode = .scaleAspectFit
        button.tintColor = UIColor(red: 0, green: 122/255, blue: 1, alpha: 1)
        messageInputBar.setLeftStackViewWidthConstant(to: 36, animated: false)
        messageInputBar.setStackViewItems([button], forStack: .left, animated: true)
`

**Comment by asn111** [comment]
Hi I need some assistance,  i have managed to get the picture, but now how do i add this picture to the `inputBar` to send, not having any clue from Example proj also. :(
at this point
```
func inputBar(_ inputBar: InputBarAccessoryView, didPressSendButtonWith text: String) {
        self.sendRequestForPublishMessage(text)
        inputBar.inputTextView.text = ""
        messagesCollectionView.scrollToBottom(animated: true)
    }
```

**Comment by nathantannar4** [comment]
@asn111 Please take a look at the `InputTextView` source file.
Copy your image to the pasteboard, `UIPasteboard.general.image = myImage`
Then execute `paste()` on the `InputTextView`

**Comment by asn111** [comment]
i did got it on `InputBar` using `AttachmentManager`... the thing i am not understanding now is how to show this image in Chat screen. that has been sent. or even its coming from other end. Can't show the image its showing empty message for now.

**Comment by nathantannar4** [comment]
Well, you need to send the image to whichever backend you're using. To display media messages you should look at `MessageKind`.

**Comment by asn111** [comment]
Yes I saw `MessageKind` but how could i show this on Chat screen. right now i am doing something like this and its not working,
```
func configureMediaMessageImageView(_ imageView: UIImageView, for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) {
            switch message.kind {
            case .photo:
                let url = messages[indexPath.section].url
                imageView.sd_setImage(with: URL(string: url!))
                self.messagesCollectionView.reloadItems(at: [indexPath])
                break            
        default:break
        }
    }
```

**Comment by asn111** [comment]
here I am having crash at photo and no idea how to define this one, 
```
extension ChatMessageObject : MessageType {
    var sender: SenderType {
        //return
        return Sender(id: publisher, displayName: "")

    }
    var messageId: String {
        return ""
    }
    
    var sentDate: Date {
        return Date()
    }
    
    var kind: MessageKind {
        if type.contains("text") {
            return .text(message)
        }
        else if type.contains("image"){
            return .photo(imagee as! MediaItem)
        }
        else {
            return .text(url)
        }
    }  
}
```

**Comment by asn111** [comment]
I got that issue fixed, but now i am facing another one :(  
 height of inputBar remain increased plus no typing happening after sending image. 

![IMG_4989](https://user-images.githubusercontent.com/8926549/58240348-3e7b9980-7d64-11e9-89a1-2606bbcdbb0f.PNG)

**Comment by asn111** [comment]
Hi, i need to know also when I tap a message cell,  how can i detect what that message cell contains in it as data ?
