### ISSUE TITLE
Height of InputView

### ISSUE THREAD

**Issue by hhoangna** [MessageKit/MessageKit#1075]
I'm using ur lib on 6s, 7, iPhoneX and higher
When using InputView with keyboard height, 6s and 7 seem return match height but X and higher inputView height wrong? 
What matter with me? Help

**Comment by nathantannar4** [comment]
Sorry I don't understand what your asking. What do you mean return match height?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
