### ISSUE TITLE
Swipe to hide keyboard on IphoneXS Max

### ISSUE THREAD

**Issue by hhoangna** [MessageKit/MessageKit#1076]
On Iphone XS Max i found this bug. What happend? 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/26923574/58146072-c4251980-7c7e-11e9-8363-e4199a70a042.gif)

**Comment by nathantannar4** [comment]
What's the bug? I don't see the issue from your Gif. What's your expected result?


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hhoangna** [comment]
Hi @nathantannar4,
In my Gif, when I swipe down by move finger down slowly, keyboard stop at point like Gif and then iphone can't working anymore. And i using MessageInputBar

**Comment by nathantannar4** [comment]
@hhoangna How is that a bug? It's an InputAccessoryView that's how UIKit handles it with the scroll views keyboardDismissMode set to interactive

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hhoangna** [comment]
@nathantannar4 
I can not describe specifically for you to understand. You should download https://github.com/MessageKit/MessageInputBar source code and run it on XS Max. Then, you show keyboard and hide keyboard same my steps

**Comment by nathantannar4** [comment]
@hhoangna Are you using MessageKit v3? I am not supporting MessageInputBar as a dependency anymore. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hhoangna** [comment]
@nathantannar4 yup. I found you use https://github.com/nathantannar4/InputBarAccessoryView now. I will update this ver, thanks
