### ISSUE TITLE
No such module 'MessageInputBar'

### ISSUE THREAD

**Issue by mrminhhuy** [MessageKit/MessageKit#1077]
Hello all, i'm using MessageKit lib. But it's rise an error when build
"No such module 'MessageInputBar".

**Comment by bmt2018** [comment]
If you're using existing code and have updated to MessageKit 3.0, MessageInputBar has been replaced with InputBarAccessoryView.  See [here](https://github.com/MessageKit/MessageKit/releases/tag/3.0.0-beta-swift4-2) for more info.

**Comment by lordKaos11** [comment]
can you guys please explain the Inputbaraccessoryview

I tried to use older code and I updated to MessageKit 3.0

I cannot get this to work.  the send button when pressed does nothing

can we please get an example

**Comment by nathantannar4** [comment]
You should to re-type out the delegate methods (let it be done with autocomplete) to make sure it matches correctly 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lordKaos11** [comment]
I added an extension to my VC
------ myViewController: InputBarAccessoryViewDelegate

I added the didpresssendbuttonwith:

When text is entered into input bar and u press send nothing happens. 

In my pod I still have the messageInputBar
In my VC I imported MessageInputBar and InputBarAccessoeyview

Should I be adding something in viewdidliad?

I have literally tried everything I've seen online. been at this for almost 8 hours.

**Comment by mrminhhuy** [comment]
i used version MessageKit 2.0 to resolve this issue

**Comment by nathantannar4** [comment]
@huyvm that's not really a solution

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mrminhhuy** [comment]
@nathantannar4 because with old project, need use version 2.0. But, with new project use version 3.0, MessageInputBar with other branch
