### ISSUE TITLE
MessageInputBar animating down and disappearing when not fully popped from UINavigationController

### ISSUE THREAD

**Issue by haemi** [MessageKit/MessageKit#1078]
I'm using MessageKit 2.0 (but could also reproduce this on 3.0 beta) and iOS 12, Swift 4.2

It's reproducable on Simulator and device, but I can NOT reproduce this in the Example app. Maybe because my chat stack is inside a UITabBarController?

When I'm doing the swipe back gesture, the MessageInputBar navigates down (I already do not understand why, because this does not happen in the Example app as well) and when I undo this gesture (not popping, but stay on the chat detail), the MessageInputBar disappears completely.

I'm really thankful for every hint about what could cause this behavior. In my subclass I already commented out `viewWillAppear` and stuff like that, didn't help...

I also saw [this issue](https://github.com/MessageKit/MessageKit/issues/620) (`MessageInputBar dismissed when an alert is presented`) which may be related, but it didn't help me unfortunately...

![ezgif-1-7f35ff9ef9cb](https://user-images.githubusercontent.com/183958/58307281-7f27f100-7dfe-11e9-99c4-fdd6eba99904.gif)

**Comment by nathantannar4** [comment]
It looks like when you start dragging out, your Chat controller resigns the first responder and thus the input bar becomes hidden. How are you configuring your `UITabBarController`? Is it a custom subclass? I thought its something about that is preventing your Chat controller from regaining being the first responder

**Comment by leacode** [comment]
I have a similar issue.  
Just add a button to the sample code on the navigation bar. 
And then present whatever ViewController from the chatViewController.
The input bar will move down and disappear.
As a result, the offset of the collection view will change. 
All I want is not to have any affections when I present a ViewController from the MessageViewController.

**Comment by marcknock** [comment]
I had similar issues, mine is wrapped in a container view controller, so commenting out `func inputAccessoryView` fixes it, but obviously removes the input bar. In my case it is being presented in a UISplitViewController detail view, and in appearance it would cause all sort of strange animations in the message view, this fixed it: https://stackoverflow.com/questions/46690918/inputaccessoryview-appearing-with-animation-after-view-appears-in-ios

**Comment by sprzenus** [comment]
I have a similar bug but using UISplitViewController as the root view controller. It happens only on small devices in portrait screen orientation (detail view controller appears like in a UINavigationController) when you make the input bar first responder and then pop to the primary view controller in any way. It happens in simulator iPhone XR 12.2, Xcode 10.2.

**Comment by experion-tibin** [comment]
> It looks like when you start dragging out, your Chat controller resigns the first responder and thus the input bar becomes hidden. How are you configuring your `UITabBarController`? Is it a custom subclass? I thought its something about that is preventing your Chat controller from regaining being the first responder

Hi @nathantannar4 Could you provide elaborate  on how the Chat Controller can regain the first responder  
after presenting another VC?

**Comment by mlyongardiner** [comment]
@experion-tibin self.becomeFirstResponder() where necessary, possibly viewDidAppear
