### ISSUE TITLE
MessageInputBar is flying!

### ISSUE THREAD

**Issue by ZaneH** [MessageKit/MessageKit#1079]
- What version of MessageKit are you using?
3.0.0 (InputBarAccessoryView is 4.2.2)

- What version of iOS are you running on?
iOS 12.1.2

- What version of Swift are you running on?
Swift 4.2

- What device(s) are you testing on? Are these simulators?
Physical (iXR), and simulator.

- Is the issue you're experiencing reproducable in the example app?
No

I'm doing _nothing_ strange with the input bar. The only thing I can think of is that we're also using IQKeyboardManager (**but** we've already disabled it from the AppDelegate and still get this issue).

![demo](https://i.imgur.com/0ygJ1M2.gif)

I've also seen other people's issues where it's suggested to return true for `canBecomeFirstResponder`, but it doesn't change anything.

**Comment by nathantannar4** [comment]
I have seen that issue caused by IQKeyboardManager. But if you're positive it's disabled, I would say the issue could be related to the custom view controller container it looks like you're using. 

Try a native navigation controller push, or standard present and see if the problem persists. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ZaneH** [comment]
@nathantannar4 I've made sure that it wasn't IQKeyboardManager (kinda) by using the standard `present()` instead of `pushViewController()`– and it worked perfectly.

It appears that it has something to do with the navigation controller setup. The setup that I'm using _is_ actually a standard UINavigationController, however, we are using [Hero](https://github.com/HeroTransitions/Hero) as well, which has complicated our hierarchy.

Would you know anything about that?

**Comment by nathantannar4** [comment]
Are you creating a new controller each time you select a conversation? It seems like the controller is being reused and thus the final frame it's transitioning to is becoming smaller. I would look at your to/from frames. (but I don't know how hero works that much)

You appear to have a simple cross fade animation, which can be done natively without hero. You could also try that. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ZaneH** [comment]
_shyoof_

Spent the better part of the day debugging this one. Turns out it was neither a retain cycle (even though there was one), it wasn't IQKeyboardManager (even though it was partially), but it was Hero. I set `self.navigationController?.hero.isEnabled = false` in `didSelectRowAt:` and reenabled it in `viewDidAppear:`.

Thanks for sending me in the right direction!
