### ISSUE TITLE
Improving MessageLabel

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#108]
The current `MessageLabel` implementation as a substitute for `UITextView` is a little rough. 

The code could use some cleanup & refactoring regarding:
- Parsing DataDetector attributes and storing detected ranges
- Syncing the internal text storage with `UILabel` properties
   - Currently, we have to apply to attributes before we set the text in `cellForItem(at:indexPath)` and       I'd like to remove this undefined behavior.
- The code determing whether a gesture should be triggered or how to resolve conflicting gestures is a little complex. 

This is mainly me documenting this behavior so I don't forget where the problem is 😅

**Comment by SD10** [comment]
Don't need an issue for this. 
I keep creating them because working with the `UILabel` subclass is so difficult.

**Comment by damirstuhec** [comment]
@SD10 Why not use `UITextView` directly. It would also automatically support features like #609.
