### ISSUE TITLE
Chat Image rotating to 90 degrees when sent in chat before that stays normal.

### ISSUE THREAD

**Issue by asn111** [MessageKit/MessageKit#1081]
What version of MessageKit are you using?
v2.0
What version of iOS are you running on?
v 12.1
What version of Swift are you running on?
v 4.2
What device(s) are you testing on? Are these simulators?
iphone 6
Is the issue you're experiencing reproducible in the example app?
I haven't seen that in example app.

Issue I am facing now is if I have to upload a picture it rotates to the 90 degree to the right every time, but before upload getting from photos or capturing it is shows that is normal. 
why is it happening like that, kindly help. showing in image for reference.
![IMG_5032](https://user-images.githubusercontent.com/8926549/58456297-43ae5f00-813d-11e9-8455-57c39979f7c2.PNG)

**Comment by AndreyFM** [comment]
> What version of MessageKit are you using?
> v2.0
> What version of iOS are you running on?
> v 12.1
> What version of Swift are you running on?
> v 4.2
> What device(s) are you testing on? Are these simulators?
> iphone 6
> Is the issue you're experiencing reproducible in the example app?
> I haven't seen that in example app.
> 
> Issue I am facing now is if I have to upload a picture it rotates to the 90 degree to the right every time, but before upload getting from photos or capturing it is shows that is normal.
> why is it happening like that, kindly help. showing in image for reference.
> ![IMG_5032](https://user-images.githubusercontent.com/8926549/58456297-43ae5f00-813d-11e9-8455-57c39979f7c2.PNG)

Hi.How do you insert image to input bar?I have the same task.

**Comment by asn111** [comment]
> > What version of MessageKit are you using?
> > v2.0
> > What version of iOS are you running on?
> > v 12.1
> > What version of Swift are you running on?
> > v 4.2
> > What device(s) are you testing on? Are these simulators?
> > iphone 6
> > Is the issue you're experiencing reproducible in the example app?
> > I haven't seen that in example app.
> > Issue I am facing now is if I have to upload a picture it rotates to the 90 degree to the right every time, but before upload getting from photos or capturing it is shows that is normal.
> > why is it happening like that, kindly help. showing in image for reference.
> > ![IMG_5032](https://user-images.githubusercontent.com/8926549/58456297-43ae5f00-813d-11e9-8455-57c39979f7c2.PNG)
> 
> Hi.How do you insert image to input bar?I have the same task.

Yess ,, i did insert image..

**Comment by enchtein** [comment]
Hi, problem not in message kit.
U should fix image orientation to normal before sent image to chat

Just add this extension 
extension UIImage {
  func fixOrientation() -> UIImage? {
    if self.imageOrientation == UIImage.Orientation.up {
      return self
    }
    
    UIGraphicsBeginImageContext(self.size)
    self.draw(in: CGRect(origin: .zero, size: self.size))
    let normalizedImage = UIGraphicsGetImageFromCurrentImageContext()
    UIGraphicsEndImageContext()
    return normalizedImage
  }
}
and call this func at didPressSendButtonWith
use getting image (with normal orientation) - send it
