### ISSUE TITLE
Crash when reloading section

### ISSUE THREAD

**Issue by bmt2018** [MessageKit/MessageKit#1083]
I'm using MessageKit 3.0.0 on iOS 12.3.1.  My code is written in Swift 5 and I'm testing on an iPhone XS Max.  My chat messages are stored in a Realm database and I'm observing that collection of messages for changes.  When I detect changes, I am doing the following:

```
                self?.messagesCollectionView.performBatchUpdates( {
                    if deletions.count > 0 {
                        print("deletions count: \(deletions.count)")
                        self?.messagesCollectionView.deleteSections(IndexSet(deletions))
                    }
                    if insertions.count > 0 {
                        print("insertions count: \(insertions.count)")
                        self?.messagesCollectionView.insertSections(IndexSet(insertions))
                    }
                    if modifications.count > 0 {
                        print("modifications count: \(modifications.count)")
                        self?.messagesCollectionView.reloadSections(IndexSet(modifications))
                    }
                }, completion: { [ weak self] _ in
                    self?.messagesCollectionView.scrollToBottom(animated: true)
                })

```

For anyone not familiar with Realm, the "deletions", "insertions" and "modifications" values are arrays of integer indices of the changed elements in the collection.  This makes it convenient for updating a UITableView or UICollectionView.

At first, my code seemed to be working ok but then I ran into an issue that appears to be related to multiple updates occurring very quickly.  For example, when I send a chat message, the server will acknowledge that the the message was received which will cause the chat message object to be modified.  When a recipient sees the message, that, too, will cause the chat message object to be updated.  If these two events occur together very quickly, my code that calls `messagesCollectionView.reloadSections(IndexSet(modifications))` will be run twice.  It seems like the second call actually occurs while the first call is still being processed and this results in a crash with the following message:

```
[CollectionView] An attempt to prepare a layout while a prepareLayout call was already in progress (i.e. reentrant call) has been ignored. Please file a bug. UICollectionView instance is (<MessageKit.MessagesCollectionView: 0x10c01b400; baseClass = UICollectionView; frame = (0 0; 414 896); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x2830aa670>; layer = <CALayer: 0x283ea44a0>; contentOffset: {0, 137}; contentSize: {414, 604}; adjustedContentInset: {88, 0, 429, 0}> collection view layout: <MessageKit.MessagesCollectionViewFlowLayout: 0x10b7069d0>)
[CollectionView] An attempt to update layout information was detected while already in the process of computing the layout (i.e. reentrant call). This will result in unexpected behaviour or a crash. This may happen if a layout pass is triggered while calling out to a delegate. UICollectionViewFlowLayout instance is (<MessageKit.MessagesCollectionViewFlowLayout: 0x10b7069d0>)
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndexedSubscript:]: index 0 beyond bounds for empty array'

```

Is there a better way to handle reloading of the individual sections to avoid this re-entrant problem?  Thanks very much!

**Comment by nathantannar4** [comment]
From the crash logs, it looks like you are performing updates too fast. I haven't worked with Realm before but I would suggest debouncing/throttling the detected changes.
