### ISSUE TITLE
Value of type 'InputBarButtonItem' does not conform to expected element type 'InputItem'

### ISSUE THREAD

**Issue by nightroadcosplay** [MessageKit/MessageKit#1088]
- What version of MessageKit are you using?
3.0.0-beta-swift5
- What version of iOS are you running on?
12.3.1
- What version of Swift are you running on?
5.0
- What device(s) are you testing on? Are these simulators?
iPhone 5s

In some cases it can be really helpful to provide a short example of your code.
If so, please wrap these code blocks in backticks, like this:

```swift
        let cameraItem = InputBarButtonItem(type: .system)
        cameraItem.tintColor = .redSticker
        cameraItem.image = #imageLiteral(resourceName: "photo_white")
        cameraItem.addTarget(self, action: #selector(cameraPressed), for: .primaryActionTriggered)

        cameraItem.setSize(CGSize(width: 60, height: 30), animated: false)

        messageInputBar.leftStackView.alignment = .center
        messageInputBar.setLeftStackViewWidthConstant(to: 50, animated: false)
        messageInputBar.setStackViewItems([cameraItem], forStack: .left, animated: false) 
```

I get this error on setStackViewItems for cameraItem:
Value of type 'InputBarButtonItem' does not conform to expected element type 'InputItem'

**Comment by nathantannar4** [comment]
Have you also imported MessageInputBar in that file? If your using 3.0 make sure it's removed from your project. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nightroadcosplay** [comment]
> Have you also imported MessageInputBar in that file? If your using 3.0 make sure it's removed from your project.
> 
> Sent with [GitHawk](http://githawk.com)

That was the problem, thank you.
It's working now.

**Comment by d1mster** [comment]
> Have you also imported MessageInputBar in that file? If your using 3.0 make sure it's removed from your project.
> 
> Sent with [GitHawk](http://githawk.com)

I have the same issue. If I remove MessageInputBar from my project, it says "Use of unresolved identifier 'InputBarButtonItem'" How to solve?

**Comment by hechukwu** [comment]
@nathantannar4 what do you mean by `If your using 3.0 make sure it's removed from your project.` I still get this error after importing `MessageInputBar`

**Comment by nathantannar4** [comment]
Remove `import MessageInputBar`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hechukwu** [comment]
I got it to work by importing `InputBarAccessoryView` instead. Thanks
