### ISSUE TITLE
Can you provide Reactions on message like as a facebook messenger app?

### ISSUE THREAD

**Issue by ghost** [MessageKit/MessageKit#1093]

**Comment by nathantannar4** [comment]
Unfortunately this is a feature that isn't supported at this time. But I think there are some other libraries that could help achieve this 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ghost** [comment]
Okay thanks for reply, can you guide me how can i add small type of reaction UI on existing message bubble in all kinds of message type?

**Comment by SD10** [comment]
You can use this method of `MessagesDisplayDelegate` to configure the `accessoryView` of each cell:

https://github.com/MessageKit/MessageKit/blob/master/Sources/Protocols/MessagesDisplayDelegate.swift#L87-L97

👋 👻
