### ISSUE TITLE
how to change font of TextMessageCell and change messages direction

### ISSUE THREAD

**Issue by HagerGamal95** [MessageKit/MessageKit#1096]
I am stuck in two problems 
1 - I want to change the font of textMessageCell from preferredFont to any font I want 
2 - I want to change the alignment of messages meaning that the received message start from right and the sent message start from left as this image 
so how I can do this without changing in the pod 
![Simulator Screen Shot - iPhone XR - 2019-06-14 at 16 01 41](https://user-images.githubusercontent.com/36477659/59516999-d4699680-8ec2-11e9-8dc8-7858da7e03fa.png)

**Comment by nathantannar4** [comment]
1. You will need to use `MessageKind.attributedText`
2. The alignment of the messages is based off `isCurrentSender` so in your MessagesDataSource for isCurrentSender return the opposite

Does that help? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
