### ISSUE TITLE
Colorful Messages (Feature)

### ISSUE THREAD

**Issue by hhoangna** [MessageKit/MessageKit#1100]
Could you support or create an example for color of messages.
It must be gradient color look like new feature of Messenger like this:
![messenger-4-group-chat-3-ios](https://user-images.githubusercontent.com/26923574/59647468-80520100-91a5-11e9-9349-5b0b557d1368.png)

**Comment by marcetcheverry** [comment]
Use CAGradientLayer. You can modify existing cells.

**Comment by hhoangna** [comment]
> Use CAGradientLayer. You can modify existing cells.
@marcetcheverry
How? Could you give me an example?
I spent more hours but i still have no idea :((

**Comment by braindrain92** [comment]
Did you figure out how @hhoangna ?

**Comment by marcetcheverry** [comment]
You need to be more clear about the question you have. Do you know how to use CAGradientLayer outside of MessageKit?

There are existing examples on modifying and making custom cells in the Examples folder. The rest is just standard UIKit.

**Comment by SD10** [comment]
Hey @hhoangna,

Check out this method of MessagesDisplayDelegate:

https://github.com/MessageKit/MessageKit/blob/master/Sources/Protocols/MessagesDisplayDelegate.swift#L33-L42
