### ISSUE TITLE
When sending an image, the inputBar never gets clear with image and every time on pressing send, sends again same image as before.

### ISSUE THREAD

**Issue by asn111** [MessageKit/MessageKit#1103]
What version of MessageKit are you using?
v2.0
What version of iOS are you running on?
v 12.1
What version of Swift are you running on?
v 4.2
What device(s) are you testing on? Are these simulators?
iphone 6
Is the issue you're experiencing reproducible in the example app?
I haven't seen that in example app.

Hi I have been using your library for a while, it lovely and thanks for that, but i am having a problem. when ever i send an image, it goes fine, but then i have cleared the `inputBar` too, and still even if i only type something it sends same image again , i did not know what i want to clear in order to remove that image reference from `inputBar`. thanks.

bellow is the code i am where handling my `inputBar`.

```
 func inputBar(_ inputBar: InputBarAccessoryView, didPressSendButtonWith text: String) {
self.sendRequestForPublishMessage(nil,type: "image", url: url, thumbnailURL: nil)
                        inputBar.inputTextView.text = ""
                        self.messagesCollectionView.scrollToBottom(animated: true)
                        self.messagesCollectionView.reloadData()
                        inputBar.invalidatePlugins()
}
```

**Comment by nathantannar4** [comment]
Images pasted in are an `NSTextAttachment` so try setting the `InputTextView.attributedText` to an `NSAttributedString`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
