### ISSUE TITLE
How can i add both image and  text in single message?

### ISSUE THREAD

**Issue by gizmeondev** [MessageKit/MessageKit#1104]
What version of MessageKit are you using?
v3.0
What version of iOS are you running on?
v 10.14.4
What version of Swift are you running on?
v 4.2
What device(s) are you testing on? Are these simulators?
iphone 6
 I need to implement both image and text  in single message. Is there any way to implement this?

**Comment by nathantannar4** [comment]
Yes, you can use `NSAttributedString` with attachments for the images. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
Sorry I should add, that response was aimed at building those messages in the MessageInputBar. Displaying both in a single cell would required implementing your own custom cell

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
