### ISSUE TITLE
Set different text colors for incoming/outgoing messages with NSAttributedString type

### ISSUE THREAD

**Issue by yulian948** [MessageKit/MessageKit#1109]
Hi,
What I want to reach is different text color for incoming/outgoing messages with`.attributedText(NSAttributedString)` type. 
For `.text` type I would normally implement `func textColor(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> UIColor` method. But it is not called for `.attributedText(NSAttributedString)`. 
I can not set my text color in attributed string itself, because I need to know whether the message is incoming or outgoing.

Thanks,
Yulian

**Comment by nathantannar4** [comment]
@yulian948 `.attributedText` is a value you have control over returning, you should be able to build in some logic to achieve this. If not let me know what you're stuck with and what you have attempted. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yulian948** [comment]
Thanks @nathantannar4 !
Sure I can implement this logic inside `MessageType` implementation, but I was not sure if it's good solution (putting additional data into message entity) and was wondering if the behavior I need can be achieved in some different way.

**Comment by nathantannar4** [comment]
For attributed strings no there is no other current implementation

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
