### ISSUE TITLE
Set Emoji Message to have Clear Background

### ISSUE THREAD

**Issue by braindrain92** [MessageKit/MessageKit#1111]
I am trying to set the cell background color of all emoji messages to .clear. I thought doing so in this method would be best (though maybe not):

```
func backgroundColor(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> UIColor {
        //grey color for receiver, blue for sender
        return isFromCurrentSender(message: message) ? .blue : .grey
    }
```

I tried comparing the `MessageKind` but didn't have much luck there: ![Emoji Image](https://i.ibb.co/9Yb1kM1/Screen-Shot-2019-06-25-at-2-50-34-PM.png)

The documentation says emoji messages have a clear background, but that doesn't appear to be the case in version 3.0.0: (https://messagekit.github.io/Protocols/MessagesDisplayDelegate.html#/s:10MessageKit23MessagesDisplayDelegateP15backgroundColorSo7UIColorCAA0A4Type_p3for_10Foundation9IndexPathV2atAA0C14CollectionViewC2intF) 

I think my answer is close, so any help would be great!

**Comment by braindrain92** [comment]
This fixed the issue: 
```
if case .emoji(let value) = message.kind {
            return UIColor.clear
} 
```
The documentation does need to be updated for 3.0.0

**Comment by nathantannar4** [comment]
I think the documentation is still valid. If not can you please be more clear as to what you think is wrong?

It looks like your trouble was that `MessageKind` does not conform to `Equatable` because it has associated types. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
The behavior and documentation seems to be correct here
