### ISSUE TITLE
[AvatarPosition Horizontal.natural needs to be resolved] when trying add custom cell

### ISSUE THREAD

**Issue by hhoangna** [MessageKit/MessageKit#1114]
It is my custom Collection View Cell
![Screen Shot 2019-06-27 at 17 41 04](https://user-images.githubusercontent.com/26923574/60260148-09cea500-9903-11e9-8edb-8ee08ecadcc6.png)
I have a custom UIView added into my custom CollectionViewCell
![Screen Shot 2019-06-27 at 17 41 32](https://user-images.githubusercontent.com/26923574/60260161-12bf7680-9903-11e9-9388-789b1ff7dff4.png)
And i get this error.
![Screen Shot 2019-06-27 at 17 42 38](https://user-images.githubusercontent.com/26923574/60260168-1521d080-9903-11e9-8c96-8a4db9cb874b.png)
What's configuration I missing?

**Comment by nathantannar4** [comment]
@hhoangna did you still need help?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vincenzo-favara** [comment]
@nathantannar4  Hi, I need some help about this issue

**Comment by hhoangna** [comment]
@nathantannar4 no thanks, i resolved my issue

**Comment by SaurabhPrajapati** [comment]
@vincenzo-favara any update? I'm facing same issue.

**Comment by vincenzo-favara** [comment]
no, I'm sorry, I found a workaround put a 0.1 delay when typing cell appearing

**Comment by vivi7** [comment]
now my workaround seems it doesn't work anymore, any help?

**Comment by vincenzo-favara** [comment]
now my workaround seems it doesn't work anymore, any help?

**Comment by jugos654** [comment]
@vincenzo-favara  Did you found something that works? i am stuck on same issue...

**Comment by shimunKg** [comment]
Can someone please provide a solution for this problem? @nathantannar4 can you please maybe help? 
@vincenzo-favara  have you found a way to do it? 

Thanks a lot

**Comment by sraudax** [comment]
@nathantannar4 we are all still stuck here, please help! This is fatal for 2 of my apps :(

**Comment by hhoangna** [comment]
> @nathantannar4 we are all still stuck here, please help! This is fatal for 2 of my apps :(

do u have ovveride func apply(_ layoutAttributes: ... ) in your code

**Comment by vincenzo-favara** [comment]
I fund the issue, sorry guys if i didin't write before.
So The problem was in my custom typing cell that it didin't implement a custom MessageSizeCalculator. so isssue can be considered fixed.
