### ISSUE TITLE
layoutCellTopLabel in MessageContentCell missing assignments

### ISSUE THREAD

**Issue by mdescalzo** [MessageKit/MessageKit#1116]
- What version of MessageKit are you using?
3.0.0
- What version of iOS are you running on?
12.2
- What version of Swift are you running on?
4.2
- What device(s) are you testing on? Are these simulators?
iPad sim, iPhone Xs
- Is the issue you're experiencing reproducable in the example app?
Yes

The layout methods for cell and message labels each have assignments for textAlignment and textInsets.  layoutCellTopLabel is missing these assignments.

**Comment by SD10** [comment]
This was resolved by #117. Thank you!!!
