### ISSUE TITLE
Set Return Key Function

### ISSUE THREAD

**Issue by Alexander-Frost** [MessageKit/MessageKit#1121]
How can you set the action for the keyboard return key?

Typically you would do something along the lines of:

> func textFieldShouldReturn(_ textField: UITextField) -> Bool {
>             textField.resignFirstResponder() 
>             print("RETURN PRESSED HERE")
>             return true
>  }
after adding the UITextFieldDelegate to the VC.

Thanks!

**Comment by nathantannar4** [comment]
Hey @Alexander-Frost, is there a reason you cannot use the delegate?

One way would be to check for the newline character of \n in a textDidChange hook.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Alexander-Frost** [comment]
My mistake. The input bar contains a text view, not a text field, that was why the delegate function wasn't returning. Thanks!
