### ISSUE TITLE
Insert Into Final Collection View Cell

### ISSUE THREAD

**Issue by iOS53** [MessageKit/MessageKit#1122]
Hello everyone,

![image](https://user-images.githubusercontent.com/52382413/60400118-95cc1100-9b3d-11e9-95e8-8f6fa9bbb74a.png)

I am trying to re-create these pre-written buttons. How can you insert an item into the final cell of a message kit collection view?

I believe this would make for a good addition to MessageKit so I can submit a pull request when I finish adding it in.

**Comment by nathantannar4** [comment]
I see two options:
1. Make a custom cell with a horizontal layout collection view in it
2. Put a horizontal layout collection view in the topStackView of the input bar

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iOS53** [comment]
How can you insert the custom cell in the final cell spot?

**Comment by nathantannar4** [comment]
It should be the last message returned in the data source. Ie, the message that will be at the last index path. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iOS53** [comment]
How would you get that last index path from the data source?

**Comment by nathantannar4** [comment]
You are likely returning an array of messages in your datasource, you could have a message at the end of the array that represents the quick replies. 

If you are still confused by this then you should look more into how UITableView/UICollectionView datasources work.

**Comment by iOS53** [comment]
if indexPath.row == chatNetworkManager.currentMessages.count {
}
works. What method do I add it to?

**Comment by nathantannar4** [comment]
@iOS53 sorry I can't help you with every step. Only with MessageKit specific questions. Please start with the ChatExample project to implement a custom cell. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iOS53** [comment]
This is just the final step. I found the message count. Please help

**Comment by iOS53** [comment]
I made the custom cell too

**Comment by iOS53** [comment]
Please do you have any hints?

**Comment by nathantannar4** [comment]
I have explained this already above. To show your custom cell the `MessagesDataSource` you have set needs to return a message that represents your custom cell. The `MessageKind` needs to be .custom, as you should have found by following the ChatExample

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iOS53** [comment]
I followed the example at this link https://github.com/MessageKit/MessageKit/issues/686#issuecomment-389677565 but it's not showing. What is wrong?

**Comment by iOS53** [comment]
I copied all the code exactly as they have and even created new swift files

**Comment by nathantannar4** [comment]
I think you need to spend more time understanding the example project and the library. The example project clearly shows how to add a custom cell. 

I can only help with specific questions.  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iOS53** [comment]
Yes, you're right. The example project shows how to add a custom cell, which I copied plainly just like from that Github post (https://github.com/MessageKit/MessageKit/issues/686#issuecomment-389677565) but this is a cell that shows only 1 time and it is being inserted into the datasource so it is not a regular custom cell. What is missing from that github link that would let you insert a custom cell like in the picture posted with the question?

**Comment by nathantannar4** [comment]
Go back and read my first response. You can't just copy and paste... You need to have a collection view in your custom cell 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iOS53** [comment]
Yes I have that but it doesn't show up is what I'm saying

**Comment by iOS53** [comment]
Happy 4th of July

**Comment by iOS53** [comment]
@nathantannar4

**Comment by nathantannar4** [comment]
@iOS53 It’s not very good GitHub etiquette to constantly comment on an issue along the lines of “help it’s not working” and tag users just to get their attention. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
