### ISSUE TITLE
Swift 5 Support

### ISSUE THREAD

**Issue by AttilaTheFun** [MessageKit/MessageKit#1123]
Hi I was wondering if / when you're planning on updating the project to build with Swift 5? It's really frustrating when Xcode keeps complaining that a conversion to Swift 5 is available because this pod is still set to Swift 4.2.

**Comment by iOS53** [comment]
Why don't you do the conversion yourself to help everyone out. It's an open source project, if you don't do it nobody will!

**Comment by nathantannar4** [comment]
It's already done on the Swift5 branch. The next release will be Swift 5

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
@nathantannar4 where are we at on this? I'm just catching up

**Comment by nathantannar4** [comment]
I think the development branch is already updated to swift 5 so the next release can be swift 5

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
