### ISSUE TITLE
How to set bubble spacing?

### ISSUE THREAD

**Issue by AttilaTheFun** [MessageKit/MessageKit#1124]
Hey I was wondering the best way to adjust the spacing between bubbles? I tried using the minimum line spacing and interitem spacing but that didn’t work. I guess since each bubble is in its own section? Can I use the section insets?

**Comment by nathantannar4** [comment]
Yes! Section insets is the key 👍🏻
See the advanced example for a compact message bubble layout. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
