### ISSUE TITLE
How do you insert a MessageKit custom cell?

### ISSUE THREAD

**Issue by iOS53** [MessageKit/MessageKit#1128]
Hello everybody,

Please explain in detail how to insert a custom cell into Messagekit. Your answer should be spelled out in steps. If you choose to include images in the steps, then I'll upvote your post giving you github points.

**Comment by SD10** [comment]
😅 Oh I've missed open source

**Comment by JulienKode** [comment]
You can take a look at: 

- https://github.com/MessageKit/MessageKit/issues/686
- https://stackoverflow.com/questions/56958482/how-to-create-custom-cell-with-messagekit/57165876#57165876
- https://github.com/MessageKit/MessageKit/issues/945
