### ISSUE TITLE
Message Label was hidden by Container View

### ISSUE THREAD

**Issue by hhoangna** [MessageKit/MessageKit#1129]
I have 2 Message Label in messageContainerView. 
I want have label with 4 corner like this but it seem to be drop by messageContainerView

![Screen Shot 2019-07-04 at 10 36 12](https://user-images.githubusercontent.com/26923574/60638353-3f661780-9e48-11e9-9e2a-1ffb6edd7001.png)
How can i do like this
![IMG_0067](https://user-images.githubusercontent.com/26923574/60638347-3bd29080-9e48-11e9-8c4a-022f97165d9b.PNG)

**Comment by nathantannar4** [comment]
Is this a custom cell? If so you cannot rely on the standard delegate methods to configure your cell. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hhoangna** [comment]
Yup, i'm customizing a reply cell. All i need is Message Label with corner radius

**Comment by nathantannar4** [comment]
You need to configure it to have the corner cell then. You can’t rely on the rounded corner methods that work for the standard cells unless you link it up correctly to do so. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hhoangna** [comment]
I can calculate the cell properly but the only problem I have is the Message Label cannot be rounded. I tried using layer.cornerRadius, clipToBounds but did not work

**Comment by nathantannar4** [comment]
You might want to consider adding subviews to your cell which you can manipulate the corner radius of
