### ISSUE TITLE
Implementing collectionView(_:layout:insetForSectionAt:) causes undefined UICollectionViewFlowLayout behavior

### ISSUE THREAD

**Issue by AttilaTheFun** [MessageKit/MessageKit#1130]
Hey folks,

I'm trying to implement this method in my MessagesViewController as follows:

```
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, insetForSectionAt section: Int) -> UIEdgeInsets {

        typealias InsetsSpec = Specs.Message.Insets
        var insets = InsetsSpec.default
        let indexPath = IndexPath(item: 0, section: section)

        let isFirstMessage = section == 0
        let isPreviousMessageFromSameSender = self.messagesDataController.isPreviousMessageSameSender(at: indexPath, in: self.messagesCollectionView)
        if isFirstMessage {
            insets.top = InsetsSpec.default.top * 2
        } else if isPreviousMessageFromSameSender {
            insets.top = InsetsSpec.minimum.top
        }

        let isLastMessage = section == collectionView.numberOfSections - 1
        let isNextMessageFromSameSender = self.messagesDataController.isNextMessageSameSender(at: indexPath, in: self.messagesCollectionView)
        if isLastMessage {
            insets.bottom = InsetsSpec.default.bottom * 2
        } else if isNextMessageFromSameSender {
            insets.bottom = InsetsSpec.minimum.bottom
        }

        return insets
    }
```

I want to have different spacing between the bubbles depending on whether they're in the first / last position, or if they're "linked" with adjacent bubble. I tried setting the fixed section inset with:

layout.sectionInset = Specs.Message.Insets.default

As suggested by @nathantannar4  
This works, but doesn't let me customize it on a per-item basis.

When I try to implement this method, I receive the following errors:

```
> The behavior of the UICollectionViewFlowLayout is not defined because:
> the item width must be less than the width of the UICollectionView minus the section insets left and right values, minus the content insets left and right values.
> The relevant UICollectionViewFlowLayout instance is <MessagesCollectionViewFlowLayout: 0x7fb20dc7e910>, and it is attached to <MessageKit.MessagesCollectionView: 0x7fb20e850a00; baseClass = UICollectionView; frame = (0 0; 375 812); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x600001195800>; layer = <CALayer: 0x600001f438a0>; contentOffset: {0, -88}; contentSize: {0, 0}; adjustedContentInset: {88, 0, 84, 0}> collection view layout: <MessagesCollectionViewFlowLayout: 0x7fb20dc7e910>.
```

After some digging, the root cause appears to be that in a few places the "sectionInset" property is used, rather than the collection view delegate method. In the flow layout:

```
    public var itemWidth: CGFloat {
        guard let collectionView = collectionView else { return 0 }
        return collectionView.frame.width - sectionInset.left - sectionInset.right
    }
```

The collection view delegate method, if unimplemented, defaults to this value. But because MessageKit ignores this, the flow layout attempts to use the value from the delegate which differs from the sectionInset property.

I believe we should remove all direct reads from the sectionInset property in favor of the delegate method (which will read this indirectly).

**Comment by AttilaTheFun** [comment]
Hmm after some more investigation, this will be a bit tricker than expected. The itemWidth is used in a number of places where we just have access to the message and not the indexPath. The assumption that the sectionInsets are fixed and do not vary is pretty baked-in right now. I might be able to hack around this since I really only need to vary the height for now. But for the next API-breaking release, there should really be the ability to customize these insets on a per-bubble basis.

**Comment by nathantannar4** [comment]
Try adjusting the padding of messages to get a more compact layout instead. Take a look at the advanced example in the demo project 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AttilaTheFun** [comment]
@nathantannar4 Unfortunately there still doesn't seem to be a way to really configure that on a per-bubble basis. I suppose this could be a non-issue if I decide to populate the top and bottom labels as then I could just use the message top / bottom label heights to separate the groups of bubbles.

**Comment by SD10** [comment]
@AttilaTheFun Thanks for bringing this to my attention, I'm going to look at this

**Comment by N1nomiya** [comment]
Hi there, I'm facing the same problem. That is there a way to configure different insets for different bubbles/cells?

**Comment by adolffre** [comment]
Having exactly the same warning all over my chat =T
