### ISSUE TITLE
MessageInputBar disappear after tapping the input bar 

### ISSUE THREAD

**Issue by alkazale777** [MessageKit/MessageKit#1131]
![1](https://user-images.githubusercontent.com/42755471/60655904-303a9600-9e57-11e9-80d8-f29dcc61770c.gif)

I test the same code in new app its work fine but when put it in my old app the MessageInputBar disappear after tapping the input bar.

Please let us know the following things:

- What version of MessageKit are you using?
2.0.0
- What version of iOS are you running on?
12
- What version of Swift are you running on?
4.2
- What device(s) are you testing on? Are these simulators?
both
- Is the issue you're experiencing reproducable in the example app?
no

**Comment by nathantannar4** [comment]
Are you using IQKeyboardManager or anything like that?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alkazale777** [comment]
@nathantannar Thank you for replaying https://github.com/MessageKit/MessageKit/issues/1131#issuecomment-508501669

No ,I don't use it

I use the same code here https://github.com/instamobile/messenger-iOS-chat-swift-firestore

**Comment by nathantannar4** [comment]
Look at other GitHub issues related to input bar not showing, it sounds like you have your controller as a child view controller and is not becoming the first responder. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alkazale777** [comment]
https://github.com/MessageKit/MessageKit/issues/1131#issuecomment-508547638 thanks for your comment 

I really check and try all issues without any improvement

in the beginning my controller was as a child , but after that I try to make it the first controller running in my app as a normal one    and I get the same result

**Comment by alkazale777** [comment]
the reason is DAKeyboardControl.h (Plug in) it works after I comment the following line //method_exchangeImplementations(originalMethod, swizzledMethod);
