### ISSUE TITLE
Switch out cell image style

### ISSUE THREAD

**Issue by braindrain92** [MessageKit/MessageKit#1133]
What is the best way to switch out the message tail style with our own message image style? 

I would like to have WeChat's message style with the right side pointer. Is there an example project you would look at to do this or is it as easy as replacing the tail image?

**Comment by SD10** [comment]
Hey @braindrain92,

Check out this method of `MessagesDisplayDelegate`:

https://github.com/MessageKit/MessageKit/blob/master/Sources/Protocols/MessagesDisplayDelegate.swift#L33-L42
