### ISSUE TITLE
Include a phone number and a display name, when pressing @

### ISSUE THREAD

**Issue by senuraa** [MessageKit/MessageKit#1134]
Currently` I've included a display name and a phone number as shown in the code. But when I'm showing the message to the user it should show @displayName, and when sending the message to the server it should go as @phoneNumber. How to have this functionality?

I'm returning a text and a context with AutoCompletion object in autocompleteManager, how do I retrieve this context and send it to server

current autocompleteManager function

```
func autocompleteManager(_ manager: AutocompleteManager, autocompleteSourceFor prefix: String) -> [AutocompleteCompletion] {
       if prefix == "@" {
           return self.contactsArray
               .map { user in
                   return AutocompleteCompletion(text: user.displayName,
                                                 context: ["id": user.phoneNumber,"text":user.displayName])
           }
       }else if prefix == "#" {
           return self.tasks
               .map { task in
                   return AutocompleteCompletion(text: task.title, context: ["id":task.documentID])
           }
       }
       return []
   }
```
input bar didPressSendButtonWith

```
    func inputBar(_ inputBar: InputBarAccessoryView, didPressSendButtonWith text: String) {
        if let text = inputBar.inputTextView.text  {
            guard let id = serviceManager?.discussionService?.addMessage() else { return }
            let textWithNumber = replaceUserName(text: text)
            let message = DisscussionMessage(text: textWithNumber, user: (serviceManager?.authService?.getCurrentUser())!, messageId: id, date: Date(), groupId: self.group?.documentID ?? "")

            self.saveMessage(message)
        }
        inputBar.inputTextView.text = ""
        messagesCollectionView.scrollToBottom()
    }
```

**plugin version - 3.0.0-beta-swift5**

**Comment by nathantannar4** [comment]
To get the context you will have to look at the `attributedString` of the `InputTextView`. The context is stored as an attribute of that attributed string so you would have to build a `String` by parsing the attributedString. The key is:

```
public extension NSAttributedString.Key {
    
    /// A key used for referencing which substrings were autocompleted
    /// by InputBarAccessoryView.AutocompleteManager
    static let autocompleted = NSAttributedString.Key("com.system.autocompletekey")
    
    /// A key used for referencing the context of autocompleted substrings
    /// by InputBarAccessoryView.AutocompleteManager
    static let autocompletedContext = NSAttributedString.Key("com.system.autocompletekey.context")
}
```
Let me know if this still makes sense. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by senuraa** [comment]
@nathantannar4 Its a bit hard to comprehend, as I'm still a beginner to Swift do you have a sample code which does this? or if you could explain how to replace the attributedString with the context it would be super helpful

**Comment by nathantannar4** [comment]
@senuraa you have to enumerate the attributes to get the context. https://developer.apple.com/documentation/foundation/nsattributedstring/1412461-enumerateattribute

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by senuraa** [comment]
@nathantannar4 thanks got it to work! (y)
