### ISSUE TITLE
Why is cellForItemAt dequeuing non existing cells?

### ISSUE THREAD

**Issue by Leon12345679** [MessageKit/MessageKit#1139]
Greetings!
I'm implementing a feature where if a message doesn't  get delivered a red notification appears on the right side of the message. To do this I have a SendError() function and also a Boolean variable in each data array instance that tells the cell if it should display an error. The problem is that for some reason sometimes when  dequeued the generated cell is displayed incorrectly.

Normal cell:
<img width="159" alt="Screen Shot 2019-07-13 at 3 52 31 PM" src="https://user-images.githubusercontent.com/26027354/61171876-43034800-a586-11e9-83c5-936c03bb961d.png">

Also a normal cell:
<img width="155" alt="Screen Shot 2019-07-13 at 3 52 26 PM" src="https://user-images.githubusercontent.com/26027354/61171877-439bde80-a586-11e9-9bac-4b1e2e640c09.png">

Super weird paranormal cell:
<img width="135" alt="Screen Shot 2019-07-13 at 3 55 00 PM" src="https://user-images.githubusercontent.com/26027354/61171962-49de8a80-a587-11e9-9ec8-28f65736e575.png">

The paranormal cell is in the normal, non-error position and  half of the notification is visible. 
I need the MessageCollectionView to remember, and correctly display the error notifications until they are dealt with by the user - 2 cell types: error, no error. How do I accomplish this and what am I doing wrong?

This is my CellForRowAt: 
```swift

override open func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
    
    let cell = super.collectionView(collectionView, cellForItemAt: indexPath)
    cell.contentView.subviews.forEach ({
        if $0 is UIButton {
            print("REMOVED")
            $0.removeFromSuperview()
        }
    })
    
    if messageList[indexPath.section].errorShouldShow {
        sendError(cell: cell, index: indexPath, animates: false)
        return cell
    }
    
    cell.contentView.frame = CGRect(x: cell.frame.minX - 8, y:  cell.contentView.frame.origin.y, width: cell.contentView.frame.width, height: cell.contentView.frame.height)
    return cell
}
```
This is my SendError function:
```swift
func sendError(cell: UICollectionViewCell, index: IndexPath, animates: Bool)  {
    
    let errorNotif: UIButton = UIButton(frame: CGRect(x: self.view.frame.maxX - 18, y: cell.contentView.frame.maxY - 24, width: 24, height: 24))
    errorNotif.setImage(#imageLiteral(resourceName: "error"), for: .normal)
    cell.contentView.addSubview(errorNotif)
    
    if animates {
        UICollectionViewCell.animate(withDuration: 0.1, animations: {
            
            cell.contentView.frame = CGRect(x: cell.frame.minX - 28 , y:  cell.contentView.frame.origin.y, width: cell.contentView.frame.width, height: cell.contentView.frame.height)
            
            
            
        }, completion: {(finished: Bool) in
            
            
        })
    } else {
        cell.contentView.frame = CGRect(x: cell.frame.minX - 28 , y:  cell.contentView.frame.origin.y, width: cell.contentView.frame.width, height: cell.contentView.frame.height)
    }
}
```

And this is my message send failure handler:
```swift
      
} else {
    let visibleIndexPaths = self.messagesCollectionView.indexPathsForVisibleItems
    
    self.messageList[index.section].errorShouldShow = true
    if let cell = self.messagesCollectionView.cellForItem(at: index) {
        if visibleIndexPaths.contains(index) {
            self.sendError(cell: cell, index: index, animates: false)
        }
    }
}

```
I'm very new to using MessageKit so surely I missed something. Any help would be greatly appreciated!

**Comment by nathantannar4** [comment]
Without me taking a super detailed look since this is pretty client specific, I would suspect the error comes from you modifying the cells content view frame. I don’t think that is the best approach as it’s the collection views responsibility to do that. 

I would suggest subclassing a cell rather than changing things dynamically, or, try utilizing the accessory view of the cell.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
