### ISSUE TITLE
Strange behaviour of send button

### ISSUE THREAD

**Issue by Azraiths** [MessageKit/MessageKit#1142]
Hi. 
Guys something strange is happening here. 
Little bit of tech spec: 
MessageKit from branch 3.0.0-swift5
iOS - 11 and above
Swift 5
Testing device iPhone XS.
Now about glitch

this is my code in viewDidLoad

```swift
        messageInputBar.delegate = self
        messagesCollectionView.messagesDataSource = self
        messagesCollectionView.messagesLayoutDelegate = self
        messagesCollectionView.messagesDisplayDelegate = self
```
and extension for protocol
```swift
extension ChatViewController:  InputBarAccessoryViewDelegate {
    
    func messageInputBar(_ inputBar: InputBarAccessoryView, didPressSendButtonWith text: String) {
        inputBar.inputTextView.text = ""
    }
    
}
```
But. Send button just don't trigger protocol method in my ViewController. While I tried figure it out I can clearly see that this line is being executed as expected
$0.inputBarAccessoryView?.didSelectSendButton() (InputBarAccessoryView.swift line 159).
So I'm a bit lost in which direction I should look at to solve this?

**Comment by Meox92** [comment]
I know this issue is closed, but I think it should be discussed...
I had the exact same problem, I did upgrade from previous version and I didn't know about the refactor of the name
The method name has been changed to     
`    func **inputBar**(_ inputBar: InputBarAccessoryView, didPressSendButtonWith text: String) {}
`

The method is optional, so the compiler didn't complain...I think this method shouldn't be optional, why should someone have a chat and don't enable message sending?

**Comment by Azraiths** [comment]
Yeah. I figured it out right exact after this issue was opened. I thought that it could be some sort of bug because it's not main branch yet

**Comment by Sumire226** [comment]
Guys, you saved my day!! I got stuck on this for a while also.  Thank you so much for sharing this!!! :)

**Comment by EdIzaguirre** [comment]
Hey guys! I'm still having the same issue as you all are having, but I am not understanding the solution. I keep pressing send, but the message bubble is not appearing. What do you mean the method name has been changed? See below for my code. 
<img width="713" alt="Screen Shot 2020-06-13 at 12 35 13 PM" src="https://user-images.githubusercontent.com/55713891/84577578-67593d00-ad72-11ea-882e-784dbf37e00c.png">

**Comment by EdIzaguirre** [comment]
Never mind! Figured it out. ** input bar ** is just InputBar. Thanks for the help!
