### ISSUE TITLE
Photo Size Calculator & Cell Tapped Background Color

### ISSUE THREAD

**Issue by seable-cmcy** [MessageKit/MessageKit#1145]
Two questions for you. 

First, explicitly how do you set the cell size for photos? I have read the documentation and have done digging online. You can easily set the emoji and text cell sizes using:

>         if let layout = messagesCollectionView.collectionViewLayout as? MessagesCollectionViewFlowLayout { 
>                 layout.emojiMessageSizeCalculator.messageLabelFont = UIFont.systemFont(ofSize: Storyboard.emojiFontSize)
>         }

What is the equivalent that lets you enter a **CGSize**? I started writing this after seeing something online, but I still have **no idea** how to set the CGSize for all photo messages:

>
     func customCellSizeCalculator(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> CellSizeCalculator {
        guard let messagesDataSource = messagesCollectionView.messagesDataSource else {
            fatalError("Ouch. nil data source for messages")
        }
        let message = messagesDataSource.messageForItem(at: indexPath, in: messagesCollectionView)
        
        // Here you can add a custom cell message calculator
        if case .photo(let pic) = message.kind {
            
        }
    }

This seems pretty convoluted for such a simple task.

Second, how can you set the color of a cell when it is pressed? You can set the general colors for sender's and receiver's using 
> func backgroundColor(for message: MessageType, ...) {}

How can we set the cell pressed color in the _didTapMessage_ function?

Thank you!

I'm sure others will search to find solutions to this on Github so any feedback wouldn't just help me, it would help everyone.

**Comment by nathantannar4** [comment]
It’s a property of `MediaItem`
https://github.com/MessageKit/MessageKit/blob/master/Sources/Protocols/MediaItem.swift

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
