### ISSUE TITLE
'MessageInputBarDelegate' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by seable-cmcy** [MessageKit/MessageKit#1146]
This error keeps coming up when I updated my pods. I am using:
  - MessageInputBar (0.4.1):
    - MessageInputBar/Core (= 0.4.1)
  - MessageInputBar/Core (0.4.1)
  - MessageKit (3.0.0):
    - InputBarAccessoryView (~> 4.2.2)

When I call the function:

>     func messageInputBar(_ inputBar: MessageInputBar, didPressSendButtonWith text: String) {}

it also says: "'MessageInputBar' is ambiguous for type lookup in this context"

How can I fix it?

**Comment by nathantannar4** [comment]
Remove MessageInputBar from your podfile or cartfile then rebuild. See the change log on why it was removed. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by seable-cmcy** [comment]
Thanks Nathan! Removing it fixed the error. But it also caused all `InputBarButtonItem(type: .custom)` properties to throw errors. 

What is the equivalent of something like `let cameraItem = InputBarButtonItem(type: .custom)`?

**Comment by seable-cmcy** [comment]
Adding `import InputBarAccessoryView` fixed it
