### ISSUE TITLE
double messages

### ISSUE THREAD

**Issue by GualbertoVannini** [MessageKit/MessageKit#1147]
**INFO:**
**1.** Version MessageKit: 2.0.0
**2.** IOS deployment target: 11.0
**3.** Swift 4.2
**4.** Testing on real iphone 7 and simulator iphone 7 
**5.** Not reproducible, totally rendom.

Hello, 
Sometimes, with apparently no logic to reproduce it, when I send a message, it appears double on chat. The double message if I force the refresh (e.g. moving to another screen and then going back to the chat) disappear, and I can see only once. 

Did it happen to other users?

**Comment by nitinalabur** [comment]
are you sure your data source is not containing double messages? I had a similar issue, and solved by ensuring there were no issues with my own data source.
