### ISSUE TITLE
How to display an image within the input bar's text field as iMessage ?

### ISSUE THREAD

**Issue by seable-cmcy** [MessageKit/MessageKit#1148]
How could you display an image within the input bar's text field as iMessage allows: 
![image](https://user-images.githubusercontent.com/53124065/61715105-59e62f00-ad2a-11e9-9760-7d6b92a85970.png)?

**Comment by JulienKode** [comment]
@seable-cmcy You have to create a plugin for [MessageInputBar](https://github.com/MessageKit/MessageInputBar) you can find an example here https://github.com/MessageKit/MessageInputBar/tree/master/Plugins/AttachmentManager

You can also take a look at:
-  [`InputPlugin`](https://github.com/MessageKit/MessageInputBar/blob/master/Sources/Protocols/InputPlugin.swift) protocol it's the interface between your plugin and [MessageInputBar](https://github.com/MessageKit/MessageInputBar)
- [`AttachmentManager.swift `](https://github.com/MessageKit/MessageInputBar/blob/master/Plugins/AttachmentManager/AttachmentManager.swift) which use the views and implement `InputPlugin`

I can recommend you to may be copy and paste the [AttachmentManager](https://github.com/MessageKit/MessageInputBar/tree/master/Plugins/AttachmentManager) in your project and start using it, then making your change to have the same look and feel as iMessage. Which is the feature that you want

**Comment by seable-cmcy** [comment]
Thanks!

**Comment by JulienKode** [comment]
@seable-cmcy No problem 😊

If you have other question don't hesitate to re-open this issue 😊
