### ISSUE TITLE
3.0.0-swift5 Branch - failed to demangle superclass (MessagesViewController)

### ISSUE THREAD

**Issue by sanvean** [MessageKit/MessageKit#1151]
Hi,

When trying to use MessageKit using carthage on the latest 3.0.0-swift5 branch, when instantiating a subclass of MessagesViewController the following crashing error is thrown:

> failed to demangle superclass of ConversationViewController from mangled name '10MessageKit22MessagesViewControllerC' 
> 

Is there a build setting that I need to tweak in order to use this library?

Thanks,
Ben

**Config Details**
- What version of MessageKit are you using? 3.0.0-swift5
- What version of iOS are you running on? 12.4
- What version of Swift are you running on? 5
- What device(s) are you testing on? Are these simulators? Xcode 10.4 Simulator + iPhone X
- Is the issue you're experiencing reproducable in the example app?
No Example App uses Cocoapods

**Cartfile**
github "MessageKit/MessageKit" "3.0.0-swift5"

```swift
import UIKit

import MessageKit
import InputBarAccessoryView

class ConversationViewController: MessagesViewController {

  override func viewDidLoad() {
    super.viewDidLoad()
    
  }
}

// Error is thrown during instantiation from another ViewController:
extension ConversationListViewController: UITableViewDelegate {

 public func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
    
    let conversationViewController = ConversationViewController()
  
    self.navigationController?.pushViewController(conversationViewController, animated: true)
    tableView.deselectRow(at: indexPath, animated: true)
  }
```

**Comment by JulienKode** [comment]
@sanvean have you try to add `-all_load` to `Other Linker Flags` in the project

**Comment by sanvean** [comment]
> @sanvean have you try to add `-all_load` to `Other Linker Flags` in the project

Hi Julien,

Yes I tried that based on this SO thread: https://stackoverflow.com/questions/55584094/failed-to-demangle-superclass-with-cocoapods-in-xcode-10-2

But unfortunately no change in outcome...

**Comment by sanvean** [comment]
Figured it out by starting from a clean project, whilst I had MessageKit.framework + InputBarAccessoryView.framework both added as Optional in _**Link With Binary With Libraries**_, they were not in the Run Script section for Carthage:

`/usr/local/bin/carthage copy-frameworks` 

adding:

`$(SRCROOT)/Carthage/Build/iOS/MessageKit.framework
 $(SRCROOT)/Carthage/Build/iOS/InputBarAccessoryView.framework`

as Input Files solved the issue.

**Comment by JulienKode** [comment]
@sanvean Glad that you solve it 😊
