### ISSUE TITLE
How to handleTapGesture with different message kinds ? 

### ISSUE THREAD

**Issue by Frace17** [MessageKit/MessageKit#1152]
- What version of MessageKit are you using?
3.0.0
- What version of iOS are you running on?
12.1
- What version of Swift are you running on?
5
- What device(s) are you testing on? Are these simulators?
iPhone 7

What is the correct way to handleTapGesture when i press on cell? 

I have MediaItem, LocationItem, AudioItem and attributedText cells, for each type i should use different actions, can you give me a small example please

**Comment by JulienKode** [comment]
@Frace17 I recommend you to implement [MessageCellDelegate](https://github.com/MessageKit/MessageKit/blob/3.0.0-swift5/Sources/Protocols/MessageCellDelegate.swift#L154). Then you can handle tap on all kind of cells.

Most of them inherit from [MessageContentCell.swift](https://github.com/MessageKit/MessageKit/blob/master/Sources/Views/Cells/MessageContentCell.swift#L160) so you can implement `didTapMessage` as example. Note that theses delegate methods will give you the cell as parameter: `didTapMessage(in cell: MessageCollectionViewCell)`.  So inside your method you just have to detect which kind of cell you have. 

Here is an example:

```
// MARK: - MessageCellDelegate
extension ChatViewController: MessageCellDelegate {
    
    func didTapMessage(in cell: MessageCollectionViewCell) {
        if cell is LocationMessageCell {
           
        }
        if cell is TextMessageCell {
           
        }
    }

}
```

If you want to take a look at the implementation you can see an example here [MessageKit](https://github.com/MessageKit/MessageKit/blob/master/Sources/Views/Cells/AudioMessageCell.swift#L82)

**Comment by Frace17** [comment]
@JulienKode I understand that i need to use ```didTapMessage(in cell: MessageCollectionViewCell)``` function, but i don't know how correctly get messageKind from gesture in ```handleTapGesture(_ gesture: UIGestureRecognizer)``` function. If its not too much trouble, can you give me small code example

**Comment by JulienKode** [comment]
@Frace17 Have you try something like that ?

```
// MARK: - MessageCellDelegate
extension ChatViewController: MessageCellDelegate {
    
    func didTapMessage(in cell: MessageCollectionViewCell) {
        if cell is LocationMessageCell {
           
        }
        if cell is TextMessageCell {
           
        }
    }

}
```

**Comment by Frace17** [comment]
@JulienKode Great thank you!!! For help and fast response! <3

**Comment by JulienKode** [comment]
@Frace17 No problem 😊

Don't know if it's the best way to do it. May be @nathantannar4 and @SD10 have a better way to do it
