### ISSUE TITLE
Long press on send button

### ISSUE THREAD

**Issue by eemi2010** [MessageKit/MessageKit#1161]
Hello there,
first thx for this great library.
One question: Is there a way to detect a longpress event on the send button. I would like to implement audio recording when the user long press on the send button.

Cheers.

**Comment by eemi2010** [comment]
Found a solution in the slack group. Closing.

**Comment by hayyyyyyden** [comment]
@eemi2010 Hi, Could you share the solution here as well? I want to implement something similar. Thanks in advance!

**Comment by eemi2010** [comment]
@hayyyyyyden  I basically did 

``messageInputBar.sendButton.addGestureRecognizer(longPressGesture)` 

where "longPressGesture" is a UILongPressGestureRecognizer

`` let longPressGesture = UILongPressGestureRecognizer(target: self, action: #selector(longPressed))
