### ISSUE TITLE
MessageInputBarDelegate not firing when pressing Send

### ISSUE THREAD

**Issue by AnthonyTTaylor** [MessageKit/MessageKit#1162]
Please let us know the following things:

Verison 3.0.0
iOS 12
Swift 4.2
Simulator Xs Max
Reproducible in fresh test project and example projectt
In some cases it can be really helpful to provide a short example of your code.
If so, please wrap these code blocks in backticks, like this:

```swift
import UIKit
import MessageKit
import InputBarAccessoryView
//import MessageInputBar


private var messages: [Message] = []

class InboxThreadViewController: MessagesViewController, MessageInputBarDelegate {
   
    @objc public var myValue:String?
    private var messages: [Message] = []
    override func viewDidLoad() {
        super.viewDidLoad()
        
        
        messageInputBar.delegate = self
        messagesCollectionView.messagesDataSource = self
        messagesCollectionView.messagesLayoutDelegate = self
        messagesCollectionView.messagesDisplayDelegate = self
        title = "MessageKit"

func messageInputBar(_ inputBar: MessageInputBar, didPressSendButtonWith text: String) {
        print("Message : \(text)")
        NSLog("HELLO")
    } 
    }
```
MessageInputBar never gets triggered when hitting send in the view, if I downgrade to MessageKit 1.0.0, after making a few changes to downgrade, the delegate fires every time you press send.

**Comment by nathantannar4** [comment]
Change the delegate method from `func messageInputBar` to `func inputBar`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omartehsin1** [comment]
> Change the delegate method from `func messageInputBar` to `func inputBar`
> 
> Sent with [GitHawk](http://githawk.com)

I have the same issue as OP and when I do that then I get the error of Use of undeclared type 'InputBarAccessoryView'

Any solutions for this?

**Comment by nathantannar4** [comment]
Import `InputBarAccessoryView`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omartehsin1** [comment]
> Import `InputBarAccessoryView`
> 
> Sent with [GitHawk](http://githawk.com)

![Screen Shot 2019-08-26 at 12 39 31 PM](https://user-images.githubusercontent.com/33768337/63706919-99f37280-c7fe-11e9-9b71-3e9cd1b4de0e.png)

Hi Nathan, this is the error i am getting in the InputTextView file in the pod folder. it happens as soon as I begin to type anything. The app just crashes.

**Comment by Tulleb** [comment]
Same problem here, using version 3.4.2.

You all did a great job @nathantannar4, thanks, as well as the whole team of course! But the documentation is really poor and it's quite hard to explore the example project for beginners.

**Comment by Tulleb** [comment]
Found out why: I was resetting `messageInputBar = MessagesInputBar()` somewhere after setting the `messageInputBar.delegate = self` 🙄

**Comment by eyuphanakkaya** [comment]
hi guys MessageInputBarDelegate not showing up at all 
<img width="629" alt="image" src="https://github.com/MessageKit/MessageKit/assets/96181594/f90f1c06-3bf1-4827-a02e-f456d7e43209">
