### ISSUE TITLE
How can I save messages locally without using Core Data?

### ISSUE THREAD

**Issue by Leon12345679** [MessageKit/MessageKit#1163]
Greetings!
I need to save all of my messages locally on the device.
How can I accomplish this hopefully without using Core Data? 
Would storing messages as NSObjects that conform to NSCoding work? 
Or is there some other way?

Any ideas will be greatly appreciated!

**Comment by mding5692** [comment]
For what purpose are you saving the messages for? Like so when you turn on the app, the messages appear instantly?

**Comment by Leon12345679** [comment]
Yes. I would like to save a certain amount of messages locally and fetch the others from my server. Would this be possible using non Core Data methods?

**Comment by mding5692** [comment]
You might want to check out the Disk project repo:

https://github.com/saoudrizwan/Disk

or Codable storage on IOS generally:

https://mecid.github.io/2019/05/22/storing-codable-structs-on-the-disk/

But there are a lot of options:

https://stackoverflow.com/questions/8040065/storing-data-locally-on-the-iphone

https://stackoverflow.com/questions/28628225/how-to-save-local-data-in-a-swift-app

https://stackoverflow.com/questions/46370901/what-is-the-best-way-to-store-load-local-data-in-ios

https://stackoverflow.com/questions/37340047/best-way-to-save-data-locally-on-the-device-in-ios-app

However, don't think this is a relevant question for MessageKit specifically.

**Comment by mding5692** [comment]
@Leon12345679  Going to close if no more issues 👍
