### ISSUE TITLE
MessageInputBar is animated separately if the MessagesViewController is dismissed modally

### ISSUE THREAD

**Issue by whoyawn** [MessageKit/MessageKit#1168]
- What version of MessageKit are you using? 3.0.0-swift5
- What version of iOS are you running on? iOS 12.4
- What version of Swift are you running on? 5
- What device(s) are you testing on? Are these simulators? iPhone XR simulator, iPhone XR
- Is the issue you're experiencing reproducible in the example app? Yes

```swift
    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let cell = cells[indexPath.row]
        switch cell {
...
        case "Advanced Example":
            let advanced = AdvancedExampleViewController()
            let newNav = UINavigationController(rootViewController: advanced)
            advanced.navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .cancel, target: self, action: #selector(close))
            navigationController?.present(newNav, animated: true, completion: nil)
//            navigationController?.pushViewController(AdvancedExampleViewController(), animated: true)
...
        }
    }
    
    @objc func close() {
        dismiss(animated: true)
    }
```

Result: If I present the MessagesViewController as a modal, everytime I dismiss it, the input bar get dismissed after the upper part of the controller gets dismissed
Expected: The entire controller should be dismissed at the same time.

**Comment by nathantannar4** [comment]
When you dismiss the model view controller, resign it as the first responder 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by whoyawn** [comment]
Changed the close function to:

```
@objc func close() {
        presentedViewController?.resignFirstResponder()
        dismiss(animated: true)
    }
```
Animation still is delayed.

<img src="https://user-images.githubusercontent.com/15709918/63552107-af5d5980-c4eb-11e9-91dc-bf95b35c7f1a.gif" width="250" height="550">

**Comment by nathantannar4** [comment]
Based on your code snippet, I don't think you should be calling it on `presentedViewController`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by whoyawn** [comment]
Which controller do you mean to resign as the first responder? The modal view controller (messages view controller) or the controller that is presenting the messages view controller? Either way, the delay still happens.

**Comment by nathantannar4** [comment]
The `MessagesViewController`. The one with the input accessory view. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by whoyawn** [comment]
Ah, it was a bug on my end, as my `presentedViewController` referred to the `UINavigationController`.

Should this behavior of the input accessory view be documented anywhere? I'd imagine this would be a common problem.

**Comment by nathantannar4** [comment]
Hopefully someone just sees this GitHub issue as documentation. Since its standard behavior of how UIKit works I don't feel the need to document it. Its standard behavior of an input accessory view because even during animation it's still the first responder. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
