### ISSUE TITLE
Top view also getting scrolled when start typing.

### ISSUE THREAD

**Issue by MiteshiOS** [MessageKit/MessageKit#1169]
I Embedded "MessagesViewController" into my another view controller. In viewcontroller xib i have a custom navigation bar. So as per the Embedded Example in demo but when i start typing whole view getting scroll with my custom top view. Please check attached screenshot and let me know how can i stop it. I want it same like Embedded Example.
![1](https://user-images.githubusercontent.com/17427703/63316813-edad1a00-c32d-11e9-90c8-63c50110a5a3.jpeg)
![22](https://user-images.githubusercontent.com/17427703/63316818-ef76dd80-c32d-11e9-9ea5-4c34ae437f9b.jpeg)

**Comment by valic** [comment]
Hello

Tell me what was the problem?

**Comment by coldsteelbr** [comment]
It still is not solved. In my project ChatViewController embedded into the UINavigationViewController slides up when the keyboard appears

![Screenshot 2020-04-30 at 13 25 35](https://user-images.githubusercontent.com/10029968/80678973-279e0500-8ae6-11ea-8c6c-0d54e95af6d6.png)

**Comment by pranavpari** [comment]
any update on it? I am facing the same issue

**Comment by vikht0r28** [comment]
I had the same problem but it was for something else.

If you are using IQKeyboardManager you must disable it in the view.
`IQKeyboardManager.shared.disabledDistanceHandlingClasses.append (ChatViewController.self)`

That solved my problem. I hope it helps you
