### ISSUE TITLE
can i add view on top of MessagesViewController like header view

### ISSUE THREAD

**Issue by mohammadshalhoob** [MessageKit/MessageKit#117]
can i add view on top of MessagesViewController like header view .
like this design .
thanks
![04-seeker-chat-en-02-a](https://user-images.githubusercontent.com/25342711/30277246-e66207a2-970f-11e7-9ad1-3abe129a0c5a.jpg)

**Comment by SD10** [comment]
@mohammadshalhoob Unfortunately, our keyboard handling logic is blocking this capability. We also don't support having labels inside of the message bubbles yet. I'm going to work on making this possible for you. Thank you for bringing it to my attention

**Comment by mohammadshalhoob** [comment]
thanks SD10 for your help .

**Comment by SD10** [comment]
@mohammadshalhoob The header will be possible in `v0.8.0`. You'll have to add the header as a subview of your controller and then adjust the `messagesCollectionView.contentInset.top` to account for the size of your header. Still working on allowing the labels to be inside the bubble.

**Comment by mohammadshalhoob** [comment]
thank you SD10 .

**Comment by SD10** [comment]
You now need to set the `additionalTopContentInset` property as described in #218.

**Comment by asaplee** [comment]
Hi! When using this, my messages actually go underneath the subview. How do I fix this. Thanks :)

**Comment by nathantannar4** [comment]
@asaplee please make sure you are using the latest version. If you still have issues open a new issue. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
@nathantannar4 Thanks for helping out here 👍 But let's not lock issues unless they become toxic or we have a strong reason to do so

**Comment by VictorShurapov** [comment]
> @mohammadshalhoob The header will be possible in `v0.8.0`. You'll have to add the header as a subview of your controller and then adjust the `messagesCollectionView.contentInset.top` to account for the size of your header. Still working on allowing the labels to be inside the bubble.

Hello! Is it possible to add a label to our message bubble? :)
