### ISSUE TITLE
How to check message list array contains same element or not ?

### ISSUE THREAD

**Issue by MiteshiOS** [MessageKit/MessageKit#1172]
let message = MockMessage(text: "test", user: MockUser(senderId: "123", displayName: "test", messageId: UUID().uuidString, date: Date())

var messageList: [MockMessage] = []
messageList.append(message)

How to check my message list array contains same element or not ?

**Comment by mding5692** [comment]
Like remove duplicates or look for duplicates?

**Comment by MiteshiOS** [comment]
@mding5692 I wants to look for duplicates. If same message will be there then i will not append it.

**Comment by dstuecken** [comment]
I would do it like this:

```
extension MockMessage: Comparable {
    static func == (lhs: MockMessage, rhs: MockMessage) -> Bool {
        return lhs.messageId == rhs.messageId
    }
}
```


and then 
```
let message = MockMessage(text: "test", user: MockUser(senderId: "123", displayName: "test", messageId: UUID().uuidString, date: Date())
var messageList: [MockMessage] = []
messageList.append(message)

for m in messageList {
  if m == message {
    // Message already exists
    break
  }
}
```

alternatively without the extension you could also do
```
for m in messageList {
  if m.messageId == message.messageId {
    // Message already exists
    break
  }
}
```

**Comment by mding5692** [comment]
There are multiple different ways of doing this, like the above comment, you just need to make sure the array doesn't already contain an element with the same messageId:

https://stackoverflow.com/questions/47569157/how-to-check-if-already-custom-object-exist-in-array

https://stackoverflow.com/questions/46519004/can-somebody-give-a-snippet-of-append-if-not-exists-method-in-swift-array

https://stackoverflow.com/questions/34709066/remove-duplicate-objects-in-an-array

**Comment by mding5692** [comment]
^The above should be adequate for your purposes @MiteshiOS 

Will close this as not as relevant to the MessageKit's actual API and components.
