### ISSUE TITLE
Support System Messages

### ISSUE THREAD

**Issue by johnharutyunyan** [MessageKit/MessageKit#1173]
Guys , thank you for this amazing framework, you rock! 

How about to have system type messages?

**Comment by nathantannar4** [comment]
This is possible with yourself defining a system sender and use the .custom message type!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by johnharutyunyan** [comment]
@nathantannar4 , thanks so much, I have already create.
