### ISSUE TITLE
It seems we don't really implement messagesCollectionView.delegate?

### ISSUE THREAD

**Issue by hyouuu** [MessageKit/MessageKit#1175]
- What version of MessageKit are you using? 
From `development` branch

(Other infos are unrelated to this issue)

We set `messagesCollectionView.delegate = self` in https://github.com/MessageKit/MessageKit/blob/05b481c1f7eda0233d1a8eaaec5fd0aa9b75a142/Sources/Controllers/MessagesViewController.swift#L155. However, I don't see anywhere we comply to `UICollectionViewDelegate`, so it seems to do nothing - did I miss something?

I'm trying to listen to the `scrollViewDidEndDragging` callback so needs to direct the delegate to my class, but found the line above so wanted to double check. If it actually does nothing we should remove the line to reduce confusion.

Thanks!

**Comment by hyouuu** [comment]
Ping @nathantannar4 @SD10 @zhongwuzw

**Comment by reaganwood1** [comment]
Hi @hyouuu, `MessagesViewController` implements many of the methods of the UICollectionViewDelegate. One such example `func collectionView(_ collectionView: UICollectionView, shouldShowMenuForItemAt indexPath: IndexPath) -> Bool` on line 361. Also, MessageKit uses a collection view, which inherits from `UIScrollView`. Therefore, if you want to subscribe to end dragging events, I believe all you need to do is implement `scrollViewDidEndDragging` inside your subclass of the `MessageViewController`. I have tried something similar in my example project with good success. Hope this helps!

**Comment by hyouuu** [comment]
Ah it actually works this way - thanks! I thought as a subclass that optional method was not implementable :p
