### ISSUE TITLE
ChatExample Missing debub.xcconfig file

### ISSUE THREAD

**Issue by jakelangton** [MessageKit/MessageKit#1176]
I cloned the repository and when trying to run ChatExample.xcworkspace but I get the following error.

.../MessageKit/Example/Pods/Target Support Files/ Pods-ChatExample/Pods-ChatExample.debug.xcconfig: unable open file (in target "ChatExample" in project "ChatExample") (in target 'ChatExample')

I don't see a Pods folder in the Example folder. Not sure how to proceed.

**Comment by primeviltom** [comment]
I'm not exactly sure what I did to fix it, so there may some extra unnecessary steps in the following:
I assume you're familiar with cocoapods (if not do that first)

open the project and remove the top line in each of 
Pods-ChatExample.debug.xcconfig 
Pods-ChatExample.release.xcconfig

open the Podfile and remove the 2 lines that are inherit search paths or something.
pod install

Open xcworkspace and clean build folder (This is frequently required for example projects)
Run the app.

**Comment by Mozahler** [comment]
I'm getting this message as well.  I tried using carthage.  I'm adding this message so the issue doesn't go stale, and will come back with an update when I resolve the issue.

**Comment by jakelangton** [comment]
My issue was resolved by running 'pod init' in terminal. When you download this project, it does not have CocoaPods, so you must do the pod init after going into the Example folder inside terminal.

**Comment by hlebowicz** [comment]
It occured to me too. 
Just do the `pod install` in Example directory and you should be good.
