### ISSUE TITLE
Is this still alive?

### ISSUE THREAD

**Issue by bguidolim** [MessageKit/MessageKit#1179]
Hi!

I would like to ask: is this library still alive?

I see open issues without any interaction or pull requests opened for a long time with no interactions.
There is no new release for weeks.

I can help to keep this alive, but I have no motivation to open PR if no one is reviewing and merging.

If for some reason the owners are not able to continue with this, I would like to suggest to handover to someone else. By the way, I'm open to tackle this.

Thanks.

**Comment by mohitathwani** [comment]
I'd like to be a part as well.

**Comment by nathantannar4** [comment]
I myself am no longer able to make contributions. Would love to see others help maintain the project. We have a slack channel where this can be discussed in greater detail. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cyBerta** [comment]
Hi can you please give feedback here as soon as there has been some decisions made? I'm also interested in conributing, but I'm waiting until an active group of repository maintainers has been established.

**Comment by iJasonWade** [comment]
I would also like to contribute to this library if a group is established to do just that!

**Comment by grangej** [comment]
I also would like to be part of this, will reach out on slack

**Comment by 0xFA709394** [comment]
I would like to be a part as well.

**Comment by clay-mindoula** [comment]
haha crickets ... dead it is
