### ISSUE TITLE
picture messages don't load as they should

### ISSUE THREAD

**Issue by michaeldebo** [MessageKit/MessageKit#1183]
Hi, I have incorporated message kit into my app, and it mostly works. There's one problem, when there are images on the chat screen, a new message (text or photo) results in the picture messages disappearing showing older texts instead, then popping back into place. This does not look good. I tried a bunch of things, but have been unable to fix this problem. Is this a common problem? Any suggestions for how to smoothly load a new message?

**Comment by reaganwood1** [comment]
Hi @michaeldebo. This is not a problem for me! What version are you on? If you post some code for how you're loading in messages into the your messaging app, I may be able to help!

**Comment by michaeldebo** [comment]
Thanks! I added the cocoapod 2-3 days ago, which installs the most recent version then, which I believe is the most recent now. I don't know the version number though. I don't know how to look up the number.

Please look over my code around retrieving and processing messages. Hopefully you'll spot why the photos disappear then reappear when visible on the screen when a new message is sent or received. 



This function gets called by viewWillAppear and it users Firebase's snapshot listener.

    fileprivate func getMessages() {
        DispatchQueue.global(qos: .userInitiated).async {
            guard let chatId = self.chat?.chatId else { return }
            self.chatViewModel.getMessages(chatId: chatId) { success in
                if success {
                    if self.firstTime {
                        self.firstTime = false
                        DispatchQueue.main.async {
                            self.messages = self.chatViewModel.messages
                            self.messagesCollectionView.reloadData()
                            self.messagesCollectionView.scrollToBottom()
                            self.removeSpinner()
                        }
                    } else {
                        DispatchQueue.main.async {
//                            let lastIndex = self.chatViewModel.messages.count - 1
//                            let lastMessage = self.chatViewModel.messages[lastIndex]
                            self.messages = self.chatViewModel.messages
//                            self.messages.append(lastMessage)
                            self.messagesCollectionView.reloadDataAndKeepOffset()
                            self.messagesCollectionView.reloadWithoutAnimation()
                            self.messagesCollectionView.scrollToBottom()
                            self.removeSpinner()
                        }
                    }
                }
            }
        }
    }


In the ChatViewModel class there is:

    var messages = [Message]()

    func getMessages(chatId: String, completion: @escaping ((Bool)->())) {
        let service = ChatServices()
        service.getChatMessages(chatId: chatId) { (chatMessages) in
            if let chatMessages = chatMessages {
                self.messages = chatMessages
                completion(true)
            } else {
                completion(false)
            }
        }
    }


Then in the ChatServices class there is:

 func getChatMessages(chatId: String, completion: @escaping (([Message]?)->())) {
        guard let id = Auth.auth().currentUser?.uid else { print("Error trying to retrieve messages--user not logged in."); return }
        let db = Firestore.firestore()
        let ref = db.collection("conversation").document(chatId).collection("messages")
        //let query = ref.order(by: "sent_at", descending: false)
        ref.addSnapshotListener { (snapshot, error) in
            if let e = error {
                print("$-- error getting messages for chat user: \(id) chat \(chatId) error: \(e)")
                completion(nil)
                return
            }
            self.parseChatMessages(snap: snapshot, completion: { (messages) in
                if let messages = messages {
                    completion(messages)
                } else {
                    completion(nil)
                }
            })
        }
    }
    
    fileprivate func parseChatMessages(snap: QuerySnapshot?, completion:@escaping (([Message]?) -> ())) {
        var messages = [Message]()
        var count = 0
        guard let snap = snap else { completion(messages); return }
        for document in snap.documents {
            if let url = document.data()["url"] as? String {
                retrievePhotoMessage(document, url) { (chatMessage) in
                    count += 1
                    if let chatMessage = chatMessage {
                        messages.append(chatMessage)
                    }
                    if messages.count == snap.documents.count || snap.documents.count == count {
                        let sortedMessages = messages.sorted{ $0.sentDate < $1.sentDate }
                        completion(sortedMessages)
                    }
                }
            } else {
                retrieveTextMessage(document) { (chatMessage) in
                    count += 1
                    if let chatMessage = chatMessage {
                        messages.append(chatMessage)
                    }
                    if messages.count == snap.documents.count || snap.documents.count == count {
                        let sortedMessages = messages.sorted{ $0.sentDate < $1.sentDate }
                        completion(sortedMessages)
                    }
                }
            }
        }
    }
    
    func retrieveTextMessage(_ document:QueryDocumentSnapshot, completion: @escaping ((Message?) -> ())) {
        if let senderUID = document.data()["sender"] as? String,
            let sentAt = document.data()["sent_at"] as? Int,
            let text = document.data()["text"] as? String,
            let messageId = document.data()["message_id"] as? String {
            let db = Firestore.firestore()
            db.collection("user").document(senderUID).getDocument(completion: { (doc, error) in
                if let doc = doc, doc.exists, let data = doc.data(), let displayName = data["first_name"] as? String {
                    let user = ChatUser(senderId: senderUID, displayName: displayName)
                    let chatMessage = Message(text: text, user: user, messageId: messageId, sentAt: sentAt)
                    completion(chatMessage)
                } else {
                    completion(nil)
                }
            })
        } else {
            completion(nil)
        }
    }
    
    func retrievePhotoMessage(_ document: QueryDocumentSnapshot, _ url: String, completion: @escaping ((Message?) -> ())) {
        if let senderUID = document.data()["sender"] as? String,
            let sentAt = document.data()["sent_at"] as? Int,
            let messageId = document.data()["message_id"] as? String {
            let db = Firestore.firestore()
            db.collection("user").document(senderUID).getDocument(completion: { (doc, error) in
                if let doc = doc, doc.exists, let data = doc.data(), let displayName = data["first_name"] as? String {
                    guard let url = URL(string: url) else { return }
                    self.getData(from: url) { data, response, error in
                        guard let data = data, error == nil, let image = UIImage(data: data) else { return }
                        let user = ChatUser(senderId: senderUID, displayName: displayName)
                        let chatMessage = Message(image: image, user: user, messageId: messageId, sentAt: sentAt)
                        completion(chatMessage)
                    }
                } else {
                    completion(nil)
                }
            })
        }
        completion(nil)
    }
    
    func getData(from url: URL, completion: @escaping (Data?, URLResponse?, Error?) -> ()) {
        URLSession.shared.dataTask(with: url, completionHandler: completion).resume()
    }

**Comment by michaeldebo** [comment]
I fixed the problem. Thanks!
