### ISSUE TITLE
Cannot assign value of type 'UIImage' to type 'MediaItem?'

### ISSUE THREAD

**Issue by BenjaminLiCN** [MessageKit/MessageKit#1198]
Hi 

I was trying to set up MessageKind, the code looks like:
var kind: MessageKind {
    if let image = image {
      return .photo(image)
    } else {
      return .text(content)
    }
  }
where image is UIImage type, then it asked me to change image type to MediaItem.
But I couldn't convert UIImage to MediaItem, so I'm really confused
I checked the source code of MediaItem, it doesn't have an initialiser...

**Comment by BenjaminLiCN** [comment]
fixed by adding following code

`private struct ImageMediaItem: MediaItem {

    var url: URL?
    var image: UIImage?
    var placeholderImage: UIImage
    var size: CGSize

    init(image: UIImage) {
        self.image = image
        self.size = CGSize(width: 240, height: 240)
        self.placeholderImage = UIImage()
    }

}`

**Comment by keithwang5** [comment]
Hi. I just received this error. Could you further elaborate how you solved it with an unrelated struct?

**Comment by Kaspik** [comment]
You need to pass an object/class/struct that conforms to `MediaItem` protocol - not UIImage itself.
