### ISSUE TITLE
UIResponder.keyboardWillChangeFrameNotification fired many times upon hiding keyboard

### ISSUE THREAD

**Issue by lsmilek1** [MessageKit/MessageKit#1199]
Hi,

even in the example app there is UIResponder.keyboardWillChangeFrameNotification fired about 3 - 5 times when keyboard is being dismissed by swipe down. This is causing probably even wrong bottom inset (a bit noticeable in example app). I noticed this behaviour on iOS13. Anyone else having problems with dismissing keyboard?

thanks!

**Comment by batuhangoktepe** [comment]
I have the same problem and I didn't fix yet. Did you find an solution?

**Comment by lsmilek1** [comment]
Unfortunatelly I haven’t found solution. I ended up with following workaround that still cause some artefacts...
- instead of “keyboardWillChange” I register “willHide”, “willShow” and “didChange”
- the issue is noticeable the most during hiding, therefore on first “willHide” I set bool to ignore my custom animations and asyncAfter 0.5sec I set it back.
- “didChange” handle input text view height change, since it is not animated anyway

It is far from perfect, but I spend already more time than I can affort with this issue. So I hope soon will someone come with better fix (perhaps even Apple, since this was not noticeable in later iOS)

**Comment by corentin-yubo** [comment]
Hey @lsmilek1 I have the same problem of you and i have seen your post in StackOverflow here :
https://stackoverflow.com/questions/56584816/swift-uicollectionview-cell-displayed-scrolled-in-to-the-view-incorrectly-when-k

Can you contact me please ? I have sent to you an invitation on Linkedin (Corentin Emonet) thanks!
