### ISSUE TITLE
[iOS 13] InputBarAccessoryView showing on top of presentedViewController

### ISSUE THREAD

**Issue by isupremedyou** [MessageKit/MessageKit#1203]
**MessageKit version(s):** 
3.0.0-beta-swift5
**iOS version(s):** 
iOS 13
**Devices/Simulators affected:** 
iPhone 11
**A well written description of the problem you are experiencing:**
The messageInputBar is showing above the `presentedViewController` when a user puts the app into the background and then returns it to the foreground
**Please provide complete steps to reproduce the issue:**
NOTE: in iOS 13 Apple introduced a new card style for modal presentations, so perhaps this is related to other changes that came with that.

**This only occurs when the `inputTextView` is currently the first responder while a VC is being presented**

- My presenting VC is a subclass of `MessagesViewController` and it is calling `present(:animated:completion:)`
- The presented VC shows in the iOS 13 modal card style, with the messageInputBar being hidden underneath (as expected)
- If the user moves the app to the background at this point, and then returns to the app, the messageInputBar is now showing above the presented VC (see attached image)

**For UI related issues, please provide a screenshot/GIF/video showing the issue:**
Video: https://www.dropbox.com/s/h9c3nf3hpmmu9me/Screen%20Recording%202019-10-18%20at%2012.33.23%20PM.mov?dl=0
Image: https://www.dropbox.com/s/qcjosi8noduspgs/Screenshot%202019-10-18%2012.34.05.png?dl=0

**Comment by isupremedyou** [comment]
I should note that one workaround I have tried is to always call `resignFirstResponder()` on  `inputTextView` when `viewWillDisapper(:)` is called, but in iOS 13 this method never gets called during a modal presentation.

**Comment by atacand1920** [comment]
Try to put modalPresentationStyle .fullscreen before present method , it will remove the card style presentation

**Comment by isupremedyou** [comment]
@atacand1920, yes but this is for the future of the framework, iOS 13 encourages the card style modal.

**Comment by Vaberer** [comment]
I'm having the same issue when trying to present a new UIWindow above the MessagesViewController.

Would love to see a workaround for this.

**Comment by musa-almatri** [comment]
I have the same issue. Currently handling it by showing and hiding the input bar manually when presenting another view controller `self.messageInputBar.isHidden = true`. Hope there is a better way to do this.
