### ISSUE TITLE
url link tags #tags are not selected. 

### ISSUE THREAD

**Issue by arishanapalli** [MessageKit/MessageKit#1206]
Hi

How the links  #tag @name are clickable / detector ? 

unable to click on urls shared www.google.com #username @person
 are not clickable / detected ...!  so I can have my logic based on selection items.
Can we have it in advanced Example ?

Can we get those sample implementation part..

**Comment by nathantannar4** [comment]
@JulienKode 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
