### ISSUE TITLE
Space in bottomLabel

### ISSUE THREAD

**Issue by denikaev** [MessageKit/MessageKit#1207]
How can I delete space in bottom label? Need install on .zero. Pls check screenshot
![479D0270-3B4D-44A2-98AC-EB1C1A511734](https://user-images.githubusercontent.com/29748197/67320287-afdb9600-f516-11e9-9a79-b7788a9720d4.jpeg)

**Comment by isupremedyou** [comment]
Hi @denikaev, thanks for your question. You can adjust the textAlignment and textInsets properties by adjusting the value on the flow layout of the MessagesCollectionView.

First, you need to subclass Messages Collection View. Then in `viewDidLoad()` you can try the following:
```
if let layout = messagesCollectionView.collectionViewLayout as? MessagesCollectionViewFlowLayout {
  let bottomLabelAlignment = LabelAlignment(textAlignment: .right, textInsets: .zero)
  layout.setMessageOutgoingMessageBottomLabelAlignment(bottomLabelAlignment)
}
```

I hope that helps. Keep in mind that you would need to make adjustments for the incoming message bottom label as well.

**Comment by denikaev** [comment]
Hi, it helped, thanks :)
