### ISSUE TITLE
Using newest InputBarAccessoryView with current release of MessageKit?

### ISSUE THREAD

**Issue by bmt2018** [MessageKit/MessageKit#1208]
I'm currently using MessageKit 3.0.0 (via Cocoapods) in an iOS app that I'm developing.  I noticed when I run 'pod outdated' that there is a newer version (4.3.1) of the InputBarAccessoryView dependency available but the .podspec file for MessageKit 3.0.0 currently references InputBarAccessoryView like this:

`s.dependency 'InputBarAccessoryView', '~> 4.2.2'`

...which obviously means I'll only get a version of InputBarAccessoryView up to 4.2.2.  I'm somewhat new to iOS development and and Cocoapods but I'm wondering is there any way for me to pull in the latest InputBarAccessoryView (with Swift 5 updates) or does the MessageKit .podspec file have to be updated?  Thanks very much!

**Comment by thiagocenturion** [comment]
Up! I'm waiting for a solution to build the MessageKit 3.0.0 + InputBarAccessoryView in Swift 5 project.
