### ISSUE TITLE
Podfile, installation

### ISSUE THREAD

**Issue by mikelanza** [MessageKit/MessageKit#1209]
Hello,

I'm unclear on the exact Podfile I should create for Swift 5 (using MessageKit 3.0.0).  Can you show me this?

Thanks.

- Mike

**Comment by clay-mindoula** [comment]
I'm using Xcode 11.2.x, Swift 5.1 and MessageKit 3.0.0, the following was extracted from my pod file:

```
platform :ios, '11.1'
inhibit_all_warnings!
ENV['SWIFT_VERSION'] = '5'
use_frameworks!

pod 'MessageKit', '3.0.0'
 
```
