### ISSUE TITLE
Allow cellTopLabel & cellBottomLabel to be positioned inside of the messageContainer

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#121]
From #117:
![30277246-e66207a2-970f-11e7-9ad1-3abe129a0c5a](https://user-images.githubusercontent.com/7445580/30329948-78298f82-9799-11e7-88b4-0115a67d6d73.jpg)
We should allow the user to be able to have the `cellTopLabel` & `cellBottmLabel` inside of the `messageContainer`.

This was pretty painful to try and get done in `v0.7.0` but with the latest refactoring of the `MessagesCollectionViewFlowLayout` I think it should be achievable.

### Possible approach:
- When sizing the height of the `messageContainer` we have to add the height of both the `top` and `bottom` labels.
- When sizing the width of the `messageContainer` we make sure the minimum width is not less than the width of any of the labels it contains.
- The API for this would be adding more `enum` cases to the `LabelAlignment` enum or an associated value:
    - `messageLeading(inContainer: Bool)`
    - `messageTrailing(inContainer: Bool)`

**Comment by mohammadshalhoob** [comment]
thanks SD10 .

**Comment by SD10** [comment]
MessageKit will never support this as a first-class feature. The reason is making the message container's size dependent on 3 different NSAttributedStrings would be reintroducing the performance problems we aim to solve in #580. 

However, this should be easily achievable to do on your own after #579, assuming that you make a few reasonable assumptions of the sizes of this text so that you don't have to size them on the fly. As a library however, it's a bit too difficult for us to make these assumptions.
