### ISSUE TITLE
messageInputBar appear with slow animation 

### ISSUE THREAD

**Issue by Mustafa-Ezzat** [MessageKit/MessageKit#1211]

**Comment by Mustafa-Ezzat** [comment]
Scenario:
Using UIDocumentInteractionController to preview image
When preview messageInputBar is Hidden (normal)
When dismiss messageInputBar is show with wiered slow animation 
MessageKit version 3.0
Swift 5
iOS 13
iPhone 6s

**Comment by ajeetpratap** [comment]
I am having the same issue. have you figured it out

**Comment by AramSemerjyan** [comment]
Same thing. Any updates?

**Comment by bilaalrashid** [comment]
I’m also experiencing this issue

**Comment by kinoroy** [comment]
@bilaalrashid Please open a new issue with the appropriate details if you're experiencing this. It's more likely to be seen by other contributors that way. Thanks! 🤗
