### ISSUE TITLE
User interaction is not work!

### ISSUE THREAD

**Issue by azizimarouan** [MessageKit/MessageKit#1219]
didTapMessage and other methods not work

**Comment by azizimarouan** [comment]
I added an UITapGestureRecognizer to messagesCollectionView to dismiss the keyboard , all the other gestures become disabled, how to fix that.

**Comment by kinoroy** [comment]
If you add a gesture recognizer to the messages collection view, you need to implement `UIGestureRecognizerDelegate` and allow simultaneous recognition like so:
```` swift
  func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool {
    return true
  }
````
Make sure you also set yourself as the delegate on your gesture recognizer.
