### ISSUE TITLE
How to animate on collection view cell ( Chat bubble)

### ISSUE THREAD

**Issue by rajeshfintel** [MessageKit/MessageKit#1221]
Hi All,

We are trying to do some animation on Collection view cell but we are not able to achieve smooth animation like this example : [https://dribbble.com/shots/6428387-Messenger-Mobile-Concept](https://dribbble.com/shots/6428387-Messenger-Mobile-Concept)

Could you please any idea to implement smooth animation on chat bubble (Collectionview cell)

Please let us know any default animation available in MessageKit ?

Please let us know the following things:

Swift 5.0 version 
Latest "MessageKit" library

**Comment by kinoroy** [comment]
This is currently a pending feature request (Issue #759). At this time you would have to implement it yourself. You can check out how they implemented it in JSQMessagesViewController : https://github.com/jessesquires/JSQMessagesViewController/blob/develop/JSQMessagesViewController/Layout/JSQMessagesCollectionViewFlowLayout.m but that project is written in Objective-C and also deprecated, so it may use outdated APIs, but you could probably get the gist of it.
