### ISSUE TITLE
Working with incoming messages

### ISSUE THREAD

**Issue by Montymer** [MessageKit/MessageKit#1224]
Hi, I am working on a school project. We are creating a messaging app. For sockets in backend, we are using https://pusher.com/channels . The connection to it works well and I get json data that I already got parsed into things I need. The problem is, that I am trying to create a new message from the data that I get from Pusher. And I am not sure if I understand how to do it. I managed to get the new message into the "Messages" array, but the message itself isn't showing in program. 

```swift
 func incomingMsg(incData: String){
        let data = Data(incData.utf8)
        var tempname: String = ""
        var tempMsg: String = ""
        do {
            // make sure this JSON is in the format we expect
            if let json = try JSONSerialization.jsonObject(with: data, options: []) as? [String: Any] {
                // try to read out a string array
                if let name = json["name"] as? String {
                    tempname = name
                    print(name)
                }
                if let msg = json["message"] as? String {
                    tempMsg = msg
                    print(msg)
                }
                
                let tempUser = User(userId: "1", name: tempname, email: "example@example.cz")
                
                let newMessage = Message(user: User(userId: "1", name: "Will Smith", email: "example@example.cz"), msgtext: tempMsg, messageId: UUID().uuidString)
                                  self.messages.append(newMessage)
                                  self.messagesCollectionView.reloadData()
                                  self.messagesCollectionView.scrollToBottom()
                print(messages.count)
            }
```

Few variables like email and such are written by myself, because Pusher is not yet connected to our database. After this code runs, the messages.count shows 1 but no message is shown in the app. Any advices about my problem or any other things about my code? I am new to swift and still learning :-)
Thank you for your advice!

**Comment by kinoroy** [comment]
Your code snippet does not give enough information to determine why "messages aren't showing up in the program". Please provide a [Minimal, Complete, Reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help others help you figure out your issue. You will need to include things like your view controller, your model, delegates, etc. As much as necessary to reproduce and thus debug the problem.
