### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by Drusy** [MessageKit/MessageKit#1225]
Since Xcode 11 includes Swift Package Manager, it would be nice to support it

**Comment by kinoroy** [comment]
Unfortunately SPM doesn't yet support assets. MessageKit contains an asset bundle and so cannot yet support SPM.

**Comment by Drusy** [comment]
I think this may come sooner or later. Hopefully sooner :)
Should we keep track of this issue or open it again when the SPM feature is out ?
