### ISSUE TITLE
🦊🐹🐶🐰 Support Animojis 🐔🐼🐷🐮

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#123]
### HARD DEADLINE
MessageKit `v0.9.0` 😁

**Comment by Sherlouk** [comment]
😂

**Comment by Sherlouk** [comment]
From what I can tell Apple haven't brought out an API for Animojis, instead it just looks like the messages are turned into traditional video formats and played in messages (that's how they've managed to get legacy support)

Wouldn't be surprised if someone creates their own library to do it with an interface etc

**Comment by SD10** [comment]
Looks like you're going to have your work cut out for you then 😃 But seriously, it would be fun to try after getting the core project in a better place

**Comment by SD10** [comment]
Closing this because I'm done joking with @Sherlouk 😂
