### ISSUE TITLE
sendButton and delegate method not triggered

### ISSUE THREAD

**Issue by M0in4** [MessageKit/MessageKit#1232]
- What version of MessageKit are you using? **Last development branch**
- What version of iOS are you running on? **13.3**
- What version of Swift are you running on? **Swift 4.2**
- What device(s) are you testing on? Are these simulators? **All devices**
- Is the issue you're experiencing reproducable in the example app? I have no idea.

```swift
                            self.messagesCollectionView.messagesDataSource = self
                            self.messagesCollectionView.messagesLayoutDelegate = self
                            self.messagesCollectionView.messagesDisplayDelegate = self
                            self.messagesCollectionView.messageCellDelegate = self
                            
                            if let layout = self.messagesCollectionView.collectionViewLayout as? MessagesCollectionViewFlowLayout {
                                layout.textMessageSizeCalculator.outgoingAvatarSize = .zero
                                //layout.textMessageSizeCalculator.incomingAvatarSize = .zero
                            }
                            self.messagesCollectionView.reloadData()
                            self.messagesCollectionView.scrollToBottom()
                            
                            self.messageInputBar.delegate = self
                            self.messageInputBar.inputTextView.delegate = self
```

When I was on iOS 12 the delegate was called correctly but with ios13 it's not
I can't click the 'sendButton' even if the user interaction is enabled and I don't got any delegate of cell like avatar click or cell click

**Comment by AMJ-7** [comment]
I have same issue !!!!

**Comment by M0in4** [comment]
Reopen. Never fixed

**Comment by Kaspik** [comment]
Does it work on new 3.1.0-beta.1 version?

**Comment by M0in4** [comment]
Its still bugged

**Comment by Kaspik** [comment]
We need a way to repro - either example project, or please create repro-project. Thanks!

**Comment by Kaspik** [comment]
Solved - `InputBarAccessoryViewDelegate` has new names for functions. Closing.
