### ISSUE TITLE
Quoted Content

### ISSUE THREAD

**Issue by eemi2010** [MessageKit/MessageKit#1234]
Hello there,
Please what would be the best to add a quoted view like on the image below. I tried to copy the code of the default text view and add a vertical stack view with no success.

Cheers

![QuotedView](https://user-images.githubusercontent.com/2421746/71782394-b89e1d00-2fd9-11ea-8abd-63f4414e413a.png)

**Comment by MuhtasimTanmoy** [comment]
Looking for same thing though no solution found.

**Comment by fukemy** [comment]
does anyone solved this? im using attributetext to display quote but it's still good solution
