### ISSUE TITLE
Making MessageKit Catalyst-compatible

### ISSUE THREAD

**Issue by yuriymacdev** [MessageKit/MessageKit#1238]
On macOS Catalyst, while MessageView itself is tolerable (apart from some weird behavior with the context menu, which can be customly fixed), the text input view at the bottom doesn't render at all:

![image](https://user-images.githubusercontent.com/50522970/72952529-d79efc00-3d9a-11ea-81ee-cd0814085fda.png)

Is there a plan to make InputBarAccessoryView Catalyst-compatible? 
If not, could you share your thoughts on why it may not show up, and I would be willing to create a pull request whenever I get time?
Thanks!

**Comment by Alexander-Frost** [comment]
Have you tried printing out the frame coordinates for the bar to verify it exists?

**Comment by yuriymacdev** [comment]
> Have you tried printing out the frame coordinates for the bar to verify it exists?

It's all zeros on macOS. It looks like the control never gets added as a subview on macOS (willMove toSuperview: is not called on Mac)

**Comment by Alexander-Frost** [comment]
Are you able to add other items, ie: a uiview, as subviews? It sounds like the frame for the input bar view hasn't been created or it hasn't been added as a subview.

**Comment by yuriymacdev** [comment]
> Are you able to add other items, ie: a uiview, as subviews? It sounds like the frame for the input bar view hasn't been created or it hasn't been added as a subview.

Yes, other subviews can be added:
<img width="775" alt="image" src="https://user-images.githubusercontent.com/50522970/73029584-792c5900-3e40-11ea-8a0f-7c42cc2ce5b4.png">

**Comment by yuriymacdev** [comment]
So the problem is with the fact that the Message Input Bar is not a normal subview, manually stacked below the MessagesView, but an [inputAccessoryView](https://developer.apple.com/documentation/uikit/uiresponder/1621119-inputaccessoryview) which is glued to the screen keyboard and retrieved by an inputAccessoryView call made by the system.

Obviously, Catalyst apps don't get a screen keyboard at all (since Macs always have hardware keyboards), and the MessagesViewController's method -(UIView*)inputAccessoryView is never called by UIInputResponderController as it does on iOS => the text bar never gets added onto the screen.

Possible solution: conditionally compile for Catalyst, forcibly adding the inputAccessoryView as a subview to the bottom of the window.

**Comment by yuriymacdev** [comment]
The control needs custom styling for dark mode, correct constraints and probably needs some custom finishing to get a seamless behavior, otherwise seems to be working.
Here's what I got. 
![image](https://user-images.githubusercontent.com/50522970/73040281-a76e6080-3e61-11ea-95fd-afee342b6706.png)

**Comment by Alexander-Frost** [comment]
That looks great. Glad you could hack together a solution.

**Comment by jariz** [comment]
Yes, this helps absolutely no one trying to use this library with Catalyst! Thanks for not explaining this whatsoever.

**Comment by yuriymacdev** [comment]
@jariz 
Like I said, in [https://github.com/MessageKit/MessageKit/issues/1238#issuecomment-577959325](url), you only need to add the inputAccessoryView as a subview manually to the bottom of the window and handle all of its constraints manually, instead of expecting the system to add it as a, well, Input Accessory View.

**Comment by nathantannar4** [comment]
fyi @yuriymacdev the InputBarAccessoryView (MessageInputBar) already a keyboard manager which can bind the view as a subview. Are you using that? It will handle things like scroll to dismiss and auto sizing
