### ISSUE TITLE
Direct Scroll to bottom rather show the top message and then scroll to bottom.

### ISSUE THREAD

**Issue by Faari7** [MessageKit/MessageKit#1244]
Is there a way to scroll the messages to the most recent message while going into the chat room. currently, i am reloading the Collection view and scroll to the bottom. In case of more messages, it firs show me the top message and then scroll and show me the most recent ones, i want it to take me to the bottom without showing me the top messages. 

Also is there is any other way where we can store user scrolling positions and then show them exactly where they last were just like Whatsapp is doing.

**Comment by TayyabAli652** [comment]
try this to scroll the most recent message without show top messages first.
   

>         self.messagesCollectionView.reloadData()
>         let indexPath = IndexPath(row: 0 , section: self.messageList.count - 1)
>         self.messagesCollectionView.scrollToItem(at: indexPath, at: .bottom, animated: false)

**Comment by TayyabAli652** [comment]
try this to scroll the most recent messages without showing top messages first.

>     self.messagesCollectionView.reloadData()
>     let indexPath = IndexPath(row: 0 , section: self.messageList.count - 1)
>     self.messagesCollectionView.scrollToItem(at: indexPath, at: .bottom, animated: false)

**Comment by Faari7** [comment]
Yeah i am doing the same. I just wanted to know if there is any other
better way to do it.

**Comment by xsoti** [comment]
Not sure if solution above works for you, beacuse in my case I coudn't scroll to bottom in viewWillAppear and I end up with this workaround:

  ```
 override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        
        if !subviewsLoaded {
            messagesCollectionView.reloadData()
            
            messagesCollectionView.scrollToBottom()
            subviewsLoaded = true
        }
    }
```

**Comment by hessu** [comment]
The viewDidLayoutSubviews workaround from @xsoti works for me.

Workarounds in viewWillAppear happened too late when using NSFetchedResultsController for loading messages and the first messages would flash briefly.

Workarounds with transforms to rotate views caused layout issues (margins not right in top and bottom), and the scroll bar got rotated to left.

**Comment by lewis-smith** [comment]
I would like to keep this issue alive, I see this and my testers have commented on it.

i will try some of the work arounds mentioned above, but would def be nice to have it working out of the box

**Comment by austinwright** [comment]
@lewis-smith, MessageKit does not provide or endorse any specific data layer for the message content, that is entirely up to you to implement and control. As such it doesn't make sense for MessageKit to provide an 'out-of-the-box' functionality. Any plain UICollectionView with many items could have the same UI/UX problem when loading/appearing on the navigation hierarchy, depending on how the data-source has been implemented.
