### ISSUE TITLE
Regarding MessageKit in 2020

### ISSUE THREAD

**Issue by hyouuu** [MessageKit/MessageKit#1245]
Firstly thanks to @SD10 @nathantannar4 @zhongwuzw for the hard work building MessageKit! 

After the first half of 2019, it seems that all 3 core members have been quite busy (I remember Nathan is working for Apple now and can't contribute to open source anymore?), so this repo has become quite stale. Thanks to Zhong, today merge permission was granted to me and @moldovaniosif, and I would like to try to bring this awesome project back to life if possible, so opening a discussion here for people to chime in - what do you feel about MessageKit at this stage and what's the best way to keep it moving forward?

I just cleaned up many stale branches, merged in a few straightforward PR fixes, and plan to make another release from `development` soon (probably call it 3.1? thoughts?) as it's already ~60 commits ahead - let me know if you're using `development` and how stable it has been for you. My side project has been on that branch for over a year, and so far so good.

Hopefully this can bring people back to contribute to MessageKit together!

**Comment by jakubwarchol** [comment]
Looking forward to seeing more activity around here :)

**Comment by Kaspik** [comment]
Thanks for great news @hyouuu 

I looks like also branch `3.0.0-swift5` was removed (it included version `3.1.0` already as well as `InputBarAccessoryView` version `4.3.1` instead of `4.2.2` in latest CocoaPods version `3.0.0`.

Could we please update 3.1.0 asap so we don't have to deal with _downgrade_ of `InputBarAccessoryView` and also don't have to use master/development?

**Comment by hyouuu** [comment]
Interesting @Kaspik - what do you mean it included 3.1.0? Do you mean the numbering in podspec? I think that's merged into 'development' if you look at https://github.com/MessageKit/MessageKit/blob/development/MessageKit.podspec

**Comment by hyouuu** [comment]
For now you could point to 'development' in your Podfile like this:
`pod 'MessageKit', :git => 'https://github.com/MessageKit/MessageKit.git', :branch => 'development'`

**Comment by Kaspik** [comment]
Yes, that's what I mean. Yeah, I pointed to development, but I don't want to leave it like that for long if it's active branch. Release would be great! :)

We might have some PR to the `InputBarAccessoryView` too - are you active there as well?

**Comment by hyouuu** [comment]
Gotcha! That is @nathantannar4 's repo - Nathan would you like to grant write access to some of us to keep that moving forward?

**Comment by Kaspik** [comment]
What is https://github.com/MessageKit/MessageInputBar for then? 😄

**Comment by hyouuu** [comment]
I think Nathan replaced it with the one in his own repo and renamed to `InputBarAccessoryView`

**Comment by hyouuu** [comment]
Let's see what Nathan has to say, and if there's no response for a while we can fork and move forward

**Comment by hyouuu** [comment]
btw @Kaspik @jakubwarchol  wondering if you could review https://github.com/MessageKit/MessageKit/pull/1247? Not sure how the permissions work for code reviews

**Comment by alexmomotiuk** [comment]
It's awesome news, ready to help.

**Comment by hyouuu** [comment]
Thanks for the review @alexmomotiuk ! @Kaspik if you get time could you help make a PR to update the CHANGELOG in `development` for the past changes? I think the recent ones didn't include sufficient changes there; I can hop in to help with that but kind of busy this week. After the changelog change I'm planning to make a 3.1 release asap, and after 3.1 release update swift version to 5.1

**Comment by kinoroy** [comment]
There seems to be quite a few old open issues for things which are already implemented, so I'm going to go through and clean some of them up.
Are you guys all on the [Slack](https://join.slack.com/t/messagekit/shared_invite/MjI4NzIzNzMyMzU0LTE1MDMwODIzMDUtYzllYzIyNTU4MA)?

**Comment by Kaspik** [comment]
@hyouuu I should have some time this week to do it. :)

@kinoroy I wasn’t until now, thanks for the link. Are there any channels we should know about?

**Comment by kinoroy** [comment]
@Kaspik I's pretty dead for the most part, no secret channels I know about. I just created #revive-messagekit we can use it to talk about plans moving forward?

**Comment by SD10** [comment]
Yeah I agree the repo is very stale right now. We need a Swift 5 update (see #1250). @nathantannar4 and I have been experiencing some very large life changes since the end of 2019 and have had less time for open source. I moved to Washington D.C. two weeks ago and have been job hunting. Hoping to finish interviews soon and have more time for open source again ❤️ The Slack channel is a good idea I've commented there 🍻 Thanks @hyouuu

**Comment by exceptioncatcher91** [comment]
@hyouuu When do you plan the release of 3.1? Will this new version be compatible with the latest version of InputBarAccessoryView (4.3.2 podspec dependency)?

**Comment by Kaspik** [comment]
@exceptioncatcher91 The release is planned soon but InputBarAccessoryView 4.3.2 is not on CocoaPods yet - so it probably will go out with 4.3.0.

**Comment by marcusrohden** [comment]
Hello guys,  I went to do a full clean on my project pods and when I tried to reinstall I got an error informing that pods couldn't find the '3.0.0-swift5' branch. Can anyone point me which branch should I set to get a stable version for Swift 5?

**Comment by Kaspik** [comment]
@marcuslindemannrohden  At this moment, you need to point to `development` or specific commit, but there will be new version `3.1.0-beta` on cocoapods available today. Stay tuned!

**Comment by SD10** [comment]
Closing this as project is moving forward with the help of additional core team members

**Comment by Kaspik** [comment]
Final stable release 3.1.0 is out now. 🎉
