### ISSUE TITLE
How do you add padding to a custom cell?

### ISSUE THREAD

**Issue by brideout** [MessageKit/MessageKit#1262]
- What version of iOS are you running on? 13
- What version of Swift are you running on? 5
- What device(s) are you testing on? Are these simulators? iPhone 11 Pro Simulator

I followed the custom cell tutorial and used the code from the example project. My problem I am running into is how to add padding around the cell. Should I be trying to set the padding in the 
```swift
CustomMessagesFlowLayout: MessagesCollectionViewFlowLayout
```
class or somewhere else? I am able to add padding and insets for a standard cell with no problem in the view controller.

<img width="405" alt="Screen Shot 2020-02-28 at 8 48 31 AM" src="https://user-images.githubusercontent.com/16547931/75558261-2b8aa980-5a07-11ea-88ec-396bf8d1e2ec.png">

**Comment by austinwright** [comment]
If you are using a subclass of `MessageSizeCalculator`, then you would probably need to set
```swift
    public var incomingMessagePadding = UIEdgeInsets(top: 0, left: 4, bottom: 0, right: 30)
    public var outgoingMessagePadding = UIEdgeInsets(top: 0, left: 30, bottom: 0, right: 4)
```
either directly, or via the `MessagesCollectionViewFlowLayout` API:
```
    public func setMessageIncomingMessagePadding(_ newPadding: UIEdgeInsets) {
...
    public func setMessageOutgoingMessagePadding(_ newPadding: UIEdgeInsets) {
```

I set my custom padding during the `viewDidLoad` lifecycle workflow, however you should be able to configure these at any time and then invalidate the collectionView's layout and/or reload specific items or a whole section or the whole collection.
