### ISSUE TITLE
Animated "typing" bubbles not showing

### ISSUE THREAD

**Issue by lewis-smith** [MessageKit/MessageKit#1265]
- What version of MessageKit are you using?
3.1.0-beta.1  👻

- What version of iOS are you running on?
I see it on iOS 13.3.1 & iOS 13.4 b3

- What version of Swift are you running on?
5

- What device(s) are you testing on? Are these simulators?
iOS 13.3.1 = real 10XS
iOS 13.4 b3 = iPhone 11 simulator

- Is the issue you're experiencing reproducable in the example app?
Yes. I see it in the "Advanced" example

--

In the MessageKit beta the animated "typing" bubbles don't show

![Simulator Screen Shot - iPhone 11 - 2020-03-04 at 10 18 20](https://user-images.githubusercontent.com/1905433/75870477-ec8f9600-5e02-11ea-8a17-e2d65523e360.png)

I see this in my own app too

**Comment by lewis-smith** [comment]
I will take a look and see if I can figure it out, but if anyone knows the problem right away do let me know!

**Comment by martinpucik** [comment]
Fixed in #1266 💪
