### ISSUE TITLE
Change Message font

### ISSUE THREAD

**Issue by ahmedwasil** [MessageKit/MessageKit#1267]
Hey,

Which function to override to set the font for the message bubbles. I have seen in previous issues about setting attributedString in MessageKind or MessageData. However not sure how to access and set this? Is this to be set in the setup code or a override function?

Using Message Kit 0.13.1
and Swift 4.

**Comment by martinpucik** [comment]
Hey @ahmedwasil, you're right, you need to use `NSAttributedString` if you want to set a custom font for your messages.

You can refer to the Example project how to achieve this.

1. You provide a model for every message that conforms to `MessageType` protocol, like this https://github.com/MessageKit/MessageKit/blob/7729b8ce3dbb78c3bde8113ed3fcf455d81235f5/Example/Sources/View%20Controllers/ChatViewController.swift#L157-L159

2. In that model, you set the `kind: MessageKind` property to `.attributedText` value, like this
https://github.com/MessageKit/MessageKit/blob/7729b8ce3dbb78c3bde8113ed3fcf455d81235f5/Example/Sources/Models/MockMessage.swift#L115-L117
and like this
https://github.com/MessageKit/MessageKit/blob/7729b8ce3dbb78c3bde8113ed3fcf455d81235f5/Example/Sources/Models/MockMessage.swift#L100-L101

3. To see an example how to format attributed string, that you can then pass as an argument to the `.attributedText`, you can look here
https://github.com/MessageKit/MessageKit/blob/7729b8ce3dbb78c3bde8113ed3fcf455d81235f5/Example/Sources/Data%20Generation/SampleData.swift#L96-L129

**Comment by austinwright** [comment]
@ahmedwasil - Martin is right, this is documented in a couple places, as well as showcased in the Example app. If you have any more questions feel free to open another issue with the `question` label.

That being said, I would advise that you use a more recent release of the framework - version 3.0.0 is the latest stable release. The 3.0.0 Swift 5 branch is also very stable but was never released. And the 3.1.0 beta is very close to being released. You will find more examples and documentation using the latest version, as well as receive better support as many maintainers and other contributors are using these more recent versions.
