### ISSUE TITLE
Typing in MessageInputBar and pressing the Return Key Causes a delay while Resizing

### ISSUE THREAD

**Issue by howardevans21** [MessageKit/MessageKit#1268]
I am having difficulty when I type in the message input after all cells have been loaded successfully, but when I press the return key, a delay occurs while the message bar resizes. After the cursor reaches to the very bottom, the message bar stop resizing and no delays. It seems when the message bar resizes, a delay happens when I tap on the return to go to the next line. 

I am using Message Kit 3.0.0. 

Can anyone please offer any suggestions or help ?

**Comment by howardevans21** [comment]
![613AE05B-F402-46F7-865B-FB63885D002F](https://user-images.githubusercontent.com/29368134/76137402-968d3f00-600a-11ea-99f1-c56225e92ff1.jpeg)

**Comment by Kaspik** [comment]
Hey, is the same happening on MessageKit 3.1.0-beta.1?

**Comment by howardevans21** [comment]
@Kaspik I am using the 3.0.0 version. I copied the same example code in my project, but still got the issue.

**Comment by austinwright** [comment]
@howardevans21, a few questions:

1. Are you overriding `func textView(_ textView: UITextView, shouldChangeTextIn range: NSRange, replacementText text: String) -> Bool {`?
2. Or doing any other heavy text searching / calculations when the inputbar text changes?
3. Are you doing any intense calculations on your views or content position when the input bar changes its height?
4. How much of a delay are you experiencing?
5. Is the delay related to the view rendering or is it an input lag?
6. Can you post a GIF or video of the problem? 

Try running instruments with the time profiler. Make sure you long-press the record button, select 'recording options', and check the 'record waiting threads' checkbox.

**Comment by howardevans21** [comment]
@austinwright Hi, I was able to resolve the issue. The problem was me overriding the textView function. After removing it resolved the issue. Thanks so much for your support!
