### ISSUE TITLE
protocol witness for MessagesDataSource.messageForItem(at:in:) in conformance

### ISSUE THREAD

**Issue by KPR7168** [MessageKit/MessageKit#1269]
Hi there,

We're experiencing a number of crashes that says  ``` EXC_BREAKPOINT
protocol witness for MessagesDataSource.messageForItem(at:in:) in conformance ``` and we can't really pinpoint why it is happening. Plz send help 🙏🏼

Versions:
- MessageKit (3.0.0)
- Actual iOS 11 - 13 devices
- Swift 4
- Can't reproduce it in the example or my own app.

Here is what the crash looks like:
![image](https://user-images.githubusercontent.com/5600349/76154088-853b5400-612a-11ea-8df5-645e96164f33.png)

And this is my CustomMessageFlowLayout class:
![image](https://user-images.githubusercontent.com/5600349/76154105-cf243a00-612a-11ea-9e3b-fe332ff16a30.png)

**Comment by kinoroy** [comment]
It might be that in the call to `messageForItem(at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView)` there is something happening like you are trying to access an element of an array which is out of bounds or you have some arithmetic overflow. 
Double check any array accesses or integer arithmetic for potential boundary condition bugs in your implementation of `messageForItem(at:, in:)` in your `MessagesDataSource`

**Comment by KPR7168** [comment]
Thanks for your reply. But, if that's the case though, shouldn't we get indexOutOfBound crash instead?

**Comment by kinoroy** [comment]
@KPR7168  `EXC_BREAKPOINT` is a Swift trap. That is, code generated by the Swift compiler has detected some sort of precondition failure. These precondition failures are things like a force unwrap of nil or an out of bounds array access, integer overflow, etc. Since this is happening specifically in `messageForItem(at:in:)`, I’d have to see your implementation of that method to potentially see what’s going on.

**Comment by KPR7168** [comment]
@kinoroy Thank you for your suggestion 🙏🏻. I took some time to go through any lines that are trying to get the element from an array and place a guard around it to prevent out of bounds and it seems to fix it.
