### ISSUE TITLE
how to  use you message kit in project 

### ISSUE THREAD

**Issue by irfanabdulkhaliq** [MessageKit/MessageKit#1271]
Hello! I am using the latest version of MessageKit, Xcode and iOS.

I want to use message kit in my project but I don't  know how to use it. Can anyone tell me how to add message kit in project. 

I checked the example but I don't understand . 

thankx

**Comment by Kaspik** [comment]
Hey!

There is Quick Start guide - https://github.com/MessageKit/MessageKit/blob/master/Documentation/QuickStart.md
Then after understanding this, the example project should help you more. :)

I hope this helps!
