### ISSUE TITLE
messageInputBar.stackViewItems on the left are not showing

### ISSUE THREAD

**Issue by frnkwk** [MessageKit/MessageKit#1275]
Hello, I'm using MessageKit 3.1.0-beta1 on iOS 13.3 simulator, Xcode 11.3.1, Swift 5.

When I set a left button on messageInputBar like below, the button is not showing.
```swift
messageInputBar.setStackViewItems([cameraButton], forStack: .left, animated: false)
```

If I set `.right`, `.bottom`, `.top ` instead of `.left`, the button is showing correctly.

**Comment by Kaspik** [comment]
Hey @frnkwk - could you please try to repro this in Example project or create a repro project for us and add it here? Thanks!

**Comment by martinpucik** [comment]
Hey @frnkwk could you try to set
```swift
messageInputBar.setLeftStackViewWidthConstant(to: 52, animated: false)
```

before setting the input button? 

```swift
messageInputBar.setStackViewItems([cameraButton], forStack: .left, animated: false)
```

**Comment by frnkwk** [comment]
Hi @martinpucik -  It works! Also, I found `setRightStackViewWidthConstant` in Example project. Thanks!
