### ISSUE TITLE
Inserting Images into Chat view while they are uploading

### ISSUE THREAD

**Issue by ahmedwasil** [MessageKit/MessageKit#1279]
I have implemented the camera and image picker functions, currently when i post a picture it takes  about 10/20 seconds for it to be shown in the chat view.

Is there a way where once I have selected the image i want to send, it is immediately pushed into the chat view whilst it is still uploading to firebase?

Also when launching the chat view, no images are shown immediately but appear on in the view once downloaded. Is there a way activity view is shown while the image is downloading?

```swift
func messageStyle(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> MessageStyle {
    switch message.kind {
    case .photo:
        let configurationClosure = { (containerView: UIImageView) in
            let imageMask = UIImageView()
            imageMask.image = MessageStyle.bubble.image
            imageMask.frame = containerView.bounds
            containerView.mask = imageMask
            containerView.contentMode = .scaleAspectFill

            containerView.kf.indicatorType = .activity
            containerView.kf.indicator?.startAnimatingView()
                
            let m = message as? Message
            print(m)

            guard
                let message = message as? Message,
                let url = message.downloadURL
            else {
                print("Could not convert message into a readable Message format")
                return
            }

            print("Setting image to \(url.absoluteString)")

            containerView.pin_setImage(from: url)
        }
        return .custom(configurationClosure)
     default:
        return .bubble
    }
}
```

**Comment by kinoroy** [comment]
You are entirely in control of what messages are shown at any time. When the user presses send you can immediately insert a temporary `Message` object containing your photo message into wherever you are storing your messages locally, and then reload the collection view/do a batch update. Just save a temporary copy of the image to a local URL, and use that URL as the image source in your temporary `Message` object. When you upload the image and successfully post the message to the backend, you can update or replace that temporary message object. Any implementation of this is highly dependent on how your app is structured.

You can definitely also show an activity view. `configureMediaMessageImageView(imageView:message:indexPath:messagesCollectionView:)` in your `MessagesDisplayDelegate` gives you full access to the `imageView` where you can add an activity indicator while you load your image. Some image loading libraries like KingFisher include activity indicator support.

**Comment by ahmedwasil** [comment]
@kinoroy thanks for your response. The first part of the message makes sense. I will try that approach. In regards to the second part, I did previously try the configureMediaMessageImageView option, however this function was not being called at all. Any ideas?

**Comment by kinoroy** [comment]
@ahmedwasil did you make sure to set the delegate up? If lets say, you extended your messages view controller as your `MessagesDisplayDelegate`, then in the view controller somewhere (like in viewDidLoad) you should have the line 
````swift
messagesCollectionView.messagesDisplayDelegate = self
````
