### ISSUE TITLE
how to update  label of delivered and read 

### ISSUE THREAD

**Issue by irfanabdulkhaliq** [MessageKit/MessageKit#1280]

**Comment by irfanabdulkhaliq** [comment]
I am trying to update label of read, send and delivered , can anyone tell how I can update the labels

**Comment by martinpucik** [comment]
Hey @irfanabdulkhaliq 
You can look at how we're displaying message status in our example project here 👇 
https://github.com/MessageKit/MessageKit/blob/df613292a00167b595e076d279ef249e1f5880c5/Example/Sources/View%20Controllers/AdvancedExampleViewController.swift#L256

**Comment by austinwright** [comment]
Closing, as the question has been answered, the functionality is documented, and it is showcased in the Example app.
