### ISSUE TITLE
Layout out of safe area when keyboard appears

### ISSUE THREAD

**Issue by fly-qp** [MessageKit/MessageKit#1282]
MessageKit-version: 3.0.0 (pod)
iOS-version: 13.0
Swift-version: 5
Testing-devices - iPhone 7 - iPhone X Pro Max (hard & soft)

MessageKit implemented in subview container view - when showing keyboard everything moves up out of safe area into status bar.

What I have already tried:
   - siting size manually when keyboard appears - seems to have no effect
   - using different layout & constraints
   - using different version of MessageKit & different devices - everything seems to be same

Screen shots:
<img width="519" alt="Bildschirmfoto 2020-03-14 um 11 26 22" src="https://user-images.githubusercontent.com/62172673/76680168-ad252e80-65e6-11ea-9ef8-2ca0a7419cdf.png">
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-14 at 11 11 58](https://user-images.githubusercontent.com/62172673/76680143-8109ad80-65e6-11ea-8706-4e3f71686ea4.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-14 at 11 12 04](https://user-images.githubusercontent.com/62172673/76680144-81a24400-65e6-11ea-85c4-bb0ab572f03c.png)

**Comment by austinwright** [comment]
So, you are using a toolbar instead of a UINavigationController / UINavigationBar?
Does the toolbar have a static height?
Have you checked your toolbar's compression resistance is greater than the container's?
Have you checked the `messagesCollectionView.contentInset.top`?

**Comment by devcat1010** [comment]
I have the same issue. How to fix it? @austinwright

**Comment by martinpucik** [comment]
@devcat1010 if you're facing the same issue, could you please make a PR with changes to our Example project so this issue is reproducible there? It'd really help us to track down what's wrong here

**Comment by devcat1010** [comment]
Thank you for your reply. 
Here is a video that I am looking. 

https://www.dropbox.com/s/a6vq0wi14od6awv/Screen%20Recording%202020-06-05%20at%207.14.09%20AM.mov?dl=0

**Comment by devcat1010** [comment]
@martinpucik Did you check my video?

**Comment by alielsokary** [comment]
@fly-qp @devcat1010  
and anyone looking for a fix
Are you using **IQKeyboardManager**? 
If so then you can fix the issue simply by adding this in `AppDelegate` `didFinishLaunchingWithOptions`: 

`IQKeyboardManager.shared.disabledDistanceHandlingClasses.append(YourChatViewController.self)` 

😉
