### ISSUE TITLE
Ability to customise the default cells once they've been configured

### ISSUE THREAD

**Issue by sylvan-d-ash** [MessageKit/MessageKit#1283]
I'm working on a chat app and would like for the messages to load from bottom to top. A quick search online showed that the easiest way to achieve this is by inverting the `Y-axis` of both the collection view and the cells.

So I was wondering if it's possible to include a user-defined closure that is called after each cell has been configured. Perhaps something like `beforeConfigure?()` and `afterConfigure?()` closures. I believe this would provide more flexibility to developers without having to tamper with the library.

**Comment by kinoroy** [comment]
You can always override `collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell` in your subclass of `MessagesViewController`, calling the `super` implementation (which calls the `configure` methods) and then do any post-configuration you need to do to the cell. 

Although what I found is that inverting the cells and collection view was not the best way to solve this. Instead I used a custom CollectionViewLayout class which subclasses `MessagesCollectionViewFlowLayout` to have the messages load from the bottom to top. Check out this gist that I found, it worked well for me: https://gist.github.com/jochenschoellig/04ffb26d38ae305fa81aeb711d043068

**Comment by austinwright** [comment]
@sylvan-d-ash does @kinoroy's response answer your question?

**Comment by sylvan-d-ash** [comment]
@kinoroy nice. Thank you for that.
@austinwright yes, very helpful
