### ISSUE TITLE
Message/Image Cacheing 

### ISSUE THREAD

**Issue by ahmedwasil** [MessageKit/MessageKit#1286]
Does Message Kit support Image and Message caching? 

Right now every time i load the chat view, my messages are shown immediately, but the images download/load slowly and then pop up in the chat view. 

Any solutions to this within MessageKit ?

**Comment by austinwright** [comment]
MessageKit does not do any caching of the data / content, that is up to you. AlamoFireImage has an autopurging image cache, or you could roll your own NSCache. I'm sure there are other options out there too, those are just some examples.

**Comment by martinpucik** [comment]
Hey @ahmedwasil 
Did you have a chance to use the PINRemoteImage library to load your images from the previous issue we discussed?

https://github.com/MessageKit/MessageKit/issues/1276#issuecomment-598036207

PINRemoteImage also provides a cache for your images so it should load faster when you're returning to the chat screen

**Comment by ahmedwasil** [comment]
@martinpucik yes i have tried using the PinRemoteImage but get the same slow response. I have tried the progressive feature too which doesn't seem to work. I got a feeling that I am not setting the image in the correct place. 

Currently its all being loaded in this function:

func messageStyle(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> MessageStyle {

I check for the message.kind and if it is a .photo then set a containerView to load the image from a url.

**Comment by martinpucik** [comment]
@ahmedwasil  There is a method on `MessagesDisplayDelegate`
```swift
func configureMediaMessageImageView(_ imageView: UIImageView, for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView)
```

I'd try to load images there, something like

```swift
func configureMediaMessageImageView(_ imageView: UIImageView, for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) {
    switch message.kind {
        case .photo(let media):
            imageView.pin_setImage(from: media.url)
        default:
            break
    }
}
```

**Comment by ahmedwasil** [comment]
@martinpucik would i still need to set anything in regards to .photo kind in the messageStyle function?

**Comment by martinpucik** [comment]
@ahmedwasil not for the image loading part to work

**Comment by ahmedwasil** [comment]
@martinpucik Thanks, but still getting the same response. Images taking a long time to load and re loading each time i go back into the message view.

**Comment by martinpucik** [comment]
@ahmedwasil in that case it may be because you're loading large images and the cache is not big enough to hold them all? 
In any case it doesn't look like your issue is related to the MessageKit, but if you think it is, could you please try to reproduce it in our Example project?

**Comment by ahmedwasil** [comment]
@martinpucik Is there an example app available which is loading images from a url? Ive looked through the ChatExample App but its using images from the Assets Resources.

**Comment by martinpucik** [comment]
@ahmedwasil  I added a PR with this option #1294

**Comment by ahmedwasil** [comment]
@martinpucik thank you very much. I will get round to looking at it this weekend. Really appreciate the extra effort.

**Comment by martinpucik** [comment]
@ahmedwasil LMK if the example is working for you 👍

**Comment by ahmedwasil** [comment]
@martinpucik I have pulled the latest example but can't seem to find your changes. Have they been removed?

**Comment by martinpucik** [comment]
@ahmedwasil it’s in the development branch

**Comment by ahmedwasil** [comment]
@martinpucik thank you that is fully working now. Really appreciate the extra efforts in creating the example.

Quick question can the image be displayed dependant to the ratio of the image or does the size always need to be preset?
