### ISSUE TITLE
InputTextView sizes incorrectly for long messages

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#129]
![screen shot 2017-09-16 at 8 00 24 pm](https://user-images.githubusercontent.com/7445580/30526251-2eaadf80-9bdd-11e7-90d8-5cbccf620c41.png)

### How to reproduce:
1. Paste or type a large amount of text inside of the `UITextView`. 

Something that will be greater than the the `maxWidth` allowed when calculating the `intrinsicContentSize`

**Note**: Reaching a `maxWidth` with new lines don't trigger this bug

**Comment by Ganzolo** [comment]
I just battled a lot with this issue. I think I found a fix with minimum impact on current code. I think the problem relies on UIKit. What I did is getting rid of intrinsicContentSize to change the height of view and only relies on :

- Content Compression resistance
- layout height constraint

**Comment by nathantannar4** [comment]
Hey,
I looked over what you had and you left out some things. I don't think changing the entire intrinsicContentSize is needed. I have been doing some texting and I think adding a heightconstaint just to the InputTextView when height > maxHeight is all we need

**Comment by SD10** [comment]
This is fixed in #173
