### ISSUE TITLE
How do I display the refresh control as shown in the example app?

### ISSUE THREAD

**Issue by codyaweber** [MessageKit/MessageKit#1293]
Message Kit 3.1.0, iOS 12, Swift 5

I think this is very simple, I'm just missing something. In the example app, there's a nice animation where the refresh control appears in tandem with the scrolling down motion. All I see in the example app to manage the refresh control is:
`
messagesCollectionView.addSubview(refreshControl)
`
`
refreshControl.addTarget(self, action: #selector(loadMoreMessages), for: .valueChanged)
`

I'm doing this same thing, and the refresh control just sits in the middle of the collection view, and doesn't animate in while pulling the collection view down from the top. I don't see anything in the docs about this. Is there a setting or something I'm missing?

**Comment by martinpucik** [comment]
Hey @codyaweber 
Could you try to add the refresh control to the `messagesCollectionView` like this?

https://github.com/MessageKit/MessageKit/pull/1294/files#diff-ba6ce00d2ff2b20c050f2392174f4fb1R116

**Comment by codyaweber** [comment]
Same result.

**Comment by martinpucik** [comment]
@codyaweber could you please try to post some sample code? You issue could be because of some layout issue as I can't reproduce this in our Example project

**Comment by codyaweber** [comment]
I just realized that it was actually appearing, but matched the background color of my view more closely than I thought, so I couldn't see it. 🤦🏽‍♂️Appreciate the response and this library.
