### ISSUE TITLE
Was just wondering if someone could explain the logic behind the entire code base?

### ISSUE THREAD

**Issue by Contreux** [MessageKit/MessageKit#1298]
I have been using storyboards my entire coding career and for creating dynamic cells would always create a  CellClass which is linked to a NibFile and then in the view controller that would contain either the UICollectionView or table view I would load them in using the UITableviewdelegate and data source delegate and then configure the cell within the cell's class.

**Comment by martinpucik** [comment]
@willMorph this is kind of a broad question 😹 do you have something specific we could help you with?
