### ISSUE TITLE
[Bug] Keyboard change results in extra white space on the screen

### ISSUE THREAD

**Issue by ampatalas** [MessageKit/MessageKit#13]
Steps to reproduce:

1. Start writing a message text in MessageInputBar.
2. Press 'change keyboard' button.

Every keyboard change results in more white space.

Result:

| Before keyboard change | After keyboard change |
| --- | --- |
| ![img_8370](https://user-images.githubusercontent.com/4039445/28715676-5c69218c-7399-11e7-9f57-b4ecf7c00110.PNG) | ![img_8371](https://user-images.githubusercontent.com/4039445/28715675-5c689dd4-7399-11e7-9b6f-2744f21e8f14.PNG) |

**Comment by SD10** [comment]
@ampatalas Awesome, thanks! I thought I fixed this. 
Will take care of it 👍 Unless you'd like to? 😃

**Comment by SD10** [comment]
@ampatalas Unless you'd like to? 😃
