### ISSUE TITLE
Message height sizes incorrectly. Increases as message length increases

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#130]
![screen shot 2017-09-16 at 7 58 48 pm](https://user-images.githubusercontent.com/7445580/30526264-9cfcfdec-9bdd-11e7-904b-555b70c1f9e6.png)

**Comment by Summa-Labs** [comment]
@SD10 Hey Steven we already fixed it. If you want we can send you pull req to review it. It was problem with the fonts.
