### ISSUE TITLE
Convert internal, static colors into color assets.

### ISSUE THREAD

**Issue by austinwright** [MessageKit/MessageKit#1301]
Xcode 9 introduced Color Assets. Now that MessageKit is targeting iOS 11+, we can make use of these color assets and gain their benefits - mainly that color asset (and system defined semantic color) instances automatically adjust to the current environment settings. So if an end-user has their phone set to automatically switch from light to dark mode, currently a framework client would need to refresh the view programatically. This means listening for notifications and other boilerplate code. Otherwise the end-user does not have a seamless experience and would need to make some manual interaction to reload/refresh the view.

Color Assets should have a light and dark mode, and should also provide high contrast variants of the light and dark mode colors.

Color Assets should be named in a way that conveys the intended use of the color, rather than specific color values.

**Comment by kinoroy** [comment]
Closing as this was merged to master today.
