### ISSUE TITLE
How do I change outgoing / incomingMessageLabelInsets?

### ISSUE THREAD

**Issue by claudiacrotti** [MessageKit/MessageKit#1302]
I am using the latest iOS and version of MessageKit (3.1.0). I'm looking to change the inner padding of the text inside the bubble. I would like to have more space around the text inside the cell. I don't seem to be able to find the way to just override / set `MessageLabelInsets` or `incomingMessageLabelInsets` (if these are the correct values to edit... 

I tried adding with no success in the view controller that is `MessageCellDelegate, MessageLabelDelegate, MessagesLayoutDelegate, MessagesDisplayDelegate, MessagesViewController` the following:

```
func messageLabelInset(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> UIEdgeInsets {
        return UIEdgeInsets(top: 12, left: 14, bottom: 12, right: 14)
    }
``` 

I am using the default cell for text and `MessageKind` of `attributedText`

Thank you for your help and for this!!!

**Comment by Joker666** [comment]
Did you find a solution?

**Comment by claudiacrotti** [comment]
Not really, I ended up writing the cell by myself as a custom one

**Comment by ostatnicky** [comment]
@claudiacrotti It looks that you solved by your own way. Just hint for others: try to set it up not even on `textMessageSizeCalculator` but even on `attributedTextMessageSizeCalculator`.

```
layout.textMessageSizeCalculator.incomingMessageLabelInsets = ...
layout.attributedTextMessageSizeCalculator.incomingMessageLabelInsets = ...
```

It worked to me.
