### ISSUE TITLE
Why the size calculator cannot calculate my custom cell height?

### ISSUE THREAD

**Issue by orkhanalizada** [MessageKit/MessageKit#1307]
- What version of MessageKit are you using?
        - latest
- What version of iOS are you running on?
        - 11.3.4
- What version of Swift are you running on?
        - 5.2
- What device(s) are you testing on? Are these simulators?
        - iPhone 7 and Simulators
- Is the issue you're experiencing reproducable in the example app?
        - cannot say

Hi, I'm struggling with this problem 5 days already and I tried EVERYTHING. So decided to post here, maybe you can help me.
What I want to do is to create my custom cell and display messages inside of it. And the structure of my cell should look like:
    |--(UIImageView)--(UILabel)--|
    |------------------ (UILabel)--|

UIImage for Avatars, first label for the username and the latest for the message itself.
I've created that cell from xib file.

Now I'm overriding `cellForItem` method and say:

````
let cell = messagesCollectionView.dequeueReusableCell(CustomCell.self, for: indexPath)
cell.configure(with: message, at: indexPath, and: messagesCollectionView)
return cell
````

My custom cell swift file looks like:

```
open func configure(with message: MessageType, at indexPath: IndexPath, and messagesCollectionView: MessagesCollectionView) {
        switch message.kind {
        case .custom(let text):
            messageLabel.text = text as? String
        default: break
        }
    }
````

and the result what I get is:

<img width="406" alt="Screenshot 2020-04-01 at 20 25 27" src="https://user-images.githubusercontent.com/54267156/78172796-f08cf300-7456-11ea-8703-ca2e61a16760.png">

as you can see, the height is not changing. Can someone please help me to fix this?
I will be soo grateful!

In my `CustomMessageSizeCalculator` I also have:

````
open override func sizeForItem(at indexPath: IndexPath) -> CGSize {
        guard let layout = layout else { return .zero }
        let collectionViewWidth = layout.collectionView?.bounds.width ?? 0
        let contentInset = layout.collectionView?.contentInset ?? .zero
        let inset = layout.sectionInset.left + layout.sectionInset.right + contentInset.left + contentInset.right
        return CGSize(width: collectionViewWidth - inset, height: 44)
    }
```

So as you can see, it is always 44, nevertheless the text is huge or small.

**Comment by Kaspik** [comment]
`return CGSize(width: collectionViewWidth - inset, height: 44)` - what exactly do you expect as height if you always return `44`? :)
