### ISSUE TITLE
messageCollectionView's contentInset is not consistently set as keyboard appears

### ISSUE THREAD

**Issue by hyouuu** [MessageKit/MessageKit#131]
On 0.7.2 in a longer than screen messageCollectionView, tapping on the input bar would work properly ~50% of the time; the other 50% you cannot scroll to the bottom

**Comment by SD10** [comment]
@hyouuu You have to give me more information than this 😃
Regardless, I think I know what you're talking about: #109. Let me know if that sounds right. 
Should be fixed soon

**Comment by hyouuu** [comment]
Exactly - thanks! Marking this as dupe
