### ISSUE TITLE
messageInputBar does not show with SwiftUI (wrapped with UIViewControllerRepresentable)

### ISSUE THREAD

**Issue by bhatti** [MessageKit/MessageKit#1311]
Hi,
 I am adding MessageKit to a SwiftUI app that wraps a child controller inherited from `MessagesViewController` using UIViewControllerRepresentable. It shows message bubbles but it doesn't show messageInputBar. Can you suggest a workaround to fix this?

Version of MessageKit: 3.1.0
Version of iOS: IOS 13.1
Version of Swift: 
Apple Swift version 5.1.2 (swiftlang-1100.0.278 clang-1100.0.33.9)
Target: x86_64-apple-darwin19.0.0

Device(s) are you testing on? Are these simulators: iPhone 8 and Simulator

Swift Wrapper code
```swift

struct EmbeddedChatViewController : UIViewControllerRepresentable {
    typealias UIViewControllerType = ChatViewController
    var contact: ContactEntity
    
    init(contact: ContactEntity) {
        self.contact = contact
    }
    
    func makeUIViewController(context: Context) -> ChatViewController {
        let ctr = ChatViewController()
        ctr.contact = self.contact
        return ctr
    }
    
    func updateUIViewController(_ uiViewController: ChatViewController, context: Context) {
        uiViewController.reload()
        
        //
    }
}


class ChatViewController: MessagesViewController {
...
}


```

Thanks

**Comment by nathantannar4** [comment]
I don’t think SwiftUI supports inputAccessoryViews. You will have to manage the presentation of the input bar yourself for SwiftUI
