### ISSUE TITLE
How can i change [PlayButtonView] background?

### ISSUE THREAD

**Issue by Devinsomnia** [MessageKit/MessageKit#1321]
How can I change the color of the play button in video messages according to the dark mode and light mode?

- What version of MessageKit are you using?
-> MessageKit (3.1.0)

- What version of iOS are you running on?
-> Real Device: 13.4
-> Simulator: 13.4

- What version of Swift are you running on?
-> Swift 5.0

- What device(s) are you testing on? Are these simulators?
-> Real Device: iPhone 7
-> Simulator: All Simulator

- Is the issue you're experiencing reproducable in the example app?
-> Yes, there is also this problem in the sample MessageKit project.

**Comment by Kaspik** [comment]
I believe this was fixed.

3.2.0 release is just about to happen, closing! 🎉
