### ISSUE TITLE
Dismiss keyboard when scrolling messages

### ISSUE THREAD

**Issue by busu90** [MessageKit/MessageKit#1322]
Is there a way to dismiss the keyboard in an interactive way when scrolling messages? Currently this only happens if i drag down on the messageInputBar.
Also is there a tap to dismiss feature? (taping on the messaesCollectionView should dismiss the keyboard)

**Comment by Contreux** [comment]
I'm wondering the same about the tap to dismiss, I managed to implement it with a simple tap gesture but it seems to override any of the responses from individual messages.

**Comment by Contreux** [comment]
Add this  to MessageCellDelegate
Works well for tap to dismiss
```
func didTapBackground(in cell: MessageCollectionViewCell) {
		messageInputBar.inputTextView.resignFirstResponder()
}
```

**Comment by cwestMobile** [comment]
messagesCollectionView.keyboardDismissMode = .onDrag

will resolve this fro drag
