### ISSUE TITLE
Text color of message behaving incorrectly 

### ISSUE THREAD

**Issue by varunlibra3** [MessageKit/MessageKit#1323]
Hi

- What version of MessageKit are you using? 3.0.0
- What version of iOS are you running on? 13.0.0
- What version of Swift are you running on? 4.2
- What device(s) are you testing on? Are these simulators? iPhone 11 simulator
- Is the issue you're experiencing reproducable in the example app? Nopes

Facing weird problem with text color for message kind = text. isFromCurrentSender returns true/false correctly but text color is coming black for messages.

```swift
func textColor(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> UIColor {
        print (message.kind, " ", isFromCurrentSender(message: message))
        return isFromCurrentSender(message: message) ? .white : .darkText
    }
```
Log output:
text("Hello supplier")   true
text("How are you? 🙂")   false
text("another message")   false
text("Hi supplier 2")   true
text("what about your goods? ")   false

But when I run the code, it shows black color (check image below). Can't figure this out.

![Simulator Screen Shot - iPhone 11 - 2020-04-12 at 17 55 02](https://user-images.githubusercontent.com/8653442/79081064-fa7ce480-7ce7-11ea-9c06-854682fb4c10.png)

**Comment by austinwright** [comment]
Are you sure the data is `.text` and not actually being processed as `.attributedText`? Attributed text does not honor the `textColor(for message: ...` delegate.

**Comment by varunlibra3** [comment]
Yes, I am sure MessageKind is `.text` as it is printed in logs also. When MessageKind is `.attributedText`, delegate `textColor(for message: ...` is not even called

**Comment by varunlibra3** [comment]
Reopening this issue because it was never solved. This is the delegate function:
```
func textColor(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> UIColor
{
print("message textColor ", indexPath, message.kind, isFromCurrentSender(message: message))
return isFromCurrentSender(message: message) ? .white : .darkText
}
```

![text_color](https://user-images.githubusercontent.com/8653442/82453302-57558280-9a7e-11ea-96b8-930e26f9d9ac.gif)

It is strange because background color is set properly, only text color and indexing seems to be an issue. Please help.

**Comment by martinpucik** [comment]
@varunlibra3 could you try to reproduce this in our Example project? Or make a PR with changes to the example project where this issue is reproduced?

**Comment by varunlibra3** [comment]
Hey, I tried recreating this on Example app but could not. It works perfectly. Actually I am loading all chat messages from Twilio. Once Twilio channel is initialized, I call loadFirstMessages() to load messages using Twilio endpoint. I even commented textColor() method to load default color, it still doesn't work. Any idea what could be causing this?

**Comment by Kaspik** [comment]
Have you tried latest version 3.1.0? It had some serious changes and fixes included, as well as dark mode.

**Comment by varunlibra3** [comment]
Yes, just updated to 3.1.0, problem still persists.

**Comment by varunlibra3** [comment]
So finally I had to go with NSAttributedString instead of text and build my messageList. This solves the problem.

**Comment by fukemy** [comment]
@varunlibra3 hi, how did u solved for attribute textcolor for current sender and non-current sender?
```
func textColor(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> UIColor {
        switch message.kind{
        case .attributedText(_):
            return isFromCurrentSender(message: message) ? .white : .darkText
        default:
            return isFromCurrentSender(message: message) ? .white : .darkText
        }
    }
```

i tried but not working
