### ISSUE TITLE
UICollectionView crash in setTypingIndicatorHidden

### ISSUE THREAD

**Issue by kphns** [MessageKit/MessageKit#1324]
Using MessageKit 3.0.0 or 3.1.0 on iOS 13.4, I get a crash that I did not get on previous versions of iOS 13.

When calling
```swift
messagesViewController.setTypingIndicatorViewHidden(false, animated: true)
```
I get:
```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to insert section 1 but there are only 1 sections after the update'
```
This is strange -- if I ask my data source before calling setTypingIndicatorViewHidden using:

```swift
print("collection view thinks there are 
\(messagesViewController?.messagesCollectionView.numberOfSections as Optional) sections,
 whereas the data source thinks there are 
\(messagesViewController?.messagesCollectionView.messagesDataSource?.numberOfSections(in: messagesViewController.messagesCollectionView) as Optional)")
```

I get:

collection view thinks there are Optional(1) sections, whereas the data source thinks there are Optional(23)

I am doing no other updates at the time.  This appears whether or not I use any scrolling functions.  My data is actually displaying as appropriate, so the data source is hooked up and functioning as expected.  It's only when I try to show the typing indicator that I get this crash.

I've tried sprinkling calls to reloadData throughout, and nothing seems to help.

This does sound like a UICollectionView issue, but I am at a loss as to how to work around it (other than not using the typing indicator view, of course).  Any thoughts?

**Comment by austinwright** [comment]
I'm pretty sure the typing indicator injects a static section into the collection. I haven't used it and have only looked at the code in passing, though. You might want to take a second look at how the example app is doing things, and analyze the code a bit more. It seems like your datasource delegate needs to take into account if the typing indicator is present or not when returning how many sections are in your collection.

**Comment by kphns** [comment]
Re:  my datasource needing to take into account the typing indicator -- no, the MessagesDataSource implementation does not need to do that, as the UICollectionViewDataSource implementation in MessagesViewController adds one to the number of sections if the typing indicator is visible:


```swift
    open func numberOfSections(in collectionView: UICollectionView) -> Int {
        guard let collectionView = collectionView as? MessagesCollectionView else {
            fatalError(MessageKitError.notMessagesCollectionView)
        }
        let sections = collectionView.messagesDataSource?.numberOfSections(in: collectionView) ?? 0
        return collectionView.isTypingIndicatorHidden ? sections : sections + 1
    }
```

(From MessagesViewController.swift).

Again, this worked under iOS 13.3.1 and breaks under 13.4.

Changing from 

```swift
let section = messagesCollectionView.numberOfSections
```

to 

```swift
let section = messagesCollectionView.messagesDataSource?.numberOfSections(in: messagesCollectionView)
```

does nothing except change the first number in the error message (from 1 to the correct number).

However, if I comment out the call to performUpdatesForTypingIndicatorVisability and add a call to reloadData, it works again, but the animations are somewhat janky.  Better than crashing, for now!
