### ISSUE TITLE
Weird animation on message input bar textView placeholder text. 

### ISSUE THREAD

**Issue by ahmedwasil** [MessageKit/MessageKit#1329]
When deleting text from the InputTextView, as the last character is removed, the placeholder text animates into the textview from the top left corner. 

This only happens when `setRightStackViewWidthConstant(to: 40, animated: true)` the animated is set to true. When i change this to false, the placeholder text reappears correctly without flying in. 

Anyone have any ideas as to why this is happening?

**Comment by isupremedyou** [comment]
@ahmedwasil when are you calling `setRightStackViewWidthConstant(to:animated:)`? 

I've not encountered this behavior before. You may need to share a GIF or link to a video showing what is happening in addition to answering when you are calling the method.
