### ISSUE TITLE
Controller does not conform to protocol 'MessagesDataSource'

### ISSUE THREAD

**Issue by febick** [MessageKit/MessageKit#1332]
I have the same problem - https://github.com/MessageKit/MessageKit/issues/978

Xcode said that my controller does not conform to protocol "MessagesDataSource" and asking to add currentSender and messageForItem function. But I already have it in the code!...

![1](https://user-images.githubusercontent.com/25277792/79690098-62d84280-8261-11ea-8bab-bdf3a69efb5d.png)

And if I click to Fix....

![2](https://user-images.githubusercontent.com/25277792/79690118-74214f00-8261-11ea-9394-9cb815351a3b.png)

And if delete redeclaration code - again error with not conform to protocol.

How I can fix it?

**Comment by isupremedyou** [comment]
@febick I would try steps 1, 2, and 4 from [this article](https://developerinsider.co/clean-xcode-cache-quick-fix/) and see if that resolves your issue.

**Comment by nurlan-dzhavadov** [comment]
@isupremedyou I have the same issue and I didn't help me. Any ideas?
