### ISSUE TITLE
Video message playback icon bug in dark mode

### ISSUE THREAD

**Issue by bmt2018** [MessageKit/MessageKit#1335]
The "video playback icon" that is shown on video messages is too dark when iOS is in dark mode.  This may be the same issue that is referred to in [#1321](https://github.com/MessageKit/MessageKit/issues/1321). See screenshots below from the Example app.

![IMG_0139](https://user-images.githubusercontent.com/36267412/79751726-15031f00-82e1-11ea-8967-90f17989f120.jpeg)
![IMG_0138](https://user-images.githubusercontent.com/36267412/79751732-192f3c80-82e1-11ea-9188-4d3355880181.jpeg)

**Comment by kinoroy** [comment]
Thanks for reporting this @bmt2018 ! A fix has been merged into the development branch and will be included in the next release.

**Comment by Kaspik** [comment]
3.2.0 release is just about to happen, closing! 🎉
