### ISSUE TITLE
InputBarAccessoryView inside the horizontal bounds of a view controller?

### ISSUE THREAD

**Issue by ivanornes** [MessageKit/MessageKit#1337]
Hi all,

I am trying to use the MessagesViewController with the InputAccessoryView. The problem is that in regular horizontal size classes the MessagesViewController doesn't cover the whole screen and the InputBar covers the bottom of the screen without taking into account the MessagesViewController bounds. 

I did manage to show the InputBar with the right size following the SubviewExampleViewController from the InputBarAccessoryView project. But whenever I dismiss the keyboard the InputBar fills again all the horizontal bottom region. See the attached screenshots below. 

- MessageKit version 3.1.0
- iOS version 13.4
- Swift 5
- I am testing with an iPad
- For reproducing the issue is necessary to add the MessagesViewController as a child of another view controller in a region of the screen. The MessagesViewController should not fill the entire screen. 

![aaa](https://user-images.githubusercontent.com/645151/80000142-0ffac700-84bd-11ea-8836-7d50627c02ed.jpg)
![IMG_E3922](https://user-images.githubusercontent.com/645151/80000176-18eb9880-84bd-11ea-8f1e-ee69c4fcc95b.JPG)
![IMG_E3924](https://user-images.githubusercontent.com/645151/80000200-2143d380-84bd-11ea-8225-164f894a8f03.JPG)

**Comment by nathantannar4** [comment]
What view are you adding it to? How are you setting it up?

**Comment by ivanornes** [comment]
Hi @nathantannar4!

You can replicate the issue by reducing the width of the Messages view controller. I have modified the Embedded view controller example of the MessageKit example project. You can check out the change [here].(https://github.com/oinsider/MessageKit/commit/ccf6f2d9aebdde1faa1b84738ceb5ca106aba1b1)

**Comment by ashleyng** [comment]
@oinsider did you take a look at my PR? I added some example code that supports splitview on iPad (which also uses InputBarAcessoryView's subview example). I quickly just tested the code on a simulator and it seems to work fine when the keyboard is dismissed 
https://github.com/MessageKit/MessageKit/pull/1284

**Comment by ivanornes** [comment]
Hi @ashleyng!
Looks great I think that I'm going to make it work! 😊
Thanks!!
