### ISSUE TITLE
TopLabel for CustomCell

### ISSUE THREAD

**Issue by saparfriday** [MessageKit/MessageKit#1339]
Thank you for this repo. It is awesome.

I want to show send date with cellTopLabelAttributedText over CustomCell. How can I realize it? 
Please give me the direction where I should go in order to resolve this issue. Thanks to all

**Comment by kinoroy** [comment]
When you use a custom cell, you are responsible for its layout entirely, so methods in MessagesDisplayDelegate, etc are not called for your cell, you have to do everything you need in `customCell(for:at:in:)`.
 However if you subclass your custom cell from `MessageContentCell` ( just add your content into its `messageContainerView` ), then you get `cellTopLabel` for free and you can configure it in the customCell method with `myCustomCell.configure(with:at:and:)` and then in that case the delegate methods would be called for your cell. 
If you are unable to subclass MessageContentCell then you would need to add your own label view and then customize it with the message data in `customCell(for:at:in:)`
