### ISSUE TITLE
Check if carthage installation is working

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#134]
Carthage support was probably broken by the new project structure regarding MessageKit assets 🤔

**Comment by cwalo** [comment]
I can confirm that I'm able to get this working using Carthage with `0.7.3`, but the images are not found.

**Comment by cwalo** [comment]
After `0.7.4`, looks like we're in good shape.

**Comment by SD10** [comment]
Great 😃 Sorry I signed up for ZenHubIO and it reopened a ton of issues...
