### ISSUE TITLE
thread 1: fatal error: avatar position horizontal.natural needs to be resolved. message kit

### ISSUE THREAD

**Issue by shimunKg** [MessageKit/MessageKit#1340]
Hi guys
Does anybody know how to solve this issue? 

@nathantannar4, @zhongwuzw @SD10 
Thanks for the effort guys, sorry for bothering but i really need your help on this one
![Screen Shot 2020-04-28 at 9 57 33 PM](https://user-images.githubusercontent.com/34037990/80531688-4e035980-899b-11ea-8b8f-61d6ead0ff3b.png)

**Comment by sraudax** [comment]
Hi @nathantannar4 we really need you here, it's fatal for 2 of my apps. It's blocking release :( I also see others are stuck. BIG thanks!

@vincenzo-favara are you also still struggling with this?

**Comment by kinoroy** [comment]
@shimunKg @sraudax  Can either of you either of you provide a repo that reproduces this? Or is it reproducible in the example project?

**Comment by SD10** [comment]
@shimunKg @sraudax basically your `MessagesCollectionViewLayoutAttributes` are making it to the cell with an `AvatarPosition.Horizontal` case of `.natural`. This means the cell is unable to determine the placement of the avatar view and thus unable to render the layout.

This is usually resolved here:
https://github.com/MessageKit/MessageKit/blob/5e16637ffc1fb39f2c3f9bc3396bbee41118947d/Sources/Layout/MessageSizeCalculator.swift#L150-L160

In hindsight, maybe throwing a `fatalError` here is too strict -- we could not crash and just not provide an accurate layout. But this really forces you to think about the code

**Comment by vincenzo-favara** [comment]
I fund the issue, sorry guys if i didin't write before.
So The problem was in my custom typing cell that it didin't implement a custom MessageSizeCalculator. so isssue can be considered fixed.

**Comment by sraudax** [comment]
@SD10 @kinoroy thanks both for prompt replies. We found the cause and fix, @shimunKg will provide detail here soon. Again, appreciate fast responses and thanks for a great pod! In hindsight I think you are right - this probably should not be fatal error.

The only (unrelated) question I have, is could we shorten the "sending" time? (the time from when user presses "send" to message appearing in chat window). I am not a developer, so hope my crappy explanation makes sense. It's a minor UX improvement but in my view still an improvement.

Let us know if you can, thanks!
![MessageKit sending](https://user-images.githubusercontent.com/49594328/80603645-5e6a1180-8a39-11ea-96eb-7d77166eae74.PNG)


@vincenzo-favara 👍

**Comment by kinoroy** [comment]
@sraudax Nothing in MessageKit is causing a delay in the sending time, that would be up to your implementation of how you are sending messages. If you want the message to appear instantly while the asynchronous sending to your backend is in progress (optimistic sending) then you can create a temporary message object and insert that into your messages data source and it should appear instantly. You can later check the response from your backend and update the temporary model or delete it if sending failed. I realize you're not a developer so maybe none of that makes sense lol but it is entirely possible to eliminate the delay and its not coming from MessageKit. If your devs need help with that they can open another ticket and I'd be glad to explain it more.
