### ISSUE TITLE
Insert new message when using grouped messages

### ISSUE THREAD

**Issue by keyhan76** [MessageKit/MessageKit#1346]
Hi, Im grouping my messages using date and showing each section of messages by their specific section date.
my approach is somehow like this: [](https://github.com/MessageKit/MessageKit/commit/31480f28c08fcc8ea3a49e517d6738fbe1db4449#diff-81bad7f501caa7649f9acc2880b07456)
everything works fine except when I try to insert new messages from input bar using this function:

```swift
guard var previousMessage = chatMessages.last else { return }
        previousMessage.append(message)

messagesCollectionView.performBatchUpdates({
            messagesCollectionView.insertSections([previousMessage.count - 1])
            if chatMessages.count >= 2 {
                messagesCollectionView.reloadSections([previousMessage.count-1])
            }
        }, completion: { [weak self] _ in
            if self?.isLastSectionVisible() == true {
                self?.messagesCollectionView.scrollToBottom(animated: true)
            }
        })
```

in this block app crashed due to section counts.
What should I do for inserting messages by group?

**Comment by keyhan76** [comment]
Managed to fix it this way:
<img width="768" alt="Screen Shot 2020-05-09 at 13 06 08" src="https://user-images.githubusercontent.com/17951995/81468627-f87a4880-91f5-11ea-9db6-cf1971c3fb3d.png">
is there any better solution?

**Comment by fukemy** [comment]
why noone answer this question?
