### ISSUE TITLE
weird CellBottomLabel, MessageBottomLabel and cellTopLabel frame and font size

### ISSUE THREAD

**Issue by keyhan76** [MessageKit/MessageKit#1347]
- What version of MessageKit are you using? 3.0.0
- What version of iOS are you running on? 13.4.1
- What version of Swift are you running on? 5.2
- What device(s) are you testing on? Are these simulators? iPhone 11 Pro max simulator
- Is the issue you're experiencing reproducable in the example app? No

I get a weird frame for all the cell and message labels when first loading my datas.
I have to scroll down or up so they will get fixed!.
here is an screen shot of it:
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-05-09 at 17 35 26](https://user-images.githubusercontent.com/17951995/81474616-f2975e00-921b-11ea-88cf-d2a4afbe063b.png)

As u can see  CellBottomLabel, MessageBottomLabel and cellTopLabel are too big although I have used the exact same code for their height and attributed string provided in the example project.
Any solutions?

**Comment by martinpucik** [comment]
@keyhan76 Could you please post some sample code how are you setting the attributed strings ?

**Comment by keyhan76** [comment]
@martinpucik I just copy and paste the code in ChatViewController in the example project.
<img width="849" alt="Screen Shot 2020-05-09 at 17 48 24" src="https://user-images.githubusercontent.com/17951995/81474864-69812680-921d-11ea-8faf-4f2d9537a829.png">
<img width="814" alt="Screen Shot 2020-05-09 at 17 48 31" src="https://user-images.githubusercontent.com/17951995/81474868-6ede7100-921d-11ea-9527-622b00a7f362.png">

**Comment by martinpucik** [comment]
@keyhan76 try to change the font to something bigger like `.title1` to see if the size changes

**Comment by keyhan76** [comment]
@martinpucik yes still exists

**Comment by martinpucik** [comment]
@keyhan76 Sorry, I don’t quite follow. So setting font type to `.title1` is changing the size of the label?

**Comment by keyhan76** [comment]
@martinpucik no I meant nothing happens and it’s the same as font type caption.

**Comment by martinpucik** [comment]
@keyhan76 got it 👍, could you then check if these delegate methods are being called to make sure `messagesCollectionView` delegates are set properly?

**Comment by keyhan76** [comment]
@martinpucik Yes checked many times and they are getting called.
I found a workaround although, I used messageCollectionView.reloadAndKeepOffset() in view did appear and fixed it somehow.
But then I noticed some of the upper cells are having the same issue.

**Comment by keyhan76** [comment]
@martinpucik any solutions for this?!

**Comment by martinpucik** [comment]
@keyhan76 are you using `reloadData()` to load new messages or are you animating changes by yourself?

**Comment by keyhan76** [comment]
@martinpucik no just using reloadData() and then messageCollectionView.scrollToBottom().

**Comment by martinpucik** [comment]
@keyhan76 ok, as this is not repro in our Example project, do you think you could put together a simple example project where this issue can be reproduce? It may help us to debug this

**Comment by keyhan76** [comment]
@martinpucik Ok sure
