### ISSUE TITLE
Crash insertions in performBatchUpdates using Realm

### ISSUE THREAD

**Issue by javiermanzo** [MessageKit/MessageKit#1348]
Hi, I am getting a crash when I insert a new Realm Object and I perform an update of the collection view.

- What version of MessageKit are you using?
3.1.0
- What version of iOS are you running on?
12.1
- What version of Swift are you running on?
5
- What device(s) are you testing on? Are these simulators?
iPhone 11 Simulator

In some cases it can be really helpful to provide a short example of your code.
If so, please wrap these code blocks in backticks, like this:

```swift
func startDataFetch() {
        let notificationToken = self.messages.observe { [weak self] (changes: RealmCollectionChange) in
            guard let collectionView = self?.messagesCollectionView else { return }
            switch changes {
            case .initial:
                collectionView.reloadData()
                break
            case .update(_, let deletions, let insertions, let modifications):
                collectionView.performBatchUpdates({
                      collectionView.insertSections(IndexSet(insertions))
                      collectionView.deleteSections(IndexSet(deletions))
                      collectionView.reloadSections(IndexSet(modifications))
                    
                    if insertions.count > 0 {
                        collectionView.scrollToBottom(animated: true)
                    }
                }, completion: { _ in })
                break
            case .error(let error):
                fatalError("\(error)")
                break
            }
        }
    }
```

I get this crash:

> Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of sections.  The number of sections contained in the collection view after the update (10) must be equal to the number of sections contained in the collection view before the update (10), plus or minus the number of sections inserted or deleted (10 inserted, 0 deleted).'

**Comment by martinpucik** [comment]
@javiermanzo you had 10 sections before update, you inserted 10 sections with the update but after the update you still only have 10 sections in your data source. 

It seems to me like data source handling issue.

**Comment by javiermanzo** [comment]
> @javiermanzo you had 10 sections before update, you inserted 10 sections with the update but after the update you still only have 10 sections in your data source. 
> 
> It seems to me like data source handling issue. 


I had 0 objects and I inserted 10 objects in my Realm db. When I receive the notification of the update I am trying to insert that objects in my the sections of my collectionView.

**Comment by martinpucik** [comment]
@javiermanzo Could you verify that there were 0 sections in collectionView before the update? `UIKit` is reporting different number of sections in the stacktrace.
