### ISSUE TITLE
How to remove the disable greyish layover over send button ?

### ISSUE THREAD

**Issue by talat-baig** [MessageKit/MessageKit#1349]
<img width="443" alt="Screenshot 2020-05-12 at 1 17 33 PM" src="https://user-images.githubusercontent.com/37650114/81654170-0678d500-9453-11ea-866c-fd75c58bc752.png">

**Comment by martinpucik** [comment]
@talat-baig could you provide more info? Screenshot or code sample? We have an issue tamplate you should fill when posting a new issue.

But maybe setting `shouldManageSendButtonEnabledState` to `false` on `messageInputBar` will fix your issue

**Comment by talat-baig** [comment]
Please check the image provided...Actually I guess that image that is there on the top of send button, need to remove that. Could you please suggest me how to do that

**Comment by martinpucik** [comment]
@talat-baig you can find how to customize input bar or send button in our example project, e.g here

https://github.com/MessageKit/MessageKit/blob/417722060ead863b93b94fab7c5eedd4e1f6db53/Example/Sources/View%20Controllers/AdvancedExampleViewController.swift#L106-L122

or here

https://github.com/MessageKit/MessageKit/blob/417722060ead863b93b94fab7c5eedd4e1f6db53/Example/Sources/View%20Controllers/AdvancedExampleViewController.swift#L124-L165

**Comment by talat-baig** [comment]
ok thank you for the support. I found the solution
