### ISSUE TITLE
Keyboard goes over the InputTextView

### ISSUE THREAD

**Issue by keyhan76** [MessageKit/MessageKit#1353]
I'm using Localization in my app (change localization on fly) when I change localization from English to Arabic for example, and then present the Chat view controller, the keyboard will cover the InputBar and Input Text View and there is no way to dismiss it. Also message cells go under the Message Input Bar too.
Is it a known issue?

**Comment by keyhan76** [comment]
I found that on Iphone X + the above issue happens running on iOS 13.4.1
But on iPhone 8 Plus running iOS 13.4.1 the UIInputSetContainerView is completely off the screen!!!!
It raised a runtime error: Layout Issues: Position and height are ambiguous for UIInputSetContainerView.

here is the debug hierarchy: for iPhone 8 Plus
<img width="451" alt="Screen Shot 2020-05-13 at 11 30 51" src="https://user-images.githubusercontent.com/17951995/81781569-93806480-950d-11ea-9eaa-4b925179d1d8.png">

**Comment by keyhan76** [comment]
Double checked... Result is: on iOS 11, 12 every thing works fine with iPhones having notch(X) and regular ones (like 8, 8+, 6...).
But on iOS 13.4.1 for iPhone X and higher the keyboard frame covers the whole input bar and for iPhone X and lower like iPhone 8 the Input bar is completely gone!!

**Comment by keyhan76** [comment]
I've added the messageViewController as a subview in my parent VC just like the example project provided by the library.

**Comment by keyhan76** [comment]
find out it was an issue with localization library

**Comment by vishaljanice17** [comment]
@keyhan76 Can you please explain how to fix this issue? i am facing same thing 

Thanks

**Comment by keyhan76** [comment]
@vishaljanice17 What are you using for the localization? The issue wasn't related to MessageKit.

**Comment by vishaljanice17** [comment]
I am not using any library for localization. I am using `localization.strings `

![Screen Shot 2021-08-26 at 8 20 05 PM](https://user-images.githubusercontent.com/8909968/130927855-64f59975-fe4d-4850-9896-7a48478b4efa.png)

And i am having this issue 

![Screen Shot 2021-08-26 at 8 23 05 PM](https://user-images.githubusercontent.com/8909968/130928182-81d18d68-17cc-4c49-bb3d-7ac3cfa5ede6.png)

@keyhan76
