### ISSUE TITLE
Strange warning in Swift 5

### ISSUE THREAD

**Issue by prernaa** [MessageKit/MessageKit#1361]
**Describe the bug**

I installed MessageKit through CocoaPods. I imported it into my ViewController code. On compiling, it gave me the following warning: "Setter argument 'newValue' was never used, but the property was accessed". 

**To Reproduce**

Simply install and import MessageKit using "import UIKit".
- Xcode Version 11.4.1 (11E503a)
-  Swift 5

**Expected behavior**

This warning shouldn't appear

**Screenshots**

**Environment**
- What version of MessageKit are you using?
The current version through CocoaPods (installed May 27, 2020)

- What version of iOS are you running on?
iOS 13

- What version of Swift are you running on?
Swift 5

- What device(s) are you testing on? Are these simulators?
Yes. Various simulators.

**Comment by martinpucik** [comment]
@prernaa Could you please provide file name and line number where this warning appears? It should point to some MessageKit file if it’s related to this framework.

**Comment by Kaspik** [comment]
That's a warning on InputBarAccessoryView that was fixed already - https://github.com/nathantannar4/InputBarAccessoryView/pull/119
