### ISSUE TITLE
How to add a footerview to the chatViewController

### ISSUE THREAD

**Issue by PradnyaAC** [MessageKit/MessageKit#1363]
i want to add a footer to the whole chat view controller but not finding any way of doing it. Please help.

**Comment by martinpucik** [comment]
@PradnyaAC could you please elaborate more what exactly are you trying to accomplish?
Some design screenshot or sketch/drawing would be helpful too.

**Comment by PradnyaAC** [comment]
@martinpucik here is an image sample of what i need to do, i have marked the footer in black square. TIA
<img width="347" alt="Screenshot 2020-06-01 at 10 21 48 PM" src="https://user-images.githubusercontent.com/42998795/83432452-85f83380-a456-11ea-9f80-54284b731d71.png">

**Comment by martinpucik** [comment]
@PradnyaAC I'd try to use `backgroundView` property on `UICollectionView` and add your custom view as a subiew there, more: https://developer.apple.com/documentation/uikit/uicollectionview/1618074-backgroundview
