### ISSUE TITLE
Message bubbles don't align like in iMessage

### ISSUE THREAD

**Issue by anmolrajpal** [MessageKit/MessageKit#1368]
**Is your feature request related to a problem? Please describe.**
I'm trying to put custom section inset for each cell but I'm unable to figure out a good way. I don't know why you guys have deprecated `func messagePadding` method but whatever be the reason, there must be an alternate solution for this problem.

**Describe the solution you'd like**
### I expect that the next release must provide inset delegates to the cell so we can play with them.

**Describe alternatives you've considered**
I tried to override collectionView inset for section method like below but I get invalid flow layout warnings which are expected. But it solves the problem anyway. I don't know wether I should continue this approach or not.
```
// MARK: - Overriding super collection view because MessageKit framework has not provided delegates for this
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, insetForSectionAt section: Int) -> UIEdgeInsets {
        let indexPath = IndexPath(item: 0, section: section)
        let message = messageForItem(at: indexPath, in: collectionView as! MessagesCollectionView)
        if isFromCurrentSender(message: message) {
            if !isNextMessageSameSender(at: indexPath) {
                return UIEdgeInsets(top: 1, left: 8, bottom: 1, right: 16)
            } else {
                return UIEdgeInsets(top: 1, left: 8, bottom: 1, right: 26)
            }
        } else {
            if !isNextMessageSameSender(at: indexPath) {
                return UIEdgeInsets(top: 1, left: 16, bottom: 1, right: 8)
            } else {
                return UIEdgeInsets(top: 1, left: 26, bottom: 1, right: 8)
            }
        }
    }
```

**Additional context**
The warnings I get:
```
The relevant UICollectionViewFlowLayout instance is <MessageKit.MessagesCollectionViewFlowLayout: 0x145110640>, and it is attached to <MessageKit.MessagesCollectionView: 0x14703e400; baseClass = UICollectionView; frame = (0 0; 414 736); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x28376fdb0>; animations = { bounds.origin=<CASpringAnimation: 0x28396ca60>; bounds.size=<CASpringAnimation: 0x28396ca80>; }; layer = <CALayer: 0x283950ec0>; contentOffset: {0, 711.66666666666663}; contentSize: {414, 1534}; adjustedContentInset: {64, 0, 51.666666666666629, 0}; layout: <MessageKit.MessagesCollectionViewFlowLayout: 0x145110640>; dataSource: <MessagingApp.MessagesController: 0x146014600>>.
2020-06-02 03:09:12.685143+0530 MessagingApp[10554:3101338] Make a symbolic breakpoint at UICollectionViewFlowLayoutBreakForInvalidSizes to catch this in the debugger.
```

**Comment by kinoroy** [comment]
Hey! The `messagePadding` delegate method was replaced by `incomingMessagePadding` and `outgoingMessagePadding` on `MessageSizeCalculator`s. You can set the padding through the `MessagesCollectionViewFlowLayout` object using `setMessageIncomingMessagePadding`, and `setMessageOutgoingMessagePadding`. 

You can see an example of this in the Example app in the `AdvancedExampleViewController`

**Comment by anmolrajpal** [comment]
Hi @kinoroy I’ve already tried that and it works great. But as my question states, I want to apply this padding for specific sections. 

How can I apply this layout for each cell?

**Comment by kinoroy** [comment]
Sorry that I misread your question. Unfortunately we no longer support a dynamic layout over the cell IndexPath. This is by design (see PR #573) so that we can cache information relevant to the layout.

**Comment by anmolrajpal** [comment]
@kinoroy Alright, I hope if we can have that functionality. As you can see my code, I’m just trying this so that we can have aligned Message bubbles just like iMessage app. I wonder if there’s another way to achieve that alignment.

**Comment by kinoroy** [comment]
Could you elaborate on what you mean by 'aligned bubbles just like the iMessage app`? By default, MessageKit should look like iMessage already. Is there a screenshot you could share of an 'incorrect alignment' relative to iMessage?

**Comment by anmolrajpal** [comment]
![image](https://user-images.githubusercontent.com/53750739/84743358-70931580-afcf-11ea-8287-a079e7781547.jpeg)
![image](https://user-images.githubusercontent.com/53750739/84743399-843e7c00-afcf-11ea-8c8f-e57725bebb57.jpeg)

@kinoroy You can see the difference.

**Comment by anmolrajpal** [comment]
![image](https://user-images.githubusercontent.com/53750739/84743684-e9926d00-afcf-11ea-9191-e8fd9a13d65c.jpeg)
![image](https://user-images.githubusercontent.com/53750739/84743706-f31bd500-afcf-11ea-8760-47bfb41ba76e.jpeg)

@kinoroy you can see the difference. I’ve uploaded screenshots showing difference between iMessage and MessageKit implementation.

**Comment by kinoroy** [comment]
Thanks for the screenshot of the issue @anmolrajpal ! I'll mark this as a confirmed bug so it doesn't get closed.

**Comment by mknippen** [comment]
+1, this was also listed as an issue in #1156 , but closed because it became stale

**Comment by mendimr** [comment]
Might be late but I found a solution.

I had this problem today where the bubbles had more space on the left or right depending who was the sender so I started investigating why would that be the case since I can clearly see that miss alignment even on the example app.

All bubbles have the insets set to:
`public var incomingMessageLabelInsets = UIEdgeInsets(top: 7, left: 18, bottom: 7, right: 14)
public var outgoingMessageLabelInsets = UIEdgeInsets(top: 7, left: 14, bottom: 7, right: 18)`

When using the .bubble style the mask is set all the way to the edge of the background width but when using the .bubbleTail, the mask crops the background shorter than the .bubble does to leave space for the tail.

<img width="708" alt="Screen Shot 2021-06-30 at 3 38 28 PM" src="https://user-images.githubusercontent.com/48059845/123970264-441f2100-d9b9-11eb-8e43-e250b252741e.png">

I can think of two solutions right now:
1. Create a custom style that crops the .bubble to align it with the .bubbleTaill 
2. Set the insets evenly and create a custom style for both cells to avoid cropping the width of the background.

I was able to do something similar to this image following these steps:
<img width="764" alt="Screen Shot 2021-06-30 at 3 10 05 PM" src="https://user-images.githubusercontent.com/48059845/123966287-92cabc00-d9b5-11eb-8df9-d526235c08c6.png">

```
if let layout = messagesCollectionView.collectionViewLayout as? MessagesCollectionViewFlowLayout {
    layout.textMessageSizeCalculator.incomingMessageLabelInsets = UIEdgeInsets(top: 8, left: 14, bottom: 8, right: 14)
    layout.textMessageSizeCalculator.outgoingMessageLabelInsets = UIEdgeInsets(top: 8, left: 14, bottom: 8, right: 14)
}
```

```
public func messageStyle(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> MessageStyle {

    // check which message is the last one and adjust the corder radius

    return .custom { view in
        let path = UIBezierPath(shouldRoundRect: view.bounds, topLeftRadius: topLeft, topRightRadius: topRight, bottomLeftRadius: bottomLeft, bottomRightRadius: bottomRight)
        let mask = CAShapeLayer()
        mask.path = path.cgPath
        view.layer.mask = mask
    }
}

```
[UIBezierPath extension](https://stackoverflow.com/a/58770001)

**Comment by monstermac77** [comment]
I believe I have the code to fix this that doesn't involve clipping the corners: https://github.com/MessageKit/MessageKit/issues/1385#issuecomment-1480355202

![Simulator Screen Shot - iPhone 14 Pro - 2023-03-22 at 18 45 31](https://user-images.githubusercontent.com/3255298/227055535-87e48570-dbd4-4b49-bac1-fa9476fa3b7b.png)
