### ISSUE TITLE
Message cells jumping when keyboard is dismissed 

### ISSUE THREAD

**Issue by alexanderconstancio** [MessageKit/MessageKit#1373]
I've attached a gif of the behavior I am getting, if you look at the upper cells when the keyboard is dismissed you can see they have this glitchy behavior like one cell fades in on top of another. 

I also get this message when I dismiss the keyboard -

"[View] First responder warning: '<InputBarAccessoryView.InputTextView: 0x7feb280b3e00; baseClass = UITextView; frame = (0 0; 330 38); text = ''; clipsToBounds = YES; tintColor = UIExtendedSRGBColorSpace 0.239216 0.67451 0.968627 1; gestureRecognizers = <NSArray: 0x600003239bf0>; layer = <CALayer: 0x600003dd4280>; contentOffset: {0, 0}; contentSize: {139, 36.5}; adjustedContentInset: {0, 0, 0, 0}>' rejected resignFirstResponder when being removed from hierarchy"

I'm even getting this bug on the downloaded example project. 

![animated](https://user-images.githubusercontent.com/39841215/83700050-59195d00-a5cb-11ea-8971-3385b7401f23.GIF)

**Comment by alexanderconstancio** [comment]
No one has had this issue?

**Comment by ekazaev** [comment]
It is reproduce-able in the demo app

**Comment by alexanderconstancio** [comment]
> It is reproduce-able in the demo app

Yes it happens to me in the demo app, for iphone 11, in the newest version of the library
