### ISSUE TITLE
Title bar disappeared when keyboard appears

### ISSUE THREAD

**Issue by devdog1010** [MessageKit/MessageKit#1379]
I have this issue when the keyboard has appeared. 

![screen0](https://user-images.githubusercontent.com/64758616/84328997-62a94480-ab38-11ea-9e23-d69b3fb11ddf.png)

![screen1](https://user-images.githubusercontent.com/64758616/84329015-6b017f80-ab38-11ea-9d6c-c5c81d946122.png)

![screen2](https://user-images.githubusercontent.com/64758616/84329030-718ff700-ab38-11ea-9a6a-7710c3ed46b3.png)

**Comment by alielsokary** [comment]
@devdog1010 

Are you using **IQKeyboardManager**? 
If so then you can fix the issue simply by adding this in `AppDelegate` `didFinishLaunchingWithOptions`: 

`IQKeyboardManager.shared.disabledDistanceHandlingClasses.append(YourChatViewController.self)` 

😉
