### ISSUE TITLE
Time Against Each Message

### ISSUE THREAD

**Issue by abdulrehman73331** [MessageKit/MessageKit#1381]
Hey I want to show time against each message just like whatsapp. I tried in messageBottomLabelAttributedText function but Time is being shown on bottom of last message only. I need to show time of each message (either sent from me or from other user)

**Comment by martinpucik** [comment]
@abdulrehman73331 you can refer to the Example project for the guide on how to implement bottom text for every message

https://github.com/MessageKit/MessageKit/blob/9567f87f7620ba899334367898b10a688cb7c3af/Example/Sources/View%20Controllers/ChatViewController.swift#L168-L171


https://github.com/MessageKit/MessageKit/blob/9567f87f7620ba899334367898b10a688cb7c3af/Example/Sources/View%20Controllers/BasicExampleViewController.swift#L113-L131

**Comment by abdulrehman73331** [comment]
Thank you appreciated!

**Comment by abdulrehman73331** [comment]
Hi how can I override  this functional since I am using the Advance View controller example in my Code and I can't override this function and this function is not being used in advance view controller can you help me out?
