### ISSUE TITLE
bottom text on receiver message is not coming right (height or constraint issue)

### ISSUE THREAD

**Issue by abdulrehman73331** [MessageKit/MessageKit#1383]
Hey I have attached screenshot, I am trying to show date against each message. I am using Advance view controller example. I am simply overriding messageBottomlabel text method but as you can see in image date is showing fine on sender message but on receiver message its flying on air or being cut down in some messages.
![Simulator Screen Shot - iPhone 11 - 2020-06-15 at 14 58 46](https://user-images.githubusercontent.com/50770758/84644578-ca84d400-af18-11ea-8024-25a4c75c75b1.png)

**Comment by kinoroy** [comment]
Hey @abdulrehman73331 can you post the code that you changed VS the example app that reproduces this?

**Comment by abdulrehman73331** [comment]
@kinoroy I haven't changed any code I am using the Advance ViewController code but i have commented the messageBottomLabelAttributedText code I am not ovveriding this function to change any text so I am using this function's default text which is returning date. I'm returning 16  in messageBottomLabelHeight

**Comment by kinoroy** [comment]
Thanks for the additional info! Since you're now showing the date under incoming messages whereas that wasn't the case before, the padding for overlapping the avatar view and the message bubble is messing things up. Try changing the `incomingMessagePadding` line in `configureMessagesCollectionView()` to remove the top/bottom padding:
```swift
layout?.setMessageIncomingMessagePadding(UIEdgeInsets(top: 0, left: -18, bottom: 0, right: 18))
````

**Comment by abdulrehman73331** [comment]
@kinoroy  thanks bro working now!
