### ISSUE TITLE
Images instantiated with `contentsOf:` leak their path

### ISSUE THREAD

**Issue by yspreen** [MessageKit/MessageKit#1388]
There's two image inits in MessageKit which cause memory leaks:

```
/Sources/Models/MessageStyle.swift:85:        guard var image = UIImage(contentsOfFile: path) else { return nil }
/Sources/Extensions/UIImage+Extension.swift:39:        let image = UIImage(contentsOfFile: imagePath ?? "")
```

According to [this](https://stackoverflow.com/a/62061661/2585092) answer on SO, using `UIImage(data: Data(contentsOf: url))` instead fixes this issue.

![image](https://user-images.githubusercontent.com/12631527/85557690-01807700-b5f6-11ea-934d-f27592da13fa.png)
![image](https://user-images.githubusercontent.com/12631527/85558057-63d97780-b5f6-11ea-8d90-cfd302fac5a1.png)

**Comment by kinoroy** [comment]
Hey @yspreen thanks for reporting this! Would you be interested in submitting a PR for this? :) No pressure

**Comment by martinpucik** [comment]
@yspreen I think this is not used anymore on `development` branch. Could you please check if this could be consider fixed?

**Comment by kinoroy** [comment]
@martinpucik Confirmed, #1341 fixed this.
![Screen Shot 2020-06-30 at 11 00 00 AM](https://user-images.githubusercontent.com/22554212/86160680-f67b8a00-bac0-11ea-8df4-0034c9499f59.png)
