### ISSUE TITLE
Type does not conform to protocol 'MessagesDataSource'

### ISSUE THREAD

**Issue by nurlan-dzhavadov** [MessageKit/MessageKit#1389]
I have the same issue, as in issues #1332 and #978 . The problem is that none of the answers have helped me at all. 
Here is the screenshot of my screen in Xcode. I have the latest Xcode version and of course the latest version of iOS on my simulator, as well as in my project (the default iOS version is iOS 13 or above)

<img width="854" alt="Снимок экрана 2020-06-24 в 18 50 49" src="https://user-images.githubusercontent.com/56748319/85589717-75e60500-b64c-11ea-90a0-712514d6aca2.png">

I've just followed the instruction in the guide for beginners. I just have a different name of the ViewController itself, as you can see in the screenshot, but nothing else.

Here is the full code of the ViewController:

```
import UIKit
import MessageKit

public protocol MessageType {

    var sender: Sender { get }
    var messageId: String { get }
    var sentDate: Date { get }
    var kind: MessageKind { get }
}

public protocol SenderType {

    var senderId: String { get }
    var displayName: String { get }
}

class PhoneAddictionChatVC: MessagesViewController {

    override func viewDidLoad() {
            super.viewDidLoad()
        
        messagesCollectionView.messagesDataSource = self
        messagesCollectionView.messagesLayoutDelegate = self
        messagesCollectionView.messagesDisplayDelegate = self
        }
    }

public struct Sender: SenderType {
    public let senderId: String

    public let displayName: String
}

// Some global variables for the sake of the example. Using globals is not recommended!
let sender = Sender(senderId: "any_unique_id", displayName: "Steven")
let messages: [MessageType] = []

extension PhoneAddictionChatVC: MessagesDataSource {

    func currentSender() -> SenderType {
        return Sender(senderId: "any_unique_id", displayName: "Steven")
    }

    func numberOfSections(in messagesCollectionView: MessagesCollectionView) -> Int {
        return messages.count
    }

    func messageForItem(at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> MessageType {
        return messages[indexPath.section]
    }
}

extension PhoneAddictionChatVC: MessagesDisplayDelegate, MessagesLayoutDelegate {}




```

**Comment by kinoroy** [comment]
Your problem comes from re-declaring `MessageType` and `SenderType`, these are protocols provided already by MessageKit and when you re-declare them, you create a new `MessageType` which is not compatible with MessageKit's `MessageType` because despite having the same name, they are not the _same type_. You need to delete these declarations from your code: 
```swift
public protocol MessageType {

    var sender: Sender { get }
    var messageId: String { get }
    var sentDate: Date { get }
    var kind: MessageKind { get }
}

public protocol SenderType {

    var senderId: String { get }
    var displayName: String { get }
}
```

**Comment by nurlan-dzhavadov** [comment]
Wow! I didn't know that I don't need to use that. Thank you for a quick response! It solved my problem)
