### ISSUE TITLE
Messages scroll up out of view when i begin to type

### ISSUE THREAD

**Issue by ahmedwasil** [MessageKit/MessageKit#1392]
Latest 3.1.0 version. 

When i start to type, the messagesCollectionView scrolls up and messages end up out of view.

Anyone experienced this? and know a quick fix?

Thanks

**Comment by kinoroy** [comment]
If you're referring to the iMessage-like behaviour of scrolling to the last message when the user begins typing then make sure that both `scrollsToLastItemOnKeyboardBeginsEditing`, and `scrollsToBottomOnKeyboardBeginsEditing` are set to false on your MessagesViewController (this is the default, but if you copied some code from the Example project then one of them might be set to true).

**Comment by ahmedwasil** [comment]
Yes exactly that behaviour. I can't find these variables set in my class, but have set them to false to be sure but still same issue persists.

**Comment by kinoroy** [comment]
@ahmedwasil Can you post some code that reproduces this? This doesn't reproduce in the example app when I remove the line setting `scrollsToBottomOnKeyboardBeginsEditing = true`.

**Comment by ahmedwasil** [comment]
I think I have traced the issue into the InputBarAccessoryView. When i enter the first character, it updates the RightStackView and hides 2 buttons, shows the send button and changes the width constraint. 

Function in Messages View Controller:

```swift
func inputBar(_ inputBar: InputBarAccessoryView, textViewTextDidChangeTo text: String) {

        if text.count > 0 {
            customInputBar?.showSendButton()
        } else {
           customInputBar?.hideSendButton()
        }
    }
```


Function in CustomInputBar

`func showSendButton() {
        setRightStackViewWidthConstant(to: 40, animated: false)
        self.sendButton.isHidden = false
        self.cameraButton.isHidden = true
        self.fileButton.isHidden = true
    }`
