### ISSUE TITLE
SwiftUI InputAccessoryView not showing

### ISSUE THREAD

**Issue by davy-devibharat** [MessageKit/MessageKit#1405]

**Comment by kinoroy** [comment]
I'm not a SwifUI expert but it doesn't seem to have a separate concept of inputAccessoryView and firstResponder so I'm not sure how well they're meant to interact. 

The two workarounds I've seen so far are either 1) Embed the MessagesVC as the rootVC of a UINavigationController and then bridge the navVC to SwiftUI, or 2) Make a subclass of MessagesVC, and then in your `viewDidAppear()` lifecycle method, add `becomeFirstResponder()` and then bridge that subclass to SwiftUI.
