### ISSUE TITLE
How can I remove the animation when the keyboard dismiss?

### ISSUE THREAD

**Issue by xiaoshuaiyu1993** [MessageKit/MessageKit#1406]
Hi, The lastest version of MessageKit, I changed the keyboardDismissMode to onDrag, and I changed the messageStyle to my custom style, then when the keyboard dismiss, the cell got an animation that loads from left to right, top to bottom，how can I fix that?

**Comment by kinoroy** [comment]
Can you please provide at least a screen recording showcasing the issue? And if possible, code that would help us reproduce this?

**Comment by xiaoshuaiyu1993** [comment]
Thanks for your reply, the following is the showcasing, but it doesn't seem obvious, so I also record an slow animation version,
![Untitled2](https://user-images.githubusercontent.com/13144082/87266836-c1c3f580-c4f8-11ea-81e5-cc3af0a929cb.gif)
![Untitled](https://user-images.githubusercontent.com/13144082/87267025-2da65e00-c4f9-11ea-844d-8b9d3bae573e.gif)

**Comment by seasoftvuhphuong** [comment]
I have a same issue, too

![61D64912-A25F-4392-8F9A-A489F1D78EC2](https://user-images.githubusercontent.com/65529176/87419182-413aed00-c5fd-11ea-9638-f56cbcc46106.gif)

**Comment by lhr000lhrmega** [comment]
the animation is caused by `messageCollectionViewBottomInset`
I added this code below in `MessagesViewController+Keyboard.swift` that fixes the unexpected animation.

``` Swift
 UIView.performWithoutAnimation {
            messageCollectionViewBottomInset = newBottomInset
}
```
But this is pretty hacking, no sure whether it's the best solution.

**Comment by kinoroy** [comment]
Thanks for the screen recording @xiaoshuaiyu1993 , I'll mark this as a bug.

@lhr000lhrmega Thanks for sharing your solution. Would you like to submit a pull request fixing this? :)

**Comment by lhr000lhrmega** [comment]
> Thanks for the screen recording @xiaoshuaiyu1993 , I'll mark this as a bug.
> 
> @lhr000lhrmega Thanks for sharing your solution. Would you like to submit a pull request fixing this? :)

No problem.

**Comment by alexanderconstancio** [comment]
Has this issue been updated in master? Thanks

**Comment by lhr000lhrmega** [comment]
> Has this issue been updated in master? Thanks


 try this fork
https://github.com/lhr000lhrmega/MessageKit

**Comment by kinoroy** [comment]
Thanks to @lhr000lhrmega the fix has been merged into develop, and will be included in the next release.

**Comment by lhr000lhrmega** [comment]
> Thanks to @lhr000lhrmega the fix has been merged into develop, and will be included in the next release.

(*^▽^*)

**Comment by Kaspik** [comment]
Release is just about to happen, closing this now! :)
