### ISSUE TITLE
load More Messages

### ISSUE THREAD

**Issue by haykqolozyan** [MessageKit/MessageKit#1407]

**Comment by haykqolozyan** [comment]
In some cases, while loading additional messages, the function "reloadDataAndKeepOffset()" does not work correctly.

**Comment by kinoroy** [comment]
Hey! Thanks for opening an issue. 

Unfortunately we cannot help you debug this without additional context, like replication steps or code that reproduces the issue or more detailed descriptions of the cases in which this happens. Please use and fill out as much detail in the provided bug issue template that you can when creating an issue. I can re-open this issue if you can provide additional context that we can look into :)
