### ISSUE TITLE
Hi, i want to implement some function in UITextViewDelegate

### ISSUE THREAD

**Issue by fukemy** [MessageKit/MessageKit#1409]
Hello, as the way you using typing indicator to show when online user is typing, i want to implement it when the user start typing and send event to server.
 `
So I think the only way is implement TextViewDidBeginEditting and TextViewDidEnEditing
`

But i hear u decided to remove UITextViewDelegate in issue [262](https://github.com/MessageKit/MessageKit/pull/262)

<b>nathantannar4 commented on Oct 17, 2017 </b>
`
It appears that inside a UITextVIew anchoring a label to the left and right anchors don't extend the labels width all the way, thus adjusting the textAllignment doesn't have visible changes. (Thanks @hemangshah)
`
`
This fix changes the constraints of the label to use a width anchor instead of a right anchor. Also removed the UITextViewDelegate as I saw it was causing other MessageInputBar height issues and was previously only included as a temp solution to another bug that was corrected.
`

 So can you give me some advices? Thanks

**Comment by kinoroy** [comment]
MessageKit no longer uses the UITextViewDelegate internally, however you're still free to set the text view delegate yourself. For example, you could extend your MessagesVC subclass as a `UITextViewDelegate` and then in `viewDidLoad`, set the delegate like this: 
```swift
messageInputBar.inputTextView.delegate = self
```

Another way you could do this is just by listening to the `textDidBeginEditingNotification` and `textDidEndEditingNotification` notifications through `NotificationCenter` like this:
```swift
        NotificationCenter.default.addObserver(self,
                                               selector: #selector(yourMethodHere),
                                               name: UITextView.textDidBeginEditingNotification, object: nil)
        NotificationCenter.default.addObserver(self,
                                               selector: #selector(anotherMethodHere),
                                               name: UITextView.textDidEndEditingNotification, object: nil)
```
where `yourMethodHere` and `anotherMethodHere` are `@objc` exposed methods that you create.

**Comment by fukemy** [comment]
yeah im using your 2nd method, thanks <3
