### ISSUE TITLE
error keyboard autodismiss, can determine which's cause that situation

### ISSUE THREAD

**Issue by fukemy** [MessageKit/MessageKit#1412]
Hello, i only got this problem when have multi image cell in chatVc, i make video for you can see clearly:
https://streamable.com/0rzurs
 Just scroll up a bit then the problem disappear, but when scroll to bottom, the problem show again
 
 i tried to find the line that make endediting/risignfirstResponder, but can not find the exactly code cause this. Please helppp

**Comment by fukemy** [comment]
i have put all debug to "endEditing" and"resignFirstResponder", but can not catch one of theme
![Screen Shot 2020-07-19 at 17 28 28](https://user-images.githubusercontent.com/8202437/87872749-825c4400-c9e5-11ea-9a47-e13954e41ffc.png)
![Uploading Screen Shot 2020-07-19 at 17.28.47.png…]()

**Comment by fukemy** [comment]
after enable OS_DEBUGGING i see this log:
`
First responder warning: '<InputBarAccessoryView.InputTextView: 0x105927e00; baseClass = UITextView; frame = (0 0; 644 43); text = ''; clipsToBounds = YES; tintColor = UIExtendedSRGBColorSpace 0.270588 0.756863 0.34902 1; gestureRecognizers = <NSArray: 0x280e93b70>; layer = <CALayer: 0x280035680>; contentOffset: {0, 0}; contentSize: {644, 43}; adjustedContentInset: {0, 0, 0, 0}>' rejected resignFirstResponder when being removed from hierarchy
`

**Comment by fukemy** [comment]
found problem, so lucky when find exactly in > 1000 lines of code
`
 override func viewWillLayoutSubviews() {
        super.viewWillLayoutSubviews()
        
        if self.isFirstResponder != true {
            self.perform(
                #selector(becomeFirstResponder),
                with: nil,
                afterDelay: 0.3
            )
        }
    }
`
i dont know what purpose to use this code, but im copy from github search to solve problem that i forgot, sorry

**Comment by fukemy** [comment]
ok i got this code from [here](https://github.com/MessageKit/MessageKit/issues/696) when i want to embed chatVC into other vc, lul i waste 1 days for fix this problem

**Comment by alexanderconstancio** [comment]
> found problem, so lucky when find exactly in > 1000 lines of code
> `
> override func viewWillLayoutSubviews() {
> super.viewWillLayoutSubviews()
> 
> ```
>     if self.isFirstResponder != true {
>         self.perform(
>             #selector(becomeFirstResponder),
>             with: nil,
>             afterDelay: 0.3
>         )
>     }
> }
> ```
> 
> `
> i dont know what purpose to use this code, but im copy from github search to solve problem that i forgot, sorry

I am still having this issue in my app, where are you supposed to place this code in the project?

**Comment by fukemy** [comment]
@alexanderconstancio this code is provided for display textview when you place messageVC into other VC, if u have same issue, just check all function below in your app
`becomeFirstResponder`
`regisnFirstResponer`
`endediting(true)`

put debug then check where the code make your issue
