### ISSUE TITLE
How to update bottom label?

### ISSUE THREAD

**Issue by Mactacs** [MessageKit/MessageKit#1413]
How can I update specific message bottom label when message was sent to the app server?

**Comment by kinoroy** [comment]
Hi @Mactacs, 

Your custom class or struct that conforms to `MessageType` could have a variable on it that tracks the state of the message `sent, delivered, etc` and when you send the message, and receive feedback from your server you simply update that model in your data source, and reload that item in the collection view. Then make use of the message `bottomLabel` in MessageKit to display this status. You can see an example of using the bottom label in the example app repo.
