### ISSUE TITLE
How can I change default cell height (middle container from default 52) to any greater than it?

### ISSUE THREAD

**Issue by Lihuo** [MessageKit/MessageKit#1414]

**Comment by kinoroy** [comment]
Hi @Lihuo , 

Could you be more clear about your question? Is this for a custom cell or for a built-in MessageKit cell? The built-in cells should size to their content, but if you want to add padding to the top and bottom by using `setMessageIncomingMessagePadding` and `setMessageOutgoingMessagePadding` on the `messagesCollectionView.messagesCollectionViewFlowLayout` object.

**Comment by Lihuo** [comment]
Hi @kinoroy ,

My purpose is want to change the build-in MessageKit cell height to dynamic (type as text) and I just figure it out the custom way to do it, but I lost some delegate method from the build- in (messageDisplay delegate method).

**Comment by Lihuo** [comment]
@kinoroy , 
![Screen Shot 2020-07-22 at 16 40 04](https://user-images.githubusercontent.com/18390488/88161362-19b9d500-cc3a-11ea-8832-5bd1c94498bb.png)
![Screen Shot 2020-07-22 at 16 35 08](https://user-images.githubusercontent.com/18390488/88161367-1aeb0200-cc3a-11ea-8e9e-324be768c2fd.png)

both of these image have different height and this is what I want, but I can apply any functions related to MessageDisplay delegate (it's not affected).

**Comment by Lihuo** [comment]
Okay, I can change text height to dynamic by override function textMessageSizeCalculator function.
