### ISSUE TITLE
Is there a built-in property/view to show when there are no messages in a MessagesViewController? 

### ISSUE THREAD

**Issue by Jovy83** [MessageKit/MessageKit#1416]
Hi, 

This is more of a question than an issue. Is there a built-in view or property that I can use to show when there are no messages yet in a `MessagesViewController`? For example on Android, I use a `RecyclerView` for my chat layout and it has an `emptyView` property that can be used to show a message to the user if there are no messages yet. Is there an equivalent for MessageKit?

Thanks.

**Comment by kinoroy** [comment]
Hey @Jovy83, 

You set the `backgroundView` of the `messagesCollectionView` to a `UILabel` which shows your message. You could then show/hide it when you update your data source, depending on if there are messages or not.

**Comment by Jovy83** [comment]
@kinoroy This helps a lot. Thanks for the info!
