### ISSUE TITLE
Cant Build MessageKit :(

### ISSUE THREAD

**Issue by JordanHanley** [MessageKit/MessageKit#1420]
Hey I keep trying to install MessageKit through coco pods. But every time I try to build my Xcode project I get compilation errors.

<img width="275" alt="Screen Shot 2020-07-29 at 6 47 03 PM" src="https://user-images.githubusercontent.com/19930988/88861513-1f7c6100-d1cc-11ea-9c21-adfe2ce5c902.png">

Message Kit Version - 3.1.0
Xcode Version - 10.3
Deployment Target - 12.4
Swift - 5.0
Tested on iphoneXR

Any insight would be much appreciated

**Comment by kinoroy** [comment]
Hi @yords123 

You'll need to use Xcode 11 (which is the latest stable version) to build MessageKit. Xcode 10 is no longer supported.
