### ISSUE TITLE
Why is there no support for Swift Package Manager

### ISSUE THREAD

**Issue by rob8861** [MessageKit/MessageKit#1425]
Swift Package Manager is what Cocoapods should have always been.
We are trying very hard to get rid of this cancer known as cocoapods.

are there plans to add SPM support to MessageKit

Thanks

**Comment by rob8861** [comment]
looks like it is because SPM doesn't support assets. oh well...

**Comment by Kaspik** [comment]
Yes, we are waiting for XCode 12 and Swift 5.3 :) Use master with new XCode if you want to try that - https://github.com/MessageKit/MessageKit/pull/1341
