### ISSUE TITLE
messages do not display any attributed text (top or bottom)

### ISSUE THREAD

**Issue by rob8861** [MessageKit/MessageKit#1426]
Hello,

I am trying a basic vanilla implementation of MessageKit.
Things seem to work but when messages are received or sent, the top or bottom attributed text such as the name of the sender or date aren't showing, even tho the delegate methods are being called.

for instance

`func cellTopLabelAttributedText(for message: MessageKit.MessageType, at indexPath: IndexPath) -> NSAttributedString? {
        if indexPath.section % 3 == 0 {
            return NSAttributedString(string: MessageKitDateFormatter.shared.string(from: message.sentDate), attributes: [NSAttributedString.Key.font: UIFont.boldSystemFont(ofSize: 10), NSAttributedString.Key.foregroundColor: UIColor.darkGray])
        }
        return nil
    }
    
    func cellBottomLabelAttributedText(for message: MessageKit.MessageType, at indexPath: IndexPath) -> NSAttributedString? {
        
        return NSAttributedString(string: "Read", attributes: [NSAttributedString.Key.font: UIFont.boldSystemFont(ofSize: 10), NSAttributedString.Key.foregroundColor: UIColor.darkGray])
    }
    
    func messageTopLabelAttributedText(for message: MessageKit.MessageType, at indexPath: IndexPath) -> NSAttributedString? {
        let name = message.sender.displayName
        return NSAttributedString(string: name, attributes: [NSAttributedString.Key.font: UIFont.preferredFont(forTextStyle: .caption1)])
    }
    
    func messageBottomLabelAttributedText(for message: MessageKit.MessageType, at indexPath: IndexPath) -> NSAttributedString? {
        
        let dateString = formatter.string(from: message.sentDate)
        return NSAttributedString(string: dateString, attributes: [NSAttributedString.Key.font: UIFont.preferredFont(forTextStyle: .caption2)])
    }`

are all called with the current data but when the collectionView updates with new messages only the message text and the ? mark are displayed. 

Any idea how I can display the sender name and the date the message was sent/received

here is what I have so far. as you can see, the date and sender name aren't showing

![image](https://user-images.githubusercontent.com/1551002/89448572-75498f80-d71d-11ea-8a58-d1eadc405705.png)

Thanks

**Comment by kinoroy** [comment]
Hi @rob8861,

Are you setting the correct height for your labels in your `MessagesLayoutDelegate`?  The default height for these labels is zero: 
```swift
    func cellTopLabelHeight(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> CGFloat {
        return 0
    }
    
    func cellBottomLabelHeight(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> CGFloat {
        return 0
    }
    
    func messageTopLabelHeight(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> CGFloat {
        return 0
    }

    func messageBottomLabelHeight(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> CGFloat {
        return 0
    }
```

**Comment by rob8861** [comment]
Hi @kinoroy 

Thank you. That's what I was missing. The documentations did not mention that the default value is zero. It just said "you do not need to implement those protocols". Maybe update the docs?

anyhow, now the labels are showing but the avatar icon shifted to the bottom

![image](https://user-images.githubusercontent.com/1551002/89454741-c14d0200-d726-11ea-9728-e3702d11d79b.png)

any idea how to fix that.

Thanks

**Comment by rob8861** [comment]
this

`func avatarPosition(for message: MessageKit.MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> AvatarPosition`

doesn't seem to do anything, regardless of what position I choose.

**Comment by kinoroy** [comment]
@rob8861 

the `avatarPosition` delegate method was removed from MessagesLayoutDelegate in version 1.0. `avatarPosition` is now a parameter set on the layout object:

```swift
messagesCollectionView.messagesCollectionViewFlowLayout.setMessageIncomingAvatarPosition(...)
messagesCollectionView.messagesCollectionViewFlowLayout.setMessageOutgoingAvatarPosition(...)
```

Sorry that the docs were confusing. You don't need to implement any of those methods _to compile your app_ because they have default implementations. However you are choosing to override some of those default implementations (like `cellBottomLabelAttributedText`) so you need to also override the default height as well. The default height of 0 works for the default `cellBottomLabelAttributedText` because the label is `nil` by default. 

I can create an issue about updating the docs to maybe make this more clear. You're always welcome to submit a PR if you find something is lacking as well.

**Comment by rob8861** [comment]
@kinoroy 
Thank you again for the quick reply and support. It worked.

I am sure as I use the library more and integrate more features I'll have other ideas or suggestions and will be happy to contribute to this effort.

thank you again.
