### ISSUE TITLE
MessageInputBar overlaps TabBar view in iPad split view mode

### ISSUE THREAD

**Issue by htnha** [MessageKit/MessageKit#1430]
Hi,

I currently have a problem with MessageInputBar in iPad split view mode:

A Tab Bar controller is used in the master view, then the MessageInputBar overlaps it when opening a chat.

I embed the MessageVieController in a UIViewController. How can I adjust the MessageInputBar's width so that it only fits in the containing UIViewController.

Please help me!

**Comment by htnha** [comment]
Any one please help me?

**Comment by Kaspik** [comment]
Hey! Did you check our example app? I believe there is a split view mode example as well.
