### ISSUE TITLE
top label alignment

### ISSUE THREAD

**Issue by Hamza-Almass** [MessageKit/MessageKit#1432]
Hi, 

i am try to implement the cellTopLabelAlignment to align the username but it's not work?
how can i set it

thank you

**Comment by kinoroy** [comment]
Hi @hamdshah 

Can you please share the code you are using, and a more detailed explanation describing what the current behaviour is, and what you expect the behaviour to be. This will help us, help you. For your reference, have a look at this StackOverflow guide on how to create a reproducible example: https://stackoverflow.com/help/minimal-reproducible-example

Thanks
