### ISSUE TITLE
Tap on mention user did not get any event

### ISSUE THREAD

**Issue by shahchirag2110** [MessageKit/MessageKit#1438]
Describe the bug
I have added mentioned user in message and it will show highlighted but when i tap on that name. no event get me that user name.

To Reproduce
Steps/code to reproduce the behavior :
Add mention user and tap on the that name 

```
func didTapMessage(in cell: MessageCollectionViewCell) {
        print("Message tapped")
        
        if cell is LocationMessageCell, let index = messagesCollectionView.indexPath(for: cell){
            messageView?.resignKeyboard()
            self.openMapForPlace(index: index)
        }
    }
    
    func didTapImage(in cell: MessageCollectionViewCell) {
        print("Image tapped")
        
        if let index = messagesCollectionView.indexPath(for: cell){
            messageView?.resignKeyboard()
            self.showImageInFullScreen(index: index)
        }
        
    }
    
    func didTapAvatar(in cell: MessageCollectionViewCell) {
        print("Avtar tapped")
        if let index = messagesCollectionView.indexPath(for: cell)
        {
            let objChat = self.messageList[index.section].arrChat[index.row]
            goToOtherProfileVC(myViewController: self, userID: objChat.senderId ?? 0)
        }
    }
    func didTapBackground(in cell: MessageCollectionViewCell) {
        print("background tapped")

    }
```
Expected behavior :
We get user name on which i get taped.

Video
[https://drive.google.com/file/d/1ewVR2khyW__zHWJO08AL8Cr6T-2MIUK1/view?usp=sharing](https://drive.google.com/file/d/1ewVR2khyW__zHWJO08AL8Cr6T-2MIUK1/view?usp=sharing)

Environment

Version of MessageKit : 3.1.0
Version of iOS : iOS 12
Version of Swift : swift 5
What device(s) are you testing on? : simulators , iPhone 5SE

**Comment by mmdock** [comment]
shouldn't you need to implement `didSelectMention(_ mention: String)` https://github.com/MessageKit/MessageKit/blob/05b481c1f7eda0233d1a8eaaec5fd0aa9b75a142/Sources/Protocols/MessageLabelDelegate.swift#L64

**Comment by shahchirag2110** [comment]
@mmdock Will you please guide me how I can use this delegate?
