### ISSUE TITLE
Missing image assets in example project

### ISSUE THREAD

**Issue by fossil12** [MessageKit/MessageKit#1440]
**Describe the bug**
When running the example application the app crashes, because the image assets are missing.

**To Reproduce**

1. Clone Repository
2. Check out `development` branch
3. Run `pod install` in `Example`
4. Open project in Xcode (11.6 (11E708))
5. Run in iOS 13.6 Simulator
4. Tap on "Basic Example"

**Expected behavior**
Example is shown.

**Actual behavior**
App crashes because, the referenced images in `SampleData` are not in the project.

If I missed a step on how to run the example project, please let me know.

**Comment by fossil12** [comment]
I checked out cbc908b71056864a4340160431d069c5cff8bdfd. There the assets are still around.

**Comment by Kaspik** [comment]
Seems like our development branch was missing whole Resources folder included in the project, fixed, waiting for CI. Thanks for reporting this! :)
