### ISSUE TITLE
Messages hides under keyboard

### ISSUE THREAD

**Issue by matsotaa** [MessageKit/MessageKit#1443]
**Describe the bug**
I could enter in my chat from several points. Enter into chat: from ViewController of TabBar which is NavigationController also; or from ViewController which is a child of some TabBarItem through NavigationController.
So, when I enter in my messageCollectionView and start typing messages I have no problem with it, but when I scroll collectionView to the highest point of it I've that some part of my message hides under keyboard.
I suppose it some issue with constraints or what.
Sometimes I've got same problem when I just entered into message view controller and start typing, but it's rare, so I guess it's just a symptom of main problem described before

I have in viewDidLoad:
scrollsToBottomOnKeyboardBeginsEditing = true 
maintainPositionOnKeyboardFrameChanged = true

Also tried with: 
override func viewDidLayoutSubviews() {
        super. viewDidLayoutSubviews()
        messagesCollectionView.contentInset.bottom = messageInputBar.frame.height
        messagesCollectionView.scrollIndicatorInsets.bottom = messageInputBar.frame.height
    }

Have Any ideas?

**Environment**
- What version of MessageKit are you using?
3.0.0
- What version of iOS are you running on?
iOS 12.0
- What version of Swift are you running on?
![2020-08-27 19 46 35](https://user-images.githubusercontent.com/59237122/91470986-17ccdc80-e89e-11ea-8486-f1a735fb3dea.jpg)
![2020-08-27 19 46 41](https://user-images.githubusercontent.com/59237122/91470995-1b606380-e89e-11ea-98c7-cf9e133189a7.jpg)

Swift 4
- What device(s) are you testing on? Are these simulators?
iPhone Pro 11 (device, not simulator)
- Is the issue you're experiencing reproducible in the example app?
YES

**Additional context**

**Comment by Kaspik** [comment]
Does it happen with our latest release as well?

**Comment by matsota** [comment]
Yes, I updated pod but nothing happens, so I've back to 3.0.0

**Comment by matsotaa** [comment]
> Does it happen with our latest release as well?

Yes, I updated pod but nothing happens, so I've back to 3.0.0

Right now I've updated this project to swift 5 and MessageKit to latest. But problem is still with me

**Comment by matsotaa** [comment]
> Does it happen with our latest release as well?

Hi, again. I probably have something interesting. That is happens only when scroll is coming to the `navigationBar`
And if `navigationController?.navigationBar.prefersLargeTitles = true` I have this problem.
If I have `navigationController?.navigationBar.prefersLargeTitles = false` of my ChatViewController this problem goes away, but some cells in the top (first few cells I downloaded) hides under navigationBar.

**Comment by matsotaa** [comment]
Sorry, but did your receive my comment? This issue with navigatorBar is on side of MessageKit, or I did some wrong? Also I have strange indent from keyboard and last message, `whenKeyboardAppears`

**Comment by Kaspik** [comment]
It might be, and it might not be - the best would be checking our example project if it works or not. :) I wasn't trying to investigate it, so I left the Bug? label on it so someone else can take a look.

**Comment by matsota** [comment]
Maybe you can help how to remove indent to keyboard when it appears? additionalBottomInset

**Comment by matsotaa** [comment]
Maybe you can help how to remove indent to keyboard when it appears? I found an additionalBottomInset. And when I type additionalBottomInset = -100 extra indent is hides, but this is bad solution I guess. I suppose this problem occurs because I Have a TabBarController, and when I entered in chat I dismiss bottom items of tabbar. and somehow it add for me additionalBottomInset when keyboard appears. Or something like that, maybe it counting tabbarHeight, but it not exist in chatVC.. somewhere there.

**Comment by wassup-** [comment]
Can this please be reopened? I have the same issue. This started happening after updating MessageKit from 2.0.0 to 3.3.0.
As @matsota suggested, setting `navigationBar.prefersLargeTitles = false` prevents this from happening, however a real fix should be implemented.

**Comment by matsota** [comment]
> Can this please be reopened? I have the same issue. This started happening after updating MessageKit from 2.0.0 to 3.3.0.
> As @matsota suggested, setting `navigationBar.prefersLargeTitles = false` prevents this from happening, however a real fix should be implemented.

**Comment by matsotaa** [comment]
@wassup- Don't forget that `navigationBar.prefersLargeTitles = false` don't actually helps. It just transfer problem to the top. Actually I realized that I did not try to open `chatVC` from parent `ViewController` through `NavigationController`. Any way I decided to make make custom chat.. So good luck to you. If you will handle this don't forget to tell us all :)

**Comment by wassup-** [comment]
I'm not sure I understand what you mean with *it just transfer problem to the top*? Do you mean the collectionview has wrong insets? Or do you mean content scrolls out-of-screen at the top (which is normal for scroll views)?

**Comment by matsotaa** [comment]
@wassup- in my case when I set `navigationBar.prefersLargeTitles = false` few last messages hides under Navigation Controller Bar, when it contains more than screen can show at one time. It's not big deal, but kinda frustrating) Any way do you show your chatVC from parent? If not - try, maybe it will be helpful

**Comment by wassup-** [comment]
My setup is the following: `UITabBarController` -> `UINavigationController` -> `MyMessagesViewController`.
As far as I can tell, I'm not having any issues with content disappearing behind the navigation bar, other than the default scroll view behaviour when the content is too big to display at once.

The messages view controller is the root view controller of the navigation controller. I'm using a custom `InputBarAccessoryView` that sticks above the tab bar so the user can still navigate through the tabs.

![Simulator Screen Shot - iPod touch (7th generation) - 2020-12-17 at 17 17 00](https://user-images.githubusercontent.com/1745504/102514930-642a6b00-408d-11eb-90cf-924e8674fc74.png)


This involves playing with padding, but this exact same setup has worked before with 2.0.0 (only back then it was a custom `MessageInputBar`), so I don't think that is the problem.

**Comment by Kaspik** [comment]
I believe the problem isn't with large titles, but that you need to add custom inset that will count with tab bar height. MessagesController counts with insets / offsets that it can count with, but it doesn't count with Tab bar itself afaik.
