### ISSUE TITLE
Dismiss keyboard from InputBarButtonItem

### ISSUE THREAD

**Issue by neugierige** [MessageKit/MessageKit#1445]
UPDATE: It's unclear to me how it's possible to programmatically dismiss the keyboard at all. After seeing that `resignFirstResponder` didn't work on anything, I checked `isFirstResponder` and it returns false on `messageInputBar.inputTextView` (as well as messageInputBar and the view controller itself). I also tried calling `endEditing` and that made no difference either. Any ideas?? 

I need to implement a tool bar button that can dismiss the keyboard, and I'm wondering how best to do this. I do not have reference to `messageInputBar` inside of that `.onTouchUpInside` closure. Of course, I can always use a notification, but is there a way to set up a target/selector inside the InputBarButtonItem declaration? 

```swift
private var dismissKeyboardButton: InputBarButtonItem = {
    return InputBarButtonItem()
        .configure {
            $0.spacing = .fixed(22)
            $0.image = UIImage(named: WFImageIconDismissKeyboard)
            $0.setSize(CGSize(width: 25, height: 25), animated: false)
            $0.accessibilityLabel = "close_keyboard".localized()
        }.onTouchUpInside { button in
            print("dismiss button tapped")
            // TODO: dismiss keyboard
        }
}()
```

- What version of MessageKit are you using? 
the latest

- What version of iOS are you running on?
13.2

- What version of Swift are you running on?
5.0

- What device(s) are you testing on? Are these simulators?
No, iPhone 7 and iPhone X

- Is the issue you're experiencing reproducable in the example app?
Not an issue

**Comment by neugierige** [comment]
I found a way to get around this problem: 
1. Assign your subclass of MessageViewController to be a `UITextViewDelegate`
2. Implement `textViewDidBeginEditing`
3. Inside this function, set the textView to be the firstResponder with `textView.becomeFirstResponder()`. This textView is messageInputBar's inputTextView
4. Inside your dismiss keyboard function, call `messageInputBar.inputTextView.resignFirstResponder()`

**Comment by martinpucik** [comment]
@neugierige you can use [UIView.endEditing()](https://developer.apple.com/documentation/uikit/uiview/1619630-endediting) to resign the first responder of the current view

**Comment by neugierige** [comment]
That doesn't work. I pretty much exhausted all other options before finding this strategy. I encourage you to try this yourself.

**Comment by Kaspik** [comment]
Have you been able to figure out who is the first responder in the moment you are tapping the button? I would start digging into that.

**Comment by neugierige** [comment]
@Kaspik Please see the content of the issue I provided above. That is exactly what I did. When the keyboard is up, no one is the first responder. That's why I had to set it to get it to work. Here are the repo steps if you want to try: 

1. Create a InputBarButtonItem and add it to the messageInputBar
2. In the `onTouchUpInside` closure, post a notification that the button was tapped
3. In your MessageViewController subclass, add observer to the notification, and try to dismiss the keyboard

To be clear, I did this inside BasicExampleViewController and neither `resignFirstResponder` nor `endEditing` worked. `messageInputBar.inputTextView.isFirstResponder` is false inside `textViewShouldBeginEditing`, but in `textViewDidEndEditing` it is true again. 🤷
