### ISSUE TITLE
Link previews overlap with media items

### ISSUE THREAD

**Issue by mmdock** [MessageKit/MessageKit#1446]
**Describe the bug**
Image previews and media types right next to each other frequently cause an overlap.
**To Reproduce**
Steps/code to reproduce the behavior:
Reproduce in the example app by simply configuring the example app's setting as such in the screenshots below and then going to advanced example, zero code changes.

**Expected behavior**
Not to have them overlap.

**Screenshots**
<img width="367" alt="Screen Shot 2020-08-30 at 4 25 04 PM" src="https://user-images.githubusercontent.com/2423465/91671639-65835800-eadd-11ea-8874-ea3f0efa2469.png">

<img width="348" alt="Screen Shot 2020-08-30 at 4 22 03 PM" src="https://user-images.githubusercontent.com/2423465/91671624-408ee500-eadd-11ea-860c-58d961ed4fe3.png">
<img width="353" alt="Screen Shot 2020-08-30 at 4 21 26 PM" src="https://user-images.githubusercontent.com/2423465/91671625-41277b80-eadd-11ea-8890-a2d4f686cfe6.png">

**Environment**
- What version of MessageKit are you using? Version used by example app as of Aug 30, 2020
- What version of iOS are you running on? example above used iOS 12.4
- What version of Swift are you running on? whatever is included in Xcode 11.6 and also Xcode 12 (I'm running both on my machine and frequently changing between 11E708 CLT and 12A8189h CLT, have tested in simulator using BOTH command line tool sets.)
- What device(s) are you testing on? Are these simulators?  (iPhone X, iOS 12.4 simulator), (iPhone Xs, iOS 14 real device)
- Is the issue you're experiencing reproducible in the example app? Yes.

**Additional context**

**Comment by kinoroy** [comment]
Hi @mmdock thanks so much for opening an issue!

I was able to repro this so I'll mark it as confirmed and one of us can look at this soon in more detail

I'll loop in @bguidolim who did the link preview feature and maybe he could have a look

**Comment by bguidolim** [comment]
Done 👍

**Comment by Kaspik** [comment]
Thanks guys, I'll either ship a hotfix or new version together with https://github.com/MessageKit/MessageKit/pull/1444 today. :)

**Comment by ElrB** [comment]
Hi guys, please help.

How does one configure link preview messages. Can you please show me or refer me to a code example, thanks, will highly appreciate it.
