### ISSUE TITLE
Add a MKPointAnnotation to Location Message

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#145]
The current location message is bare bones. It would be nice to add a pin representing the exact location on the map.

![screen shot 2017-09-21 at 11 51 31 am](https://user-images.githubusercontent.com/7445580/30708102-42af923a-9ec3-11e7-804c-790d252672a2.png)

**Comment by etoledom** [comment]
If it’s fine I’d like to get this one ☝️

**Comment by SD10** [comment]
@etoledom Feel free 👍

**Comment by SD10** [comment]
This was added in #150
