### ISSUE TITLE
Add button inside InputTextView?

### ISSUE THREAD

**Issue by kientux** [MessageKit/MessageKit#1452]
Let's say I want to achive this input layout:

![image](https://user-images.githubusercontent.com/4200743/92221533-d5bc2000-eec7-11ea-947b-ee5d5b951a55.png)

I can add 2 buttons in left `InputStackView`. But what about that "emoji" button next to `InputTextView`? The problem is `middleContentView` must have rounded corner and gray background, so emoji and send button cannot be both in right stackView.

**Comment by martinpucik** [comment]
Hey @kientux did you try to add the `emoji button` into the input textview as a subview? And you could use [UITextView.textContainerInset](https://developer.apple.com/documentation/uikit/uitextview/1618619-textcontainerinset) to add some space for the button

**Comment by kientux** [comment]
Thanks @martinpucik, I tried to add it into input textview but there're some issues:
- I update frame of emoji button inside delegate call `inputBar(_:didChangeIntrinsicContentTo:)`, but it seems that it has some delay until the frame of `inputTextView` is updated.
- Also if I add emoji button into textView, when text content is long enough, the textView will be scrollable and emoji button get scrolled too (it supposed to be in a fixed position).

I think about using `messageInputBar.setMiddleContentView(_:animated:)` to set my own instance of `InputTextView`, but maybe it will heavily affect the messageInputBar behavior, and I have to implement many custom logic myself.

**Comment by martinpucik** [comment]
@kientux you could add the button to the `inputTextView.superView` which is the private [middleContentWrapperView](https://github.com/nathantannar4/InputBarAccessoryView/blob/8e8a943db5aab5bdc66cd49ee1b44cd6b4b38eac/Sources/InputBarAccessoryView.swift#L139)

**Comment by fukemy** [comment]
work as expected thanks

**Comment by nathantannar4** [comment]
Checkout the Facebook input bar example I had made. This can be achieved without using the private wrapper view.
