### ISSUE TITLE
 Multiple custom cell 

### ISSUE THREAD

**Issue by delmarz** [MessageKit/MessageKit#1454]
I checked all the example project however it seems only single custom cell are supported. What I am going to achieve is to create 1 custom cell to display the 'download file'  and 1 custom cell to display the title same on the example 'Someone left the conversation'

<img width="214" alt="Screen Shot 2020-09-05 at 3 51 55 PM" src="https://user-images.githubusercontent.com/7381514/92298783-bb4d7980-ef8f-11ea-87b9-ca34882c418e.png">

- What version of MessageKit are you using? 3.3.0
- What version of iOS are you running on?  >iOS12
- What version of Swift are you running on? 5.2.x
- What device(s) are you testing on? Are these simulators? Physical Device

It would be appreciated if you can add sample project. Thanks

**Comment by martinpucik** [comment]
Hey @delmarz you can register any number of custom cells 

https://github.com/MessageKit/MessageKit/blob/ae53cdd1f3b01925f8a787be06893c558bfcfb4a/Example/Sources/View%20Controllers/AdvancedExampleViewController.swift#L37

and the just dequeue and return them in this method
```swift
func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell
```
as we're doing in the Example project

https://github.com/MessageKit/MessageKit/blob/ae53cdd1f3b01925f8a787be06893c558bfcfb4a/Example/Sources/View%20Controllers/AdvancedExampleViewController.swift#L250

**Comment by delmarz** [comment]
Thanks! @martinpucik I got it now., The issue because if you register after the super viewdidload it will not visible the custom cell.

another question. How do we execute when tapping the custom cell? Can you provide us sample custom cells that overriding the messageContentCell? its because in order to achieve the bubble effect, background same as the default. The only added elements are to add the download icon and filename please refer to the screenshot above. thanks again.

**Comment by martinpucik** [comment]
@delmarz you can just subclass the `MessageContentCell`
https://github.com/MessageKit/MessageKit/blob/ae53cdd1f3b01925f8a787be06893c558bfcfb4a/Sources/Views/Cells/MessageContentCell.swift#L29

in your project for your custom cell. All the properties are open and can be overriden

**Comment by delmarz** [comment]
Do you have a sample project that is subclassing the messageContentCell? want to make sure what is else needs to override in order to make it work. e.g The bubble behavior should be remain same as messageContentcell.
Thank you

@martinpucik

**Comment by sagarsukode** [comment]
How to add different height sizes for multiple custom cells?

**Comment by dm-for-git** [comment]
I wanna use both the default cell of MessageKit and a custom cell, I know how to add a custom cell, and already worked but I don't know how to keep the default cell of MessageKit?
