### ISSUE TITLE
Why is "MessageKit Custom Cell Guide" guiding to subclass MessageFlowLayout?

### ISSUE THREAD

**Issue by zilppuri** [MessageKit/MessageKit#1458]
I was going through the guide:
https://github.com/MessageKit/MessageKit/blob/master/Documentation/CUSTOM_CELLS.md#how-can-i-add-a-custom-cell

This lists as one of the steps necessary to **subclass MessageFlowLayout** to provide a cell size calculator.

However the default MessageFlowLayout implementations already calls MessagesLayoutDelegate for sizeCalculator on custom cells:
```
open func cellSizeCalculatorForItem(at indexPath: IndexPath) -> CellSizeCalculator {
...
      case .custom:
            return messagesLayoutDelegate.customCellSizeCalculator(for: message, at: indexPath, in: messagesCollectionView)
        }
```
Also MessagesLayoutDelegate allows you to provide a custom UICollectionViewCell.
`func customCell(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> UICollectionViewCell`

Both of these methods are called by default without re-creating MessagesCollectionView with a custom MessagesCollectionViewFlowLayout in viewDidLoad. At least for me this brough on different issues - and at least this will make the CollectionView be created twice during viewDidLoad (first during superclass).

I wonder why the guide does not refer to MessagesLayoutDelegate. Ping @Kaspik ? 🙂

**Comment by zilppuri** [comment]
Also the section 2. is wrong: "2. MessageSizeCalculator: We set the size of our cell by creating a class that inherits from MessageSizeCalculator CustomMessageSizeCalculator.swift"
```
open class CustomMessageSizeCalculator: MessageSizeCalculator {
    open override func messageContainerSize(for message: MessageType) -> CGSize {
    // Customize this function implementation to size your content appropriately. This example simply returns a constant size
    // Refer to the default MessageKit cell implementations, and the Example App to see how to size a custom cell dynamically
        return CGSize(width: 300, height: 130)
    }
}
```

If you are subclassing **UICollectionViewCell** you should **not** override **messageContainerSize** but instead `open func cellContentHeight(for message: MessageType, at indexPath: IndexPath) -> CGFloat`. The messageContainerSize method return value will be modified to add default header, footer etc from the normal MessageKit layout. If you are creating a complete custom cell implementation (as inheriting UICollectionViewCell would indicate), you won't have these layouts.

**Comment by martinpucik** [comment]
Hi @zilppuri thank you for raising this issue. If you want to contribute this fix, this would be very much welcome!
