### ISSUE TITLE
Convert s.resource to use s.resource_bundles in pod spec file

### ISSUE THREAD

**Issue by wzio** [MessageKit/MessageKit#1459]
**Describe the bug**
` s.ios.resources = ['Sources/Assets.xcassets']` triggers CocoaPods/CocoaPods#8431 which can cause apps to pull in excessive amounts of resources.

**Expected behavior**
should use  `resource_bundles` in pod spec file

**Comment by ajradik** [comment]
I was also experiencing a similar issue... two Assets.car files stopped the project from building.. solved it by downgrading to version 3.1.0
