### ISSUE TITLE
topStackView's height not becoming 0 after using Attachment Manager

### ISSUE THREAD

**Issue by mmdock** [MessageKit/MessageKit#1461]
**Describe the bug**
I am sending a image and loading the image into the attachment manager before sending.  After it is sent, the InputBarAccessoryView is still quite a bit taller.

**To Reproduce**
Steps/code to reproduce the behavior:

DemoCode: 
For complete demo, see patch file here:
[file.txt](https://github.com/MessageKit/MessageKit/files/5222449/file.txt) (This is actually a git `.patch` but github doesn't support adding a .patch file.  So rename to file.patch and apply to MessageKit/master.  I wrote this patch off of commit `ae53cdd` if that also helps)

General overview:
Manage attachment manager as such:
```
    func attachmentManager(_ manager: AttachmentManager, shouldBecomeVisible: Bool) {
        setAttachmentManager(active: shouldBecomeVisible)
    }

    func setAttachmentManager(active: Bool) {
        
        let topStackView = messageInputBar.topStackView
        if active && !topStackView.arrangedSubviews.contains(attachmentManager.attachmentView) {
            topStackView.insertArrangedSubview(attachmentManager.attachmentView, at: topStackView.arrangedSubviews.count)
            topStackView.layoutIfNeeded()
        } else if !active && topStackView.arrangedSubviews.contains(attachmentManager.attachmentView) {
            topStackView.removeArrangedSubview(attachmentManager.attachmentView)
            topStackView.layoutIfNeeded()
        }
    }
```

Make button and apply to left stack view:

```
        messageInputBar.setLeftStackViewWidthConstant(to: 42, animated: false)
        let addPictureButton = makeButton(named: "ic_camera") {
            self.attachmentManager(self.attachmentManager, didSelectAddAttachmentAt: self.attachmentManager.attachments.count)
        }
        let leftItems = [addPictureButton, .flexibleSpace]
        messageInputBar.setStackViewItems(leftItems, forStack: .left, animated: false)

       private func makeButton(named: String, completion: (()->Void)? = nil) -> InputBarButtonItem {
        return InputBarButtonItem()
            .configure {
                $0.spacing = .fixed(10)
                $0.image = UIImage(named: named)?.withRenderingMode(.alwaysTemplate)
                $0.setSize(CGSize(width: 42, height: 42), animated: false)
                $0.tintColor = UIColor(white: 0.8, alpha: 1)
            }.onSelected {
                $0.tintColor = .primaryColor
            }.onDeselected {
                $0.tintColor = UIColor(white: 0.8, alpha: 1)
            }.onTouchUpInside { _ in
                print("Item Tapped")
                if let complete = completion {
                    complete()
                }
        }
    }
 
```

**Expected behavior**
I expect the InputBarAccessoryView topStackView to return to a height of 0 after sending image and removing attachmentManager's attachmentView.

Note: This issue only seems to occur if the left stack items are **too tall**.  If I change:
`$0.setSize(CGSize(width: 42, height: 42), animated: false)` to `$0.setSize(CGSize(width: 38, height: 38), animated: false)` it works as expected.  It fails to behave correctly for any values >= 39 for the size.

**Screenshots**
![Simulator Screen Shot - iPhone 8 - 2020-09-14 at 21 13 37](https://user-images.githubusercontent.com/2423465/93165558-3b32bc80-f6d1-11ea-81c2-9d293f278fc7.png)
<img width="398" alt="Screen Shot 2020-09-14 at 9 13 28 PM" src="https://user-images.githubusercontent.com/2423465/93165567-3ec64380-f6d1-11ea-9bab-fad7757c0ab1.png">

_**With the second screenshot, it is hard to tell, but the topStackView ends right below the typing indicator**_

**Environment**
- What version of MessageKit are you using?
   3.1.0 and 3.3.0
- What version of iOS are you running on? 
 I have re-created this issue on iOS 10-14
- What version of Swift are you running on?
Latest Xcode 11 or Xcode 12 versions (I alternate)
- What device(s) are you testing on? Are these simulators?
- Tested on simulators primarily, and one iOS 14 device
- Is the issue you're experiencing reproducible in the example app?
yes, after apply my patch linked above.

**Additional context**
Note: if you use Xcode 12, you will need to update PINRemoteImage to 3.0.1 which I did not include in the patch in order to streamline to prevent the PINRemoteImage Xcode 12 compilation issue.  As such, someone should update to the example  to use that asap (it's in their master branch but they haven't yet updated Cocoapods.)

**Comment by martinpucik** [comment]
Hey @mmdock thank you for raising this issue. 
In my project after sending a message all I'm calling is `invalidatePlugins()` and `invalidateIntrinsicContentSize()` on `messageInputBar: InputBarAccessoryView`. Could you try to call this to fix your issue? Attachments container sizing is working properly for me with these methods

**Comment by mmdock** [comment]
@martinpucik will give it a look today.  I know I am calling invalidatePlugins already, but not sure about InvalidateIntrinsicContentSize().

**Comment by mmdock** [comment]
@martinpucik  forgot to mention, adding `invalidateIntrinsicContentSize()` to the end of my `setAttachmentManager(active:)` function was what was missing.  thanks for the help!

**Comment by aidosk21** [comment]
thank you! calling `invalidateIntrinsicContentSize()` also helped for me!
