### ISSUE TITLE
SPM Support

### ISSUE THREAD

**Issue by dissesmac** [MessageKit/MessageKit#1466]
Why in Cocoapods we can Use in ios 10 but in SPM from ios 11?

**Comment by Kaspik** [comment]
SPM is fully supported only with XCode 12 and Swift 5.3

XCode 12 recommends iOS 12 (and drops iOS 11 automatically) thus we decided to support iOS 12+. Developers don't really have a reason to support iOS 11 itself as 100% devices can update from iOS 11 to iOS 12 and there wasn't any device dropped. :)
