### ISSUE TITLE
messageForItem(at:in:) / cellSizeCalculatorForItem crash when inserting message from websocket

### ISSUE THREAD

**Issue by mmdock** [MessageKit/MessageKit#1470]
**Describe the bug**
Crashing when trying to get a message using `messageForItem(at:in:)`

**To Reproduce**
This code appears to be crashing. Not sure about repro steps, but here is the code snippets:

```
    func numberOfSections(in messagesCollectionView: MessagesCollectionView) -> Int {
        return messageList.count
    }
    
    func messageForItem(at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> MessageType {
        return messageList[indexPath.section]
    }
```

and here is the crash log:
Crashed: com.apple.main-thread
0  libswiftCore.dylib             0x1c4144648 closure #1 in closure #1 in closure #1 in _assertionFailure(_:_:file:line:flags:) + 456
1  libswiftCore.dylib             0x1c4143ac0 _assertionFailure(_:_:file:line:flags:) + 472
2  libswiftCore.dylib             0x1c41209e4 _ArrayBuffer._checkInoutAndNativeTypeCheckedBounds(_:wasNativeTypeChecked:) + 212
3  libswiftCore.dylib             0x1c4124acc Array.subscript.getter + 88
4  MyApp                            0x10090d204 BasicChatViewController.messageForItem(at:in:) + 213 (BasicChatViewController.swift:213)
5  MyApp                            0x100911364 protocol witness for MessagesDataSource.messageForItem(at:in:) in conformance BasicChatViewController + 4304884580 (<compiler-generated>:4304884580)
6  MessageKit                     0x101de03e4 MessagesCollectionViewFlowLayout.cellSizeCalculatorForItem(at:) + 184 (MessagesCollectionViewFlowLayout.swift:184)
7  MessageKit                     0x101ddee44 MessagesCollectionViewFlowLayout.layoutAttributesForElements(in:) + 123 (MessagesCollectionViewFlowLayout.swift:123)
8  MessageKit                     0x101ddf214 @objc MessagesCollectionViewFlowLayout.layoutAttributesForElements(in:) + 4326748692 (<compiler-generated>:4326748692)
9  UIKitCore                      0x1ba2af2b4 __45-[UICollectionViewData validateLayoutInRect:]_block_invoke + 224
10 UIKitCore                      0x1ba2aedc4 -[UICollectionViewData validateLayoutInRect:] + 1872
11 UIKitCore                      0x1ba2b1e90 -[UICollectionViewData layoutAttributesForCellsInRect:validateLayout:] + 160
12 UIKitCore                      0x1ba2773d0 -[UICollectionView _computePrefetchCandidatesForVisibleBounds:futureVisibleBounds:prefetchVector:notifyDelegateIfNeeded:] + 104
13 UIKitCore                      0x1ba27732c -[UICollectionView _computePrefetchCandidatesForVelocity:notifyDelegateIfNeeded:] + 176
14 UIKitCore                      0x1ba27ecec -[UICollectionView layoutSubviews] + 1040
15 UIKitCore                      0x1baf3f2bc -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2160
16 QuartzCore                     0x1bd590978 -[CALayer layoutSublayers] + 292
17 QuartzCore                     0x1bd590db8 CA::Layer::layout_if_needed(CA::Transaction*) + 472
18 UIKitCore                      0x1baf2ac8c -[UIView(Hierarchy) layoutBelowIfNeeded] + 556
19 UIKitCore                      0x1ba295f98 -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:animator:] + 284
20 UIKitCore                      0x1ba295e58 -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:] + 100
21 UIKitCore                      0x1ba295dd4 -[UICollectionView _performBatchUpdates:completion:invalidationContext:] + 88
22 UIKitCore                      0x1ba295d00 -[UICollectionView performBatchUpdates:completion:] + 68
23 MessageKit                     0x101dee9cc MessagesViewController.setTypingIndicatorViewHidden(_:animated:whilePerforming:completion:) + 264 (MessagesViewController.swift:264)
24 MyApp                            0x10090d338 BasicChatViewController.setTypingIndicatorViewHidden(_:performUpdates:) + 217 (BasicChatViewController.swift:217)
25 MyApp                            0x100918440 BasicChatViewController.removeTypingIndicator() + 471 (BasicChatViewController.swift:471)
26 MyApp                            0x100918518 @objc BasicChatViewController.removeTypingIndicator() + 4304913688 (<compiler-generated>:4304913688)
27 MyApp                            0x1009174ec BasicChatViewController.webSocketDidReceive(text:) + 449 (BasicChatViewController.swift:449)
28 MyApp                            0x100918554 protocol witness for WebSocketManagerDelegate.webSocketDidReceive(text:) in conformance BasicChatViewController + 4304913748 (<compiler-generated>:4304913748)
29 MyApp                            0x1003f396c WebsocketManager.didReceive(event:client:) + 81 (WebsocketManager.swift:81)
30 MyApp                            0x1003f8014 protocol witness for WebSocketDelegate.didReceive(event:client:) in conformance WebsocketManager + 4299538452 (<compiler-generated>:4299538452)
31 Starscream                     0x102262c2c closure #1 in WebSocket.didReceive(event:) + 174 (WebSocket.swift:174)
32 Starscream                     0x102253b20 thunk for @escaping @callee_guaranteed () -> () + 4331338528 (<compiler-generated>:4331338528)
33 libdispatch.dylib              0x1b65e6134 _dispatch_call_block_and_release + 32
34 libdispatch.dylib              0x1b65e75ac _dispatch_client_callout + 20
35 libdispatch.dylib              0x1b65f37d4 _dispatch_main_queue_callback_4CF + 832
36 CoreFoundation                 0x1b68c08d4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
37 CoreFoundation                 0x1b68bb58c __CFRunLoopRun + 1692
38 CoreFoundation                 0x1b68babc8 CFRunLoopRunSpecific + 480
39 GraphicsServices               0x1c0c9c5cc GSEventRunModal + 164
40 UIKitCore                      0x1baa6d744 UIApplicationMain + 1936
41 MyApp                            0x1001e7798 main + 11 (main.swift:11)
42 libdyld.dylib                  0x1b6737384 start + 4

and here is the websocket code that appears to be a related based on the above stack trace::

```
    func webSocketDidReceive(text: String) {
        guard let message:Message = JSONSerializer.parse(text) else { return }
        
        guard message.type != .typing else {
            if !isFromCurrentSender(message: message){
                self.setTypingIndicatorViewHidden(false)
            }
            return
        }
        
        if isFromCurrentSender(message: message){
            // user has sent their message
            guard let messageTag = message.tag else { return }
            guard let messageIndex = self.messageList.indexDistance(where: {$0.tag == messageTag}) else { return }
            
            message.visualStatus = .sent
            self.messageList[messageIndex] = message
            self.messagesCollectionView.reloadSections([messageIndex])
        }else { //otherUser has sent a message
            self.insertMessage(message)
            self.setTypingIndicatorViewHidden(true)
        }
    }

    func insertMessage(_ message: Message) {
        messageList.append(message)
        reloadBottom()
    }
    
    func reloadBottom(){
        messagesCollectionView.performBatchUpdates({
            messagesCollectionView.insertSections([messageList.count - 1])
            if messageList.count >= 2 {
                messagesCollectionView.reloadSections([messageList.count - 2])
            }
        }, completion: { [weak self] _ in
            if self?.isLastSectionVisible() == true {
                self?.messagesCollectionView.scrollToBottom(animated: true)
            }
        })
    }
```

**Expected behavior**

Not to occasionally crash when receiving messages via the websocket.

my guess is there is a problem with:

```
        }else { //otherUser has sent a message
            self.insertMessage(message)
            self.setTypingIndicatorViewHidden(true)
        }
```

Should I be hiding the typing indicator first, before appending a message and loading the bottom? I intended to swap that with my next release but was curious if anyone sees any other suspect behavior in my code snippets.

**Environment**
- What version of MessageKit are you using? 3.3.0
- What version of iOS are you running on?
<img width="415" alt="Screen Shot 2020-09-23 at 10 43 13 AM" src="https://user-images.githubusercontent.com/2423465/94049257-9a579780-fd89-11ea-82ac-9a0c9335e4d6.png">

- What version of Swift are you running on? Swift 5.3 / Xcode Version 12.0 (12A7209)
- What device(s) are you testing on? Are these simulators? These are actual users receiving this crash
- Is the issue you're experiencing reproducible in the example app? I am not sure.

**Comment by fukemy** [comment]
hi, did u solved this, i think i have same issues with 
![Screen Shot 2021-11-11 at 11 37 44](https://user-images.githubusercontent.com/8202437/141238024-7782784a-e9de-44ef-9018-b197a17e58c0.png)
u
