### ISSUE TITLE
Xcode throws a warning when adding the library through SPM

### ISSUE THREAD

**Issue by quanvo87** [MessageKit/MessageKit#1471]
**Describe the bug**
`found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target`

`/Users/xxx/Library/Developer/Xcode/DerivedData/xxx/SourcePackages/checkouts/InputBarAccessoryView/Sources/Supporting Files/Info.plist`

**To Reproduce**
Create a new project and add MessageKit through SPM.

**Expected behavior**
No warning.

**Environment**
- What version of MessageKit are you using? 3.4.1
- What version of iOS are you running on? 14

**Comment by Kaspik** [comment]
Hey, thanks for reporting! That's a known issue and will be fixed next week in upcoming release. :)

**Comment by Kaspik** [comment]
Fixed!
