### ISSUE TITLE
[Example] Subview Example - messageInputBar not following keyboard when dragging down

### ISSUE THREAD

**Issue by michalPietraszko** [MessageKit/MessageKit#1474]
**Describe the bug**
When dragging keyboard down to dismiss messageInputBar is staying fixed until keyboardWillChangeFrame notification is sent

**To Reproduce**
as above - Example -> Subview Example -> drag keyboard down

**Expected behavior**
View follows keyboard

**Screenshots**
![IMG_2337](https://user-images.githubusercontent.com/40294686/94686495-3144c680-032b-11eb-8f18-1f9cfbee4c0a.PNG)

**Environment**
- What version of MessageKit are you using? 3.4.1
- What version of iOS are you running on? 14.0
- What version of Swift are you running on? 5
- What device(s) are you testing on? Are these simulators? 11 Pro Max
- Is the issue you're experiencing reproducible in the example app? Yes

**Comment by michalPietraszko** [comment]
Message for PPL googling in the future:

Example project for InputBarAccessoryView also has "Subview" examples

I had to modify it slightly and it's working like a charm: 

**KeyboardManager.swift** 

        callbacks[.willChangeFrame] = { [weak self] (notification) in
            let keyboardHeight = notification.endFrame.height
            guard
                self?.isKeyboardHidden == false,
                notification.isForCurrentApp else { return }
 
            if keyboardHeight == 69 { return } // add this line
            
            UIView.performWithoutAnimation { // change whatever was in this line to this 
                self?.constraints?.bottom?.constant = -keyboardHeight
                self?.inputAccessoryView?.superview?.layoutIfNeeded()
            }
        }

Fix is **only** for InputBarAccessoryView Example project - it has to be ported to MessageKit I might submit a pull request once I do that. Anyways should be pretty straight forward.

**Comment by IrelDev** [comment]
MessageKit subview example is not correct, because there is a one missing line.
if you want to interactively dismiss the keyboard, you need to bind the keyboard manager to the message collection view, as shown below. 
```swift
import Foundation
import UIKit
import InputBarAccessoryView

final class MessageSubviewViewController: BasicExampleViewController {
    
    private let keyboardManager = KeyboardManager()
    private let subviewInputBar = InputBarAccessoryView()
    
    // MARK: - View Life Cycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        view.addSubview(subviewInputBar)
        
        // Binding the inputBar will set the needed callback actions to position the inputBar on top of the keyboard
        keyboardManager.bind(inputAccessoryView: subviewInputBar)
        
        // Binding to the messagesCollectionView will enable interactive dismissal
        keyboardManager.bind(to: messagesCollectionView)
    }
    override func inputBar(_ inputBar: InputBarAccessoryView, didPressSendButtonWith text: String) {
        processInputBar(subviewInputBar)
    }
}

```
