### ISSUE TITLE
Carthage - Task failed with exit code 65

### ISSUE THREAD

**Issue by abdelmajidrajad** [MessageKit/MessageKit#1477]
The framework failed to build with Carthage .  

I got this message after trying to build it . 
Task failed with exit code 65:

**/usr/bin/xcrun xcodebuild -project /Users/mac/Desktop/Mine-Projects/PoyoLive/PoyoLive/Carthage/Checkouts/MessageKit/MessageKit.xcodeproj -scheme MessageKit -configuration Release -derivedDataPath /Users/mac/Library/Caches/org.carthage.CarthageKit/DerivedData/11.7_11E801a/MessageKit/3.3.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/ng/ss5_fw4j1_99yfzl4sgs_by80000gn/T/MessageKit SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/mac/Desktop/Mine-Projects/PoyoLive/PoyoLive/Carthage/Checkouts/MessageKit)**

**Environment**
- 3.3.0 Message Kit version 
- iOS 11.0
- Swift 5.2
- Xcode 11.7

**Comment by Kaspik** [comment]
Have you tried removing derived data and re-running everything from scratch? That doesn't look like MessageKit issue.

**Comment by abdelmajidrajad** [comment]
<img width="641" alt="Screenshot 2020-10-02 at 12 34 48" src="https://user-images.githubusercontent.com/12987448/94919068-b35bf900-04ab-11eb-9134-7fa29d980f79.png">
Yes I did, unfortunately It didn't passed.

**Comment by kgpmurray** [comment]
@abdelmajidrajad Did you find a fix for this in the end?
