### ISSUE TITLE
How to set the height of TextMessageCells

### ISSUE THREAD

**Issue by mvjpalsson** [MessageKit/MessageKit#1480]
Hi!

I am trying to build an IRC type chat interface where all messages are left aligned, and there are no bubbles around the messages. I want to space consecutive messages closer together than what the default is. 

However, no matter what layout variables and delegate methods I implement, it seems that the ```TextMessageCells``` still have some minimum height to them. Attaching screenshot here for reference: 

![Screen Shot 2020-10-08 at 10 27 09 AM](https://user-images.githubusercontent.com/10208451/95493724-b7779300-0951-11eb-96de-f3cfeed5d0a3.png)

Basically, what I would like to do, is remove the distance between the ```MessageLabel``` and the ```TextMessageCell``` it is contained in. In other words, I want the ```TextMessageCells``` to be the same height as the ```MessageLabel``` that they contain.

So far, I've tried implementing custom layouts, custom cell size calculators, overriding the ```sizeForItemAt```, all with no luck. I've sifted through the library code, and inspected the constraints in the View Hierachy, but am not able to figure out what exactly is behind this extra spacing, and at any rate I'd like to try to change it without having to mess with MessageKit internals.

What is the preferred/easiest way of doing this?

**Comment by hamzaozturk** [comment]
Set section inset to zero.

```
    override func configureMessageCollectionView() {
        super.configureMessageCollectionView()
        
        let layout = messagesCollectionView.collectionViewLayout as? MessagesCollectionViewFlowLayout
        layout?.sectionInset = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0)
    }
```

![Simulator Screen Shot - iPhone 11 - 2020-10-10 at 20 58 19](https://user-images.githubusercontent.com/6054248/95661855-5ad7cc00-0b3b-11eb-894f-b323147a2907.png)

**Comment by mvjpalsson** [comment]
@hamzaozturk Thank you, but I don't think that is what is going on here. The section inset is already set to 0 all around, but there is empty space _within_ each section. See the picture below. 

<img width="879" alt="Screen Shot 2020-10-10 at 3 43 34 PM" src="https://user-images.githubusercontent.com/10208451/95666530-61504e80-0b0f-11eb-9505-593ae9f4db65.png">

The sections are all right next to each other with no space in between, but for some reason there is an empty space between the bottom of each ```MessageContainerView``` and the section containing it. In the top section, with the ```AvatarView``` and ```messageTopLabel```, the section boundaries hug the content perfectly, but in the other ones there is this empty space. Inspecting the constraints doesn't yield any information because it's not using ```AutoLayout```, I believe.

**Comment by hamzaozturk** [comment]
Can you create a demo and share the code? it is hard to find without knowing what you have customized.

**Comment by hamzaozturk** [comment]
I think i have figured it out. You set avatar view hidden on the bottom cells. However,  since the avatar view height is greater than the message content, it creates a space.

**Comment by mvjpalsson** [comment]
Thank you @hamzaozturk, that was indeed the case! :) To fix it, I subclassed TextMessageSizeCalculator and overrode ```cellContentHeight``` to check if previous sender is the same, and if so modify the height calculations as necessary. 

Closing this issue now.
