### ISSUE TITLE
self.messagesCollectionView.scrollToBottom() not working on iOS 14

### ISSUE THREAD

**Issue by zaaaszaaas** [MessageKit/MessageKit#1481]
scrollToBottom works on iOS 14/14.1 not at all (works on iOS 13.5)

- after input and send a text an extra empty space is added between keyboard and the inputted text (seems that the extra space has the same height as the keyboard height)
- the bug is reproducible: **MessageKit Example-App -> SwiftUI-View**

----------------------------------------------
----------------------------------------------

- What version of MessageKit are you using?

3.4.1

- What version of Swift are you running on?

target iOS 13 - Swift5
target iOS 14 - Swift5

- What device(s) are you testing on? Are these simulators?

Problem occur on iPhone11Pro and on Simulator

- Is the issue you're experiencing reproducible in the example app?

the bug is reproducible: **MessageKit Example-App -> SwiftUI-View**

- Video that shows the behavior of the bug:

[Message-Kit Example App (SwiftUI-View)](https://youtu.be/RFqWbfdIMaY)

**Comment by Kaspik** [comment]
Will check this, in the meantime you could try `scrollToLastItem()` :)

@martinpucik Have you checked if it works on our project still?

**Comment by zaaaszaaas** [comment]
i just tried scrollToLastItem()

unfortunately scrollToLastItem() behaves in iOS14 like scrollToBottom(). The inputed text is hidden behind the inputArea :/

scrollToLastItem() works on iOS 13.5

**Comment by zaaaszaaas** [comment]
scrollToLastItem() was embedded in this function....

if self?.isLastSectionVisible() == true {
}

After commenting these lines out scrollToLastItem() is working but still add additional space between keyboard and inputed text. The additional space has approximately the height of the keyboard. same problem occurs with "scrollToBottom()"

any idea @Kaspik @martinpucik ?

**Comment by zaaaszaaas** [comment]
@Kaspik @martinpucik 

you can also reproduce the bug on iOS 14 in the "Example-App" -> "SwiftUI Example" (after input some text and send it)

it is strange that the problem occurs in the Example-App only with the SwiftUI Example. On my Project the Controller is not imbedded with SwiftUI

**Comment by fukemy** [comment]
solved it using below code:
```

        scrollsToBottomOnKeyboardBeginsEditing = true
        scrollsToLastItemOnKeyboardBeginsEditing = true
        maintainPositionOnKeyboardFrameChanged = true
```

**Comment by zaaaszaaas** [comment]
> solved it using below code:
> 
> ```
> 
>         scrollsToBottomOnKeyboardBeginsEditing = true
>         scrollsToLastItemOnKeyboardBeginsEditing = true
>         maintainPositionOnKeyboardFrameChanged = true
> ```

this solves not the problem. 

in MessageKIT Example App these lines already present:

```
        messagesVC.scrollsToBottomOnKeyboardBeginsEditing = true // default false
        messagesVC.maintainPositionOnKeyboardFrameChanged = true // default false
```

i replaced them with:

```
        messagesVC.scrollsToBottomOnKeyboardBeginsEditing = true // default false
        messagesVC.scrollsToLastItemOnKeyboardBeginsEditing = true // default false
        messagesVC.maintainPositionOnKeyboardFrameChanged = true // default false
```

the problem still occur. I made a video. take a look:

https://youtu.be/RFqWbfdIMaY

any change that this bug will resolved soon?

**Comment by zaaaszaaas** [comment]
> solved it using below code:
> 
> ```
> 
>         scrollsToBottomOnKeyboardBeginsEditing = true
>         scrollsToLastItemOnKeyboardBeginsEditing = true
>         maintainPositionOnKeyboardFrameChanged = true
> ```

i tried this. unfortunately this fix solves not the problem. In the MessageKit-Example App (Sources->Views->SwiftUI->MessagesView.swift) these two lines already exits:

```
messagesVC.scrollsToBottomOnKeyboardBeginsEditing = true // default false
messagesVC.maintainPositionOnKeyboardFrameChanged = true // default false
```
i replaces them with these lines:

```
messagesVC.scrollsToBottomOnKeyboardBeginsEditing = true // default false
messagesVC.scrollsToLastItemOnKeyboardBeginsEditing = true // default false
messagesVC.maintainPositionOnKeyboardFrameChanged = true // default false
```


The Example-App is still showing this strange scrolling on iOS14. Check this Video:
[Message-Kit Example App (SwiftUI-View)](https://youtu.be/RFqWbfdIMaY)

**Comment by fukemy** [comment]
lets try to comment load more message function, then test by type into textview then press send programmatically bro

**Comment by zaaaszaaas** [comment]
> 
> 
> lets try to comment load more message function, then test by type into textview then press send programmatically bro

i am not sure if i understood you right. 

what should be archived by commenting the "load more message" function? "load more message" should work with MessageKit anyway. After all the Example-App (Sources->Views->SwiftUI->MessagesView.swift) contains no "loadMoreMessages" function.

The MessageKit Example-App is still showing this strange scrolling on iOS14. Check this Video:

[Message-Kit Example App (SwiftUI-View)](https://youtu.be/RFqWbfdIMaY)

This problem also exists on iOS14.1 and it also occur if MessageKit is implemented directly (without SwiftUI) and the navigation starts from a SwiftUI-View

**Comment by zaaaszaaas** [comment]
problem is still present. i hope this bug will be confirmed soon.

**Comment by martinpucik** [comment]
@zaaaszaaas could you please check the Example app again on master? I can't repro this issue anymore

**Comment by AlbertoPvt** [comment]
`self.messagesCollectionView.scrollToItem(at: IndexPath(row: 0, section: self.messages.count - 1), at: .top, animated: false)` should work properly.

**Comment by zaaaszaaas** [comment]
@martinpucik 

i just tried. with the new update "sending a message" is not working in the  "MessageKit Example-App -> **SwiftUI-View**". tested on iOS 14.2

What happens: after clicking on "send" the inputed text disappears (as it should) and **no** new message is inserted

Did you tried sending a message in the "MessageKit Example App -> SwiftUI-View"?

**Comment by zaaaszaaas** [comment]
> @zaaaszaaas could you please check the Example app again on master? I can't repro this issue anymore

@martinpucik

i just tried. with the new update "sending a message" is not working in the "MessageKit Example-App -> SwiftUI-View". tested on iOS 14.2

What happens: after clicking on "send" the inputed text disappears (as it should) and no new message is inserted

Did you tried sending a message in the "MessageKit Example App -> SwiftUI-View"?

**Comment by Kaspik** [comment]
So the problem this issue is about is fixed. Problem with SwiftUI persists, but that's different.

We don't fully support SwiftUI, it's still experimental. I'll close this issue as it's fixed then. :)

**Comment by zaaaszaaas** [comment]
hi @Kaspik 

The MessageKit-Example-App contains a SwiftUI Implementation that does not work anymore. a chat view that scrolls not to the right place is not just a little bug, its a big one.

To say the problem has been resolved under this circumstance, I do not consider it logical.

SwiftUI is now in version 2.0. i don't think you can call it anymore experimental. 

I hope the problem will be fixed soon. however if there will be no fix in the future the Swift-UI Implementation from the Example-App should be removed.

**Comment by mrformidable** [comment]
I was able to fix the problem by using the `keyboardDidShowNotification` and setting `messagesCollectionView.contentInset.bottom = 0`

`      NotificationCenter.default.addObserver(self, selector: #selector(handleKeyboardDidShow(_:)), name: UIResponder.keyboardDidShowNotification, object: nil)
`

`@objc func handleKeyboardDidShow(_ notification: Notification) {
    messagesCollectionView.contentInset.bottom = 0
  }`
