### ISSUE TITLE
get instance of label bottom

### ISSUE THREAD

**Issue by fukemy** [MessageKit/MessageKit#1484]
hello, i want to show seen user like facebook, skype,.. so i tend to add image into cellBottomAttributeText using NSTextAttachment, but image not show after loaded, so can u help how to get label bottom instance, i will add imageView into this label? Thanks

**Comment by hamzaozturk** [comment]
You can try adding image as text attachment using the code below:

```
    override func messageBottomLabelAttributedText(for message: MessageType, at indexPath: IndexPath) -> NSAttributedString? {
        
        if isFromCurrentSender(message: message) {
            let imageAttachment = NSTextAttachment()
            imageAttachment.image = #imageLiteral(resourceName: "message_delivered")
            imageAttachment.bounds = CGRect(x: 0, y: 0, width: 16, height: 10)

            let imageString = NSAttributedString(attachment: imageAttachment)
            let string = NSAttributedString(string: "Delivered ", attributes: [NSAttributedString.Key.font: UIFont.boldSystemFont(ofSize: 10), NSAttributedString.Key.foregroundColor: UIColor.darkGray])

            let text = NSMutableAttributedString(attributedString: string)
            text.append(imageString)
            
            return text
        }
        return nil
    }
```

![Simulator Screen Shot - iPhone 11 - 2020-10-18 at 21 16 35](https://user-images.githubusercontent.com/6054248/96376389-58065800-1187-11eb-9ac4-8a4610971251.png)

**Comment by fukemy** [comment]
hi, i need to display useravatar that seen this message, so need use image url, not resource or loaded image
```
imageAttachment.image = #imageLiteral(resourceName: "message_delivered") -> need change to image url
```

so attachment image is not display after image is loaded, im stuck in this problem

**Comment by Kaspik** [comment]
Then use Kingfisher or any other library for loading remote images. :)

**Comment by hamzaozturk** [comment]
@Kaspik this is not an image view so you can not use those libraries. There should be some way to update bottom label independently. 

@fukemy Have you ever tried reloading the section after image is downloaded?

**Comment by fukemy** [comment]
@hamzaozturk i dont think reload section is good because it's will cause many leak layout problems, my solution : 
1. Download all image with downsize (50/50) and store as UIImage before display all message
2. Set to NSTextAttachment and it work

 Above solution is not good because it's make more time to loading message, but i can not find any solution that better. 
 Note : try using UIImage(data: with content url) is work, but it's make delay when scroll to cell that contain NSTextAttachment

NOTE: Even using [AsyncTextAttachment](https://github.com/Cocoanetics/Swift-Examples/blob/master/Attachments/Attachments/AsyncTextAttachment.swift), still not working

**Comment by fukemy** [comment]
<img width="378" alt="Screen Shot 2020-10-19 at 15 50 46" src="https://user-images.githubusercontent.com/8202437/96422927-dd8b1600-1222-11eb-80ea-db7710e725a6.png">
here is result.

**Comment by fukemy** [comment]
please give some advise if u think it would be better. THanks

**Comment by hamzaozturk** [comment]
You need to create your own cells using Custom Cells. You can not achieve what you want using current structure.

**Comment by fukemy** [comment]
thanks, can u help another open question?
