### ISSUE TITLE
Time while sending message

### ISSUE THREAD

**Issue by wertpoiu** [MessageKit/MessageKit#1485]
Why messagkit takes so much time while sending messages it shouldnt be quick?

**Comment by kinoroy** [comment]
Hi @wertpoiu,

MessageKit is just a UI framework, it doesn't do any 'sending'. MessageKit will display whatever messages are in your data source so if there's any delay then that would be a delay in you inserting the message into your data source and reloading the collection view. 
Whats probably happening is that you are waiting for the response from your backend to be successful before you are inserting the message object into your data source. If you want this to be instant, you should insert a temporary message object into the data source when the user hits send. You may not have all the details like the ID if thats generated on your backend but when you get the response from your backend with the correct details, you could update the temporary message or swap it out. 

Hope that helps!

**Comment by wertpoiu** [comment]
> Hi @wertpoiu,
> 
> MessageKit is just a UI framework, it doesn't do any 'sending'. MessageKit will display whatever messages are in your data source so if there's any delay then that would be a delay in you inserting the message into your data source and reloading the collection view.
> Whats probably happening is that you are waiting for the response from your backend to be successful before you are inserting the message object into your data source. If you want this to be instant, you should insert a temporary message object into the data source when the user hits send. You may not have all the details like the ID if thats generated on your backend but when you get the response from your backend with the correct details, you could update the temporary message or swap it out.
> 
> Hope that helps!



> Hi @wertpoiu,
> 
> MessageKit is just a UI framework, it doesn't do any 'sending'. MessageKit will display whatever messages are in your data source so if there's any delay then that would be a delay in you inserting the message into your data source and reloading the collection view.
> Whats probably happening is that you are waiting for the response from your backend to be successful before you are inserting the message object into your data source. If you want this to be instant, you should insert a temporary message object into the data source when the user hits send. You may not have all the details like the ID if thats generated on your backend but when you get the response from your backend with the correct details, you could update the temporary message or swap it out.
> 
> Hope that helps!

thank you for clarifying. Actually i didnt check the code properly there was sleep(1) in code

**Comment by wertpoiu** [comment]
> Hi @wertpoiu,
> 
> MessageKit is just a UI framework, it doesn't do any 'sending'. MessageKit will display whatever messages are in your data source so if there's any delay then that would be a delay in you inserting the message into your data source and reloading the collection view.
> Whats probably happening is that you are waiting for the response from your backend to be successful before you are inserting the message object into your data source. If you want this to be instant, you should insert a temporary message object into the data source when the user hits send. You may not have all the details like the ID if thats generated on your backend but when you get the response from your backend with the correct details, you could update the temporary message or swap it out.
> 
> Hope that helps!

thank you for clarifying. Actually i didnt check the code properly there was sleep(1) in code
