### ISSUE TITLE
The screen jumps if there are few messages

### ISSUE THREAD

**Issue by ed8009** [MessageKit/MessageKit#1486]
Hi, thanks for the awesome library!

I have a problem that is reproducible in the example project:
Set: `maintainPositionOnKeyboardFrameChanged = true`
If there are 1-2 messages in the chat, the screen jumps when opening/hiding the keyboard.

<img src="https://user-images.githubusercontent.com/8483801/96554638-7a9b8c80-12bf-11eb-805a-6e48623a3f80.gif" width="40%">

Has anyone had this problem? Tell me what I can do?

**Comment by yunnnyunnn** [comment]
Same here

**Comment by Kaspik** [comment]
Might be related: https://github.com/MessageKit/MessageKit/issues/1481

**Comment by martinpucik** [comment]
Hey @ed8009 thanks for reporting this. Could you try it again on master? Just merged https://github.com/MessageKit/MessageKit/pull/1505 that may fix this

**Comment by ed8009** [comment]
Hey @yunnnyunnn thanks for your attention to the problem!
No, the error remains, I reproduced it in your test project, look at the screen jumps when there are few messages in the chat


https://user-images.githubusercontent.com/8483801/103129331-64d48a00-46a9-11eb-891c-4e6f35d3c9ea.mov
