### ISSUE TITLE
Support Audio messages

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#149]
We can add an additional case to `MessageData` called `.audio(Data)` and a new subclass of `MessageCollectionViewCell` called `AudioMessageCell`. 

The sizing of the cell is pretty trivial. A big question would be what the UI would look like for this type of cell.

**Comment by cwalo** [comment]
I'd be interested in tackling this one. I would probably use something similar to the Messages audio message UX as a starting point. Waveform drawing is the hardest part, and I've got that down, so should be pretty straightforward.

**Comment by SD10** [comment]
Sounds good to me 👍 Let me know if you have any questions or change your mind

**Comment by mperovic** [comment]
@SD10 I'm currently implementing Audio Player. Current design is not the best (but this is request from my designer). I have one question (for now): where I can put AudioPlayer object which will be responsible for playing audio and updating UI (slider). My idea is to do this in the `MessagesViewController`. In general, I want to continue playing an audio message even if the cell goes out of the screen.  Is this good solution?

<img width="643" alt="screen shot 2017-09-29 at 3 11 28 pm" src="https://user-images.githubusercontent.com/182573/31017409-9f557b2e-a528-11e7-8641-52195c420744.png">

**Comment by cwalo** [comment]
@mperovic Nice! My gut says `MessagesViewController` should should contain a lazily loaded instance of the Audio Player. Looking at the Messages app, audio plays no matter where you are in the collection view, so that sounds good to me.  I'd really like to see a low-resolution waveform in there if you feel comfortable doing that. [Example here](https://github.com/cwalo/AudioArmada/blob/master/AudioArmada/Classes/WaveformZoomable.swift), but that can be reduced quite a bit in our case. Also happy to look over anything you've got.

**Comment by SD10** [comment]
I think the default UI should look something like `iMessage`. I'd also like to add as little as possible on the playing/audio side of things. I'd like it to be strictly UI with hooks to update that UI based on the status of your own player

**Comment by mperovic** [comment]
@SD10 @cwalo I have finished initial development with some changes in UI. It still doesn't look like a `iMessage`, but I hope I will implement this changes until the end of next week.

If someone want to look at my work it's available from my repo, branch `#149-Support Audio messages`

**Comment by SD10** [comment]
This seems like a good addition to the next major version. Ideally, the cell would have an iMessage style UI.

**Comment by chrisverra** [comment]
Hi @SD10 is this audio feature being picked up yet?

**Comment by SD10** [comment]
Hey @chrisverra, no it is not being worked on at the moment 👍

**Comment by cwalo** [comment]
Hey @chrisverra! @mperovic started some good stuff in a branch, but it's fallen behind the current state of the library. You might find some inspiration there. Look forward to seeing what you come up with!

**Comment by nathantannar4** [comment]
We have a great PR #892 that will add this feature! I have added it as a 2.1 milestone

**Comment by AwaisFayyaz** [comment]
Hi guys, 
Great work out there. Really love this library!

Is audio message support implemented or not at the moment ?

**Comment by nathantannar4** [comment]
@AwaisFayyaz currently in PR slated for 3.0 release

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lasernite** [comment]
@nathantannar4 Any word on the stability of the 3.0.0-beta branch? Have an app with 1k DAU using MessageKit, and would love to add audio message support :)

**Comment by nathantannar4** [comment]
3.0.0 is released!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kinoroy** [comment]
Since 3.0.0 released, I'm closing this.
