### ISSUE TITLE
How to hide keyboard when tap on messagesCollectionView on 3.4.2

### ISSUE THREAD

**Issue by ldt25290** [MessageKit/MessageKit#1491]
I add a UITapGestureRecognizer into messagesCollectionView in my custom viewcontroller which extends MessagesViewController.
I also return true in delegate method of UIGestureRecognizerDelegate.
```swift
 func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool {`
    return true
 } 
```
The above method is called but my selector method of above tap gesture is not called.
Here is my code:
<img width="828" alt="Screen Shot 2020-10-29 at 23 15 02" src="https://user-images.githubusercontent.com/4800933/97601590-ebb80e00-1a3c-11eb-8a18-7a1c24324518.png">

- Version of MessageKit: 3.4.2

**Comment by s-reshetnikov** [comment]
The same question, solutions, that you gave earlier, don't work in 3.4.2

**Comment by WineKai** [comment]
i use 3.1.0 also cannot hide keyboard when tap on

**Comment by jd014** [comment]
You can leverage the existing gesture recognizer method in `MessagesCollectionView` by creating your own custom class that inherits `MessagesCollectionView`. Add a simple delegate and you can detect any taps in messagesCollectionView without interrupting the `MessageCellDelegate` methods.
```
protocol MessagesCollectionViewDelegate: AnyObject {
    func didTap()
}

class ChatMessagesCollectionView: MessagesCollectionView {
    weak var messagesCollectionViewDelegate: MessagesCollectionViewDelegate?
    
    override func handleTapGesture(_ gesture: UIGestureRecognizer) {
        super.handleTapGesture(gesture) // Required for MessageCellDelegate methods to work
        messagesCollectionViewDelegate?.didTap()
    }
}
```

Now just implement the delegate method in your `MessagesViewController` and hide the keyboard when the delegate is triggered.

```
class ChatMessagesViewController: MessagesViewController {
    override func viewDidLoad() {
        self.messagesCollectionView = ChatMessagesCollectionView()
        (self.messagesCollectionView as? ChatMessagesCollectionView)?.messagesCollectionViewDelegate = self
        super.viewDidLoad()
    }
}

extension ChatMessagesViewController: MessagesCollectionViewDelegate {
    func didTap() {
        self.messageInputBar.inputTextView.resignFirstResponder()
    }
}
```

**Comment by le-hu-dev** [comment]
extension YourMessageVC: MessageCellDelegate {
 func didTapBackgroud(in cell: MessageCollectionViewCell) {
    self.messageInputBar.inputTextView.resignFirstResponder()
  }
}

**Comment by martinpucik** [comment]
Examples above should work 👍

**Comment by EvgeniyMac** [comment]
override func viewDidLoad() {
        super.viewDidLoad()
        self.hideKeyboardWhenTappedAround()
    }   

    func hideKeyboardWhenTappedAround() {
        let tap: UITapGestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(dismissKeyboard))
        tap.cancelsTouchesInView = false
        messagesCollectionView.addGestureRecognizer(tap)
    }
    
    @objc func dismissKeyboard() {
        view.endEditing(true)
    }
