### ISSUE TITLE
MessagesViewController frame changed when keyboard open. Leads to unwanted padding.

### ISSUE THREAD

**Issue by MadGeorge** [MessageKit/MessageKit#1494]
Hello. 
This case was tested with clean MessagesViewController subclass without any override

```swift
import MessageKit
class DemoChat: MessagesViewController {}

// some other controller
override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)
    navigationController?.pushViewController(DemoChat(), animated: true)
}
```

**Before** keyboard become active. Controller view frame is correct.

![CleanShot 2020-11-03 at 21 14 49](https://user-images.githubusercontent.com/25031713/98025120-5b057780-1e1a-11eb-9ef8-d1d154a41e56.png)

**After** keyboard become active. Why view frame changed? What is the purpose of the bottom padding? I rawly run thought the sources and did not find any  spots with root of this frame changes. 

![CleanShot 2020-11-03 at 21 15 21](https://user-images.githubusercontent.com/25031713/98025173-6a84c080-1e1a-11eb-8758-f6366ed71dc7.png)

**This is the problem**
Because it adds additional padding between input view and messages. This padding takes into account when offset for bottom messages is calculated.

I tested with regular UIVIewController with input fields and can not reproduce. View frame always remain the same no matter of the keyboard appearance. 

This spacing looks like exact match of unwonted frame change
![CleanShot 2020-11-03 at 21 26 46](https://user-images.githubusercontent.com/25031713/98025948-702ed600-1e1b-11eb-92e1-dc5146387072.png)

**Environment**
- MessageKit (3.0.0)
- iOS 13, 12, 14
- Swift 5
- simulators and device

**Comment by Kaspik** [comment]
Version 3.0.0 is pretty outdated and doesn§t have any fixes for XCode 12 and new iOS. Please try latest version.

**Comment by MadGeorge** [comment]
@Kaspik i can not update to any higher version, since my project min requirement target is iOS 11

**Comment by MadGeorge** [comment]
Ok. i temporary raised up my min build target and updated to the 3.4.2. The issue with view frame change remain the same.

**Comment by Kaspik** [comment]
Hmm, interesting, just FYI - there is no device that can't update to iOS 12 so that's why we dropped iOS 11. Every device using iOS 11 can be upgraded to iOS 12. :)

By any chance, do you use `additionalBottomInset`?

This is for example our setup of subclass of MessagesViewController:
```
messagesCollectionView.isPrefetchingEnabled = false
messagesCollectionView.delaysContentTouches = false
additionalBottomInset = 4 /// account for input bar shadow
scrollsToLastItemOnKeyboardBeginsEditing = true
```
and we are not seeing any issue.

Are you able to repro in our example project? Or upload some test project we can repro this on?

**Comment by MadGeorge** [comment]
Can be closed. It's IQKeyboardManager dependency broke the layout when collection view is presented.

**Comment by matsotaa** [comment]
Its very common issue for all who using messageKit, I guess. I read a lot about people stands in front of that.
MessageKit suggested `additionalBottomInset` in `MessagesViewController`. I use it to with `keyboardWillShowNotification`, but be careful and check it, cause somehow in some place `MessagesViewController` reads that `keyboardWillShowNotification` before it does.

Anyway, this is nice library. But they need to fix this inset... I Suppose problem somewhere with calculation where `tabBar.frame.height` involved
