### ISSUE TITLE
Showing gap in MessageInputBar when open popover form UIPopoverPresentationController 

### ISSUE THREAD

**Issue by sauravkure** [MessageKit/MessageKit#1495]
When I open popover from a button which added in  "messageInputBar.leftStackView" then popover open not in exact position. 
Please check this code and attached screenshot of the issue. Please let me know the solution of this problem if it's known to you:

let lPopOverVC : WorkFlowPopover? = UIStoryboard.loadKPPopOver()
lPopOverVC?.PopoverDelegate = self
lPopOverVC?.chatViewModal = self.viewModel
guard let popoverController lPopOverVC?.popoverPresentationController else {return}
popoverController.permittedArrowDirections = .down
popoverController.sourceView = self.view
popoverController.sourceRect = (sender as! UIButton).frame
popoverController.delegate = self
self.present(lPopOverVC lPopOverVC!, animated: true) {
        }
![Simulator Screen Shot - iPhone 11 Pro - 2020-11-06 at 21 28 02](https://user-images.githubusercontent.com/74039695/98387470-6d302180-2077-11eb-9536-f4c916db9435.png)

**Comment by sauravkure** [comment]
If possible please update me on this issue

**Comment by nathantannar4** [comment]
Because you are setting the source view and the source rect, I think the coordinate space is messed up. You should set the source view as the sender UIButton and not set the source rect.

**Comment by sauravkure** [comment]
Hi Nathan, 

I have tried your solution but still getting same issue. can you please check it again?

**Comment by sauravkure** [comment]
Hi,

Can you please check this issue and let me know the solution of this issue if this problem known to you.
