### ISSUE TITLE
Xamarin support for this library?

### ISSUE THREAD

**Issue by marchrius** [MessageKit/MessageKit#1496]
Is there a binding library or a support for create binding library for Xamarin?

**Comment by kinoroy** [comment]
Hey @marchrius,

I'm not familiar at all with Xamarin but we would welcome contributions if there's a way we could make MessageKit work better for Xamarin developers.

**Comment by marchrius** [comment]
Hi @kinoroy , thanks for answer.

The official Microsoft documentation about library binding is at https://docs.microsoft.com/en-us/xamarin/ios/platform/binding-swift/

**Comment by martinpucik** [comment]
Let's reopen this if there are more peeps who would find this useful
