### ISSUE TITLE
Timestamps don't unpin after shown on Notch Devices.

### ISSUE THREAD

**Issue by isadon** [MessageKit/MessageKit#1497]
**Describe the bug**
Timestamps pinning behavior is inconsistent on iPhone (Notch devices). Upon opening view containing MessageKit they are hidden. Upon swiping left they show and then stay visible. Letting go of the swipe gesture doesn't hide/unpin the timestamps as they were.

**Expected behavior**
Timestamps should unpin and go back to their original position prior to swiping left to see them.

**Screenshots**
Here is a screenshot showing the timestamps in the view after the swipe gesture has finished. Prior to the swipe they were hidden. 
<img width="347" alt="Screen Shot 2020-11-09 at 9 51 01 PM" src="https://user-images.githubusercontent.com/1881038/98621631-b54c7f80-22d5-11eb-84b3-5b5c902455e4.png">

**Environment**
iOS 14.1
MessageKit Development Branch commit: 
Swift 5.3
Testing on iPhone X, XS, 11, 12 (All Notch iPhone Devices, Real and Simulator)

**Comment by kinoroy** [comment]
Thanks for the bug report @donileo !

@amirpirzad Would you be able to have a look at this since you did the swipe left to show time PR?

**Comment by amirpirzad** [comment]
> Thanks for the bug report @donileo !
> 
> @amirpirzad Would you be able to have a look at this since you did the swipe left to show time PR?

Yes sure.

**Comment by Kaspik** [comment]
Fixed, will be released in next version. :)
