### ISSUE TITLE
CodeConventions? SwiftLint? Tabs vs Spaces?

### ISSUE THREAD

**Issue by fbartho** [MessageKit/MessageKit#15]
Not trying to start a holywar! Just want to make sure we don't have a lot of thrash with new contributions matching each developer's personal settings.

## Done Definition:
- [ ] tabs vs spaces is decided for this project
- [ ] tabs vs spaces is encoded in XcodeProj's Project-level settings that way it inherits on different developer's systems.
- [ ] tabs vs spaces is encoded in an editorconfig.org dot file (this makes Github correctly display diffs with tabs)
- [ ] code conventions are documented in a swift format or swiftlint, or other config file + prose description for developers.
- [ ] future tickets if additional tooling for swiftlint/format/other tools to enforce the standards is necessary!

**Comment by SD10** [comment]
@fbartho You opened this about 30 seconds before I was about to open an issue about adding Swiftlint 😁

**Comment by SD10** [comment]
The` v0.2.0` branch has SwiftLint now and a basic `.swiftliny.yml` file.
As the project progresses we will refine these rules. 
Having something like a repository style guide would be nice, but lower priority than other things 😅.
We use tabs, 1 tab == 4 spaces 😬

**Comment by MacMeDan** [comment]
Did we just open up the holy war?
