### ISSUE TITLE
imageURL of MediaMessageCell

### ISSUE THREAD

**Issue by tauypaldiyev** [MessageKit/MessageKit#1502]
Message with imageURL does not show image. What can I do to fix this? Help please

**Comment by Kaspik** [comment]
This report tells us nothing, sorry.

How are you setting, the image, what Image Library do you use, what is the code to show the image?

**Comment by tauypaldiyev** [comment]
<img width="572" alt="Screen Shot 2020-12-03 at 21 35 54" src="https://user-images.githubusercontent.com/31894257/101051351-94630b80-35af-11eb-8741-f11e51f85f0b.png">

Behaviour of cell for this piece of code, where I initialize MockMessage with imageURL is ->

<img width="291" alt="Screen Shot 2020-12-03 at 21 35 14" src="https://user-images.githubusercontent.com/31894257/101051461-bb214200-35af-11eb-87f3-02cbd673237d.png">

I couldn't find how to resolve this, and hardcoded, downloaded image, and initialized with image ->

<img width="619" alt="Screen Shot 2020-12-03 at 21 38 40" src="https://user-images.githubusercontent.com/31894257/101051635-ed32a400-35af-11eb-8da0-54b8f26d09b0.png">

Behaviour for this is -> 
<img width="291" alt="Screen Shot 2020-12-03 at 21 34 09" src="https://user-images.githubusercontent.com/31894257/101051688-f9b6fc80-35af-11eb-9c41-b3f36ade7c3a.png">

I don't like it. If there is any way to use URL, please help me to apply it

**Comment by Kaspik** [comment]
As you can see in `MediaMessageCell.swift`, `photo` media item is supported only with image (so your second case, which is the correct case). You can only implement your own media cell, that will accept the url, and will load the URL via Kingfisher right in the cell. :)
