### ISSUE TITLE
Having a scrolling problem with MessageKit on SwiftUI

### ISSUE THREAD

**Issue by crspybits** [MessageKit/MessageKit#1503]
Thanks so much for your library! I've got it in a production app (Neebla on the app store) and am updating that app with SwiftUI and running into an issue.

**Describe the bug**
When I tap in the input field, I am finding it necessary to tap a second time in the input field to get proper scrolling. Without the second tap, I can scroll the content out of view. See: 
https://www.dropbox.com/s/b599saahswohiqh/Problem%20with%20scrolling.mov?dl=0

**To Reproduce**
My code is based on the SwiftUI example posted here.
It's all online. This is the code based on MessageKit:
https://github.com/SyncServerII/Neebla/tree/main/Neebla/UI/Screens/Comments

**Expected behavior**
I expect to not be able to scroll the messages completely off the screen.

**Screenshots**
See video.

**Environment**
- What version of MessageKit are you using?
3.4.2

- What version of iOS are you running on?
14.2

- What version of Swift are you running on?
5.3

- What device(s) are you testing on? Are these simulators?
Simulators and physical iPhone.

- Is the issue you're experiencing reproducible in the example app?
I've not provided one yet. Sorry. I can do that if needed.

What I'd appreciate is some insight into which code gets triggered on this second tap into the input field. I've looked into it and can't yet find it.

**Additional context**
I'm using SPM. My UI is mostly SwiftUI.

**Comment by Kaspik** [comment]
Might be related: https://github.com/MessageKit/MessageKit/issues/1481

**Comment by martinpucik** [comment]
@crspybits could you try again with the latest master? #1506 may have fixed this

**Comment by crspybits** [comment]
I just tried master. Unfortunately, there's no change in the behavior that I'm seeing.

**Comment by crspybits** [comment]
It definitely looks related to #1481.

**Comment by crspybits** [comment]
I assume the scroll view contentSize should change when the keyboard appears. I put this into the `MessageSwiftUIVC`:
```
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWillDisappear), name: UIResponder.keyboardWillHideNotification, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(keyboardDidAppear), name: UIResponder.keyboardDidShowNotification, object: nil)
    }

    @objc func keyboardDidAppear() {
        // messagesCollectionView.scrollToLastItem(at: .top, animated: true)
        print("view.frame.size: \(view.frame.size)")
        print("messagesCollectionView.frame.size: \(messagesCollectionView.frame.size)")
        print("messagesCollectionView.contentSize: \(messagesCollectionView.contentSize)")
    }

    @objc func keyboardWillDisappear() {
    }
```

and when the keyboard appears, I get (in the Xcode console output):
```
view.frame.size: (414.0, 389.5396482530875)
messagesCollectionView.frame.size: (414.0, 389.5)
messagesCollectionView.contentSize: (414.0, 615.0)
```

**Comment by crspybits** [comment]
Playing with this some more and changing away from deprecations (in MessageKit), it looks like my problem is resolved. Going to test a little more.

**Comment by crspybits** [comment]
Hmmm. Not seeing that improved result again. Still getting content scrolling out of view.

**Comment by jminutaglio** [comment]
Also having the same scrolling out of view...  :(

**Comment by crspybits** [comment]
I see that this has a question mark, i.e., `bug?`. Anything more I can provide? I am still seeing this issue with MessageKit in my app. Thanks!

**Comment by Kaspik** [comment]
SwiftUI is still experimental for MessageKit, we should mention that anywhere... I haven't even took a look on the current implementation / support for SwiftUI honestly.

**Comment by Gardenhire** [comment]
I am facing this issue with SwiftUI as well. Happy to help provide more info for debugging if needed.

**Comment by ImTheSquid** [comment]
I'm also having the same problem. I've figured out that tapping on the `MessagesCollectionView` sometimes fixes the problem temporarily but other times it doesn't.

**Comment by micai24** [comment]
I was able to fix the problem by using the `keyboardDidShowNotification` and setting `messagesCollectionView.contentInset.bottom = 0`

`      NotificationCenter.default.addObserver(self, selector: #selector(handleKeyboardDidShow(_:)), name: UIResponder.keyboardDidShowNotification, object: nil)
`

`@objc func handleKeyboardDidShow(_ notification: Notification) {
    messagesCollectionView.contentInset.bottom = 0
  }`

Note i'm using this for SwiftUI, tested for iOS 14.5+ and iOS 15 only phone devices.
