### ISSUE TITLE
Memoji stickers are rendered awfully large in Input Bar Textfield

### ISSUE THREAD

**Issue by AlbertoPvt** [MessageKit/MessageKit#1507]
**Describe the bug**
Memoji stickers are rendered extremely large inside the textfield when input in the InputBar. 

**To Reproduce**
Steps/code to reproduce the behavior:
On the Example App, navigate to any Example.
Then input a Memoji from the keyboard in the textfield. 

**Expected behavior**
Memojis should be rendered at their regular size. 

**Screenshots**
[Click here.](https://ibb.co/BKNXK0r)

**Environment**
- What version of MessageKit are you using? 
3.4.2
- What version of iOS are you running on?
3.4.2
- What version of Swift are you running on?
5.3
- What device(s) are you testing on? Are these simulators?
Physical iPhone Xr. 
- Is the issue you're experiencing reproducible in the example app?
Yes. 

**Additional context**

The issue was already being presented in #1235 but has been closed without an answer.
 If anyone knows how to handle the issue it and wanna help me it is greatly appreciated.

**Comment by martinpucik** [comment]
Hey @AlbertoPvt thanks for reporting this. It seems like this is an [InputBarAccessoryView's](https://github.com/nathantannar4/InputBarAccessoryView) issue. Please try to report this over there
