### ISSUE TITLE
When pressing send button without writing anything on inputTextView, the inputBar dissapears. 

### ISSUE THREAD

**Issue by andreparente** [MessageKit/MessageKit#1508]
- What version of MessageKit are you using?
3.4.2
- What version of iOS are you running on?
14.2
- What version of Swift are you running on?
5
- What device(s) are you testing on? Are these simulators?
Simulators and iPhone SE (2nd generation)

- Is the issue you're experiencing reproducable in the example app?
No :(

I'm using IQKeyboardManager too, dont know if its influencing on some behaviour

**Comment by martinpucik** [comment]
Hey @andreparente could you try to reproduce this issue in our Example project or change the example code so the issue could be reproduced? https://github.com/MessageKit/MessageKit/tree/master/Example

**Comment by andreparente** [comment]
Hello Martin, it seems like always when I tap outside uitextView and inside inputBar, it disappears... On the example project this doesn't happen! I will try to reproduce on the example, I think maybe IQKeyboardManager lib is recognizing the tap gesture and dismissing the inputAccessoryView (maybe). It seems the big difference between my project and the example project.

**Comment by andreparente** [comment]
update: I removed the lib IQKeyboardManager and the problem still persists...

**Comment by andreparente** [comment]
the chatViewController it's pushed, its not modal (just like the example).

**Comment by andreparente** [comment]
update: I created a TestChatViewController which inherits from MessagesViewController, an empty one, without any logic, only viewDidAppear. 
![image](https://user-images.githubusercontent.com/15111549/101907471-60807b00-3b99-11eb-914a-81861c12dc0d.png)

and the bug still goes on, how can I make it more clear for you guys? Thanks for the attention :)

**Comment by vvit** [comment]
@andreparente Good lord, I'm struggling with the same issue. Could you drop the dependencies you're using in your project? Podfile or Cartfile. 
Let's compare them and find similar.
Thanks.

UPD. Actually importing all my pods into a sample project doesn't help. Maybe it's about view hierarchy.

**Comment by andreparente** [comment]
Hello @vvit, this is my podfile: (even without IQKeyboardManagerSwift, the problem still persists..) 
![image](https://user-images.githubusercontent.com/15111549/103300847-a41f1580-49de-11eb-8f17-90870ea7432b.png)

**Comment by andreparente** [comment]
@vvit I use a NavigationController that has a root TabBarController and pushes the ChatViewController... Do you have a tabbarcontroller on the hierarchy?

**Comment by vvit** [comment]
Thanks. The pods have nothing to do with it. I have similar hierarchy. 
- TabBarController
— NavigationController

I’m also pushing the chat VC. Once I present it modaly the issue disappears!
I might end up using an alternate solution described in another issue here on GitHub. Fork a repo, detach the message bar from inputView and add a bottom constraint to it.

**Comment by andreparente** [comment]
well, maybe the tabbarController on the hierarchy has something to do with it (the project example doesnt use it, right?)

**Comment by vvit** [comment]
I’ve been trying to modify the sample project by adding tab bar and nav bar controllers but believe it or not there was no issue.

**Comment by vvit** [comment]
Not sure if this disappear issue is related: https://github.com/nathantannar4/InputBarAccessoryView/issues/77

**Comment by vvit** [comment]
My temporary solution is here: https://github.com/vvit/MessageKit/commits/ssource

**Comment by Yulia8294** [comment]
Hey, I've been having the same issue, and turned out it was IQKeyboardManager after all. But just disabling it by setting **isEnabled** to false did not help, I had also to disable **shouldRegisnOnTapOutside** feature when loading Chat Controller. So the following code fixed the issue for me:

``` 
IQKeyboardManager.shared().isEnabled = false
IQKeyboardManager.shared().shouldResignOnTouchOutside = false
```

I disable them on **viewWillAppear** and enable back on **viewWillDisappear**. Hope it will help somebody.

**Comment by Kaspik** [comment]
@vvit @andreparente Did you see ^^? Did it resolve your issue?

**Comment by vvit** [comment]
@Kaspik no, it didn't help. The project I used didn't import that lib.
