### ISSUE TITLE
inputaccessyView not follow keyboard

### ISSUE THREAD

**Issue by WineKai** [MessageKit/MessageKit#1510]
hey , i used this project in my product,  it almost work perfect。
But I also encountered some problems：
<img width="376" alt="WX20201212-192611@2x" src="https://user-images.githubusercontent.com/16148218/101982582-03c3b400-3cb0-11eb-96fc-de620532d624.png">
how can i fix this? 

tks

**Comment by cody1024d** [comment]
I'm seeing the same issue.

Specifically, after sending a message, and then going to the home screen, and then opening your app back up, the above occurs.
