### ISSUE TITLE
Allow to pick an image using UIImagePickerController

### ISSUE THREAD

**Issue by MohannadBakbouk** [MessageKit/MessageKit#1511]
Hi everyone
It's really an awesome repo which helps me a lot  and I would like to contribute to,  what I need to do adding a camera button into documentation example to allow pick an Image using  UIImagePickerController as shown in the screenshot below

![CameraButton](https://user-images.githubusercontent.com/71793823/102729283-f9736c80-42e4-11eb-8b15-b959c1d7e2b6.png)

I've implemented it so can I make a pull request?
thank you in advance

**Comment by Kaspik** [comment]
Hey! We will be more than happy if you enhance any of our example views or if you add a new one. :)

personally I think it would be nice to fix the camera controller by centering it (vertically) and improving the padding, as well as maybe using some native camera icon, but happy to review whatever you prepare.

Note: If you re gonna do it, you might think about enhancing example project in `InputBarAccessoryView` repo itself.

**Comment by MohannadBakbouk** [comment]
"you might think about enhancing example project in InputBarAccessoryView repo itself "
Did you mean Adding a built-in camera button into InputBarAccessoryView the existed one send button?

**Comment by MohannadBakbouk** [comment]
@Kaspik  I've tried to merge my previous work with the example of InputBarAccessoryView so I subclass  InputBarAccessoryView and I created new delegate method for attachments  as shown below
func inputBar(_ inputBar: InputBarAccessoryView, didPressSendButtonWith attachments[AttachmentManager.Attachment])
the work is ready for review  and I created a pull request for it  with 1512 number
thank you in advanced
