### ISSUE TITLE
Can't show all text in cell

### ISSUE THREAD

**Issue by result0924** [MessageKit/MessageKit#1513]
**Describe the bug**
Can't show all text in cell

**To Reproduce**
Steps/code to reproduce the behavior:
If the bug can be reproduced in the MessageKit example app, this is really helpful to us!

In some cases it can be really helpful to provide a short example of your code.
If so, please wrap these code blocks in backticks, like this:

<details>
<summary>
<b>Debug Coe</b>
</summary>
<p>

```swift
    override func configureMessageCollectionView() {
        super.configureMessageCollectionView()
        
        let layout = messagesCollectionView.collectionViewLayout as? MessagesCollectionViewFlowLayout
        layout?.sectionInset = UIEdgeInsets(top: 5, left: 8, bottom: 5, right: 8)
        
        // Hide the outgoing avatar and adjust the label alignment to line up with the messages
        layout?.setMessageOutgoingAvatarSize(.zero)
        layout?.setMessageOutgoingMessageTopLabelAlignment(LabelAlignment(textAlignment: .right, textInsets: UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 8)))
        layout?.setMessageOutgoingMessageBottomLabelAlignment(LabelAlignment(textAlignment: .right, textInsets: UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 8)))

        // Set outgoing avatar to overlap with the message bubble
        layout?.setMessageIncomingMessageTopLabelAlignment(LabelAlignment(textAlignment: .left, textInsets: UIEdgeInsets(top: 0, left: 18, bottom: outgoingAvatarOverlap, right: 0)))
        layout?.setMessageIncomingAvatarSize(CGSize(width: 35, height: 35))
        layout?.setMessageIncomingMessagePadding(UIEdgeInsets(top: 0, left: 10, bottom: 0, right: 42))
        layout?.setMessageOutgoingMessagePadding(UIEdgeInsets(top: 0, left: 53, bottom: 0, right: 8))

        layout?.setMessageIncomingAvatarPosition(.init(vertical: .messageLabelTop))

        messagesCollectionView.messagesLayoutDelegate = self
        messagesCollectionView.messagesDisplayDelegate = self
    }
```

```swift
mock attributed string

let randomSentence = "ご連絡ありがとうございます。\n\nいただいた内容は原則１日1回、薬剤師が確認して順次回答いたします。（休業日を除く）\n※薬局の休業日および15時以降にいただいたご相談は、翌営業日以降、順次回答いたします。\n※ご連絡内容や薬局の混雑状況によっては、回答に時間がかかる場合もございます。\n※※年末年始　休業日のお知らせ※※\n12月29日(火) 午後\n12月30日(水)～1月3日(日)　"
        let textAllRange = NSRange(location: 0, length: randomSentence.utf16.count)
        let content: String = randomSentence
        let attributedText = NSMutableAttributedString(string: content)
        attributedText.addAttribute(NSAttributedString.Key.font, value: UIFont.systemFont(ofSize: 16, weight: .regular), range: textAllRange)
        let paragraphStyle = NSMutableParagraphStyle()
        paragraphStyle.minimumLineHeight = 24
        paragraphStyle.maximumLineHeight = 24
        attributedText.addAttribute(NSAttributedString.Key.paragraphStyle, value: paragraphStyle, range: textAllRange)
        let textColor: UIColor = .red
        attributedText.addAttribute(NSAttributedString.Key.foregroundColor, value: textColor, range: textAllRange)
        return MockMessage(attributedText: attributedText, user: user, messageId: uniqueID, date: date)
```

```swift
mock text
        let randomSentence = "yuchen您好, 我們非常擔心您剛記錄的 500 mg/dL 血糖值。建議您馬上回診或電繫您的醫師、衛教師，若無人處理請前往急診處理。"
        return MockMessage(text: randomSentence, user: user, messageId: uniqueID, date: date)
```
 </p>
</details>

Please, *do not* submit screenshots of code, instead copy and paste it as above.

**Expected behavior**
show all message

**Screenshots**

Can't show last line
`12月30日(水)～1月3日(日)`

<img width="311" alt="截圖 2020-12-30 下午1 23 44" src="https://user-images.githubusercontent.com/822363/103331934-09d4d580-4aa3-11eb-9648-69da2508751b.png">

Can't show last line
`理。`

<img width="315" alt="截圖 2020-12-30 下午2 07 57" src="https://user-images.githubusercontent.com/822363/103333359-b06fa500-4aa8-11eb-96ca-40599bda20dc.png">

**Environment**
- What version of MessageKit are you using? 
   3.4.2
- What version of iOS are you running on? 
   14.2
- What version of Swift are you running on? 
   swift 5.3
- What device(s) are you testing on? Are these simulators? 
   simulator iPhone 11 Pro
- Is the issue you're experiencing reproducible in the example app? 
   yes

**Additional context**

must use japanese language and japan locale and iPhone 11 Pro

<img width="470" alt="截圖 2020-12-30 下午1 33 51" src="https://user-images.githubusercontent.com/822363/103332083-abf4bd80-4aa3-11eb-9128-18ec14fadfe8.png">

**Comment by Kaspik** [comment]
I have honestly no idea how to work or debug Japanese so any help here is appreciated.

**Comment by result0924** [comment]
thanks for your reply.
my workaround solution is change UIFont don't use system font in Japanese

**Comment by Kaspik** [comment]
I'm surprised that system font doesn't work, but happy that you found a workaround in the meantime.
