### ISSUE TITLE
Message UI is broken in landscape mode on the iPad.

### ISSUE THREAD

**Issue by ninholli** [MessageKit/MessageKit#1516]
<img width="643" alt="Screen Shot 2021-01-04 at 10 21 39" src="https://user-images.githubusercontent.com/45158249/103498362-137d8500-4e77-11eb-8eb1-93c64211d0c8.png">
<img width="839" alt="Screen Shot 2021-01-04 at 10 21 45" src="https://user-images.githubusercontent.com/45158249/103498355-0eb8d100-4e77-11eb-8548-10a9a5bb5870.png">

**Comment by fukemy** [comment]
i have no ideal to solve this bug, the only way i solved this i remove all layout message setting code, then it's work
