### ISSUE TITLE
[InputBar Bug] Rejected resignFirstResponder when being removed from hierarchy

### ISSUE THREAD

**Issue by Ludotrico** [MessageKit/MessageKit#1517]
**Issue:**
The input bar is not dismissed. 

**To reproduce:**
1.) Make MessageVC a child of another VC.
2.) Push MessageVC on VC's navigation controller
3.) begin typing in input bar
4.) Call resignFirstResponder()
5.) Notice that "rejected resignFirstResponder when being removed from hierarchy" is printed to the console and the input bar can never be dismissed

Similar to this [issue](https://github.com/nathantannar4/InputBarAccessoryView/issues/178).

**Comment by fukemy** [comment]
hi, how did u solved this?
