### ISSUE TITLE
Create New MessageKit Release

### ISSUE THREAD

**Issue by DomenicBianchi01** [MessageKit/MessageKit#1519]
I am trying to migrate my app to use static framework linking; however, the current release of MessageKit uses the `resources` field in the podspec. This causes build errors when using static linking. This problem has already been fixed (the podspec now uses `resource_bundles`) but it is not included in the current release.

Would it be possible to release a new version of MessageKit?

**Comment by Kaspik** [comment]
I'm currently not able to release new version due to CocoaPods issue - https://github.com/CocoaPods/CocoaPods/issues/10326

After that one is resolved we can get new version out. In the meantime, I suggest using commit or master itself.

**Comment by DomenicBianchi01** [comment]
Ah ok. Thanks for the quick reply!

**Comment by DomenicBianchi01** [comment]
@Kaspik This is probably a dumb question but since the issue has to do with M1 Mac's, is it possible for someone with an Intel Mac to do the release?

**Comment by Kaspik** [comment]
It is, if someone would be available. :) I can actually do release for SPM, only CocoaPods won't have a new version.

Let me do it later today.

**Comment by DomenicBianchi01** [comment]
I've got an Intel Mac so if you provide me the instructions I can do it. ¯\_(ツ)_/¯

**Comment by Kaspik** [comment]
That's not that easy. :) SPM release shipped.

**Comment by DomenicBianchi01** [comment]
@Kaspik Can you please reopen the issue? We can't use SPM for our app since some of the dependencies we use don't support SPM yet (looking at you Material Components.....). Therefore, not being able to make a Cocoapods release is still a valid issue.

**Comment by Kaspik** [comment]
CocoaPods pushed as well.

**Comment by DomenicBianchi01** [comment]
Sweet thanks!
