### ISSUE TITLE
removeKeyboardObservers is not called when MessagesViewController is dismissed

### ISSUE THREAD

**Issue by carlsondev** [MessageKit/MessageKit#1522]
**Describe the bug**
The "removeKeyboardObservers" method defined in "MessagesViewController+Keyboard.swift" (line 38) is not called when the MessagesViewController is dismissed even with it being called in the "deinit". This leads to the keyboard observers still being active when the view is not in memory, causing issues or even crashes when the keyboard is shown after the MessagesViewController is dismissed. 
I originally noticed this crash with the "currentSender()" method from implementing the MessagesDataSource since the sender I was returning is nil when the user is logged out. If the user tried to enter login information it would crash since the keyboard observers were still active but the currentSender was nil since the user had not logged in. 
In order to solve this, I needed to copy the "removeKeyboardObservers" method and call it before dismissing my MessagesViewController.

**To Reproduce**
Steps/code to reproduce the behavior:

I believe this may have to do with the fact that my MessagesViewController is embedded in a NavigationViewController to get certain functionality. (ConversationViewController subclasses MessagesViewController)

*Inside TableView didSelect which is presenting the ConversationViewController*

```swift
let nav = self.storyboard?.instantiateViewController(identifier: "conversationNavController") as! UINavigationController
let initalConvoVC = self.storyboard?.instantiateViewController(identifier: "conversationVC") as! ConversationViewController
nav.viewControllers.append(initalConvoVC)
nav.modalPresentationStyle = .fullScreen
self.present(nav, animated: true, completion: nil)
```
*Inside the ConversationViewController when the back button is pressed*

```swift
self.dismiss(animated: true, completion: nil)
```

**Expected behavior**
Listed above

**Screenshots**

https://user-images.githubusercontent.com/7782391/104116252-18f22980-52d4-11eb-9200-818ca686bd10.mp4

**Environment**
- What version of MessageKit are you using?: 3.2
- What version of iOS are you running on?: 14.0 (but this happens on any version tested)
- What version of Swift are you running on? Swift 5
- What device(s) are you testing on? Are these simulators? Testing on an iPhone XR and various simulators
- Is the issue you're experiencing reproducible in the example app? This is not reproducible in the example app since it doesn't seem to dismiss any view, only move around through the navigation controller. Also, there are no instances where the keyboard would be shown outside of a MessagesViewController

**Comment by Kaspik** [comment]
I'm not sure if we are able to support version 3.2.0 - could you please try with latest release?

**Comment by carlsondev** [comment]
My bad, that fixed it. "viewWillDisappear" is now overriden in "MessagesViewController" in the new version which fixes the issue.

**Comment by fukemy** [comment]
i solved by overriten viewWillDisappear and do nothing ( do not call super method)
