### ISSUE TITLE
Content offset not preserved during device orientation change

### ISSUE THREAD

**Issue by chrispychiki** [MessageKit/MessageKit#1528]
First off, thanks for this wonderful library. It's a great way to incorporate messaging and I really appreciate all the effort it takes to create and maintain it.

**Describe the bug**

When device orientation changes, the messages should remain in the same relative location.

Since the available space and message size changes on orientation change, obviously some messages will no longer be visible. However, I would expect that whatever message was visible right above the input bar should remain visible no matter how many times the device is rotated.

What actually happens is that the messages kind of "jump" up and their relative positions within the view are not maintained, even when rotating the device back.

**To Reproduce**
Steps/code to reproduce the behavior:

1. Open example app
2. Change device orientation (e.g. portrait -> landscape). Previously visible messages are no longer visible because the scroll position has jumped up
3. Change device orientation back. Originally visible messages are still not visible and I need to scroll down to see them again

**Expected behavior**

On orientation change (e.g. portrait -> landscape), whatever messages I was looking at before the change should remain in the same relative location in the view after the change.

**Screenshots**

**Environment**
- What version of MessageKit are you using? 3.5.0
- What version of iOS are you running on? 14.2
- What version of Swift are you running on? 5
- What device(s) are you testing on? Are these simulators? Testing on personal device
- Is the issue you're experiencing reproducible in the example app? Yes

**Additional context**

I did try implementing a workaround in my own ViewController:

```swift
    override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        super.viewWillTransition(to: size, with: coordinator)

        let visibleSections = messagesCollectionView.indexPathsForVisibleItems.map{$0.section}.sorted()
        guard visibleSections.last != nil else {
            return
        }
        prevIndexPathAtBottom = IndexPath(item: 0, section: visibleSections.last!)
    }

    func collectionView(_ collectionView: UICollectionView, targetContentOffsetForProposedContentOffset proposedContentOffset: CGPoint) -> CGPoint {
        if let prevIndex = prevIndexPathAtBottom {
            messagesCollectionView.scrollToItem(at: prevIndex, at: .bottom, animated: false)
            return messagesCollectionView.contentOffset
        }
        return proposedContentOffset
    }
```

This isn't quite right, but it does more or less keep the messages in the same relative position. Is there a better way of achieving this effect?

**Comment by ekazaev** [comment]
Sorry for the off topic, have a look here https://github.com/ekazaev/ChatLayout This issue does not exist in this implementation.
