### ISSUE TITLE
Disable MessageInputBar

### ISSUE THREAD

**Issue by StackHelp** [MessageKit/MessageKit#1533]
Is it possible to disable the `MessageInputBar`?

**Comment by Kaspik** [comment]
Did you try to remove the inputBarAccessoryview os set the accessoryView to nil?

**Comment by martinpucik** [comment]
@StackHelp I think overriding `canBecomeFirstResponder()` and setting it to `false` in your `MessagesViewController` subclass should achieve this 

https://github.com/MessageKit/MessageKit/blob/bdb07821037d7760041c979d7986774a0edb06ef/Sources/Controllers/MessagesViewController.swift#L77-L79

lmk if that solves your issue :)
