### ISSUE TITLE
MessageKitError.couldNotFindColorAsset on startup when integrated with Cocoapods

### ISSUE THREAD

**Issue by schroederm** [MessageKit/MessageKit#1537]
**Describe the bug**
I've added MessageKit to my project and created a minimal MessageViewController following the guide. When I integrate MessageKit with SPM, it starts up correctly and I see the view controller. When I integrate with Cocoapods, the app crashes when trying to access the `.collectionViewBackground` color asset from the `MessagesCollectionView` initializer. 

That's because the `UIColor` extension cannot load the color in `colorFromAssetBundle`. `po`ing `Bundle.messageKitAssetBundle` at the breakpoint indicates that the Bundle was located, but is "not yet loaded". Trying to reproduce this with the example app works without any problems. 

The main difference between that and my app is that I don't include the pod in the main target but instead in a project internal framework that's built for my UI classes to be consumed by the main app. Not sure if that could trip up the loading of Bundles.

**Environment**
- What version of MessageKit are you using?
3.5.0

- What version of iOS are you running on?
14.4 (Simulator)

- What version of Swift are you running on?
Swift 5, Xcode 12.4

- What device(s) are you testing on? Are these simulators?
iPod touch (7th gen) simulator

- Is the issue you're experiencing reproducible in the example app?
No, see above.

**Comment by Kaspik** [comment]
Sorry for late reply. I'm not sure what is the best way to solve or debug this (ideally, we would add another example that would be this case), but as it seems like a CocoaPods issue only in this edge case (via another framework) - and I'm not sure if there is a situation where you can't use SPM for this - should we actually spend time on this?

**Comment by AbdulMateenChughtai** [comment]
@schroederm were you able to get this issue resolved? I'm stuck on the same problem. My environment is iOS 15 and Xcode 13.

**Comment by schroederm** [comment]
@AbdulMateenChughtai No, I dropped that project so I didn't investigate any further.
