### ISSUE TITLE
ScrollToLastItem shows the user the scroll instead of opening the vc on the last item

### ISSUE THREAD

**Issue by mlyongardiner** [MessageKit/MessageKit#1539]
**Describe the bug**
The messagecollectionview scrolls to the bottom of the collectionview after the view has appeared, instead of while the view is loading. The user should not see the table scrolling to the bottom, and removing the animation, or setting it to false, still shows them the "top" of the collectionview for a brief moment before scrolling to the bottom". If I call scrollToLastItem in viewWillAppear, nothing happens. If I call it in viewDidAppear, it's called too late and the user sees the table scroll to the bottom.

How can I load the VC so that the user does NOT see it scroll to the bottom AND there's no extra lag time to open the VC?

I haven't added code here because I'm not sure what would be helpful to show, please let me know what methods you would need to see from me to help. To preface, I do not do any loading of messages when loading the VC, it's already preloaded and at most 10 items unless the user pulls down to load more, so it shouldn't be an issue with the messagesList or the amount of items in the list. If MessageKit does not allow for this, how might I be able to hack around it?

**Environment**
- What version of MessageKit are you using?
- 3.5
- What version of iOS are you running on?
- 14.3
- What version of Swift are you running on?
- Swift 5
- What device(s) are you testing on? Are these simulators?
- iPhone 12Pro, real device and simulator
- Is the issue you're experiencing reproducible in the example app?
- Yes, only the SwiftUI example has the desired behavior, all other examples show the user the scroll to the bottom.

**Comment by Kaspik** [comment]
This is what we do on our project:
```
private var isFirstLoad: Bool = true

override public func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        if isFirstLoad {
            isFirstLoad = false
            messagesCollectionView.reloadData()
            messagesCollectionView.scrollToLastItem(animated: false)
            UIView.animate(withDuration: 0.2) {
                self.messagesCollectionView.alpha = 1
            }
        }
}
```
The important part is that we have the data there, so reloadData here actually really loads all cells, makes the content size not 0, and then scrolls.

**Comment by mlyongardiner** [comment]
@Kaspik This works a lot better!! The question I have is how to make it account for cellBottom and messageBottom height. I can see the table "correct" for the message and cell bottom heights after it loads, instead of onAppear as it should. How might I go about resolving this? Please see the video here: https://vimeo.com/520054306

**Comment by Kaspik** [comment]
That means the cell is not rendered correctly in the reloadData() which means the data might not be there on your side - `scrollToLastItem` uses system method with `position: .bottom` so there is really small chance we have bug in our scroll method.

**Comment by mlyongardiner** [comment]
@Kaspik but if it properly loads to the last cell then the data is there, right? Would it have to do with my cellBottom and messageBottom functions taking too long to process?

**Comment by Kaspik** [comment]
Yes, if they are asynchronous, they are not ready for the initial calculation :)

**Comment by mlyongardiner** [comment]
@Kaspik hmm here are the functions I'm using. The messageBottomLabel is for "read/unread" labels and I use a custom view for the cellBottom which is for a custom action "Send Reminder" or "View More" for group chats. Both don't use any async calls.. but please feel free to look at let me know what you think!!

`override func messageBottomLabelAttributedText(for message: MessageType, at indexPath: IndexPath) -> NSAttributedString? {
        
        if !isNextMessageSameSender(at: indexPath) && isFromCurrentSender(message: message) && isLastFromCurrentSender(at: indexPath) { // only show for the last from current sender
                                    
            let myMessage = messageList[indexPath.section]
            var string: NSMutableAttributedString!
            
            // check when the message was sent
            var sendString = ""
            if Calendar.current.isDateInToday(myMessage.sentDate) {
                sendString = currentDayFormatter.string(from: myMessage.sentDate)
            } else if Calendar.current.isDateInYesterday(myMessage.sentDate) {
                sendString = "Yesterday"
            } else {
                sendString = previousDayFormatter.string(from: myMessage.sentDate)
            }
            
            // check if/when the message was read
            var readString = ""
            if let date = myMessage.readDate {
                if Calendar.current.isDateInToday(date) {
                    readString = currentDayFormatter.string(from: date)
                } else if Calendar.current.isDateInYesterday(date) {
                    readString = "Yesterday"
                } else {
                    readString = previousDayFormatter.string(from: date)
                }
            }
            
            let imageAttachment = NSTextAttachment()
            string = NSMutableAttributedString(string: "")
            imageAttachment.bounds = CGRect(x: 0, y: 0, width: 10, height: 10)

            print("read by: ", myMessage.readBy)
            
            let group = Chat.shared.getGroup(with: myMessage.chatId)
            let otherMembers = group.members.filter{$0 != User.shared.user.uid}
            
            // if group chat, use "readBy"
            if isGroupChat, let readBy = myMessage.readBy {
            
                let count = readBy.count
            
                if count == otherMembers.count {
                    imageAttachment.image = UIImage(named: "green")
                } else {
                    imageAttachment.image = UIImage(named: "red")
                }
                
                string.append(NSAttributedString(attachment: imageAttachment))
                string.append(NSAttributedString(string: " Sent \(sendString), Read by \(count) of \(otherMembers.count)"))
            
            } else { // if single chat, use "read"
                
                if myMessage.read {
                    
                    imageAttachment.image = UIImage(named: "green")
                    string.append(NSAttributedString(attachment: imageAttachment))
                    string.append(NSAttributedString(string: " Sent \(sendString), Read \(readString)"))
                    
                } else {
                    imageAttachment.image = UIImage(named: "red")
                    string.append(NSAttributedString(attachment: imageAttachment))
                    string.append(NSAttributedString(string: " Sent \(sendString), Unread"))
                }
            }
                        
            string.addAttributes([NSAttributedString.Key.foregroundColor : UIColor.blueyGrey, .font : UIFont(name: "SFProText-Regular", size: 13)!], range: NSRange(location: 0, length: string.length))
            return string
        }
        return nil
    }`

`public override func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        
        guard let messagesDataSource = messagesCollectionView.messagesDataSource else {
            fatalError("Ouch. nil data source for messages")
        }

        // Very important to check this when overriding `cellForItemAt`
        // Super method will handle returning the typing indicator cell
        guard !isSectionReservedForTypingIndicator(indexPath.section) else {
            return super.collectionView(collectionView, cellForItemAt: indexPath)
        }

        let message = messagesDataSource.messageForItem(at: indexPath, in: messagesCollectionView)
        if case .custom = message.kind {
            let cell = messagesCollectionView.dequeueReusableCell(CustomCell.self, for: indexPath)
            cell.configure(with: message, at: indexPath, and: messagesCollectionView)
            return cell
        }
        
        if case .text = message.kind {
            let cell = messagesCollectionView.dequeueReusableCell(TextMessageCell.self, for: indexPath)
            cell.configure(with: message, at: indexPath, and: messagesCollectionView)

            if isPreviousMessageSameSender(at: indexPath) {
                cell.messageTopLabel.textInsets = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0)
            }

            if let message = message as? MessageItem {
                if let returnedCell = handleCellBottomCell(for: indexPath, cell: cell, message: message) {
                    return returnedCell
                }
            }

            if reminderView.superview == cell.cellBottomLabel {
                print("remove reminder from superviews")
                reminderView.removeFromSuperview()
            }
            return cell
        }
        
        return super.collectionView(collectionView, cellForItemAt: indexPath)
    }`

`func handleCellBottomCell(for indexPath: IndexPath, cell: MessageContentCell, message: MessageItem) -> MessageContentCell? {
        
        if !isGroupChat {
            
            if !message.read && isFromCurrentSender(message: message) && (indexPath.section == messageList.count - 1) { // if unread and is the most recent message

                cell.cellBottomLabel.addSubview(reminderView)

                reminderView.translatesAutoresizingMaskIntoConstraints = false
                let viewConstraints = [
                    reminderView.topAnchor.constraint(equalTo: cell.cellBottomLabel.topAnchor, constant: 10),
                    reminderView.bottomAnchor.constraint(equalTo: cell.cellBottomLabel.bottomAnchor, constant: -10),
                    reminderView.trailingAnchor.constraint(equalTo: cell.cellBottomLabel.trailingAnchor, constant: 0),
                ]
                NSLayoutConstraint.activate(viewConstraints)

                return cell
            }
            
            return nil
            
        } else {
            
            if !isNextMessageSameSender(at: indexPath) && isFromCurrentSender(message: message) && isLastFromCurrentSender(at: indexPath) { // if unread and is the most recent message from the current user {
             
                cell.cellBottomLabel.addSubview(moreView)

                moreView.translatesAutoresizingMaskIntoConstraints = false
                let viewConstraints = [
                    moreView.topAnchor.constraint(equalTo: cell.cellBottomLabel.topAnchor, constant: 10),
                    moreView.bottomAnchor.constraint(equalTo: cell.cellBottomLabel.bottomAnchor, constant: -10),
                    moreView.trailingAnchor.constraint(equalTo: cell.cellBottomLabel.trailingAnchor, constant: 0),
                ]
                NSLayoutConstraint.activate(viewConstraints)
                
                return cell
            }
            
            return nil
        }
    }`

**Comment by mlyongardiner** [comment]
@Kaspik And calculating the height is also simple here:
`func messageBottomLabelHeight(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> CGFloat {
        return (!isNextMessageSameSender(at: indexPath) && isFromCurrentSender(message: message) && isLastFromCurrentSender(at: indexPath)) ? 20 : 0
    }`

`func cellBottomLabelHeight(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> CGFloat {
        
        if let message = message as? MessageItem {
            if !isGroupChat {
                if !message.read && isFromCurrentSender(message: message) && (indexPath.section == messageList.count - 1) {
                    return 50
                }
            } else {
                if !isNextMessageSameSender(at: indexPath) && isFromCurrentSender(message: message) && isLastFromCurrentSender(at: indexPath) {
                    return 50
                }
            }
        }
        return 0
    }`

**Comment by Kaspik** [comment]
The question is if the data are there. Unfortunately I won't be able to help you without the test project itself or something similar so I hope you will be able to resolve this. :)

**Comment by mlyongardiner** [comment]
@Kaspik shouldn't I be able to test if the data is there when it needs to be? Can I log that in the console, and if so where should I be looking for it to be?

**Comment by mlyongardiner** [comment]
@Kaspik Of course it had to do with a custom segue I was using! Do you (know how to) properly implement a "left to right" segue in any of your apps? Like iMessage when clicking into a message.

**Comment by Kaspik** [comment]
We are not using storyboards nor xibs so all animations and presentations are done manually, sorry. :) Not sure what you mean "when clicking into a message".
