### ISSUE TITLE
Is there a way to customize separatorLine in InputBarAccessoryView?

### ISSUE THREAD

**Issue by mgorvat** [MessageKit/MessageKit#1541]
I'm trying to figure out how to customize separatorLine in InputBarAccessoryView class appearance. I need this view have space to left and right border of the view. Constraints are setting up in setupConstraints, however I don't understand how to change constraints. What is the most correct way to do this?

MessageKit version: 3.4.1.

**Comment by Kaspik** [comment]
This is more of a question to the https://github.com/nathantannar4/InputBarAccessoryView repo :)
