### ISSUE TITLE
MessageKit input bar auto growing and  hiding the navigation bar iOS

### ISSUE THREAD

**Issue by annapurnarelan20** [MessageKit/MessageKit#1542]
Testing on simulator
1.version of iOS are you running on : iOS 14.4 
2.What version of Swift are you running on? : 5.1
3.What device(s) are you testing on? Are these simulators? : simulators , yes iPhone 12

Pls refer the image attached.
getting the issue as soon as I am starting typing in the input textview it the messages view is going up and hiding the navigation bar.

Please help.

<img width="414" alt="Screenshot 2021-02-18 at 8 10 24 PM" src="https://user-images.githubusercontent.com/47179317/108373496-f681f300-7225-11eb-8c53-0e50f3a2e40f.png">

**Comment by sergiotrejo016** [comment]
Hey @annapurnarelan20  have you find any solution or the root cause,
 I´m having same issue, also I have notice that every time I tap on the textView, chat view is push up a little bit

**Comment by annapurnarelan20** [comment]
Hey sergio,

Yes i found the solution, i have used iQkeyboard manager in my application 
IQKeyboardManager.shared.enable = true , if you want to exclude the chat view controller from this i added following line 

       IQKeyboardManager.shared.disabledDistanceHandlingClasses.append(Your chatvc) and it worked perfectly 👍👍


Hope this will help!!

Regards,
Annapurna Relan

**Comment by martinpucik** [comment]
So the issue is not in MessageKit? @annapurnarelan20 feel free to reopen this if not 👍
