### ISSUE TITLE
Inputbar not showing with TabBarConroller

### ISSUE THREAD

**Issue by FlorianBenger** [MessageKit/MessageKit#1544]
Hi,

I'm trying to use a MessageViewController with a Tabbarcontroller in combination. The problem is the Inputbar is not showing. I read all the other request but nothing worked for me. 
Is this combination possible at the moment? I tested it also in a small test project.

I'm using 

Messagekit 3.5.0
XCode 12 
The simulator and the device have the same behaviour.

This is my Storyboard. The bottom controller is my MessageViewController

[
![Bildschirmfoto 2021-02-26 um 20 00 30](https://user-images.githubusercontent.com/77433049/109343489-bcd86a00-786d-11eb-9340-782c8d9333aa.png)
](url)

```
 override func viewDidLoad() {
        super.viewDidLoad()
        
        messageInputBar.delegate = self as InputBarAccessoryViewDelegate
        maintainPositionOnKeyboardFrameChanged = true
        
        messageInputBar.leftStackView.alignment = .center
        messageInputBar.setLeftStackViewWidthConstant(to: 50, animated: false)
        messageInputBar.inputTextView.tintColor = .yellow
        messageInputBar.sendButton.setTitleColor(.purple, for: .normal)
        
        messagesCollectionView.messagesDataSource = self
        messagesCollectionView.messagesLayoutDelegate = self
        messagesCollectionView.messagesDisplayDelegate = self
        self.becomeFirstResponder()
        
       
        
        // Do any additional setup after loading the view.
    }
```

This is how it looks

![Bildschirmfoto 2021-02-26 um 20 09 30](https://user-images.githubusercontent.com/77433049/109344155-a54db100-786e-11eb-855a-a11bad7998c1.png)

Perhaps you can give me a hint or much better a solution.

Thanks for this great extension.

**Comment by FlorianBenger** [comment]
Ok I'm a step further. 
I added this to my code.
```
   override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
       self.becomeFirstResponder()
        
    }
```

But then the tabbar disappear. :-/

**Comment by bryan-vh** [comment]
I believe that the team behind this project believes it is better to utilize the full real estate of the phone to present the chat messages, so you shouldn't really be trying to put the MessagesViewController in a tab bar controller. Instead, you should try to present the MessagesViewController somehow from the tab bar controller (via a button, barbuttonitem, etc)

**Comment by Kaspik** [comment]
I can't think of a situation where you want to have input on top of tab bar (or how it would look like) - and I don't think system allows inputBarAccessoryView to be automatically handled together with tab bar.
