### ISSUE TITLE
there seems to be an issue , though I confirmed to MessagesDataSource and added the necessary methods still gives me an error to add currentSender() and MessageForItem() method and if add than off course Xcode will give me an error than have added multiple times

### ISSUE THREAD

**Issue by Yuvraj102** [MessageKit/MessageKit#1550]
**Describe the bug**

**To Reproduce**
Steps/code to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Environment**
- What version of MessageKit are you using?
- What version of iOS are you running on?
- What version of Swift are you running on?
- What device(s) are you testing on? Are these simulators?
- Is the issue you're experiencing reproducible in the example app?

**Additional context**

**Comment by Yuvraj102** [comment]
please fix it

**Comment by Kaspik** [comment]
@Yuvraj102 For future reference / opening new issue - please fill out the form that is in bug template, give us as much details as you can, ideally tell us if it's reproducible on Example project, or create minimal demo project that we can see the issue and debug it.
