### ISSUE TITLE
Though I confirmed to MessagesDataSource and added the necessary methods still gives me an error to add currentSender() and MessageForItem()

### ISSUE THREAD

**Issue by Yuvraj102** [MessageKit/MessageKit#1551]
**Describe the bug**
I installed the pod as mentioned in the docs and I confirmed to 3 protocols also set their delegate to self , but the error is when I confirmed to MessagesDataSource and added the protocol stubs and still I am getting an error to add stubs and when I click that fix that adds again that stub method and than next as you guys know Xcode will shout saying that " invalid redeclaration " , only currentSender() and messageForItem() are being added 2 times 

**To Reproduce**
here is my code for that view controller 
```

import UIKit
import MessageKit

public protocol MessageType {

    var sender: Sender { get }

    var messageId: String { get }

    var sentDate: Date { get }

    var kind: MessageKind { get }
}
public protocol SenderType {

    var senderId: String { get }
    
    var displayName: String { get }
}

public struct Sender: SenderType {
    public let senderId: String

    public let displayName: String
}

let sender = Sender(senderId: "any_unique_id", displayName: "Steven")
let messages: [MessageType] = []
class ViewController: MessagesViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        messagesCollectionView.messagesDataSource = self
        messagesCollectionView.messagesLayoutDelegate = self
        messagesCollectionView.messagesDisplayDelegate = self
        // Do any additional setup after loading the view.
    }
    
}

extension ViewController:MessagesDataSource {
   // I GET THAT ERROR HERE , I WILL ALSO MENTION A SCREEN SHOT BELOW
    func currentSender() -> SenderType {
        return Sender(senderId: "any_unique_id", displayName: "Steven")
    }
    
    func messageForItem(at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> MessageType {
        return messages[indexPath.section]
    }
    
    func numberOfSections(in messagesCollectionView: MessagesCollectionView) -> Int {
        
        return messages.count
    }
    
    
}
extension ViewController:MessagesLayoutDelegate ,MessagesDisplayDelegate {
    
}

```

**Screenshots**
Even if I have added that stub methods its giving that error 
![error ss1](https://user-images.githubusercontent.com/68990772/110434488-e1d3a500-80d7-11eb-9166-1223c878f190.png)
Below is screen shots when I press fix 
![ss2](https://user-images.githubusercontent.com/68990772/110434716-2b23f480-80d8-11eb-8d0a-d49be1f9f932.png)
below is screen shot for my podfile

![Screenshot 2021-03-09 at 1 07 47 PM](https://user-images.githubusercontent.com/68990772/110435072-91107c00-80d8-11eb-89f2-82bf7bbc68cd.png)

**Environment**
I am running code 12.4
I am running it on iOS 14.4

**Additional context**
I tried cleaning my project , reinstalling pods , cleaning derived data , installing using package manager but still no luck , 
I referred this quick starter guide as mentioned in the docs := https://github.com/MessageKit/MessageKit/blob/master/Documentation/QuickStart.md

**Comment by Kaspik** [comment]
Remove this from your view controller:

```

public protocol MessageType {

    var sender: Sender { get }

    var messageId: String { get }

    var sentDate: Date { get }

    var kind: MessageKind { get }
}
public protocol SenderType {

    var senderId: String { get }
    
    var displayName: String { get }
}

public struct Sender: SenderType {
    public let senderId: String

    public let displayName: String
}
```

**Comment by Yuvraj102** [comment]
Yeah that solved my error , thank you so much, I think that quick starter guide needs little update 😄 
https://github.com/MessageKit/MessageKit/blob/master/Documentation/QuickStart.md

**Comment by Yuvraj102** [comment]
why is messageInputBar.delegate = self giving an error do I need to add some extra dependency too ?
![Screenshot 2021-03-09 at 2 19 30 PM](https://user-images.githubusercontent.com/68990772/110444201-b99d7380-80e2-11eb-96c8-e20cb03580a1.png)
below is the whole code 


```

import UIKit
import MessageKit

struct  Sender:SenderType {
    var senderId: String
    var displayName: String
}
struct Message:MessageType {
    var sender: SenderType
    
    var messageId: String
    
    var sentDate: Date
    
    var kind: MessageKind
    
}
let sender = Sender(senderId: "any_unique_id", displayName: "Steven")
let messages: [MessageType] = []

class ChatViewController: MessagesViewController{
    
    override func viewDidLoad() {
        super.viewDidLoad()
        messageInputBar.delegate = self
        messagesCollectionView.messagesDataSource = self
        messagesCollectionView.messagesLayoutDelegate = self
        messagesCollectionView.messagesDisplayDelegate = self
        view.backgroundColor = .green
        
    }
    
}
extension ChatViewController:InputBarAccessoryViewDelegate  {
    
}
extension ChatViewController:MessagesDataSource {
    
   
    func currentSender() -> SenderType {
        return Sender(senderId: "any_unique_id", displayName: "Steven")
    }
    
    func messageForItem(at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> MessageType {
        return messages[indexPath.section]
    }
    
    func numberOfSections(in messagesCollectionView: MessagesCollectionView) -> Int {
        
        return messages.count
    }
    
    
}
extension ChatViewController:MessagesLayoutDelegate ,MessagesDisplayDelegate {
    
}

```

**Comment by Kaspik** [comment]
`import InputBarAccessoryView`

Do you understand basics of Swift development? If not, I would recommend first going through Swift Playgrounds tutorial.

**Comment by Yuvraj102** [comment]
ooh yeah got it thank you , do you have a full detailed docs , if yes please link , I am actually referring to example project

**Comment by Kaspik** [comment]
There is nothing like a `doc` about that you need to import library if you want to use it... again, please checkout Swift tutorials on developer.apple.com before opening such a trivial issues. :)

**Comment by Yuvraj102** [comment]
I thought that InputBarAccessoryView was included in message kit itself , sure
