### ISSUE TITLE
Text MessageItem Getting Clipped

### ISSUE THREAD

**Issue by mlyongardiner** [MessageKit/MessageKit#1552]
**Describe the bug**
*Occasionally* when I enter a chat some of the text gets clipped by the bubble and I'm trying to figure out why this happens 1. only sometimes and 2. since I'm not making ANY modifications to the cell size - I'm simply using the built in MessageItem for my text and emoji chats. Any help would be appreciated! Happy to share specific code/functions as requested, but again I'm not modifying the cell size so I'm not sure what functions I would show that would be helpful here.

The weird behavior is that 1. it clips the message, 2. changes my tail setup (as seem in the images below), and 3. pushes the trailing bounds to the middle of the screen even though I have no custom trailing constraint (only leading padding for OUTGOING messages)

**Environment**
What version of MessageKit are you using?
3.5
What version of iOS are you running on?
14.3
What version of Swift are you running on?
Swift 5
What device(s) are you testing on? Are these simulators?
iPhone 12Pro, real device and simulator
Is the issue you're experiencing reproducible in the example app?
I don't believe so, but I'm not making any customizations to the Cell Size
![IMG_FF681E76D46B-1](https://user-images.githubusercontent.com/68454399/110552654-b9629f80-8105-11eb-84cd-40d4a97dcdb5.jpeg)
![IMG_FF681E76D46B-2](https://user-images.githubusercontent.com/68454399/110552661-bc5d9000-8105-11eb-8a47-d3ad6fd92cb6.jpeg)

**Comment by fukemy** [comment]
i got same problem only swipe to show date
