### ISSUE TITLE
How do I properly show/un-show an avatar if messages have the same sender and are next to each other? 

### ISSUE THREAD

**Issue by narner** [MessageKit/MessageKit#1554]
I'm currently using this code from the examples to not show a user's avatar if the multiple messages are from the same author:

```
func configureAvatarView(_ avatarView: AvatarView, for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) {
    let sigil = Sigil(ship: Sigil.Ship(rawValue: message.sender.senderId)!, color: .black).image(with: CGSize(width: 24.0, height: 24.0))
    let avatar = Avatar(image: sigil, initials: "")
        avatarView.set(avatar: avatar)
                avatarView.isHidden = isNextMessageSameSender(at: indexPath)
}

func isNextMessageSameSender(at indexPath: IndexPath) -> Bool {
    guard indexPath.section + 1 < messages.count else { return false }
    return messages[indexPath.section].sender.displayName == messages[indexPath.section + 1].sender.displayName
}
```

This is the result I'm expecting to get (from the example) app: 

![CleanShot 2021-03-12 at 11 24 07](https://user-images.githubusercontent.com/2131591/110990732-8fd58e00-8328-11eb-932b-590367a41dac.png)

This is what I'm getting with my app at the moment (the messages in orange here are all from the same person, as my messages in gray on the right):

![CleanShot 2021-03-12 at 11 27 18](https://user-images.githubusercontent.com/2131591/110990807-af6cb680-8328-11eb-9c49-3f9f6861c017.png)

[Cross-posted to StackOverflow](https://stackoverflow.com/questions/66606076/configureavatarview-not-working-properly-in-messagekit)

**Comment by Kaspik** [comment]
Why the message in orange shows wrong avatar (the last one?) This seems like an issue with your data internally.

**Comment by narner** [comment]
Oh I misspoke apologies; the last one on the orange side is a different user from the *rest* of the orange messages

**Comment by Kaspik** [comment]
Okay, did you check that the compare of `displayName` is correct and returns `true` as you expect?

**Comment by narner** [comment]
Put a 100-reputation bounty on my SO question here: https://stackoverflow.com/questions/66606076/configureavatarview-not-working-properly-in-messagekit

**Comment by Kaspik** [comment]
That won't help at all. You need to start debugging and replying :)

**Comment by Kaspik** [comment]
Can you compare not based on displayName but based on senderId or something really unique?

**Comment by Kaspik** [comment]
Closing for no response. You are now debugging this on SO, but I don't think without more info from your side you will be able to get help from someone else. Good luck!
