### ISSUE TITLE
Animate Sending From Textfield into Chat

### ISSUE THREAD

**Issue by mlyongardiner** [MessageKit/MessageKit#1557]
How can I create an Apple Messages-like sending animation where the user presses a send button and the chat animates from the TextField into the Chat? Any tips welcome, thanks!!

**Environment**
What version of MessageKit are you using?
3.5
What version of iOS are you running on?
14.3
What version of Swift are you running on?
Swift 5
What device(s) are you testing on? Are these simulators?
iPhone 12Pro, real device and simulator

**Comment by martinpucik** [comment]
Hey @mlyongardiner, I guess you can achieve this by using [UIKit dynamics](https://www.objc.io/issues/5-ios7/collection-views-and-uidynamics) ?
I think you'll have more success with getting tips on how to implement that on Google/StackOverflow tho :-/
