### ISSUE TITLE
Send Button Size

### ISSUE THREAD

**Issue by phil16727** [MessageKit/MessageKit#1559]
Hi, 
I am playing around with the example. 
If I set the title to Something else then "Send"  the text ist not displayed properly.

```
 func configureMessageInputBar() {
        messageInputBar.delegate = self
        messageInputBar.sendButton.title = "LongWord"
        messageInputBar.sendButton.sizeToFit()
        messageInputBar.inputTextView.tintColor = .primaryColor
        messageInputBar.sendButton.setTitleColor(.primaryColor, for: .normal)
        messageInputBar.sendButton.setTitleColor(
            UIColor.primaryColor.withAlphaComponent(0.3),
            for: .highlighted
        )
    }
```

I added "SizeToFit" but this didn't change the Button Size!
Any Ideas?

**Comment by Kaspik** [comment]
That's not a question for this library but for https://github.com/nathantannar4/InputBarAccessoryView - please refer to example projects there.
