### ISSUE TITLE
Delegate func typingIndicatorViewSize(...) is not called when implemented

### ISSUE THREAD

**Issue by julianiaccopucci** [MessageKit/MessageKit#1562]
Describe the bug
The func typingIndicatorViewSize(...) delegate function is not called when implemented.

Environment

What version of MessageKit are you using? 3.5.1
What version of iOS are you running on? iOS 14
What version of Swift are you running on? 5
What device(s) are you testing on? Are these simulators? Simulator
Is the issue you're experiencing reproducible in the example app? yes

Additional context
This method is declared in the protocol but not used by the delegate at any time.

**Comment by Kaspik** [comment]
Are you sure about MessageKit 2.5.1?

**Comment by julianiaccopucci** [comment]
> Are you sure about MessageKit 2.5.1?

Sorry a type. Updated.

**Comment by Kaspik** [comment]
I'm not sure what you mean by `This method is declared in the protocol but not used by the delegate at any time.`?

Did you implement `MessagesLayoutDelegate` and `func typingIndicatorViewSize(in messagesCollectionView: MessagesCollectionView) -> CGSize` on your own? Or do you use the default implementation from here? https://github.com/MessageKit/MessageKit/blob/40442dcaefeb5991721829a27d660d23d28b9000/Sources/Protocols/MessagesLayoutDelegate.swift#L137

**Comment by julianiaccopucci** [comment]
> I'm not sure what you mean by `This method is declared in the protocol but not used by the delegate at any time.`?
> 
> Did you implement `MessagesLayoutDelegate` and `func typingIndicatorViewSize(in messagesCollectionView: MessagesCollectionView) -> CGSize` on your own? Or do you use the default implementation from here?
> 
> https://github.com/MessageKit/MessageKit/blob/40442dcaefeb5991721829a27d660d23d28b9000/Sources/Protocols/MessagesLayoutDelegate.swift#L137

Three things:
- When setting the delegate and implementing the function, the function is not called
- When not implementing the delegate or function, the default implementation is never called
- When looking at the library, the function is never used, or in other words, not used at any time by the library to calculate the TypingIndicator size. The size is calculated by the class TypingCellSizeCalculator and it doesn't take into account the delegate at anytime. Actually the hight is hard-coded at 62

**Comment by Kaspik** [comment]
Coool, thanks, will take a look. :)
