### ISSUE TITLE
CocoaPods 1.10.1 - Swift/Xcode 12.2 - "Resources -> Assets.xcassets" missing target membership for Framework

### ISSUE THREAD

**Issue by ashokds** [MessageKit/MessageKit#1564]
**Describe the bug**
Using MessageKit pod with Cocoapds v1.10.1 based swift project on Xcode12.2 results in following error:

```
Fatal error: MessageKit: Could not load the color asset.: file MessageKit/UIColor+Extensions.swift, line 32
```

Using `MessageKit v3.5.1`

**To Reproduce**
Originally it was reported at: https://github.com/docusign/native-ios-sdk/issues/65 by https://github.com/tutucmarin

Here is the [project link](https://github.com/tutucmarin/DocuSign-issue.git) that could help with the reproducing it at your end.

How to replicate the issue with MessageKit:

- Make sure the DocuSign and MessageKit pods are installed
- In AppDelegate, uncomment line number 20 (`DSMManager.setup()`)
- Run the app

**Alternative repro steps**

Also, it can be reproduced by other steps (requires some changes to MessageBox files)

- A: Add public interface to TypingBubble that usages the `UIColor+Extension`.
```
// In `TypingBubble.swift` add a public static function.
    public static func backgroundColor() -> UIColor {
        .incomingMessageBackground
    }
```

- B: Edit `AppDelegate` in [project-link](https://github.com/tutucmarin/DocuSign-issue.git):
```
// In AppDelegate.swift, invoke backgroundColor() 
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        
        FeatureFlagging.config()
        
        let incomingMessageBackground : UIColor = TypingBubble.backgroundColor()
        print(incomingMessageBackground)
        
        // DSMManager.setup()

        return true
    }
```

- C: Run to notice `Fatal Error: ...`

**Expected behavior**

- No `Fatal Error: ... ` related to accessing background color assets. 
- Asset should be included in the installed pod.

**Screenshots**

For the `Cocoapods v1.10.1`, screenshot from Xcode 12.2.
<img width="1122" alt="MessageKit-Target-Membership-missing" src="https://user-images.githubusercontent.com/17131511/112875675-5798b400-9079-11eb-8260-f459cb6de24e.png">

**Environment**
- What version of MessageKit are you using?
3.5.1
- What version of iOS are you running on? 
13.6
- What version of Swift are you running on?
5.0
- What device(s) are you testing on? Are these simulators?
Simulator.
- Is the issue you're experiencing reproducible in the example app? 
Yes.

**Additional context**

Podfile.lock
```
  - MessageKit (3.5.1):
    - InputBarAccessoryView (~> 5.3.0)
```

**Comment by Kaspik** [comment]
Seems like a regression merged in 6 months ago. Resources are still correct way: https://github.com/CocoaPods/CocoaPods/issues/5192

One note from me - if possible, switch to SPM. CocoaPods are slowly dying and there is still no support for Apple Silicon or any update related to it. :)

**Comment by ashokds** [comment]
Thanks for the information @Kaspik ,
Yes, planning to move to SPM in coming months.
