### ISSUE TITLE
refresh control lag & reload data 100% CPU usage

### ISSUE THREAD

**Issue by IrelDev** [MessageKit/MessageKit#1568]
Every time I try to load more messages with pull-to-refresh & reload data, there is a small ui blocking delay that takes up to 100% of the CPU power.

I didn't do anything inside messages display delegate or so and my loadMoreMessages function is done asynchronously so what exactly could be the problem?

## **I Tried**:
- insertSections(at:) instead of reloadDataAndKeepContentOffset and got the same result
- Replace loadMoreMessages with default MockSocket code and got the same result
- Instruments app led to UICollectionView -> layoutSubviews but I couldn't find anything that could resolve my issue
---
- What version of MessageKit are you using? - 3.6.0
- What version of iOS are you running on? - iOS 14.4
- What version of Swift are you running on? - Swift 5
- What device(s) are you testing on? Are these simulators? - Real devices, iPhone 11 + iPhone 6s
- Is the issue you're experiencing reproducible in the example app? - Nope

**Comment by Kaspik** [comment]
Can you create MVP app for us to download and test?

**Comment by IrelDev** [comment]
For some reason, removing ```messagesCollectionView.contentInsetAdjustmentBehavior = .never``` resolved an issue for me  :)

**Comment by IrelDev** [comment]
in addition, don't put CoreData calls or any other heavy task in currentSendrer or isFromCurrentSender()
