### ISSUE TITLE
Create AudioMessageCell with Data downloaded from network

### ISSUE THREAD

**Issue by IrelDev** [MessageKit/MessageKit#1571]
I want to download & play base64 encoded voice message from the remote server and i wonder what i should do to use AudioMessageCell with data that needs some transformation? Is there any example of that?

So, what method should be used for voice message network request?
What method is intended for initializing AVAudioPlayer from data? configureAudioCell from ChatAudioController probably?

## **I Tried**:
- Perform network request in `configureAudioCell` from MessagesDisplayDelegate, but it does not have any IndexPath as a parameter so i can't load anything to or from data array
---
Should i create a custom cell that have some `downloadIfNeeded` method?
Should i subclass AudioMessageCell?
Maybe, ChatAudioController is the key? 

- What version of MessageKit are you using? - 3.6.0
- What version of iOS are you running on? - iOS 14.4
- What version of Swift are you running on? - Swift 5

**I'm sorry if this is a duplicate but i could not find any useful information or proper example**

**Comment by martinpucik** [comment]
@IrelDev you could use `func didTapPlayButton(in cell: AudioMessageCell)` from `MessageCellDelegate` :)
