### ISSUE TITLE
Podspec should use `resource_bundles`, not `resources` (`resources` causes assets to be clobbered when static linking is enabled)

### ISSUE THREAD

**Issue by Westacular** [MessageKit/MessageKit#1573]
**Describe the bug**

#1565 reverted #1460, switching the podspec back to using 'resources' instead of 'resource_bundles'.

This is bad choice. The motivation to do so (from #1564) is based on a misunderstanding of a bug caused by a separate framework. Reverting the change creates issues for anyone using the static-linked frameworks option in Cocoapods (e.g. by specifying `use_frameworks! :linkage => :static` in their Podfile)

What happens in those scenarios, loosely speaking:

1. The pods are built as separate `.framework`s
2. These frameworks are statically linked into the main binary for the app
3. The resources from the `.frameworks` are copied into the main app bundle

Which means that _any pod_ which specifies `resources` is liable to have those resources clobber or be clobbered by resources from another pod or the main app target. Asset catalogs, which are always compiled to a file named `Assets.car`, are particularly at risk as they're basically guaranteed to clash and clobber each other.

The solution — and the recommended approach by Cocoapods maintainers is to use `resource_bundles` (see discussion at https://github.com/CocoaPods/CocoaPods/issues/8431 — and also note the many of linked issues from other projects where they're switching to use `resource_bundles`) — , in exactly the way MessageKit was doing prior to #1565, and also in versions 3.1.0 and earlier. By using a nested resource bundle, what happens is:

For step 1 above: Xcode builds a framework containing a nested resource bundle containing the asset catalog: `.../MessageKit.framework/MessageKit.bundle/Assets.car`
For step 3 above: The nested resource bundle is copied to the main app bundle: `Whatever.app/MessageKit.bundle/Assets.car`

**Aside:**
The logic of

a. Find the bundle for a class from this pod
b. Find a nested bundle named `MessageKit.bundle` within that bundle
c. Load all resources from _that_ bundle

works in both the statically and dynamically linked scenarios because in both cases `MessageKit.bundle` winds up nested directly inside the same bundle that contains the compiled code for the class (i.e., `MessageKit.framework` for the dynamic case, and the main app bundle for the static case).

**Meanwhile:**

1. There are many reasons to favour using `:linkage => :static` with Cocoapods, and some scenarios where you are effectively forced to do so.
2. SPM also prefers static linking, and what it's doing under the covers for packaging resources is the same behaviour as Cocoapods does when using `resource_bundles` and static linking — SPM just hides that behind some magical `Bundle.module` code-gen.
3. SPM still comes with some significant limitations (notably: targets cannot contain a mix of objc and swift) that prevent some frameworks from adopting it — so Cocoapods isn't dead yet.

**Regarding issue #1564 reported by @ashokds (and the [original downstream issue](https://github.com/docusign/native-ios-sdk/issues/65)):**

- The fact that MessageKit's `Assets.xcassets` is not a member of the MessageKit framework target is by design, for reasons described above. (It's a member of the `MessageKit-MessageKit` target, which gets built into the `MessageKit.bundle` that Cocoapods build scripts later nest inside `MessageKit.framework`)
- The reported issue does _not_ occur for me using the "Alternative repro steps".
- If you run without calling `DSMManager.setup()`, everything works.
- If you call something to trigger loading a resource from `MessageKit.bundle` _prior_ to calling `DSMManager.setup()`, everything works.
- It seems that the _only_ scenario where this problem occurs is when you call `DSMManager.setup()` _before_ loading any resource from `MessageKit.bundle`.
- I suspect that the real issue is that when `DSMManager.setup()` is called, the DocuSign framework swizzles something that in turn breaks certain bundle/resource loading scenarios. (I can't easily confirm this, however, because that framework is not open source.)

**Comment by Kaspik** [comment]
Re: Last part of the message - the issue happens also if you use the MVP provided [here](https://github.com/tutucmarin/DocuSign-issue.git). When debugging this MVP, I wasn't able to get the resources load at all.

It's little bit sad to see that CocoaPods issue is still open after more than 2 years.

Feel free to open a PR that fixes this and will work for both / all cases and thanks for the detailed issue for everyone else.

PS: What do you mean SPM target can't contain mix of Obj-C and Swift? We use SPM in our Obj-C + Swift project without any issue for a year+.

**Comment by wzio** [comment]
For now we use this workaround in Podfile
```
#due to bug for cocoapod https://github.com/CocoaPods/CocoaPods/issues/8431
dynamic_frameworks = ["MessageKit", "InputBarAccessoryView"]

pre_install do |installer|
  installer.pod_targets.each do |pod|
    if !dynamic_frameworks.include?(pod.name) and !pod.build_as_static_framework?
      def pod.build_as_static_framework?
        true
      end
      def pod.build_as_dynamic_framework?
        false
      end
    end
  end
end
```
so we can use MessageKit with dynamic framework while other pods with static framework

**Comment by wzio** [comment]
> Re:
 PS: What do you mean SPM target can't contain mix of Obj-C and Swift? We use SPM in our Obj-C + Swift project without any issue for a year+.

Maybe He means that in Obj-C and swift cannot mix in a single framework when using SPM

**Comment by Kaspik** [comment]
CocoaPods integration is deprecated and will be removed with upcoming 4.0.0 release.
