### ISSUE TITLE
How to show multiple files on chat screen ?

### ISSUE THREAD

**Issue by janeshsutharios** [MessageKit/MessageKit#1574]
Hey !!
Thanks for rock solid Library.
I just wanted to know how can i integrate multiple file on Chat screen.

For example :
 ```
  var kind: MessageKind {
        if files?.count == 0 || files == nil {
        return .text(text ?? "")
        } else {
            let mediaItem = ImageMediaItem(imageURL: URL(string: files!.first!.url!)!)
            return .photo(mediaItem)
        }
    }

```
So in my case `files` is array of image object, & currently i am only able to use first object of image, instead of all images.

**Comment by Kaspik** [comment]
You will probably need to create custom cell that will accept all files. :)

**Comment by janeshsutharios** [comment]
> You will probably need to create custom cell that will accept all files. :)

@Kaspik so `messagesCollectionView.register(CustomCell.self)` as in `AdvancedExampleViewController.swift` should create similar of it ?
