### ISSUE TITLE
MessageCollectionView scrolls down when hiding keyboard at latest message position

### ISSUE THREAD

**Issue by Linkadi98** [MessageKit/MessageKit#1575]
**Describe the bug**
At postion of latest message cell, when hides keyboard the collectionView scrolls down itself with distance equal to height of keyboard, if I add a tap gesture to collectionView to hide keyboard when tap on it.

**To Reproduce**
Add a tap gesture on collectionView
```swift
let tap = UITapGestureRecognizer(target: self, action: #selector(dismissKeyboardOnTap))
messagesCollectionView.addGestureRecognizer(tap)
```
Hide keyboard 

```swift
@objc private func dismissKeyboardOnTap() {
        messageInputBar.inputTextView.resignFirstResponder()        
}
```

**My attemp to fix**

I observed `contentOffset.y` of collectionView and I saw a weird behavior of it. At the latest message postion, when `contentInset.bottom` of collectionView changed, the `contentOffset.y` changed to, after that, the `contentOffset.y` continously changed with the code: 
```swift
if maintainPositionOnKeyboardFrameChanged && differenceOfBottomInset != 0 {
            let contentOffset = CGPoint(x: messagesCollectionView.contentOffset.x, y: messagesCollectionView.contentOffset.y + differenceOfBottomInset)
            guard contentOffset.y <= messagesCollectionView.contentSize.height else {
                return
            }
            messagesCollectionView.contentOffset = contentOffset
        }
```
It meant after `contentInset.bottom` changed, `contentOffset.y` changed to the value which was exactly equal to the value `contentOffset.y` of `contentOffset` calculated in the block code above. Then the `contentOffset.y` changed again, meant that `contentOffset.y` changed twice at this postion.

So I made an early exit to prevent this bug

```swift
let offsetYBeforeChangeBottomInset = messagesCollectionView.contentOffset.y
messageCollectionViewBottomInset = newBottomInset
let offsetYAfterChangeBottomInset = messagesCollectionView.contentOffset.y
        
// make sure changing content bottom inset will not effect to changing content offset y
guard offsetYBeforeChangeBottomInset == offsetYAfterChangeBottomInset else { return }
```

Bug is gone.

**Environment**
- What version of MessageKit are you using: latest
- What version of iOS are you running on: iOS 14.1
- What version of Swift are you running on: 5.3.1
- What device(s) are you testing on: iPhone 11. Are these simulators? Yes
- Is the issue you're experiencing reproducible in the example app? Yes

**Comment by pbogdanv** [comment]
I have been looking for a solution for a long time, only this code works great:


```
private func handleKeyboardDidChangeState(_ notification: Notification) {
        guard !isMessagesControllerBeingDismissed else { return }

        guard let keyboardStartFrameInScreenCoords = notification.userInfo?[UIResponder.keyboardFrameBeginUserInfoKey] as? CGRect else { return }
        guard !keyboardStartFrameInScreenCoords.isEmpty || UIDevice.current.userInterfaceIdiom != .pad else {
            return
        }

        guard self.presentedViewController == nil else {
            return
        }

        guard let keyboardEndFrameInScreenCoords = notification.userInfo?[UIResponder.keyboardFrameEndUserInfoKey] as? CGRect else { return }
        let keyboardEndFrame = view.convert(keyboardEndFrameInScreenCoords, from: view.window)
        
        let newBottomInset = requiredScrollViewBottomInset(forKeyboardFrame: keyboardEndFrame)
        let differenceOfBottomInset = newBottomInset - messageCollectionViewBottomInset
        
        if maintainPositionOnKeyboardFrameChanged && differenceOfBottomInset != 0 {
            let contentOffset = CGPoint(x: messagesCollectionView.contentOffset.x, y: messagesCollectionView.contentOffset.y + differenceOfBottomInset)
            messagesCollectionView.setContentOffset(contentOffset, animated: false)
        }
        
        messageCollectionViewBottomInset = newBottomInset
    }

```

**Comment by tomaskorfant** [comment]
> I have been looking for a solution for a long time, only this code works great:
> 
> ```
> private func handleKeyboardDidChangeState(_ notification: Notification) {
>         guard !isMessagesControllerBeingDismissed else { return }
> 
>         guard let keyboardStartFrameInScreenCoords = notification.userInfo?[UIResponder.keyboardFrameBeginUserInfoKey] as? CGRect else { return }
>         guard !keyboardStartFrameInScreenCoords.isEmpty || UIDevice.current.userInterfaceIdiom != .pad else {
>             return
>         }
> 
>         guard self.presentedViewController == nil else {
>             return
>         }
> 
>         guard let keyboardEndFrameInScreenCoords = notification.userInfo?[UIResponder.keyboardFrameEndUserInfoKey] as? CGRect else { return }
>         let keyboardEndFrame = view.convert(keyboardEndFrameInScreenCoords, from: view.window)
>         
>         let newBottomInset = requiredScrollViewBottomInset(forKeyboardFrame: keyboardEndFrame)
>         let differenceOfBottomInset = newBottomInset - messageCollectionViewBottomInset
>         
>         if maintainPositionOnKeyboardFrameChanged && differenceOfBottomInset != 0 {
>             let contentOffset = CGPoint(x: messagesCollectionView.contentOffset.x, y: messagesCollectionView.contentOffset.y + differenceOfBottomInset)
>             messagesCollectionView.setContentOffset(contentOffset, animated: false)
>         }
>         
>         messageCollectionViewBottomInset = newBottomInset
>     }
> ```

Hi...it is also working for me....I had similar problem with overlapping last message by keyboard. @pbogdanv  will you create pull request for this issue?

**Comment by pbogdanv** [comment]
I change it local
