### ISSUE TITLE
Memoji keyboard overlaps screen

### ISSUE THREAD

**Issue by varxogre** [MessageKit/MessageKit#1584]
**Describe the bug**
When you open a memoji menu, the UIKeyboardMediaServiceRemoteViewController covers the entire screen, preventing the user from interacting with the rest of the screen. Any ideas on how to avoid this?
<img width="800" alt="Снимок экрана 2021-05-18 в 14 20 31" src="https://user-images.githubusercontent.com/63405341/118643641-7ef03f80-b7e5-11eb-9134-1ed62502ca77.png">
![Simulator Screen Shot - iPhone 12 - 2021-05-18 at 14 20 41](https://user-images.githubusercontent.com/63405341/118643660-86174d80-b7e5-11eb-87eb-72c1e57057d1.png)

**Environment**

What version of MessageKit are you using: latest
What version of iOS are you running on: iOS 14.4
What version of Swift are you running on: 5.3.1
What device(s) are you testing on: iPhone 12. Are these simulators? Yes
Is the issue you're experiencing reproducible in the example app? Yes

**Comment by martinpucik** [comment]
This looks like an iOS issue? It blocks the whole screen in any other application I tried. I'd suggest to file a feedback with Apple.
