### ISSUE TITLE
Background color of messages times (swipe view)

### ISSUE THREAD

**Issue by fabdurso** [MessageKit/MessageKit#1585]
Thanks again for the amazing library!

I just added `showMessageTimestampOnSwipeLeft = true` (https://github.com/MessageKit/MessageKit/pull/1444) to the chat, and everything looks good.
When dark mode is on, I set the messages view background to a color that is not pure black and also the times color to blue:
```swift
messagesCollectionView.backgroundColor = #mycolor
messageInputBar.backgroundView.backgroundColor = #mycolor

func messageTimestampLabelAttributedText(for message: MessageType, at indexPath: IndexPath) -> NSAttributedString? {
  let attributes = [
    NSAttributedString.Key.foregroundColor: .blue
  ]
  //
  //
  //
}
```

So, when swiping to check the messages time, the result is

![colors](https://user-images.githubusercontent.com/7327521/118845863-b9013480-b8fe-11eb-9f7f-db5f9d875815.png)

Is there a way to also set the background color of the view containing the messages times?
Or to just set its color to be the same as `messagesCollectionView.backgroundColor`? @Kaspik @amirpirzad @martinpucik 

Thanks!

**Comment by fabdurso** [comment]
@Kaspik @amirpirzad @martinpucik is this supposed to work like that?

**Comment by amirpirzad** [comment]
Hi, My apologies for the delayed response.
message time container is view of your controller

`view.backgroundColor = AnyColor`

it's ok or do you want more customization?
