### ISSUE TITLE
Adding multiple lines to input bar causes textbox to grow over messages

### ISSUE THREAD

**Issue by Telexx** [MessageKit/MessageKit#1586]
As you can see below typing a multi line message causes the bottom messages to be hidden.

Is there a way of making the nessagescollectionview shrink therefore keeping the bottom most messages visible?

![image](https://user-images.githubusercontent.com/5538471/118986782-8d6e6080-b977-11eb-9af8-346315a22920.png)

**Comment by erwanmace** [comment]
Was this ever fixed. I am still seeing this issue

**Comment by martinpucik** [comment]
This is fixed on 4.0.0 branch. Please make sure `maintainPositionOnInputBarHeightChanged` is set to `false` if you want to keep latest messages visible when inputTextView changes height
