### ISSUE TITLE
How to download async metadata for link preview

### ISSUE THREAD

**Issue by PiotrBogus** [MessageKit/MessageKit#1587]
Hi,
I would like to use link preview cell but i don't see inside example how do you download async website metadata to create LinkItem object. Your example just create static cell from given inside example data. This solution is a little bit useless w/o async download.

Best regards,
Piotr

**Comment by fukemy** [comment]
yes u do it  by 2 ways below:
1. When populate data u call some function to get UIImage from network, then send this image using NotificationCenter, after get this image in Chat class, replace image when this cell is visible.
2. Create a copy of LinkPreviewMessage with some modify

**Comment by mmdock** [comment]
https://developer.apple.com/documentation/linkpresentation/lpmetadataprovider

for iOS 13+ use LinkPresentation framework to get the metadata, use the meta data to populate the LinkMessage, reload cell at that index.

A good guide:
https://www.raywenderlich.com/7565482-visually-rich-links-tutorial-for-ios-image-thumbnails

This guide mentions not to use LPLinkPreview in a tableview... that's probably smart.  So, just use the LPMetadataProvider to get the metadata and use it to fill in the data for the MessageKit built in cell.
