### ISSUE TITLE
How add other controller to MessageViewController?

### ISSUE THREAD

**Issue by CainLuo** [MessageKit/MessageKit#1589]
I am very sorry for mentioning an issues, how can I achieve the display of EmotionKeyboard in the figure below and other more page displays? I tried to modify the frame height of the messagesCollectionView, and I tried to update the Constraints of the messagesCollectionView, but it didn't work, the only way I didn't try was to use a separate UIViewController to addChild MessagesViewController, EmotionKeyboard, MoreViewController, is there a better way than this? Can I add it to the Example project?

What I hope for：
![1021622287382_ pic_hd](https://user-images.githubusercontent.com/8857291/120068646-4c332a80-c0b4-11eb-95dd-8c7109b4aba4.jpg)
![1031622287383_ pic_hd](https://user-images.githubusercontent.com/8857291/120068649-52c1a200-c0b4-11eb-9267-b3e778822c1c.jpg)

Current status：
<img width="473" alt="image" src="https://user-images.githubusercontent.com/8857291/120068660-6a992600-c0b4-11eb-82b6-42688d5932e8.png">

**Comment by fukemy** [comment]
did u tried to replace MessageViewController inputAccessoryView
```
open override var inputAccessoryView: UIView? {
        return messageInputBar
    }
```

**Comment by CainLuo** [comment]
> inputAccessoryView

@fukemy  Does this need to replace inputAccessoryView? I just want to show the more functional View similar to the one at the bottom of WeChat, but I don't know how to do it.

**Comment by fukemy** [comment]
the fastest way is create your view ( config instrisicHeight) and add into bottomStackView

**Comment by CainLuo** [comment]
> the fastest way is create your view ( config instrisicHeight) and add into bottomStackView

Have you tried the relevant example?
