### ISSUE TITLE
Edge insets are miscalculated for message bubbles with tails

### ISSUE THREAD

**Issue by cwalo** [MessageKit/MessageKit#159]
As @SD10 mentioned, insets are calculated from the edge of the frame, not taking the tail into account.

![screen shot 2017-09-21 at 4 31 13 pm](https://user-images.githubusercontent.com/2067455/30819844-b67e31ce-a1e5-11e7-8af6-9d67318654b8.png)

**Comment by SD10** [comment]
This is an easy fix I just don't know the best way to do it. 
I could reverse the left & right inset values behind the scenes but that's sort of undefined behavior.
We could add a `incomingMessageLabelInset` & `outgoingMessageLabel` inset property. 😐
We could move `messageLabelInsets` to a method... more methods 😐
