### ISSUE TITLE
How to dump data for autocompletemanager.tableview in Autocompletemanager

### ISSUE THREAD

**Issue by Duongcn912** [MessageKit/MessageKit#1590]
i want to get data from api when user fills @ prefix. For example, when the user enters @name, the application will call the API to get a list of people named "name". So how can i dump data into autocompletemanager.tableview. Currently I only see the data source of the tableview as an available array. And I can't dump data after call API on it

**Comment by Duongcn912** [comment]
> i want to get data from api when user fills @ prefix. For example, when the user enters @name, the application will call the API to get a list of people named "name". So how can i dump data into autocompletemanager.tableview. Currently I only see the data source of the tableview as an available array. And I can't dump data after call API on it

**Comment by fukemy** [comment]
AutocompleteManager -> reloadData()
