### ISSUE TITLE
Adding Multiple Custom Cells to cellForItemAt

### ISSUE THREAD

**Issue by Joseph-Sam** [MessageKit/MessageKit#1591]
I have seen two other questions: [1007](https://github.com/MessageKit/MessageKit/issues/1007) and [1454](https://github.com/MessageKit/MessageKit/issues/1454) for this topic but I wasn't able to follow either. I have one custom cell fully working but now am having an issue adding a second custom cell. I followed the same process (created class for custom cell, added it to the source data for the messages, and registered it in the viewDidLoad.

My issue is how to determine which one should be displayed in the cellForItemAt function for the collectionView. The format for determining what _kind_ of custom cell to use eludes me. I only have the method to determine it should be a custom cell generally which is given in the example: 
`if case .custom = message.kind { }`

When I try to determine which one is used by the message.kind == ..... I get 
Binary operator '==' cannot be applied to two 'MessageKind' operands

**Comment by fukemy** [comment]
if case .custom(let data) = message.kind { 
  if let _ = data as? [MULTIIMAGE type]{} 
  if let _ = data as? [PDF type]{}  
}

u can get cell kind like that

**Comment by Joseph-Sam** [comment]
Thank you so much!!!

**Comment by Joseph-Sam** [comment]
Hi again… 

I have another question if you’re able to help.

I’m not able to set the side of the custom cell I’m returning. Should that be done in the custom MessageSizeCalculator, where the custom cell is created and contents filled, where the cell is returned in the collection view, or somewhere else?

I see this answer on GitHub: You need to write the layout code for how the cell will be aligned. Cells always span the width of the screen, we just use the MessageCollectionViewFlowAttributes to align it based on isCurrentCenter.

However, I don’t know where to do this. 

As of now, my custom cells are returning but all are in the center of the screen no matter what size I hardcode in the SizeCalculator.

Thanks again for any help you’re able to provide.

**Comment by fukemy** [comment]
Hi, sry for long time reply, you can see logic of textmessagecell or linkmessagecell to understand the logic of calculating custom cell size
