### ISSUE TITLE
fatal error: avatar position horizontal.natural needs to be resolved. message kit

### ISSUE THREAD

**Issue by dan085** [MessageKit/MessageKit#1595]
**Describe the bug**

when send a message and receive show this issue

**To Reproduce**
Steps/code to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Environment**
- What version of MessageKit are you using?3.6.1
- What version of iOS are you running on? ios 14
- What version of Swift are you running on? 5
- What device(s) are you testing on? Are these simulators? iphone se 2020
- Is the issue you're experiencing reproducible in the example app?

**Additional context**

**Comment by martinpucik** [comment]
@dverdugo85 could you please try to reproduce it in our example project or post some of your code to help debug this issue :)
