### ISSUE TITLE
Issue when reload list from cache UserDefaults

### ISSUE THREAD

**Issue by dan085** [MessageKit/MessageKit#1596]
**Is your feature request related to a problem? Please describe.**

```
func insertMessage(_ message: MockMessage) {
        messagesCollectionView.performBatchUpdates({
            messageList.append(message)
        }, completion: { [weak self] _ in
            if self?.isLastSectionVisible() == true {
                self?.messagesCollectionView.scrollToBottom(animated: true)
            }
        })
}
```

not work when reload chat from cache, when  enter for first instance work  the typing and show new message, when clise the uiviewcontroller and  enter again the same user typing work but when arrive new message not show this, only save in cache... 

```
   func  get_chat_friend_new(_ KEY_MOBILE :String) ->[MockMessage]{
       print("get_chat_friend_new")
        print(KEY_MOBILE)
        if let placesData = mUserDefaults!.object(forKey: KEY_MOBILE) as? Data {
            if let placesArray = try? NSKeyedUnarchiver.unarchiveTopLevelObjectWithData(placesData) as? [MockMessage] {
                return placesArray
            }else{
                return [MockMessage]()
            }
                   
        }else{
            return [MockMessage]()
        }
    }
```

the  typing not desappear and not show new message

this function not work 

```
    private func performUpdatesForTypingIndicatorVisability(at section: Int) {
        if isTypingIndicatorHidden {
            messagesCollectionView.deleteSections([section - 1])
        } else {
            messagesCollectionView.insertSections([section])
        }
    }
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by martinpucik** [comment]
Hey @dan085 it's a bit hard to figure out what could be the issue from the snippets you added. Could you please try to reproduce the issue in our example project? If it's reproducible, please reopen this issue. Thanks!
