### ISSUE TITLE
Present messageKit in half page

### ISSUE THREAD

**Issue by behzad94** [MessageKit/MessageKit#1597]
I am trying to present the chat viewController on half-page. But MessageKit has a weird bug. Which displays messages outside the ViewController.

I put parts of the code and two weird screenshots here.

**Use this StackOverflow link to see screenshots.**
https://stackoverflow.com/questions/68261602/present-messagekit-in-half-page

```swift
extension UIViewController {
    func embed(_ viewController:UIViewController, inView view:UIView){
        viewController.willMove(toParent: self)
        viewController.view.frame = view.bounds
        view.addSubview(viewController.view)
        self.addChild(viewController)
//        self.view.autoresizingMask = [.flexibleWidth, .flexibleHeight]
//        self.view.clipsToBounds = true
        viewController.didMove(toParent: self)
    }
}
```

**Comment by Osydon** [comment]
I'm having the same issue. 

Upon scrolling down, messages overflow beyond the childView controller's boundaries and obstruct the parent view's UI. Hoping the team can help. Thanks

**Comment by Osydon** [comment]
@behzad94 I'm still struggling trying to figure out this issue. Have you managed to overcome it or is it a bug in messageKit? thanks

**Comment by justdan0227** [comment]
I also have this issue.  Any thoughts?

**Comment by Osydon** [comment]
Has anyone been able to figure out the issue on this thread? I can't seem to fix it.

**Comment by martinpucik** [comment]
Please refer to `MessageSubviewContainerViewController` in our Example project. I can't reproduce this issue in there
