### ISSUE TITLE
Community maintenance fork of legacy repository

### ISSUE THREAD

**Issue by chrisballinger** [MessageKit/MessageKit#16]
I think we need a maintenance-only "LTS" version of JSQMessagesViewController here: https://github.com/MessageKit/JSQMessagesViewController

The current repository in the MessageKit org is a fork of the original, but I believe @jessesquires should move ownership of the original upstream repo to this organization, and grant some of us the ability to push hotfix releases to CocoaPods.

There are some significant UI issues with JSQMessagesViewController in iOS 11, which means there are 40,000+ apps that will suddenly become broken without a clear path forward. I understand Jesse's reasons for deprecating the project, but I think the community needs to be given a chance to maintain the original code while the "next generation" replacement is stabilizing.

I'd like to step forward as a maintainer of the legacy code. I'm the primary maintainer of a number of other popular open source libraries like CocoaAsyncSocket, XMPPFramework, and KissXML. My goal as a maintainer would be to merge critical bug fixes only, and maintain clear warnings that the project is deprecated.

If we work together we can make this transition a lot easier for everyone.

**Comment by SD10** [comment]
Hey @chrisballinger, thanks for raising this issue.

Regarding ownership of JSQMessagesViewController, that's something only Jesse can decide.

I'm not totally against this but I do have some concerns with encouraging the use of JSQMVC instead of focusing the effort on building the new project. I also think having two active repos could confuse people as to which project they're supposed to use. 

I need some more time to formalize my opinion on this.

**Comment by chrisballinger** [comment]
My goal would be to make it very clear where future development should be focused. We could even add `DEPRECATED_MSG_ATTRIBUTE` throughout the code to make it obvious. The timeline is just too short to expect 1) this library to be production ready and 2) apps able to migrate everything before iOS 11 is released. There is also a huge economic cost to migrating libraries. Albeit hyperbolic, if it takes the average app developer 100 hours to migrate at $100/hr, the 40,000+ apps using this library will cost $400,000,000.

I would definitely be ok with a firm maintenance window of 12 months or less, depending on the production-readiness timeline of the replacement. My main concern is giving developers a single place to go for fixes related to the upcoming iOS 11 release.

**Comment by jessesquires** [comment]
hey @chrisballinger -- i've added you to **jessesquires/JSQMessagesViewController** as a collaborator. you have push access. i can also give you ownership to publish pod updates. let me know if this is sufficient 😄

**Comment by chrisballinger** [comment]
@jessesquires Thanks man!

**Comment by SD10** [comment]
Thank you both 😃
