### ISSUE TITLE
Ability to look like FaceBook Comment List

### ISSUE THREAD

**Issue by justdan0227** [MessageKit/MessageKit#1602]
Is there a way that we could configure the framework to work like Facebook Comment where it shows that oldest at the top, and show x number allowing you to load more (somewhat opposite that of iMessage)

**Comment by justdan0227** [comment]
Does anyone have thoughts on this?

**Comment by justdan0227** [comment]
Bump?

**Comment by martinpucik** [comment]
@justdan0227 I'd say this could be accomplished today with either custom message cell or custom message footer view for the `Load more` button
