### ISSUE TITLE
When scrolling message collection,  Keyboard is scrolling but InputBarAccessoryView does not scroll.

### ISSUE THREAD

**Issue by nguyenquocdathcmus** [MessageKit/MessageKit#1604]
**Describe the bug**
When scrolling message collection,  Keyboard is scrolling but InputBarAccessoryView does not scroll in the MessageKit subview controller.

**To Reproduce**
- Step 1: Subview example
- Step 2: Press and hold when scrolling
![Simulator Screen Shot - iPhone 11 - 2021-07-23 at 13 49 09](https://user-images.githubusercontent.com/32430754/126756672-d2bf01dc-66f1-47db-8891-e248763e173f.png)
![Simulator Screen Shot - iPhone 11 - 2021-07-23 at 13 45 51](https://user-images.githubusercontent.com/32430754/126756766-5bffedf8-10c4-4ddc-8146-1eca61839297.png)

**Comment by nguyenquocdathcmus** [comment]
https://github.com/MessageKit/MessageKit/issues/1474

**Comment by Kaspik** [comment]
More than happy to review and approve a PR fixing this.
