### ISSUE TITLE
Should add Encryption label Text Bubble as first row like whatsapp

### ISSUE THREAD

**Issue by ZeeMughal892** [MessageKit/MessageKit#1606]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![New chat](https://user-images.githubusercontent.com/48951574/127402070-5a70bb81-8237-4953-8ae5-1f1925180250.png)

**Comment by mendimr** [comment]
You can achieve this by adding a custom cell and append it at the top of the conversation.
I think the ChatExample app can help you do that if you take a look at the (Someone left the conversation) cell in the Advanced Example.
<img width="390" alt="Screen Shot 2021-07-29 at 10 12 07 AM" src="https://user-images.githubusercontent.com/48059845/127457862-393973ab-9054-40b4-9ca6-f0f955e187bc.png">

Also see this guide so you know what to look for: https://github.com/MessageKit/MessageKit/blob/master/Documentation/CUSTOM_CELLS.md

**Comment by martinpucik** [comment]
I'd say this is a very specific feature to be in the library as it could be easily implemented with custom cells or header/footer views
