### ISSUE TITLE
Smooth animation when adding data to top of MessageCollectionView?

### ISSUE THREAD

**Issue by mikeusru** [MessageKit/MessageKit#1609]
Hi! I'm using MessageKit wrapped in a UIViewControllerRepresentable, similar implementation to the provided example. I implemented my messages loading using a UIRefreshControl as so: 
```
final class MessageSwiftUIVC: MessagesViewController {
     private let refreshControl = UIRefreshControl()
    //...
     override func viewDidLoad() {
        super.viewDidLoad()
        refreshControl.addTarget(self, action: #selector(didPullToRefresh(_:)), for: .valueChanged)
        messagesCollectionView.alwaysBounceVertical = true
        messagesCollectionView.refreshControl = refreshControl
    }

    @objc private func didPullToRefresh(_ sender: Any) {
        loadOlderMessages()
        DispatchQueue.main.async {
            self.refreshControl.endRefreshing()
        }
    }
//...
}
```

This works, the problem is the older messages are added abruptly, so it looks bad. I'd love for them either to get added above the view so users can scroll up to them, or at least to animate down. How can I do this?

Thanks in advance!

**Comment by bryan-vh** [comment]
@mikeusru I ended up using a UICollectionViewDiffableDataSource subclass to somewhat remedy this issue as it is able to animate the differences. Honestly it sucks there hasn't been a switch over to some sort of diffable data source in this library so you're pretty much forced to do it on your own :/

**Comment by e1block** [comment]
@bryan-vh Do you have some sample code you could share?
