### ISSUE TITLE
Cell top label needs more vertical space or ability to set dynamically 

### ISSUE THREAD

**Issue by cwalo** [MessageKit/MessageKit#161]
You'll see in the screenshot that in some cases, the `cellTopLabel` butts up right against the message bubble. I think exposing a method in `MessagesLayoutDelegate` to set the size would be ideal - similar to `headerViewSize`.

<img width="258" alt="screen shot 2017-09-25 at 2 19 21 pm" src="https://user-images.githubusercontent.com/2067455/30826624-d8de0e58-a1fc-11e7-8e97-8507d2642bc9.png">

**Comment by SD10** [comment]
We're going to have a slogan "We don't use properties but there's a method for everything"

**Comment by cwalo** [comment]
As @SD10 suggested, subclassing `MessagesCollectionViewLayout` and setting `cellTopLabelInsets` in `init()` gets the job done.

**Comment by SD10** [comment]
We'll fix this by adding the `UIEdgeInsets` as an associated value to the `LabelAlignment` enum. This will allow you to set any inset dynamically. We'll then be able to remove these properties from `MessagesCollectionViewFlowLayout.

**Comment by cwalo** [comment]
Resolved by #166
