### ISSUE TITLE
MessageInputBar appears in a strange position.

### ISSUE THREAD

**Issue by pa-mikiko-jinnouchi** [MessageKit/MessageKit#1612]
Open the mp4 file from MessageKit using QuickLook's QLViewController.

Swipe down to close the file, and the messageInputBar will disappear.
Press the Done button to close the file, and the messageInputBar will be displayed.

This happens in iOS 14.5, 13.7, but not in 12.2.

Can you please fix this?
Thank you for your consideration.🙇‍♂️

| iOS 12.2 | 13.7, 14.5 |
| - | - |
| ![１](https://user-images.githubusercontent.com/66453647/131100631-2072cb1e-0943-4125-8fe3-d058be3d682d.gif) | ![２](https://user-images.githubusercontent.com/66453647/131100696-78576201-920f-4a04-97c7-c598d2964c25.gif) |

MessageKit 3.6.1
iOS 14.5, 13.7
Apple Swift version 5.4
Real machines and simulators

**Comment by Kaspik** [comment]
Could you please create minimal project where we can reproduce this so I can debug it better? Or is it happening in some of our examples too?
