### ISSUE TITLE
Wrong Avatar Position

### ISSUE THREAD

**Issue by devuzan** [MessageKit/MessageKit#1615]
I couldn't find a solution in the quickstart, faq, or StackOverflow.

When built the following code below, with collectionViewLayout settings, it doesn't work in the way I expected it to. 

```swift
        layout?.setMessageOutgoingAvatarSize(CGSize(width: 30, height: 30))
        layout?.setMessageOutgoingAvatarPosition(.init(vertical: .messageLabelTop))
        layout?.setMessageOutgoingMessageTopLabelAlignment(LabelAlignment(textAlignment: .right, textInsets: UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 40)))
```

There are single and double message screenshots.

https://i.ibb.co/W57fSDB/singlemessage.png
https://i.ibb.co/qM3zJkb/doublemessage.png

I would like to anchor the avatar's top to the place next to the nickname top position (messageLabelTop). However, what the code does instead is placing the avatar's top next to the last message that is sent. It doesn't do this when one single message is only being sent. Everything is OK. But when we send several messages one after another it makes this problem.

How can I achieve this? Thank you in advance.

- MessageKit version: 3.6.1
- iOS Version: 12.1 ( and others.)
- Swift: 5.3.2
- Built on the simulator

**Comment by mendimr** [comment]
I'm not 100% sure but it looks like you're displaying the avatar only for the last message and then instructing it to stay at the top which is why you got the desired position on the first image but not on the second one.

If that is the case, you should reverse the logic and only show the avatar for the first message.

```
public func configureAvatarView(_ avatarView: AvatarView, for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) {
  if !isPreviousMessageSameSender(at: indexPath) && isNextMessageSameSender(at: indexPath) {
    // first message of the group
  } else if !isPreviousMessageSameSender(at: indexPath) && !isNextMessageSameSender(at: indexPath) {
    // first and last message of the group
  }
}
```

You should be able to find the isPreviousMessageSameSender isNextMessageSameSender logic on the ChatExample app

**Comment by martinpucik** [comment]
@devuzan please reopen this if the issue still persists
