### ISSUE TITLE
Message scrolls to top of screen when sent

### ISSUE THREAD

**Issue by mikeusru** [MessageKit/MessageKit#1619]
**Describe the bug**
After I add a message, the new message scrolls to the top of the screen.

**To Reproduce**
Steps/code to reproduce the behavior:

**Expected behavior**
Recent message should appear just above keyboard

**Screenshots**
[https://share.icloud.com/photos/0jEFkGWa1gmNCvGlcblVLPI8Q](url)

**Environment**
- What version of MessageKit are you using?
- 3.6.1
- What version of iOS are you running on?
- 14
- What version of Swift are you running on?
- 5
- What device(s) are you testing on? Are these simulators?
- iPhone 11
- Is the issue you're experiencing reproducible in the example app?
- I believe so, in the SwiftUI example

**Additional context**

**Comment by xpnewmedia** [comment]
any fix?

**Comment by mikeusru** [comment]
Still nothing…

**Comment by Redrum1983** [comment]
Hey brother will you help me clone my mom's phone?? Please it's for safety reasons?

**Comment by iosware** [comment]
I can observe same issue
![1619](https://user-images.githubusercontent.com/142815/165290390-154a3e98-052a-437d-bdc5-c50bcd5703b4.gif)

**Comment by martinpucik** [comment]
this should be fixed in 3.8.0 and on 4.0.0 branch
