### ISSUE TITLE
How do I inherit MessageViewController from BaseViewController ??

### ISSUE THREAD

**Issue by Awaisabid332** [MessageKit/MessageKit#1620]

**Comment by Kaspik** [comment]
What is `BaseViewController`?

**Comment by Awaisabid332** [comment]
mean some navigations and common functions in BaseViewController for every ViewController.

**Comment by Awaisabid332** [comment]
> What is `BaseViewController`?

mean some navigations and common functions in BaseViewController for every ViewController.
For example


class BaseViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    func navigationTitle(title: String) {
        self.title = title
    }
}

class ChatViewController: BaseViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        navigationTitle(title: "Chat")
    }
}

**Comment by mendimr** [comment]
Is this what you're trying to do:
```
class ChatViewController: BaseViewController, MessagesViewController {
  override func viewDidLoad() {
    messagesCollectionView = MessagesCollectionView(frame: view.frame, collectionViewLayout: MessagesCollectionViewFlowLayout())
    super.viewDidLoad()
    navigationTitle(title: "Chat")
  }
}
```

**Comment by Kaspik** [comment]
I'm not aware of any `BaseViewController` in MessageKit. You can subclass MessagesViewController which is UIViewController iirc. mendimr is right, you can do whatever you want - there is no plan to build something like that in MessageKit, so closing. :)

**Comment by Awaisabid332** [comment]
> Is this what you're trying to do:
> 
> ```
> class ChatViewController: BaseViewController, MessagesViewController {
>   override func viewDidLoad() {
>     messagesCollectionView = MessagesCollectionView(frame: view.frame, collectionViewLayout: MessagesCollectionViewFlowLayout())
>     super.viewDidLoad()
>     navigationTitle(title: "Chat")
>   }
> }
> ```

swift not allow multiple inherit.
