### ISSUE TITLE
Replied Chat Bubble like whatsapp

### ISSUE THREAD

**Issue by irmakcenker** [MessageKit/MessageKit#1623]
Hi, I would like to make chat bubbles which includes replied message information.
Is it possible to add a view in a message container view to show which message replied ? When I add a view, cell content size is not changing. I add a container view to InputBarAccessoryView's top stack view and it works fine but I could not find any solution for chat bubbles. I will appreciate if you share possible solutions. 

Thanks :)

**Comment by fukemy** [comment]
can you share some preview image that you want to make?

**Comment by martinpucik** [comment]
@irmakcenker please add a example screenshot for the reference :)

**Comment by erwanmace** [comment]
I think this is what @irmakcenker is referring to: a view inside the message referring to the original message which we are replying to. I am looking for the best approach to do this as well without rewriting custom cells for all message type.

![IMG_DC9C522E5E82-1](https://user-images.githubusercontent.com/8786380/213861065-3c6e87e9-1717-405d-89df-4d87728e9764.jpeg)

there is an existing discussion here ([issue 1690](https://github.com/MessageKit/MessageKit/issues/1690))
