### ISSUE TITLE
Hide keyboard when user Tap in messagesCollectionView (outside keyboard)

### ISSUE THREAD

**Issue by alopezhenquen** [MessageKit/MessageKit#1624]
I've been trying to add Tap gestures recognizers to messagesCollectionView, to hide the keyboard when pressed outside of it (as WhatssApp do). But MessagesViewController implements gestureRecognizerShouldBegin from UIGestureRecognizerDelegate and prevents it from recognize any gesture other than UIPanGestureRecognizer.

```swift
public func gestureRecognizerShouldBegin (_ gestureRecognizer: UIGestureRecognizer) -> Bool {
    guard let panGesture = gestureRecognizer as? UIPanGestureRecognizer else {
        return false
    }
    let velocity = panGesture.velocity (in: messagesCollectionView)
    return abs (velocity.x)> abs (velocity.y)
}
```

I would appreciate it if you made this function OPEN, to be able to overwrite it if necessary in my ChatViewController which inherits from MessagesViewController. I have already tried to include the library directly in my project, to be able to edit MessagesViewController, and everything is fine.

My example method would be like this:

```swift
override func gestureRecognizerShouldBegin (_ gestureRecognizer: UIGestureRecognizer) -> Bool {
    if let panGesture = gestureRecognizer as? UIPanGestureRecognizer {
        let velocity = panGesture.velocity (in: messagesCollectionView)
        return abs (velocity.x)> abs (velocity.y)
    }
    if (gestureRecognizer as? UITapGestureRecognizer) == myExampleTapGestureRecognizer {
        return true
    }
    return false
}
```

This then allows me to handle TAP gestures, and maintains the recognition of Pan gestures for keep default functionalities of messagesCollectionView.
Thank you! I await your considerations, good Work! Congrats!
Greetings

**Comment by Kaspik** [comment]
I would be happy to review a PR that makes this possible. :)

**Comment by alopezhenquen** [comment]
Thanks for your response. Changes made in PR #1638. Waiting for review. :)
