### ISSUE TITLE
Typing Bubble's Width Returns 0

### ISSUE THREAD

**Issue by mehmetbaykar** [MessageKit/MessageKit#1628]
LayoutSubViews function in [TypingBubble.swift](https://github.com/MessageKit/MessageKit/blob/master/Sources/Views/TypingBubble.swift) crashes when assigning frames with a NaN width.  To fix this problem add a width checker before lay-outing subviews by **guard bounds.width > 0 else { return}**

       
         open override func layoutSubviews() {
         super.layoutSubviews()
        
        // To maintain the iMessage like bubble the width:height ratio of the frame
        // must be close to 1.65
        
        guard bounds.width > 0 else { return} // add this in order to prevent NaN crashes
        
        let ratio = bounds.width / bounds.height
        let extraRightInset = bounds.width - 1.65/ratio*bounds.width // might return NaN value if the width is 0
        
        let tinyBubbleRadius: CGFloat = bounds.height / 6
        tinyBubble.frame = CGRect(x: 0,
                                  y: bounds.height - tinyBubbleRadius,
                                  width: tinyBubbleRadius,
                                  height: tinyBubbleRadius)
        
        let cornerBubbleRadius = tinyBubbleRadius * 2
        let offset: CGFloat = tinyBubbleRadius / 6
        cornerBubble.frame = CGRect(x: tinyBubbleRadius - offset,
                                    y: bounds.height - (1.5 * cornerBubbleRadius) + offset,
                                    width: cornerBubbleRadius,
                                    height: cornerBubbleRadius)
        
        let contentBubbleFrame = CGRect(x: tinyBubbleRadius + offset,
                              y: 0,
                              width: bounds.width - (tinyBubbleRadius + offset) - extraRightInset,
                              height: bounds.height - (tinyBubbleRadius + offset))
        let contentBubbleFrameCornerRadius = contentBubbleFrame.height / 2
        
        contentBubble.frame = contentBubbleFrame // Crash occurs
        ............`

**Comment by rushisangani** [comment]
I'm also facing this issue.

![Screenshot 2021-11-02 at 10 06 23 AM](https://user-images.githubusercontent.com/7363933/139787580-f7abfb92-e04d-4dfa-98b7-40af1733e809.png)

**Comment by Kaspik** [comment]
Would be more than happy to review a PR for this. :)

**Comment by Kaspik** [comment]
I guess fixed by https://github.com/MessageKit/MessageKit/pull/1645?

**Comment by mehmetbaykar** [comment]
Yes It has been fixed and merged by #1637

**Comment by Janneman84** [comment]
I found a way to trigger this crash in the example app, it's pretty easy:
- run example app
- open Advanced Example (2nd option)
- **immediately** scroll up a bit, half a screen should do it
- once _Typing..._ appears on the top bar quickly scroll to the bottom

Basically when the typing indicator is **first** shown while off screen, then if you scroll towards it you trigger the error.
