### ISSUE TITLE
inputBarAccessoryView looping when fetching on MessageKit installation

### ISSUE THREAD

**Issue by Camelot93** [MessageKit/MessageKit#1631]
Hello,

I am using SPM as a dependency manager for my Xcode project. When adding MessageKit package using the URL github.com/MessageKit/MessageKit, Xcode enters a fetching loop when trying to retrieve inputBarAccessoryView where it:

-Fetches inputBarAccessoryView
-resolve packages
-updates Messagekit
-clone inputBarAccessoryView
-remove inputBarAccessoryView

And repeats

the Error encountered during this process is
invalid custom path 'Sources' for target 'InputBarAccessoryView'

Environment Xcode
Dependency manager SPM
Version of MessaggeeKit that i am trying to get is the same as master

**Comment by Kaspik** [comment]
Did you try to remove derived data while having XCode closed etc?

**Comment by Camelot93** [comment]
@Kaspik  I tried it and it installed inputBarAccessoryView but  Xcode enters a fetching loop when trying too retrieve MessageKit this time

**Comment by Kaspik** [comment]
Not able to repro this as it works on our project normally the same as it does in example.
