### ISSUE TITLE
Dismissing the keyboard does not work properly

### ISSUE THREAD

**Issue by mehmetbaykar** [MessageKit/MessageKit#1633]
When dismissing the keyboard with swiping from top to bottom on the accessory view, the layout of the collection view changes. I believe it has to do with InputAccessoryView and [MessagesViewController-Keyboard](https://github.com/MessageKit/MessageKit/blob/master/Sources/Controllers/MessagesViewController%2BKeyboard.swift)

Please check the video attached.

https://user-images.githubusercontent.com/20362928/139854671-f117de7e-3d09-494f-a8e6-546b1568c3e4.mov

**Comment by mehmetbaykar** [comment]
@Kaspik  any update on that?

**Comment by mehmetbaykar** [comment]
Found the issue will make a PR.

**Comment by Kaspik** [comment]
How does it look with the PR you closed?

**Comment by mehmetbaykar** [comment]
Sorry. I realised that this PR has an extra commit that should've been. I will make a new PR when I can.
