### ISSUE TITLE
Leak at AttachmentManager CollectionView

### ISSUE THREAD

**Issue by enchtein** [MessageKit/MessageKit#1635]
**Describe the bug**
I try to implement AttachmentManager at my app and catch sight of leak while attaching image at collection cell.
You can see this at your helper project (Chat Example). Just run it. Go to Advanced Example vc and try to attach a few images. Please pay attention on memory used before you attach image and after. The most problem that even after sending attaches the memory isn't receive. And even view controller dismissed - memory not receive.

**Expected behavior**
I think leak consist on rendering image. ARC does not manager memory for Core Foundation

**Screenshots**
memory usage before add images:
<img width="1080" alt="1" src="https://user-images.githubusercontent.com/51451975/141022292-9ad8b3ae-87fa-428a-a63b-3c31d3940b93.png">

after image was added to collection:
<img width="1080" alt="2" src="https://user-images.githubusercontent.com/51451975/141022587-2d78ec08-48ed-4103-9114-8ffe57e32ea8.png">

after images was sent:
<img width="1080" alt="3" src="https://user-images.githubusercontent.com/51451975/141022344-9b09afd8-8828-4ae2-b437-ae43a24339e4.png">

after vc dismissed:
<img width="1080" alt="4" src="https://user-images.githubusercontent.com/51451975/141022364-a18be8f1-e5cf-4193-a675-535cb509b347.png">

- What version of Swift are you running on? 
12.5
- What device(s) are you testing on? Are these simulators?
It's manifests itself on simulators and I test on iPhone 8

**Comment by Kaspik** [comment]
Happy to review a PR that fixes / improves this!

**Comment by MuhtasimTanmoy** [comment]
Fix given at #1649. Kindly review.

**Comment by MuhtasimTanmoy** [comment]
Would like to have some clarifications regarding another related issue.

In `LaunchViewController` for opeing samples this snippet is used,

```swift
let viewController = BasicExampleViewController()
let detailViewController = NavigationController(rootViewController: viewController)
splitViewController?.showDetailViewController(detailViewController, sender: self)
```

When I am using `deint{ }` in  `BasicExampleViewController` it is not being called when I back press. Instead, when I relaunch `BasicExampleViewController` the previous one's `deint{ }` is called.

When I am replacing it with this snippet, 
```swift
let viewController = BasicExampleViewController()
navigationController?.pushViewController(viewController, animated: true)
```
`Deint{}` not being called when back pressed.

Is this default behavior for `SplitViewController` or `ARC` should have reclaimed memory on back pressed as an improvement?

**Comment by Kaspik** [comment]
I'm honestly not an expert in split views so can't help you here. :)
