### ISSUE TITLE
How to change y coordinate/margin of input bar button item?

### ISSUE THREAD

**Issue by ElrB** [MessageKit/MessageKit#1636]
![Screen Shot 2021-11-12 at 8 33 37 AM](https://user-images.githubusercontent.com/66596779/141422267-aa49ab03-0810-4f04-bcdd-684e61d36a90.png)

My attach and mic button appears to be slight out of line with the message input bar vertically. How can I change this, so the two buttons shift up a bit? If possible, please also tell me know how to shift them on the x-axis. Thank you.

**Comment by carlsondev** [comment]
I haven't experienced this and haven't tested this though but it might be a good idea to see if you can create your own constraints with the layout anchors (like centerXAnchor, centerYAnchor, leadingAnchor, etc).

**Comment by ElrB** [comment]
The app keeps crushing when setting centerYAnchor constraints with messages like; 

Thread 1: Exception: "Unable to activate constraint with anchors <NSLayoutYAxisAnchor:0x600001573840 \"InputBarAccessoryView.InputBarButtonItem:0x7ffcd77d9180.centerY\"> and <NSLayoutYAxisAnchor:0x600001573d40 \"InputBarAccessoryView.InputBarAccessoryView:0x7ffcd77d1fb0.centerY\"> because they have no common ancestor.  Does the constraint or its anchors reference items in different view hierarchies?  That's illegal."

**Comment by carlsondev** [comment]
Are the UI elements added to the input bar before you call "activate" or after?

**Comment by ElrB** [comment]
Just realized that I was calling activate before ui elements were added, but even after activating at the right moment, the result is a weird message input bar behavior, its height changes depending on wether the keyboard is shown or not.

**Comment by carlsondev** [comment]
Okay I doubt this will fix it, but check if the input bar has "translatesAutoresizingMaskIntoConstraints' set to false. Either that or on the input bar button.

If this doesn't work you can add a heightAnchor constraint to the input bar.

**Comment by ElrB** [comment]
They are all set to false.
I am not really experienced in using anchor constraint, as I usually use visual format. Can you please advice if am setting my attachment button anchor right? This is what currently have but all it does is change the message input bar height and not the y coordinate of attach button.

attachButton.centerYAnchor.constraint(equalTo: messageInputBar.centerYAnchor, constant: 0).isActive = true

**Comment by carlsondev** [comment]
That looks good to me. I think you should also try and do messageInputBar.heightAnchor.constraint(equalToConstant: 100).isActive = true in order to stop the message input bar from changing height. Of course you can change 100 to whatever you think would be more appropriate

**Comment by ElrB** [comment]
I think adding a constant height constraint will prevent the input text view from increasing in size when user type a lot of text in it. 
But even after setting those anchors, the thing that I want changed (the attachment button y coordinate), does not change, instead other layouts change. Maybe I should just leave it.

**Comment by mendimr** [comment]
Did you check the view hierarchy and the InputStackView properties?
The InputStackView alignment is set to **.bottom** by default so try and set it to **.center**

```
messageInputBar.leftStackView.alignment = .center
messageInputBar.rightStackView.alignment = .center
```

**Comment by ElrB** [comment]
@mendimr wow, thank you a lot. Its now perfect with those settings.
