### ISSUE TITLE
Setting an Avatar asynchronously

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#164]
There's currently no clear way of doing this and the priority of this feature is extremely high. The question is how to expose an API for this without:

- A) Adding any networking code to the library
- B) Making any assumption on how the user manages async images, `SDWebImage`, `Kingfisher`, etc.

It would be best if we just had some sort of hook to retrieve an Avatar and at the very most all we know is this method is going to be performed asynchronously.

**Comment by mperovic** [comment]
@SD10 I implemented it using Nuke + Preheat. It works great. By my opinion option B is a quite acceptable solution.

**Comment by SD10** [comment]
@mperovic Thanks for the feedback. I know solving this is sort of user-specific, but I still think there should be some form of very basic first class support in the library. Glad to hear you were able to work things out.

That being said, the worst thing we can do is force users to use a specific method or add a specific 3rd party dependency.

**Comment by eliburke** [comment]
I agree strongly. Sub-dependencies are a huge pain, and everyone's backend requirements are different. 

I built something like the following for a project I am working on:
* An NSCache-derived AvatarCache and <CachedAvatar> container object
* CachedAvatar stores identifier, initials, optional avatar, optional placeholder, updateInProgress, lastUpdateAttempt
* avatar lookup takes the ID and flags indicating if placeholder / initial images are acceptable
* if initials are enabled, placeholder image is disabled, and vice-versa
* avatar fetch is async

In practice: the view controller (or cell or whoever) requests an avatar, and indicates if initials / placeholder is OK. Cache looks up the ID and returns it if available, or kicks off an async query and then generates an AvatarInitials image and returns it. Next call to the cache will get AvatarInitials image immediately. Eventually when the async query completes, the avatar is written to the cache, so when the view controller next requests the avatar it gets the real deal. 

In my particular case, the async query is a method but I think it could instead be an optional closure for users to override. Also in my case, avatars are written to a Realm database so it is easy to watch for update notifications. To accommodate other uses, a weak reference of the AvatarCache could be passed to the fetch closure, so the resulting image can be written into the cache, and then the cache can notify MessageKit. There would probably also need to be a closure for "saving" the avatar to database / filesystem. [Edit] one more wrinkle is cancellation. I use my implementation globally so I don't mind outstanding requests, but a way to cancel could be useful, or it could be left to subclassing. 

Some other thoughts: 
* MessageKit would have a default AvatarCache implementation that generates icons and has dummy values for the placeholder image and for the fetchAvatar closure
* User can override the default to subclass or save it between MessageKit instances
* Generator method for AvatarInitials should expose foreground and background colors, possibly font, dimensions and corner radius
* sample project could provide some commented examples /w Nuke / Kingfisher / AlamoFire implementations of the query code, as well as a basic "save to filesystem"

All of this may be more heavy handed than what you are looking for, but if you like the outline I can see about extracting the guts of it.

**Comment by SD10** [comment]
@eliburke That was a lot to digest! But it sounds very similar to a solution we were discussing internally. The problem is, like you had mentioned, it is a very heavy implementation.

I was hoping having the user define a single async block to retrieve the Avatar could solve this 😅

**Comment by gungorbasa** [comment]
@SD10 I was playing with some code last night. What do you think about something like below. We can integrate it in AvatarView.

https://gist.github.com/gungorbasa/088dca7492617e54be2caeff8515bcdf
https://gist.github.com/gungorbasa/a9cb8f6129936bd18623e59af25b73ac

**Comment by SD10** [comment]
@gungorbasa Thanks for taking a look at this! I still haven't had enough free time to look into this more. I'd really prefer to not add any networking code to this project.

The approach you outlined also seems to be limited to using a `URL` to access the image. It needs to support 3rd part libraries such as `Kingfisher` / `Alamofire` / `SDWebImge`.

We also have to take into consideration people using BaaS platforms like `Firebase`. And of course local storage like `Realm`/`CoreData`.

**Comment by cwalo** [comment]
@SD10 Taking a stab at this today. I definitely agree that it shouldn't be the job of MessageKit to do any networking calls. Thinking a `MessagesDataSourceDelegate` method that provides the avatar view on cell configuration and lets the user do whatever they need to.

**Comment by cwalo** [comment]
Something like this in `configure(with message)...`:

```swift
if let configureAvatar = dataSource.configureAvatarView(avatarView, for: message, at: indexPath, in: messagesCollectionView) {
    configureAvatar()
} else {
    avatarView.set(avatar: avatar)
}
```

**Comment by cwalo** [comment]
Here's what that looks like in practice using objects from realm and setting with AlamofireImage:

```swift
    func configureAvatarView(_ avatarView: AvatarView, for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> (() -> Void)? {
        let message = messageAt(indexPath)

        return {
            if let urlString = message.member?.avatarURL, let url = URL(string: urlString) {
                avatarView.imageView.af_setImage(withURL:url,
                                                 placeholderImage: UIImage(named: "avatarDefaultSmall"),
                                                 filter: CircleFilter(),
                                                 imageTransition: .crossDissolve(0.2)
                )
            } else {
                avatarView.imageView.image = UIImage(named: "avatarDefaultSmall")?.af_imageRoundedIntoCircle()
            }
        }
    }
```

**Comment by SD10** [comment]
I was thinking this could be an approach. Similar to what @cwalo described above:
```Swift
func avatarConfiguration(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> (AvatarView) -> Void
```
You would get a reference to the `AvatarView` for each cell. The biggest problem here is that cells are reused and the `AvatarView` in the block may be on a different (wrong) cell at the time the request completes.

However, it would be the job of the developer to ensure the image is being applied to the right cell. They would likely have to manage their own `UIImage` cache from this method.

cc @eliburke @cwalo @gungorbasa @mperovic

**Comment by cwalo** [comment]
I like the idea of reducing this to a single delegate method - if that's the intention. I'll have to think through ensuring that the correct image is used. Until the image is cached, won't the issue always stand for the first load?

**Comment by gungorbasa** [comment]
I am not sure but can't we solve that issue with

```swift
public func collectionView(_ collectionView: UICollectionView, didEndDisplaying cell:   UICollectionViewCell, forItemAt indexPath: IndexPath) {
        cell.image = defaultImage
}
```
@SD10

**Comment by SD10** [comment]
@gungorbasa The block holds a reference to the AvatarView, so even if we clear out the old image the network request may complete after the cell has already been cleared.

**Comment by SD10** [comment]
Anyways, I think the delegate method I described above also allows us to deprecate the `Avatar` struct. Since you have a reference to the cell, you no longer need that helper object 🤔

**Comment by Jeyhey** [comment]
One way to handle asynchronous avatar setting is to have a combination of (a) a delegate method called by the collection view and (b) a setter method called upon completion of the network request. Something like:
```swift
func avatar(_ avatarView: ImageView, at indexPath: IndexPath) {
      let contact = contact(at: indexPath)
      let sender = contact.sender
      /* check if avatar is in local cache*/
      if let avatar = MediaService.shared.avatar(for: contact) {
            avatarView.image = avatar
      /* otherwise set placeholder and fetch avatar from network*/
      } else {
            avatarView.image =  UIImage(named: "avatarDefault")
            let url = MediaService.shared.avatarUrl(for: contact)
            SomeLibrary.shared.downloadImage(for: url) { avatar in
                  self.setAvatarImage(avatar, for: sender)
            }
      }
}
```

In the method `setAvatarImage` MessageKit would check if the sender has any visible cells and (a) set the avatar image for these or (b) ignore if no cells are visible for the sender.

**Comment by Jeyhey** [comment]
Or replace the `setAvatarImage`-method with a completion block `((UIImage, Sender) -> Void)` in the delegate function. That would be cleaner:

**Comment by Jeyhey** [comment]
```swift
func avatar(_ avatarView: ImageView, at indexPath: IndexPath, _ completion: ((UIImage, Sender) -> Void) ) {
      let contact = contact(at: indexPath)
      let sender = contact.sender
      /* check if avatar is in local cache*/
      if let avatar = MediaService.shared.avatar(for: contact) {
            avatarView.image = avatar
      /* otherwise set placeholder and fetch avatar from network*/
      } else {
            avatarView.image =  UIImage(named: "avatarDefault")
            let url = MediaService.shared.avatarUrl(for: contact)
            SomeLibrary.shared.downloadImage(for: url) { avatar in
                  completion(avatar, sender)
            }
      }
}
```

**Comment by cwalo** [comment]
@Jeyhey yeah, I think we're all on a similar page. FWIW @SD10 started a branch with a pretty slick implementation here: https://github.com/MessageKit/MessageKit/tree/debug/async-avatar

**Comment by ijameelkhan** [comment]
Can we merge this into master ? this looks to me a proper solution for asynch avatars. 
Also can we add avatarURL into Sender struct ?

**Comment by SuperTango** [comment]
What about the ability to (via whatever callback) just provide a UIView or UIImageView directly.  I've got a use case where my user avatars are composited with not only the standard user avatar, but some other "badges".  So my avatar wants to be a UIView with a bunch of UIImageViews contained within.

**Comment by SD10** [comment]
@SuperTango Would you not be able to do this with the changes being made in #416?
I wouldn't recommend removing/adding subviews to the `AvatarView` dynamically 🤔 It would be better if the image itself could be composed of those "badges".

**Comment by SuperTango** [comment]
I'm not sure.  The thing is that we add a couple of different types of flair (badges, rings, etc).  based on the runtime status of the users, so we already have a custom UIView component that handles all of this for us.  The fact that the MesageKit Avatar is purely an UIImage (and is automatically clipped to a circle) is somewhat limiting here.  Having the ability to provide a UIView gives more flexibility.

**Comment by SD10** [comment]
@SuperTango Got it, thanks 👍 Seems similiar to #418 now

**Comment by SD10** [comment]
This will be possible in #416. We went with a minimal approach, just giving the user a hook to configure the `AvatarView` for every cell. 

```Swift
 func configureAvatarView(_ avatarView: AvatarView, for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView)
```
