### ISSUE TITLE
Support for documents like doc, pdf

### ISSUE THREAD

**Issue by DevGirisankar** [MessageKit/MessageKit#1642]
Does Messagekit supports attachments like documents? if so can anyone help me to implement ?
If not supported, how can i do that ? is there any way to do it?

**Comment by DevGirisankar** [comment]
@Kaspik ?!

**Comment by Kaspik** [comment]
You would need your own custom cell to handle this kind of things right now.

**Comment by DevGirisankar** [comment]
closing the issue

**Comment by erwanmace** [comment]
You could generate an image thumbnail of the doc/pdf and use the media photo cell to display it.
Then handle the didTapMessage and open the actual document

**Comment by VVTArtemiyFirsov** [comment]
When will support for thumbnail of the pdf in CollectionView of Attachments? Now it's final class: `final public func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell ` Thanks.

**Comment by stingray06** [comment]
When will support for thumbnail of the pdf in CollectionView of Attachments? Now it's final func: `final public func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell ` Thanks.
