### ISSUE TITLE
How to change message style? Default is bubble I want bubble_full_tail

### ISSUE THREAD

**Issue by sanjeet-panda** [MessageKit/MessageKit#1646]
Default message style is bubble, but I want to change to bubble_full_tail.

- What version of MessageKit are you using?
3.7.0
- What version of iOS are you running on?
14.4
- What version of Swift are you running on?
5
- What device(s) are you testing on? Are these simulators?
Simulator
- Is the issue you're experiencing reproducable in the example app?
MayBe

**Comment by sanjeet-panda** [comment]
MessagesDisplayDelegate - The default value returned by this method is **MessageStyle.bubble.**

Need to change to bubbleTail

**Comment by Kaspik** [comment]
It's up to you what you return in your own implementation, right?
