### ISSUE TITLE
cannot find messagesCollectionView in scope

### ISSUE THREAD

**Issue by baamds** [MessageKit/MessageKit#1653]
Hi guys, so I have been struggling with this issue for several hours. 
I installed MessageKit in a project where GrowingTextView is also used, and repeatedly got that error saying the messagesCollectionView is not recognisable.

In another project without growingTextView everything works just fine, so I dont know if this problem should be considered as a bug or not. Do you guys confirm the complication? Is there any solution for this? 

Cheers to the good work

**Comment by Kaspik** [comment]
Never tried and can't seem to find a reason why that would happen.

**Comment by baamds** [comment]
Okay so now I have gone through the entire project, the problem was not clash with GrowingTextView as I thought. 

I had an existing ViewController called MessagesViewController, so I was subclassing another viewcontroller instead of the actual MessagesViewController.
