### ISSUE TITLE
configureMediaMessageImageView method is not working.

### ISSUE THREAD

**Issue by prakashstrivemindz** [MessageKit/MessageKit#1657]
I'm using MessageKit for chat but there is configureMediaMessageImageView method is not working.

Chat included text message, media message and document file.

**Comment by martinpucik** [comment]
@prakashstrivemindz can you reproduce this in out example project? I just tried the advanced example controller and the media message cell is loaded correctly.
Please feel free to reopen this issue if it's reproducible in the example 🙏
