### ISSUE TITLE
How can we detect if user press the "Send/Return" button on keyboard

### ISSUE THREAD

**Issue by wbwxshao** [MessageKit/MessageKit#1659]
I would like the user to be able to send messages when he/she presses the "Send" button on the keyboard also. For a textField I know that can be achieved with the delagte. But could anyone please point me how can we do this in MessageKit? I was not able to find a proper method to use here.
Thanks in advance!

**Comment by fukemy** [comment]
```
    func inputBar(_ inputBar: InputBarAccessoryView, didPressSendButtonWith text: String) {
    }
```

**Comment by wbwxshao** [comment]
@fukemy 
Thanks for your answer, but isn't that method used for the send button next to the text field?
I'm looking for how to use keyboard's "send/return" button

**Comment by fukemy** [comment]
u can get the textfield from messageInputBar using messageInputbar.inputTextView.
Read more about textView here
https://stackoverflow.com/questions/703754/how-to-dismiss-keyboard-for-uitextview-with-return-key

**Comment by wbwxshao** [comment]
@fukemy 
Thanks for your answer again. Seems like in this case we cannot use the textView delegate methods mentioned in the stackoverflow. But we need to use the UIToolBar way? But I also tried with that and it didn't work for me. I have added the code but once I pressed the textView, it will disappear, and keyboard will not show.

**Comment by fukemy** [comment]
messageInputBar using TextView not TextField, did u implemented wrong delegate?

**Comment by fukemy** [comment]
Sorry bro, I dont think you can do this, the way you only can do is modify the textview return key, or event when user click the return key.

 The messageInputBar only accept UITextView, not UITextField

**Comment by Kaspik** [comment]
There is no reason why you should use anything else than UITextView, and for UITextView this has been answered I believe. :) Sorry if it doesn't work the way you would like to.
