### ISSUE TITLE
messageCollectionView hides behind NavigationBar

### ISSUE THREAD

**Issue by developer-securehops** [MessageKit/MessageKit#1662]
I am getting issue in the message view controller 
basically, messageCollection is behind the navigation bar, I have tried `isTranslusent= false` but no gain
and navigation bar is also not start from top 
please have a look the pictures below

![Simulator Screen Shot - iPhone 13 Pro Max - 2022-01-03 at 16 00 48](https://user-images.githubusercontent.com/97017229/147946699-3826882d-1f38-4300-a822-d77d8a308a73.png)

<img width="1039" alt="Screenshot 2022-01-03 at 4 01 39 PM" src="https://user-images.githubusercontent.com/97017229/147946746-7314461b-5958-4134-a082-54d0b49c1034.png">

**Comment by Kaspik** [comment]
Check our examples and search in closed issues please.
