### ISSUE TITLE
SwiftUI - Example App -> No Data Update, No Visual Update on Message Sending

### ISSUE THREAD

**Issue by virus-zip** [MessageKit/MessageKit#1672]
The example app which is provided in the repo does not resolve the SwiftUI example screens as it should. When a message is sent trough the provided UI, neither the datasource nor the visuals are updated. In some rare cases, the full UI of the MessagesView is broken with the List view full deplaced on top of the view.

Steps/code to reproduce the behavior:
-> Clone the repo, compile and run example app.
-> Bug can be reproduced in the example app. 

- What version of MessageKit are you using? -> newest version, 3.7.0
- What version of iOS are you running on? -> iOS 15
- What version of Swift are you running on? -> newest
- What device(s) are you testing on? Are these simulators? real device, iPhone 11, IPhone 12 Pro Max, iPhone 12
- Is the issue you're experiencing reproducible in the example app? -> yes

**Comment by YonatanGM** [comment]
I am having the same  problem. The  updateUIViewController in the viewrepresentable doesn't seem to get called when the message array changes from swiftUI.

**Comment by mertnesvat** [comment]
having the same issue, I think it's related to the first responder because when I navigate back it updates immediately.

**Comment by mertnesvat** [comment]
I wasn't sure what the problem was, but I managed to solve it while troubleshooting. 
Just create a MessageViewModel and use the published messages instead of using State in the view like below,
```
struct SwiftUIExampleView: View {
  // MARK: Internal

    @ObservedObject var viewModel = MessageViewModel()
//  @State var messages: [MessageType] = SampleData.shared.getMessages(count: 20)

    var body: some View {
        MessagesView(messages: $viewModel.messages)
            .onAppear {
                self.connectToMessageSocket()
            }
            .onDisappear {
                self.cleanupSocket()
            }
            .navigationBarTitle("SwiftUI Example", displayMode: .inline)
  }

  // MARK: Private

  private func connectToMessageSocket() {
    MockSocket.shared.connect(with: [SampleData.shared.nathan, SampleData.shared.wu]).onNewMessage { message in
        DispatchQueue.main.async {
            self.viewModel.messages.append(message)
        }
    }
  }
```
MessageViewModel 

```
import Foundation
import Combine
import MessageKit

class MessageViewModel: ObservableObject {
    @Published var messages: [MessageType] = []
    private var cancellables = Set<AnyCancellable>()
    init() {
        $messages
            .sink { new in
                print("new message \(new)")
            }
        .store(in: &cancellables)
    }
}
```
