### ISSUE TITLE
Include *Experimental* tags for SwiftUI ressources

### ISSUE THREAD

**Issue by virus-zip** [MessageKit/MessageKit#1673]
The current version of MessageKit provides rather experimental support for SwiftUI. Please reference the status of the library of SwiftUI components more prominent.

**Comment by Kaspik** [comment]
As you can see SwiftUI was added 2 years ago when iOS 13 came in, and since then a lot has changed. We never released a version that would announce SwiftUI full support. You are more than welcome to update it to SwiftUI 2 with iOS 14+ and fix the Example project, will review the PR. :)

**Comment by virus-zip** [comment]
I think at this point it might be viable to write a whole new library for SwiftUI instead of adding support to this well-working UIKit library. Thank you for the acknowledgment and keep up the good work!

**Comment by Kaspik** [comment]
That's definitely an option too, but it's also a question whether for SwiftUI you even need a library for chat. :)
