### ISSUE TITLE
No InputBarAccessoryView visible in Mac Catalyst build

### ISSUE THREAD

**Issue by Nimeton60** [MessageKit/MessageKit#1675]
- What version of MessageKit are you using?
MessageKit 3.7.0, InputBarAccessoryView 5.4.0

- What version of iOS are you running on?
macOS 12.2.1

- What version of Swift are you running on?
Xcode 13.2.1 with the latest Swift

What device(s) are you testing on? Are these simulators?
MacBook Pro 16'' with M1 Pro

Is the issue you're experiencing reproducable in the example app?
yes, same issue

**Comment by willm132** [comment]
@martinpucik I am having this issue also. Is there a fix for this?

**Comment by willm132** [comment]
@Nimeton60 I am also not able to get the navigation bar to show on Mac Catalyst to add a back button. Is this working for you?

**Comment by Nimeton60** [comment]
I gave up on this for the moment, I’m planning to revisit next month.

**Comment by Nimeton60** [comment]
@nathantannar4 you told in the related bug to @yuriymacdev: "the InputBarAccessoryView (MessageInputBar) already a keyboard manager which can bind the view as a subview. Are you using that? It will handle things like scroll to dismiss and auto sizing"

I got as far as adding the InputBarAccessoryView as a subview to the window, which works fine except that it doesn't auto-resize. What/where is that keyboard manager you mention?

**Comment by martinpucik** [comment]
@Nimeton60 KeyboardManager is part of InputBarAccessoryView package. You can look at implementation in our Example project.

**Comment by Nimeton60** [comment]
Yes that works great, thanks!

**Comment by willm132** [comment]
@Nimeton60 What code did you need to implement to get this working on Mac Catalyst. I am still not able to get this working.

**Comment by Nimeton60** [comment]
Turned out to be simple. Subclassing MessagesViewController:

#if targetEnvironment(macCatalyst)
    private let _keyboardManager = KeyboardManager()
    
    private func _addMacInputBar(_ inputBar: InputBarAccessoryView) {
        view.addSubview(inputBar)
        _keyboardManager.bind(inputAccessoryView: inputBar)
        _keyboardManager.bind(to: tableView)
    }
#endif

    override func viewDidLoad() {
        super.viewDidLoad()
        
        _configureMessageCollectionView()
#if targetEnvironment(macCatalyst)
        _addMacInputBar(messageInputBar)
#endif
        messageInputBar.configure(delegate: self)
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
#if targetEnvironment(macCatalyst)
        messageInputBar.inputTextView.canBecomeFirstResponder = true
        messageInputBar.inputTextView.becomeFirstResponder()
#endif
    }

    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        
#if targetEnvironment(macCatalyst)
        messageInputBar.inputTextView.resignFirstResponder()
        messageInputBar.inputTextView.canBecomeFirstResponder = false
#endif
    }
