### ISSUE TITLE
iPad InputBar bug. How to change InputBar width?

### ISSUE THREAD

**Issue by chaishuanzhu** [MessageKit/MessageKit#1688]
![IMG_0006](https://user-images.githubusercontent.com/18279510/159107143-57a660d7-347b-4ade-a16d-5406dc0e6473.PNG)
![IMG_846743F5E4AD-1](https://user-images.githubusercontent.com/18279510/159107150-bbf4449f-426d-424f-a00d-a756c19b40ca.jpeg)

**Comment by martinpucik** [comment]
Hey @chaishuanzhu thanks for raising this. As we're adding message input into inputAccessoryView of the ChatViewController, this is expected behavior for now. If you require a different behavior, it should be pretty easy to change the behavior in your project without changes in the library.
