### ISSUE TITLE
Support for the new AttributedString 

### ISSUE THREAD

**Issue by NicolaiBure** [MessageKit/MessageKit#1701]
**Is your feature request related to a problem? Please describe.**
Hi I was trying to add the new AttributedString that iOS added on iOS15  I looked that it only supported NSAttributedString. The thing is on the markdown feature the new have

I think if its not a lot of work doing the change will improve a lot MessageKit

As a Alternative I might consider changing the source code to use it

**Comment by martinpucik** [comment]
Hey @NicolaiBure could you try to init NSAttributedString with your AttributedString? https://developer.apple.com/documentation/foundation/nsattributedstring/3787788-init
