### ISSUE TITLE
The cell layout is invalid when you load more items in the example project.

### ISSUE THREAD

**Issue by chauhan130** [MessageKit/MessageKit#1702]
**Describe the bug**
The cells are laid out incorrectly or sized incorrectly when you pullToRefresh at the top to load more messages in the example project.

**To Reproduce**
Steps/code to reproduce the behavior:

1. Open either Advanced Example, Autocomplete Example, or Embedded Example (I think it happens more if we have typing indicator).
2. Tap the status bar to reveal the very first message.
3. Pull to load the previous messages.
4. Till you notice some odd behavior, repeat steps 2 and 3.

**Expected behavior**
It should load previous messages with the correct layout.

**Screenshots**

https://user-images.githubusercontent.com/1622768/166446513-ca981e95-b94f-46bd-89b3-19baa9e32788.mov

**Environment**
- What version of MessageKit are you using? - The main branch (latest commit is 9d787d80140dcc69789b09bd6a47e863bc8143d3).
- What version of iOS are you running on? - iOS 15.4
- What version of Swift are you running on?  - Swift 5
- What device(s) are you testing on? Are these simulators? - iOS Simulator iPhone 13 Pro
- Is the issue you're experiencing reproducible in the example app? - Yes

**Additional context**
I think the underlying reason is the app uses `reloadData` as well as `performBatchUpdates`, and when they both are combined, this issue occurs. Probably related to #1108, #1026

I had been facing this issue in our app for a long time. I am also skeptical about the typing indicator being a major part of the problem (as it reserves its own section in the collection view). 

**Temporary workaround:**
When we use only the `reloadData` (instead of `performBatchUpdates`) and hide the typing indicator, the issue is not discovered. (This issue does not happen 100% of the time in our app so can't say for sure that the workaround has fixed the problem.)

**Comment by Kaspik** [comment]
Could you try latest 4.0.0 beta 1?

**Comment by Kaspik** [comment]
Version 4.0.0 is out, let me know if you still have this issue.
