### ISSUE TITLE
Memory leaks when returning .custom() in messageStyle() delegate method

### ISSUE THREAD

**Issue by Janneman84** [MessageKit/MessageKit#1703]
I've discovered a potential memory leak (retain cycle) in the messageStyle delegate method when returning a `.custom` style. It can be fixed by unowning both `self` ánd `messageContainerView`
```swift
func messageStyle(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> MessageStyle {
    return MessageStyle.custom() { [unowned self, unowned messagesCollectionView] messageContainerView in
        //referencing self (like calling a method) would normally keep the ViewController stuck in memory:
        print(self)
        //referencing messageContainerView when not unowned would keep itself in memory too, even if self is unowned:
        print(messageContainerView)
    }
}
```

Of course this only applies if you're referencing these inside the callback. I'm not sure exactly what causes this and if there is way to change the source code so you won't have to use `unowned` anymore. If that is not possible maybe there is some way to warn the user about this?

I have the feeling that there are plenty of users with leaky apps because of this. This might even explain certain odd crashes and other issues some users have.

Tested on 3.7.0 and 3.8.0.

**Comment by martinpucik** [comment]
Hey @Janneman84, thanks for raising this. I think this is working correctly. AFAIK it's client's responsibility to manage their object references when used in escaping closures. Using `[weak obj] / [unowned obj]` is pretty standard practice.
