### ISSUE TITLE
Type in foreign languages like Korean with unique typing behavior

### ISSUE THREAD

**Issue by adamvnovak** [MessageKit/MessageKit#1717]
<img width="382" alt="스크린샷 2022-05-16 오전 11 09 16" src="https://user-images.githubusercontent.com/42633268/168655872-79779041-9cec-4e99-9f6f-d06288834b00.png">

When I type "Hello" in Korean, instead of appearing like it should as "안녕하세요", it splits up the characters into "ㅇㅏㄴㄴㅕㅇㅎㅏㅅㅔㅇㅛ". I'm not sure how other languages with non-roman alphabets like Japanese, Chinese, or Arabic appear on MessageKit, but I suspect they could suffer from the same problem. 

This problem does not exist when typing in any standard UITextField.

It would be really great if you all could add support for typing in foreign languages.

**Comment by martinpucik** [comment]
Hey @adamvnovak thanks for raising this. I can't reproduce this though in the example project on `main` branch. When typing `ㅇㅏㄴㄴㅕㅇㅎㅏㅅㅔㅇㅛ` the result is `안녕하세요` for me

| | |
|---|---|
|![Simulator Screen Shot - iPhone 13 - 2022-05-17 at 15 58 04](https://user-images.githubusercontent.com/5503097/168828621-fb4cd3c8-b872-4b4a-b601-ae09dd65a8b7.png)|![Simulator Screen Shot - iPhone 13 - 2022-05-17 at 15 58 11](https://user-images.githubusercontent.com/5503097/168828640-50e353eb-a226-49a0-9156-e777f1b6dabe.png)|
