### ISSUE TITLE
I'm still getting this issue. MessagecollectionView's frame are not properly managed while opening the keyboard. Some message are hidden below the keyboard.

### ISSUE THREAD

**Issue by DevSoft0073** [MessageKit/MessageKit#1718]
[

**Comment by DevSoft0073** [comment]
Kindly let me know what I have to do now

<img width="328" alt="image" src="https://user-images.githubusercontent.com/93834349/168979602-0f272c7a-4124-4765-857e-9be76dbe894e.png">
<img width="334" alt="image" src="https://user-images.githubusercontent.com/93834349/168979670-59f1cc97-651d-4151-aae0-d3c3a5b415ff.png">

**Comment by Kaspik** [comment]
Explore the example projects please and open an issue properly next time if you are seeing the issue there as well.
