### ISSUE TITLE
Avatar image is not visible for custom cell

### ISSUE THREAD

**Issue by tatanehajain** [MessageKit/MessageKit#1719]
**Describe the bug**
I am using custom and default cells in the same controller on the basis of conditions. For default cell avatar image is visible however for the custom cell its not visible.

**To Reproduce**
Steps/code to reproduce the behavior:
Use custom cell and default cell in the same controller so that MessageType will be "AttributedText" for a few cells and "Custom" for others.
Avatar image is visible for cell with MessageType AttributedText and its not visible for CustomCell.

Even in MessageKit example app there is no Avatar image for custom cell.

**Expected behavior**

**Screenshots**

**
![Simulator Screen Shot - iPhone 11 - 2022-05-18 at 16 26 44](https://user-images.githubusercontent.com/40622109/169034842-aa3a60ed-b61f-4836-b33d-303a78b0b1b5.png)
Environment**
- What version of MessageKit are you using? -- 3.3.0
- What version of iOS are you running on? -- 15.4
- What version of Swift are you running on? -- 5
- What device(s) are you testing on? Are these simulators? -- iPhone 11 Simulator
- Is the issue you're experiencing reproducible in the example app? -- Even in example app there is no avatar image for custom cell.

**Additional context**

**Comment by martinpucik** [comment]
Hey @tatanehajain thanks for raising this issue. I think our custom cell in Example project doesn't inherit from `MessageCollectionViewCell` where there is an `avatarView` implemented. Your custom cells should iherit from this class if you want the avatar to be set up and visible.

**Comment by tatanehajain** [comment]
Hi martinpucik,
My custom cell is inherited from MessageCollectionViewCell and still its not working. 
Below is the sample code for cell:

import UIKit
import SDWebImage
import MessageKit

class ActivityVideoCollectionViewCell: MessageCollectionViewCell {

    @IBOutlet weak var videoImageView: UIImageView!
    @IBOutlet weak var tapGestureBackgroundView: UIView!
    @IBOutlet weak var videoTextLabel: UILabel!
    var playVideo: (() -> Void)?

    override func awakeFromNib() {
        super.awakeFromNib()
        // Initialization code
        customUI()
    }

    func customUI() {
        videoTextLabel.configureLabel(fontType: .paragraphMedium, textColorType: .dark, alignment: .left)
        tapGestureBackgroundView.roundCorners(radius: 16)
        let tapGesture = UITapGestureRecognizer(target: self, action: #selector(playActivityVideo))
        tapGestureBackgroundView.addGestureRecognizer(tapGesture)
    }

    func setupData(textData: MWBotTextsMap) {
        videoTextLabel.text = textData.text
        videoImageView.sd_setImage(with: URL(string: textData.videoData?.thumbnail ?? ""))
    }

    @objc func playActivityVideo() {
        playVideo?()
    }
}

**Comment by martinpucik** [comment]
@tatanehajain how's your view hierarchy looking in the debugger?

**Comment by Kaspik** [comment]
Will close if no additional response.
