### ISSUE TITLE
Installing latest version fails due to SwiftFormatPlugin

### ISSUE THREAD

**Issue by magneticrob** [MessageKit/MessageKit#1731]
**Describe the bug**
When upgrading from MessageKit 3.3.0 to MessageKit 4.0.0, on Xcode 13.4.1 (13F100) I get the following error:

`Malformed input JSON: Plugin declared with `buildTool` capability but doesn't conform to `BuildToolPlugin` protocol`

**To Reproduce**

All I did was remove the MessageKit cocoapod dependency, then add the MessageKit SPM dependency. I have restarted Xcode, cleaned the build project, and am attempting to download Xcode 14 Beta 3 to see if that fixes anything.

**Expected behavior**
MessageKit should not fail the build.

**Screenshots**
<img width="865" alt="Screenshot 2022-07-27 at 11 03 22" src="https://user-images.githubusercontent.com/1032538/181220865-a730baf8-d85a-4e8b-b148-0f660b3c0bff.png">

**Environment**
- What version of MessageKit are you using? - 4.0.0
- What version of iOS are you running on? - N/A - Project does not build
- What version of Swift are you running on? - Swift 5
- What device(s) are you testing on? Are these simulators? - N/A - Project does not build
- Is the issue you're experiencing reproducible in the example app? - N/A - Project does not build

**Comment by Kaspik** [comment]
Are you using 4.0.0 version or `master`?

@martinpucik Some of your master changes?

**Comment by magneticrob** [comment]
Hey @Kaspik, I am running 4.0.0, here's a screenshot of how it looks in my package dependencies section:

<img width="449" alt="Screenshot 2022-07-27 at 11 10 03" src="https://user-images.githubusercontent.com/1032538/181222192-69c75e7b-ce8c-4197-bf4b-8edb12a18e78.png">

**Comment by magneticrob** [comment]
OK, this is a bit strange - after fixing all of the breaking changes (e.g. updating the `maxContainerSize(...` function declarations etc, it seems I missed one (`senderType`) - after fixing that last one I seem to be up and running again, although the error remains. Xcode eh? 

Not sure if you want to close this or not, but I am up and running now.

**Comment by Kaspik** [comment]
`main` means you are using branch, not tag. Please switch to `4.0.0` release. How did you add it to SPM?

**Comment by magneticrob** [comment]
I just followed the installation guide, then hit OK.

<img width="849" alt="Screenshot 2022-07-27 at 11 18 23" src="https://user-images.githubusercontent.com/1032538/181223778-2eaa229d-c9f8-425f-89af-2a49c3a4a8c2.png">

**Comment by Kaspik** [comment]
Yeah, so if you added the URL, it asked if `upToNextMajor` or if you wanna use branch or what.

Probably go to the SPM in Xcode, remove MessageKit, try to add it again and make sure you use the versions and not branches. :)

<img width="1117" alt="Screenshot 2022-07-27 at 12 24 38" src="https://user-images.githubusercontent.com/7204168/181225009-279ce27f-e71b-488b-892e-bc29432fca13.png">

**Comment by magneticrob** [comment]
I did actually get it working correctly before making that change, but have done so now too, so thanks for the pointer there. 

Now to work on the rest of the breaking changes, like MessageKit thinking my cells are text and giving me a fatalError ;) 

Thanks for the quick response @Kaspik , really appreciated.
