### ISSUE TITLE
Add padding between Message text and bubble 

### ISSUE THREAD

**Issue by maasim94** [MessageKit/MessageKit#1735]
Hi first of thanks for library, I'm trying to achieve padding between attributed text and cell bubble. i have tried searched all issues with key word padding but couldn’t find way to achieve that. since it is very simple problem that's why i don't want to use custom cell. 

![IMG_49D28DC5B135-1](https://user-images.githubusercontent.com/8789336/185096772-651e5238-7589-45ca-be4c-396e0abf5efd.jpeg)

**Comment by Kaspik** [comment]
I think you could `apply` `MessagesCollectionViewLayoutAttributes` to the cell where you will include `textInsets` in the attributes?

https://github.com/MessageKit/MessageKit/blob/b2503bc21f5a3e1c68f8bfa54a1ddbd2be27f93c/Sources/Views/Cells/TextMessageCell.swift#L41
