### ISSUE TITLE
CameraInputBarAccessoryView not working in AdvancedExampleViewController

### ISSUE THREAD

**Issue by akatreyt** [MessageKit/MessageKit#1741]
**Describe the bug**
When running the example app the custom CameraInputBarAccessoryView is not showing the camera image

**To Reproduce**
run the example app on sim or device

**Expected behavior**
To see the custom input view with the camera icon

**Screenshots**
![Simulator Screen Shot - iPhone 13 mini - 2022-09-02 at 13 12 33](https://user-images.githubusercontent.com/555971/188213900-f1826439-ebfd-4361-914a-afb44be72369.png)

- What version of MessageKit are you using? 4.0.0
- What version of iOS are you running on? 15.5
- What version of Swift are you running on? 
- What device(s) are you testing on? Are these simulators? all sim and physical device 13 mini
- Is the issue you're experiencing reproducible in the example app? yes

**Comment by mripston** [comment]
I'm having the same issue on simulator and devices

**Comment by sibtainali632** [comment]
Facing the same issue, has anyone been able to find a solution for this?

**Comment by akatreyt** [comment]
I fixed it by doing inputBarType = .custom(customInputView)

**Comment by sibtainali632** [comment]
@akatreyt  It worked like a charm, thanks
