### ISSUE TITLE
InputBarAccessoryView (and subview) heights different with MessageKit 4.0.0?

### ISSUE THREAD

**Issue by bmt2018** [MessageKit/MessageKit#1749]
We have an app that's been using MessageKit since 3.0.  This is a screenshot of the InputBarAccessoryView in a version of our app that was built using MessageKit 3.x.

<img width="396" alt="MK 3 0" src="https://user-images.githubusercontent.com/36267412/193302993-bc9fea41-e0b8-45b0-b43c-6acf9654307e.png">

As you can see, the vertical spacing between the top stack view, the middle text view and the bottom stack view in the InputBarAccessoryView looks as you would expect.  We just migrated from MessageKit 3.x to 4.0.0 and now here's what we're seeing:

<img width="396" alt="MK 4 0" src="https://user-images.githubusercontent.com/36267412/193303383-e3272d53-ef06-4835-93d2-a69a8efac99a.png">

I obviously changed the background colors on the various views to make it easier to see what's happening.  As you can see, the bottom stack view is being stretched vertically which results in extra space between the InputBarButtonItems inside and the text view.  I've built both the MessageKit example app and the InputBarAccessoryView example app and I don't see this problem in either of them so it would seem that it's an issue in our code but I'm not sure where yet.  Has anyone encountered something like this after migrating to MessageKit 4.0.0?

**Comment by Kaspik** [comment]
Can you set different colors for objects inside the stack view? Can you also paste here the setup of your purple stack view?

**Comment by bmt2018** [comment]
Hi Jakub,

I changed the background color on all the InputBarButtonItems in the bottom stack view like this:

![IMG_0157](https://user-images.githubusercontent.com/36267412/193317230-e0beb06f-f1dc-442e-bee5-eae284abe0df.jpeg)

Those InputBarButtonItems in the bottom stack view are configured like this:

```
    let geotagButton = InputBarButtonItem()
        .configure {
            $0.spacing = .fixed(10)
            $0.contentHorizontalAlignment = .center
            $0.contentVerticalAlignment = .center
            $0.image = UIImage(named: "chat_input_bar_geotag")?.withRenderingMode(.alwaysTemplate)
            $0.setSize(CGSize(width: 28, height: 28), animated: false)
        }

    let cameraImageButton = InputBarButtonItem()
        .configure {
            $0.spacing = .fixed(10)
            $0.contentHorizontalAlignment = .center
            $0.contentVerticalAlignment = .center
            $0.image = UIImage(named: "chat_input_bar_photo")?.withRenderingMode(.alwaysTemplate)
            $0.setSize(CGSize(width: 28, height: 28), animated: false)
        }

    let cameraVideoButton = InputBarButtonItem()
        .configure {
            $0.spacing = .fixed(10)
            $0.contentHorizontalAlignment = .center
            $0.contentVerticalAlignment = .center
            $0.image = UIImage(named: "chat_input_bar_video")?.withRenderingMode(.alwaysTemplate)
            $0.setSize(CGSize(width: 28, height: 28), animated: false)
        }

    let audioButton = InputBarButtonItem()
        .configure {
            $0.spacing = .fixed(10)
            $0.contentHorizontalAlignment = .center
            $0.contentVerticalAlignment = .center
            $0.image = UIImage(named: "chat_input_bar_audio")?.withRenderingMode(.alwaysTemplate)
            $0.setSize(CGSize(width: 28, height: 28), animated: false)
        }
    
    let charCountButton = InputBarButtonItem()
        .configure {
            let maxLengthOfTextMessage = MaxLengths.chatMessage
            $0.title = "0/\(maxLengthOfTextMessage)"
            $0.contentHorizontalAlignment = .right
            $0.contentVerticalAlignment = .center
            $0.titleLabel?.font = UIFont.systemFont(ofSize: 11, weight: .semibold)
            $0.setSize(CGSize(width: 50, height: 28), animated: false)
        }

    let bottomStackItems = [geotagButton, cameraImageButton, cameraVideoButton, audioButton, .flexibleSpace, charCountButton]

```
We do some pretty simple configuration on the messageInputBar mostly to set padding on the middle content view and to configure the top stack view so it stacks up its contents horizontally instead of vertically.  Other than assigning the InputBarButtonItems in the bottomItems array, we don't do any other configuration to the bottom stack view.

```
        messageInputBar.middleContentViewPadding.top = 5
        messageInputBar.middleContentViewPadding.bottom = 8
        messageInputBar.setStackViewItems(topStackItems, forStack: .top, animated: false)
        messageInputBar.topStackView.axis = .horizontal
        messageInputBar.topStackViewPadding.left = 11
        messageInputBar.topStackViewPadding.right = 11
        messageInputBar.topStackViewPadding.top = 10
        messageInputBar.topStackView.distribution = .fillEqually
        messageInputBar.topStackView.spacing = 15.0
        messageInputBar.setStackViewItems(bottomStackItems, forStack: .bottom, animated: false)

```

Just as a test, I tried setting a height constraint (equal to 50) on the bottom stack view and then the middle content view gets stretched vertically to fill the space:

![IMG_0158](https://user-images.githubusercontent.com/36267412/193319618-efc698d3-3383-4339-8aba-cb8fdbf0e4b7.jpeg)

Unfortunately, I'm sort of at a loss for why this is suddenly happening especially since I can't reproduce it in either of the example apps.

**Comment by Kaspik** [comment]
Are you somehow doing something with input bar accessory view? For example, we moved to subview instead of accessory view (https://github.com/MessageKit/MessageKit/pull/1704). I would try to disable most of the code related to `messageInputBar` (is that your own subclass?) or try something with that there. :)

**Comment by bmt2018** [comment]
Hi Jakub,

We're not doing anything with input bar accessory view directly.  Just configuring the .messageInputBar that's part of MessageKit.  I noticed in the AdvancedExampleViewController (from the example app) that messageInputBar is being assigned an instance of CameraInputBarAccessoryView (which, of course, inherits from InputBarAccessoryView).  Our code doesn't currently do anything like this but if that's a change that's necessary for 4.0.0, then that might explain my issue!

In looking into the problem more today, I noticed something else odd about this.  When I don't explicitly tell the top stack view that it should lay out its subitems horizontally, then it defaults to vertical, of course, and everything appears as I would expect:

![vertical_stack](https://user-images.githubusercontent.com/36267412/193668054-d6590474-9904-4953-a618-97cf0b2c902a.jpeg)


If I explicitly set the axis of the top stack view to horizontal and add two InputBarButtonItems, then the layout appears correct:

![2_horizontal_buttons](https://user-images.githubusercontent.com/36267412/193668264-39c06b7b-53ae-41ed-a757-b42e14345810.jpeg)

But as I add a 3rd, 4th or 5th InputBarButtonItem to the stack, the height of the bottom stack continues to grow:

![3_horizontal_buttons](https://user-images.githubusercontent.com/36267412/193668438-165e086d-5970-4e5b-8a3a-e805529382dc.jpeg)

![4_horizontal_buttons](https://user-images.githubusercontent.com/36267412/193668455-3e1f8bc4-82fa-4024-a8d5-f98901d1b01a.jpeg)

![5_horizontal_buttons](https://user-images.githubusercontent.com/36267412/193668482-cf6064dc-bf15-4aa2-a7a9-2e33de6979d2.jpeg)

I feel like there has to be something that I've missed during migration from 3.x -> 4.0.0 since we didn't have this issue previously.

**Comment by Kaspik** [comment]
Just out of curiosity (because we do the same as in example - have custom class and assign this class / object itself to the input view) - if you try that, does that work?

I really have no other ideas here. You could try setting content priority / hugging / compression on the bottom stack view too, but having input bar as a separate class that you just assign could be maybe easier if it's that many objects and this complicated input. :)

**Comment by bmt2018** [comment]
Thanks for the suggestion, Jakub.  No, I haven't yet tried creating a custom class and assigning it as the input view but that's my next step.  I'm also wondering if this could be related to our view hierarchy, as well.  Our root view controllers is a tab bar controller.  One of the tabs is for "messaging" and that view controller is a container view controller which dynamically re-parents child view controllers.  One of those child VCs is our "chat" VC which uses a table view to show a list of all the chats that the user is involved in.  Tapping on a row, of course, pushes a new VC to show the messages in that chat.  This VC is where we've implemented MessageKit.  For what it's worth, this VC also has it's .hidesBottomBarWhenPushed property set to true so the tab bar isn't visible.  I tried commenting that out and while it didn't make a difference with this issue, I'm still not 100% convinced that something related to our view hierarchy and/or navigation stack isn't responsible for this issue.  Thanks again for your suggestions.  I appreciate it!

**Comment by bmt2018** [comment]
So I was just looking through our code again and noticed that we're setting the top stack view items before we configure the stack view.  Just out of curiosity, I tried setting the items after the code that configures the top stack view and now the layout appears to work as expected.

**Comment by Kaspik** [comment]
Interesting! But glad you found the issue. Feel free to close this then. :)
