### ISSUE TITLE
InputBarAccessoryView goes up way too much on iPad using pagesheet

### ISSUE THREAD

**Issue by Janneman84** [MessageKit/MessageKit#1750]
I just updated to 4.0. My chats are shown in a pagesheet VC. When on iPad the input view doesn't stick properly to the keyboard. This iOS 16 screenshot explains it all:

![Simulator Screen Shot - iPad Air (5th generation) - 2022-10-04 at 11 31 23](https://user-images.githubusercontent.com/9085167/193785987-9f9d1d5a-33ad-4e48-8bb3-1bdb929b3864.png)

You can easily reproduce yourself by changing one simple line of code in the example app in `LaunchViewController.swift`:
```swift
  override func tableView(_: UITableView, didSelectRowAt indexPath: IndexPath) {
    let cell = sections[indexPath.section].rows[indexPath.row]
    switch cell {
    case .basic:
      let viewController = BasicExampleViewController()
      let detailViewController = UINavigationController(rootViewController: viewController)
      //splitViewController?.showDetailViewController(detailViewController, sender: self)
      present(detailViewController, animated: true)
```

So use `present()` instead of `showDetailViewController ()`. Then just open the basic example on iPad and tap on the input field to show the keyboard.

I'm not sure this is a problem with MessageKit or InputBarAccessoryView though.

I see the same issue occur on iOS 14.1 simulator, but not as dramatic.

**Comment by Janneman84** [comment]
Updating to 4.1.1 did not improve this issue. Would anyone like to at least confirm this bug?

**Comment by Janneman84** [comment]
Ok I dove into the code and managed to fix the issue by making some changes to `KeyboardManager.swift` of `InputBarAccessoryView`.

In other words, it's not the fault of `MessageKit`.

**Comment by David77030** [comment]
I noticed same issue when using SwiftUI Example, the input is way above bottom, can you share your fix ?

**Comment by Janneman84** [comment]
I got it mostly working but there is one minor issue I need to look into. I'll probably have it ready next weekend.

**Comment by RhimiMohamed** [comment]
I have a  same issue when using SwiftUI Example, please  can you share your fix ?

**Comment by Janneman84** [comment]
I'm actually waiting for Xcode 14.1 to come out, could be any day now.

**Comment by Janneman84** [comment]
I posted some code to fix the issue here:
https://github.com/nathantannar4/InputBarAccessoryView/issues/238

**Comment by Kaspik** [comment]
IBAV 6.3.0 is out, MessageKit on master uses it for testing purpose for those who are interested.
