### ISSUE TITLE
👻 (reproducible simply in Example App) textViewShouldBeginEditing of messageInputBar.inputTextView not called

### ISSUE THREAD

**Issue by marune-jp** [MessageKit/MessageKit#1753]
**Describe the bug**
See title + other UITextViewDelegate callbacks are called so it is not a delegate setting problem

**Environment**
- What version of MessageKit are you using? newest
- What version of iOS are you running on? ios 16
- What version of Swift are you running on? 5
- What device(s) are you testing on? Are these simulators? devices + simulators
- Is the issue you're experiencing reproducible in the example app? YES

**Comment by marune-jp** [comment]
@Kaspik  @martinpucik Thank you, this problem is currently preventing us making critical updates to our app.

**Comment by Kaspik** [comment]
"Is the issue you're experiencing reproducible in the example app? YES" - where? How? What modifications did you make? What is your setup code? `textViewShouldBeginEditing` is not used anywhere in the example app.

**Comment by marune-jp** [comment]
@Kaspik thanks for the follow up.
I have just added a Text View delegate to the message input bar, and only `textViewShouldBeginEditing` is not received.
It was received normally in previous versions.

You should obtain the same result quite easily.
Do not hesitate to tell me if you want me to give you the diff. (I'll do it again then)

**Comment by Kaspik** [comment]
I'm still not sure I follow what "message input bar" means - is it the InputBarAccessoryView, or is it something else? And which example app you updated / where? The code update would be nice. :)

**Comment by marune-jp** [comment]
> is it `InputBarAccessoryView`

yes! Of the "Basic example" or something like that.
Please have a try if you have time, if not I will PR tomorrow or maybe later.

**Comment by marune-jp** [comment]
@Kaspik Here is a simple patch reproing the issue on main branch. Pasting here too to make it more easy for you (sorry I am not used to github, I don't seem to be able to make PRs using Fork and so I stopped trying immediately)

[delegate_not_called-repro.patch.txt](https://github.com/MessageKit/MessageKit/files/9861613/delegate_not_called-repro.patch.txt)

```
    func textViewShouldBeginEditing(_ textView: UITextView) -> Bool {
        print("should begin editing (not) called")
        return true
    }
    
    func textViewShouldEndEditing(_ textView: UITextView) -> Bool {
        print("should end editing called. notice that 'shoud begin' is never called. you are my savior if you manage to make it called :)")
        return true
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        self.messageInputBar.inputTextView.delegate = self
    }
```
↑
Paste this in BasicExampleViewController while making the class a UITextViewDelegate

**Comment by Kaspik** [comment]
Fixed in IBAV 6.2.0 - https://github.com/nathantannar4/InputBarAccessoryView/releases/tag/6.2.0

Please use `Update packages to latest versions` to fetch InputBarAccessoryView dependency to 6.2.0.

**Comment by marune-jp** [comment]
@Kaspik thank you very much for this. Not out of cocoapods yet so I will soon migrate the whole to the most recent major version through SPM, do some tests and post some feedback when done.

**Comment by marune-jp** [comment]
@Kaspik works great, thank you again. :)
