### ISSUE TITLE
TextColor with attributedText not working

### ISSUE THREAD

**Issue by AngelPachecoNextia** [MessageKit/MessageKit#1756]
**Describe the bug**
The TextMessageCell looks empty because the textColor is white.
In the TextMessageCell(configure function) the switch case(attributedText) not set textColor.

**To Reproduce**
Steps/code to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Environment**
- What version of MessageKit are you using?
- What version of iOS are you running on?
- What version of Swift are you running on?
- What device(s) are you testing on? Are these simulators?
- Is the issue you're experiencing reproducible in the example app?

**Additional context**

**Comment by Kaspik** [comment]
Please properly fill the bug report and with all the data and your code / steps to reproduce, otherwise I'll close this. Thanks.
