### ISSUE TITLE
Why closed if messageInputBar still under tabbar and inputAccessoryView under keyboard with space of tabor height

### ISSUE THREAD

**Issue by Archideus** [MessageKit/MessageKit#1757]

**Comment by Archideus** [comment]
<img width="396" alt="Screenshot 2022-10-26 at 00 43 53" src="https://user-images.githubusercontent.com/5715881/197887966-7f5afe9d-0270-4926-8bdf-44811efcde42.png">
<img width="413" alt="Screenshot 2022-10-26 at 00 43 31" src="https://user-images.githubusercontent.com/5715881/197887973-72cfd766-6a6b-4381-8e5e-21a9b5196e43.png">

**Comment by Kaspik** [comment]
Use proper bug report please.
