### ISSUE TITLE
Xcode slow down problem

### ISSUE THREAD

**Issue by smsdm4** [MessageKit/MessageKit#1758]
I have a problem and that is that when I import the MessageKit package and it is successfully added, Xcode becomes very slow.
I did not find this problem in the searches.
If anyone has encountered this problem, I would appreciate it if you could help me.

MessageKit version: 4.1.1
iOS version: 16
Swift: 5
Implemented and tested on simulator and rail device

Tested on two devices with similar results:
Mac Mini 2020 M1 with 16GB RAM
MacBook Pro 2021 M1Pro with 16GB RAM

**Comment by Kaspik** [comment]
Xcode 14 itself has a bug that uses a lot of CPU and is slow, Xcode 14.1 beta and RC are fixing this. Let's see if that help you, but personally I haven't seen anything related to this.

**Comment by smsdm4** [comment]
> 

This is strange to me.
Because I even tested the package on the package manager of a raw project, and it reduced the speed of Xcode, and after removing it, the speed returns to normal.
I will install Xcode 14.1 beta and test on it. Thanks for the advice my friend.

**Comment by smsdm4** [comment]
> Xcode 14 itself has a bug that uses a lot of CPU and is slow, Xcode 14.1 beta and RC are fixing this. Let's see if that help you, but personally I haven't seen anything related to this.

This is strange to me.
Because I even tested the package on the package manager of a raw project, and it reduced the speed of Xcode, and after removing it, the speed returns to normal.
I will install Xcode 14.1 beta and test on it. Thanks for the advice my friend.

**Comment by Kaspik** [comment]
If you will be able to repro and somehow tell me how / debug it on pure MessageKit project, it would be great, happy to help.

**Comment by smsdm4** [comment]
> If you will be able to repro and somehow tell me how / debug it on pure MessageKit project, it would be great, happy to help.

Actually I didn't debug it.  On the my main project, I tried to import it into SPM, but after adding it, the speed decreases.  After checking the available memory of the device and other hardware, I tried to create a new project and add it to SPM to make sure that the problem is not from my main project.  But in the new project, it became slow after it was added.  I checked on another system and the same problem was present.  I don't know what will happen to Xcode after adding message kit.

**Comment by smsdm4** [comment]
> Xcode 14 itself has a bug that uses a lot of CPU and is slow, Xcode 14.1 beta and RC are fixing this. Let's see if that help you, but personally I haven't seen anything related to this.

I installed Xcode 14.1 beta and my problem was completely solved.
Thank you for your guidance.
