### ISSUE TITLE
Xcode 14 Gets Slower when Updating to 4.1.1

### ISSUE THREAD

**Issue by mehmetbaykar** [MessageKit/MessageKit#1759]
**Xcode gets slower**
After updating the Messagekit(4.1.1) Xcode gets slower. Scrolling, building, and interacting with IDE slows up. 

**To Reproduce**
Steps/code to reproduce the behavior:
- Update the version of MessageKit Package to 4.1.1

**Expected behavior**
Downgrading to 4.0.0 fixes the problem.

**Environment**
- MessageKit: 4.1.1
- macOS: Ventura 13.0
- iOS:13.0
- Swift:5.7

**Comment by Kaspik** [comment]
Please search closed issues. It's not messagekit, it's Xcode 14. Download Xcode 14.1 :)

**Comment by mehmetbaykar** [comment]
The latest version of Xcode is 14.0.1, not 14.1 :)
And that is the version I have(the latest one)

**Comment by Kaspik** [comment]
Yeah, it's an RC only.
