### ISSUE TITLE
How to check whether the ContactMessageCell is tapped and how get the Phonenumber?

### ISSUE THREAD

**Issue by Kuro7070** [MessageKit/MessageKit#1761]
I'm currently developing with IOS and the library Messagekit. I'm trying to check, whether the ContactMessageCell is tapped. Messagekit does not seem to have a didTap function like didTapImage or didTapBackground especially for the ContactCell. `

I have tried to make it work with the didTapMessage function and get access to the data of the ContactMessageCell through the collectionview but I cant access the phone data like name, number, email. I can print them but not access them. Has somebody an idea? Thx for your help guys :)

```
func didTapMessage(in cell: MessageCollectionViewCell) {
          if let contact = (cell as? ContactMessageCell) {
              //TODO
              guard let indexPath = messagesCollectionView.indexPath(for: contact)
              else {
                  print("Failed to identify message when audio cell receive tap gesture")
                  return
              }
              let message = messagesCollectionView.messagesDataSource?.messageForItem(at: indexPath, in: messagesCollectionView)
              print(message)
```

result of "print(message)"

Optional(ChatApp.ChatMessage(sender: ChatApp.Sender(senderId: "self", displayName: "Thomas"), messageId: "21", sentDate: 2022-11-21 09:43:41 +0000, kind: MessageKit.MessageKind.contact(ChatApp.ContactElement(displayName: "John Appleseed", initials: "JA", phoneNumbers: ["888-555-5512"], emails: ["test@goge.de"]))))

````
struct ContactElement:ContactItem{
var displayName: String
var initials: String
var phoneNumbers: \[String\]
var emails: \[String\]
}
```

**Comment by martinpucik** [comment]
Hey @Kuro7070 you can switch over message.kind to get to the associated value of the MessageKind enum

**Comment by Kuro7070** [comment]
Hey @martinpucik  I already tried it about message.kind. If I try "print(message?.kind)" then the print is

Optional(MessageKit.MessageKind.contact(ChatApp.ContactElement(displayName: "John Appleseed", initials: "JA", phoneNumbers: ["888-555-5512"], emails: ["test@goge.de"])))

The problem is I can't access the ContactElement. After message?.kind comes only self -> like message?.kind.self

**Comment by martinpucik** [comment]
@Kuro7070 you need to access the associated value of the MessageKind enum case, more here: https://docs.swift.org/swift-book/LanguageGuide/Enumerations.html#ID148

**Comment by Kuro7070** [comment]
@martinpucik it works, thank you
solution:
```        
            switch message?.kind {
            case .audio(let AudioItem):
                print("UPC: \(AudioItem)")
            case .none:
                print("extra")
            case .some(.text(_)):
                print("extra")
            case .some(.attributedText(_)):
                print("extra")
            case .some(.photo(_)):
                print("extra")
            case .some(.video(_)):
                print("extra")
            case .some(.location(_)):
                print("extra")
            case .some(.emoji(_)):
                print("extra")
            case .some(.contact(let contactItem)):
                print(contactItem.phoneNumbers)
            case .some(.linkPreview(_)):
                print("extra")
            case .some(.custom(_)):
                print("extra")
            }
```
