### ISSUE TITLE
How change the color of the navigationbar when scrollview is scrolled up

### ISSUE THREAD

**Issue by Kuro7070** [MessageKit/MessageKit#1762]
Hi, I'm trying to change the color of my navigationBar in my chatview. The default value is already changed, but when I'm scrolling to the end, the color changes to white/translucent. Could someone help me? Thx :)

<img width="369" alt="Bildschirmfoto 2022-11-23 um 12 17 21" src="https://user-images.githubusercontent.com/61473335/203533819-2563c7e7-008a-4a83-ad1f-caf26fa46951.png">

<img width="367" alt="Bildschirmfoto 2022-11-23 um 12 17 34" src="https://user-images.githubusercontent.com/61473335/203533776-04a79e43-5a06-475c-b7e8-9e3143aed364.png">

**Comment by Kuro7070** [comment]
I solved it by my self. Maybe this helps someone later
solution:
```        let appearance = UINavigationBarAppearance()
        appearance.configureWithOpaqueBackground()
        appearance.backgroundColor = UIColor(named:"c_black")
        navigationController?.navigationBar.standardAppearance = appearance;
        navigationController?.navigationBar.scrollEdgeAppearance = navigationController?.navigationBar.standardAppearance```

**Comment by scottishwilly90009** [comment]
Hello
