### ISSUE TITLE
Support for Cocoapods in case we have to use it?

### ISSUE THREAD

**Issue by sunil-app** [MessageKit/MessageKit#1765]
Thank you for the wonderful library!

I wonder why have we removed support for the Cocoapods? I know SPM is really good and I have been MessageKit through SPM ever since. 

Ever since Xcode 14 has arrived, I have trouble building the MessageKit with the Azure pipeline with following error:

```
/Users/runner/Library/Developer/Xcode/DerivedData/<App>-hdgndojekdcpbqanrtalixkifyxd/SourcePackages/checkouts/MessageKit/Package.swift: error: MessageKit_MessageKit does not support provisioning profiles. MessageKit_MessageKit does not support provisioning profiles, but provisioning profile Adhoc has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target 'MessageKit_MessageKit' from project 'MessageKit')
```

This seems [a known issue](https://developer.apple.com/forums/thread/700327). I tried to fix this issue but could not find how to fix this. (considering that I have to use manual signing).

If we were still supporting the Cocoapods today, the MessageKit would be working just fine in case there are any such issues with SPM.

**Comment by Kaspik** [comment]
Hey @sunil-app ! I'm not aware of any issue with MessageKit & SPM.

We dropped it to simplify things and development, like not having project file, not maintaining two ways etc.

How did you setup MessageKit via SPM, can you post some code so we can figure this thing out for you?

**Comment by scottishwilly90009** [comment]
Hello how can I help you
