### ISSUE TITLE
How to display that user is typing? (like in iMessage)

### ISSUE THREAD

**Issue by IKorabel** [MessageKit/MessageKit#1768]
Hello. How can I display that a user is typing?
A user in my application interacts with a bot. I want to show that the bot is typing his reply while responding to the server.

**Comment by Kaspik** [comment]
Check the Advanced example, it uses typing indicator as well.

**Comment by IKorabel** [comment]
I did but because of multithreading error, indicator couldn't be correctly presented

**Comment by Kaspik** [comment]
I'm not sure what you mean, UI changes need to be happening on Main thread always?
