### ISSUE TITLE
Slack Invite Links are Expired

### ISSUE THREAD

**Issue by monstermac77** [MessageKit/MessageKit#1782]
In the [ReadMe](https://github.com/MessageKit/MessageInputBar#readme) one line reads "Come join us on Slack and 🗣 don't be a stranger" and another "Interested in contributing to MessageKit? Click here to join our Slack."

Both of the links (https://join.slack.com/t/messagekit/shared_invite/MjI4NzIzNzMyMzU0LTE1MDMwODIzMDUtYzllYzIyNTU4MA) are expired. 

If the Slack is still active, I'm sure many would like to join for support / to contribute.

**Comment by fhernandezKt88** [comment]
Hi, could anyone fix this please ?

**Comment by monstermac77** [comment]
If a maintainer could let us know if there even is a Slack, then we can close this. I can also create one and market it to others so that we can get a more real-time community going.

**Comment by monstermac77** [comment]
This was fixed in https://github.com/MessageKit/MessageKit/pull/1396, thanks @artemas-radik and @kinoroy.
