### ISSUE TITLE
Make KeyboardManager public

### ISSUE THREAD

**Issue by arguiot** [MessageKit/MessageKit#1785]
Hello, would it be possible to make the KeyboardManager public? Many people are complaining in the issues with bottom space and how to handle it: #1779. I had this issue personally, and the only way I fixed it was by accessing the `keyboardManager` object and rebind the inputAccessory like this:
```
keyboardManager.bind(inputAccessoryView: inputContainerView) { -50 }
keyboardManager.shouldApplyAdditionBottomSpaceToInteractiveDismissal = true
```
The problem is that to achieve this, you necessarily need to import MessageKit this way:
```
@testable import MessageKit
```
Which is not super nice...

**Comment by Kaspik** [comment]
https://github.com/MessageKit/MessageKit/commit/439bb19a6f37b574f91955b32fc4c466e5608d5c
