### ISSUE TITLE
Advanced Example crashes when typing indicator is hidden

### ISSUE THREAD

**Issue by laud** [MessageKit/MessageKit#1787]
👻
**Describe the bug**
Advanced Example crashes when typing indicator is hidden

**To Reproduce**
Steps/code to reproduce the behavior:
1. Open the example app
2. Navigate to Advanced Example
3. Typing indicator shows. Upon indicator hide, the app crashes.

**Expected behavior**
The indicator should not crash on hide.

**Screenshots**
<img width="1795" alt="Screen Shot 2023-04-10 at 4 23 57 PM" src="https://user-images.githubusercontent.com/858939/231017679-4060beed-c5f9-4632-84e4-f2e735404231.png">

**Environment**
- What version of MessageKit are you using? latest commit
- What version of iOS are you running on? iOS 16.4.1
- What version of Swift are you running on? Swift 5.8
- What device(s) are you testing on? Are these simulators? On Device
- Is the issue you're experiencing reproducible in the example app? Yes, it crashes on the example app

**Additional context**
The problem is partially solved when animation is set to `false`. However, other cases of the app crashing due to improper index still occurs (e.g. sending a message when indicator is visible).

**Comment by jwamin** [comment]
💯 

We got around this by removing the inline typing indicator on our integration, having discovered the issue exists in the sample app too.

Was just about to raise myself. 👍

**Comment by laud** [comment]
I would like to use the inline typing indicator for my own project. I was able to patch the crash with following changes, but it seems brittle.

```
diff --git a/Example/Sources/Layout/CustomMessageFlowLayout.swift b/Example/Sources/Layout/CustomMessageFlowLayout.swift
index e2d7d452..6ae73111 100644
--- a/Example/Sources/Layout/CustomMessageFlowLayout.swift
+++ b/Example/Sources/Layout/CustomMessageFlowLayout.swift
@@ -33,6 +33,9 @@ open class CustomMessagesFlowLayout: MessagesCollectionViewFlowLayout {
     if isSectionReservedForTypingIndicator(indexPath.section) {
       return typingIndicatorSizeCalculator
     }
+      if indexPath.section >= messagesDataSource.numberOfSections(in: messagesCollectionView) {
+          return typingIndicatorSizeCalculator
+      }
     let message = messagesDataSource.messageForItem(at: indexPath, in: messagesCollectionView)
     if case .custom = message.kind {
       return customMessageSizeCalculator
diff --git a/Sources/Controllers/MessagesViewController+TypingIndicator.swift b/Sources/Controllers/MessagesViewController+TypingIndicator.swift
index 44107340..1358561e 100644
--- a/Sources/Controllers/MessagesViewController+TypingIndicator.swift
+++ b/Sources/Controllers/MessagesViewController+TypingIndicator.swift
@@ -55,6 +55,7 @@ extension MessagesViewController {
     if animated {
       messagesCollectionView.performBatchUpdates({ [weak self] in
         self?.performUpdatesForTypingIndicatorVisability(at: section)
+          messagesCollectionView.reloadData()
         updates?()
       }, completion: completion)
     } else {

```

Specifically, something has changed with the collectionView layout implementation such that a full `reloadData` is needed before continuing with updates.

**Comment by DanielSP99** [comment]
same bug :(

**Comment by Kaspik** [comment]
I believe this is now fixed in the advanced example. :)
