### ISSUE TITLE
need first Message to be on Bottom , usually messaging started from top in   MessageKit

### ISSUE THREAD

**Issue by MhmadRaziq** [MessageKit/MessageKit#1791]
<img width="393" alt="Screen Shot 1444-10-09 at 7 06 40 PM" src="https://user-images.githubusercontent.com/76057495/235312320-8563a6ca-052c-481d-88bd-d9464297c9dc.png">

**Comment by Kaspik** [comment]
Just add the offset based on calculation, there is no plan to implement this out of the box. :)
