### ISSUE TITLE
input bar top stack causing large gap to collection view

### ISSUE THREAD

**Issue by alsharda** [MessageKit/MessageKit#1796]
**Describe the bug**
I am experiencing an issue with MessageKit where adding a top stack view to the message input bar (of height 44) is causing a large gap to appear between the keyboard and the message collection view when the keyboard is shown.

**To Reproduce**
Steps/code to reproduce the behavior:

`func configureAttachmentToolbar() {
        let testUI = AttachmentMenuViewController()

       testUI.translatesAutoresizingMaskIntoConstraints = false
        
        messageInputBar.topStackView.addArrangedSubview(testUI)

        NSLayoutConstraint.activate([
            testUI.heightAnchor.constraint(equalToConstant: 44),
            testUI.widthAnchor.constraint(equalToConstant: self.view.frame.width),
        ])

private func configureMessageInputBar() {
       configureAttachmentToolbar()
        messageInputBar.inputTextView.isUserInteractionEnabled = true
        messageInputBar.isHidden = false
        attachButton.image = UIImage(named: "attach")
        attachButton.setSize(CGSize(width: 36, height: 36), animated: false)
        attachButton.addTarget(self, action: #selector(actionAttachMessage), for: .touchUpInside)

        recordButton.image = UIImage(named: "recorder")
        recordButton.backgroundColor = .clear
        recordButton.setSize(CGSize(width: 34, height: 34), animated: false)
        recordButton.anchor(paddingBottom: 45)
        recordButton.addTarget(self, action: #selector(recordTapped), for: .touchUpInside)
        recordButton.isHidden = false
        
        pauseButton.image = UIImage(named: "pauseRecorder")
        pauseButton.setSize(CGSize(width: 40, height: 40), animated: false)
        pauseButton.addTarget(self, action: #selector(stopTapped), for: .touchUpInside)
        pauseButton.isHidden = true
       
        var configuration = UIButton.Configuration.filled()
        configuration.baseBackgroundColor = .clear
        configuration.baseForegroundColor = .clear
        configuration.contentInsets = NSDirectionalEdgeInsets(top: 0, leading: 0, bottom: 5, trailing: 0)
        recordButton.configuration = configuration
        configuration.contentInsets = NSDirectionalEdgeInsets(top: 0, leading: 0, bottom: 5, trailing: 0)
        pauseButton.configuration = configuration
        
        messageInputBar.inputTextView.placeholder = "Say something fun..."
        messageInputBar.setStackViewItems([attachButton], forStack: .left, animated: false)

        messageInputBar.setLeftStackViewWidthConstant(to: 36, animated: false)
        messageInputBar.contentView.backgroundColor = .clear
        messageInputBar.inputTextView.layer.borderColor = UIColor.clear.cgColor
        messageInputBar.inputTextView.layer.borderWidth = 3
        messageInputBar.inputTextView.layer.cornerRadius = 16
        messageInputBar.inputTextView.placeholderLabelInsets = UIEdgeInsets(top: 8, left: 100, bottom: 8, right: 36)
        messageInputBar.inputTextView.isImagePasteEnabled = false
        messageInputBar.inputTextView.backgroundColor = UIColor(red: 142/255.0, green: 120/255.0, blue: 244/255.0, alpha: 0.04)
        messageInputBar.inputTextView.textContainerInset = UIEdgeInsets(top: 8, left: 16, bottom: 8, right: 16)
        messageInputBar.isTranslucent = true
        messageInputBar.inputTextView.textColor = .white
        messageInputBar.sendButton.setTitleColor(UIColor(red: 142/255.0, green: 120/255.0, blue: 244/255.0, alpha: 1), for: .normal)
        messageInputBar.sendButton.setTitleColor(UIColor.white.withAlphaComponent(0.3), for: .disabled)
        messageInputBar.sendButton.setImage(nil, for: .normal)
        messageInputBar.sendButton.setTitle("Send", for: .normal)
        messageInputBar.sendButton.titleLabel?.font = UIFont.systemFont(ofSize: 16)
        messageInputBar.separatorLine.isHidden = true
        messageInputBar.sendButton.isHidden = true

        messageInputBar.setStackViewItems([recordButton, messageInputBar.sendButton, pauseButton], forStack: .right, animated: false)
    }
       `

**Expected behavior**
The issue appears to be related to how the intersection of the keyboard frame with the collection view frame is calculated and used to adjust the content inset of the collection view.

In particular, when a top stack view is added to the message input bar, the calculation does not seem to take this into account, leading to the gap between the keyboard and the collection view.

**Screenshots**
(1) this is a screenshot before the keyboard appears

![IMG_9005](https://github.com/MessageKit/MessageKit/assets/113173568/1a63cb2a-326e-4973-98de-f1b1f81d09c9)

(2) this is a screenshot after keyboard appears showing large gap
![IMG_9004](https://github.com/MessageKit/MessageKit/assets/113173568/8778857d-5fd8-4cbd-b51e-39b26a23a6c3)

**Environment**
- What version of MessageKit are you using?
- Latest release
- What version of iOS are you running on?
- iOS 16.5
- What version of Swift are you running on?
- 14.2
- What device(s) are you testing on? Are these simulators?
- Physical device - iphone 13

**Additional context**
We went through the calculations made by requiredScrollViewBottomInset(forKeyboardFrame:) and requiredInitialScrollViewBottomInset() in MessageKit to understand what's happening.

We found that the calculation of the intersection of the keyboard frame with the collection view frame seems to be correct, but the resulting adjustment of the content inset of the collection view is causing the view to appear too far above the keyboard.

We observed that the method requiredScrollViewBottomInset(forKeyboardFrame:) wasn't falling into the condition where the keyboard is hidden, is a hardware one, or is undocked and does not cover the bottom of the collection view (option 1). Instead, it was always going to the else condition (option 2).

**Here are the frames of the keyboard and collection view:**
I printed the result of each variable before and after the keyboard appears (top is before & bottom is after)

keyboardEndFrame: (0.0, 713.3333333333334, 390.0, 130.66666666666663)
keyboardEndFrame: (0.0, 511.9999999999999, 390.0, 432.66666666666674)

intersection: (0.0, 713.3333333333334, 390.0, 130.66666666666663)
intersection: (0.0, 511.9999999999999, 390.0, 332.0000000000001)

automaticallyAddedBottomInset: 34.0
automaticallyAddedBottomInset: 34.0

option 2: 130.66666666666663 , 0.0 , 34.0
option 2: 332.0000000000001 , 0.0 , 34.0

automaticallyAddedBottomInset: 34.0
automaticallyAddedBottomInset: 34.0

newBottomInset: 96.66666666666663
newBottomInset: 298.0000000000001

messageCollectionViewBottomInset: 0.0
messageCollectionViewBottomInset: 96.66666666666663

newBottomInset: 96.66666666666663
newBottomInset: 298.0000000000001

contentOffset: (0.0, 5.666666666666629)
contentOffset: (0.0, 218.00000000000014)

Intersection calculation:  let intersection = messagesCollectionView.frame.intersection(keyboardFrame)
Resulting adjustment: return max(0, intersection.height + additionalBottomInset - automaticallyAddedBottomInset)

This leads to an adjustment of 332.0, which is causing the collection view to appear too far above the keyboard.

It appears that the additionalBottomInset and automaticallyAddedBottomInset values are not affecting the calculation, as they are both 0.0 and 34.0 respectively in all cases.

**Comment by alsharda** [comment]
Found out it was because of IQKeyboardManager pod. I had to set
`        IQKeyboardManager.shared.enable = false
        IQKeyboardManager.shared.enableAutoToolbar = false`
when loading my chat view.

**Comment by tugsadsen** [comment]
> Found out it was because of IQKeyboardManager pod. I had to set ` IQKeyboardManager.shared.enable = false IQKeyboardManager.shared.enableAutoToolbar = false` when loading my chat view.

It worked, thank you
