### ISSUE TITLE
Vulnerability Disclosure

### ISSUE THREAD

**Issue by aviadhahami** [MessageKit/MessageKit#1817]
Hi folks,
I wanted to know where should one report security vulnerabilities in this project, thx!

**Comment by Kaspik** [comment]
Open an issue or a PR with a fix.

**Comment by aviadhahami** [comment]
Hi @Kaspik, I believe a discrete disclosure is more appropriate in this case. Is there another option? (discord etc)

**Comment by Kaspik** [comment]
Email, Twitter, Slack (MessageKit has a Slack workspace).

**Comment by aviadhahami** [comment]
The Slack link is invalid :\ https://join.slack.com/t/messagekit/shared_invite/MjI4NzIzNzMyMzU0LTE1MDMwODIzMDUtYzllYzIyNTU4MA

**Comment by Kaspik** [comment]
https://join.slack.com/t/messagekit/shared_invite/zt-2484ymok0-O82~1EtnHALSngQvn6Xwyw
