### ISSUE TITLE
Introduce PrivacyManifest

### ISSUE THREAD

**Issue by SGA-Kosuke-Machida** [MessageKit/MessageKit#1829]
Hello, do you have a plan to introduce PrivacyManifest?

If it is not added by spring 2024, apps using this library will be rejected, I think.

It's described here in detail.
https://developer.apple.com/news/?id=r1henawx
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests

Thank you.

**Comment by Kaspik** [comment]
Yeah, we can do that this week. So far I'm probably aware only of `NSPrivacyCollectedDataTypeOtherUserContent`?

**Comment by Kaspik** [comment]
Actually thinking about this more - do we need this for this framework? It's not using the API mentioned afaik (correct me!) nor it collects any data.

**Comment by crisp** [comment]
Looks like it's just in the example app, please confirm

**Comment by Kaspik** [comment]
Yeah I believe so.
