### ISSUE TITLE
Could not find module 'MessageKit' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator

### ISSUE THREAD

**Issue by chunxige** [MessageKit/MessageKit#1834]
Failed to compile on the apple simulator 
version: 4.2

**Comment by NitinManageCaptive** [comment]
same issue

**Comment by Tymoteusz24** [comment]
same bug

**Comment by Kaspik** [comment]
I don't think this is wrong setup of MessageKit but more of the project itself?

Related: https://stackoverflow.com/questions/56957632/could-not-find-module-for-target-x86-64-apple-ios-simulator
