### ISSUE TITLE
Project setup issue with package dependency

### ISSUE THREAD

**Issue by NitinManageCaptive** [MessageKit/MessageKit#1838]
### Discussed in https://github.com/MessageKit/MessageKit/discussions/1837

<div type='discussions-op-text'>

<sup>Originally posted by **NitinManageCaptive** May  9, 2024</sup>
Could not find module 'MessageKit' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at: /Users/mcs/Library/Developer/Xcode/DerivedData/HLP-ctczrmrozfgbkcfmbslkcnsjavoe/Index.noindex/Build/Products/Debug-iphonesimulator/MessageKit.swiftmodule

I am using Xcode 15.3 with apple m2 macOS sonoama 14.4.1</div>

**Comment by Kaspik** [comment]
Not aware of any issue so this will be something specific for your project setup.
