### ISSUE TITLE
Simple UIButton in the cell

### ISSUE THREAD

**Issue by st-small** [MessageKit/MessageKit#1840]
Hi folks!
I'm using custom cell and wonder how to add there any button. I want to get native animation when user makes touch up inside and get the touch in the selector method. 
1. I have added button, it shows but no animation and trigger didn't interact. 
2. I have overrided `func hitTest(_ point: CGPoint, with event: UIEvent?)` it helps to show button animation but trigger still doesn't work.

So I want to ask what happened with selector, why it doesn't work?

Thanks in advance.

My button:
```swift
private var retryButton: UIButton = {
        let retry = UIButton(type: .system)
        retry.translatesAutoresizingMaskIntoConstraints = false
        retry.backgroundColor = .white
        retry.layer.cornerRadius = 20
        retry.isUserInteractionEnabled = true

        return retry 
}()
```

**Comment by gerchicov-vg** [comment]
@st-small how did you you resolve this issue?

**Comment by st-small** [comment]
@gerchicov-vg Yes, thank you!

**Comment by gerchicov-vg** [comment]
@st-small ?

**Comment by st-small** [comment]
@gerchicov-vg I'm sorry, I misunderstood your question. 
At first it is need to read sample project more deeper. 
1. `MessagesCollectionView` file there function `handleTapGesture`
2. Function `handleTapGesture` needs to pass into every collectionView cell
3. Parent message cell class (MessageContentCell) should has implementation to get all gestures
4. Child message cells (that inherited from `MessageContentCell`) should override that function

**Comment by gerchicov-vg** [comment]
@st-small in my code `handleTapGesture` exists (my custom cell is inherited from `MessageContentCell`) but it is not called at all.
I found another solution - to override cell's `hitTest`, manually check if a location belongs to my view with my buttons and return this view if necessary. But it looks weird to manually route a touch to a destination view.

**Comment by st-small** [comment]
@gerchicov-vg As I saw in the sample project, it should be like you described.

This is example from the `MediaMessageCell`
```swift
open override func handleTapGesture(_ gesture: UIGestureRecognizer) {
    let touchLocation = gesture.location(in: imageView)

    guard imageView.frame.contains(touchLocation) else {
      super.handleTapGesture(gesture)
      return
    }
    delegate?.didTapImage(in: self)
  }
```
