### ISSUE TITLE
version >= 4.0: “Breaking change: Dropped CocoaPods support”

### ISSUE THREAD

**Issue by Jacky-LinPeng** [MessageKit/MessageKit#1841]
My project uses the Cocopods management tripartite library, and now the latest 4.x version does not support cocopods. How do I use the latest version?

Note:
My local podspc relies on 'MessageKit' : spec.dependency 'MessageKit','4.2.0'

**Comment by Kaspik** [comment]
You can't. You can switch to SPM instead of CocoaPods, but is has been dropped almost 2 years ago. :)
