### ISSUE TITLE
Overriding inputAccessoryView property results in application freeze and crash after about a minute

### ISSUE THREAD

**Issue by maazsurti** [MessageKit/MessageKit#1846]
**Describe the bug**

In MessageContainerController, 

this code:
```
/// Required for the `MessageInputBar` to be visible
override var inputAccessoryView: UIView? {
   conversationViewController.inputAccessoryView
 }
```
causes the app to freeze completely and then produces an `EXC_BAD_ACCESS` crash

**To Reproduce**
Steps/code to reproduce the behavior:

Open the "Embedded Example" in the example app.

**Expected behavior**
To open and function normally

**Screenshots**
![Screenshot 2024-06-11 at 7 53 33 PM](https://github.com/MessageKit/MessageKit/assets/98577646/a9915149-e48c-4184-ace1-2ec007b63776)

**Environment**
- What version of MessageKit are you using? 
5.15.18
- What version of iOS are you running on? 
17.2
- What version of Swift are you running on?
5.9.2
- What device(s) are you testing on? Are these simulators?
Yes, iPhone 15 simulator, running on iOS 17.2
- Is the issue you're experiencing reproducible in the example app?
Yes

**Additional context**

I installed the package using SPM

**Comment by fukemy** [comment]
Does your class `ExampleBasicViewController` extend the `ChatViewController`?
the key is here: https://github.com/MessageKit/MessageKit/blob/75215ecfc849b084049017cc81f0b7213775ed7f/Example/Sources/View%20Controllers/BasicExampleViewController.swift#L30-L40

**Comment by maazsurti** [comment]
> Does your class `ExampleBasicViewController` extend the `ChatViewController`? the key is here:
> 
> https://github.com/MessageKit/MessageKit/blob/75215ecfc849b084049017cc81f0b7213775ed7f/Example/Sources/View%20Controllers/BasicExampleViewController.swift#L30-L40

This is the example code provided in the package itself, as I have mentioned already.
To answer your question, yes.

**Comment by MiteshiOS** [comment]
@maazsurti It seems like there are some internal issues with the library itself. Any luck on a solution?

**Comment by Kaspik** [comment]
I updated some of the examples code but I'm not able to repro this. What's needed to repro?

**Comment by MiteshiOS** [comment]
This is the official Chat Example provided in the repo itself.
To reproduce please follow these steps.

1) Go to MessageKit-main -> Example -> ChatExample.xcworkspace
2) Run the project
3) Select Embedded Example
4) On navigating to the Embedded example screen try to type something in the typing area.
Example app will crash due to above mentioned reason

**Comment by Kaspik** [comment]
The example app has been fixed and master updated to use newer fixed IBAV SPM. The override in this case is not needed and actually wrong.

Will leave on master for a while for testing.

**Comment by MiteshiOS** [comment]
Thank you for the quick fixes and updates @Kaspik
