### ISSUE TITLE
Disable the bot which closes issues in this repo with timeout

### ISSUE THREAD

**Issue by gerchicov-vg** [MessageKit/MessageKit#1851]
There are a lot of unresolved problems which are closed with no solution

**Comment by Kaspik** [comment]
They are not closed if there is label assigned.

**Comment by gerchicov-vg** [comment]
@Kaspik I see a lot of "closed" issues with different labels - `bug?`, `SwiftUI`, `question` and etc. They are also labeled as "stale" and closed by timeout

**Comment by Kaspik** [comment]
Yeah "bug?" is not confirmed bug thus marked as close if not more interaction by the time.
