### ISSUE TITLE
Swift 6 (xcode 16) Support! 

### ISSUE THREAD

**Issue by AndreParenteNeon** [MessageKit/MessageKit#1864]
seems the build is broken for swift 6 support, a lot of properties cannot be referenced from a nonisolated context..  

Example: Main actor-isolated property 'messagesDataSource' can not be referenced from a nonisolated context

**Comment by Kaspik** [comment]
Duplicate.

**Comment by Kaspik** [comment]
MessageKit is not yet updated for Xcode 16.

**Comment by AndreParenteNeon** [comment]
thanks @Kaspik!
