### ISSUE TITLE
The bubble arrow is in the wrong direction

### ISSUE THREAD

**Issue by xingmanlou** [MessageKit/MessageKit#1869]
**Screenshots**
![Simulator Screenshot - iPhone 16 Pro - 2024-10-30 at 11 02 12](https://github.com/user-attachments/assets/8a8d50d1-d0ea-476d-955b-faa6373830c9)

**Environment**
- What version of MessageKit are you using? 
--> 4.3.0,This is correct in version 4.2.0

- What version of iOS are you running on? 
-->18.0,18.1, 17.5.1 (xcode16,xcode16.1)

- What version of Swift are you running on? 
- -> swift5

- What device(s) are you testing on? Are these simulators?
--> iphone11 and simulator

- Is the issue you're experiencing reproducible in the example app?
--> yes

**Comment by Kaspik** [comment]
Isn't this only bug in the example project, not in the library itself?

https://github.com/MessageKit/MessageKit/commit/587a60f27367cc95fc65d7a6e39a4c5aa6c4ef59
