### ISSUE TITLE
[Bug] Layout is off when in landscape mode

### ISSUE THREAD

**Issue by pinchih** [MessageKit/MessageKit#19]
Not sure if MessageKit will support landscape mode in the future, but it's not displayed correctly at this point. ( v0.1.0 )

![simulator screen shot jul 31 2017 3 37 28 pm](https://user-images.githubusercontent.com/12094516/28801568-01aa4922-7607-11e7-8d63-4e91da80542c.png)
# #

**Comment by SD10** [comment]
Definitely a priority 👍 Thank you

**Comment by SD10** [comment]
This should be taken care of by `bcbdf4b` on `v0.2.0`. 
Also, referencing #12 since this was discussed there.
