### ISSUE TITLE
Ability to add typing indicator view

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#191]
### Support typing indicator view
![e3ff80b2-b56f-11e5-8397-0778e70e922a](https://user-images.githubusercontent.com/7445580/30995276-b26be9a0-a47e-11e7-9514-c4571749db87.gif)

It would be nice if it's animated 😉
I think @nathantannar4 was discussing this but he had some pretty crazy ideas.

I also think it would be nice to be able to display the avatar bubble on the typing indicator. I think there is another JSQMVC issue related to this. EDIT: [#1251](https://github.com/jessesquires/JSQMessagesViewController/issues/1251)

Related issues:
[Typing Indicator Animated #1382](https://github.com/jessesquires/JSQMessagesViewController/issues/1382)

**Comment by nathantannar4** [comment]
I am studying for a Microsoft interview this weekend. I will try to find time next week to look into future enhancements to the MessageInputBar. Will probably try to support the typing bubble and the slack style indicator. Probably slack style first to get the logic down.

**Comment by SD10** [comment]
@nathantannar4 No worries, open source is for fun - not a job 😃 I'm still unsure if we want to but the typing bubble in the MessageInputBar. It doesn't make sense to me as of now

**Comment by mehul-singhal** [comment]
@nathantannar4 I would like to work with you you guys in making typing indicator view. Give me some time and i will send you guys a pull request.
Thanks

**Comment by nathantannar4** [comment]
Cool! I am working on a more refined version of my autocomplete

**Comment by SD10** [comment]
@DrunkenLord Do you have any idea how you would implement this? We're discussing in Slack how to go about this feature. It has to fit with everything else we're doing in the library.

**Comment by mehul-singhal** [comment]
@SD10 I have worked with typing indicator in a small application which i built in a hackathon. I will be adding an end point on the server, Triggering pusher from application while typing and some other things. If you want i can join the slack and we can discuss it over there and decide if you want me to go in the direction to work on it or not.

**Comment by nathantannar4** [comment]
@DrunkenLord this is just a chat UI library. We do not handle server endpoints to see if someone is typing. We simply need a `showTypingIndicator: Bool` which inserts or removes an indicator cell from the collection view

**Comment by mehul-singhal** [comment]
@nathantannar4 I am sorry i didn't knew about it. We can choose to use the `showTypingIndicator: Bool`. It should not be a issue i guess. I haven't worked on it before though.

**Comment by jaunesarmiento** [comment]
I made some progress adding a typing indicator to the app I'm working on. It's very simple but there's a lot of hardcoded values for frames and positioning. Some questions popped up while working on it though:
1. Should the typing indicator view be a footer view? Or a fully custom supplementary view?
2. Should the typing indicator look like the normal message bubble or do we allow customization here? We can add something like `func messageStyleForTypingIndicator() -> MessageStyle` to `MessagesDisplayDelegate` to allow customization.

**Comment by jbouaziz** [comment]
Just a thought but I'd simplify it and add a label above the `messageInputBar` with the name of users typing.

**Comment by SD10** [comment]
We've discussed adding a typing indicator but haven't gotten around to it. I think we decided on inserting a cell at the very bottom of `MessagesCollectionView` for this.

As @jbouaziz mentioned, you can also add a view as part of the `topStackView` in the `MessageInputBar`. This is very similar to the Slack style typing indicator. I don't think we'll provide first class support for this style, because it:

a) Reserves the top stack view
b) Is very easy to do outside the library

**Comment by otymartin** [comment]
@SD10 @nathantannar4 
Just curious if the animated iMessageStyle typing indicator is still in works

**Comment by SD10** [comment]
@otymartin We don't have first-class support for this yet. You're able to achieve either iMessage style or Slack style it if you want it though

**Comment by otymartin** [comment]
@SD10 Nice, any guide on that. Not really sure how to proceed

**Comment by SD10** [comment]
@otymartin iMessage style would likely use a cell or footer at the bottom of the `collectionView`. For the Slack style typing indicator, you would add a view to the `MessageInputBar`'s top stack view.

**Comment by kinoroy** [comment]
Since #1038 is merged, I'm closing this.
