### ISSUE TITLE
Lint project for access control & override order

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#193]
SwiftLint doesn't have a rule for this yet and the inconsistency is driving me crazy:
```Swift
// Good
public override func foo() {}

// Bad
override public func foo() {}
```

**Comment by tapanprakasht** [comment]
@SD10 I have written some custom swiftlint rule to handle mentioned the issue. This can be enhanced further. This is a just initial step. May it won't recognize all the possible scenarios as of now. After applying the rule project shows 24 new warnings. 
Can I fix that warning?

**Comment by tapanprakasht** [comment]
@SD10  I hope that requirements mentioned here are fulfilled by the PR #196. I think this issue can be closed now.

**Comment by SD10** [comment]
Great, closing this 👍
