### ISSUE TITLE
Flags to perform automatic scrolling

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#203]
### Flags to perform automatic scrolling
It would be nice to have two flags for users to control scrolling:
```Swift
var scrollToBottomOnKeyboardBeginsEditing = false
var scrollToBottomOnFirstLoad = true
```

@cwalo I think if we put the `messagesCollectionView.scrollToBottom()` call inside of the `isFirstLayout` flag in `viewDidLayoutSubviews` we don't have to do anything with calculating the `contentOffset`?

**Comment by cwalo** [comment]
@SD10 Yeah, no calculation required if done there.
