### ISSUE TITLE
Deprecate .text(String) case of MessageData

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#205]
### Deprecate .text(String) case of MessageData

We currently have two cases of the `MessageData` enum that are capable of handling text:

`.text(String)`
`.attributedText(NSAttributedString)`

The problem with the `.text(String)` case is that it requires that users set the `messageLabelFont` property of `MessagesCollectionViewFlowLayout`. If they don't this can result in unexpected behavior.

In order to counteract this problem, I suggest we remove the `.text(String)` case altogether.

**Comment by hemangshah** [comment]
@SD10, can we set the default fonts in `messageLabelFont` so then we only require to set it again if we want to change?

**Comment by SD10** [comment]
@hemangshah Yeah we have a default font already and if you want to change it you can subclass the layout object or assign a new value to the property in your view controller.

We probably won't deprecate the `String` API because some users may feel like `NSAttributedString` is unfriendly.

However, I highly encourage everyone to use `.attributedText(NSAttributedString)` for better performance.

**Comment by gungorbasa** [comment]
1 question @SD10, I am not sure but why don't we integrate `MockMessage.swift` into the framework itself and write `init` function with attributed string(Some sort of default implementation for `.text`). Sort of another abstraction layer. So user can use new message object to create type of message.

```
init(text: String, sender: Sender, messageId: String) {
        defaultAttributedText ...
	self.init(data: .attributedText(defaultAttributedText), sender: sender, messageId: messageId)
}
```

**Comment by SD10** [comment]
@gungorbasa This won't help because the core problem is that a regular `String` doesn't have any attributes. We need these attributes to size the message

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
Closing this because after discussing the topic we agreed that `String` is a far friendlier interface for users. However, it is still strongly recommended that you use `.attributedText(NSAttributedString)` where possible.
