### ISSUE TITLE
The toolbar is placed under safe area (iOS 11 iphoneX)

### ISSUE THREAD

**Issue by samsonwyt** [MessageKit/MessageKit#207]
I have tried using iphone X to test the example, and the input bar is placed under the iphone X safe area!

[https://imgur.com/a/O2s5d](url)

**Comment by alexbinary** [comment]
@samsonwyt your link is broken, looks like a Markdown problem.
Here is a working link : https://imgur.com/a/O2s5d

**Comment by nathantannar4** [comment]
Fixed in v0.10.0
