### ISSUE TITLE
Scrolling to bottom automatically?

### ISSUE THREAD

**Issue by jackdem** [MessageKit/MessageKit#214]
I want the view to scroll to most recent message when loading, at the moment it just hangs and doesnt scroll to the bottom, I cant work out how to implement this? 

also small additional query, how do i change the chat bubble colours?

Thanks!

**Comment by SD10** [comment]
Hey @jackdem,
There is currently no easy way of doing this. It will be possible in the next version 😭 
See #213  and #183

**Comment by jackdem** [comment]
whats the eta on the next version?

**Comment by SD10** [comment]
@jackdem I'm not sure on this, unfortunately. MessageKit is free open source software :( That being said, we're trying to work with a few apps using MessageKit in production so they are having a large impact on releases.

Also, these have been implemented in v0.9.0.
