### ISSUE TITLE
Slack Invite. 

### ISSUE THREAD

**Issue by MacMeDan** [MessageKit/MessageKit#22]
Hey Everyone,
 We have a slack channel secured for helping coordinating features and dev in real time. Most conversations/discussions will happen here on github and we want to keep it that way. But at times tho it can be difficult to get things merged in when there are conflicts so we have created this slack group. 

Click the link to join. Be respectful and encouraging. 

https://join.slack.com/t/messagekit/shared_invite/enQtNTU5NTQ0NTQ5OTg3LTY5NDdmZDk1NzU1YjBjZjY1MTExNzkwMjcxZTkyYzhjNzdhMTM2YzFiNzE4YmRlYjI2MjdkMWRhNGEwMjg2NDE

This link will expire a week from 9/7/2017 please message me if it past that time and you would like to join.

**Comment by xjli1972** [comment]
@MacMeDan : The Slack invitation link is no longer valid, could you please generate a new one?

**Comment by SD10** [comment]
@xjli1972 Updated 👍

**Comment by Michele404** [comment]
Update

**Comment by nathantannar4** [comment]
@Michele404 is it not working? Im not sure how to interpret your comment

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Michele404** [comment]
Yes, its not working

**Comment by nathantannar4** [comment]
https://join.slack.com/t/messagekit/shared_invite/enQtNTU5NTQ0NTQ5OTg3LTY5NDdmZDk1NzU1YjBjZjY1MTExNzkwMjcxZTkyYzhjNzdhMTM2YzFiNzE4YmRlYjI2MjdkMWRhNGEwMjg2NDE

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MacMeDan** [comment]
I updated the link in the original message.
