### ISSUE TITLE
Scroll to latest message is not happening after typing the message.

### ISSUE THREAD

**Issue by tapanprakasht** [MessageKit/MessageKit#221]
I am trying out sample Chat application inside MessageKit project and found the following behavior. After typing the message, we need to scroll the view to see the new message. I think this is not good for a chat application. The keyboard is hiding the new message. See the below workflow I have tried.
![bug](https://user-images.githubusercontent.com/4947384/31139365-f14c3350-a88e-11e7-99fc-158e0e2e4dfe.gif)

Is it a bug or Is there any configurable property to make it work?
**scrollsToBottomOnKeybordBeginsEditing** is already set to true in the sample application.

**Comment by SD10** [comment]
@tapanprakasht We're just not calling `messagesCollectionView.scrollToBottom()` after sending the message. I'm working on refactoring the example app and I guess I removed it. Regardless, user is responsible for calling this 😅

**Comment by tapanprakasht** [comment]
@SD10 I think by default in the sample app **messagesCollectionView.scrollToBottom()** should be there. Can I add this in the sample app?
