### ISSUE TITLE
Input scroll handling

### ISSUE THREAD

**Issue by HeroPD** [MessageKit/MessageKit#23]
Hi guys in this example i am demonstrated how to handle InputAccessoryView. Source code is in obj-c so feel free to convert 
[TextFieldDemo.zip](https://github.com/MessageKit/MessageKit/files/1193704/TextFieldDemo.zip)

maybe it's better using tableview instead of collectionview

**Comment by SD10** [comment]
@HeroPD We're using `UICollectionView` because it is more flexible than `UITableView` 😃

**Comment by HeroPD** [comment]
@SD10 i think `UITableView ` performance is better than `UICollectionView` so we don't need `UICollectionView` features in chat app
Well at least changing keyboard handling is important old `contentinset` approach looks crappy 😄

**Comment by SD10** [comment]
@HeroPD I'm not aware of any negative performance implications of using `UICollectionView` over `UITableView` but we will continue to use the former. 

As for keyboard handling, what we have now is rudimentary and will be looking to improve it. Thank you for raising this issue 👍 If you have any other questions, please get in contact with me on Slack.

**Comment by HeroPD** [comment]
i found bug so replace below function
```objective-c
- (void)keyboardWillShow:(NSNotification*)aNotification {
    NSDictionary* info = [aNotification userInfo];
    CGSize kbSize = [[info objectForKey:UIKeyboardFrameEndUserInfoKey] CGRectValue].size;
    NSLog(@"UIKeyboardDidShow %f", kbSize.height);
    if (_tableBottom.constant != kbSize.height) {
        CGPoint offset = _tableView.contentOffset;
        [_tableView setContentOffset:offset animated:NO];
        _tableBottom.constant = kbSize.height;
        [self.view layoutIfNeeded];
        if (_lastKeyboardHeight != kbSize.height) {
            if (kbSize.height - _lastKeyboardHeight > 0) {
                CGPoint contentOffset = CGPointMake(0, _tableView.contentOffset.y+(kbSize.height - _lastKeyboardHeight));
                if (_tableView.contentSize.height > _tableView.frame.size.height) {
                    if (_tableView.contentSize.height - _tableView.frame.size.height > contentOffset.y) {
                        [_tableView setContentOffset:contentOffset animated:NO];
                    } else {
                        [_tableView setContentOffset:CGPointMake(0, _tableView.contentSize.height - _tableView.frame.size.height) animated:NO];
                    }
                }
            }
        }
    }
    _lastKeyboardHeight = kbSize.height;
}
```

**Comment by HeroPD** [comment]
if you want i could convert it myself as challenge of swift
