### ISSUE TITLE
Keyboard will cover 4th and 5th messages in the newly initiated chat

### ISSUE THREAD

**Issue by timetraveler90** [MessageKit/MessageKit#243]
## General Information

* MessageKit Version: **0.9.0**

* iOS Version(s): **Any**

* Swift Version: **Any**

* Devices/Simulators: **Any**

* Reproducible in ChatExample? (Yes/No): **Yes**

##  What happened?
When you initiate the new chat and start sending messages, depending on the screen size, 4th and 5th messages will be covered by the keyboard until you send the new message and then, the chat view will 'jump up' so every new message will be displayed properly.
You can refer to my screenshot to see what's the issue in this case.

![issue](https://user-images.githubusercontent.com/4432648/31279155-472b33a0-aaa8-11e7-9dc4-e075833fd4ed.jpeg)

## What did you expect to happen?
To have every single message visible without keyboard covering it.

**Comment by SD10** [comment]
Hey @timetraveler90 thanks for reporting this. I'm using the example app on an iPhone 7 and can't replicate. Can you provide steps to replicate it?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
Looks like it could be a problem with an opaque nav bar and the top inset

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eduardshugar** [comment]
Same thing with opaque nav bar. Also, text color doesn't work for me with 0.9.0, it's always .darkText

**Comment by timetraveler90** [comment]
Hey, you just have to start conversation with anyone with whom you do not have previous messages. And as soon as you start typing and sending messages, you will notice that after 4th message next one or two messages, depending on the device screen size, will be covered by the keyboard. 

So if you want me to report it like a real QA, steps would be something like this:
- Start the new conversation with person with whom you don't have previously exchanged messages
- Send three to four messages and observe the chat view behavior 
- Note that keyboard is covering some of your messages
- Keep on sending few more messages and note that situation will get normalized as soon as you send 6+ messages

I was able to reproduce this issue on iPhone 5s and iPhone 6 devices, haven't tried it with iPhone 7 yet.
I hope that you have a bit clearer picture right now about this issue.

**Comment by SD10** [comment]
@pselok I think I know the problem with the text color. It could not be cast as the TextMessageDisplayDelegate in the cell.

@timetraveler90 Thank you for the detailed report 😊 I'll look into resolving this

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
@pselok You need to conform to `TextMessagesDisplayDelegate` for the textColor to take effect

**Comment by SD10** [comment]
@timetraveler90 Check out #250 should be a solution

**Comment by hemangshah** [comment]
@SD10 – this is an issue even if I don't have the default navigation bar. I am using a custom view as a navigation bar.

**Comment by SD10** [comment]
Hey @hemangshah, I submitted a patch for this but it’s very likely that you’ll have to manage the top content inset yourself when using a custom view

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
