### ISSUE TITLE
using CollectionView in viewController which extends MessageViewController

### ISSUE THREAD

**Issue by amirhosseinpy** [MessageKit/MessageKit#246]
I want to add a gif bar for gif mode but I can not use collectionView for the bar how can I do that?

**Comment by SD10** [comment]
Hey @amirhosseinpy, would adding a subview to overlay the collectionView work for you? 

You can set the `additionalTopContentInset` property to the height of your subview to account for the height. Then position the subview accordingly.

**Comment by amirhosseinpy** [comment]
The problem is I can not add UICollectionView delegate and dataSource functions to my UIControllerView.

**Comment by SD10** [comment]
@amirhosseinpy You should be able to `override` the `UICollectionView` methods that MessageKit uses but I can't promise this will be easy. You will have to make your changes and then call the `super` implementation to handle the MessageKit components.

**Comment by nathantannar4** [comment]
Going to close this for now. Please let us know if you have any further issues and for all questions we encourage the use of our Slack channel!
