### ISSUE TITLE
Adding transactional message cell

### ISSUE THREAD

**Issue by famAlex** [MessageKit/MessageKit#254]
I believe that a transactional message cell would be useful to support scenarios like bot integrations or commercial conversations: sellers/bots propose a multi-options menu to chose from either to drive end user or to finalize a sale.
It could be a cell containing just an image and a button (selling an item), a carousel of images with associated buttons or just buttons for predetermined actions.

**Comment by SD10** [comment]
@famAlex This seems a little bit specialized for the scope of the library. Have any example UI?

**Comment by famAlex** [comment]
@SD10 Sure! Here an example from https://messenger.fb.com : 

<img width="265" alt="schermata 2017-10-11 alle 12 08 52" src="https://user-images.githubusercontent.com/13166743/31434683-57810396-ae7d-11e7-9a7f-6ea612887dc3.png">

<img width="297" alt="schermata 2017-10-11 alle 12 08 32" src="https://user-images.githubusercontent.com/13166743/31434691-5b806a7c-ae7d-11e7-9e66-d0f2435c18a6.png">

I agree with you that it could sound a specific use case for the library but at the same time - in my opinion- we are facing  a spread of driven conversations in any scenario where a piece of business is involved (faqs, hybrid customer support, bots, automatic responders, purchase-flows) this is why I thought it could be an interesting functionality for the community to take in account in a future.
Anyway thanks for having me driven in the right section ;-) 
Kind regards
Alessandro

**Comment by cwalo** [comment]
@famAlex I don't necessarily see anything preventing you from creating a custom cell to achieve this behavior. I am already using a few. First-class support for these things feels like a slippery slope...

**Comment by nathantannar4** [comment]
@famAlex This was a good suggestion but as @cwalo said its a slippery slope for first-class support. We use a UICollectionView so you can register your own cells and return them for this functionality!

Going to close this for now. Please let us know if you have any further issues and for all questions we encourage the use of our Slack channel!

**Comment by nathantannar4** [comment]
@SD10 gotcha keep feature requests open

**Comment by famAlex** [comment]
Many thanks @nathantannar4, I'll follow your suggestion about extending the functionality by myself.
(and sorry if I asked in the wrong place).
Kind regards 
Alessandro

**Comment by SD10** [comment]
I really see no reason to add this after #579 because MessageKit users can pretty much create any cell they'd like and pass along any information using `MessageData.custom(Any?)`. Given that this is such a specific request, I don't think that MessageKit could do as well of a job as the client themselves
