### ISSUE TITLE
Streamlining build infrastructure

### ISSUE THREAD

**Issue by tapanprakasht** [MessageKit/MessageKit#255]
I see some inconsistencies in the current build infrastructure MessageKit is using. In MessageKit GitHub homepage [build](https://travis-ci.org/MessageKit/MessageKit) link leads to Travis page and code coverage is 100% which is incorrect. When we do pull request, verification build is done using buddy build. 
I saw recent test case failure due to refactoring (#245) which is uncaught by build infrastructure. This means test targets are not running while doing the merge or pull. 
@SD10 I have following suggestions to resolve this.

- Use one build infrastructure throughout the project.

- Verify test targets are running properly for each merge/pull request

- Use the codecov tool properly.

**Comment by SD10** [comment]
Thanks @tapanprakasht 👍 The thing is we don’t really have any tests so it’s not that important to me right now. We will be using buddy build for CI but it’s good to keep our .travis.yml in case we need it. I think this would be good to re-evaluate after I merge the open PR regarding testing

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by martinpucik** [comment]
This was resolved by moving to Github Actions
