### ISSUE TITLE
When loading a MessageViewController using a "segue" or as a subview, components are not loaded 

### ISSUE THREAD

**Issue by zikossnake** [MessageKit/MessageKit#256]
## General Information

* MessageKit Version: 0.9.0

* iOS Version(s): 11

* Swift Version: 4

* Devices/Simulators: iPhone 8s

* Reproducible in ChatExample? (Yes/No): Yes

##  What happened?

when I am either loading the conversationViewController as a subview or with a segue, the component for input bar and messages are not loaded. the collectionView is loaded because I managed to color it (self.messagesCollectionView.backgroundColor = UIColor.red), but as I said I just have a blank screen.
The only way to make it works is by pushing it (navigationController?.pushViewController(ConversationViewController(), animated: true)), but I would like to load it using segue

**Comment by nathantannar4** [comment]
Are you able to share your code for how you are using a segue?

**Comment by nathantannar4** [comment]
Going to close this for now. Please let us know if you have any further issues and for all questions we encourage the use of our Slack channel!
