### ISSUE TITLE
ChatExample's messageList didSet causes code to run on non-ui thread

### ISSUE THREAD

**Issue by candiun** [MessageKit/MessageKit#257]
## General Information

* MessageKit Version: 0.9.0

* iOS Version(s): All

* Swift Version: All

* Devices/Simulators: All

* Reproducible in ChatExample? (Yes/No): Yes

##  What happened?

The main thread sanitizer detected that code did not run on the main UI thread.

## What did you expect to happen?

The code should have ran on the main UI thread

**Comment by SD10** [comment]
Hey @evilmint thanks for reporting this 👍 it has already been fixed in the upcoming version

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
