### ISSUE TITLE
Run Code When MessageCell Added?

### ISSUE THREAD

**Issue by carson-katri** [MessageKit/MessageKit#259]
How do I run code when a cell is created? I need to change some things on the message label itself.

**Comment by SD10** [comment]
Hey @CTKRocks can you be more specific or give me a little more information? I'm having trouble understanding what you're trying to do.

**Comment by azurechen** [comment]
@SD10 Do you consider adding a method in MessageDataSource and implement like

```swift
func cell(at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> MessagesCollectionViewCell {
    let cell = messagesCollectionView.dequeueReusableCell(withStyle: .text, for: indexPath) as! TextMessageCell
    cell.avatar.backgroundColor = .gray
    cell.message = message[indexPath.section]
}
```

to replace `messageForItem(at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView)`

It can provide more flexibility to customize cells and do something when cell is displayed on the screen.
And looks like the usage of `UITableViewDataSource` and `UICollectionViewDataSource`. Users can easier understand how to use it.

**Comment by SD10** [comment]
@azurechen I hadn't planned on it because the goal is for the user not to have to deal with configuring the cells. I'll look into it as a potential override point though 👍

**Comment by candostdagdeviren** [comment]
Totally agree with @SD10 . One point can be custom cell types like location/media but I don't think also that's a really good idea. It comes with a lot of complexity

**Comment by azurechen** [comment]
OK, @SD10 I agree your goal. But sometimes we still need to change some attributes of avatarView (ex: backgroundColor, radius, border, and async image) to customize the chatting room to meet app style.
Please refer to the comment of PR #283 , and give me some opinions. Thanks!

**Comment by carson-katri** [comment]
I like the idea of opening that up. I could get the customization I need.

**Comment by SD10** [comment]
I looked into this but I don't think it's possible with how the `MessageCollectionViewCell` is typed currently. The generic constraint makes it very difficult to work with. My goal is to remove the generics from the cells entirely in the next release.

**Comment by stefanluptak** [comment]
Hi! I saw some generics are now gone in the `0.12.0` version. Is this customization still planned? I want just one thing: set a custom radius for the avatar. I am able to do it by modifying the Pod itself, but that's not very sensible solution.

**Comment by SD10** [comment]
Hey @EskiMag,
I'm not sure if I'll add the method described above because it is quite redundant to `MessagesViewController`'s implementation of `collectionView(cellForItemAt:)`.
This is more beneficial as an override point because you can still call the `super` implementation.

#416 May be of use to you. We're trying to provide a configure method to allow people to load avatars asynchronously, but could be ~2 weeks until this is a live change.

**Comment by SD10** [comment]
I'm not going to add a method that returns a `MessageCollectionViewCell` because it's just boilerplate. Overriding `cellForItemAt` can do everything everyone needs
