### ISSUE TITLE
Placeholder Alignment is always set to Left.

### ISSUE THREAD

**Issue by hemangshah** [MessageKit/MessageKit#260]
## General Information

* MessageKit Version: 0.8.1 **and** 0.9.0

* iOS Version(s): 11.0

* Swift Version: 3.0

* Devices/Simulators: iPhone 7+

* Reproducible in ChatExample? (Yes/No): Yes

##  What happened?

In the ChatExample, setting this line after setting the delegate of `messageInputBar` doesn't change the placeholder alignment to `right`. It's always showing the placeholder alignment from `left`.

`messageInputBar.inputTextView.placeholderLabel.textAlignment = .right`
`messageInputBar.inputTextView.textAlignment = .right`

**Both don't work.**

## What did you expect to happen?

I am expecting the placeholder to come from right side.

**Comment by nathantannar4** [comment]
Fixed with PR #262
