### ISSUE TITLE
Detect Selected Cell

### ISSUE THREAD

**Issue by ulaserdegor** [MessageKit/MessageKit#261]
How to find the line number and type of the clicked cell? For example, if there is location information I want to open it on the map.

**Comment by SD10** [comment]
@ulaserdegor You can set the `MessageCellDelegate` to check for taps on detected text or just check if a message was tapped in general. The delegate method `didSelectMessage(in cell: MessageCollectionViewCell)` gives you a reference to the cell that was tapped.

```Swift
func didSelectMessage(in cell: MessageCollectionViewCell) {
    let indexPath = messagesCollectionView.indexPath(for: cell)
    // use that indexPath to get the `MessageType` from the data source
}
```

You can then switch on the `message` and handle the selection accordingly. ie) show maps, pull up a contact/start a call, open calendar

**Comment by ulaserdegor** [comment]
this work. But messagedata needs enums...

```
func didSelectMessage(in cell: MessageCollectionViewCell) {
   let indexPath = messagesCollectionView.indexPath(for: cell)
  let messageData = String(describing: messages[(indexPath?.section)!]data)
  if messageData.contains("location"){
   showMapApps()
}
}
```

**Comment by bandalrahul** [comment]
how i can access media or message on didSelectMessage?
if messageData.contains("location"){
   showMapApps()
}

not fulfill requirement I am using MockMesage model
