### ISSUE TITLE
QuickStart.md Typo

### ISSUE THREAD

**Issue by danielchangsoojones** [MessageKit/MessageKit#265]
The Quickstart.md has a type for the protocol of MessagesDataSource:

it says:
`func numberOfMessagess(in messagesCollectionView: MessagesCollectionView) -> Int {
		return messages.count
}`

there is an extra 's'. It should be:
```
func numberOfMessages(in messagesCollectionView: MessagesCollectionView) -> Int {
        return messages.count
    }
```

**Comment by SD10** [comment]
@danielchangsoojones Thanks for pointing this out 👍 Want to submit a PR fixing this?
