### ISSUE TITLE
Rewrite MessageLabel and move it to its own project

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#287]
The **2nd** biggest performance impact in this project is the `MessageLabel`. 

There's a lot of work to keep the private & internal text storage of `UILabel` in sync with our own storage. We are also doing parsing on the main thread, which would be nice to eliminate.

I'd like to eliminate some of these things by creating our `MessageLabel` through a subclass of `UIView` and not `UILabel`. 

It will be written at: https://github.com/SD10/MessageLabel

**Comment by chrisballinger** [comment]
Shouldn't a critical dependency of this project live under the MessageKit org?

**Comment by SD10** [comment]
Hey @chrisballinger, it surely will be! It's still an empty repo, I haven't gotten around to transferring it 😅

**Comment by nathantannar4** [comment]
What about `MessageInputBar` ? :(

**Comment by SD10** [comment]
@nathantannar4 I'm working on it 😅 😅 One at a time!

**Comment by SD10** [comment]
This may no longer become its own project. The `MessageLabel` rewrite performed worse and I had a lot of trouble doing parsing in the background. I will probably be able to cherry pick a few improvements though.

**Comment by nathantannar4** [comment]
I think the isConfiguring flag is good to keep 👍

**Comment by SD10** [comment]
Made some minor improvements in #356 but nothing worthy of separating it from the current project. Closing this for now
