### ISSUE TITLE
Add an example changelog entry

### ISSUE THREAD

**Issue by BasThomas** [MessageKit/MessageKit#291]
The CHANGELOG_GUIDELINES has an example header, but no example. We should add one [here](https://github.com/MessageKit/MessageKit/blob/master/CHANGELOG_GUIDELINES.md#example).

**Comment by SD10** [comment]
Good one 👍 We should take the CHANGELOG section from `v0.10.0` and use it as the example

**Comment by creyD** [comment]
Tried to resolve this. I hope this helps you guys. :)
