### ISSUE TITLE
Add more badges to README

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#293]
We could use some more badges on the README. Possibly for:
- remove travis & add buddybuild badge
- add MIT license badge
- add CocoaPods badge
- add Carthage badge
- add Swift Version badge
- add Xcode version badge
- add contributors welcome badge 😃 

You can check out another one of my projects for an example of some of these:
https://github.com/SD10/Nora

**Comment by Mosuswalks** [comment]
On it!
