### ISSUE TITLE
Support undocked/split keyboard on iPad

### ISSUE THREAD

**Issue by antonselyanin** [MessageKit/MessageKit#296]
## General Information

* MessageKit Version:
v0.10.0

* iOS Version(s):
11

* Swift Version:
Swift 4

* Devices/Simulators:

* Reproducible in ChatExample? (Yes/No):
Yes

1. Keyboard handling code doesn't support undocked/split keyboard 
https://support.apple.com/en-us/HT207521

2. When the keyboard changes size it doesn't adjust scrolling position (the keyboard covers part of the content)

**Comment by SD10** [comment]
This could be reconsidered for the next version. There's already #297 which aims to solve this

**Comment by Kaspik** [comment]
Should be updated via https://github.com/MessageKit/MessageKit/pull/297

**Comment by martinpucik** [comment]
This should be resolved in #1704
