### ISSUE TITLE
Typo when initializing Avatar()

### ISSUE THREAD

**Issue by JaceTan** [MessageKit/MessageKit#298]
## General Information

* MessageKit Version:
0.10.0

* iOS Version(s):
N/A

* Swift Version:
N/A

* Devices/Simulators:
N/A

* Reproducible in ChatExample? (Yes/No):
Probably

##  What happened?
When accessing the Avatar initializer, the "initials" argument is spelled incorrectly.
It's spelled "initals" (missing the last "i") in the function but in the [MessagesDataSource](https://github.com/MessageKit/MessageKit/blob/master/Documentation/MessagesDataSource.md), it's spelled correctly.

Sorry I'm being anal about spelling. I really do appreciate this entire project. It just bugs me more than it should.

**Comment by SD10** [comment]
@JaceTan Don't worry this is very important actually 😃 Would you mind submitting a PR with the fix?
