### ISSUE TITLE
Does not scroll to bottom when a message posted from input bar contains 2 lines or more

### ISSUE THREAD

**Issue by azhararmar** [MessageKit/MessageKit#302]
## General Information

* MessageKit Version: 0.1.0

* iOS Version(s): 10.3.2

* Swift Version: 4

* Devices/Simulators: iPhone6 Device & Simulator

* Reproducible in ChatExample? (Yes/No): Yes

##  What happened?
If a message entered from input bar has 2 or more lines, the messages does not scroll to bottom even after `scrollsToBottomOnKeybordBeginsEditing` is set to true

Please note that `func messageInputBar(_ inputBar: MessageInputBar, didPressSendButtonWith text: String) ` already has `messagesCollectionView.reloadData()` and `self.messagesCollectionView.scrollToBottom()` implemented.

## What did you expect to happen?
The message collection must scroll to bottom each time a new message is posted by user.

**Comment by nathantannar4** [comment]
@azhararmar I looked into this and I do not believe it to be a bug. The flag `scrollsToBottomOnKeybordBeginsEditing` is for automatically scrolling the view to the bottom when the `InputTextView` becomes the first responder. That is, the keyboard begins editing as the flag states. It is not a flag that scrolls the view whenever the send button is pressed. That is left for you to implement via `messagesCollectionView.scrollToBottom()`

This is how it is done in the example app. I believe you misunderstood the flag, `scrollsToBottomOnKeybordBeginsEditing`

**Comment by SD10** [comment]
You're both correct here. @azhararmar You have misunderstood the flag, it is as @nathantannar4 described, but you're correct about the `MessagesCollectionView` not scrolling to the bottom for messages with 2 lines or more. 

#301 Looks like the solution to this. Also discussed in #268 && #336

**Comment by azhararmar** [comment]
Sorry for delayed response. I was held up with few stuff.

@nathantannar4 you are right in your explanation. However I did implement `messagesCollectionView.scrollToBottom()` when send button is pressed. @SD10 thanks for clarification and for the fix of-course :-)

**Comment by SD10** [comment]
Being worked on in #395

**Comment by SD10** [comment]
Will be fixed in 0.12.0 by #395
