### ISSUE TITLE
Search filters inside a chat

### ISSUE THREAD

**Issue by iosNeophyte** [MessageKit/MessageKit#304]
Any possibility of a search filter feature to be added?
If not, can the layout be customisable to easily add a search bar controller at the top of the messageCollectionView?

**Comment by SD10** [comment]
Hey @iosNeophyte,

I don't have any plans to add this specific functionality but anything on the table if the community wants it. That being said, it definitely has low priority.

I think you should be able to add a subview to your viewcontroller that sits on top of the `MessagesCollectionView`. You would then have to add the height of that view to the top inset of the `MessagesCollectionView`.

**Comment by azhararmar** [comment]
While this seems a desirable feature, as @SD10 pointed out, it must not be hard to achieve this  in current version. With an input field in place, you can filter messagelist and reload collectionview.

However it would be interesting to have to have the input field on top of collection view and with an option to enable/disable with necessary delegate methods.

**Comment by iosNeophyte** [comment]
Hey thanks.. I got it done with your suggestion :)

**Comment by nathantannar4** [comment]
Going to close this for now. Please let us know if you have any further issues and for all questions we encourage the use of our Slack channel!

**Comment by SD10** [comment]
@nathantannar4 Lets keep this open as it’s a feature request. I don’t want duplicate issues for these things

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
I don't think this is a good candidate for MessageKit. Would be better to embed a `MessagesViewController` in some sort of higher level search controller
