### ISSUE TITLE
Remove TextMessageDisplayDelegate & TextMessageLayoutDelegate

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#308]
### Reasoning

- These should just be a part of the base `MessageDisplayDelegate` and `MessageLayoutDelegate` protocols as text messages are pretty standard. 

- Having these extra protocols acts a barrier to entry to using the library. If the user does not conform to `TextMessageDisplayDelegate` and `TextMessageLayoutDelegate` they are missing minor UI details. ie) different text color for incoming & outgoing messages

**Comment by SD10** [comment]
What about putting everything back into `MessagesDisplayDelegate` & `MessagesLayoutDelegate` in general?

Right now all the protocols for non-standard text message types require that they implement the `MessagesLayoutDelegate` protocol.

```Swift
protocol MediaMessageDisplayDelegate: MessagesDisplayDelegate {}
```

This is because the adopter of this protocol will be assigned to `MessagesCollectionView`'s `messagesDisplayDelegate` property. 

Thus, we're making the assumption that `MessagesDisplayDelegate` & `MediaMessageDisplayDelegate` are the same object. However, the API only requires that they implement the same interface.

It could be doing more harm than good IMO. Sort of undefined behavior if you have multiple objects conforming to these protocols, not obvious to users that you have to add these protocols to get the default behaviors, lots of casting required in the library internals.

cc @nathantannar4 @cwalo @etoledom

**Comment by SD10** [comment]
@nathantannar4 What do you think about this?
I suggest we just have `MessagesDisplayDelegate` & `MessagesLayoutDelegate`.
No need to get cute. Everything is optional and can be redefined in an extension anyways.

**Comment by nathantannar4** [comment]
If it makes it easier thats good enough for me

**Comment by cwalo** [comment]
I'm cool with reducing the number of delegates.
