### ISSUE TITLE
Message Input Bar Flickering On New Line

### ISSUE THREAD

**Issue by azhararmar** [MessageKit/MessageKit#309]
## General Information

* MessageKit Version: 0.1.0

* iOS Version(s): 10.3.2

* Swift Version: 4

* Devices/Simulators: iPhone 6s Device & Simulator

* Reproducible in ChatExample? (Yes/No): Yes

##  What happened?
When the message reaches end of line in input bar, the message goes to next line with a flicker, i.e the message input bar looks kind of closing and re-opening on every new line.

## What did you expect to happen?
Can we remove this flickering when going to new line on message input bar? this kind of feels weird.

**Comment by nathantannar4** [comment]
@azhararmar Interesting, I am having trouble seeing this flickering. Even when I slow the simulators animation time

**Comment by azhararmar** [comment]
PFA the screenshot in GIF format. I tested this in iOS11 simulator and the issue exist for me.

![screenshot](https://user-images.githubusercontent.com/10097624/32275173-3830136a-bf30-11e7-98c9-3bd51e37bbbb.gif)

I am running the simulator with default settings.

**Comment by nathantannar4** [comment]
Hi @azhararmar , I can't yet reproduce this in the ChatExample app. Are you using some kind of custom View controller container where your MessagesViewController is a child view controller? Have you overriden or changed any default values of the MessagesViewController

**Comment by azhararmar** [comment]
Hi @nathantannar4. I tested this further and I come to understand this issue is shown when [IQKeyboardManager](https://github.com/hackiftekhar/IQKeyboardManager) is enabled. The solution is to disable IQKeyboardManager in the ViewController with following code.

```swift
override func viewWillAppear(_ animated: Bool) {
    super.viewWillAppear(animated)
     IQKeyboardManager.sharedManager().enable = false
}
    
override func viewDidDisappear(_ animated: Bool) {
    super.viewDidDisappear(animated)
    IQKeyboardManager.sharedManager().enable = true
}
```

There are several users who uses `IQKeyboardManager` library. Perhaps if we can add a note in the documentation warning the user to disable IQKeyboardManager in the ViewController to avoid the conflict. 

I will close this issue for now.

**Comment by SD10** [comment]
Hey @azhararmar thanks for updating us and documenting this for other users 👍

**Comment by nathantannar4** [comment]
Ah yes @azhararmar we already manage the keyboard state.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mlyongardiner** [comment]
Hi @nathantannar4 -
Even after removing IQKeyboardManager entirely from my project (I uninstalled the pod) my app still flickers (more like pauses) when it's preparing to go to a new line. What info can I give you to help get to the bottom of it? Thanks!
