### ISSUE TITLE
New MessageKit workflow

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#316]
Our current release process makes it difficult to make minor releases in a timely fashion, thus we will be using a new workflow for MessageKit development.

### Process

- `master` branch is for bugfixes, documentation, and non-API breaking changes

- `development` is for significant new features and API breaking changes

We will have to change `CONTRIBUTING.md` to represent this new process

**Comment by azhararmar** [comment]
@SD10 may I ask what is the current workflow? I personally avoid directly committing to master for whatever circumstances. Isn't it a better option to have a minor release branch with all of the issues grouped? or is it that you don't want to wait for related issues to be fixed before releasing the critical updates or fixes?

**Comment by SD10** [comment]
@azhararmar Well, we don't commit directly to `master` -- it's locked. We can only commit to master by merging a pull request.

But yes, I basically want to ship bugfixes immediately. We had an issue with `v0.9` -> `v0.10` where we had this mix of API breaking changes + bugfixes and the release was taking too long, preventing us from shipping a release that fixed the bugs.

My hopes are that this new strategy will allow us to release bug patches within a few days after they've been fixed.

**Comment by hyouuu** [comment]
Thanks for posting this! So to use the latest and contribute we should focus on `development`? BTW not important but it seems `develop` is the standard branch name ;)

**Comment by SD10** [comment]
Sorry I missed this @hyouuu. I think you're correct but we'll use `development` because I use this same branch name at Moya and I dislike abbreviations 😅
