### ISSUE TITLE
We should not conflate authorship with message direction (inbound/outbound)

### ISSUE THREAD

**Issue by alijaza** [MessageKit/MessageKit#318]
## General Information

MessageKit assumes a 1:1 conversation between a currentSender and a recipient. This assumption is not necessary and makes it difficult to implement group messaging. For example, if I work at a company which has many representatives sending outbound messages to the same customer, my data source may provide an `author` as well as a direction property (`inbound` or `outbound`) for each message object.

* MessageKit Version: 0.10.0

* iOS Version(s): 11

* Swift Version: 4

* Devices/Simulators: NA

* Reproducible in ChatExample? (Yes/No): Yes, just setup data source as explained.

##  What happened?

I tried to set different authorship to some of the outbound messages.

## What did you expect to happen?

I expect authorship and direction to be decoupled, but `MessagesDataSource` uses `isFromCurrentSender` to decide whether the message is outbound or inbound.

**Comment by nathantannar4** [comment]
Hi @alijaza 

So a feature you are asking for is that messages not from the current sender can appear on the right?

**Comment by nathantannar4** [comment]
I believe you could obtain this functionality with the `isFromCurrentSender(message: MessageType)->Bool` method. If not please let me know

**Comment by SD10** [comment]
@alijaza see #322

**Comment by SD10** [comment]
@alijaza This is solved by #322 and will be possible in MessageKit 11.0. I'm not sure when that will be but I know you have a short term solution using `isFromCurrentSender()` for the time being.
