### ISSUE TITLE
Logic To Handle Inbound Messages

### ISSUE THREAD

**Issue by azhararmar** [MessageKit/MessageKit#319]
I am using CoreData to store all the messages. However I require a listener when there is a new inbound message coming from the server to update chat conversation.

I am using `NSFetchedResultsController` which provides me with required `didChange anObject` and `controllerDidChangeContent` delegates.

What I am stuck at is `messageForItemAtIndexPath` method. I cannot for some reason fetch the object directly inside this delegate using `fetchedResultsController.object(at: indexPath)` Because it raises an exception with message `'NSInvalidArgumentException', reason: 'no section at index 1'`

My question is

1. How do I access individual object using `fetchedResultsController` in the `messageForItemAtIndexPath` delegate and using the same how do I count the object.
2. If FRC is not the ideal solution (which I am not sure) how did you think through to handle data-source? Do you expect to append the `messageList` array and reload collection view every time the conversation is to be updated?
3. For a conversation with hundred/thousand of messages. Do you expect to load all messages on load? how about pagination?

**Comment by nathantannar4** [comment]
Hi @azhararmar 

To answer your questions:
1. You will need to develop some way of accessing the results from the controller. Most people will store message data in an array and reference those items using `indexPath.section` as each message is in its own section
2. You don't need to reload the collection view every time you can insert sections too. Messages will need to be added to the same list that your dataSource uses. That is standard for how a `UICollectionView` and even `UITableView`
3. It is up to the developer to determine how many messages you want to display and when you should load more. Not sure what you mean about pagination
