### ISSUE TITLE
Adding ConversationViewController as a child view controller the messageInputBar not display on the view

### ISSUE THREAD

**Issue by nfasate** [MessageKit/MessageKit#323]
## General Information

* MessageKit Version: 0.10.0

* iOS Version(s): iOS 10.3

* Swift Version: Swift 4

* Devices/Simulators: Device

* Reproducible in ChatExample? (Yes/No): Yes

##  What happened?
When I try to add ConversationViewController as a child view controller on InboxViewController that time messageInputBar does not display on the view.
 
**Below code**
> let contentVC:UIViewController = ConversationViewController()
            addChildViewController(contentVC)
            self.view.addSubview(contentVC.view)
            contentVC.didMove(toParentViewController: self)

## What did you expect to happen?
The messageInputBar must display on the view even though I add ConversationViewController as a child view.

**Comment by SD10** [comment]
@nfasate I think you have to call:
```Swift
messagesViewController.becomeFirstReponder()
```
cc @cwalo I think he had a solution for this

**Comment by nfasate** [comment]
Hi SD10,

Thanks for quick reply, but I don't get it from where I have to call `messagesViewController.becomeFirstReponder()` in my code.

I guess the size of `messageInputBar` is always return zero when I have added ConversationViewController as a child view.

Thanks.

**Comment by Wotafak** [comment]
@nfasate try calling `messagesViewController.becomeFirstReponder()` in viewDidAppear

**Comment by nfasate** [comment]
@Wotafak,

I am not able to call `messagesViewController.becomeFirstReponder()` in ViewDidAppear it throw compilor error` Use of unresolved identifier 'messagesViewController'`

**Comment by SD10** [comment]
@nfasate It looks like your `MessagesViewController` is called `contentVC`.

**Comment by nfasate** [comment]
@SD10 Even after using `contentVC.becomeFirstResponder()`, the MessageViewController doesn't show `messageInputBar`.

**Comment by nfasate** [comment]
@SD10 Thanks a ton !! it worked.

**Comment by BasThomas** [comment]
Hey @nfasate - can you share how you solved the problem in the end?

**Comment by nfasate** [comment]
Hi @BasThomas  

I just added `self.becomeFirstResponder()` in ConversationViewController `ViewDidAppear` as per sugested by @Wotafak and @SD10 .

**Comment by cwalo** [comment]
My scenario sounds slightly different as I have two view controllers added as children - one being the MessagesViewController. I'm just toggling their hidden state depending on which is selected. But yeah, to handle the input bar, I call `becomeFirstResponder` and when I want it go away, I call`inputBar.inputTextView.resignFirstResponder` and `messagesViewController.resignFirstResponder`.
