### ISSUE TITLE
Remove MessageKit v0.9.0 deprecations

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#328]
This is an easy contribution. Just delete the code highlighted in the link below and point your PR to `development` 😃 

https://github.com/MessageKit/MessageKit/blob/64e26b4e9a745cc1f6e4a6bf71bc8412490e3655/Sources/Supporting/MessageKit%2BAvailability.swift#L43-L80

**Comment by hemangshah** [comment]
Hi @SD10, https://github.com/MessageKit/MessageKit/pull/332
