### ISSUE TITLE
Does not scroll to bottom when the height of the keyboard has changed

### ISSUE THREAD

**Issue by hellokenta1024** [MessageKit/MessageKit#338]
## General Information

* MessageKit Version:
0.10.1
* iOS Version(s):
iOS 11.1
* Swift Version:
Swift 4.0
* Devices/Simulators:
iPhone 8 (Simulators)
* Reproducible in ChatExample? (Yes/No):
yes

##  What happened?
messageCollectionView doesn't scroll to bottom when the height of the keyboard has changed.

![message-kit](https://user-images.githubusercontent.com/7506836/32537332-90bd6896-c4a5-11e7-860a-a97549cbcfb4.gif)

## What did you expect to happen?
I think that it is better to scroll `messageCollectionView` to bottom when the height of the keyboard has changed like messenger, iMessage and Slack.

**Comment by SD10** [comment]
This has been added in #340 and will be available in `0.12.0`

**Comment by zaaaszaaas** [comment]
i experience the same problem on iOS 14

MessageKit 3.4.1
