### ISSUE TITLE
Load MessagesCollectionView messages starting at the bottom

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#35]
### MessagesCollectionView reverse loading

The cells should be laid out starting from the bottom and additional cells should be added to the top of the previous cell.  This will allow the user to paginate upwards to new messages.

Some discussion around this topic can be found here: https://github.com/MessageKit/MessageKit/issues/12

### Thoughts:
I guess this is ultimately about pagination. I never really thought of handling it in this library 🤔

**Comment by SD10** [comment]
It's still unclear to me which problem this solves, but I don't like the idea of reversing the layout:

### Why?
- It dictates how users have to manage their data sources, including:
    - Possibly requires users perform sort operations on their methods due to the reverse layout
    - Requires users to prepend new messages, increasing the complexity of the operation
- Is counter intuitive

**Comment by pmusolino** [comment]
The problem to solve is the same of IGListKit https://github.com/Instagram/IGListKit/issues/242

**Comment by SD10** [comment]
@Codeido Thanks! 
I'll look into maintaining the scroll position, it's just not going to be made possible by a reversed layout.
