### ISSUE TITLE
Keyboard won't dismiss when there is ONLY one message in the chat

### ISSUE THREAD

**Issue by ijameelkhan** [MessageKit/MessageKit#351]
## General Information

* MessageKit Version:
0.10.2
* iOS Version(s):
10.0
* Swift Version:
4.0
* Devices/Simulators:
iPhone and Simulators
* Reproducible in ChatExample? (Yes/No):
No

##  What happened?
They keyboard won't dismiss until there are a lot message in the screen which produces scrollable content. When there is limited content. The Collectionview can't scroll hence they keyboard won't dismiss. 

See attached screenshot

![2017-11-14 17 55 48](https://user-images.githubusercontent.com/1882875/32781091-868ce9ea-c965-11e7-9777-ac8d9f379829.png)

My App is using this pod https://github.com/CosmicMind/Material which creates containment controller if thats plays any role in this issue ?

## What did you expect to happen?
I expect it to be bouncy even when there is Limited / No content so we can dismiss the keyboard.

**Comment by nathantannar4** [comment]
If you would like that behaviour you need to set the `MessagesCollectionView` `alwaysBounceVertical` to `TRUE`

**Comment by SD10** [comment]
@nathantannar4 This should be set to true on `MessagesCollectionView`by default. @ijameelkhan Would you like to make a PR with this change?

**Comment by ijameelkhan** [comment]
Here you go: #352

Closing the issue - Thank you everyone.
