### ISSUE TITLE
Bottom label vertical alignment

### ISSUE THREAD

**Issue by Beniamiiin** [MessageKit/MessageKit#353]
Is it possible to set the position of the bottom label like in the screenshot?
![bottom label](https://user-images.githubusercontent.com/4854239/32823811-87cabf50-c9ef-11e7-8dfc-e86ecefb10ee.png)

**Comment by SD10** [comment]
Hey @Beniamiiin, unfortunately this layout is not possible at the moment 🙁

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Beniamiiin** [comment]
@SD10 then I'll do it.

**Comment by SD10** [comment]
Looks more related to #190 #432 than related to the bottom label itself. We will never support laying out the bottom label in such fashion. Going to close this as a duplicate
