### ISSUE TITLE
Update ChatExample settings page to toggle MessageKit functionality

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#362]
There's currently an empty `SettingsViewController` in the example app. It would be nice if through this controller we could change/enable/disable functionality in the `ConversationViewController`.

This would increase my productivity 😃 because I would be able to test things without making code changes.

Things we could do:
- [x] Set number of mock messages to appear in `ConversationViewController`
- [x] Turn Text Messages **on / off**
- [x] Turn Attributed Text Messages **on / off**
- [x] Turn Photo Messages **on / off**
- [x] Turn Video Messages **on /off**
- [ ] Select enabled `DetectorTypes`

**Comment by jaredStef** [comment]
I'd be glad to pick this up if anyone has yet to do so

**Comment by SD10** [comment]
Feel free @jaredStef! It would be super helpful to me 😄

**Comment by nathantannar4** [comment]
Additionally can you add to the settings page, avatar (on/off), colors (sender and receiver) :) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
@nathantannar4 I don't think updating the colors of sender / receiver do any good? I'm really only interested in things that will help debug 😅 But there's a lot on this list, I'd be happy if someone even added any subset of them

**Comment by alessioarsuffi** [comment]
I'm preparing a pull request with fix of Set number of mock messages to appear in ConversationViewController. :)

Update:

- [x] Set number of mock messages to appear in `ConversationViewController` from: [0.13.0](https://github.com/MessageKit/MessageKit/releases/tag/0.13.0)

**Comment by hamzaozturk** [comment]
Things we can do in Settings now:
- [x] Set number of mock messages
- [x] Turn Text Messages **on / off**
- [x] Turn Attributed Text Messages **on / off**
- [x] Turn Photo Messages **on / off**
- [x] Turn Video Messages **on /off**
- [x] Turn Emoji Messages **on /off**
- [x] Turn Location Messages **on /off**
- [x] Turn Url Messages **on /off**
- [x] Turn Phone Messages **on /off**
