### ISSUE TITLE
What method can I display the message time on the left (if the current sender) or on the right (incoming messages) from the "bubble"?

### ISSUE THREAD

**Issue by relaxsus** [MessageKit/MessageKit#370]
## General Information

* MessageKit Version:

* iOS Version(s):

* Swift Version:

* Devices/Simulators:

* Reproducible in ChatExample? (Yes/No):

**Comment by SD10** [comment]
@relaxsus We currently don't have any supplementary views that are on the left or right of the chat bubbles. You would have to use the `cellBottomLabel` or a `MessageFooterView`

**Comment by jitesh-sharma** [comment]
can we have any method to set the text alignment (left, right and center) of cell bottom label ???.
 And also I want to make some changes in collection view cell. so can we have access of that cell ?

**Comment by SD10** [comment]
@jitesh-sharma The labels are sized to fit so text alignment doesn’t really matter. But I am working on allowing static sizes, then alignment would be useful.

Working on opening up a cell method too, I’m just very behind

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jitesh-sharma** [comment]
@SD10 thanks for quick reply, waiting for new release with all this changes

**Comment by layanavg** [comment]
Is this feature is updated, as I need the same feature in my app.
