### ISSUE TITLE
MessageStyle TailCorner wrong in iOS 9

### ISSUE THREAD

**Issue by shahnewaz469** [MessageKit/MessageKit#376]
## General Information

* MessageKit Version:
0.11.0
* iOS Version(s):
iOS 9
* Swift Version:
4.0
* Devices/Simulators:
iPhone 6s
* Reproducible in ChatExample? (Yes/No):
yes

##  What happened?
MessageStyle.TailCorner always shows in the bottom right for both sender and receiver.

## What did you expect to happen?
It should be bottom left for the receiver and bottom right for the sender.

**Comment by nathantannar4** [comment]
Thanks for bringing this to our attention. I can confirm that is an issue. I notice a steep degradation of scroll performance in general with the message labels @SD10

**Comment by zhongwuzw** [comment]
@shahnewaz469  , Thanks for your issue, we have fixed it and will release in next version.
