### ISSUE TITLE
Create UIView subclass - MessageContainerView

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#38]
### Reasoning:

I'd like to create a custom `UIView` subclass, `MessageContainerView`, that takes in a `MessageStyle` argument which is represented as an `enum`.

```Swift
enum MessageStyle {
   case bubble(cornerRadius: CGFloat)
   case bubbleTailed(cornerRadius: CGFloat)
   case bubbleOutline(cornerRadius: CGFloat)
   case custom(UIView)
   case none
}
```

Then have a delegate method:

```Swift
func styleForMessage(_ message: MessageType, at indexPath: IndexPath, in collectionView: MessagesCollectionView) -> MessageStyle
```

This is a really rudimentary and rough around the edges. But seems like a cool idea and user friendly.

**Comment by fbartho** [comment]
One cool thing I've seen in plenty of chat systems is collecting sequential bubbles from a single person into a single large shape. (adding the tail and avatar only to the latest message by that person). This also rounds the corners to make a macro bubble out of the sequential messages.

- Reference: Facebook Messenger iOS does a variant of this.

Is this an interesting discussion re: this Github issue plan? -- Dynamic styling of multiple messages based on surrounding scope.

**Comment by SD10** [comment]
@fbartho I'm definitely open to this, after supporting some basic message styling first of course. I noticed this as well when scoping out messaging apps for inspiration. I think Kik and WhatsApp do similar things as well.

**Comment by MacMeDan** [comment]
Definitely would be a cool feature we just want to make it enableable. I don't know how we would define the styles 🤔 but I guess that is the fun of this whole thing.🎉

**Comment by SD10** [comment]
Added in `v0.7.0`
