### ISSUE TITLE
Couldn't Generate Swift Representation. (Carthage)

### ISSUE THREAD

**Issue by MacMeDan** [MessageKit/MessageKit#382]
## General Information

When Cmd clicking on a reference to `MessageKit` this error is thrown Error(from SourceKit): "Connection Interrupted" Their may be a relation to importing the project via `Carthage` I hypothesize that it is an issue with the way the project is linked but cannot confirm. 

WorkAround: Pull down the `MessageKit` project and look up what you need through that project. 

* MessageKit Version: 0.11.0

* iOS Version(s): iOS11.2

* Swift Version: 4.2

* Devices/Simulators: iPhone6s+

* Reproducible in ChatExample? (Yes/No): NO due to the chat example using cocoapods 

## What did you expect to happen?

When you `Cmd` Click on an object from `MessageKit` this error is thrown.
![screen shot 2017-12-06 at 2 17 40 pm](https://user-images.githubusercontent.com/6182351/33729003-95254d36-db39-11e7-901f-bc5c817fc799.png)

**Comment by nathantannar4** [comment]
@cwalo you use Carthage, any idea?

**Comment by SD10** [comment]
@nathantannar4 I asked him about this. Apparently, he has experienced it in both MessageKit and your input bar project for quite some time. It doesn't happen on any other of his Carthage dependencies

**Comment by nathantannar4** [comment]
Maybe Carthage support was added wrong?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
https://stackoverflow.com/questions/32894901/xcode-couldnt-generate-swift-representation-for-my-own-framework

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by soleniacz** [comment]
Nope. Same issue here. Strange for any other `Frameworks`  in my project SourceKit generates representation.

**Comment by MacMeDan** [comment]
I ended up switching to cocoapods because of this (and other reasons) but would still love to know what causes the issue.

**Comment by cwalo** [comment]
I've been poking at this one periodically, and I'm really not sure. I've compared build settings between MessageKit and projects that work and nothing jumps out at me...

**Comment by kinoroy** [comment]
Is anyone still experiencing this? I just tried to reproduce the issue now but it seems to work fine.

**Comment by MacMeDan** [comment]
Ya I think its not an issue any more.
