### ISSUE TITLE
Looking for Core Contributors for v1

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#4]
# Looking for Core Contributors for v1

This is and always will be a community effort, but I think this project will require that I either write v1 myself or with a group of core contributors. The community can provide feedback, request features, and additional people can make contributions from there.

### Conduct
- [ ] Respectful of all members and their opinions
- [ ] Capable of reviewing code and having your own code reviewed

### Must
- [ ] Have the spare time to dedicate to this project
- [ ] Be passionate about writing high-quality clean code
- [ ] Be willing to write unit tests if need be
- [ ] Be willing to communicate via Slack & Google Hangouts
- [ ] Be able to start this weekend

### Preferably:
- [ ] Interested in being a long term contributor 
(having knowledge of the evolution of the initial codebase is a huge plus in the long run)

#  Please
Only volunteer if you're serious about the project and can contribute a large amount of code for v1 rather quickly.  Each and every contributor is welcome but this is a special task 👍

**Comment by sunshinejr** [comment]
I think this is a great idea. I can't promise to write any code, but if you need someone to do code reviews, you can count me in 👍

**Comment by omaralbeik** [comment]
@SD10 If 4~6 hours a week, count on me :)

**Comment by bojanstef** [comment]
I'll try my best

**Comment by sairamkotha** [comment]
@SD10  I can work for 2-3 hours per week .

**Comment by gabrielPeart** [comment]
@SD10 You can count on me

**Comment by jyounus** [comment]
I could probably spare a couple of hours every week and help out where needed.

**Comment by rizwankce** [comment]
Count on me 👍  I can start off this weekend and spend 4-6 Hours probably.

**Comment by gutoglup** [comment]
@SD10 You can count on me. I can work for 2-3 hours per day.

**Comment by jjjeeerrr111** [comment]
Can give 2-3 hrs a week. I've been looking forward to this rewrite for a while, i'd be glad to help :)

**Comment by mding5692** [comment]
Can put in 6 hrs per week based on hours I can have that are free either during afternoons or weekends, happy to write tests, review and also participate in code

**Comment by SD10** [comment]
Thanks everyone! I'm going to start some things this weekend. Possibly open a few issues as tasks and can always use code reviews on any PRs.

**Comment by matteodanelli** [comment]
I can help about 4 hours/week as well as code reviews.
Currently I am using the library in my current project, so I can also test it.

**Comment by RuiAAPeres** [comment]
I would highly advise you to drive this project on your own @SD10 until you have a `0.1` release.

**Comment by mding5692** [comment]
@RuiAAPeres sounds like a good idea, is there a meeting planned or some real-time chat software that we can use to chat like slack created, that would be good to actually keep people involved @SD10  Thanks again 👍

**Comment by gabrielvieira** [comment]
@SD10 You can count on me

**Comment by caguilar-dev** [comment]
I can help with few hours/week as well as code reviews.

**Comment by SD10** [comment]
@RuiAAPeres Some others have shared similar thoughts and that's the plan 👍

**Comment by SD10** [comment]
@mding5692 There will be a Slack channel but I want to keep the discussion in the public for now.

**Comment by Jimmybee** [comment]
I'd be happy to contribute when you are ready.

**Comment by aorumbayev** [comment]
Hey @SD10 - I can dedicate 2-3 per week on it

**Comment by MacMeDan** [comment]
I will put in as much time as I can shooting for 5hr a week. Always available to do reviews and I have leaned from the legacy JSQ lib that if you can keep your features small it makes reviewing and getting them in the project easier. I'm available to review any pull request also.

**Comment by SD10** [comment]
@MacMeDan and everyone else. I have a really rough PR in progress.

It could be difficult to understand until I have some sort of minimum working version and add comments. 

Nonetheless, if anyone other than me can understand the code at this point -- if you see something that will pose a potential problem just LMK.

**Comment by MacMeDan** [comment]
Ya I will take a look at it.

**Comment by gungorbasa** [comment]
I would love to contribute and I can put 2-3 hours per week.

**Comment by ggthedev** [comment]
i am a freelancer and i would like to take this opportunity to contribute to this project as my first open source gig...and i can spend upto 2hrs/day for this project.

**Comment by LucianoPAlmeida** [comment]
@SD10 , @omaralbeik, count me in :)

**Comment by hamdshah** [comment]
@SD10 Count me in as well ⚔🗡

**Comment by ampatalas** [comment]
Total open source newbie... But I would love to help!

**Comment by zkenes** [comment]
Never participated in big open-source projects. I would love to help. You can count on me up to 10h/week
@SD10

**Comment by NinoScript** [comment]
I'm available too if you still need people.

**Comment by lzyraining** [comment]
Such a great idea. I haven't been contribute to any open source. I'm love to help. I can dedicate 1 ~ 2 hours on  every weekday and spent more time on weekend. Please count me in. @SD10

**Comment by telip007** [comment]
You can count on me ✌️ Weekdays it will probably be less than 2-3 hours but in the weekends I can dedicate some more time to it. :)

**Comment by Przytua** [comment]
I can help.

**Comment by mszaro** [comment]
_Edit_: Unfortunately due to the decisions to drop Objective-C compatibility, I can't justify my (or my company's) time contributing to this project. Wishing good luck to all involved.

**Comment by marcsnts** [comment]
Would love to contribute to this project! I can dedicate 4-12 hours a week.

**Comment by SD10** [comment]
Everyone please see #12

**Comment by grevolution** [comment]
@SD10 I'd love to be part of the effort. I can spare 4+ hours a week for this.

**Comment by andreaantonioni** [comment]
@SD10  I was looking for an open source project to contribute to and I think I've found it ;) 
I can spend 3 ~ 4 hours/week

**Comment by SD10** [comment]
Closing this in favor of #12

**Comment by hilalbaig** [comment]
Count me too, ready to spend 3-4hrs weekly.

**Comment by SD10** [comment]
The project has become a lot more stable since the opening of this issue.
Anyone looking to collaborate can join the **MessageKit Slack** channel [here](https://join.slack.com/t/messagekit/shared_invite/MjI0NDkxNjgwMzA3LTE1MDIzMTU0MjUtMzJhZDZlNTkxMA).
