### ISSUE TITLE
Last call for v1.0 features

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#40]
## EDIT: 
As discussed by the MessageKit community we won't jump to a **v1.0** release just yet.

----

Hey everyone 👋,
We're looking to make a solid `v1.0` release of **MessageKit** in the next few days.

**So this will be the last call to make suggestions for v1.0**

You can look at the current state of the project on the `v0.3.0` branch.
There are a few bugs regarding the layout of the `cellTopLabel`/`cellBottomLabel` and text alignment.
We're aware of these and will have them resolved later today, so please ignore them for now.

With `v1.0` we should be able to support basic `MessageCollectionViewCells` that look like this:

![messagecollectionviewcell](https://user-images.githubusercontent.com/7445580/29096725-d01e02bc-7c5b-11e7-9fb2-39071efde8f2.png)

### What we're looking for?
- Anything you think is drastically important and missing from the potential v1.0
- Refining the API / Naming
- Any bug reports

### Join the Slack
[Click Here to Join the MessageKit Slack Channel](https://join.slack.com/t/messagekit/shared_invite/MjI0NDkxNjgwMzA3LTE1MDIzMTU0MjUtMzJhZDZlNTkxMA)

**Comment by AndrewLauder** [comment]
Forgive me if it's already mentioned, but what about typing indicator?

**Comment by SD10** [comment]
@AndrewLauder Yes we're aware of this 👍 You can check out the MessageKit roadmap in #62
