### ISSUE TITLE
Miscalculated layout in customized inputView

### ISSUE THREAD

**Issue by antoinelamy** [MessageKit/MessageKit#403]
## General Information

* MessageKit Version: `master`

* iOS Version(s): 11.2

* Swift Version: 4.0

* Devices/Simulators: iPhone 8

* Reproducible in ChatExample? (Yes/No): Yes
Just add a call to `slack()` at the end of `viewDidLoad()` and change the `setStackViewItems` call to be not animated.

##  What happened?
Customizing the inputView in viewDidLoad cause the intrinsicContentSize to be miscalculated and the bottom buttons in the exemple slack keyboard are cut in half.

## What did you expect to happen?
The inputView appear correctly when it appear on screen.

## Notes
There is a weird guard condition in `MessageInputBar.setStackViewItems()` that prevent `layoutIfNeeded()` on the bar's stack views if no superView is present. Removing this guard statement fix the problem.

**Comment by nathantannar4** [comment]
Hi @antoinelamy, I took a look at this. The `guard` statements are not useless, they ensure safety. The bug you experience in `master` is due to how the `bottomAnchor` to the `window` is assigned. The issue is not present on `development`

**Comment by antoinelamy** [comment]
@nathantannar4 what safety? I am unaware that an offscreen layout pass is somehow risky. In fact, the initial view controller's view layout pass is always off screen.

**Comment by antoinelamy** [comment]
Do you have an alternative fix?

**Comment by nathantannar4** [comment]
It's already fixed, checkout `development`! :D 

The safety is the offscreen layout that can be dangerous. @zhongwuzw added the `guard` statements

**Comment by antoinelamy** [comment]
I'm glad the issue is already fixed. If you have any documentation about the dangers of offscreen layout I would be interested, never heard of it.

**Comment by nathantannar4** [comment]
Its mainly to protect against those that pass the `animated` parameter as true. You can't `animate` something not on screen
