### ISSUE TITLE
InputTextView placeholder rendering wrong in landscape

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#41]
### InputTextView placeholder rendering wrong in landscape
![screen shot 2017-08-08 at 6 28 13 pm](https://user-images.githubusercontent.com/7445580/29098877-5c419924-7c67-11e7-8579-c5ba80b7cf0b.png)

@andreaantonioni Can you look into this?

**Comment by andreaantonioni** [comment]
Fixed in PR #42 👍🏻
