### ISSUE TITLE
messagesCollectionView in rich notification 

### ISSUE THREAD

**Issue by turk-jk** [MessageKit/MessageKit#411]
Great Library! : ) 👍
first of all, thanks to you all for the big effort. 

how can I implement the MessagesCollectionView alone in a NotificationViewController ( UNNotificationContentExtension). 
I'm trying to have chat in the rich notification. 
Thank you.

**Comment by turk-jk** [comment]
no idea how to add label to the question/  feature request to this issue

**Comment by SD10** [comment]
Hey @turk-jk,
Unfortunately, this is not something I have tried yet so I'm unable to assist you with this. However, if you make some progress with this issue, please let me know! 👍
