### ISSUE TITLE
Change avatar background color

### ISSUE THREAD

**Issue by quanvo87** [MessageKit/MessageKit#419]
If you set an avatar to an image that doesn't cover the whole view, you see a grey background by default. Is there a way to change this, to say, clear?

The only code I've implemented that deals with the avatar is in `avatar(for:, at:, in:)`.

**Comment by SD10** [comment]
@quanvo87 No easy way of doing this right now. Making the `AvatarView` more customizable seems to be the focus lately. #416 #418

**Comment by quanvo87** [comment]
Fixed by #416 . Thanks!
