### ISSUE TITLE
Discuss Image Paste support for InputTextView

### ISSUE THREAD

**Issue by nathantannar4** [MessageKit/MessageKit#424]
This is a general discussion area for PR #423 which focuses on adding paste support for images in the InputTextView. I have started the PR with some initial code to lay the groundwork.

We welcome any comments and/or suggestions

**Comment by zhongwuzw** [comment]
Copy from @nathantannar4 's opinion in #423 
> Ya the way I thought is that I just expose an images property and it’s up to the developer to support getting the image and sending it as a separate message

**Comment by zhongwuzw** [comment]
@nathantannar4 , Yep, I think you can update the `Example` to make behavior same as `iMessage`.

**Comment by nathantannar4** [comment]
Yea I did so in my PR

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
One thing we could improve is keeping images the same size. Right now it sized images in the NSTextContainer based on the frame width. So if a user rotates the phone and then enters a new image they can be different sizes. Do we want to redraw all the image attachments ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zhongwuzw** [comment]
@nathantannar4 , you treat the text as one message. What's the `iMessage` process is:

Text example:
```
This is a top test message\n    [1]
[pic]\n  [2]
This is a bottom test message    [3]
```

`iMessage` split the text to three parts. [1] as a single message. [2] as a image message,and [3] as a single message.And also strip `LF`.


> One thing we could improve is keeping images the same size. Right now it sized images in the NSTextContainer based on the frame width. So if a user rotates the phone and then enters a new image they can be different sizes. Do we want to redraw all the image attachments ?

It needs redraw IMO.

**Comment by nathantannar4** [comment]
Hi @zhongwuzw, I added the functionality for parsing components and redrawing

Example
```
for component in inputBar.inputTextView.components {
            
            if let image = component as? UIImage {
                
                // send image message
                
            } else if let text = component as? String {
                
                // send text message
            }
            
        }
```

**Comment by SD10** [comment]
This was added in #423 👍
