### ISSUE TITLE
Inputbar show permanent

### ISSUE THREAD

**Issue by girishghoda** [MessageKit/MessageKit#427]
## General Information

* MessageKit Version: 0.12.0

* iOS Version(s): 10

* Swift Version: 4

* Devices/Simulators: Device 5c

* Reproducible in ChatExample? (Yes/No): No

##  What happened?
I used Cosmicmind material library in my app,so it cause inputbar hide & not show

## What did you expect to happen?
I want to show inputbar as permanent,never want to hide in chat view

**Comment by SD10** [comment]
Hey @girishghoda, sorry but I'm unfamiliar with Cosmicmind so I'm not aware of their compatability with MessageKit. Nonetheless, thank you for creating this issue. It is possible that someone else has faced this issue and found a solution.

**Comment by girishghoda** [comment]
Hey @SD10 
But can i always show inputbar (fix) not want to hide?
