### ISSUE TITLE
Message bubble not tightly wrapping text

### ISSUE THREAD

**Issue by Jeyhey** [MessageKit/MessageKit#430]
## General Information

* MessageKit Version: 0.12.0

* iOS Version(s): iOS 10.3.3

* Swift Version: 4

* Devices/Simulators: iPhone SE (not simulated)

* Reproducible in ChatExample? (Yes/No): probably

##  What happened?

For multiline messages the message bubble does only loosely wrap the text leaving empty space on the right side. It's best explained with a picture. The following picture shows the issue:

![3eb6036f-3b3b-4b78-a3ba-0b494efb034b](https://user-images.githubusercontent.com/11479763/34456465-3121ad0a-ed97-11e7-8bf0-0d2669e28d28.jpg)

## What did you expect to happen?

I expect the bubble to wrap the text tightly. When rendering the chat with JSQMessagesViewController the bubble looks as follows:

![714d8774-17e2-4540-a60f-7602ab870bf7](https://user-images.githubusercontent.com/11479763/34456466-31386d7e-ed97-11e7-9e4d-9ac5d3f76a8e.jpg)

**Comment by SD10** [comment]
@Jeyhey Have you changed the `MessagesCollectionViewFlowLayout` font property at all? Can you reproduce this on the example app?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Jeyhey** [comment]
No, I did not change `messageLabelFont` in `MessagesCollectionViewFlowLayout`. I set the text of the messages as attributed string.

The issue is not that the bubble does not correctly wrap the text. It does so for most messages. The issue is that the **bubble will always have maximum width** for text messages that **need more than one line**.

I know this behaviour from the Android UI elements. On Android this behaviour is normal (e.g. WhatsApp). On the iOS platform, however, the UI elements seem to be able to resize and tightly fit multiline text.

I'll see if I can reproduce this in the example app and let you know. This will take some time though.

**Comment by SD10** [comment]
> The issue is not that the bubble does not correctly wrap the text. It does so for most messages. The issue is that the bubble will always have maximum width for text messages that need more than one line.

Thanks for clearly point out the issue, you are correct. I'll see if this is a change I can make.

**Comment by Jeyhey** [comment]
Share your thoughts on this and I'll try to look into it as well.

**Comment by SD10** [comment]
I know when sizing the label, we check:
- if the size to display the text is greater than the max width. 
- if yes, we size the label height with the max width.
-  if no, we size the label height with the given width.

We would need some sort of check if the label is going to be split on multiple lines... It seems tricky to me as of now. Of course, we could always use a ghost `UILabel` to size things, but I definitely don't want to inherit the overhead from that.

**Comment by Jeyhey** [comment]
I think that the desired behaviour I described would be very nice to have as it is the way that all applications on iOS (iMessage, WA, Twitter-PMs ...) display message bubbles.

Thank you for the explanations. It helped me finding the source of the problem: It seems that passing `.greatestFiniteMagnitude` as width of `CGRect` to `boundingRect(with:options:context)` is preventing the width to tightly fit the string.

If you use the maximum width of the message container the issue is solved. In the `NSAttributedString` and `String` extensions, change the method to (here for `NSAttributedString`):
``` 
func width(considering height: CGFloat, and width: CGFloat) -> CGFloat {
        let constraintBox = CGSize(width: width, height: height)
        let rect = self.boundingRect(with: constraintBox, options: .usesLineFragmentOrigin, context: nil)
        return rect.width
    }
```

And in `MessagesCollectionViewFlowLayout` call it like so:
``` 
func labelSize(for attributedText: NSAttributedString, considering maxWidth: CGFloat) -> CGSize {
        ...
        let estimatedWidth = attributedText.width(considering: estimatedHeight, and: maxWidth)
        ...
   }
```

**Comment by Jeyhey** [comment]
Should I make a pull-request?

**Comment by SD10** [comment]
@Jeyhey Can you solve this issue with no more than 2 calls to `boundingRect(with:options)`?

 I think it may be a little difficult to submit a PR given the state of the codebase, however, I'm going to look into this for you:

> If you use the maximum width of the message container the issue is solved. In the NSAttributedString and String extensions, change the method to (here for NSAttributedString):

**Comment by SD10** [comment]
@Jeyhey In the latest version of MessageKit we use the maximum width of the `MessageContainerView`. So if that was indeed the fix then this should be resolved. If it is not, then it's not something MessageKit will support. I see a lot of messages throughout all my apps that do not fit the text tightly. I think the sizing operations are too expensive to try and size a message to fit through recursion
