### ISSUE TITLE
Sent messages not appearing correctly

### ISSUE THREAD

**Issue by mmuharem** [MessageKit/MessageKit#436]
## General Information

* MessageKit Version:
0.12.0

* iOS Version(s):
10+

* Swift Version:
3+

* Devices/Simulators:
iPhone 5s-X

* Reproducible in ChatExample? (Yes/No):
Yes

##  What happened?
Out of box, running the 'ChatExample' AND importing MessageKit in podfile to existing project, sending text message does not size correctly at all in simulators

## What did you expect to happen?
That when I send  the word 'Test' as a message, that I see 'Test' AND in the same font size as the previous messages. However, I either see it in smaller font (ChatExample) or I do not see the complete word (pod installation)

<img width="318" alt="screen shot 2018-01-01 at 9 10 12 pm" src="https://user-images.githubusercontent.com/6509420/34472827-6c4c389e-ef38-11e7-8d1e-dae00f7e6c13.png">

<img width="287" alt="screen shot 2018-01-01 at 9 15 04 pm" src="https://user-images.githubusercontent.com/6509420/34472860-e063e02e-ef38-11e7-802b-30f14fa8df1d.png">

**Comment by SD10** [comment]
@mmuharem Are you sure you have MessageKit 12.0 in your project? I’m a little confused as to what you’re saying here. Is your app not working or the ChatExample?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
The ChatExample app should have a smaller font. It’s sending messages as `.attributedText(NSAttributedString)` to check for bugs. I’ll be able to check if there’s an issue in a bit.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mmuharem** [comment]
I did two different things:

1. Downloaded 0.12 and ran the ChatExample. Sending messages is small font (which could be the .attributedText as you mentioned

2. pod 'MessageKit' for my own project installation. This results in this behavior for typing 'Test' below in the screenshot. This one I am completely unsure of as I copied the entire ConversationViewController but only changed one function which got my chat messages. These appear perfectly fine. However, sending a message will not show the entire word 'Test' if I send it. It only shows 'T' and I do not know why 
<img width="296" alt="screen shot 2018-01-01 at 10 17 37 pm" src="https://user-images.githubusercontent.com/6509420/34473509-a50cacb4-ef41-11e7-8d6b-173b356735fd.png">
<img width="296" alt="screen shot 2018-01-01 at 10 17 46 pm" src="https://user-images.githubusercontent.com/6509420/34473510-a8937660-ef41-11e7-936b-de446837f3c8.png">

**Comment by SD10** [comment]
Have you done `pod update`? I want to make sure you’re using 0.12. Does it say that is the version that was installed after `pod install`?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mmuharem** [comment]
Grrrrrr, I just did the pod update and the issue I was facing in option 2 is not there anymore. Only thing I am getting is that the text is the small font like the original iPhone X screenshot I posted earlier. So, how does one change that?

**Comment by SD10** [comment]
You want to use `.text(String)` instead of `.attributedText(NSAttributedString)` when creating a message

**Comment by mmuharem** [comment]
Ah great. Got it. Much appreciated!
