### ISSUE TITLE
When are voice messages supported?

### ISSUE THREAD

**Issue by guoweikun621** [MessageKit/MessageKit#445]
## General Information

* MessageKit Version:

* iOS Version(s):

* Swift Version:

* Devices/Simulators:

* Reproducible in ChatExample? (Yes/No):

**Comment by SD10** [comment]
Hey @guoweikun621,
This is a duplicate of #149.
Ideally, I'd like something that looks like the iMessage audio messages. We also want it to be lightweight, we don't want to deal with audio players 😕  I'm accepting PRs but there's other things I would like to work on that are a higher priority
