### ISSUE TITLE
SeparatorLine height

### ISSUE THREAD

**Issue by Elshad** [MessageKit/MessageKit#446]
## General Information

* MessageKit Version: 0.12.1

* iOS Version(s): 11

* Swift Version: 4

* Devices/Simulators: both

* Reproducible in ChatExample? (Yes/No): YES

##  What happened?

`messageInputBar.separatorLine.height = 0.5`

## What did you expect to happen?
Not changes height of separator
Maybe i use wrong solution. 

How i can change separatorLine hight in messageInputBar?

**Comment by Elshad** [comment]
```
for constraint in messageInputBar.separatorLine.constraints {
    if constraint.identifier == "height" {
        constraint.constant = 0.5
    }
}
```
For now i use this

**Comment by nathantannar4** [comment]
That height property is so people can easily reuse it in the top stack view. If you look you can see if overrides the intrinsic content size. Would you like the height to be changeable?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Elshad** [comment]
@nathantannar4 not dynamic height, but different (0.5) than defined (1.0) in framework
