### ISSUE TITLE
Cell rendering bug

### ISSUE THREAD

**Issue by Elshad** [MessageKit/MessageKit#448]
## General Information

* MessageKit Version: 0.12.1

* iOS Version(s): 11

* Swift Version: 4

* Devices/Simulators: Tested in Simulator

* Reproducible in ChatExample? (Yes/No): Yes

##  What happened?
<img width="363" alt="screen shot 2018-01-09 at 18 14 30" src="https://user-images.githubusercontent.com/2334731/34725093-59346164-f569-11e7-9781-eaa42c7ca117.png">
<img width="364" alt="screen shot 2018-01-09 at 18 21 30" src="https://user-images.githubusercontent.com/2334731/34725324-f761e032-f569-11e7-870d-61ec4717d60c.png">

## What did you expect to happen?
<img width="366" alt="screen shot 2018-01-09 at 18 14 43" src="https://user-images.githubusercontent.com/2334731/34725112-64614ba6-f569-11e7-8230-d0f55b86df13.png">

## When
When swipe controller to half (as shown below picture) and return, cells which not visible while swiping after return rendered badly

<img width="466" alt="screen shot 2018-01-09 at 18 15 18" src="https://user-images.githubusercontent.com/2334731/34725283-da0dbab0-f569-11e7-95cc-30e2358ab9c2.png">

P.S. Sorry for my bad explanation of process

**Comment by Elshad** [comment]
![screencast_480](https://user-images.githubusercontent.com/2334731/34727121-6645cd4c-f56f-11e7-9d2e-f984c519b368.gif)

<img width="395" alt="screen shot 2018-01-09 at 18 54 23" src="https://user-images.githubusercontent.com/2334731/34727168-8c75dab6-f56f-11e7-8393-f7899b366012.png">

**Comment by SD10** [comment]
@Elshad more information as to how you caused this would be great 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Elshad** [comment]
@SD10 
1. I downloaded the ChatExample
2. I opened app in Simulator
3. Action causing bug i paste below as GIF
![screencast_480](https://user-images.githubusercontent.com/2334731/34731160-f2482d66-f57a-11e7-84c3-075fe8fb2011.gif)

As seen content of some cells is not displayed correctly

**Comment by nathantannar4** [comment]
I dont see an issue there? Are you talking about how it slides down? That's standard UIScrollView and UINavigationController interaction

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Elshad** [comment]
@nathantannar4 
Before 
<img width="73" alt="screen shot 2018-01-09 at 21 49 32" src="https://user-images.githubusercontent.com/2334731/34734969-2b625296-f587-11e7-8d7b-8851eb584605.png">
After
<img width="75" alt="screen shot 2018-01-09 at 21 49 43" src="https://user-images.githubusercontent.com/2334731/34734981-38a90990-f587-11e7-966f-bac8f875a50f.png">

Before
<img width="90" alt="screen shot 2018-01-09 at 21 49 35" src="https://user-images.githubusercontent.com/2334731/34734986-3f434004-f587-11e7-972b-1553f14d0918.png">
After
<img width="84" alt="screen shot 2018-01-09 at 21 50 29" src="https://user-images.githubusercontent.com/2334731/34735000-45d6c698-f587-11e7-9707-37431269f968.png">

**Comment by nathantannar4** [comment]
Gotcha

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zhongwuzw** [comment]
@Elshad , Thanks for your report, we have fixed it in `development` branch, we'll merge it in next release. Thanks again!

**Comment by SD10** [comment]
@zhongwuzw Sorry to ping you on everything today. 

Since #461 was not merged, does this mean this is closed but not resolved?

**Comment by zhongwuzw** [comment]
@SD10 The issue reported by @Elshad is resolved, but still has another issue like #461 . 😄
