### ISSUE TITLE
MessageInputBar not resize after message sent

### ISSUE THREAD

**Issue by Elshad** [MessageKit/MessageKit#449]
## General Information

* MessageKit Version: 0.12.1

* iOS Version(s): 11

* Swift Version: 4

* Devices/Simulators: Tested in Simulator

* Reproducible in ChatExample? (Yes/No): No, i cant reproduce in ChatExample

##  What happened?
<img width="364" alt="screen shot 2018-01-09 at 18 32 03" src="https://user-images.githubusercontent.com/2334731/34725852-a8139f00-f56b-11e7-830a-4e99ce540bb3.png">

## What did you expect to happen?
<img width="364" alt="screen shot 2018-01-09 at 18 32 17" src="https://user-images.githubusercontent.com/2334731/34725863-aed94768-f56b-11e7-8ad9-3622152d2ef1.png">

## When
<img width="364" alt="screen shot 2018-01-09 at 18 31 47" src="https://user-images.githubusercontent.com/2334731/34725893-c4a53958-f56b-11e7-887f-08968a801259.png">

When sent message lines count bigger than 1 textView not resize its height.
```swift
let chatMessage = ChatMessage(
    text: text, 
    sender: self.currentSender(),
    messageId: UUID().uuidString, 
    date: Date()
)
vmodel.append(message: chatMessage)
inputBar.inputTextView.text = String()
messagesCollectionView.reloadData()
messagesCollectionView.scrollToBottom()
```

**Comment by Elshad** [comment]
I found the solution, but i dont know its good solution or not.
If it is OK, please close this issue
```swift
let chatMessage = ChatMessage(
    text: text, 
    sender: self.currentSender(),
    messageId: UUID().uuidString, 
    date: Date()
)
vmodel.append(message: chatMessage)
inputBar.inputTextView.text = String()
inputBar.invalidateIntrinsicContentSize() // Added to force inputBar to resize its layout
messagesCollectionView.reloadData()
messagesCollectionView.scrollToBottom()
```

**Comment by SD10** [comment]
cc @nathantannar4

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
You said you can't reproduce it in the ChatExample. Can you please tell me how you are setting up your MessageInputBar? And what are you doing when the user taps send

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Elshad** [comment]
Now i tested, it seems that everything are ok. I can't reproduce it in my app too. Maybe it was Simulator related bug. I think we can close this issue. 
Thank you for you answers and sorry that wasted your time

**Comment by BasThomas** [comment]
No worries @Elshad, thanks for following up! Feel free to reopen if you stumble upon it in the future.

**Comment by tflin** [comment]
It happens in ChatExample. (latest 0.13.0)
Just modify the lines in MessageInputBarDelegate.messageInputBar(_ inputBar: MessageInputBar, didPressSendButtonWith text: String) to be in a DispatchQueue such as:
DispatchQueue.main.async {
        inputBar.inputTextView.text = String()
        self.messagesCollectionView.scrollToBottom()
}

Then this problem happens.

It is common to clear inputBar.inputTextView.text after you successfully send the message to server. So it would be async and will not clean inputTextView when the callback is called.

**Comment by nathantannar4** [comment]
If you are doing this async then you need to call invalidateIntrinsicContentSize. We normally do it after calling the delegate function but if you don’t clear the InputTextView right away then it’s not resized upon clearing the text

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
@tflin It would be better to store the message locally, clear the text field immediately, then attempt to send it to server.

In messaging applications this is how it is usually done. With the addition of a failure message if the message didn’t make to the server, allowing the user to resend.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
^ yup that's how I do it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
Closing this one. Thank you for the feedback everyone 👍
