### ISSUE TITLE
Enable creating custom cell types

### ISSUE THREAD

**Issue by alijaza** [MessageKit/MessageKit#453]
## General Information

* MessageKit Version: 0.12.1

* iOS Version(s): 11

* Swift Version: 4

* Devices/Simulators: NA

* Reproducible in ChatExample? (Yes/No): NA

##  What happened?

Would like to be able to create custom cell types with custom height and width. Currently the cell layout is determined based on the `MessageType`.

## What did you expect to happen?

The height and width of the cell is set in `messageContainerSize(for attributes: MessageIntermediateLayoutAttributes)` which is not overridable. We should ideally be able to subclass `MessageType` and then set the `messageContainerSize` based on attributes of our custom `MessageType'.

**Comment by SD10** [comment]
This is resolved by #491 and #498 and will be much easier to do in MessageKit 0.14.0
