### ISSUE TITLE
How to add custom buttons to chat bubble

### ISSUE THREAD

**Issue by krishna-TMZ** [MessageKit/MessageKit#457]
## General Information

* MessageKit Version:

* iOS Version(s):9.0

* Swift Version:4.0

First I'd like to send my big thanks to the developer. This is a great controller. I am working on an app with api.ai and MessageKit.
I have a requirement to add custom buttons at the bottom of the chat bubble. Please help me.

**Comment by SD10** [comment]
Hey @krishna-TMZ, you're definitely going to need to either create:
a) a custom `MessageCollectionVIewCell` subclass
b) a `MessageFooterView` subclass

It's not that straightforward to do `a` yet, we're working on it #396 #453
