### ISSUE TITLE
How to resize the Media message just like in the old JSQMessagesViewController?

### ISSUE THREAD

**Issue by glennposadas** [MessageKit/MessageKit#460]
Question: how do I make the media the same size as the JSQMessagesViewController's?

![simulator screen shot - iphone x - 2018-01-12 at 12 46 20](https://user-images.githubusercontent.com/12502679/34860168-af3bcf64-f796-11e7-8320-d07057efe999.png)
![simulator screen shot - iphone x - 2018-01-12 at 12 46 40](https://user-images.githubusercontent.com/12502679/34860169-af6ee57a-f796-11e7-920f-d1d129666731.png)

Thank you!

**Comment by SD10** [comment]
@glennposadas You'll want to check out the `MessagesLayoutDelegate` methods for media messages. You can find them [here](https://messagekit.github.io/Protocols/MessagesLayoutDelegate.html#/Media%20Messages).

**Comment by glennposadas** [comment]
Hi Steven, thanks for replying. I stared at the documentation as well as the sample code and tried to find a delegate method for modifying the size of the bubble for media message, but couldn't find one. Sorry, but do you have time to point to me where exactly can I change the size?

**Comment by SD10** [comment]
@glennposadas They're in the link above:
Width:
https://messagekit.github.io/Protocols/MessagesLayoutDelegate.html#/s:10MessageKit22MessagesLayoutDelegateP13widthForMedia12CoreGraphics7CGFloatVAA0A4Type_p7message_10Foundation9IndexPathV2atAG4withAA0C14CollectionViewC2intF
Height:
https://messagekit.github.io/Protocols/MessagesLayoutDelegate.html#/s:10MessageKit22MessagesLayoutDelegateP14heightForMedia12CoreGraphics7CGFloatVAA0A4Type_p7message_10Foundation9IndexPathV2atAG4withAA0C14CollectionViewC2intF

**Comment by glennposadas** [comment]
Awesome! Thank you!
