### ISSUE TITLE
Wrong sent messages bubble size.

### ISSUE THREAD

**Issue by RealBonus** [MessageKit/MessageKit#462]
## General Information

* MessageKit Version:
0.12.1

* iOS Version(s):
11.2, 11.2.2

* Swift Version:
4

* Devices/Simulators:
Simulator: iPhone 8, Device: iPhone 6s

* Reproducible in ChatExample? (Yes/No):
Yes.

##  What happened?
![simulator screen shot - iphone 8 - 2018-01-15 at 17 09 59](https://user-images.githubusercontent.com/14142157/34946277-582c7538-fa17-11e7-8d78-cb5f5523383c.png)

Pregenerated messages has normal sizes (well, most of them), new messages are tiny, even with same message text. Booth on a simulator and a device.

## What did you expect to happen?
Normal sized beautiful green bubble.

**Comment by nathantannar4** [comment]
This is because in the example messages are being sent with attributed text of size 8. This is expected behaviour. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
