### ISSUE TITLE
How to add event message other than bubble?

### ISSUE THREAD

**Issue by superdev89** [MessageKit/MessageKit#463]
In case of group chat, how to add messages like 'Dan has joined to the chat' or sth else like slack?
I don't want to show this as bubble.

**Comment by justdan0227** [comment]
anyone have a comment on this.  I too need something that will allow me to inject things into the chat stream as I need to show chat sessions, and have a divider between them

**Comment by SD10** [comment]
I won't say this isn't possible but I can appreciate it is not easy. If I can get #491 merged this becomes a lot easier. The goal is to possibly make this a `MessageData.system(NSAttributedString)` type. Then you would have to return a `MessageType` for this data. The `Sender` could be "system" I guess.

**Comment by justdan0227** [comment]
Prefect!

**Comment by hamzaozturk** [comment]
It is possible to create a custom cell to show system messages. It is already added in example project.
