### ISSUE TITLE
MessageInputBar.sendButton not disabled after clear inputTextView in program

### ISSUE THREAD

**Issue by tflin** [MessageKit/MessageKit#473]
## General Information

* MessageKit Version: 0.13.0

* iOS Version(s): 11.x

* Swift Version: 4.0

* Devices/Simulators: iPhone

* Reproducible in ChatExample? (Yes/No): Yes

##  What happened?
MessageInputBar.sendButton is still enabled after sending the message. InputTextView's content is cleared in example program:

inputBar.inputTextView.text = String()

## What did you expect to happen?
The sendButton should be disabled.

The notification .UITextViewTextDidChange was not called after clearing inputTextView content programming. Maybe just add 1 one more line to disable the sendButton after clearing.

**Comment by SD10** [comment]
This is resolved in 0.13.1
