### ISSUE TITLE
Is there any way to update the cellBottomLabel only

### ISSUE THREAD

**Issue by tflin** [MessageKit/MessageKit#474]
## General Information

* MessageKit Version: 0.13.0

* iOS Version(s): 11.x

* Swift Version: 4.0

* Devices/Simulators: iPhone

* Reproducible in ChatExample? (Yes/No): 

##  What happened?
Sorry if I missed something.
If including Delivered, Sent, Read status in cellBottomLabel, those status will be updated 3 times after each message is generated. When the status of a message changes, the way to update a message cellBottomLabel will be like:

// Reload some message in the messagePos.
self.messagesCollectionView.reloadSections([messagePos])

Then each message may flicker 3 times.

## What did you expect to happen?
Some way to only reload the cellBottomLabel. Or waiting for 1.0 to including status in the MessageType.

**Comment by SD10** [comment]
@tflin I'm not sure, I don't think so 😅 I started adding new cells for message status tonight. I should have a PR finished tomorrow.

**Comment by SD10** [comment]
@tflin We decided to add another label to the cell to allow users to set a status message as opposed to adding a separate cell for this. We also removed the 1 section to 1 cell limitation so you can have more than 1 message in a single section. Going to close this for now. Feel free to reopen if you have more questions 👍
