### ISSUE TITLE
is there a way to delete a message in conversation #question

### ISSUE THREAD

**Issue by kjoe07** [MessageKit/MessageKit#477]
## General Information
i am cheking docs from version 0.8.0 and forward to find a way to delete a single message from a conversation,. is there a way to do it or is done like a regular collectionView.
* MessageKit Version:
0.8.0...
* iOS Version(s):
11.0
* Swift Version:
3.2
* Devices/Simulators:
iphone 8 +
* Reproducible in ChatExample? (Yes/No):NO

**Comment by zhongwuzw** [comment]
@kjoe07 , first of all, I strongly recommend to use the newest version, `0.8.0` seems obsolete 😅 
, then answer your question, yep, you can operate just like `collectionView`, `MessageKit` is one message to one section, so you can delete message using `deleteSections(_:)` method.

**Comment by kjoe07** [comment]
ok thanks for the replay i'll give a try to new version using swift 4
