### ISSUE TITLE
Add .custom(Any) case to MessageData

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#479]
We should add a `.custom(Any)` case to MessageData so that users can use this as an access point for custom cell content.

I would assign myself but I can’t on GitHawk

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
This is resolved by #498 and will be available in MessageKit 0.14.0

**Comment by stshelton** [comment]
do u have an estimate on when MessageKit 0.14.0 will come out?? I'd like to use this library but need the ability to make custom cells.

**Comment by BasThomas** [comment]
@stshelton in the meantime you could use the following:

```ruby
pod 'MessageKit', :git => 'https://github.com/MessageKit/MessageKit', :branch => 'development'
```

**Comment by SD10** [comment]
@stshelton I don’t recommend development. Its not safe to use 😞

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by scottcc** [comment]
You forgot the "... yet!" postfix there..

**Comment by SD10** [comment]
Yeah @scottcc it’s just that `development` has some performance problems right now

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by scottcc** [comment]
No problem. We're avid users (even still) of Jesse's JSQ stuff, so I'm eagerly following along here as an evolution path. Love the discussions I'm seeing.
