### ISSUE TITLE
 Selected range frame position not updated when input text view is resized

### ISSUE THREAD

**Issue by jr9098** [MessageKit/MessageKit#480]
## General Information

* MessageKit Version:  0.12.0
* iOS Version(s): iOS 11.2
* Swift Version: 4.0
* Devices/Simulators: iPhone 6
* Reproducible in ChatExample? (Yes/No): No

##  What happened?

First I start typing. Autocorrect select my text and give me some suggestions. I Then press a button that resize my text input to show more actions besides the text view. (Items are added in the left stack view). Then,  the selected range frame (in blue) is not updating to the new position of the text input.

![img_0002](https://user-images.githubusercontent.com/13843564/35295255-a1ef5502-0046-11e8-90f9-4c8ca5a27f0e.jpg)

## What did you expect to happen?

I expected that the text selection would appear at the right position when resizing the text view

**Comment by nathantannar4** [comment]
Hi @jr9098, you calling a resize on the MessageInputBar causes this as you point out. It's not as much an issue with the bar but how a UITextView works. Can you try invalidating the size of the InputTextView when you resize the bar?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jr9098** [comment]
@nathantannar4,  I tried inputTextView.invalidateIntrinsicContentSize but it doesn't work.  Any ideas how to force it to layout its subview?

**Comment by nathantannar4** [comment]
Hmm, maybe instead of invalidating the size, set inputTextView.selectedRange = inputTextView.selectedRage

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
