### ISSUE TITLE
Video MessageData won't play when touched/clicked

### ISSUE THREAD

**Issue by NiklasWilson** [MessageKit/MessageKit#484]
## General Information

* MessageKit Version: 0.13.0

* iOS Version(s): 10.3.3(Device) & 11.3(Simulator)

* Swift Version: 4.0

* Devices/Simulators: Device & Simulator iPhone SE 

* Reproducible in ChatExample? (Yes/No):

##  What happened?
I have a message with MessageData video but when clicking the provided play button in the simulator or on a real device the video won't play.

## What did you expect to happen?
I expected the video to play. Maybe I am missing a step, please advise.

![img_0533](https://user-images.githubusercontent.com/7937886/35390983-dc782cfa-01a2-11e8-885a-2a46720aacb2.png)

**Comment by SD10** [comment]
@NiklasWilson MessageKit doesn’t handle playing the actual video content. We believe that is out of scope for the library

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NiklasWilson** [comment]
@SD10 Hmmm... ok so what do you advise then? How do you make videos play in your implementation of message kit?

**Comment by nathantannar4** [comment]
@NiklasWilson we have delegate methods to recognise when a media cell was tapped. Use that to present your video player

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NiklasWilson** [comment]
@nathantannar4 Thanks. Im sure anyone else looking at this thread in the future might also get stuck on this so could you explain this comment a bit? Im not quite understanding how to get the IndexPath for the message.

`   
/// You can get a reference to the 'MessageType' for the cell by using UICollectionView's
/// indexPath(for: cell) method. Then using the returned 'IndexPath' with the MessagesDataSource
/// method messageForItem(at:indexPath:messagesCollectionView).`

but this is what I have so far
`
extension MsgViewController: MessageCellDelegate {
    func didTapMessage(in cell: MessageCollectionViewCell) {
        UICollectionView.indexPath(for: cell)
    }
}`

which just results in 
**_Instance member 'indexPath' cannot be used on type 'UICollectionView'; did you mean to use a value of this type instead?_**

Ive take a look at the source code for
MessageCellDelegate
MessageCollectionViewCell
MessageContainerView
UICollectionView

And I didn't see a single function that returned indexPath, and those seem to be the only files that connect to the _MessageCollectionViewCell_ that is provided by _didtapMessage_

What am I missing?

**Comment by NiklasWilson** [comment]
Someone in the slack pointed out that what I wanted was 
**_messagesCollectionView.indexPath(for: cell)_**

**Comment by SD10** [comment]
For future reference, we have this under the [FAQs section](https://github.com/MessageKit/MessageKit/blob/master/Documentation/FAQs.md).

**Comment by NiklasWilson** [comment]
Thanks @SD10, I took a look at the FAQ.

Is there a  way to get the type of the message from the data contained in the message?

For example I was tying to do this (which does not work)
`let message = messagesDataSource.messageForItem(at: indexPath, in: messagesCollectionView)`
`if message.data == MessageData.video {`
`}`

**Comment by SD10** [comment]
Why not use a switch statement and extract the associated value or an if case let?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NiklasWilson** [comment]
@SD10 Either would be fine, but how does one accomplish "extract the associated value" thats really what i was asking.

The message itself doesn't seem to tell me if its a video/image/etc

**Comment by SD10** [comment]
I’m on mobile so I can’t type an efficient code example. I would google “how to extract associated values in Swift”. It’s very likely Apple even has an example in the language guide section under Enums

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NiklasWilson** [comment]
@Sd10 alright thanks steven

**Comment by NiklasWilson** [comment]
@SD10 Alright figured out the enum stuff but now I am running into **didTapMessage** not being called when tapping a message.

**Comment by SD10** [comment]
Did you tap a cell or the message content itself?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NiklasWilson** [comment]
I tried tapping everything.

**Comment by SD10** [comment]
@NiklasWilson How about `messagesCollectionView.cellDelegate`, is it set?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NiklasWilson** [comment]
this is what I have
`extension MsgViewController: MessageCellDelegate {`
`    func didTapMessage(in cell: MessageCollectionViewCell) {`

:) my bad I see what you mean. I believe thats the problem, its not set

Thank you

**Comment by NiklasWilson** [comment]
This can probably be closed. I think my question has been fully answered and there is enough data in here for someone to be able to get video/audio messages working.

**Comment by Kuro7070** [comment]
@NiklasWilson @SD10 
Hey people, I'm facing a similar problem. My didTapMessage method is not recognizing when I'm clicking on the video Element. With ContactElement and normal messages does it work. Any ideas?
```   
func didTapMessage(in cell: MessageCollectionViewCell) {
        print("tap")
        if let indexPath = messagesCollectionView.indexPath(for: cell) {
            let message = messages[indexPath.section]
            print("did tap message")
            switch message.kind {
                
                case .video(let videoItem):
                    print("video")
                    if let videoUrl = videoItem.url {
                        let player = AVPlayer(url: videoUrl)
                        let playerViewController = AVPlayerViewController()
                        playerViewController.player = player
                        present(playerViewController, animated: true) {
                            playerViewController.player!.play()
                        }
                    }
                
                case .contact(let contactItem):
                    addNewContact(contactData: contactItem)
                
                case .photo(let imageItem):
                    popUpImage(image:imageItem.image!)
                        
                default:
                    break
            }
        }
        
    }
```
