### ISSUE TITLE
messageCollectionViewBottomInset changes after viewDidLayoutSubviews, causing scrollToBottom to not work correctly on initial load

### ISSUE THREAD

**Issue by alijaza** [MessageKit/MessageKit#488]
## General Information

* MessageKit Version: 0.13.0

* iOS Version(s): 11

* Swift Version: 4

* Devices/Simulators: iPhone 8 Plus, iPhone X

* Reproducible in ChatExample? (Yes/No):  No, haven't investigated why not in detail

##  What happened?

I am calling scrollToBottom in `viewDidLayoutSubviews`. This works fine with the iMessage style keyboard, or any keyboard having the same height. When I try with the slack-style keyboard from the example app I notice that the scroll stops a little short of the bottom. It looks like this is happening because `MessagesViewController.handleKeyboardDidChangeState(_:)`, which changes the `messageCollectionViewBottomInset` is called *after* `viewDidLayoutSubviews`.

## What did you expect to happen?

Scroll to bottom should work if the `messageCollectionViewBottomInset` is correct at the time that `viewDidLayoutSubviews` is called

**Comment by nathantannar4** [comment]
Just wanna make sure, your calling the `super` method right? Also, is there a reason you want to call scroll to bottom in `viewDidLayoutSubviews`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
I’m not sure if it’s a good idea to call `scrollToBottom` in `viewDidLayoutSubviews`. It’s called too often. We use to call it here for the first layout but we removed that flag because most messages are downloaded async and it is useless. See the ChatExample for how messages are downloaded and opened starting from the bottom on first load

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alijaza** [comment]
Yes, calling super. I just want to scroll to bottom on initial load. Seems that flag was removed recently from `MessagesViewController`. Is there a better way to achieve this?

**Comment by alijaza** [comment]
Ok, I guess this was a brain fart. I am using NSFetchedResultsController and was confused about when my data would be available. Looks like I can handle all of this in viewDidLoad after all. Thanks for your responses.
