### ISSUE TITLE
Scrolling Collection View while showing keyboard 

### ISSUE THREAD

**Issue by NilStack** [MessageKit/MessageKit#49]
Hi, @SD10:
Great job! 👍 
Here is a suggestion on detail. How about scrolling Collection View to latest message while showing keyboard? The following is comparison on this between MessageKit and JSQMessagesViewController.

![d9047839-6602-4ef4-a0e5-8bb2e69527c2](https://user-images.githubusercontent.com/8167880/29158415-7c1807c0-7ddd-11e7-9875-c8414afe14c9.jpg)

![2d9a1c14-c016-44e4-8e99-88379609eb20](https://user-images.githubusercontent.com/8167880/29158423-838c727a-7ddd-11e7-8c67-a7b199a15bf4.jpg)

Thanks

**Comment by mding5692** [comment]
@NilStack I think I saw a scrollToBottom in the API in this file: https://github.com/MessageKit/MessageKit/blob/master/Sources/MessagesCollectionView.swift,
just think its not implemented in the Example

**Comment by SD10** [comment]
It looks like it's not implemented in the example and not public either. 
Cleaning up access control is part of the goal for `v0.4.0`.

We may want to create a simple helper method similar to JSQMVC such as `finishSendingMessage` which would include this functionality. Something better fit for `v0.5.0` though.

**Comment by NilStack** [comment]
@mding5692 maybe there is also an animation to mimic the keyboard.
https://github.com/jessesquires/JSQMessagesViewController/blob/develop/JSQMessagesViewController/Controllers/JSQMessagesViewController.m#L931 

@SD10 great! 👍

**Comment by SD10** [comment]
@NilStack the `MessagesCollectionView` method `scrollToBottom(animated: Bool)` should be public now in `v0.4.0`. You just have to call this after sending a method.
