### ISSUE TITLE
Alternatives to buddybuild

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#493]
We will need another CI service because buddybuild was accquired by Apple.

This thread has a lot of good information:
https://github.com/rnystrom/GitHawk/issues/1330

Article:
https://pado.name/blog/2018/01/exploring-alternatives-to-buddybuild/

**Comment by nathantannar4** [comment]
Travis is nice

**Comment by SD10** [comment]
Travis has been terrible lately 😅 That's why we switched to buddybuild. I don't have 12-48 hours to wait for a single build of MessageKit to complete

**Comment by kylebrowning** [comment]
Weird that fastlane isnt listed.

**Comment by fbartho** [comment]
@kylebrowning Fastlane isn't hosted?

I'm messing with [Nevercode.io](Nevercode.io) for work.

**Comment by zhongwuzw** [comment]
@SD10 , @nathantannar4 `buddybuild` would be invalid today, which tool we would choose, `CircleCI` or `Travis`?

**Comment by nathantannar4** [comment]
@zhongwuzw I got us approved for a free CircleCI

**Comment by SD10** [comment]
We're using CircleCI now thanks to @nathantannar4 and @zhongwuzw 👏
