### ISSUE TITLE
Input bar covers last message

### ISSUE THREAD

**Issue by NiklasWilson** [MessageKit/MessageKit#494]
## General Information

* MessageKit Version: 0.13.1

* iOS Version(s): 10.3.3(Device) & 11.3(Simulator)

* Swift Version: 4.0

* Devices/Simulators: Iphone SE

##  What happened?

The last message is behind the input bar.

## What did you expect to happen?

The last message to be above the input bar.

![simulator screen shot - iphone se - 2018-01-29 at 09 16 30](https://user-images.githubusercontent.com/7937886/35517807-25b54508-04d5-11e8-9800-594deb53f21d.png)

**Comment by SD10** [comment]
@NiklasWilson Thanks for reporting this but we need more information to help. You haven’t told us if it is replicable in the example project or not. Have you done anything to modify the top inset or bottom insets yourself?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NiklasWilson** [comment]
@SD10 
I will look into testing it on the example project, was hoping to avoid doing that. 

The only thing I do is add a NSAttributed string to top cell label.

now my extension to the MessagesLayoutDelegate does have
`    func heightForLocation(message: MessageType, at indexPath: IndexPath, with maxWidth: CGFloat, in messagesCollectionView: MessagesCollectionView) -> CGFloat {`
`        return 0;`
` }`

could that be the problem?

**Comment by SD10** [comment]
Not likely any of those are the issue. Share your message input bar code?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NiklasWilson** [comment]
My message input bar code doesn't seem like it would effect it.

This is my input bar delegate 
https://pastebin.com/s7492CWd

This is how I add the upload button
`        // Appends the upload button to input bar`
`        var currentLeftStack = messageInputBar.leftStackViewItems`
`        currentLeftStack.append(uploadButton)`
`        messageInputBar.setStackViewItems(`
 `            currentLeftStack,forStack: InputStackView.Position.left,animated: false`
`)`
`        messageInputBar.setLeftStackViewWidthConstant(to: 45, animated: false)`

but I dont do anything anywhere to modify its height.

**Comment by NiklasWilson** [comment]
@SD10 It did not occur in the example project, but all I did was run the example project.
So something that I am doing is messing it up.

My previous view has a bottom nav bar which was actually  preventing this issue as it was beneath the input bar, but I was able to slightly see the bottom nav bar as the input bar didn't cover it 100%  so i turned it off and now this problem has occurred.

**Comment by NiklasWilson** [comment]
https://github.com/MessageKit/MessageKit/issues/399 This seems to be related to my problem as this is exactly the problem I had which I solved by turning on "**_hidesBottomBarWhenPushed_**" which then resulted in my current problem.

**Comment by NiklasWilson** [comment]
SOLUTION
   ` override func viewDidLayoutSubviews() {`
    `    messagesCollectionView.contentInset.bottom = messageInputBar.frame.height`
     `   messagesCollectionView.scrollIndicatorInsets.bottom = messageInputBar.frame.height`
  `  }`

Which is apparently in the example app, must have missed that, but for anyone else who runs into the issue, this fixes it. (Solution proved by Corey)

**Comment by funct7** [comment]
This is a bad very solution. If I'm using a `UICollectionView` subclass, I should be able to set the `contentInset` the same way I would for any `UICollectionView` type and see the same effect. If the `MessagesViewController` is to have a `UICollectionView` property, it should either document the weird behavior or let the collection view behave like it should. If the view controller fails to honor that, that's the library's fault. I shouldn't have to compensate for that behavior.

I happened to run into this issue because setting `messagesCollectionView.contentInset.bottom` did nothing. Maybe I should file an issue...

**Comment by nathantannar4** [comment]
Use the didChangeIntrinsicContentSize delegate method of the MessageInputBar to adjust the bottom inset. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by karthikkmanoj** [comment]
I too face the same issue. What is the fix? Can anyone give the code?[
![img_0895](https://user-images.githubusercontent.com/34007582/49497222-e2908780-f88d-11e8-8466-4e2b54fbfe5d.PNG)
](url)

**Comment by funct7** [comment]
@nathantannar4 Yeah... but that ain't the same as `UICollectionView.contentInset`. As I mentioned in another thread, if a subclass breaks the behavior of the parent class, it's not a valid subtype.

**Comment by nathantannar4** [comment]
@funct7 we adjust the content inset automatically. I believe this issue is outdated for MessageKit 2.0. We added an `additionalBottomContentInset` if you want to increase it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by funct7** [comment]
@nathantannar4 If I may repeat myself, you guys are **breaking the behavior of the parent class**. If you guys are willing to do that, which I really believe you shouldn't, at least provide enough documentation about it. People should be able to use a library by looking at just the interface, not poring over private code.

**Comment by bhaveshbc** [comment]
@karthikkmanoj did you found any solution?

**Comment by karthikkmanoj** [comment]
@bhaveshbc No Dude. When the keyboard is open, the last message gets covered. What version of Message Kit you using?

**Comment by bhaveshbc** [comment]
2.0
