### ISSUE TITLE
Adding attributed text label to messages. 

### ISSUE THREAD

**Issue by MacMeDan** [MessageKit/MessageKit#50]
As a MessageKit user I want the ability to customise the text style and color in a message. Often times incoming messages have a different background color and for readability I would like to be able to change the color of the text to provide better contrast.

**Comment by SD10** [comment]
@MacMeDan I forgot to add this to the `v0.3.0` release notes but `MessageType` now supports:
`case text(String)` & `case attributedText(NSAttributedString)`

**Comment by MacMeDan** [comment]
Then this task is just update the example project to using `attributedText(NSAttributedString)`
