### ISSUE TITLE
Improve caching strategy

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#504]
After talking with @zhongwuzw we decided it would be good to change our caching strategy to an `IndexPath` based approach. 

This puts the emphasis on scroll performance and not the speed of the layout itself. We’ve already made improvements to the layout speed by using a context for storing previously calculated attributes.

The index path strategy requires that we invalidate any affected index paths after any reload, insertion, move, or deletion of cells in the collection view.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
This is being worked on in #502

**Comment by SD10** [comment]
It's unfortunate, but we're still facing that issue resolving undefined behavior by allowing users to make layouts dynamic over an `IndexPath`. So this is taking longer than expected:

```swift
func avatarSize(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> CGSize {
    let isEven = indexPath.section % 2 == 0
    return isEven ? .zero : CGSize(width: 20, height: 20)
}
```

### What needs invalidation
We need layout invalidation for the following scenarios:
- invalidate all indexPaths after the location of an insertion from the middle 
- invalidate all indexPaths after the location of a deletion from the middle

### What does not need invalidation
If the change only occurs at the end of the indexPaths then the attributes are fine:
- inserting N new sections at the end
- deleting N sections from the end

**Comment by zhongwuzw** [comment]
Because of the dynamic of layout, maybe we should remove all cached attributes except insert or delete cells at the end.

**Comment by SD10** [comment]
Same thing I spent hours complaining to @cwalo @nathantannar4 months ago. This is proof that it is impossible to cache anything without undefined behavior:

```Swift
// This is an example of how a user could reasonably write code
// that would stack bubbles with a single avatar
func avatarSize(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> CGSize {
        if indexPath.section > 0 {
            let previousIndexPath = IndexPath(item: 0, section: indexPath.section - 1)
            let previousMessage = messageForItem(at: previousIndexPath, in: messagesCollectionView)
            let isLastMessage = lastMessage.sender == message.sender
            if isLastMessage { return .zero }
        }
        return CGSize(width: 30, height: 30)
}
```

You can write code that is dynamic over the current `IndexPath` or `MessageType`.
You can write code that is dynamic over a past or future `IndexPath` or `MessageType`.

If you modify the collection view contents in any way we have to invalidate. The only thing you'll get from caching would be some scroll performance for previously seen messages. Too much work for too little benefit.

**Comment by SD10** [comment]
The only sort of cache that `JSQMVC` implements is for [bubble sizes](https://github.com/jessesquires/JSQMessagesViewController/blob/624fcfaa2a2dae86cd6f22c88cebea48f4f73d61/JSQMessagesViewController/Layout/JSQMessagesBubblesSizeCalculator.m). This is using the message data (text or media) for the `hashValue`. If this content has already been seen we know how to size it. Seems trivial without a benchmark IMO 😐

**Comment by zhongwuzw** [comment]
@SD10 , what's the `milestone` of this?

**Comment by SD10** [comment]
@zhongwuzw I'm not sure 🤔 The `master` branch does do caching but it is turned off by default. I feel pretty confident leaving it out of 1.0. What do you think?

**Comment by zhongwuzw** [comment]
@SD10 😂  , I'll make some performance to compare to `JSQ`, like #509 , to see wether we `must` add cache capacity.

**Comment by SD10** [comment]
Sounds good👌 it’s pretty difficult to compare the two though. You have to consider the time to create all the mock messages. Better comparison would be vs MessageKit master

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
Really no reason to do this at the moment. Caching would only lead to undefined behavior. The layout speed has increased so much that we shouldn't continue to prematurely optimize
