### ISSUE TITLE
MessageCollectionViewCell duplication (with video content) when scrolling

### ISSUE THREAD

**Issue by mohzameer** [MessageKit/MessageKit#506]
## General Information

* MessageKit Version: 0.13.1

* iOS Version(s): 11

* Swift Version: 4

* Devices/Simulators: iPhone 8 plus

* Reproducible in ChatExample? (Yes/No): Yes

##  What happened?
I'm showing videos in MessageCollectionViewCell when a video cell play button is tapped. I have made sure that only one instance of avcontroller is used across the conversation, so if a new video cell is clicked while playing one, playing once will be closed and new one will play. So it works alright.
**Problem is that** sometimes, when we scroll like a page or so while video is paused or being played, another video cell would have the exact same video at the playing at the same time. Now, it cannot be an issue with my implementation of video playing, because
1. My code starts only after tapping a cell
2. All video cells doesn't appear so, only on a cell comes in after 'complete page scroll'
So, clearly cells are duplicating, it might be an effect of dequeuing.

## What did you expect to happen?
Video cells appear as thumbnails and when clicked it should play the video, the thumbnails should be up for all video cells unless clicked after scrolling.

**Comment by SD10** [comment]
Closing this as it's a client side issue. The discussion for this happens in #507
