### ISSUE TITLE
Benchmark vs JSQMessagesViewController

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#509]
We're having trouble resolving #502. After discussing with @zhongwuzw, we determined we will probably not be able to cache anything because the layout is too dynamic. If we do, we would have to clear the cache upon any `insert`, `move`, `delete`, or `reload` inside of the collection view.

I think it would be good to have a few benchmarks of layout / scrolling performance to compare to JSQMVC. This will let us be aware of this is a problem and make any new design decisions.

EDIT: The branch in need of bench mark is `development` for #502

**Comment by zhongwuzw** [comment]
@SD10 

Just a simple test(Device:6SP):
Two lib has 10000 messages.

`MessageKit`'s frame rate:

<img width="1280" alt="messagekit" src="https://user-images.githubusercontent.com/5061845/35785123-fbdbfa7c-0a58-11e8-8e7a-1df5542396dd.png">

`JSQ`'s frame rate:
<img width="1280" alt="jsq" src="https://user-images.githubusercontent.com/5061845/35785128-027e44b6-0a59-11e8-83a2-ca0f51f108ae.png">

`MessageKit`'s time profile:
The cost of first time screen is huge, after that, when we
 add a new message, we can feel a lag.

<img width="1280" alt="time" src="https://user-images.githubusercontent.com/5061845/35785234-eae8e2a6-0a59-11e8-8918-ba43aec3eae5.png">

**Comment by SD10** [comment]
Thank you for taking the time to do this @zhongwuzw 🙏 Did you use `development` and turn on the cache? It is off by default

**Comment by tflin** [comment]
There is an obvious delay when entering a chat or adding a new message if there are more than 200 messages as @zhongwuzw tested. Hopefully the delay can be resolved soon.

**Comment by SD10** [comment]
@tflin The tests are for 10,000 messages which is an unreasonable amount of messages IMO. If you have 10,000 messages you're designing your app wrong. What is your benchmark for 200 messages?

**Comment by tflin** [comment]
On 2 iPod touch 5 devices, when entering a chat with around 200 messages with mixed picture, text and location, it takes around 10 seconds to show the screen and then scroll it to bottom. At that same chat, it takes around 10 seconds on self.messagesCollectionView.insertSections([messageCount - 1]). The tested version of MessageKit is 0.13.1. If the message count is fewer or all are text messages, the delay will be obviously shorter.

**Comment by SD10** [comment]
Thanks for getting back to me with some specs @tflin 💯! MessageKit will likely move to only iOS 10+ support as we approach iOS 12. So we likely won't support iPod Touch 5. This is still a cause for concern. If you have any suggested improvements feel free to let us know

**Comment by tflin** [comment]
@SD10 Thanks for quick reply. It is not a problem not to support iPod 5 or iOS 9. Our tester just tested it on the iPods and gave me those measures but I think the delay problem will also happen on iOS 11 or higher iOS devices. As @zhongwuzw testing, it takes more than 20 secs for MessageKit to show the first screen compared to less than 4 seconds for JSQ's. That's why I suggested it should
 be resolved by some way. Maybe MessageKit 0.14 with new static cell bottom label size will improve a lot.

**Comment by SD10** [comment]
Closing this one since I know where we stand now
