### ISSUE TITLE
How to add quick reply answers?

### ISSUE THREAD

**Issue by jj-at-fdt** [MessageKit/MessageKit#511]
What is the best way to add quick replies to the message as on the image below. Quick reply options come with the message and when user select an option, it is sent to to the channel.

![quickreplies2-ea958f6b](https://user-images.githubusercontent.com/15378716/35869314-6bdce8fe-0b67-11e8-9333-1a50d8a337c8.png)

I am wondering what is the right direction to go...? It is a custom MessageCollectionVIewCell subclass or a MessageFooterView subclass, or it is rather a MessageInputBar Plugin?

There is another related issue open here #254. 

Chat bots are becoming more and more popular and it would be nice to see broader support for common chat bot transactional messages in MessageKit as well.

**Comment by nathantannar4** [comment]
You can place a collection view in the top MessageInputBar's stack view and have each cell be the quick reply

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
Message me on slack if you need help implementing it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
@jjarv Thanks for opening this issue. I'm going to close it for now. Feel free to reopen with any other questions 👍

**Comment by codemonza** [comment]
Here's how to "place a collection view in the top MessageInputBar's stack view and have each cell be the quick reply":

Step 1: Force intrinsicContentSize of the said collection view. Similar to how it's done here: viewhttps://github.com/MessageKit/MessageInputBar/blob/master/Plugins/AutocompleteManager/Views/AutocompleteTableView.swift
Step 2: Add the collection view instance to the messageInputBar of the MessageViewController instance using addArrangedSubview
```
// In the subclass of MessageViewController
override func viewDidLoad() {
        super.viewDidLoad()
        let quickReplyVC = QuickReplyCollectionViewController() 
        messageInputBar.topStackView.addArrangedSubview(quickReplyVC.collectionView)
        ....
}

**Comment by codemonza** [comment]
Placed a CollectionView with 3 Button (which when pressed prints a statement) on topStackView. When the CollectionView is "standalone", the print statements work. On topStackView they didn't.

How the button actions are set:- In the CollectionViewController's *cellForItemAt*:
```let button: UIButton = {
         abutton.addTarget(self, action: #selector(buttonAction), for: .touchUpInside)
         return abutton
         }()    
        cell.addSubview(button)
```

There is also now this error when I type into the inputbar and press Send. The three buttons disappeared and chat screen became inaccessible. Before putting anything on topStackView of course the inputbar was working fine.
```API error: <_UIKBCompatInputView: 0x101a5d770; frame = (0 0; 0 0); layer = <CALayer: 0x282c6fac0>> returned 0 width, assuming UIViewNoIntrinsicMetric```

**Comment by codemonza** [comment]
May I request this issue be reopened?

**Comment by fukemy** [comment]
i think u got pointer issues, the pointer is point to other, but the current does not release
