### ISSUE TITLE
Typing Indicators

### ISSUE THREAD

**Issue by emperorhaplo** [MessageKit/MessageKit#513]
Hello,

Is there any kind of typing indicator similar to what imessage or other chat programs provide, like an animated ellipsis? I just need to display that in a bubble sometimes.

Also are GIFs supported out of the box or do I need to do something special to get them to work?

Thanks!

**Comment by SD10** [comment]
Hey @emperorhaplo,
Thanks for opening this issue. 
Unfortunately, there is no GIF support out of the box. I know others have gotten this working though. As for the typing indicator, this is a duplicate of #191. This feature currently does not exist in MessageKit.
