### ISSUE TITLE
How to Hide/Remove AvatarView from Collectionview?

### ISSUE THREAD

**Issue by PawanManjani** [MessageKit/MessageKit#517]
## General Information

* MessageKit Version:

* iOS Version(s):

* Swift Version:

* Devices/Simulators:

* Reproducible in ChatExample? (Yes/No):

**Comment by SD10** [comment]
How can I remove the AvatarView from the cell?

If you return CGSize.zero from the MessagesLayoutDelegate method avatarSize(for:MessageType,at:IndexPath,in:MessagesCollectionView), the AvatarView will not be visible for that cell.

```Swift
func avatarSize(for: MessageType, at: IndexPath, in: MessagesCollectionView) -> CGSize {
    return .zero
}
```

**Comment by PawanManjani** [comment]
Solved, Thank you are quick response....

**Comment by PawanManjani** [comment]
Can't build my project after adding 'MessageKit'.


<unknown>:0: error: fatal error encountered while reading from module 'MessageKit'; please file a bug report with your project and the crash log
<unknown>:0: note: compiling as Swift 3.2, with 'MessageKit' built as Swift 4.0 (this is supported but may expose additional compiler issues)

**Note: My project is running in Swift 3.2**

**Comment by PawanManjani** [comment]
Also added

post_install do |installer|
        installer.pods_project.targets.each do |target|
            if target.name == 'MessageKit'
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = '4.0'
                end
            end
        end
    end

**Comment by cwalo** [comment]
Thanks for opening a separate issue: https://github.com/MessageKit/MessageKit/issues/522
