### ISSUE TITLE
Send button text goes to ellipsis with Larger Text setting.

### ISSUE THREAD

**Issue by crspybits** [MessageKit/MessageKit#518]
## General Information

Get ellipsis with "Send" button if you use Settings app > General > Accessibility > Larger Text, turn it on and select a mid-size setting on their scale.

* MessageKit Version:

0.13.1

* iOS Version(s):

11.2

* Swift Version:

4

* Devices/Simulators:

iPhone X both real and simulated.

* Reproducible in ChatExample? (Yes/No):

Yes

##  What happened?

<img width="373" alt="screen shot 2018-02-13 at 7 33 06 pm" src="https://user-images.githubusercontent.com/5758762/36185153-e9c65146-10f4-11e8-998c-c829eb8b52d8.png">

## What did you expect to happen?

I expect  to see all the "Send" text.

## My work around

Right now, I'm doing the following:

        messageInputBar.sendButton.titleLabel?.font = UIFont.systemFont(ofSize: 22.0)

but I'd rather not just disable that dynamic font size.

--------------
I really like this library. I'd be happy to add my app to your list. Not sure where that list is though!

**Comment by nathantannar4** [comment]
Hi @crspybits thats a good catch. This would be because we initialize the font of the send button to a dynamic size with `$0.titleLabel?.font = UIFont.preferredFont(forTextStyle: .headline)` however due to the architecture of the `MessageInputBar` has width constraints on the left and right stack views. A fix for this would be to change the font of the send button such that it is static and not a .preferredFor(:)

**Comment by RealBonus** [comment]
Width constrains on labels and buttons also doesn't works well with localization.
For example, russian translation "Отправить":
![Send](https://user-images.githubusercontent.com/14142157/36566307-21c8ef86-1834-11e8-92d5-b83bd172c0d0.png)

**Comment by wiistriker** [comment]
+1

**Comment by nathantannar4** [comment]
@wiistriker You should get the dynamic font size and use it as a factor in setting the right stack view width. It needs to be big enough to fit the button

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
