### ISSUE TITLE
Making cellTopLabel and cellBottomLabel have static sizes

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#519]
We can decrease the time spent laying out each cell by ~53% if we make the `cellTopLabel` and `cellBottomLabel` have static sizes. We're getting killed by sizing attributed text to fit 2x per cell.

This is kind of a non-backward compatible change for a few reasons:
- We would likely move the `LabelAlignment` enum and users would use a combination of `UIEdgeInsets` for text and `NSTextAlignment` to position the label. Like JSQMVC.

- We would probably have to remove `AvatarPosition.Vertical`'s `cellTop` and `cellBottom` cases
because the labels would have the constant width of the cell. Like JSQMVC.

- This means you wouldn't be able to align the top edges of an `AvatarView` and `cellTopLabel` or `cellBottomLabel`. Like JSQMVC.

More on this to come. This is what has development stale lately

**Comment by hyouuu** [comment]
Given the performance hit I think this is a good move. Maybe we can have the flexibility to define different static sizes for different message types if there are needs for a few different sizes.

**Comment by SD10** [comment]
Yeah I'm working on some stuff surrounding this @hyouuu

**Comment by SD10** [comment]
You can see the PR for this @ #580. Should reduce layout times by potentially as much a 70% actually

**Comment by SD10** [comment]
Resolved by #580
