### ISSUE TITLE
Can't build my project after adding 'MessageKit'.

### ISSUE THREAD

**Issue by PawanManjani** [MessageKit/MessageKit#522]
## General Information

* MessageKit Version:
Latest
* iOS Version(s):

* Swift Version:
3.2
* Devices/Simulators:

* Reproducible in ChatExample? (Yes/No):

##  What happened?
:0: error: fatal error encountered while reading from module 'MessageKit'; please file a bug report with your project and the crash log
:0: note: compiling as Swift 3.2, with 'MessageKit' built as Swift 4.0 (this is supported but may expose additional compiler issues)

Also added

```rb
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'MessageKit'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.0'
      end
    end
  end
end
```

**Comment by PawanManjani** [comment]
Any Solution @BasThomas ???

**Comment by nathantannar4** [comment]
Please take a look at suggestions in #485

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
