### ISSUE TITLE
Keyboard covers latestest messages

### ISSUE THREAD

**Issue by NiklasWilson** [MessageKit/MessageKit#525]
## General Information

* MessageKit Version: 0.13.1

* iOS Version(s): 11.2

* Swift Version: 4

* Devices/Simulators: all (iPhone 7, iPhone se, iPhone x)

* Reproducible in ChatExample? (Yes/No): No :/

##  What happened?

When clicking the message input bar the keyboard covers the last X messages 

## What did you expect to happen?

The keyboard to move the messages view up so 100% of the messages are visible.

## What i've tried

I have gone through the example app to try and find how it accomplishes it but nothing I found in there fixes it. I tried adding
```
        scrollsToBottomOnKeybordBeginsEditing = true
        maintainPositionOnKeyboardFrameChanged = true
```

and I have
```
    override func viewDidLayoutSubviews() {
        messagesCollectionView.contentInset.bottom = messageInputBar.frame.height
        messagesCollectionView.scrollIndicatorInsets.bottom = messageInputBar.frame.height
    }
```

Please advise. I have also looked at https://github.com/MessageKit/MessageKit/issues/243 and https://github.com/MessageKit/MessageKit/pull/358

**Comment by SD10** [comment]
@NiklasWilson You need to call `super.viewDidLayoutSubviews()`

**Comment by NiklasWilson** [comment]
!! such a simple solution for a problem i've been stuck on for such a long time.
Thank you.

**Comment by SD10** [comment]
@NiklasWilson In general, any time you override a framework method you should be a good citizen and call the `super` class implementation. This rule is _not absolute_ as sometimes you will not want the side effects of the `super` call, but it is something to watch for 😃

**Comment by NiklasWilson** [comment]
@SD10 Thanks for the advise. Well if anyone else manages to get themselves into this problem I guess there is a record of the solution now :P

**Comment by NiklasWilson** [comment]
If your typing a new message, as soon as your messages hits line two this issue reoccurs. Is there some other kind of simple super that I have failed to call that could be causing it?

**Comment by Sumire226** [comment]
Thanks a lot for this post. It saved me also!! :)
