### ISSUE TITLE
Turn off timestamps

### ISSUE THREAD

**Issue by NiklasWilson** [MessageKit/MessageKit#526]
##  What happened?

Messagekit shows timestamps every so often just like iMessage

## What did you want to happen?

I would like to turn them off.

![screen shot 2018-02-19 at 8 17 24 am](https://user-images.githubusercontent.com/7937886/36382140-8b58a0b6-154d-11e8-8cc9-0763fb39ef96.png)

**Comment by SD10** [comment]
@NiklasWilson You can override the `MessagesDisplayDelegate` method `shouldDisplayHeader` and return `false`.

**Comment by NiklasWilson** [comment]
Awesome thank you.
