### ISSUE TITLE
Keyboard Pre-Loading

### ISSUE THREAD

**Issue by mmuharem** [MessageKit/MessageKit#528]
## General Information

* MessageKit Version:
13.1

* iOS Version(s):
11

* Swift Version:
4

* Devices/Simulators:
Simulator 

* Reproducible in ChatExample? (Yes/No):
Yes

##  What happened?
Is there any way to get the keyboard type (imessage/slack/default) to load before view controller appears? 

For example, In the chat example, if I choose to do `self.slack()` in `viewDidLoad()` or `viewDidAppear()` as the keyboard I would like users to see, unfortunately you are still able to see the keyboard change from just a bar on the top to then the 'slack' component with the bottom bar with buttons when you select '`Example`' from the `inboxViewController`

The images below were run with the simulator in slow animations mode

<img width="295" alt="screen shot 2018-02-20 at 12 31 37 am" src="https://user-images.githubusercontent.com/6509420/36408845-f38c87a0-15d5-11e8-882a-88ca68b1a178.png">
<img width="294" alt="screen shot 2018-02-20 at 12 31 44 am" src="https://user-images.githubusercontent.com/6509420/36408846-f398535a-15d5-11e8-90f7-585683b4b91b.png">

I understand that this is because the keyboard is built every time the view controller appears/loads, but if I am trying to avoid that and have a standard pre-loaded keyboard appear, how can I do this?

## What did you expect to happen?
I wanted the keyboard choice that I pick (Slack) programmatically in `viewDidAppear` or in `viewDidLoad` to be pre-built and not show the change when the controller loads. 

Any help would be appreciated!

**Comment by nathantannar4** [comment]
Hello, yes you can build it in viewDidLoad you just have to make sure that any size adjustments are not animated. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mmuharem** [comment]
Fantastic! 

That helped me to look at this in a different way and I have it doing exactly what I want. 

Thanks for the help Nathan!

**Comment by cwalo** [comment]
@nathantannar4 Did you mean to reopen this one?
