### ISSUE TITLE
Send button enabled state always controlled by MessageInputBar

### ISSUE THREAD

**Issue by clayellis** [MessageKit/MessageKit#529]
## General Information

* MessageKit Version: 0.1.13

* iOS Version(s): iOS 11.2 (Not relevant)

* Swift Version: 4 (Not relevant)

* Devices/Simulators: Both

* Reproducible in ChatExample? (Yes/No): Yes

##  What happened?
I would expect to be able to control the `isEnabled` state of the send button beyond text just being in the field. Currently the send button is enabled whenever there is text in the field. 

## What did you expect to happen?
In my application, I have another use case where I need to control the state.

**Comment by clayellis** [comment]
This would be fixed by #530

**Comment by zhongwuzw** [comment]
Fixed in #530 , Thanks 👍 !
