### ISSUE TITLE
"messageStyle" didn't change bible tail

### ISSUE THREAD

**Issue by KuDji** [MessageKit/MessageKit#534]
## General Information

* MessageKit Version: 0.13.1
* iOS Version(s): 11.2
* Swift Version: 4
* Devices/Simulators: iPhone 6(Device)/ iPhone 8 (simulator)
* Reproducible in ChatExample? (Yes/No): Yes

##  What happened?

Buble tail set once in method and didn't change any more.

<img width="1846" alt="2018-02-22 9 26 13" src="https://user-images.githubusercontent.com/25083996/36523600-6b1f848c-17b3-11e8-84b7-54f731ee3437.png">

```swift
func messageStyle(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> MessageStyle {
        
        if isFromCurrentSender(message: message) {
            return MessageStyle.bubbleTail(.bottomLeft, .pointedEdge)
        } else {
            return MessageStyle.bubbleTail(.bottomRight, .pointedEdge)
        }
    }
```

**Comment by KuDji** [comment]
If I comment whis code, framework fine: 
`if let cachedImage = cache.object(forKey: path as NSString) {
          return cachedImage
  }`

**Comment by SD10** [comment]
Hey @KuDji, this was resolved in #531. Can you please update your `pod`?

**Comment by KuDji** [comment]
@SD10 Thx. In real project error doesn't heppened. In the beginning, I only look at an example project in the library.

**Comment by SD10** [comment]
No problem @KuDji 👍 Thank you for clarifying 😃
