### ISSUE TITLE
Bubble outline colour always showing black

### ISSUE THREAD

**Issue by aaasifrz9** [MessageKit/MessageKit#535]
## General Information

I tried to change bubble outline with below code but always showing black outline color.
```swift
    func messageStyle(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> MessageStyle {
        return .bubbleOutline(UIColor.red)
    }
```
I also tried other colors. But no success.

**Link Sample:** https://github.com/MessageKit/MessageKit
**Page:** ConversationViewController.swift
**Method:** messageStyle in extension ConversationViewController: MessagesDisplayDelegate

I have 2 users and I want to show bubble outline color different for each user. But with above code in the provided sample is not working.

Please help. Thanks in advance.

@SD10 ,@nathantannar4 , @zhongwuzw 

![img_1840](https://user-images.githubusercontent.com/24565054/36577908-39220928-1880-11e8-91b7-01157d41854b.PNG)
![img_1839](https://user-images.githubusercontent.com/24565054/36577931-5a305962-1880-11e8-89aa-0f8668cb8395.PNG)

**Comment by SD10** [comment]
@aaasifrz9 I would recommend using `MessageStyle.custom` until we can investigate. I'm wondering if #469 had something to do with this

**Comment by zhongwuzw** [comment]
@SD10 , yep, `tintColor` is invalid because we remove the template image.

**Comment by SD10** [comment]
Thanks for confirming @zhongwuzw. We'll have to figure out how to resolve this. Ultimately I want to move away from using images for MessageStyle. It's a low priority change compared to the other changes I need to make. In the meantime people should use `MessageStyle.custom`

**Comment by aaasifrz9** [comment]
I also tried with `MesageStyle.custom` as below but the same result black outline.

```swift
func messageStyle(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> MessageStyle {

    let configurationClosure = { (view: MessageContainerView) in
        view.style = .bubbleOutline(UIColor.red)
    }
    return .custom(configurationClosure)
}
```

**Comment by zhongwuzw** [comment]
@SD10 , we can refactor bubble to remove `mask` after the `BIG change`.
I have committed a `PR` to resolve this issue temporary. But `bubbleTailOutline` still has this issue.

**Comment by aaasifrz9** [comment]
Hi @SD10 ,

Now can I check for outline color, is it working? If yes, please give me some hints where i can set different outline color for different parties?

Thanks a lot.

**Comment by SD10** [comment]
@aaasifrz9 Instead of using a `MessageStyle.bubbleOutline` use `MessageStyle.custom` but do not use it to set another style. Use it to set a border around the `MessageContainerView`

**Comment by aaasifrz9** [comment]
Can you please give me a sample example to set border according to indexPath? Also tried to set layer border with width at `view: MessageContainerView` but no success. Because .custom has closure and it is not setting border properly on each indexPath.
Please help.

**Comment by SD10** [comment]
@aaasifrz9 This is fixed now on `master`

**Comment by aaasifrz9** [comment]
Ok I'll check let you know. Thanks.

**Comment by aaasifrz9** [comment]
Thanks @SD10 , its now working now.

**Comment by Anatoli-Petrosyants** [comment]
not working

**Comment by vsyw** [comment]
Still not working

**Comment by SD10** [comment]
@iwantooxxoox What is your version of MessageKit?

**Comment by zhongwuzw** [comment]
@iwantooxxoox and which `MessageStyle` do you use?

**Comment by vsyw** [comment]
@SD10:  MessageKit 0.13.1
@zhongwuzw like this: `MessageStyle.bubbleOutline(UIColor.red)`

**Comment by vsyw** [comment]
@SD10, @zhongwuzw: Please don't bother, I just updated to 0.13.5, and it works fine now, thanks~~
