### ISSUE TITLE
How to send text message with emojis?

### ISSUE THREAD

**Issue by aaasifrz9** [MessageKit/MessageKit#541]
## General Information

I am trying to send the text message with emojis. It sends individual. Please see attached screenshots.
How can I send the text message with emojis? Please help.

![img_1849](https://user-images.githubusercontent.com/24565054/36664402-936272ba-1b0a-11e8-9c6a-86cfde7f13b1.PNG)
![img_1850](https://user-images.githubusercontent.com/24565054/36664422-a57254b6-1b0a-11e8-9d91-240d099eda81.PNG)

**Comment by SD10** [comment]
Looks like something to do with your client code and not MessageKit. You only use `MessageData.emoji` for text that contains a single emoji.

**Comment by aaasifrz9** [comment]
Thanks. I fixed it.
