### ISSUE TITLE
Question - Custom bubble cell centralized

### ISSUE THREAD

**Issue by BrenoVin** [MessageKit/MessageKit#543]
How can I create a custom message bubble cell with a centralized text, like the date label, but as a message.

**Comment by zhongwuzw** [comment]
If you just want a centralized text, you can set `textAlignment` of `MessageLabel` to `.center`.

**Comment by BrenoVin** [comment]
But this will align the text in the bubble, but I want to align the text in the screen

**Comment by SD10** [comment]
@BrenoVin Use the `.cellCenter` label alignment

**Comment by BrenoVin** [comment]
@SD10 where I can use this? I found the use of this only for cellTopLabel and cellBottomLabel, and not for the MessageLabel. tks

**Comment by BrenoVin** [comment]
My case is that:
I have a room with 3 senders, and the messages of one of these 3 users must be centered in View, not in the bubble.

**Comment by SD10** [comment]
@BrenoVin You would need to use `messagePadding(for:at:in)` of `MessagesLayoutDelegate` to center it in the cell. You need to consider the avatar size as well
