### ISSUE TITLE
Adding a subview, it's sent to the top of the view

### ISSUE THREAD

**Issue by BrenoVin** [MessageKit/MessageKit#544]
When I add a subview (in viewDidAppear for exemple), my subview is sent to the top of the view, getting (y == 0), but I set a different number

I expect that my subview keeps in the position which I set it

**Comment by nathantannar4** [comment]
Hi @BrenoVin, please be more specific. To what view are you adding a subview?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BrenoVin** [comment]
I create a CustomView to show to the users the ConnectionState. And I add this view just
`view.addSubview(myView)`

the creation of the view is like
`UIView(frame: CGRect(x: 0, y: 30, width: 20, height: 20))`

and after I add it, I get a wrong position in my view (y ==0)

**Comment by SD10** [comment]
@BrenoVin Try using a constraint instead of frame?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BrenoVin** [comment]
ok! tks @SD10
