### ISSUE TITLE
Cannot set new constraints for new contents inside MessageContainerView

### ISSUE THREAD

**Issue by hcn1519** [MessageKit/MessageKit#545]
## General Information

* MessageKit Version:
0.13.1

* iOS Version(s):
11.2

* Swift Version:
4.0

* Devices/Simulators:
11.2

* Reproducible in ChatExample? (Yes/No):
Yes

##  What happened?
Cannot Set new constraints, when I want to put some more contents(UIlabel, UIImageView etc) inside `MessageContainerView`.

## What did you expect to happen?

`MessageContainerView` can have more contents, without calling constraint method `messageLabel.fillSuperview()`.

I made SubClass of `TextMessageCell`, and added some new labels inside of `MessageContainerView`. 
Since I had new labels, I should set new constraints. But the thing is, `TextMessageCell` called `setupConstraints()` from `setupSubviews()` like this.

```Swift
open override func setupSubviews() {
        super.setupSubviews()
        messageContainerView.addSubview(messageLabel)
        setupConstraints()
    }
open func setupConstraints() {
        messageLabel.fillSuperview()
    }
```
Because of this structure, I always should call `messageLabel.fillSuperview()`, even if I don't want to use that. Actually, because of `messageLabel.fillSuperview()`, I cannot set any new constraints.

## Suggestion

If `MessageKit`has plan to support contents adjustment inside `MessageContainerView`, I would suggest that calling `setupConstraints()` method from `MessageCollectionViewCell.init(frame: CGRect)` not from `TextMessageCell. setupSubviews()`.

```Swift
// MARK: MessageCollectionViewCell
open class MessageCollectionViewCell: UICollectionViewCell, CollectionViewReusable {
   override public init(frame: CGRect) {
        super.init(frame: frame)
        contentView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        setupSubviews()
        setupGestureRecognizers()
        setupConstraints()
    }
   open func setupConstraints() {
   }
}
```

```Swift
// MARK: TextMessageCell
open class TextMessageCell: MessageCollectionViewCell {
    open override func setupSubviews() {
        super.setupSubviews()
        messageContainerView.addSubview(messageLabel)
    }
    
    open override func setupConstraints() {
        messageLabel.fillSuperview()
    }
}
```

This will make `setupSubviews()` and `setupConstraints()` work independently, and users can override each methods without calling SuperClass's constraints if  they don't want to use.

Thank you for reading my issue.

**Comment by SD10** [comment]
@hcn1519 Thank you for submitting this issue. I'll look into it but you may have to do a bit of a hack to work around this for now. I think we set constraints in this way to resolve a bug we were facing 🤔

**Comment by hcn1519** [comment]
@SD10 Thank you for your quick response. I also agree that this change can cause unexpected issues.😓 Please let me know if MessageKit has discussion about this kind of issue. 
Anyway, Thank you for your great framework, I really like it. 😀

**Comment by SD10** [comment]
@hcn1519 In MessageKit 1.0.0-beta.1 you can override any of the methods responsible for laying our the cell's subviews. You can find them in the `MessageContentCell` class.

https://github.com/MessageKit/MessageKit/blob/69c5414c224a98891e14984e83228740e4339219/Sources/Views/Cells/MessageContentCell.swift#L173
