### ISSUE TITLE
Show Sticker Panel behind keyboard

### ISSUE THREAD

**Issue by maximality** [MessageKit/MessageKit#548]
## General Information

* MessageKit Version: 0.13.1

* iOS Version(s): Any

* Swift Version: 4

* Devices/Simulators: All

* Reproducible in ChatExample? (Yes/No): Yes

##  What happened?
I want to show the sticker panel behind the keyboard and keep InputBar at the same position (like with showed keyboard).
Can't find a straight way to do it.

## What did you expect to happen?
Show sticker panel behind the keyboard and keep InputBar at the same position (like in Telegram, Viber, Skype, etc.)
https://i.stack.imgur.com/Nu6KS.gif

**Comment by nathantannar4** [comment]
Isn't the sticker for panel just a keyboard? If you are asking of we have a specific view that mocks being a sticker panel sorry we don't have one

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by maximality** [comment]
It’s a custom view which i want to put behind a keyboard and have ability to hide/show default keyboard

**Comment by maximality** [comment]
I don’t need your panel, I have my own. I just don’t know how to put it where it is supposed to be (under InputBar)

**Comment by nathantannar4** [comment]
Put it in the bottomStackView 😀

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
@maximality Do what @nathantannar4 suggested or just set your own `inputAccessoryView` temporarily if that is what you are looking for

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by maximality** [comment]
Yes, thanks guys. It helped me a lot!
