### ISSUE TITLE
How to close keyboard without it reopening?

### ISSUE THREAD

**Issue by NiklasWilson** [MessageKit/MessageKit#549]
## Question

How does one close the keyboard? 

##  What happened?

Currently I use `view.endEditing(true)` but as soon as the messages view is reloaded the keyboard comes back...

## What did you expect to happen?

It to be gone until the input is clicked again.

**Comment by nathantannar4** [comment]
Call resignFirstResponder on the view controller itself

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NiklasWilson** [comment]
`self.resignFirstResponder()`
@nathantannar4 that made the entire input bar go away...

switching it to `self.messageInputBar.resignFirstResponder()` doesn't work either.
Maybe I misunderstood where you wanted that to be called

**Comment by nathantannar4** [comment]
I thought you wanted to close the keyboard so it was gone. If you just want it dismissed call resignFirstResponder on the InputTextView in the MessageInputBar

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NiklasWilson** [comment]
:) yes that worked perfectly!
