### ISSUE TITLE
New attributedText message does not display correct until scroll from visible->invisible->visible

### ISSUE THREAD

**Issue by rulai-yinqiang** [MessageKit/MessageKit#557]
I modified the demo code like this:
____________________

```swift
extension ConversationViewController: MessageInputBarDelegate {

    func messageInputBar(_ inputBar: MessageInputBar, didPressSendButtonWith text: String) {
        
        // Each NSTextAttachment that contains an image will count as one empty character in the text: String
        
        for component in inputBar.inputTextView.components {
            
            if let image = component as? UIImage {
                
                let imageMessage = MockMessage(image: image, sender: currentSender(), messageId: UUID().uuidString, date: Date())
                messageList.append(imageMessage)
                messagesCollectionView.insertSections([messageList.count - 1])
                
            } else if let text = component as? String {
                
                let attributedText = NSAttributedString(string: text, attributes: [.font: UIFont.systemFont(ofSize: 15), .foregroundColor: UIColor.blue])
                
                let msg9String = "Use .attributedText() to add bold, italic, colored text and more..."
                let msg9Text = NSString(string: msg9String)
                let msg9AttributedText = NSMutableAttributedString(string: String(msg9Text))
                
                msg9AttributedText.addAttribute(NSAttributedStringKey.font, value: UIFont.preferredFont(forTextStyle: .body), range: NSRange(location: 0, length: msg9Text.length))
                msg9AttributedText.addAttributes([NSAttributedStringKey.font: UIFont.monospacedDigitSystemFont(ofSize: UIFont.systemFontSize, weight: UIFont.Weight.bold)], range: msg9Text.range(of: ".attributedText()"))
                msg9AttributedText.addAttributes([NSAttributedStringKey.font: UIFont.boldSystemFont(ofSize: UIFont.systemFontSize)], range: msg9Text.range(of: "bold"))
                msg9AttributedText.addAttributes([NSAttributedStringKey.font: UIFont.italicSystemFont(ofSize: UIFont.systemFontSize)], range: msg9Text.range(of: "italic"))
                msg9AttributedText.addAttributes([NSAttributedStringKey.foregroundColor: UIColor.red], range: msg9Text.range(of: "colored"))
                
                
                let message = MockMessage(attributedText: msg9AttributedText, sender: currentSender(), messageId: UUID().uuidString, date: Date())
                messageList.append(message)
                messagesCollectionView.insertSections([messageList.count - 1])
            }
            
        }
        
        inputBar.inputTextView.text = String()
        messagesCollectionView.scrollToBottom()
    }

}
```
____________________

So whatever I send, it will send a new attributedText message.
You can see the new attributedText message will not display correct.

But after you scroll the colletionview up and down, it may display correct.
![1](https://user-images.githubusercontent.com/33405365/37152181-6923c86c-2313-11e8-92ed-79d9019e8595.png)

**Comment by SD10** [comment]
@rulai-yinqiang This could be a bug but I’m a little unsure. It’s happened before but I’m almost positive this is resolved in MessageKit. Does it occur in the example app without modifications?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rulai-yinqiang** [comment]
I think it is a refresh bug.

The example app will load a lot of example messages at same time, it displays good.

But when you add a new attributedText message, it will not display as wish.

I just modify the example code to add a new attributedText message, nothing else modified.

**Comment by SD10** [comment]
@rulai-yinqiang Are you still experiencing this?

**Comment by rulai-yinqiang** [comment]
@SD10 It is easy to reproduce the bug: Just add a new attributedText message when press the SendButton.

**Comment by ankitpolaris** [comment]
I am also experiencing similar bug. I have attributedText in the message itself. Instead of showing the time outside the bubble I am showing it inside the bubble. The time text is of different smaller font size as compare to the message text. But when you scroll down and up the font size of the attributed text changes. This is the code I am using : 

                let theMessages = msgText.withAttributes([
                    .textColor(.white),
                    .font(.systemFont(ofSize: 15.0))
                    
                    ])
                let theDates = "\n\n\(finalDate1)".withAttributes([
                    .textColor(.white),
                    .font(.boldSystemFont(ofSize: 11.0))
                    
                    ])
                let finalString = theMessages + theDates
                
                
                if (id == String(self.userEntity._idx)) {
                    self.userID = Int(id)!
                    let message = MockMessage(attributedText: finalString, sender: self.currentSender(), messageId: UUID().uuidString, date: Date())
                    self.messageList.append(message)
                    self.messagesCollectionView.insertSections([self.messageList.count - 1])
                }
