### ISSUE TITLE
Wrong message bubble size for custom detector attributes

### ISSUE THREAD

**Issue by thepoortom** [MessageKit/MessageKit#558]
## General Information

* MessageKit Version:
0.13.1

* iOS Version(s):
iOS 11.2.2

* Swift Version:
Swift 4

* Devices/Simulators:
iPhone 6, iPhone X

* Reproducible in ChatExample? (Yes/No):
Yes

##  What happened?

I'm trying to set bold font in detector attributes for URL, but message bubble size not paying attention to this change.
Here is example code to reproduce in ChatExample project:

```
func detectorAttributes(for detector: DetectorType, and message: MessageType, at indexPath: IndexPath) -> [NSAttributedStringKey : Any] {
	return boldAttributes()
}

func boldAttributes() -> [NSAttributedStringKey: Any] {
	return [
		NSAttributedStringKey.font: UIFont.boldSystemFont(ofSize: 16),
		NSAttributedStringKey.underlineStyle: NSUnderlineStyle.styleSingle.rawValue,
		NSAttributedStringKey.underlineColor: UIColor.darkText
	]
}
```

Default attributes:
![mk-bug1-good](https://user-images.githubusercontent.com/14262897/37312059-962cfff0-265a-11e8-9264-446d6cc0f658.png)

Attributes with bold font:
![mk-bug1-bad](https://user-images.githubusercontent.com/14262897/37312058-960ec300-265a-11e8-9990-636a056b84df.png)

## What did you expect to happen?

Message bubble size computed correctly.

**Comment by SD10** [comment]
@thepoortom This is a known limitation of MessageKit. The size of the cell has to be calculated up front for a collection view. So any changes to attributes after the layout of the collection view will cause this to happen. You have two ways to deal with this:
A) Don’t use attributes that modify text size
B) Use `MessageData.attributedText(NSAttributedString)` and handle applying your own attributes

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thepoortom** [comment]
@SD10 Thanks for quick response! Ok, this limitation wasn't obvious for me, I'll try option B in this case. Thanks again!

**Comment by AlexeyShevchenko** [comment]
@SD10 
Hey, 
Could you please clarify what do you mean by `MessageData.attributedText(NSAttributedString)`?
