### ISSUE TITLE
Crash with empty string in MessageData.attributedText

### ISSUE THREAD

**Issue by thepoortom** [MessageKit/MessageKit#559]
## General Information

* MessageKit Version:
0.13.1

* iOS Version(s):
iOS 11.2.2

* Swift Version:
Swift 4

* Devices/Simulators:
iPhone 6, iPhone X

* Reproducible in ChatExample? (Yes/No):
Yes

##  What happened?

If I set empty string (`""`) in `MessageData.attributedText`, app crashes with message:

> *** Terminating app due to uncaught exception 'NSRangeException', reason: 'NSRLEArray objectAtIndex:effectiveRange:: Out of bounds'

in `MessagesCollectionViewFlowLayout` at line 285:

`guard let font = text.attribute(.font, at: 0, effectiveRange: nil) as? UIFont else { return }
`

You can reproduce it in ChatExample project by modifying line 160 in `SampleData` like this:

`let attributedText = attributedString(with: "")`

## What did you expect to happen?

No crash.

**Comment by SD10** [comment]
I would accept a PR fixing the out of bounds error @thepoortom 😊

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thepoortom** [comment]
@SD10 Ok, I'll make it tomorrow when I test it on working project :)
