### ISSUE TITLE
cell attributedText is truncated to one line

### ISSUE THREAD

**Issue by omaralbeik** [MessageKit/MessageKit#56]
cell text is truncated to one line when setting `.attributedText`

![attrtextheight](https://user-images.githubusercontent.com/8127757/29192162-08bdc520-7e29-11e7-96cf-b78c90d64108.png)

**Comment by SD10** [comment]
I feel like that message container is a bit wider than it should be too. I'll look into this tonight.

**Comment by MacMeDan** [comment]
Also check out `Landscape` mode I was seeing issues with the first message in the example project also but it is not attributed text.

**Comment by SD10** [comment]
Yeah, this will be resolved in `v0.5.0`. I'm pretty sure I forgot to use `.round(.up)` on the container width which is causing the first message to get cutoff in landscape.

**Comment by SD10** [comment]
Addressed in #70
