### ISSUE TITLE
Download image

### ISSUE THREAD

**Issue by relaxsus** [MessageKit/MessageKit#560]
How correctly download pictures via the link and show them in the chat? I start to download the image and to display it in the "messageForItem" method, but it goes there several times and so the download happens the same number of times .... Can someone explain or even better show a piece of code, please?

**Comment by hcn1519** [comment]
@relaxsus So far, MessageKit does not support async image downloading. So I think you need to  download & cache all images first before drawing MessageCollectionView. I did this using escaping closure and property observer.

```Swift
class ViewController: MessagesViewController {

    var contentDownloadComplete = false {
        didSet {
            DispatchQueue.main.async {
                // 4. reload messageCollectionView.
                self.messageCollectionView.reloadData()
            }
        }
    }
    override func viewDidLoad() {
        super.viewDidLoad()
        getChat()
    }

    // Your Request
    func getChat() {
        APIManager.requestMessage(target: .getMessage(request: request), completionHandler: { (data) in

            // 1. ImageDownload First, I have ChatMediaDownloadManager and 
            ChatMediaDownloadManager.downloadImageFrom(chatList: data) {
                // 2. Update your dataSource
                strongSelf.dataSource.updateMessages(imageCache: ChatMediaDownloadManager.imageCache, messageList: data)

                // 3. property observer will occur.
                strongSelf.contentDownloadComplete = true
            }
        }
    }
}
```

 
1. Download and cache images. You can make some wrapper of `MessageType` to check whether each `Chat` has image.
2. Update your `dataSource` Now you can create Chat with images.
3. Fire property observer to reload view.
4. Reload MessageCollectionView.

**Comment by SD10** [comment]
@relaxsus You can use this method in MessageKit 1.0.0-beta.1 to download images async: https://github.com/MessageKit/MessageKit/blob/69c5414c224a98891e14984e83228740e4339219/Sources/Protocols/MessagesDisplayDelegate.swift#L85
