### ISSUE TITLE
The inputBar faded into containerView.

### ISSUE THREAD

**Issue by xiaowinner** [MessageKit/MessageKit#566]
## General Information

* MessageKit Version:
0.13.1
* iOS Version(s):
iOS 11
* Swift Version:
4.0
* Devices/Simulators:
Simulators iPhone 7
* Reproducible in ChatExample? (Yes/No):
Yes

##  What happened?
I just push a viewcontroller, the viewcontroller has a containerView, and containerView has a MessageViewController.

The inputBar faded into containerView.

## What did you expect to happen?

![image](https://github.com/xiaowinner/xiaowinner.github.io/blob/master/1521194306185.jpg?raw=true)

**Comment by SD10** [comment]
@xiaowinner You probably need to call `messageInputBar.becomeFirstResponder()`

**Comment by xiaowinner** [comment]
Thanks，I test add self.becomeFirstResponder() in the viewdidApper function, work out my question.
