### ISSUE TITLE
Display view in front of InputBar

### ISSUE THREAD

**Issue by Teglgaard** [MessageKit/MessageKit#567]
Hi and thanks for an awesome library.

I have an issue displaying a view in front of the chat and the inputbar at the same time. Does anybody know how this is done? The goal is to have a view at the foremost of the screen. 

Thanks

**Comment by Teglgaard** [comment]
If anyone is confused about what I mean then I am talking about the MessageInputBar.

The view is displayed in a UITextEffectsWindow which is the foremost window. I can't seem to put anything in front of it.

**Comment by SD10** [comment]
@Teglgaard The `MessageInputBar` is the `inputAccessoryView` of the view controller. So it's not a part of the `MessagesViewController`s view hierarchy. It's something that is pinned to the top of the keyboard (/window?).

**Comment by cwalo** [comment]
@Teglgaard Check out this issue: https://github.com/MessageKit/MessageKit/issues/620
I think it will help. Close this if it does!

**Comment by SD10** [comment]
@Teglgaard I'm going to close this for now. Feel free to reopen if you're still having trouble 👍
