### ISSUE TITLE
Hybrid multi-language message be seperated

### ISSUE THREAD

**Issue by mayulu** [MessageKit/MessageKit#569]
## General Information

* MessageKit Version:0.13.1

* iOS Version(s): 11.2

* Swift Version:4.0

* Devices/Simulators:iPhone6sPlus

* Reproducible in ChatExample? (Yes/No):Yes

##  What happened?
When new message contains hybrid multi-language like Chinese + English, for example，"你好Jane", the message will be seperated in two messages: "你好" and "Jane"

## What did you expect to happen?
The sent message should keep original one message.

**Comment by SD10** [comment]
cc @nathantannar4 is this because of the example app and how the `MessageInputBar` handles images? We should probably fix the example if that is the case. Everyone is making that mistake 😓

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
@zhongwuzw Are you sure this is a bug and not because of [this code](https://github.com/MessageKit/MessageKit/blob/49c0971a4c26df199d5f50ad8858749659998aa4/Example/Sources/ConversationViewController.swift#L453)?

**Comment by zhongwuzw** [comment]
@SD10 ,yep.It's a bug because of [wrong attributes enumeration](https://github.com/MessageKit/MessageKit/blob/master/Sources/Views/InputTextView.swift#L307-L326).
I'll fix it later.

**Comment by sami79031** [comment]
The same thing happened to me when I type a word followed by an emoji. This happens especially when I send a message for the first time.

**Comment by zhongwuzw** [comment]
@mayulu , @sami79031 We would fix it when #577 merged.
