### ISSUE TITLE
Top and bottom Label is not pinned to Message in Landscape

### ISSUE THREAD

**Issue by lzyraining** [MessageKit/MessageKit#57]
<img width="664" alt="screen shot 2017-08-10 at 2 32 54 pm" src="https://user-images.githubusercontent.com/14967062/29193122-dd7d902a-7dd8-11e7-9cc1-4e5e1eead8e9.png">

Setting the top and bottom label `topLabelPinnedUnderMessage = true`, while in landscape those labels are not pinned to message.

**Comment by SD10** [comment]
@lzyraining Thank you for moving the discussion forward on this. I was hoping to clean up the name for this property in `v0.4.0`. I think it would be better named: `topLabelBeginsUnderMessage`.

Originally, I wanted to keep the labels pinned under the message container. 
This poses two potential problems:
1. It becomes impossible to center the label inside of the cell
2. The edge case where the message label is very small, 1 letter maybe, causing the label to truncate.

I've just decided to leave this as is until I can find an appropriate solution.

EDIT: maybe `topLabelExtendsPastAvatar` is even better

**Comment by lzyraining** [comment]
@SD10 I didn't see the details about the implementations. But from what the code I found it was using textAlignment to get the label position. I would recommend a simple solution, make those labels xOffset and width same as message. Then we only need to do align the text to left or right.

**Comment by SD10** [comment]
This was renamed to `topLabelExtendsPastAvatar` and `bottomLabelExtendsPastAvatar` in `v0.4.0`.
@lzyraining I can't follow your recommendation because it will break the 2 points mentioned above.
