### ISSUE TITLE
Custom SwiftLint rule. Require everything to have an explicit access control modifier

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#576]
It would be nice to have a rule that requires an access control modifier on everything inside of `MessageKit/Sources`. Even if it defaults to `internal` I still want to mark this explicitly.

We already have a custom rule [here](https://github.com/MessageKit/MessageKit/blob/49c0971a4c26df199d5f50ad8858749659998aa4/.swiftlint.yml#L8).

**Comment by alexmomotiuk** [comment]
@SD10 SwiftLint has such as rules, but it is disable by default.
https://github.com/realm/SwiftLint/blob/master/Rules.md#explicit-acl
https://github.com/realm/SwiftLint/blob/master/Rules.md#explicit-top-level-acl

**Comment by SD10** [comment]
@ProgiiX Awesome, I think this is a change we should make after the next release

**Comment by SD10** [comment]
We have this setup on `development` already
