### ISSUE TITLE
How to set Avatar image async after download

### ISSUE THREAD

**Issue by aaasifrz9** [MessageKit/MessageKit#585]
Hi @SD10 ,

As per sample provided, I tried to set Avatar image after download but it takes time to download and cell got loaded. So avatar image is not set in avatar position. But when I again come back from other controller avatar images showing properly.
But I want to set avatar images async after loading cells.
How can I do that, please help. 
Thanks.

**Comment by SD10** [comment]
@aaasifrz9 You may want to check our #164 and see if that helps you. How you handle async images is pretty client specific. 

I'd recommend using the method: 
```Swift
func configureAvatarView(_ avatarView: AvatarView, for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView)
``` 

Just remember to make sure you're applying the image to the correct cell because cells are reused.

**Comment by aaasifrz9** [comment]
Thanks @SD10 . Got the point.
