### ISSUE TITLE
attributedText changes to default text while scrolling up and down

### ISSUE THREAD

**Issue by ankitpolaris** [MessageKit/MessageKit#591]
## General Information

* MessageKit Version: 0.13.1

* iOS Version(s): 11

* Swift Version: Swift 4

* Devices/Simulators: iPhone X

* Reproducible in ChatExample? (Yes/No): Did not try, but should be able to.

##  What happened?
I am experiencing a concern. I have attributedText in the message itself. Instead of showing the time outside the bubble I am showing it inside the bubble. The time text is of different smaller font size as compare to the message text. But when you scroll down and up the font size of the attributed text changes. This is the code I am using :

                let theMessages = msgText.withAttributes([
                    .textColor(.white),
                    .font(.systemFont(ofSize: 15.0))
                    
                    ])
                let theDates = "\n\n\(finalDate1)".withAttributes([
                    .textColor(.white),
                    .font(.boldSystemFont(ofSize: 11.0))
                    
                    ])
                let finalString = theMessages + theDates
                
                
                if (id == String(self.userEntity._idx)) {
                    self.userID = Int(id)!
                    let message = MockMessage(attributedText: finalString, sender: self.currentSender(), messageId: UUID().uuidString, date: Date())
                    self.messageList.append(message)
                    self.messagesCollectionView.insertSections([self.messageList.count - 1])
                }

## What did you expect to happen?

Whether I scroll up or down it should always keep the attributedText styling.

**Comment by SD10** [comment]
@ankitpolaris It would be awesome if you could try and debug this for me ❤️ 🙏

**Comment by ankitpolaris** [comment]
![simulator screen shot - iphone x 11 1 - 2018-03-27 at 18 34 37](https://user-images.githubusercontent.com/11402396/37969119-a2ac2c76-31ed-11e8-8d7c-80ad091611d4.png)
@SD10 : Hi Steven, I tried to debug it but couldn't locate the issue. Please see the screenshot, i am trying to display date inside the message box itself. While doing so, some of the messages are not showing the correct attributes. As you can see "1 week ago" is incorrectly formatted in some of the messages. I am using observeMessages() method to display the results from Firebase DB. 

Do you have any idea where i can possibly go wrong.

**Comment by acid2k1** [comment]
@SD10 I also would like if this could be fixed. I hope you can help @ankitpolaris on this and maybe you both can fix this as soon as :) Thank you again for keeping it open source.

**Comment by acid2k1** [comment]
I have spent two days trying to debug it but I ain't having any joy :(  Anyone else have any joy? #SOS

**Comment by SD10** [comment]
@acid2k1 @ankitpolaris are you setting the text color for your `.attributedText` message using the `textColor(for:at:in)` method of `MessagesDisplayDelegate`?

**Comment by SD10** [comment]
This will be fixed by #623 duplicate of #557
