### ISSUE TITLE
Remove CollectionViewReusable protocol

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#595]
I think we can remove this protocol that requires:

```Swift
class func reuseIdentifier() -> String { }
```

Instead we can switch to using `String(describing: SomeType.Type)`

Do you think this method is reliable enough @zhongwuzw? I'm using it on other projects without problem 🤔

**Comment by zhongwuzw** [comment]
@SD10 , It's ok. Maybe `String(describing: SomeType.self)`?
