### ISSUE TITLE
What is "kf"?

### ISSUE THREAD

**Issue by pineappman** [MessageKit/MessageKit#597]
## General Information

imageView.kf. ...
I dont know The "kf".
What is "kf"?

**Comment by Sherlouk** [comment]
Random guess, kingfisher? Do you or one of your dependencies have that library?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Yep, its Kingfisher.

**Comment by SD10** [comment]
Thanks for answering this one ☝️ Going to close it because MessageKit does not use Kingfisher

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
