### ISSUE TITLE
Set Photo Image

### ISSUE THREAD

**Issue by pineappman** [MessageKit/MessageKit#598]
I want to add photo with URL.
Does thisapp support  async download image message?

------
sometimes, array is out of index 
```swift
func messageForItem(at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> MessageType {
   return messageList[indexPath.section]
}
```

**Comment by devx00** [comment]
The development branch supports it but there is little documentation of it since its still in development. I wouldn't suggest using it unless you're comfortable with figuring it out yourself.

**Comment by SD10** [comment]
Working on it 🙇🙇 `development` branch _should_ be fine to use. Just no official release yet

**Comment by SD10** [comment]
@pineappman You can use this method in MessageKit 1.0.0-beta.1 to download images async: https://github.com/MessageKit/MessageKit/blob/69c5414c224a98891e14984e83228740e4339219/Sources/Protocols/MessagesDisplayDelegate.swift#L85
