### ISSUE TITLE
Remove explicit header and footer restriction

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#599]
The current API is actually restricting because we have an explicit `MessageHeaderView` and `MessageFooterView`. After #596 is merged we will have a `MessageReusableView` class. I'm going to suggest we just remove the explicit header / footer classes in favor of using the reusable view. 

I'm just not sure whether to put this in 1.0 or not. It's just adding to the pile of changes. Maybe better fit for next major version as its not extremely important.

**Comment by hyouuu** [comment]
I'd vote for 1.0 ;)

**Comment by SD10** [comment]
We can’t put many more changes in 1.0, it has enough 😥. The responsible thing to do is leave this out

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hyouuu** [comment]
Understood!

**Comment by SD10** [comment]
We're required to put this in 1.0 now due to other reasons
