### ISSUE TITLE
Slack communication.

### ISSUE THREAD

**Issue by MacMeDan** [MessageKit/MessageKit#6]
I have created a group `message-kit` in slack to help us be organized. 

I would love to keep this more of a "coordination" tool for people working on features together keep questions and help to `stackoverflow`

EDIT: Removed as not to cause confusion

Please let me know if you have any suggestions or concerns.

**Comment by SD10** [comment]
@MacMeDan I actually already created the messagekit slack :joy: 

That's why you weren't able to use the name. The reason why I haven't made this public is because I want to keep the discussion in the open for now. I'm open to discussing making the Slack public though 👍 

Let me send you an invite.

**Comment by SD10** [comment]
@MacMeDan I sent an invite to your email listed on GitHub
