### ISSUE TITLE
The trouble of display of cells

### ISSUE THREAD

**Issue by pineappman** [MessageKit/MessageKit#600]
when  i get cells, this trouble is caused every time.

Why?

Sorry for my foolish english (i'm japanese kids)

![img_2495](https://user-images.githubusercontent.com/36385526/38027372-60ebc28c-32ca-11e8-8a84-7aa166cc4f38.PNG)

( image example)

**Comment by SD10** [comment]
@pineappman こんにちは

Do not worry. Your English is better than my Japanese. I can still only say hello 😊 

You mean the problem is the size of the green bubble? Could you elaborate more if not?

**Comment by pineappman** [comment]
Hello!! ありがとうございます(thank you)
I can elaborate the problem more detail.

I use this MessageKit with remote database
So I try to set image in the message.

First of all, get messages from database with callback [HYMessage]

And, callback back to 
```
DispatchQueue(label: "hogehoge.queue").async {
            self.messageList = text
            DispatchQueue.main.async {
               self.messageList.sort(by: { $0.sentDate < $1.sentDate})
               DispatchQueue.main.asyncAfter(deadline: .now()+0.1, execute: {
                  self.messagesCollectionView.reloadData()
                  self.messagesCollectionView.scrollToBottom(animated: true)
               })
            }
         }
```
The messageList [HYMessage] (HYMessage is Inherited MessageType Class)
And messageList is used in below codes
```  
func messageForItem(at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> MessageType {
      return messageList.count
}
  func messageForItem(at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> MessageType {
      return messageList[indexPath.section]
   }
```

Below, the point where i try to setImage maskview with kingfisher.
```
  func messageStyle(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> MessageStyle {
```

I set image with kingfisher maskview.image.
Because I want to set image with async queue!

There is the problem after send or receive image

Could you please teach me?

**Comment by SD10** [comment]
@pineappman Can you take a look at [this comment](https://github.com/MessageKit/MessageKit/issues/421#issuecomment-353575398) regarding async images and Kingfisher and let me know if it helps? I actually haven't used Kingfisher before and I don't use `messageStyle` to set images async. I override `cellForItem(at: IndexPath)`. This will be easier in MessageKit 1.0

**Comment by pineappman** [comment]
Thank you for nice help.
I override below function
```
override func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
```
and set image with kingfisher
```
         guard let message = message as? HYMessage,let url = URL(string: message.path) else {fatalError()}
         let cell = messagesCollectionView.dequeueReusableCell(MediaMessageCell.self, for: indexPath)
         cell.configure(with: message, at: indexPath, and: messagesCollectionView)
         cell.imageView.kf.indicatorType = .activity
         cell.imageView.kf.setImage(with: url)
         return cell
```
then I was able to prevent choking.

However, sender cell moves to receiver cell.
I guess that it is related to auto layout

Could you please teach me?

![img_91c242c6f8af-1](https://user-images.githubusercontent.com/36385526/38065317-91acab84-333d-11e8-9cc7-e358db9e6ee1.jpeg)

**Comment by abdbinrus93** [comment]
I am having the same issue
