### ISSUE TITLE
How to add a view on top of the collectionViewController ? 

### ISSUE THREAD

**Issue by abdbinrus93** [MessageKit/MessageKit#604]
## General Information

* MessageKit Version:

* iOS Version(s):

* Swift Version:
Swift 4
* Devices/Simulators:
iPhone 5s 
* Reproducible in ChatExample? (Yes/No):
No

##  What happened?
I am trying to add a view on top of the collectionViewController. I tried to remake constraints. 
The question is where to add my view as a subview? Should I add it to collectionViewController.view ? Or collectionView itself. The same question was asked by another guy, and you told to add it as a subview to collectionView and change contentInset of collectionView. I tried this, the top of collectionView content is moved but the view is not appearing.

**Comment by SD10** [comment]
> The same question was asked by another guy, and you told to add it as a subview to collectionView and change contentInset of collectionView.

I would recommend making it a subview of the `MessagesViewController`.

**Comment by abdbinrus93** [comment]
I have tried to add it to MessagesViewController's view as a subview and remake the constraints of messagesCollectionView since I want it to appear just below the view I want to add, but the app crashes at that point. Could you please make it clear how to remake the constraints so that I have a view on top and messagesCollectionView will be below it?

**Comment by cwalo** [comment]
Appears to be a duplicate of https://github.com/MessageKit/MessageKit/issues/622
