### ISSUE TITLE
How to add a headerView to messagesCollectionView ?

### ISSUE THREAD

**Issue by abdbinrus93** [MessageKit/MessageKit#608]
## General Information

* MessageKit Version:

* iOS Version(s):

* Swift Version:

* Devices/Simulators:

* Reproducible in ChatExample? (Yes/No):

**Comment by SD10** [comment]
You can use the delegate method of [MessagesDisplayDelegate called messageHeaderView(for:at:in)](https://messagekit.github.io/Protocols/MessagesDisplayDelegate.html#/s:10MessageKit23MessagesDisplayDelegateP17messageHeaderViewAA0agH0CAA0A4Type_p3for_10Foundation9IndexPathV2atAA0c10CollectionH0C2intF)

**Comment by abdbinrus93** [comment]
could you show an example?
`override func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, referenceSizeForHeaderInSection section: Int) -> CGSize {
    if section == 0 {
      return CGSize(width: messagesCollectionView.bounds.width, height: 200)
    }
     return CGSize.zero
  }
  
  func headerViewSize(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> CGSize {
    if indexPath.section == 0 {
      return CGSize(width: messagesCollectionView.bounds.width, height: 200)
    } else {
      return CGSize.zero
    }
  }

func messageHeaderView(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> MessageHeaderView {
    if indexPath.section == 0 {
      let messageHeaderView = MessageHeaderView()
      messageHeaderView.backgroundColor = .red
      return messageHeaderView
    } else {
      let messageHeaderView = MessageHeaderView()
      messageHeaderView.backgroundColor = .green
      return messageHeaderView
    }
  }`

**Comment by abdbinrus93** [comment]
I can not anyhow find a solution to add a UIView on top of the collectionView so that it scrolls with the messages below it as well.
