### ISSUE TITLE
Crash issue when no message

### ISSUE THREAD

**Issue by superdev89** [MessageKit/MessageKit#61]
The sample app crashes when you sent empty message list.

I debugged into the code and found the issue in MessagesCollectionView.swift.

    var indexPathForLastItem: IndexPath? {

          let lastSection = numberOfSections > 0 ? numberOfSections - 1 : 0
          guard numberOfItems(inSection: lastSection) > 0 else { return nil }
          return IndexPath(item: numberOfItems(inSection: lastSection) - 1, section: lastSection)
    }

if numberOfSections is 0, the lastSection should not exist and return nil, but here retrieving section 0.

**Comment by SD10** [comment]
@superdev89 Thank you for reporting this! 🎉 
You can submit a PR to the `v0.5.0` branch if you'd like to fix this yourself.

**Comment by MacMeDan** [comment]
@superdev89 Let us know if you would like to fix it or we will open it up to anyone. Great job finding it. 💪😎👊 I am going to assign it to you for now.

**Comment by AndrewLauder** [comment]
I fixed this issue locally, should I open a PR?

**Comment by MacMeDan** [comment]
That would be great @AndrewLauder.
