### ISSUE TITLE
Segmentation fault: 11 on Xcode 9.3

### ISSUE THREAD

**Issue by AndriiPetrovDev** [MessageKit/MessageKit#613]
## General Information

* MessageKit Version:
latest master
* iOS Version(s):
11.3
* Swift Version:
4.1
* Devices/Simulators:
Any
* Reproducible in ChatExample? (Yes/No):
Yes

##  What happened?
Example doesn't want to compile
http://joxi.ru/E2pMpPju9ZB65A

## What did you expect to happen?
Example compiles

**Comment by zhongwuzw** [comment]
@AndrewPetrov , It's the `Swift Compiler` bug, you can set `Compilation Mode` to `Whole Module` like below or just set it in `framework`, that would fix this temporary, we'll think add a `PR` to fix `master`.
![image](https://user-images.githubusercontent.com/5061845/38169325-a91f7ffe-3599-11e8-865e-cd57cb5bb957.png)

**Comment by pastmos** [comment]
It works, thanks!

**Comment by exevil** [comment]
Hello!

Any news regarding this issue?
