### ISSUE TITLE
为何不支持 ios8

### ISSUE THREAD

**Issue by chunxige** [MessageKit/MessageKit#618]
哪些地方用到了ios9以后才有的方法

**Comment by SD10** [comment]
@chunxige 我们用 `UIStackView`

**Comment by hyouuu** [comment]
@SD10 中文这么屌！！

**Comment by SD10** [comment]
我喜欢

**Comment by rulai-yinqiang** [comment]
@SD10 不要告诉我你没有用 Google 翻译。呵呵

**Comment by SD10** [comment]
I did for reading. I've only been learning Chinese for 2 months. 我是学生 😃
