### ISSUE TITLE
Command failed due to signal: Segmentation fault: 11

### ISSUE THREAD

**Issue by KuDji** [MessageKit/MessageKit#619]
Load example and get error - Command failed due to signal: Segmentation fault: 11

**Comment by SD10** [comment]
@KuDji What MessageKit version, Xcode version, Swift version? Please post the error message

**Comment by KuDji** [comment]
xCode - 9.3, Swift - 4,1. MessageKit from project example version.

**Comment by SD10** [comment]
Please see #613 👍
