### ISSUE TITLE
MessageInputBar dismissed when an alert is presented

### ISSUE THREAD

**Issue by clayellis** [MessageKit/MessageKit#620]
## General Information

* MessageKit Version:
13.2

* iOS Version(s):
11.3

* Swift Version:
4.1

* Devices/Simulators:
Both

* Reproducible in ChatExample? (Yes/No):
Yes, if you add these lines to `handleTyping` (just using it as an injection point):

```swift
@objc func handleTyping() {
    let alert = UIAlertController(title: "Title", message: "Message", preferredStyle: .alert)
    alert.addAction(UIAlertAction(title: "Dismiss", style: .default, handler: nil))
    present(alert, animated: true, completion: nil)
    
    ...
}
```

##  What happened?

The `MessageInputBar` animates down offscreen when the alert is presented. It comes back after the alert is dismissed.

## What did you expect to happen?

The alert to be presented and the `MessageInputBar` to remain visible.

## My Question

This is happening because `messageInputBar` is the `inputAccessoryView` on `MessagesViewController` and is the correct behavior in UIKit.

My question is how do I prevent the `MessageInputBar` from disappearing when the alert is presented? I've tried overriding some of the first responder properties to prevent the input bar from being "dismissed" but nothing seems to be working quite yet. Is anyone aware of a solution?

**Comment by clayellis** [comment]
![example](https://user-images.githubusercontent.com/10712068/38338350-78331236-3826-11e8-81b4-8b682016a61d.gif)

**Comment by clayellis** [comment]
https://giphy.com/gifs/2t9oMHhOAX7E75sNny/html5

**Comment by clayellis** [comment]
![animated gif-source](https://user-images.githubusercontent.com/10712068/38338436-cf7c93be-3826-11e8-98a4-726976a38972.gif)

Hmm, the embedded gif isn't working. https://giphy.com/gifs/2t9oMHhOAX7E75sNny

**Comment by SD10** [comment]
@clayellis I'm not sure if this is possible. The `MessageInputBar` is the `inputAccessoryView` of the controller 🤔

**Comment by clayellis** [comment]
@SD10 right, which is why it isn't a "bug", it's supposed to work that way. I just don't know the fine details of what occurs in the first responder chain when a controller is presented from a controller who is currently the first responder. The closest I've come to achieving the behavior I'm looking for is calling `becomeFirstResponder` on the `MessagesViewController` in the presentation completion handler:

```swift
present(alert, animated: true, completion: { self.becomeFirstResponder() })
```

But things just get weird from that point. It isn't a good solution. 

Other things I've tried:
- Subclass `UIAlertController` and overriding `canBecomeFirstResponder` and returning `false`.
- Override `disablesAutomaticKeyboardDismissal` and return `false` in the `MessagesViewController`.

**Comment by clayellis** [comment]
This SO question doesn't have any answers, but leaving a link to it here just in case at some point in the future someone answers or has the same question: https://stackoverflow.com/questions/46996251/inputaccessoryview-animating-down-when-alertcontroller-actionsheet-presented

**Comment by cwalo** [comment]
The trick is to present the alert from the topmost window and viewcontroller.

```
let topViewController = UIApplication.shared.windows.last!.rootViewController!
topViewController.present(alert, animated: true, completion: nil)
```

You could also try creating a new UIWindow above the Keyboard by giving it a higher WindowLevel and present the alert there. I suspect that's what Messages is probably doing since the previous is a bit clunky.

![alert](https://user-images.githubusercontent.com/2067455/38346126-b735b042-3858-11e8-89b6-12ad5f2e081b.gif)

**Comment by clayellis** [comment]
@cwalo That'd do the trick! I was going to use another window as a last resort, but it does seem to be a pretty clean solution! Thanks a ton, I really appreciate it.
