### ISSUE TITLE
How to use phoneNumberAttributes in project swift 3 with library use swift 4?

### ISSUE THREAD

**Issue by anhnc55** [MessageKit/MessageKit#621]
## General Information

* MessageKit Version:

* iOS Version(s): 

* Swift Version: swift 3

* Devices/Simulators:

* Reproducible in ChatExample? (Yes/No):

##  What happened?
My project user swift 3 and I user Messagekit version 0.10.2 (swift 4). I can not use phoneNumberAttributes property? So what can I do?

**Comment by SD10** [comment]
@anhnc55 MessageKit does not support Swift 3. There is an issue #485 related to this
