### ISSUE TITLE
How to add a subview to the MessagesViewController so that MessagesViewController's view scrolls with collectionView ?

### ISSUE THREAD

**Issue by abdbinrus93** [MessageKit/MessageKit#622]
## General Information

* MessageKit Version:

* iOS Version(s):
11
* Swift Version:
swift 4
* Devices/Simulators:
iPhone 5s
* Reproducible in ChatExample? (Yes/No):

##  What happened?

I added a UIView to the MessagesViewController's view. And I changed the top constraint in setUpConstraints func of MessagesViewController.

## What did you expect to happen?
the collection view's top is now below, at the point I changed it to. But the view of MessagesViewController is not scrolling.

**Comment by cwalo** [comment]
@abdbinrus93 Can you post a screenshot?

**Comment by abdbinrus93** [comment]
I see two options:
1. Register a new custom CollectionViewCell and use it for indexPath with section 0
The problem, in this case, is that all delegates and data source are dependent on indexPath.section and I have to change them all
2. Add a scrollView to MessagesViewController's view and add my view on top and messagesCollectionView at the bottom of it adding both to the scrollView.  The problem here is that setUpSubviews is private func.

**Comment by donpironet** [comment]
I have the same problem. I would like to change the collectionViewConstraints because I would like to add a  view at the bottom. This would be possible if we could override setupConstraints.

**Comment by nathantannar4** [comment]
@donpironet the problem with allowing overrides or the MessagesCollectionView is that then the auto inset adjustment could be wrong. If you want a view above your messages you should try using a custom container and add MessagesViewController as a child VC. I have an example in the Example project in the `development` branch. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by donpironet** [comment]
Thanks. I also fixed it like that yesterday. I will definitely check out your example!
