### ISSUE TITLE
Change Sender from struct to protocol

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#628]
I'm thinking that the `Sender` type is better suited as a protocol. It's common that people want to make an existing user object such as `FIRUser` or `PFUser` conform to `Sender`.

This is out of scope for 1.0 but good to keep track of.

**Comment by nathantannar4** [comment]
😝 I remember mentioning this, I'll tackle it once 1.0 is launched

**Comment by nathantannar4** [comment]
@SD10 Lets address this for a 2.0 change. Im thinking make a new protocol `SenderType` and then we can keep the struct `Sender` for backwards compatibility?

**Comment by nathantannar4** [comment]
Pushing back to a later release

**Comment by kinoroy** [comment]
Since 3.0.0 is released, I'm closing this.
