### ISSUE TITLE
Question: Resize custom cell based on subviews?

### ISSUE THREAD

**Issue by Luke47** [MessageKit/MessageKit#634]
## General Information

* MessageKit Version: 0.13.1

* iOS Version(s): 11.3

* Swift Version: 4.1

I use a subclass of `MessageCollectionViewCell` to display a custom cell with one direct subview, a LinkPreviewView, which contains several UI elements as subviews based on the content I want to show.

The LinkPreviewView builds its layout in the `configure` function of the custom cell and can have a variable height based on its content. However `messageContainerSize(for message: MessageType, at indexPath: IndexPath) -> CGSize` expects me to specify a size, which I do not know at this point.

What would be a proper way of handling this? There is no way the message container view gets resized based on its content, right? So I would need to calculate the final height already in `messageContainerSize(for message: MessageType, at indexPath: IndexPath) -> CGSize`. 

Which means I need to build the layout of the LinkPreviewView already in `messageContainerSize(for message: MessageType, at indexPath: IndexPath) -> CGSize` to get the final height. And then I need to build it a second time in the `configure` function of the custom cell to actually add it as a subview to the cell? Or alternatively, and maybe the better option, come up with a reliable way of calculating the expected height of the LinkPreviewView (which can be rather complex).

Or is there any better way I have overlooked?

**Comment by cwalo** [comment]
Hey @Luke47. I've actually dealt with this myself. For the time being, I've leaned toward a statically sized (in 1.0 this is set when creating the MediaItem for MessageData) "LinkPreviewView" consisting of a UIStackView that hides/shows the necessary elements. When I was doing the unfurling client-side, I would try reloading the relevant section _from_ the cell, but that gets a little hairy, especially if the unfurl completes after the cell has gone off screen - much to manage there. If you can offload the unfurling to be a server-side thing, it becomes quite a bit easier. For example, our API now delivers a `Media` payload on Message objects:

```
public class Media: Object, Mappable {
    @objc public dynamic var type: String? // the media type
    @objc public dynamic var name: String? // the site's name
    @objc public dynamic var serviceURL: String? // the site's URL
    @objc public dynamic var titleURL: String? // the full URL
    @objc public dynamic var url: String? // the actual URL used in the message
    @objc public dynamic var iconURL: String? // the favicon
    @objc public dynamic var title: String? // the page/media title
    @objc public dynamic var subtitle: String? // a description
    @objc public dynamic var imageURL: String? // the image URL
    public let imageWidth = RealmOptional<Int>()
    public let imageHeight = RealmOptional<Int>()
    @objc public dynamic var videoURL: String? // the video URL
    public let videoWidth = RealmOptional<Int>()
    public let videoHeight = RealmOptional<Int>()
...
```
You may not have this luxury, but then if an optional element exists, we can size more appropriately. For instance, if I see the `type` is an "image" or "gif", I'll make it a 200x200 square. If it's a "website", I'll return 200x120.

Thinking of any other advice I can offer...

**Comment by Luke47** [comment]
Thanks for your answer! The unfurling is indeed a server-side thing. But our link previews can be quite complex regarding the information they contain (e.g. including meta data fields, multiple textviews, etc.) so I can't just check the type and return a fixed size (they have a min and max size though).

But your solution with the UIStackView seems great. I will look into it and probably rewrite the view to use a full programmatic approach and to have some function `expectedContentHeight` which should be able to calculate the expected heights based on the shown content. So far, link previews are the bottle neck performance wise. So it is time for a rewrite anyway.

**Comment by cwalo** [comment]
I can empathize!
