### ISSUE TITLE
How to hide MessageDateHeaderView ?

### ISSUE THREAD

**Issue by abdbinrus93** [MessageKit/MessageKit#642]
## General Information

* MessageKit Version:

* iOS Version(s):

* Swift Version:

* Devices/Simulators:

* Reproducible in ChatExample? (Yes/No):

**Comment by BasThomas** [comment]
Hey @abdbinrus93, were you able to resolve your issue? If so, can you let us know what solved it? That might help future users stumbling upon the same issue.

**Comment by jdriselvato** [comment]
I'd also like to have this feature.

**Comment by jdriselvato** [comment]
Figured it out:

> By default, messageHeaderView uses the method shouldDisplayHeader(for:_:_) of MessagesDisplayDelegate to determine if it should return a MessageHeaderView subclass called MessageDateHeaderView or nil. The shouldDisplayHeader(for:_:_) method checks the showsDateHeaderAfterTimeInterval property of MessagesCollectionView and returns true if the the last message was sent after the specified time interval. The default value of this TimeInterval is 1 hour.

```
    func shouldDisplayHeader(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> Bool {
        return false
    }
```
