### ISSUE TITLE
How to change cellBottomLabel constraints or frame ?

### ISSUE THREAD

**Issue by abdbinrus93** [MessageKit/MessageKit#643]
## General Information

* MessageKit Version:

* iOS Version(s):

* Swift Version:

* Devices/Simulators:

* Reproducible in ChatExample? (Yes/No):

##  What happened?

I want to show the sendDate of the message in 02-01-2017 13:58 format
The bottom label shows the date properly
The problem is some cells do not show the date String fully.
How to change the frame ?

**Comment by BasThomas** [comment]
Hey @abdbinrus93, can you give some more information? Check the `General Information` in the issue template.

Also, can you share the part of your code with which you are experiencing this issue?

**Comment by SD10** [comment]
@abdbinrus93 You don't really have much control over this in the current version of MessageKit. It would require internal manipulation of the library. It is possible in the upcoming version though.

**Comment by SD10** [comment]
@abdbinrus93 You can achieve this by overriding `cellBottomLabel` in MessageKit 1.0.0-beta.1. There may be a high cost of upgrading given the breaking changes though. Thank you 👍
