### ISSUE TITLE
Current Status?

### ISSUE THREAD

**Issue by wdcurry** [MessageKit/MessageKit#644]
Sorry if this is too generic to ask here, but: i am considering an rewrite of an obj-c app that is Obj-c and uses JSQ. I am wondering as to the state of this library. I don't tax JSQ very hard, and would like to take this one on, and perhaps help out once i get my feet wet here.

Is it still too raw for production?

**Comment by SD10** [comment]
@wdcurry It's being used in production already. I wouldn't suggest getting into the project at this point in time because we're preparing for a huge API breaking release. No time frame set on the release, sorry 😢

**Comment by wdcurry** [comment]
Thank you kindly. I may just plow ahead regardless, as i don't tax things too much, given my experience with JSQ, it is likely my path of least resistance, given it is in production elsewhere.

**Comment by SD10** [comment]
@wdcurry I just released MessageKit 1.0.0-beta.1 so I'm going to close this. Thank you 👍
