### ISSUE TITLE
how to hide and show only cell's toplabel when tapped on cell 

### ISSUE THREAD

**Issue by amraamandal** [MessageKit/MessageKit#648]
## General Information

* MessageKit Version:

* iOS Version(s):

* Swift Version:

* Devices/Simulators:

* Reproducible in ChatExample? (Yes/No):

**Comment by BasThomas** [comment]
Hey @amraamandal, can you provide some general information and maybe share the part of your code that does not work as expected?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
We have to get rid of this issue template. This is horrible 🙄

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by amraamandal** [comment]
hi @BasThomas it is part of my code 
![screen shot 2018-04-13 at 8 52 45 am](https://user-images.githubusercontent.com/35094072/38711468-6f35ec48-3ef8-11e8-87ca-930b37031c92.png)

![screen shot 2018-04-13 at 8 52 17 am](https://user-images.githubusercontent.com/35094072/38711431-39a299f0-3ef8-11e8-95a2-b4a13644678b.png)

it works but not right. i have reloaded  only tapped cell but all cell's label inset loaded
when not tapped
![screen shot 2018-04-12 at 8 24 57 pm](https://user-images.githubusercontent.com/35094072/38711615-51329506-3ef9-11e8-8c5f-d0d56d1a5da5.png)

when tapped
![screen shot 2018-04-12 at 8 25 04 pm](https://user-images.githubusercontent.com/35094072/38711624-5a7ad6b4-3ef9-11e8-978d-a1ff6aded295.png)

**Comment by jbouaziz** [comment]
@amraamandal you’d probably need to associate your click bool to the index path it’s related to. From what I can see in your code, my guess is that scrolling will display the time for all the dequeued items.

**Comment by SD10** [comment]
Going to close this one. Feel free to reopen if you're still stuck @amraamandal. Thank you 👍
