### ISSUE TITLE
Setting placeholder for inputTextView does not work as expected

### ISSUE THREAD

**Issue by Luke47** [MessageKit/MessageKit#650]
## General Information

* MessageKit Version: 0.13.1

* iOS Version(s): 11.3

* Swift Version: 4.1

* Devices/Simulators: iPhone X

* Reproducible in ChatExample? (Yes/No): n.a.

##  What happened?

Using `messageInputBar.inputTextView.placeholder` to set a custom placeholder leads to display of the default placeholder AND the custom one.

Using `messageInputBar.inputTextView.placeholderLabel.text` to change the placeholder works.

## What did you expect to happen?

`messageInputBar.inputTextView.placeholder` should properly enable setting a custom placeholder

**Comment by SD10** [comment]
@Luke47 Unfortunately, I don't have the time to investigate this issue. My only thought is that possibly this `didSet` needs to become a `get` and `set` to set and retrieve the value from the `placeholderLabel`. Care to dig deeper for me?

https://github.com/MessageKit/MessageKit/blob/c52d6e42fde9aa0451a3487d354920bece296689/Sources/Views/InputTextView.swift#L77

**Comment by BasThomas** [comment]
I'll check this is you can't, @Luke47. Also happy to help!

**Comment by Luke47** [comment]
Never mind, it was my fault. I should have tried to fix the compiler errors in the demo project to test it there. The issue is not with MessageKit itself. Some other library in our project provides an extension for `UITextView` which too applies a placeholder.

Sorry for the trouble, I will close this issue :)
