### ISSUE TITLE
Improve the GitHub issue template

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#653]
[Moya has a good example of something more lightweight](https://raw.githubusercontent.com/Moya/Moya/master/.github/Issue_template.md). I think it would be good to still mention some things that are useful to provide like MessageKit version, etc. But the entire template should be a comment. I don't want to see a bunch of empty fields when users don't fill out the proper information.

**Comment by BasThomas** [comment]
I'll whip up a pull request soon!

**Comment by BasThomas** [comment]
Soon™
