### ISSUE TITLE
Styling: Improvement of default values for messageInputBar styling

### ISSUE THREAD

**Issue by Luke47** [MessageKit/MessageKit#655]
So, this has a really low priority, but I will just drop it here as it might be an improvement.

I've noticed that the default value of the `borderWidth` of the `inputTextView` is set to 1.25 and the default height of the top `separatorLine` for the `messageInputBar` is set to 1.0.

I guess the goal here is to get lines that actually look like 1 pt lines. However, the current approach does not really work because it will look like more than 1 pt depending on screen scaling. One way of getting accurate lines would be to divide by the current's device screen scaling, e.g. `inputTextView.layer.borderWidth = 1.25 / UIScreen.main.scale`

It probably makes sense to update this to provide more sensible defaults for an up to date iOS look and also the example app would look much nicer in my opinion.

Below some examples taken on an iPhone X with a scale factor of @3x

If it is something you care about please let me know and I can prepare a pull request

Current:
![pic2](https://user-images.githubusercontent.com/5190003/38732451-78fd91a6-3f1e-11e8-890b-1430c5cf2fcb.jpg)

New:
![pic1](https://user-images.githubusercontent.com/5190003/38732454-7b36712c-3f1e-11e8-8a9b-638e793a59e2.jpg)

**Comment by SD10** [comment]
@Luke47 Yeah I think we could improve the default styling of MessageKit in general. Feel free to open a PR and the team can review it
