### ISSUE TITLE
Some Warning about running Demo.

### ISSUE THREAD

**Issue by KC-218** [MessageKit/MessageKit#660]
## General Information

* MessageKit Version: 0.13.4

* iOS Version(s): 11

* Swift Version: 4

* Devices/Simulators: Simulators iPhone8

* Reproducible in ChatExample? (Yes/No): Yes

##  What happened?

I run the demo and print some warning about layout.

API error: <_UIKBCompatInputView: 0x7f882c5114b0; frame = (0 0; 0 0); layer = <CALayer: 0x604000221be0>> returned 0 width, assuming UIViewNoIntrinsicMetric

[View] First responder warning: '<MessageKit.InputTextView: 0x7faca8835a00; baseClass = UITextView; frame = (0 0; 291 30); text = ''; clipsToBounds = YES; gestureRecognizers = <NSArray: 0x6040000579d0>; layer = <CALayer: 0x6040000328a0>; contentOffset: {0, 0}; contentSize: {122, 28.5}; adjustedContentInset: {0, 0, 0, 0}>' rejected resignFirstResponder when being removed from hierarchy

-[UIWindow endDisablingInterfaceAutorotationAnimated:] called on <UITextEffectsWindow: 0x7faca4833a00; frame = (0 0; 375 667); opaque = NO; autoresize = W+H; layer = <UIWindowLayer: 0x6000000345e0>> without matching -beginDisablingInterfaceAutorotation. Ignoring.

<img width="1401" alt="2018-04-18 11 22 41" src="https://user-images.githubusercontent.com/19691907/38910287-32a4c216-42fb-11e8-8a24-144aeb9b783e.png">

## What did you expect to happen?

How to fix this warning?

**Comment by zhongwuzw** [comment]
Some is system log, one is `resignFirstResponder` warning, it's because we resign in the `Example` project, you can ignore these warnings.

**Comment by SD10** [comment]
Going to close this one 👍
