### ISSUE TITLE
Keyboard bottom space 

### ISSUE THREAD

**Issue by ToqeerAhmad** [MessageKit/MessageKit#662]
## General Information

* MessageKit Version:
(0.13.4)
* iOS Version(s):
11.3
* Swift Version:
Latest
* Devices/Simulators:
All
* Reproducible in ChatExample? (Yes/No):

Yes

##  What happened?
when this property Dismiss keyboard On drag  gets called, keyboard gets hide and the Inputbar doesn't stick at bottom.
![imag](https://user-images.githubusercontent.com/10810397/39140539-53007f22-473e-11e8-8a0c-9fae18e2637d.jpg)

## What did you expect to happen?
On dragging  collectionview when keyboard hides, Input bar should stick at bottom.

**Comment by SD10** [comment]
@ToqeerAhmad Thanks for reporting this. Duplicate of #503 so going to close this one
