### ISSUE TITLE
MessageLabel touch handling is calculating touch point offset incorrectly

### ISSUE THREAD

**Issue by austinwright** [MessageKit/MessageKit#663]
## General Information
👻
* Issue Overview:
> See `MessageLabel.stringIndex(at location: CGPoint) -> Int?`
> Line: 357
> This code: `let textOffset = CGPoint(x: textInsets.left, y: textInsets.right)`
> `textInsets.right` should probably be `textInsets.top`
> 
> https://github.com/MessageKit/MessageKit/blob/b1314ec5ba79d695c82c038896b0960bf3ab5481/Sources/Views/MessageLabel.swift#L357

* MessageKit Version: 
> v0.13.4 (both the master & development branches)

* iOS Version(s):
> 11.0 and up

* Swift Version:
>4.0

* Devices/Simulators:
> All

* Reproducible in ChatExample? (Yes/No):
> Probably?

##  What happened?
MessageLabel touch location offset calculation appears to be incorrect.

## What did you expect to happen?
Offset should be calculated correctly.

**Comment by SD10** [comment]
@austinwright Yeah good catch, looks like this logic is wrong. Think you can submit a PR removing the point altogether? Then just use `textInsets` to offset the location directly on the line below?

Please submit this patch to `master` as it is a bug fix

**Comment by austinwright** [comment]
I'll take care of this this afternoon, thanks.
