### ISSUE TITLE
Contributing a New Logo

### ISSUE THREAD

**Issue by artjeck** [MessageKit/MessageKit#669]
Hi developers!
I am a graphic designer, I want to contribute to make a logo on your project, before I start it, I have to ask your permission first 😃
Best Regards, @artjeck

**Comment by SD10** [comment]
Hey @artjeck, 
I'm not sure if we need a new logo 🤔 I'm very fond of the existing organization logo as well. Did you have something specific in mind?

**Comment by artjeck** [comment]
yes sir, i have some logo updates for this app that can make this app more interesting

**Comment by SD10** [comment]
Hey @artjeck,
Thank you for wanting to make a contribution to MessageKit 😊 I'm not really open to changing the organization logo. If you have suggestions for a new README banner, that's something I'd consider, but I don't see any problems with it as is, so there's no guarantee we'd accept it 😢

**Comment by artjeck** [comment]
Hehe no problem sir, by the way what is this banner that you mean?
![gambar](https://user-images.githubusercontent.com/38141262/39631154-a1fe591e-4fdb-11e8-8f5f-f9612680c064.png)

**Comment by BasThomas** [comment]
That is the README banner, yes.

**Comment by artjeck** [comment]
Means I will design a banner just now, how do you think sir?
