### ISSUE TITLE
Line feed is inappropriate handled in text message.

### ISSUE THREAD

**Issue by lzyraining** [MessageKit/MessageKit#67]
- Text message width was not calculated correctly when text is followed by line feed.
<img width="308" alt="screen shot 2017-08-14 at 5 19 26 pm" src="https://user-images.githubusercontent.com/14967062/29297282-c0d0fc5c-8114-11e7-9cda-5b0dc46a4c80.png">
<img width="312" alt="screen shot 2017-08-14 at 5 21 06 pm" src="https://user-images.githubusercontent.com/14967062/29297323-0a3511f8-8115-11e7-9867-a0c804ca5ca6.png">

- Text message with only line feeds can not be sent.
<img width="309" alt="screen shot 2017-08-14 at 5 19 51 pm" src="https://user-images.githubusercontent.com/14967062/29297294-d04b603c-8114-11e7-8225-fb5f7d8f3460.png">

**Comment by SD10** [comment]
@lzyraining There's a slight error in the width calculation that I'm aware of and going to take care of. I'll try and fix this tonight.

As for the last point: "Text message with only line feeds can not be sent."

This is intended behavior. You're not allowed to send empty messages. I think most people building messaging features want this behavior so we will keep it as a default.

**Comment by SD10** [comment]
@lzyraining Can you check if this is still an issue on the `v0.5.0` branch? I made some changes and can't reproduce it. You're good at breaking my code though 😄 💯

**Comment by lzyraining** [comment]
Fixed, can not reproduce as well.
