### ISSUE TITLE
Remove Avatar view for outcoming message and remove date

### ISSUE THREAD

**Issue by ljs19923** [MessageKit/MessageKit#676]
Hi! I want to remove avatar view for outcoming message and i want to personalize each date under cells or remove it because its too much.
How can i do this ?

**Comment by SD10** [comment]
@JulienLevallois About the `AvatarView` please check out https://github.com/MessageKit/MessageKit/blob/master/Documentation/FAQs.md

For modifying one of the cell's labels you can set a different text in one of the `MessagesDataSource` methods:

```swift

func cellTopLabelAttributedText(for message: MessageType, at indexPath: IndexPath) -> NSAttributedString?
    
func messageTopLabelAttributedText(for message: MessageType, at indexPath: IndexPath) -> NSAttributedString?

func messageBottomLabelAttributedText(for message: MessageType, at indexPath: IndexPath) -> NSAttributedString?
```

**Comment by ljs19923** [comment]
![image](https://user-images.githubusercontent.com/5727223/39673788-ca5de880-5110-11e8-9da2-c7a6514b78da.png)

**Comment by ljs19923** [comment]
And also i wanted to know, whats the frequence of the date in the middle of the screen ? Each new hour ?

**Comment by adri4silva** [comment]
@JulienLevallois You must use the last release "1.0.0-beta.1"
