### ISSUE TITLE
When i send a new message, the text color in cell is different

### ISSUE THREAD

**Issue by ljs19923** [MessageKit/MessageKit#678]
When i send a new message, the text color in cell is different and the outgoingAvatarSize = .zero didn't works
![image](https://user-images.githubusercontent.com/5727223/39713817-1c93f6ae-51f6-11e8-9f62-764f915029df.png)

**Comment by ljs19923** [comment]
![image](https://user-images.githubusercontent.com/5727223/39713902-5c8070da-51f6-11e8-8be7-c263017e5f8a.png)

**Comment by SD10** [comment]
Each case of the `MessageKind` enum has its own `CellSizeCalculator` object as a property of the `MessagesCollectionViewFlowLayout`. You're likely not setting the proper `AvatarSize` for the `attributedTextMessageSizeCalculator`. 

Also, if you're sending a message with a `MessageKind.attributedText(NSAttributedString)` then this is where we will get the styling attributes from for that particular message.

**Comment by ljs19923** [comment]
Okay i found for color.
But What i need to do for the avatar size ?
I put in my viewdidload : 
  
        if let layout = messagesCollectionView.collectionViewLayout as? MessagesCollectionViewFlowLayout {
            layout.textMessageSizeCalculator.outgoingAvatarSize = .zero
        }

And this like your example : 

  
                let message = MockMessage(attributedText: attributedText, sender: currentSender(), messageId: UUID().uuidString, date: Date())
                messageList.append(message)
                objects.append(mess)

                messagesCollectionView.insertSections([messageList.count - 1])

**Comment by ljs19923** [comment]
Done, thanks i found

**Comment by SD10** [comment]
Glad you resolved this one 👍
