### ISSUE TITLE
Suggestions for improvement : Reduce Space between cells ( same user )

### ISSUE THREAD

**Issue by ljs19923** [MessageKit/MessageKit#679]
Hi ! Thanks for MessageKit, its perfect but i would like reduce the space betweens cells when messages are send from the same user, like messenger. Do you think its easy to implement that ?
Thanks
![image](https://user-images.githubusercontent.com/5727223/39715873-a5d35b2a-51fc-11e8-8075-9e5f15077f2e.png)
![image](https://user-images.githubusercontent.com/5727223/39715876-a801d85e-51fc-11e8-9dea-c507ac71215f.png)

**Comment by SD10** [comment]
@JulienLevallois You have to do this customization yourself by:
- Setting the avatar to hidden if its in a stack of messages from same user
- Removing the accessory labels by returning a text of `nil`
- Modifying the collectionview layout's section insets

**Comment by jabwd** [comment]
A very easy way of implementing this is by introducing a "peak" in your viewController subclass.
- peak one message ahead, making sure you don't go above the index range of your data collection
- compare the message you are handling with the peaked and determine whether the message you are handling should display: bottom label, avatar, what not
