### ISSUE TITLE
Remove collectionview scrolling during pop/pushviewcontroller

### ISSUE THREAD

**Issue by ljs19923** [MessageKit/MessageKit#681]
Hi ! I want to remove the automatic scrolling when i push/pop the converstion viewcontroller.

 messagesCollectionView.contentInsetAdjustmentBehavior = .never seems to don't works..

Do you know why ?

**Comment by Kishimotovn** [comment]
Anyone having the same problem? contentInsetAdjustmentBehavior doesn't work :(

**Comment by nathantannar4** [comment]
Is your navigation bar translucent? Set it to not be translucent

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by robertcapsure** [comment]
when presenting a view controller

viewController.modalPresentationStyle = .overFullScreen

fixes it for me

**Comment by robertcapsure** [comment]
also try this the closest i've gotten to an actual hack

    var contentOffset = CGPoint.zero  
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        contentOffset = messagesCollectionView.contentOffset
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        if let navigationBarRect = self.navigationController?.navigationBar.frame {
            let top = navigationBarRect.size.height + navigationBarRect.origin.y
            self.messagesCollectionView.contentInset = UIEdgeInsets(top: 0, left: 0, bottom: top, right: 0)
            self.messagesCollectionView.scrollIndicatorInsets = UIEdgeInsets(top: 0, left: 0, bottom: top, right: 0)
            contentOffset.y += top
            messagesCollectionView.contentOffset = contentOffset
        }
    }
