### ISSUE TITLE
[Question] Grouping Messages

### ISSUE THREAD

**Issue by adri4silva** [MessageKit/MessageKit#683]
Is there any property or any way to verify that the lasts sent messages are from the same user?. For example, I want to only display the name of a user at the first sent message of that "group" of messages or to only display the bubble tail on the last message of the "group". I would like to almost replicate the behaviour of iMessage. Thank you!
![photo-2018-05-14-09-52-14](https://user-images.githubusercontent.com/14318028/39984789-9f6b030e-575c-11e8-9b97-bd45f20393ea.jpg)

**Comment by SD10** [comment]
@adri4silva you can use `isFromCurrentSender(message:)` of `MessagesDataSource`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
In an older (possible outdated branch) I did just that with the `GroupMessageDataSource`. You could follow with similar logic

https://github.com/MessageKit/MessageKit/commit/31480f28c08fcc8ea3a49e517d6738fbe1db4449#diff-81bad7f501caa7649f9acc2880b07456

**Comment by adri4silva** [comment]
Thanks @nathantannar4, that's what I was looking for 👍🏽

**Comment by BasThomas** [comment]
Closing this out then, feel free to reopen if you have any more questions!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
