### ISSUE TITLE
cannot run messagekit

### ISSUE THREAD

**Issue by soufelhanafi** [MessageKit/MessageKit#684]
## General Information

* MessageKit Version:

* iOS Version(s):
11.3
* Swift Version:
4.1
* Devices/Simulators:
iphone 6

##  What happened?

After  run the project i get this error message:
Swift compile error: 
Showing Recent Messages
Command failed due to signal: Segmentation fault: 11

1.	While emitting SIL for 'configure(attributes:)' at /Users/soufianelhanafi/Chat_app/github/MessageKit/Example/Pods/MessageKit/Sources/Layout/MessagesCollectionViewFlowLayout.swift:267:13
2.	While silgen emitFunction SIL function "@_T010MessageKit32MessagesCollectionViewFlowLayoutC9configure33_9C0375F378B84B8117E47AE44A345C08LLyAA0cdeG10AttributesC10attributes_tF".
 for 'configure(attributes:)' at /Users/soufianelhanafi/Chat_app/github/MessageKit/Example/Pods/MessageKit/Sources/Layout/MessagesCollectionViewFlowLayout.swift:267:13

**Comment by SD10** [comment]
@soufelhanafi Can you please provide your Xcode version and MessageKit version?

Please check #613

**Comment by soufelhanafi** [comment]
@SD10 
Xcode version: 9.3 (9E145)
MessageKit version:0.13.5

**Comment by SD10** [comment]
Cool, so this is a duplicate of #613. Please see the solution there

**Comment by soufelhanafi** [comment]
still the same issue, 
![capture-20180514-143655](https://user-images.githubusercontent.com/32456103/40004077-6cca0a62-5784-11e8-829d-67cee4df30aa.png)
