### ISSUE TITLE
avatarPosition(for:at:in:) MessagesLayoutDelegate method does not called

### ISSUE THREAD

**Issue by tamastimar** [MessageKit/MessageKit#687]
## General Information

* MessageKit Version:
1.0.0-beta.1
* iOS Version(s):
iOS 11.3
* Swift Version:
Swift 4.1
* Devices/Simulators:
iPhone 8 Simulator with iOS 11.3
* Reproducible in ChatExample? (Yes/No):
Yes

##  What happened?
avatarPosition(for:at:in:) method of MessagesLayoutDelegate does not called.

## What did you expect to happen?
I can use that method to specify the position of avatars.

**Comment by SD10** [comment]
@tamastimar This is deprecated in the latest version. Isn't there a warning message? Please use the `MessageSizeCalculator` objects to size a message. You can find them as properties of `MessagesCollectionViewFlowLayout`.

**Comment by tamastimar** [comment]
@SD10 Indeed, it's not available anymore.

The API reference tricked me. Somehow I thought that shows the state of 1.0. My bad.

**Comment by SD10** [comment]
@tamastimar You're correct, this is my fault. I forgot to update the docs website. Can you open an issue for this reminding me to do so? 🙏

**Comment by tamastimar** [comment]
@SD10 #688.

That's not a fault at all. Thanks for running the project. ;)
