### ISSUE TITLE
Feature request - Caption

### ISSUE THREAD

**Issue by alessioarsuffi** [MessageKit/MessageKit#689]
## General Information
I would like to have a property caption, inside the Media cell so It can be displayed just like the attached image.

![img_dc9002880714-1](https://user-images.githubusercontent.com/3455711/40131112-517e7bd8-5939-11e8-911b-85fc690109a4.jpeg)

* MessageKit Version:
1.0.0 beta 1

* iOS Version(s):

* Swift Version:

* Devices/Simulators:

* Reproducible in ChatExample? (Yes/No):

## What I'm wondering

We could add 

```swift
/// The caption to be displayed under media
var caption: String? { get set }
```

in MediaItem protocol. And add conditional cases in MediaMessageSizeCalculator and MediaMessageCell to accomplish the expected result

**Comment by SD10** [comment]
@alessioarsuffi So my problem with this is it adds another label to the cell. This is probably not something MessageKit will support. At some point, you just have to start making your own cells. We can't add a ton of views (especially labels) to the cells for performance reasons. It results in people only using the subset of views they need and the remainder of them clogging up the cell.

**Comment by nathantannar4** [comment]
To add to what Steven said, we aimed to mimic the iMessage style where photos are in their own message cells

**Comment by alessioarsuffi** [comment]
Ok, It's clear. I will subclass MediaMessageCell to have the desired layout, thanks :)
