### ISSUE TITLE
Make MessageType, MessageKind and Sender Codable objects for serialization

### ISSUE THREAD

**Issue by wildseansy** [MessageKit/MessageKit#691]
### Feature request: 

Make `MessageType`, `MessageKind` and `Sender` objects [`Codable`](https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types).

This will make it much easier to use caching (for example [Cache](https://github.com/hyperoslo/Cache)) frameworks for storing/recalling message history from disk. It's definitely a need for me, but it seems like this would be a common use case

**Comment by SD10** [comment]
@wildseansy This is interesting but I'm not sure it's a good idea. In our app, I don't use Codable because we're using Realm. There is no way for our objects to achieve `Codable` conformance.

I'd rather leave this up to the consumers of MessageKit to implement.

**Comment by nathantannar4** [comment]
Perhaps you can just extend `MessageType`, `MessageKind` and `Sender` as Codable objects.

**Comment by wildseansy** [comment]
yeah, I was considering subclassing and making them all `Codable`. Just thought message data serialization might be a broader need, and might save other people that pain. Might be painful though for this project to maintain as data types change.

**Comment by nathantannar4** [comment]
Data types will be consistent after 1.0, also try `extension` rather than subclassing

**Comment by SD10** [comment]
I can't support this because like I said, `Codable` is not possible for my project. This is too client specific. Thanks for the discussion though @wildseansy 👍

**Comment by davidkuhta** [comment]
Hi there! `extension` suits my needs, but I wanted to ask if making only `MessageKind` and `Sender` objects `Codable` would accommodate those whose `Message` objects are `Codable`, while not making it required as would be the case for `MessageType`.

**Comment by SD10** [comment]
@davidkuhta Protocols are not good candidates to force `Codable` conformance on. This prevents users from adopting the `MessageType` protocol in cases where they cannot adopt `Codable`. 

Considering `MessageKind` is an enum, it looks like it would be a good candidate for `Codable` conformance. However, there are associated values of the `MessageKind` enum that are protocols as well. 

In the case of `Sender`, this seems to be the only valid situation. However, we will be making `Sender` a protocol in a later version of MessageKit see #628.

Overall, I don't like the idea of forcing a specific JSON serialization strategy on consumers of MessageKit -- so `Codable` as a default is something we will never support

**Comment by wertpoiu** [comment]
> @davidkuhta Protocols are not good candidates to force `Codable` conformance on. This prevents users from adopting the `MessageType` protocol in cases where they cannot adopt `Codable`.
> 
> Considering `MessageKind` is an enum, it looks like it would be a good candidate for `Codable` conformance. However, there are associated values of the `MessageKind` enum that are protocols as well.
> 
> In the case of `Sender`, this seems to be the only valid situation. However, we will be making `Sender` a protocol in a later version of MessageKit see #628.
> 
> Overall, I don't like the idea of forcing a specific JSON serialization strategy on consumers of MessageKit -- so `Codable` as a default is something we will never support

can you please tell me how to use realm with Messagekit? I am stuck because SenderType and Messagekind does not conform to @objc.

**Comment by adtechlab03** [comment]
@wildseansy ,
I have same problem like you. have you find any solution? if yes please help me out. i need to store data in disk. need Codable objects.

Thanks
