### ISSUE TITLE
[Question] Embedding MessagesViewController in another view controller's view

### ISSUE THREAD

**Issue by wildseansy** [MessageKit/MessageKit#696]
I am trying to embed messaging UI in the hierarchy of other views in another view controller, so messages can overlay over content.

This is how I add it to the view

```swift
class ParentViewController: UIViewController {
  //ConversationViewController is subclass of MessagesViewController
  var conversationVC: ConversationViewController = ConversationViewController()
  //...
  viewDidLoad() {
        super.viewDidLoad()
        conversationVC.view.frame = self.view.bounds
        self.view.addSubview(conversationVC.view)
        self.addChildViewController(conversationVC)
        conversationVC.didMove(toParentViewController: self)
  }
}
```

This loads the messages just fine, but I cant get the `messageInputBar` to display for the life of me.  Is MessageKit designed to be able to be embedded in other view controllers?

**Comment by SD10** [comment]
@wildseansy Inside the viewDidLoad method of your `ConversationViewController` try calling `becomeFirstResponder()`. The `MessageInputBar` is the inputAccessoryView of the controller

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wildseansy** [comment]
I have tried all of these below in ConversationViewController `viewDidLoad`:

```swift
        self.becomeFirstResponder()
        self.view.becomeFirstResponder()
        self.messageInputBar.inputTextView.becomeFirstResponder()
```
but still can't see the MessageInputBar. It's worth noting the parent view controller doesn't have any text fields, and is pretty simple.  Basically just has one button and some text

**Comment by joshuaflores** [comment]
@wildseansy Try calling `self.becomeFirstResponder()` in `viewWillLayoutSubviews`

```
    override func viewWillLayoutSubviews() {
        super.viewWillLayoutSubviews()
        
        if self.isFirstResponder != true {
            self.becomeFirstResponder()
        }
    }
```

**Comment by wildseansy** [comment]
@joshuaflores - this didn't work, however after following [this post](https://stackoverflow.com/questions/45099474/becomefirstresponder-do-not-display-keyboard-in-swift-3), I tried this and it worked.  Seems a little hacky tho

```swift
    override func viewWillLayoutSubviews() {
        super.viewWillLayoutSubviews()
        
        if self.isFirstResponder != true {
            self.perform(
                #selector(becomeFirstResponder),
                with: nil,
                afterDelay: 0.3
            )
        }
    }
```

**Comment by SD10** [comment]
@joshuaflores Maybe try the parent view controller instead?

**Comment by joshuaflores** [comment]
@SD10  @wildseansy the code I posted worked for me, but it did present a few edge cases. Studying the problem some more I think the issue is calling `becomeFirstResponder` too soon. Really `viewWillLayoutSubviews` only works because of its position in the life-cycle methods. You should be able to call the same code within `viewDidLoad` by placing it within a timeout closure.

From my end I simply changed the life-cycle method from 'viewWillLayoutSubviews' to`viewDidAppear` and it seems to work fine. 

```
    override func viewDidAppear(_ animated: Bool) {
        super.viewWillLayoutSubviews(animated)
        
        if self.isFirstResponder != true {
            self.becomeFirstResponder()
        }
    }
```

The only issue now is the inputAccessory not dismissing with the viewController, but that should probably be a different gh issue...

**Comment by SD10** [comment]
You'll all get better answers if you search on SO for questions related to the `inputAccessoryView` of a `UIViewController`. This is not a MessageKit issue but a general iOS question. Just a heads up so you don't constrain yourselves to the scope of GitHub issues
