### ISSUE TITLE
Option to attach image/file and camera button click and attach

### ISSUE THREAD

**Issue by mkambale** [MessageKit/MessageKit#698]
Hi, I am integrating this framework which is simple to integrate and cool. My question is will current version of MessageKit supports Option to attach image/file and camera button click and attach?. I Just see input text bar and send button. Are there any flags to set to see this option? Please guide me.

**Comment by SD10** [comment]
@mkambale Please check out the example app. There is a demonstration of multiple buttons being added to the `MessageInputBar` through one of its stackviews. You likely want to add a button to the `leftStackView`.

**Comment by mkambale** [comment]
Thanks, I am able to add it.

**Comment by thesunita** [comment]
@mkambale : can you please guide me how you added attachment button on left of inputbar and added image. I m in urgent need please
