### ISSUE TITLE
Join bottom and top label into bubble.  

### ISSUE THREAD

**Issue by estebanarrua** [MessageKit/MessageKit#700]
## General Information

* MessageKit Version: 1.0.0-beta.1

* iOS Version(s): 11.0

* Swift Version: 4.0

Hi, I would like join the bottom and top label into the principal bubble. Exist a property to change this, or I need a custom ViewCell?  

Thanks,

Esteban.

**Comment by SD10** [comment]
Hey @estebanarrua, this seems to be related to #121. This is currently not something MessageKit supports and I don't think it will be supported in the future. You will need a custom cell to accomplish this.

**Comment by estebanarrua** [comment]
Ok. Thanks you. 

Do you have any example about custom cell?

**Comment by SD10** [comment]
@estebanarrua See this comment https://github.com/MessageKit/MessageKit/issues/686#issuecomment-389677565

**Comment by SD10** [comment]
Closing as a duplicate of #121
