### ISSUE TITLE
LabelAlignment struct needs a public memberwise initializer

### ISSUE THREAD

**Issue by BrenoVin** [MessageKit/MessageKit#701]
## General Information
I'm can't align the bottom label (left / right)

before the update I could do this using this method 
`cellBottomLabelAlignment` MessagesDisplayDelegate delegate

* MessageKit Version:
1.0 alpha

**Comment by SD10** [comment]
@BrenoVin First you need to find which `MessageSizeCalculator` object you want to configure on the `MessagesCollectionViewFlowLayout` object. Then you set either `incomingMessageBottomLabelAlignment` or `outgoingMessageBottomLabelAlignment` to the value you need.

**Comment by BrenoVin** [comment]
@SD10 I found this part 
`layout.attributedTextMessageSizeCalculator.incomingMessageBottomLabelAlignment`
My trouble is how to set the value

If I try, for example 

`layout.attributedTextMessageSizeCalculator.incomingMessageBottomLabelAlignment = LabelAlignment(textAlignment: .right, textInsets: .zero)` I got the error 

`'LabelAlignment' initializer is inaccessible due to 'internal' protection level`

**Comment by SD10** [comment]
@BrenoVin That's interesting. I wonder if the memberwise initializer is marked internal by default even though the `LabelAlignment` type is marked as `public`. We may have to add an explicit initializer. 

If you want to investigate and submit a PR adding one if this is indeed the case, I'd love that 👍

**Comment by SD10** [comment]
Yep, that's the case:

From The Swift Programming Language (Swift 4.1): Access Control

> As with the default initializer above, if you want a public structure type to be initializable with a memberwise initializer when used in another module, you must provide a public memberwise initializer yourself as part of the type’s definition.

So we need to provide our own initializer marked public.

**Comment by BasThomas** [comment]
Awesome first issue :)
