### ISSUE TITLE
Hi i want to change the alignment of date of bottom lable from right side to left side & voice versa for other bubble >> right now its on wrong side >> date is always appended on opposite side of avatar see the attachment >> i want to show the date on red marks

### ISSUE THREAD

**Issue by fahadDev6** [MessageKit/MessageKit#704]
![screen shot 2018-05-29 at 4 02 57 pm](https://user-images.githubusercontent.com/39731008/40655360-8a2e8d1c-635a-11e8-9319-97104fd56078.png)
## General Information

* MessageKit Version:

* iOS Version(s):

* Swift Ver
![screen shot 2018-05-29 at 4 02 57 pm](https://user-images.githubusercontent.com/39731008/40655210-1182c450-635a-11e8-8563-1cc00883191d.png)
sion:

* Devices/Simulators:

* Reproducible in ChatExample? (Yes/No):

**Comment by SD10** [comment]
@fahadDev6 See this comment https://github.com/MessageKit/MessageKit/issues/701#issuecomment-392569531

**Comment by fahadDev6** [comment]
I've resolve the problem 
by modifying the following method In Class **MessageCollectionViewCell**

open override func apply(_ layoutAttributes: UICollectionViewLayoutAttributes) {
        
        super.apply(layoutAttributes)
        
        if let attributes = layoutAttributes as? MessagesCollectionViewLayoutAttributes {
            
            avatarView.frame = attributes.avatarFrame
            
            cellTopLabel.frame = attributes.topLabelFrame
            
            let screenSize = UIScreen.main.bounds
            
            attributes.bottomLabelFrame.size.width = screenSize.width - 31
            
            attributes.bottomLabelFrame.origin.x = 7
            
            cellBottomLabel.frame = attributes.bottomLabelFrame
            
            messageContainerView.frame = attributes.messageContainerFrame
            
        }
        
    }

Then  we can give the attributed string
func cellBottomLabelAttributedText(for message: MessageType, at indexPath: IndexPath) -> NSAttributedString? {
        
        let dateString =  BlueBoxUtilities.getStringFromDate(date: message.sentDate,fromat: "HH:mm")//formatter.string(from: message.sentDate)//message.createdDate//formatter.string(from: message.sentDate)
        let paragraphStyle = NSMutableParagraphStyle()
        if message.sender.id == "1" {
            paragraphStyle.alignment = NSTextAlignment.right
        }
        else
        {
            paragraphStyle.alignment = NSTextAlignment.left
        }
        return NSAttributedString(string: dateString, attributes: [NSAttributedStringKey.font: UIFont.preferredFont(forTextStyle: .caption2), NSAttributedStringKey.paragraphStyle:paragraphStyle])
    }

@SD10  can you please add these changes to latest Api
