### ISSUE TITLE
Delete message by long press on cell ?

### ISSUE THREAD

**Issue by ljs19923** [MessageKit/MessageKit#706]
Hi ! I want to delete message by long press gesture on cell.
Currently i can copy the message, how can i implement the possibility of add one action ?

Thanks

**Comment by SD10** [comment]
@JulienLevallois You should be able to make `Delete` an action here by overriding
https://github.com/MessageKit/MessageKit/blob/0ceeb4905a20da59aac69d3468007e36df2b44ec/Sources/Controllers/MessagesViewController.swift#L246

Then implement it here:
https://github.com/MessageKit/MessageKit/blob/0ceeb4905a20da59aac69d3468007e36df2b44ec/Sources/Controllers/MessagesViewController.swift#L250

**Comment by ljs19923** [comment]
I dont understand where i need to override this, and what i need to do, to have 2 buttons, copy & delete

**Comment by Luke47** [comment]
> I dont understand where i need to override this, and what i need to do, to have 2 buttons, copy & delete

In the subclass of `MessagesViewController`, for example for the "delete" action (pseudocode out of my head):

```
class MyChatViewController: MessagesViewController {

override func collectionView(_ collectionView: UICollectionView, canPerformAction action: Selector, forItemAt indexPath: IndexPath, withSender sender: Any?) -> Bool {
        
        if action == #selector(UIResponderStandardEditActions.delete(_:)) {
            return true
        }
        
        return super.canPerformAction(action, withSender: sender)

    }
    
override func collectionView(_ collectionView: UICollectionView, performAction action: Selector, forItemAt indexPath: IndexPath, withSender sender: Any?) {
    
        // Delete action should be handled by yourself
        if action == #selector(UIResponderStandardEditActions.delete(_:)) {
           // Remove entry from datasource
           // Delete section of the collectionView
           return
        }
        
        // Use default handler instead
        super.collectionView(collectionView, performAction: action, forItemAt: indexPath, withSender: sender)
        
    }

}
```

**Comment by Luke47** [comment]
Okay, forget my previous comment. I just tested it and it does not seem to work. I will try to get it working (as I also need custom actions) and report back :)

**Comment by Luke47** [comment]
Okay, so @JulienLevallois here is a working example.

You need to 
1.) implement the `canPerformAction` and `performAction` delegate methods in your subclass of `MessagesViewController`, like so:

```
 override func collectionView(_ collectionView: UICollectionView, canPerformAction action: Selector, forItemAt indexPath: IndexPath, withSender sender: Any?) -> Bool {
        
        if action == NSSelectorFromString("delete:") {
            return true
        } else {
            return super.collectionView(collectionView, canPerformAction: action, forItemAt: indexPath, withSender: sender)
        }
    }
    
override func collectionView(_ collectionView: UICollectionView, performAction action: Selector, forItemAt indexPath: IndexPath, withSender sender: Any?) {

        if action == NSSelectorFromString("delete:") {
            // 1.) Remove from datasource
            // insert your code here
            
            // 2.) Delete sections
            collectionView.deleteSections([indexPath.section])
        } else {
            super.collectionView(collectionView, performAction: action, forItemAt: indexPath, withSender: sender)
        }
    }
```

2.) Also you need to write an extension to the class of the `UICollectionView` subclass you are using  and provide the implementation of the action there, e.g.

```
extension MessageCollectionViewCell {

    override open func delete(_ sender: Any?) {
        
        // Get the collectionView
        if let collectionView = self.superview as? UICollectionView {
            // Get indexPath
            if let indexPath = collectionView.indexPath(for: self) {
                // Trigger action
                collectionView.delegate?.collectionView?(collectionView, performAction: NSSelectorFromString("delete:"), forItemAt: indexPath, withSender: sender)
            }
        }
    }
}

```

That is the easiest way that I have found, I hope it helps!

**Update**: The code above is meant for system actions like copy or delete. In order to add custom actions, just follow the same scheme, but add your custom actions also to the UIMenuController, like so:

```
class CustomChatViewController: MessagesViewController {
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let customMenuItem = UIMenuItem(title: "Quote", action: #selector(MessageCollectionViewCell.quote(_:)))
        UIMenuController.shared.menuItems = [customMenuItem]
     }

}
```

Of course add the custom actions also to `canPerformAction` and `performAction` and to your UICollectionViewCell extension:

```
extension MessageCollectionViewCell {
    @objc func quote(_ sender: Any?) {
        
        // Get the collectionView
        if let collectionView = self.superview as? UICollectionView {
            // Get indexPath
            if let indexPath = collectionView.indexPath(for: self) {
                // Trigger action
                collectionView.delegate?.collectionView?(collectionView, performAction: #selector(MessageCollectionViewCell.quote(_:)), forItemAt: indexPath, withSender: sender)
            }
        }
    }
}

```

**Comment by JulienLevallois** [comment]
@Luke47 thanks! Its perfect.
But my app crash at             collectionView.deleteSections([indexPath.section])

![image](https://user-images.githubusercontent.com/5727223/41697872-fe6020a2-74e8-11e8-90c1-d1ac016b0131.png)

**Comment by ljs19923** [comment]
@Luke47  thank you very much :)

**Comment by nathantannar4** [comment]
@JulienLevallois you need to delete the message from your datasource as he commented in the code. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
Glad this one could be resolved! Thanks everyone 😃

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ljs19923** [comment]
Hi @Luke47 & @SD10 , " delete "  messages dont works for Location type message. For text & images its good but long press dont works for location :/ I want to be able to delete a location message.

Do you have ideas why ?
Thanks

**Comment by kpsdeveloper** [comment]
Hello, I have similar issue of long press on message but not canPerformAction or performAction.
I want to add alert Action menu "Forward" & "Report" when user did long press on someone else message as you see in my attachment picture. This is follow telegram feature.
![img_1316](https://user-images.githubusercontent.com/14867309/43895486-b4ea4072-9bff-11e8-8ab1-74c65c8712f3.PNG)

Appreciate for this great help!

**Comment by SD10** [comment]
@kpsdeveloper You'll have to look at my comment above in this thread. This is a general iOS question and not really related to MessageKit 😢

**Comment by tobitech** [comment]
@Luke47 I tried your answer, but my i couldn't get my delete action to do anything, not even a print statement. in other words, the delete action isn't called but it shows with the copy. any idea what might be wrong?

**Comment by tobitech** [comment]
@ichikmarev @Luke47  I have overriden the `canPerformAction action: Selector, forItemAt` and still doesn't work. only the copy action works. please help

**Comment by tobitech** [comment]
Okay this works, the issue i have with this now is in this `func messageForItem(at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> MessageType {
        return messageList[indexPath.section]
    }`  throws an index out of range error. How can I fix this please?

**Comment by nathantannar4** [comment]
@tobitech Have you forgotten to call delete on the index path of the collection view while also removing it from your messages array?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tobitech** [comment]
@nathantannar4 I did 
`messageList.remove(at: indexPath.section)
            collectionView.deleteSections([indexPath.section])
            messagesCollectionView.reloadData()`
the crash only occurs when i'm deleting the last item in my messages array

**Comment by hien352911** [comment]
Hi @Luke47 , I download sample code from messagekit and copy paste your code into sample, but it is not working. I get only copy like default of sample, not display delete. I also did not receive add custom menuItem for cell

**Comment by engin7** [comment]
Hi, solution Luke gave seems like for deleting message from both sides.  I need to implement deleting for only user who deletes it. So other person can still see the message like in whatsapp.
What changes should i make, as person leaves chat room and comes back this message will load again as its not deleted from database right? I need to implement a filtering method. Don't know how.

**Comment by ghost** [comment]
@Luke47 @kinoroy 

https://github.com/MessageKit/MessageKit/issues/706#issuecomment-395107647
Does this method work correctly on iOS15?
It doesn't work correctly when I want to change the `UIResponderStandardEditActions` for my message and the other person's message.
For example, you want to show `copy` and `delete` in my message, and only `copy` in the other message. The other person's message will also show `copy` and `delete`.

Thankyou.

**Comment by kboirel** [comment]
I added the code from @Luke47 and it's working very well for texts and images. But it's not working at all for video messages. Do you have any suggestions?
Thank you in advance

**Comment by raaed9** [comment]
Use messageKit with Firebase When I delete any message in the chat using long press, it gets deleted in front of me, but when I leave the chat and come back, it is not actually deleted.

https://user-images.githubusercontent.com/82851609/209820799-e9bcf2bc-a47b-45af-b257-e9bac381ef95.mp4

`   override func collectionView(_ collectionView: UICollectionView, performAction action: Selector, forItemAt indexPath: IndexPath, withSender sender: Any?) {


   
           if action == NSSelectorFromString("delete:") {
               // 1.) Remove from datasource
               // insert your code here
               self.mkMessages.remove(at: indexPath.section)
               // 2.) Delete sections
               collectionView.deleteSections([indexPath.section])
           } else {
              return super.collectionView(collectionView, performAction: action, forItemAt: indexPath, withSender: sender)
           }
       }`

**Comment by Kenny0105** [comment]
> Okay, so @JulienLevallois here is a working example.
> 
> You need to 1.) implement the `canPerformAction` and `performAction` delegate methods in your subclass of `MessagesViewController`, like so:
> 
> ```
>  override func collectionView(_ collectionView: UICollectionView, canPerformAction action: Selector, forItemAt indexPath: IndexPath, withSender sender: Any?) -> Bool {
>         
>         if action == NSSelectorFromString("delete:") {
>             return true
>         } else {
>             return super.collectionView(collectionView, canPerformAction: action, forItemAt: indexPath, withSender: sender)
>         }
>     }
>     
> override func collectionView(_ collectionView: UICollectionView, performAction action: Selector, forItemAt indexPath: IndexPath, withSender sender: Any?) {
> 
>         if action == NSSelectorFromString("delete:") {
>             // 1.) Remove from datasource
>             // insert your code here
>             
>             // 2.) Delete sections
>             collectionView.deleteSections([indexPath.section])
>         } else {
>             super.collectionView(collectionView, performAction: action, forItemAt: indexPath, withSender: sender)
>         }
>     }
> ```
> 
> 2.) Also you need to write an extension to the class of the `UICollectionView` subclass you are using and provide the implementation of the action there, e.g.
> 
> ```
> extension MessageCollectionViewCell {
> 
>     override open func delete(_ sender: Any?) {
>         
>         // Get the collectionView
>         if let collectionView = self.superview as? UICollectionView {
>             // Get indexPath
>             if let indexPath = collectionView.indexPath(for: self) {
>                 // Trigger action
>                 collectionView.delegate?.collectionView?(collectionView, performAction: NSSelectorFromString("delete:"), forItemAt: indexPath, withSender: sender)
>             }
>         }
>     }
> }
> ```
> 
> That is the easiest way that I have found, I hope it helps!
> 
> **Update**: The code above is meant for system actions like copy or delete. In order to add custom actions, just follow the same scheme, but add your custom actions also to the UIMenuController, like so:
> 
> ```
> class CustomChatViewController: MessagesViewController {
>     
>     override func viewDidLoad() {
>         super.viewDidLoad()
>         
>         let customMenuItem = UIMenuItem(title: "Quote", action: #selector(MessageCollectionViewCell.quote(_:)))
>         UIMenuController.shared.menuItems = [customMenuItem]
>      }
> 
> }
> ```
> 
> Of course add the custom actions also to `canPerformAction` and `performAction` and to your UICollectionViewCell extension:
> 
> ```
> extension MessageCollectionViewCell {
>     @objc func quote(_ sender: Any?) {
>         
>         // Get the collectionView
>         if let collectionView = self.superview as? UICollectionView {
>             // Get indexPath
>             if let indexPath = collectionView.indexPath(for: self) {
>                 // Trigger action
>                 collectionView.delegate?.collectionView?(collectionView, performAction: #selector(MessageCollectionViewCell.quote(_:)), forItemAt: indexPath, withSender: sender)
>             }
>         }
>     }
> }
> ```

Does anyone know where I can implement "extension MessageCollectionViewCell"?

**Comment by hkhl1997** [comment]
But how to add more button after long press?
