### ISSUE TITLE
How can i align the date to right side ? Like the bubble

### ISSUE THREAD

**Issue by ljs19923** [MessageKit/MessageKit#708]
How can i align the date to right side ? Like the bubble. This project is good, but the code is not really clear... Impossible to understand the logic behind :/

![image](https://user-images.githubusercontent.com/5727223/40797538-7eea257e-64d6-11e8-91d0-bc6f327305b1.png)

**Comment by SD10** [comment]
@JulienLevallois You would need to set the `bottomLabelAlignment` property on the `MessageSizeCalculator` object. I would recommend using CMD + Click in Xcode on the MessageKit types to jump into their files and see what properties are available

**Comment by bofiaza** [comment]
@JulienLevallois, this how I did it:

     //Date alignment
        (messagesCollectionView.collectionViewLayout as! MessagesCollectionViewFlowLayout).textMessageSizeCalculator.incomingMessageBottomLabelAlignment.textInsets = UIEdgeInsets(top: 0, left: 12, bottom: 0, right: 0)
        (messagesCollectionView.collectionViewLayout as! MessagesCollectionViewFlowLayout).textMessageSizeCalculator.outgoingMessageBottomLabelAlignment.textInsets = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 12)
        (messagesCollectionView.collectionViewLayout as! MessagesCollectionViewFlowLayout).attributedTextMessageSizeCalculator.incomingMessageBottomLabelAlignment.textInsets = UIEdgeInsets(top: 0, left: 12, bottom: 0, right: 0)
        (messagesCollectionView.collectionViewLayout as! MessagesCollectionViewFlowLayout).attributedTextMessageSizeCalculator.outgoingMessageBottomLabelAlignment.textInsets = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 12)
        (messagesCollectionView.collectionViewLayout as! MessagesCollectionViewFlowLayout).emojiMessageSizeCalculator.incomingMessageBottomLabelAlignment.textInsets = UIEdgeInsets(top: 0, left: 12, bottom: 0, right: 0)
        (messagesCollectionView.collectionViewLayout as! MessagesCollectionViewFlowLayout).emojiMessageSizeCalculator.outgoingMessageBottomLabelAlignment.textInsets = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 12)
        (messagesCollectionView.collectionViewLayout as! MessagesCollectionViewFlowLayout).photoMessageSizeCalculator.incomingMessageBottomLabelAlignment.textInsets = UIEdgeInsets(top: 0, left: 12, bottom: 0, right: 0)
        (messagesCollectionView.collectionViewLayout as! MessagesCollectionViewFlowLayout).photoMessageSizeCalculator.outgoingMessageBottomLabelAlignment.textInsets = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 12)
        (messagesCollectionView.collectionViewLayout as! MessagesCollectionViewFlowLayout).videoMessageSizeCalculator.incomingMessageBottomLabelAlignment.textInsets = UIEdgeInsets(top: 0, left: 12, bottom: 0, right: 0)
        (messagesCollectionView.collectionViewLayout as! MessagesCollectionViewFlowLayout).videoMessageSizeCalculator.outgoingMessageBottomLabelAlignment.textInsets = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 12)
        (messagesCollectionView.collectionViewLayout as! MessagesCollectionViewFlowLayout).locationMessageSizeCalculator.incomingMessageBottomLabelAlignment.textInsets = UIEdgeInsets(top: 0, left: 12, bottom: 0, right: 0)
        (messagesCollectionView.collectionViewLayout as! MessagesCollectionViewFlowLayout).locationMessageSizeCalculator.outgoingMessageBottomLabelAlignment.textInsets = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 12)

Just set the `left` and `right` inset values to your requirement.
