### ISSUE TITLE
Data detectors for MessageLabel

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#71]
If we don't use `UITextView` for the `MessageLabel` we'll have to write the data detectors in-house. 

UITextView currently supports:
- [x] Phone Number
- [x] URL
- [x] Address
- [x] Date
- [ ] Shipment Tracking Number
- [ ] Flight Number
- [ ] Lookup Suggestion

It would be nice to also support:
- [ ] Email
- [ ] Hashtags
- [ ] Mentions
- [ ] Custom detector

**Comment by ulaserdegor** [comment]
Location Type cell ? @SD10 
to open it in the map applications when clicked.

**Comment by martinpucik** [comment]
Support for all of these types and custom regex one should be implemented now
