### ISSUE TITLE
Cocoa Pods Install Not Updated

### ISSUE THREAD

**Issue by carlsondev** [MessageKit/MessageKit#713]
Without an updated cocoa pod install (which I would prefer to use), I can't use any of the demo resources since they are updated to the current version. Currently I am using Xcode 9.4 with Swift 4.

**Comment by nathantannar4** [comment]
I'm sorry but can your clarify the issue? What do mean demo resources?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by carlsondev** [comment]
The Example folder within this repo, it seems to be the best resource for learning the API. But since cocoa pods is not updated with the newest version, that example does not have the same code base, which makes it difficult to learn to use the cocoa pods version.

**Comment by nathantannar4** [comment]
Example projects never ship with the framework. You need to download the entire repository

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by carlsondev** [comment]
I understand that. All I am asking is that the cocoa pod spec becomes updated with the version in the GitHub repo so the github example code is consistent with the cocoa pod code base

**Comment by SD10** [comment]
@FibonacciRedstone Your local pods are outdated. Run `pod repo update` and then possibly `pod install` again

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
