### ISSUE TITLE
布局乱了

### ISSUE THREAD

**Issue by chunxige** [MessageKit/MessageKit#714]
<img width="379" alt="2018-06-05 1 44 14" src="https://user-images.githubusercontent.com/8032681/40957208-9660e316-68c6-11e8-8257-e3dab6dc56f8.png"> 
同一个用户 avatar的frame计算错了

**Comment by SD10** [comment]
@chunxige Where should it be? What is your `AvatarPosition` set to?

**Comment by chunxige** [comment]
sorry ,avatar的frame是正确的，问题不在这里，我打断点调试了，当我插入数据到collectionView然后reload collectionView时候，发现偶尔有时候对应的section用的不是当前section的MessagesCollectionViewLayoutAttributes做布局的，而是其他section的MessagesCollectionViewLayoutAttributes布局的，但是当我又发送一条新的消息布局又都变正常了

**Comment by chunxige** [comment]
<img width="384" alt="2018-06-06 11 14 19" src="https://user-images.githubusercontent.com/8032681/41013874-cfe37c2a-697a-11e8-8306-90af3e56be3c.png">
<img width="1276" alt="2018-06-06 11 10 30" src="https://user-images.githubusercontent.com/8032681/41013876-d1f0e08e-697a-11e8-8d68-f8a49944dc86.png">

**Comment by chunxige** [comment]
section = 0 用了 section = 5的MessagesCollectionViewLayoutAttributes

**Comment by SD10** [comment]
cc @zhongwuzw

**Comment by zhongwuzw** [comment]
@chunxige Can you upload a demo to reproduce what you meet? From your screenshot, maybe section 0 is the outgoing user, but its subviews all deranged.

**Comment by SD10** [comment]
I know we have a bug in the layout code:
https://github.com/MessageKit/MessageKit/blob/e280e7e35253d877490515dfef6cf15680797594/Sources/Views/Cells/MessageContentCell.swift#L174

All of these lines where we guard against `.zero` we need to remove. Because cells are reused

**Comment by zhongwuzw** [comment]
@SD10 
Yep, please see [comments](https://github.com/MessageKit/MessageKit/pull/699#discussion_r193364129)

**Comment by chunxige** [comment]
发现了解决的方法了，当我下拉加载更多历史消息时候用的是collectionView的reloadData方法刷新UI的，我更改成insertSections布局就好了
