### ISSUE TITLE
MessageContainerView Custom Mask

### ISSUE THREAD

**Issue by christianflanders** [MessageKit/MessageKit#717]
I'd like to be able to use a custom message bubble style with a tail, but the only way right now that I can see is to create a subclass of the message collection view cell and use my image asset to create a mask, but I haven't had much luck with this route. I tried using the .custom message style, but since the imageMask property is private, I can't do anything with my image asset.

Most of the methods in the MethodContainerView that would be helpful for doing this are private. Is there something I'm missing or would this be a possible feature to add in the future? Thanks!

**Comment by SD10** [comment]
@christianflanders You should be able to apply your own mask in the `MessageStyle.custom` block. If you look at the implementation, it sets the `mask` property to `nil` before calling the closure:

https://github.com/MessageKit/MessageKit/blob/master/Sources/Views/MessageContainerView.swift#L81
