### ISSUE TITLE
Display the date of message by swiping the cell (right or left)

### ISSUE THREAD

**Issue by mrhaxic** [MessageKit/MessageKit#718]
Hello for the awesome contribution,

This is not an issue, it is like a feature request or enhancements for the library.
What is about showing the message date by swiping the cell from the right or left side [Gestures] of course similar to iMessage.

Suggestions ?

**Comment by nathantannar4** [comment]
Currently the library doesn't support this functionality and nor is it an easy feature to accomplish. We don't have something like this planned for the best future

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kaspik** [comment]
Fixed in #1444 , closing for release. :)
