### ISSUE TITLE
AttributedString foreground color not working inside bubble

### ISSUE THREAD

**Issue by GoldSnake2100** [MessageKit/MessageKit#720]
Hi
I was trying to add two line of attributed string inside bubble.
I used this function to create message object.

let str = userName + "\n" + temp.message!
let rangeName = (str as NSString).range(of: userName)
let rangeMessage = (str as NSString).range(of: temp.message!)
                        
let attribute = NSMutableAttributedString(string: str)
attribute.setAttributes([.foregroundColor: UIColor.gray, .font: UIFont(name: "Comfortaa", size: CGFloat(fontsizeName))!] , range: rangeName)
attribute.setAttributes([.foregroundColor: UIColor.black, .font: UIFont(name: "Comfortaa", size: CGFloat(fontsizeMessage))!] , range: rangeMessage)
let message = MockMessage(attributedText: NSAttributedString(attributedString: attribute), sender: sender, messageId: snapshot.key, date: date)

But foreground color didn't apply at all.
I hope you have good solution for this.
Thanks in advance.

**Comment by nathantannar4** [comment]
Try not initializing a new attributed string when you already have one in your 'let message = ...'

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by GoldSnake2100** [comment]
Thanks for your quick reply.
But the result is same.

**Comment by GoldSnake2100** [comment]
Hi, 
I have found the issue.
I have to change order of messageLabel.textcolor in messageCell config function of MessageCollectionViewCell
This line placed after setting of messageLabel.attributedText
so the foreground color is overidden with textcolor
