### ISSUE TITLE
How to Add shadow to MessageContainerView

### ISSUE THREAD

**Issue by charbelMat** [MessageKit/MessageKit#721]
Hi,

How can we add a shadow layer to the MessageContainerView ? 

Thanks !

**Comment by SD10** [comment]
@charbelMat You might want to try looking at the `.custom` case of the `MessageStyle` enum. This gives you a configuration block with access to the `MessageContainerView`. Your other options are subclass the cells or overriding `cellForItem(at: IndexPath)` and doing some configuration there.

**Comment by lsmilek1** [comment]
Hi, on your "advanced example" I tried to add a sublayer on to the container view as following:

```
return .custom { view in
            let radius: CGFloat = 16
            let path = UIBezierPath(roundedRect: view.bounds, byRoundingCorners: corners, cornerRadii: CGSize(width: radius, height: radius))
            let mask = CAShapeLayer()
            mask.path = path.cgPath
            view.layer.mask = mask
            let shadowLayer = CAShapeLayer()
            shadowLayer.path = path.cgPath
            shadowLayer.frame = view.frame
            shadowLayer.shadowOpacity = 0.4
            shadowLayer.shadowRadius = 2
            shadowLayer.shadowColor = UIColor.black.cgColor
            shadowLayer.shadowOffset = CGSize(width: 4, height: 4)
            view.superview!.layer.insertSublayer(shadowLayer, below: view.layer)
        }
```

On the first view load it works good, but as soon as the messageKit reload and add new cells, then I get this shadow layers messed up even for previously fine cells:

![image](https://user-images.githubusercontent.com/41491201/57036465-a43ca000-6c54-11e9-93be-b8ea9d022840.png)

Actually the only thing I want to do is to take your bubble design (tail + rounded) and add a very small shadow. I believe there is a way how to achieve it through the .custom, but isn't this a little DRY  when I want the same bubble design? I would really appreciated, if this would be a part of the messageKit.

Thank you for advice/comments!

**Comment by nathantannar4** [comment]
You might want to try removing previously inserted shadow layers as it looks like you insert layers but don't handle the case where a shadow layers was already inserted. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ibhavin** [comment]
@lsmilek1  Have you find any solution?
