### ISSUE TITLE
How to keep the inputBar when presenting a viewController

### ISSUE THREAD

**Issue by felixjichao** [MessageKit/MessageKit#722]
I wand to present the system camera to capture photo, but after calling present(), the inputBar gets hided. 
As the inputAccessoryView of the collectionView, how to keep it when presenting other viewController?  Any suggestions?

**Comment by nathantannar4** [comment]
I don't think you can. It's an `InputAccessoryView` of the `MessagesViewController` which means presenting a new one will resign the existing one as the first responder. Could be wrong though, maybe try presenting one but chance the modalPresentationStyle to overCurrentContext

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by felixjichao** [comment]
@nathantannar4 the modalPresentationStyle has no effect, but I found a solution from 
https://stackoverflow.com/questions/28564710/keep-keyboard-on-when-uialertcontroller-is-presented-in-swift
which can keep the inputAccessoryView shown when presenting the AlertView, but Xcode shows ```Keyboard cannot present view controllers``` message.

**Comment by nathantannar4** [comment]
Which solution are you referring to? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by felixjichao** [comment]
```
if let window = UIApplication.shared.windows.last {
    window.rootViewController?.present(alertController, animated: true, completion: nil)
}
```

**Comment by nathantannar4** [comment]
🤔 that's probably because your presenting a new view controller on one of MessagesViewController's parents 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by felixjichao** [comment]
I am going to use this method to present ```UIAlertViewController``` in order to keep the input bar shown.
If we can have our own keyboard tracker to adjust the position of the input bar rather than using ```InputAccessoryView```, maybe we can have more custom features on the input bar.

**Comment by nathantannar4** [comment]
There are different trade-offs with making the text input a subview or an inputAccessoryView but we landed on making it the latter

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chenguohao** [comment]
this issue  is quite serious , when present a view controller ,the input bar auto-hide,  really ridiculous,

**Comment by nathantannar4** [comment]
It's possible @chenguohao but it's based on how you present your alert. https://stackoverflow.com/questions/46996251/inputaccessoryview-animating-down-when-alertcontroller-actionsheet-presented

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chenguohao** [comment]
> It's possible @chenguohao but it's based on how you present your alert. https://stackoverflow.com/questions/46996251/inputaccessoryview-animating-down-when-alertcontroller-actionsheet-presented
> 
> Sent with [GitHawk](http://githawk.com)

ok, I will try,thx for that
