### ISSUE TITLE
Why are the properties in MediaItem declared as settable?

### ISSUE THREAD

**Issue by ndonald2** [MessageKit/MessageKit#723]
Hi friendly MessageKit maintainers,

I'm in the process of adopting the 1.0-beta and I have a question about the new `MediaItem` protocol for photo/video messages. I'm curious why the properties in the protocol interface - `image`, `url`, etc - are declared as `{ get, set, }`?

It does not appear that `MessageKit`'s internals require them to be settable and I'm struggling to think of a reason why a user would want to set the properties of an existing `MediaItem` instance, especially if it's implemented as a `struct` under the hood where value semantics come into play.

The only explanation I can come up with is that you might want to asynchronously download an image and update the cell later using `MediaIMessageCell:: configure(with message: MessageType, at indexPath: IndexPath, and messagesCollectionView: MessagesCollectionView)` but even then I'm not sure it makes a ton of sense to allow mutation at the protocol level. In that case presumably the user would have access to the backing type anyway and wouldn't need to work with an instance viewed only through the `MediaItem` protocol.

Can you elaborate on this, or otherwise would you consider changing the `MediaItem` protocol's properties to get-only for simplicity's sake? I could definitely see it being confusing allowing mutation at the protocol level without any clear use case.

Thanks!

**Comment by zhongwuzw** [comment]
@ndonald2 , Good point 👍 . We can remove `set` constraint, we don't need to set internal. 
@SD10 , What's your opinion?

**Comment by SD10** [comment]
@ndonald2 @zhongwuzw I'm unclear on the downside of this being marked as `get`/`set`? In my opinion, it's always better to provide the most flexible options as possible as long as there is no unexpected behavior

**Comment by zhongwuzw** [comment]
@SD10 , My opinion, when we marked `get`, we just tell the user, we only need to get these values, and also maybe user wants a constant stored property or read-only computed property. 

>  it's always better to provide the most flexible options as possible as long as there is no unexpected behavior

🤔 It's not the flexible options, it's the most constraint options. 

<img width="499" alt="image" src="https://user-images.githubusercontent.com/5061845/41331108-de0cbe6c-6f09-11e8-8385-338ca45b912e.png">

**Comment by SD10** [comment]
@zhongwuzw @ndonald2 My bad I misunderstood what the issue was asking to accomplish 😆

**Comment by SD10** [comment]
This has been fixed in #727
