### ISSUE TITLE
How to limit the input bar to the details view controller

### ISSUE THREAD

**Issue by bofiaza** [MessageKit/MessageKit#724]
Hi,

How do I adjust the input bar such that it only covers the details area of the split view controller? In the following example, the input bar covers the whole split view.

<img width="847" alt="screen shot 2018-06-12 at 3 52 59 pm" src="https://user-images.githubusercontent.com/2460102/41288802-27ad2ad8-6e7a-11e8-8339-2558c6b3d49e.png">

**Comment by SD10** [comment]
Hey @bofiaza, currently, there is no support for this in MessageKit. You can see #296 for the changes you would need to make for this. My company won't support the iPad for our chat application for a few more months. When we do, MessageKit will support this

**Comment by Vaberer** [comment]
Is there a solution to have an input bar just in a detail controller?
