### ISSUE TITLE
How to adjust the position of message bubble

### ISSUE THREAD

**Issue by bofiaza** [MessageKit/MessageKit#729]
MessageKit version: 1.0.0-beta.1

I'm grouping some messages and having this code for the message style:

    func messageStyle(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> MessageStyle {
        if shouldStartNewGroup(from: indexPath) {
            let corner: MessageStyle.TailCorner = isFromCurrentSender(message: message) ? .bottomRight : .bottomLeft
            return .bubbleTail(corner, .curved)
        } else {
            return .bubble
        }
    }

This is how the message bubbles look like:

<img width="399" alt="screen shot 2018-06-15 at 1 54 28 am" src="https://user-images.githubusercontent.com/2460102/41429417-a4a1247e-703f-11e8-91fc-dfabcff757e3.png">

To adjust the non-tailed bubble a little bit to the left (so that it aligns perfectly along the red line), I have this:

    override func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        let size = super.collectionView(collectionView, layout: collectionViewLayout, sizeForItemAt: indexPath)
        
        if size == .zero || self.shouldStartNewGroup(from: indexPath) {
            return size
        } else {
            let newSize = CGSize(width: size.width - 12, height: size.height)
            return newSize
        }
    }

which resulted to this:

<img width="398" alt="screen shot 2018-06-15 at 1 56 44 am" src="https://user-images.githubusercontent.com/2460102/41429592-184f5170-7040-11e8-8d3d-c072d6bcb035.png">

For my question, is this the correct approach or is there a better way to achieve this?

**Comment by SD10** [comment]
@bofiaza You can set some padding around the message container by using these:
https://github.com/MessageKit/MessageKit/blob/10c98b04fe95bfe98cebaeacf726b0070a27d68f/Sources/Layout/MessageSizeCalculator.swift#L41-L42

**Comment by hjuraev** [comment]
This would not resolve the issue because it will mark all incoming and outgoing with specific paddings. We need to specify only for message bubbles with tales and not all of them. Is there a way to customize padding per message?

**Comment by Skornos** [comment]
Previously there was this method on `MessagesLayoutDelegate` but it's been deprecated. Is there a replacement how to make padding dynamic/based on the message?

```
    func messagePadding(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> UIEdgeInsets {
        fatalError("messagePadding(for:at:in) has been removed in MessageKit 1.0.")
    }

```

**Comment by cyrilzakka** [comment]
@bofiaza what is the shouldStartNewGroup() function?

**Comment by Faari7** [comment]
hi, i am facing the same issue here. I need to know how can we give extra space to specific cell/message?

**Comment by richardneitzke** [comment]
@bofiaza @Faari7 @hjuraev Have any of you found a good way to solve this misalignment problem? Just moving the bubble results in misalignment of the label, so it's not great either way for me right now.

**Comment by d-jeong** [comment]
Any better solutions to this? @Faari7 @SD10

**Comment by IrelDev** [comment]
Same issue here, any solutions?

**Comment by monstermac77** [comment]
Also would like to know a solution to this.

**Comment by monstermac77** [comment]
Also would like to know a solution to this. 

Did anyone figure out a way to elegantly get the tailed messages vertically aligned nicely with the non-tailed messages? 

<img width="398" alt="41429592-184f5170-7040-11e8-8d3d-c072d6bcb035" src="https://user-images.githubusercontent.com/3255298/225440485-0daf926f-7eea-46c8-9fab-8813c26b6c2c.png">

@IrelDev @d-jeong @richardneitzke @Faari7  @cyrilzakka @Skornos @hjuraev @bofiaza @SD10
