### ISSUE TITLE
Replace the MessageInputBar with our new MessageInputBar library

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#730]
We have decided to separate the [MessageInputBar](https://github.com/MessageKit/MessageInputBar) out into its own library. @nathantannar4 will be the lead maintainer on that project. This allows us to provide other optional subspecs to MessageKit project such as autocomplete and attachment managers without bloating the original project. 

This will be available in MessageKit 2.0 as it is a heavy new feature with API breaking changes.

cc @nathantannar4 can you submit a PR against the MessageKit `development` branch making this addition?

**Comment by nathantannar4** [comment]
Will do

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
