### ISSUE TITLE
Improve the UI of the example app

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#731]
I'd like to improve the UI of our example app so that we can take screenshots from it for the README. This is something I don't really have much time to dedicate to, but I think it's a good first issue 👍

**Comment by nathantannar4** [comment]
#760

**Comment by saurabhPV** [comment]
Just a suggestion, if you could not inherit it from ChatViewController that would really help. Because then it can be easily understood, explored and used to jump-start too.

Thanks!
