### ISSUE TITLE
Issue With Hiding Top and Bottom Labels

### ISSUE THREAD

**Issue by SamaritanMachine** [MessageKit/MessageKit#735]
**MessageKit Version: 0.13.5
Swift Version: 4.1
Test Device: iPhone 7**

When I do these two implements in MessageKit Example project, it is worked as expected. But somehow, in my project when I do that, it is not working. Labels are still in there. Also, I've tried other MessagesLayoutDelegate functions like cellTopLabelHeight(....), they are working properly. 

In MessagesLayoutDelegate;

```
func messageTopLabelHeight(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> CGFloat {
        return 0
    }

func messageBottomLabelHeight(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> CGFloat {
        return 0
    }
```

**Comment by nathantannar4** [comment]
Sounds like your missing `messagesCollectionView.messagesLayoutDelegate = self
        messagesCollectionView.messagesDisplayDelegate = self `

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SamaritanMachine** [comment]
All delegates and data sources have been set in viewDidLoad.

**Comment by nathantannar4** [comment]
Please compare in detail with the example, if it works on the example but not with what you have written it means you have likely forgotten something

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SamaritanMachine** [comment]
Okay, I fully compared in each detail. There is no difference except Message model. My message model contains only text messages. I think it doesn't effect messageTopLabelHeight and messageBottomLabelHeight functions. I set this
`func cellTopLabelHeight(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> CGFloat {
        return 0
    }` and cell's top label is invisible anymore as expected and I've figured out that when I do CMD+Click  on MessagesLayoutDelegate, I can't see messageTopLabelHeight and messageBottomLabelHeight functions. For insurance, Although doing CMD+Click on these function in example project jump to definition, I do CMD+Click on these functions, there isn't any jumping to definition in my project. Do you have any idea?

**Comment by SD10** [comment]
@SamaritanMachine Please try upgrading to MessageKit v1.0.0-beta.2

**Comment by SamaritanMachine** [comment]
I've updated v1.0.0-beta.2. My problem is solved, MessagesLayoutDelegete functions are working but there is problems that I am facing. 

First:

`func avatarSize(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> CGSize {
        if isFromCurrentSender(message: message) {
            return CGSize.zero
        }
        else {
            return CGSize(width: 30, height: 30)
        }
    }`

Before the update, avatar of current sender doesn't exist, other sender had avatar. as expected. but now the situation is exact opposite. Current sender have avatar, other sender doesn't have avatar. (PS: Although I changed if-else block, the existing of avatar didn't change.) 

Second: 

When I send the message its label color is blue. Why?

Thanks for this great library and your kind replies.

**Comment by SamaritanMachine** [comment]
Now I've updated to non-beta 1.0.0 version. I understood that some functions have been removed. How can I set avatarSize now? 
<img width="592" alt="ekran resmi 2018-06-28 13 36 47" src="https://user-images.githubusercontent.com/31671690/42029665-fe4e6880-7ad8-11e8-93ba-699bdde3b1b3.png">

What are the alternatives for these functions? I didn't find anything. Please help.

@nathantannar4 @SD10

**Comment by SD10** [comment]
Hey @SamaritanMachine,

In MessageKit 1.0.0 we take a slightly different approach to sizing cells. The `MessagesCollectionViewFlowLayout` has a a message size calculator object for each message type:

```swift
   textMessageSizeCalculator.incomingMessageLabelInsets = .zero
   textMessageSizeCalculator.outgoingMessageLabelInsets = .zero
```

**Comment by SamaritanMachine** [comment]
It didn't help to resize avatar view. I want to hide avatar view just like previous versions. When will you update example project?

**Comment by SamaritanMachine** [comment]
Answered in FAQ of documentation.
