### ISSUE TITLE
How to set minimum height MessageInputBar ?

### ISSUE THREAD

**Issue by sonysm** [MessageKit/MessageKit#739]
Dear all,
in my project I want set default height MessageInputBar as bigger then default

**Comment by nathantannar4** [comment]
Adjust the inset properties. Each is documented with how they effect the constraints

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sonysm** [comment]
![simulator screen shot - iphone x - 2018-07-01 at 17 37 33](https://user-images.githubusercontent.com/12025894/42133503-b28a5664-7d55-11e8-99b8-105d088ff116.png)

want text view more bigger

**Comment by nathantannar4** [comment]
![simulator screen shot - iphone x - 2018-07-01 at 10 05 16](https://user-images.githubusercontent.com/15272998/42136762-4a55bec4-7d16-11e8-8258-7ee57265ea09.png)

Set the font to be bigger. The height of the `InputTextView` is dynamic

`messageInputBar.inputTextView.font = UIFont.systemFont(ofSize: 44)`

**Comment by AwaisFayyaz** [comment]
Any way i can set the height of MessageInputBar without modifying the font ?
