### ISSUE TITLE
message collection view is expanding in size when an input field becomes first responder (keyboard shows)

### ISSUE THREAD

**Issue by emperorhaplo** [MessageKit/MessageKit#747]
Hi,

I embedded my MessagesViewController inside a container view, which doesn't occupy the entire screen. It looks ok when the app is loaded and when messages are appended (the area below the last message "You can go ahead..." is another view):
<img width="436" alt="screen shot 2018-07-01 at 10 57 40 pm" src="https://user-images.githubusercontent.com/10750056/42143334-92ec7d78-7d82-11e8-85e2-b7f15a62c3d3.png">

Whenever I'm appending a message, I call the method messagesCollectionView.scrollToBottom(animated: true).

However, when I have an input field in the other view become first responder (displaying a keyboard), all of a sudden the MessagesViewController starts occupying the entire screen and overlapping underneath my other view:

<img width="442" alt="screen shot 2018-07-01 at 11 03 50 pm" src="https://user-images.githubusercontent.com/10750056/42143446-0cf1ebda-7d83-11e8-83e0-d59f8490ade3.png">

And this behavior continues even after the keyboard is dismissed (I call resignFirstResponder on the input field): 

<img width="449" alt="screen shot 2018-07-01 at 10 56 22 pm" src="https://user-images.githubusercontent.com/10750056/42143574-ce7320b2-7d83-11e8-851d-131d6ac434cb.png">

I cannot even scroll to the bottom (either calling the method or scrolling manually) at that point since the MessagesViewController thinks it is already at the bottom since it thinks it occupies the entire screen.

Any idea what causes this behavior and how to fix it?

**Comment by nathantannar4** [comment]
Looks like you need to change the frame of the MessageViewController. From your screen shots I don't think it has anything to do with the keyboard. I see that your 3 button view takes up space that is unused when your input view becomes active. 

Any reason you need to embed this in another view controller and not use the MessageInputBar? Your approach seems to complicate things. I would recommend just using the MessageViewController and just add a subview for your 3 extra buttons that lies in front of the MessageCollectionView

```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by emperorhaplo** [comment]
I have some other things that go/need to be edited in the other view, like buttons and other controls that are context specific. Is there anything I need to call to set the frame of the MessageViewController? I have the size set by autolayout (the view at the bottom of the screen is called User Area, the height is constant, and the bottom of the Message Kit view is set to be equal to the top of the User Area), and this bug only happens when the keyboard or a popup appear and then dismiss. Here is my storyboard:

<img width="830" alt="screen shot 2018-07-02 at 11 56 18 am" src="https://user-images.githubusercontent.com/10750056/42174030-fc3dff56-7dee-11e8-8fc1-c5078e316ff2.png">

**Comment by osmnsrn** [comment]
Hi, I faced a similar issue. I think 'isMessagesControllerBeingDismissed' parameter is the problem. Somehow,    

private func handleKeyboardDidChangeState(_ notification: Notification) {
        guard let keyboardEndFrame = notification.userInfo?[UIKeyboardFrameEndUserInfoKey] as? CGRect else { return }
        
        guard !isMessagesControllerBeingDismissed else { return }
        
        let newBottomInset = view.frame.height - keyboardEndFrame.minY - iPhoneXBottomInset
        
        let differenceOfBottomInset = newBottomInset - messageCollectionViewBottomInset
        
        if maintainPositionOnKeyboardFrameChanged && differenceOfBottomInset != 0 {
            let contentOffset = CGPoint(x: messagesCollectionView.contentOffset.x, y: messagesCollectionView.contentOffset.y + differenceOfBottomInset)
            messagesCollectionView.setContentOffset(contentOffset, animated: false)
        }
        
        messageCollectionViewBottomInset = newBottomInset
    }

called before viewDidAppear. And 'isMessagesControllerBeingDismissed' is not true in this function. Therefore, inset is not changing.  My problem is, presenting new controller from my conversaion controller.  I tried to present  this webview 

guard let url = URL(string: "https://github.com/MessageKit/MessageKit") else { return }
        let webViewController = SFSafariViewController(url: url)
        present(webViewController, animated: true, completion: nil)

on handle typing methods and it happened again when you come back to conversation screen. I am putting screen shot.


![simulator screen shot - iphone 8 - 2018-07-04 at 16 08 58](https://user-images.githubusercontent.com/7158734/42278809-95230566-7fa4-11e8-828c-37510142f1ae.png)

**Comment by emperorhaplo** [comment]
Any updates?

**Comment by SD10** [comment]
@emperorhaplo Unfortunately no 😢 You're welcome to look into it though

**Comment by Dearich** [comment]
I have the same problem, any updates?

**Comment by emperorhaplo** [comment]
> I have the same problem, any updates?

Hey @Dearich, sorry I missed the message earlier. I haven't worked on this in a while, but I ended up writing my own table view to push messages since I couldn't fix the one above. This was 2 years ago though.
