### ISSUE TITLE
MessagesCollectionView bottom inset is below MessageInputBar in PageViewController with NavigationController's isTranslucent property set to false

### ISSUE THREAD

**Issue by korelhayrullah** [MessageKit/MessageKit#749]
Hi all, 
I am currently using MessageKit as my chat controller and I have a problem setting it. I am using the MessagesViewController inside a PageViewController allowing users to swipe through the chat. However, I have an issue, I cannot adjust the bottom contentInset for the messagesCollectionView since it frequently changes. I have looked for a solution for about 2 days and cannot figure out how to do. Apart from the PageViewController the MessagesViewController works as expected. The top inset is configurable but the bottom is not. Also, my navigationController's isTranslucent property is set to false and when I set it to true again it works as expected. I have checked the source code and nothing seems to be wrong, however, handleKeyboardDidChange func in MessagesViewController+Keyboard.swift doesn't seem the be called since it adjusts the bottom inset of the messagesCollectionView. Hope you can help me out. Maybe it is a silly question forgive me I am still developing myself. 

Bottom Inset Below MessageInputBar
![bottominsetwrong](https://user-images.githubusercontent.com/25662753/42178704-14462628-7e3a-11e8-81b4-90ea3954ad52.PNG)

Expected
![expected](https://user-images.githubusercontent.com/25662753/42178678-027dec96-7e3a-11e8-9950-6e416fd3672c.PNG)

**Comment by nathantannar4** [comment]
I have seen this in my own projects and it is due to the UIPageViewController which when improperly used can interfere with the automated content inset adjustment. The inset is determined by the frame.size of the `UIViewController` so make sure you are not placing your tabbar over the view but rather on top of the view. Does that make sense?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by korelhayrullah** [comment]
I am having difficulties understanding "so make sure you are not placing your tabbar over the view but rather on top of the view". Can you be more open? I am new on iOS :/

**Comment by nathantannar4** [comment]
When you layout your views. Don't have the tabbar overlapping the MessageViewController view 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by korelhayrullah** [comment]
I have checked all the conditions and there weren't any overlapping views causing the automated content inset adjustment to cause failure. I dug a little bit into the code and found that in `MessagesViewController+Keyboard.swift` in the function `handleKeyboardDidChangeState(_ notification:)` the `newBottomInset` value becomes negative. The `keyboardEndFrame.minY` is returning a higher value than the `view.frame.height` causing it to be negative and then the bottom inset to be set falsely. In my opinion, the `newBottomInset ` should be calculated as follows: `let newBottomInset = keyboardEndFrame.height - iPhoneXBottomInset` in which sets the bottom inset as expected regardless the situation I am using the `MessagesViewController`. I have tested it on different devices and it was working as expected. It may be revised. Besides that, the ability to add an intended bottom inset property can be added. Thank you for your replies, it really helped me out. 💃

**Comment by SD10** [comment]
@korelhayrullah I don't have much spare time to review this but thanks for conveying your issues. I'll take into consideration allowing users to have more control over the inset in case they need to override

**Comment by ranhsd** [comment]
I'm having the same issue when using adding MessagesViewController as child view controller. Don't know how to solve it...

**Comment by SD10** [comment]
How much off is the bottom inset for you @ranhsd? That would be a good place to help me start looking. This is one of the trickiest parts of the library. Unfortunately, the inset is working for my current company's view controller setup -- but I'm always looking to improve if I can

**Comment by ranhsd** [comment]
Hi @SD10 I open a new issue about it in #755 
The problem is that the MessageInputBar hides the collection view content and I cannot scroll to bottom and see the messages in there because it stuck
You can understand it from this image: 

![simulator screen shot - iphone 8 - 2018-07-09 at 19 41 05](https://user-images.githubusercontent.com/3685671/42463854-0f67c1fe-83b0-11e8-8fcc-e9a04608565a.png)

In this image I stretch the scroll in order to see the item at the bottom but I cannot normally scroll to it... In 0.13.5 it works for me

**Comment by nathantannar4** [comment]
I will look into fixing this as it seems many are using it as a child view controller

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
#755

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ranhsd** [comment]
Thanks @nathantannar4

**Comment by SD10** [comment]
Set `extendedLayoutIncludesOpaqueBars = false` in your controller

**Comment by SreekanthGudisi** [comment]
Hi similar problem here, 
[Look at issue](https://github.com/MessageKit/MessageKit/issues/870)
I'm not getting **MessageInputBar** could u help me anyone ?
