### ISSUE TITLE
Is Swift 4 supported?

### ISSUE THREAD

**Issue by ichikmarev** [MessageKit/MessageKit#750]
Dunno, but installing from pods to project with swift4 will cause some sort of errors. I wonder, is I miss smthing or Swift 4 support not on master right now?

![image](https://user-images.githubusercontent.com/19555744/42276472-884691c6-7f9c-11e8-8ed8-371ad289a777.png)

Also, don't want to insert others, but some deprecated methods

**Comment by gorbat-o** [comment]
Hello,

I am working with swift 4 and I don't have any problem like that.
Can you share your podfile configuration ?

**Comment by ichikmarev** [comment]
@gorbat-o 
<img width="659" alt="image" src="https://user-images.githubusercontent.com/19555744/42284297-c80a1464-7fb4-11e8-8571-6f90b3ab4653.png">

**Comment by SD10** [comment]
@ChikFTW Please make sure you are using the latest version of MessageKit. You may need to run the `pod update` command

**Comment by ichikmarev** [comment]
@SD10 Idk, it was weird, but I made 

```swift
pod update //dosnt helped
pod install 
pod update //it works now
```

Sorry, thank you for answers! <3
