### ISSUE TITLE
CollectionView scrolling problem when adding an image

### ISSUE THREAD

**Issue by MireilleKhalife** [MessageKit/MessageKit#751]
I have added a button to the left stackView, to add attachment (from camera or photo library). When the user chooses a photo I'm adding it to the messageList.
```swift
func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [String : Any]) {
        let chosenImage = info[UIImagePickerControllerEditedImage]
        let message = MockMessage(image: chosenImage as! UIImage, sender: currentSender(), messageId: "2", date: Date())
        self.messageList.append(message)
        self.messagesCollectionView.reloadData()
        messagesCollectionView.scrollToBottom()
        picker.dismiss(animated: true, completion: nil)
}
```
It is not scrolling to the bottom, the keyboard covers the last image (if the keyboard was dismissed when I add a photo, the inputBar covers the photo). So I can't scroll up the collectionView until I dismiss the keyboard then show it up.

<img width="388" alt="image hidden by messageinputbar" src="https://user-images.githubusercontent.com/36398390/42281519-6ebf35c2-7fac-11e8-939c-b30a036660f2.png">
Thank you

**Comment by nathantannar4** [comment]
Try calling `scrollToBottom` in the completion of the `picker.dismiss(...)`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MireilleKhalife** [comment]
@nathantannar4 I have tried it and it didn't work

**Comment by nathantannar4** [comment]
After further thought I think the insertion and `reloadData()` should be in the completion too. This is because when the `MessagesViewController` isn't the first responder the `inputAccessoryView` (`MessageInputBar`) isn't actually there; thus,  the bottom inset is calculated incorrectly.

Try
```
func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [String : Any]) {
        picker.dismiss(animated: true, completion: { _ in
                  guard let chosenImage = info[UIImagePickerControllerEditedImage] else {
                          // handle error
                          return
                  }
                  let message = MockMessage(image: chosenImage, sender: currentSender(), messageId: "2", date: Date())
                 self.messageList.append(message)
                 self.messagesCollectionView.insertSections([self.messageList.count - 1])
                 self.messagesCollectionView.scrollToBottom()
        })
}
```

**Comment by MireilleKhalife** [comment]
Did you mean ``` self.messagesCollectionView.insertSections([self.messageList.count - 1]) ``` instead of ``` self.messagesCollectionView.insertSections([self.messageList.count - 2]) ``` because it's taking the last message sent by the other user. 
And sadly it didn't work, the keyboard and the inputBar are still covering the last image.

**Comment by nathantannar4** [comment]
You might need to use `Dispatchqueue...waitAsync(...)` to add an extra delay then. If that doesn't work  it might be something else entirely

**Comment by SreeKu10** [comment]
Found a solution 
`override func viewWillAppear(_ animated: Bool) {`
`        let insets = UIEdgeInsets(top: 0, left: 0, bottom: messageInputBar.bounds.height, right: 0)`
`        self.messagesCollectionView.contentInset = insets`
`        self.messagesCollectionView.scrollToBottom()`
`}`

**Comment by MireilleKhalife** [comment]
Thank you a lot, works perfectly if the keyboard is hidden, if it's not it covers the image, so I dismissed it
```
override func viewWillAppear(_ animated: Bool) {
        self.messageInputBar.inputTextView.resignFirstResponder()
        let insets = UIEdgeInsets(top: 0, left: 0, bottom: messageInputBar.bounds.height, right: 0)
        self.messagesCollectionView.contentInset = insets
        self.messagesCollectionView.scrollToBottom()
    } 
```

**Comment by Teglgaard** [comment]
Hi I had the same problem, and have used your solution. I do not know why or how it works but it just does 💃 So I am happy. Thanks!
