### ISSUE TITLE
How to change display date format message?

### ISSUE THREAD

**Issue by sonysm** [MessageKit/MessageKit#753]
Dear all,
I want to change display message date formart 
example "Fri, 6 jully 2018, 8:80 AM"
the current date format is "Fri, 6 jul, 8:80 AM"

Thank you

**Comment by sonysm** [comment]
Thank you now I can change it.

**Comment by Jainesh219** [comment]
Hi @sonysm @nathantannar4 
 May I know the solution to change date format?
 
 Thank you
