### ISSUE TITLE
Swift 4 error pods 

### ISSUE THREAD

**Issue by reginaagst** [MessageKit/MessageKit#754]

**Comment by reginaagst** [comment]
Hi I uploaded the message kit podfile to my Xcode project and after the pod file is created when I open the new Xcode project work space when I build the project I receive allot of code errors . My question is there a new version of message kit I can down load to avoid errors . I also wanted to know when I am using message kit what do I import . Is it just Uikit . Or do I just need the sun class messageViewcontroller

**Comment by SD10** [comment]
Hey @reginaagst, it's kind of difficult to help you without having the error output. Can you paste the error messages in the body in the body of your issue?

Please check out this [getting started guide](https://github.com/MessageKit/MessageKit/blob/master/Documentation/QuickStart.md)

**Comment by reginaagst** [comment]
I'm getting error from all the pod files in at work I will have to upload files later tonight when I go home also my secound question when i put podfile into my Xcode project what do I do to import the messageKit . Or is it already imported .

**Comment by nathantannar4** [comment]
Try
```
pod repo update master
pod update
pod install
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by reginaagst** [comment]
<img width="1440" alt="screen shot 2018-07-09 at 8 35 05 pm" src="https://user-images.githubusercontent.com/38174510/42482940-9dca6d22-83b8-11e8-8ffe-2706b99bd515.png">
<img width="1391" alt="screen shot 2018-07-09 at 8 35 17 pm" src="https://user-images.githubusercontent.com/38174510/42482941-9dd657ea-83b8-11e8-9e6b-adb354fe4d6b.png">
<img width="1136" alt="screen shot 2018-07-09 at 8 35 39 pm" src="https://user-images.githubusercontent.com/38174510/42482942-9de4d522-83b8-11e8-864c-28979df01f92.png">
<img width="1133" alt="screen shot 2018-07-09 at 8 41 39 pm" src="https://user-images.githubusercontent.com/38174510/42482943-9df18eca-83b8-11e8-8c14-3892d9529726.png">

**Comment by reginaagst** [comment]
I created a pod file named test1
I opened terminal 
I put cd space bar I dragged and dropped the Xcode file into the terminal
I clicked return and typed in clear then one by one I put the lines of code to update message kit  pod files but I am still getting error.

**Comment by reginaagst** [comment]
<img width="1133" alt="screen shot 2018-07-09 at 8 41 39 pm" src="https://user-images.githubusercontent.com/38174510/42483042-2e10bc92-83b9-11e8-9838-9a55861369d4.png">
<img width="1395" alt="screen shot 2018-01-03 at 11 15 41 pm" src="https://user-images.githubusercontent.com/38174510/42483053-3a93dc74-83b9-11e8-8520-5d8c1e73035e.png">
<img width="1394" alt="screen shot 2017-12-28 at 9 19 17 pm" src="https://user-images.githubusercontent.com/38174510/42483074-6759ac7a-83b9-11e8-8f71-8a5f0d6c3959.png">

**Comment by reginaagst** [comment]
<img width="1133" alt="screen shot 2018-07-09 at 8 41 39 pm" src="https://user-images.githubusercontent.com/38174510/42483099-86585496-83b9-11e8-871e-506a56bb841a.png">
<img width="1136" alt="screen shot 2018-07-09 at 8 35 39 pm" src="https://user-images.githubusercontent.com/38174510/42483100-8a2c0cf2-83b9-11e8-976c-70194a709d5f.png">
<img width="1391" alt="screen shot 2018-07-09 at 8 35 17 pm" src="https://user-images.githubusercontent.com/38174510/42483113-97f3a174-83b9-11e8-817e-0bf8089bd1b9.png">

**Comment by nathantannar4** [comment]
We don't support iOS8

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by reginaagst** [comment]
What iOS do you support and how do I update it pod file

**Comment by reginaagst** [comment]
Is it possible for me to change version of pod file by writing code to pod file to download the pods

**Comment by nathantannar4** [comment]
@reginaagst Please stop closing and reopening. You have not been clear with your build environment. We only support iOS 9 or higher and Swift 4. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
I’m closing this issue as resolved. If you have any other questions, feel free to open a new issue, @reginaagst.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
