### ISSUE TITLE
Example Project NOT up to date with v1.0

### ISSUE THREAD

**Issue by nathantannar4** [MessageKit/MessageKit#760]
This is a PSA that our Example project is not updated for MessageKit v1.0, I am going to work on a more revised (and maybe advanced) Example project that will be shipped with v2.0

Will consider any example requests

**Comment by SD10** [comment]
@nathantannar4 Here are some things I have in mind:
- Make a nicer `MessageInputBar`, slimmer iMessage style, nicer button assets
- Maybe add an avatar image + user name to the header of a chat
- Take some screenshots using some nice royalty free images and put it on README 😊

**Comment by SD10** [comment]
cc @nathantannar4, I think we're up to date and can close this now?

**Comment by nathantannar4** [comment]
Yup we are up to date 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
