### ISSUE TITLE
`CellSizeCalculator` does not allow for `init()` to be overridden

### ISSUE THREAD

**Issue by nathantannar4** [MessageKit/MessageKit#763]
`CellSizeCalculator` was not given an explicit `public` initializer, thus it is not possible to subclass and add your own `init()` as it defaults to `internal` when an initializer is not given

**Comment by nathantannar4** [comment]
@SD10 is this intentional? In which case we require that developers only subclass `MessageSizeCalculator`

**Comment by SD10** [comment]
Nah @nathantannar4 this is definitely a bug. I'm always forgetting stuff like this
