### ISSUE TITLE
Replace MessageLabel with StyledTextKit

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#764]
### Reasoning

The [MessageLabel](https://github.com/MessageKit/MessageKit/blob/master/Sources/Views/MessageLabel.swift) class has accrued a large amount of tech debt since the beginning of this project. It's also a bottleneck for scroll performance. Text detection is done on the main thread and there is a ton of undefined behavior caused by trying to keep our `NSTextStorage` in sync with `UILabel`'s internal text storage object. 

### Proposal

Ideally, I'd like to make the migration to use [StyledTextKit](https://github.com/GitHawkApp/StyledTextKit) in the next major version of MessageKit -- pending https://github.com/GitHawkApp/StyledTextKit/issues/45

> ### Features of StyledTextKit
> - Declarative attributed string building API
> - Find text sizes on a background thread without sanitizer warnings
> - Cache rendered text bitmaps for improved performance
> - Custom attribute interaction handling (link taps, etc)

### Thoughts On Adding A 3rd Party Dependency

I'm sure some consumers of the MessageKit framework may have strong feelings against adding a 3rd party dependency, but I think the value here far outweighs the any associated cost. 

Fwiw, JSQMessagesViewController was planning on moving to [TTTAttributedLabel](https://github.com/TTTAttributedLabel/TTTAttributedLabel) in an upcoming version. We had also considered re-writing TTTAttributedLabel in Swift when starting this project. 

However, at this point, it just does not make sense to reinvent the wheel for something that StyledTextKit already does well

**Comment by nathantannar4** [comment]
💯

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zhongwuzw** [comment]
👍

**Comment by hyouuu** [comment]
Have we compared the alternatives e.g. https://github.com/malcommac/SwiftRichString? Wonder what do you see the pros & cons (StyledTextKit is pretty new - their first commit was Jan 2018)

**Comment by zhongwuzw** [comment]
The pros is it's a performance improvement.
The cons is, TBO, we lose the control of the text render, and also users need to learn the usage of third party. And what if user wants to substitute of their own text(Maybe we need to use protocol programming?)? Should we need to provide interface to the user?

**Comment by SD10** [comment]
@zhongwuzw that's a good idea, I'd definitely do heavy testing before adding a new API. we could possibly just type the view as any `UIView` or maybe add a protocol interface as you said 👍

**Comment by JulienKode** [comment]
@zhongwuzw Having a protocol for that part should be nice

**Comment by austinwright** [comment]
Is someone working on this or is there a WIP branch? Definitely interested in improving scroll performance and it would be nice to have framework support for performant, custom detection instead of having to detect & style text, and hook up gestures/ re-calculate touch locations manually.

If no one is working on this LMK and I could give it a shot.
