### ISSUE TITLE
No messages in collection view

### ISSUE THREAD

**Issue by iBolom** [MessageKit/MessageKit#77]
Hi,
when i return 0 in numberOfMessages delegate i get crash. So if i put to return 1 in this method then i get the crash in messageForItem because i access to empty array and it's tried to get first element message[1]. So i cannot handle case when i have no messages.

How can i fix this issue if i don't have any messages?

**Comment by SD10** [comment]
Hey @BojanAnox, I believe this has been fixed by #73 and will no longer be an issue in `v0.5.0`.
