### ISSUE TITLE
Add MessageCellDelegate method for didTapAccessoryView

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#770]
We need to add another delegate method that handles touches in the accessory view

**Comment by SD10** [comment]
@hyouuu Want to take a look at this? It's blocking the 1.1 release

**Comment by hyouuu** [comment]
Super busy lately - will work on it when get a chance!

**Comment by SD10** [comment]
@MessageKit/contributors This is a good issue for people looking to contribute, it's holding up the next release 😉

**Comment by nathantannar4** [comment]
Ill work on this. I added the delegate method but I think the layout of the accessory view should be tweaked. Currently we are setting it to the middle of the cell but I think we should be aligning it to the middle of the `MessageContainerView`

**Comment by SD10** [comment]
@nathantannar4 Thanks 🙏 I agree changing the alignment makes sense. We’ll have to review the layout and sizing logic if we make this change

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
Resolved!
