### ISSUE TITLE
How to share Videos, Photos & Location

### ISSUE THREAD

**Issue by ljs19923** [MessageKit/MessageKit#774]
Hi!
Im trying to allow to send videos, photos & location through my chat MessageKit, but i dont understand how i can do this... The code to send & play videos is present in message kit?
I would like to know if anyone understood how to do it and if you have an example ... urgent! Remuneration if necessary for the time spent.

Thanks :/

**Comment by ljs19923** [comment]
I want to create a button to the left of the textfield that opens an action sheet with the different options, send a photo, video, rental. Then you have to be able to send these data and read them in message kit. Is this code available?


![image](https://user-images.githubusercontent.com/5727223/43045024-05546d38-8db1-11e8-8a80-3a71bc56bef0.png)

**Comment by nathantannar4** [comment]
Hi @JulienLevallois in the Example is some code that shows you how to add buttons to the left and right of the bar. Then you just need to add actions to them. There is a well documented .MD file on how to use MessageInputBar. In MessageKit we do not support playing videos or presenting a photos other than the preview in the message bubble. If you want to add that do so in the MessageCellDelegate. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ljs19923** [comment]
Hi @nathantannar4 , and for example i will download images from my backend. So i will download image with async methods. In which delegate functions i need to implement my download process ? 
The logic of this project is not really easy.. Normally I understand all the source codes but there I really have trouble ...

**Comment by ljs19923** [comment]
Where is the delegate method cellForRow, collectionForItem, to edit the content and update images

**Comment by nathantannar4** [comment]
@JulienLevallois I'm sorry but you continue to be quite negative towards MessageKit. The architecture is sound, maybe just more advanced than what your used to. To continually raise issues while also criticising us, doesn't make us wanna help.

If you are looking for `cellForItem` I don't know how you can't find it, it's an `open` method so you can override it, get the super cell that we implement and if it's an image start the async loading. Easy.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
@JulienLevallois 
In terms of async hooks in MessageKit we have two:

This method can be used to configure the `AvatarView` asynchronously:
https://github.com/MessageKit/MessageKit/blob/18a2e58ec1378cad2d3e49e916747e57ff78118d/Sources/Protocols/MessagesDisplayDelegate.swift#L85

This method can be used to configure the image view for `Media` messages asynchronously:
https://github.com/MessageKit/MessageKit/blob/18a2e58ec1378cad2d3e49e916747e57ff78118d/Sources/Protocols/MessagesDisplayDelegate.swift#L162

**Comment by ljs19923** [comment]
Thanks @SD10 ! Do you knows one library on github to share/send photos, videos, location ? With actionsheet
