### ISSUE TITLE
Adding Buttons Below/Within Messages

### ISSUE THREAD

**Issue by svm1** [MessageKit/MessageKit#775]
Hi there! Thanks for the great work!
I'm a novice iOS dev with a small doubt more about something I am trying to do than an issue with the project - not sure if this the best place to post this but wasn't sure where else to ask. 

I want to add a set of buttons below/or inside certain messages (whichever is more doable!) in the place where the bottom text would be. However, I am not sure about how to go about doing this. I was just wondering what would be the best way to implement such a feature? I'm very new to iOS and am just looking for guidance as to where to get started with creating this.

**Comment by nathantannar4** [comment]
Hi @svmadiraju 

This is the right place to ask! To do this it sounds like you need to add a custom cell. Another user posted a how to in an issue about custom cells you could look at for reference. 

I am still working on a more revised example projects to show how to add a custom cell. 

What you will need to do is subclass the MessagesCollectionViewLayout and return a custom size calculator for the messages you want to have buttons with, as they will need to be bigger than default. 

Try first to add a basic custom cell and go from there. If your code is posted on GitHub I would be willing to help with any specifics. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by svm1** [comment]
Hey @nathantannar4 
Thanks for the response! I am trying to work with adding a custom cell, but am currently very confused. I will refer to the issue you mentioned and see how it should be done. Revised examples showing this would be great as well!

Also thanks for offering to help! If I am still stuck I will definitely reach out again.

**Comment by svm1** [comment]
Edit: Never mind, I figured it out. That really was a stupid question haha.

**Comment by SD10** [comment]
It's all good @svmadiraju. The only stupid question is the one that wasn't asked. We're glad you could resolve this issue, I'm going to close this for now 👍
