### ISSUE TITLE
messagesCollectionView contentInset bottom is not correct on devices < iPhone X

### ISSUE THREAD

**Issue by peihsendoyle** [MessageKit/MessageKit#777]
I catch up with this issue on all devices running iOS 10 & 11 (except iPhone X). There is a space between messagesCollectionView and messageInputBar.

 
<img width="424" alt="screen shot 2018-07-23 at 11 59 42 am" src="https://user-images.githubusercontent.com/7514128/43061976-7e57a404-8e81-11e8-953f-87faf5eb34ed.png">

**Comment by nathantannar4** [comment]
Yes we are aware of this issue and a PR is open to fix is. Closing as this is a duplicate. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
