### ISSUE TITLE
When I send photos, the scroll views does not fit the right size ...

### ISSUE THREAD

**Issue by ljs19923** [MessageKit/MessageKit#779]
When I send photos, the scroll views does not fit the right size ... Do you know why ?
But If i pop my vc and push again the reload the conversations with images its good

![image](https://user-images.githubusercontent.com/5727223/43072735-641340e4-8e77-11e8-93b0-1c8cdc9b6360.png)
![image](https://user-images.githubusercontent.com/5727223/43072738-67004bd0-8e77-11e8-9855-3ce127a5cdf4.png)
![image](https://user-images.githubusercontent.com/5727223/43072747-6e0cc3fe-8e77-11e8-9c14-fcae3e86d9a7.png)

**Comment by SD10** [comment]
Could be related to #777 #761 -- but sorry not sure

**Comment by ljs19923** [comment]
When I open the viewcontroller all this is displayed well but there is a scrolling problem when I send a photo. If I go back and I reopen, it is displayed even with the photo. Do not you know what I can do? On #761 there is no info

**Comment by nathantannar4** [comment]
It's because you are using a custom container controller and the offset is being calculated wrong. This was broken by an earlier PR we hope to fix it soon. There is a PR open to fix it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ljs19923** [comment]
Okay okay. Please let me know if you have news :/

**Comment by ljs19923** [comment]
Do you have news ?
Me thats works when the keyboard appear ect, but when i present a viewcontroller with self.presentVC, and then this VC disappear, i got the problem of display :/

**Comment by tflin** [comment]
We have the same problem on MessageKit 1.0.0. It does not exist on earlier beta versions. By the way, sending location message does not have this problem.

**Comment by tflin** [comment]
When displaying the system image picker, it takes the keyboard focus and the MessageInputBar will hide. Even if we didn't pick an image and none of the photo message was sent by tapping cancel of the image picker, the MessageInputBar will appear when the system image picker was gone. At that time, the last text message will be covered under the MessageInputBar like the above photo message. So it is related to the MessageInputBar not the photo message.

**Comment by nathantannar4** [comment]
@tflin it's not related to the `MessageInputBar`, only to the extent that it covers it up. When the bar isn't there then the bottom content inset calculations will be correct, but doing something with the bar isn't the issue. By the way if you need the `MessageInputBar` to reappear then you need to call `becomeFirstResponder` on the view controller

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tflin** [comment]
Maybe it is not related to MessageInputBar and a different problem. However, the insets calculation has some problems when MessageInputBar disappear/appear (MessageKit version 1.0.0).

My test is as following:
a. There are some text messages in MessagesViewController:
![image2](https://user-images.githubusercontent.com/12755752/43566855-77f3a19c-9662-11e8-86b4-4ddbc1bc92ce.png)

b. Open an ActionSheet and select the Photo Library which will open System's image Picker, at that time, the MessageInputBar will disappear as the ActionSheet and ImagerPicker will be the first responder:
![image3](https://user-images.githubusercontent.com/12755752/43566936-b88a76c2-9662-11e8-9615-9b06024d78fa.png)

c. Tap Cancel of the System's image picker, it will close. The MessagesViewController will automatically become the first responder and MessageInputBar will appear, but the last text message will be covered by MessageInputBar and you cannot scroll it up:
![image4](https://user-images.githubusercontent.com/12755752/43567080-2bc28986-9663-11e8-894b-4f50b4f89996.png)

**Comment by SD10** [comment]
Closing this because the bottom inset bug is already something being tracked

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ljs19923** [comment]
Hi @SD10 , why did you close this bug ? Where is the solution ? How can i do ?

**Comment by yakovlevmaksym** [comment]
@JulienLevallois I think you can track the status of this problem at issue:
https://github.com/MessageKit/MessageKit/issues/817
