### ISSUE TITLE
[Prerelease] v0.5.0 and Getting Out Of Prerelease Phase

### ISSUE THREAD

**Issue by SD10** [MessageKit/MessageKit#78]
Hey everyone 😅,
I've released **MessageKit** `v0.5.0`. You can download it via CocoaPods or take a look at the zip.

### Improvements
- Supports `NSAttributedString` for messages
- Adds `didSelectTopLabel` and `didSelectBottomLabel` delegate methods
- Allows user to adjust vertical position of `AvatarView` in cell relative to contents
- Adds data detector types of `Address`, `Phone Number`, `URL`, and `Date` to messages which also support tap handling

### Thanks to
@MacMeDan, @gungorbasa, @bojanstef for contributing on this release

### Getting out of the prerelease phase

Moving slowly has been very beneficial in making some key design decisions -- but this project cannot remain as a prerelease indefinitely.

**Pre-release phases will end by the September 1st and my goals for this would be a version `0.9.0`.**

### v0.6.0

 - [ ] Message container styling. ie) tailed bubbles, outlined bubbles, etc
 - [ ] Review API surrounding MessageHeaderView / MessageFooterView
 - [ ] Reviewing everything regarding xibs and cell reuse
 - [ ] Reviewing existing defaults
 - [ ] Consider date utilities for creating labels

### v0.7.0
- [x] Make MessageInputBar far more flexible and customizable

### v0.8.0
 - [ ] Support photo messages
 - [ ] Support video messages

### v0.9.0 - Last Prerelease

 - [ ] Performance Review
    - [ ] Attribute Caching
    - [ ] Improving layout invalidation context
 - [ ] Documentation

You can see the [full roadmap](https://github.com/MessageKit/MessageKit/issues/62) in the original issue.

## Contributing
Looking to get involved in the project? Come join us on at the [MessageKit Slack Channel](https://messagekit.slack.com/join/shared_invite/MjI4NzIzNzMyMzU0LTE1MDMwODIzMDUtYzllYzIyNTU4MA)

**Comment by hyouuu** [comment]
Thanks!!

**Comment by hyouuu** [comment]
Thanks for the hard work! Just want to add one thought as I just went through a pain myself: I promised a date to release an app but didn't make it on time, which made people really disappointed. Sep 1st seems pretty intense for the work load so I'd suggest make the date later -
 you could always exceed it ;)

**Comment by hyouuu** [comment]
Well... unsurprisingly "Pre-release phases will end by the September 1st" is false now :(

**Comment by SD10** [comment]
@hyouuu I don't think we're too far behind but having a deadline significantly helped increase focus. A few bugs set us back 😃

**Comment by hyouuu** [comment]
Good to hear! And 100% agree deadlines help focus 💃
