### ISSUE TITLE
Delete location/video message type by long press

### ISSUE THREAD

**Issue by ljs19923** [MessageKit/MessageKit#780]
Hi! I can delete photos & text messages by long press now, in fact i could copy and i added delete, but that dont works for location & videos... Its normal for Copy, but i want to delete message of location,videos type.

How i can do/enable that ? Thanks

**Comment by SD10** [comment]
@JulienLevallois We don't have a delete option on `MessagesCollectionView` by default. You'll have to override these two methods of `MessagesCollectionView`:

https://github.com/MessageKit/MessageKit/blob/18a2e58ec1378cad2d3e49e916747e57ff78118d/Sources/Controllers/MessagesViewController.swift#L258

https://github.com/MessageKit/MessageKit/blob/18a2e58ec1378cad2d3e49e916747e57ff78118d/Sources/Controllers/MessagesViewController.swift#L262

This question is a general iOS development question. It works the same way outside of MessageKit

**Comment by ljs19923** [comment]
Thanks @SD10

**Comment by ljs19923** [comment]
i did this but that dont works with location/video type... only text/photos messages
![image](https://user-images.githubusercontent.com/5727223/43133661-c0643fba-8f3f-11e8-966b-affda161e3f7.png)

**Comment by ljs19923** [comment]
So i updated the pod directly... to add locations & videos Copy/Delete
![image](https://user-images.githubusercontent.com/5727223/43136652-b8373e3c-8f49-11e8-831c-f75f5fab121c.png)

**Comment by tobitech** [comment]
I'm doing this and i get the delete to show but the action is not performing, only the copy one does...
