### ISSUE TITLE
MessageInputBar Bug

### ISSUE THREAD

**Issue by ghost** [MessageKit/MessageKit#781]
Hi, Provide solution for this bug screenshot is attached here,
Here MessageInputBar is gone upwords when showing controller 
ios version 11.4 and MessageKit Version 1.0.0

![simulator screen shot - iphone 8 - 2018-07-25 at 11 36 15](https://user-images.githubusercontent.com/39147630/43182426-fd88c41e-8ffe-11e8-9b7a-bc8325dd6fab.png)

![simulator screen shot - iphone 8 - 2018-07-25 at 11 31 00](https://user-images.githubusercontent.com/39147630/43182368-b95bc516-8ffe-11e8-8efd-46f59431eb82.png)

**Comment by SD10** [comment]
@nathantannar4 haven't we seen this before for some crazy reason?

**Comment by nathantannar4** [comment]
@ios3 I'm going to need more info than just a screenshot. Can you please provide the code for how you setup the MessageInputBar and the steps to reproduce

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
