### ISSUE TITLE
Initiating Cells

### ISSUE THREAD

**Issue by svm1** [MessageKit/MessageKit#783]
Hi there! I used the custom cells guide and  currently have the custom cells I want implemented. I just had a question about the initialization and usage of these cells. This might be a very basic doubt but I am really new to Swift so please excuse me!

Think it might make things easier to first show what's going on.

This is the `init` function for my custom message cell, `introBtns:`
<img width="723" alt="screen shot 2018-07-25 at 11 15 35 am" src="https://user-images.githubusercontent.com/9904305/43219791-243eed9c-8ffd-11e8-8f62-1a4635832851.png">

And this is where I create a message of the `introBtns` type, with its initializer:
<img width="606" alt="screen shot 2018-07-25 at 11 14 56 am" src="https://user-images.githubusercontent.com/9904305/43219770-16012dda-8ffd-11e8-93cb-3eddce19404d.png">

How do I use the "hello world" string passed in? When I print the value of `message.kind` in my custom cell class, I see it ouputs `followUpBtns(Optional("hello world")),` but how can I extract just the string itself?

I honestly feel that is a really dumb question but I don't understand where the arguments for the `self.init` function are defined and how I can modify them.

**Comment by nathantannar4** [comment]
```
switch message.kind {
case .introBtns(let text):
// Text=hello world
default:
// Handle non custom kinds
}
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by svm1** [comment]
Thank you!
