### ISSUE TITLE
  apply(_ layoutAttributes: UICollectionViewLayoutAttributes) not called when i load data from network

### ISSUE THREAD

**Issue by chunxige** [MessageKit/MessageKit#784]
- 0.13.5
- iphone SE 11.4，but not limit ， it happened on every iphone device sometimes
- Swift 4.0
 
```swift
        messageList.insert(contentsOf: immessages, at: 0)
        messagesCollectionView.reloadDataAndKeepOffset() 
```
![wechatimg1](https://user-images.githubusercontent.com/8032681/43236721-3965cc10-90b9-11e8-9f03-023ceef46aaa.jpeg)
when i scroll to the visible cell,it does not automatically call  the function ### apply(_ layoutAttributes: UICollectionViewLayoutAttributes)
so disordered layout 

-->

**Comment by nathantannar4** [comment]
Hi @chunxige, can you please be more specific? Did you make some custom changes to the function? Have you tried MessageKit 1.0?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chunxige** [comment]
no ,i use MessageKit 0.13.5，i try to update to MessageKit 1.0

**Comment by nathantannar4** [comment]
Are you using custom cells? What makes you think `apply` isn't being called? It seems to be laying out the avatar and labels 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
What kind of cell class type?

**Comment by chunxige** [comment]
no ,i use TextMessageCell,and i  print Log the in that function  ,i find when i scroll from last section postion to the top  postion,it dont trigger the function   ,and it use the last section's attributelayout as the top attributelayout

**Comment by chunxige** [comment]
<img width="1050" alt="2018-07-26 11 31 11" src="https://user-images.githubusercontent.com/8032681/43240077-6d654c6c-90c7-11e8-8408-bdfcf53adf6d.png">

**Comment by nathantannar4** [comment]
Are you saying it never prints anything? Because we cache layouts and so scrolling through cells after they have been layed out the first time might not trigger `apply`. @SD10 would know if this assumption is correct or not. But as I stated earlier, it is laying out the avatar and labels so the function is being called 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chunxige** [comment]
<img width="791" alt="2018-07-26 12 12 59" src="https://user-images.githubusercontent.com/8032681/43241313-470f75a0-90cd-11e8-9260-48edc0a85372.png">

i'm setting  disabeld the layout cache ,but it still happend ,and i find the solution : 
[https://stackoverflow.com/questions/23995544/ios-applylayoutattributes-does-not-get-called-for-some-of-the-cells](url)

and i refer to the MessageKit 1.0 , modified the code in  MessagesCollectionViewLayoutAttributes in the MessageKit 0.13.5, and  it works perfectly!
<img width="1015" alt="2018-07-26 12 17 12" src="https://user-images.githubusercontent.com/8032681/43241575-912f5398-90ce-11e8-8991-db4df9956c20.png">

**Comment by nathantannar4** [comment]
So just to clarify, the issue was you were using MessageKit 0.13.5?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chunxige** [comment]
yes  ,i am using MessageKit 0.13.5 now

**Comment by SD10** [comment]
Yeah we stopped caching in MessageKit 1.0 because it leads to unexpected behavior for the consumers of the framework. The old way of calculating equality of attributes was not good to say the least -- as you've fixed @chunxige 

If you think this is resolved now, let me know and we'll close this issue 👍

**Comment by chunxige** [comment]
yeah ,please close the issue
