### ISSUE TITLE
Using MessagesViewController as childViewController

### ISSUE THREAD

**Issue by BrenoVin** [MessageKit/MessageKit#785]
- What version of MessageKit are you using?
1.0

- What version of iOS are you running on?
11

- What version of Swift are you running on?
4

Hi, I'm trying to use the MessagesViewController in a container as a ChildViewController, but the MessagesInputBar always got hidden or something like this. I saw other issues talking about something which looks like my problem, but in the other issues the problem is with the size of the messageInputBar, in my case it never appears.
tks.

**Comment by nathantannar4** [comment]
You need to make the child view controller the first responder so the InputAccessoryView (MessageInputBar) will appear

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BrenoVin** [comment]
thanks @nathantannar4! 👊
