### ISSUE TITLE
How to change font size of message text?

### ISSUE THREAD

**Issue by rahulsunrays** [MessageKit/MessageKit#786]
Hi, I am stuck on how to change font size of message text displayed.

I am using pod 'MessageKit', '0.13.4' 
Latest ios 11.
Iphone8 emulator.

Please help me, I know its a silly question for u.

Thanks
Rahul

**Comment by nathantannar4** [comment]
You need that use an NSAttributedString for the MessageType

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rahulsunrays** [comment]
Hi Nathan, thank you for your response, there is no method to override in MessagesDisplayDelegate for fonts, I see methods for textcolor detectors. Can u please elaborate how can I use it?

**Comment by rahulsunrays** [comment]
oh I got it, I think u want me to use  init(attributedText: NSAttributedString, sender: Sender, messageId: String, date: Date) {
        self.init(data: .attributedText(attributedText), sender: sender, messageId: messageId, date: date)
	}

**Comment by SD10** [comment]
@rahulsunrays The `TextMessageSizeCalculator` object has a `messageFont` property
