### ISSUE TITLE
How to create a custom cell

### ISSUE THREAD

**Issue by robertoferraz** [MessageKit/MessageKit#788]
Hey guys, I have a question that is blocking me for quite a while. I've created a custom `MessageContentCell` with a Xib file, and I am trying to use it by setting the type of my message to `custom(Any?)`. Following the instructions on the file I need to implement these 2 methods:

```swift
///   - `collectionView(_:cellForItemAt indexPath: IndexPath) -> UICollectionViewCell`
///   - `cellSizeCalculatorForItem(at indexPath: IndexPath) -> CellSizeCalculator`
```

The first one `cellForItemAt:` goes without a problem, but the second one I don't really know where to put. I've created a subclass of the `MessageSizeCalculator` and tried to use in many parts of the viewController, but I am completely lost. 

Could someone instruct me?

- Version of MessageKit: 1.0.0
- Version of iOS: 11.4
- Version of Swift: 4.1

**Comment by svm1** [comment]
Hey there,
I very recently figured out how to make custom cells and have been working with them for a little bit. I simply followed the steps outlined in #686 (wildseansy's comment) and it worked like a charm. I suggest you try following that method, feel free to hit me up if you have trouble with it.

**Comment by robertoferraz** [comment]
Thanks a lot @svmadiraju I will try it and update the ticket right after

**Comment by robertoferraz** [comment]
Hey @svmadiraju  thanks a lot for the link, it works great!
