### ISSUE TITLE
InputTextView.parseForComponents() failed

### ISSUE THREAD

**Issue by tflin** [MessageKit/MessageKit#789]
- What version of MessageKit are you using?
1.0.0
- What version of iOS are you running on?
iOS 11.4.1
- Is the issue you're experiencing reproducable in the example app?
Yes

Type 1 character, return, paste 1 picture, type another character, return, and paste another picture in the example's inputTextView, such as:
A
Picture 1
B
Picture 2

And then tap the Send button, the example program will terminate.

**Comment by SD10** [comment]
cc @nathantannar4

**Comment by nathantannar4** [comment]
Yes this is an edge case

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
@SD10 I looked into this. @zhongwuzw changed the function for `parseForComponents()` in 

"Fix wrong seperated components in messageInputBar"
commit 05744ae80b066106588f33837895bb26736aecf0
Author: zhongwuzw <zhongwuzw@qq.com>
Date:   Mon Mar 19 16:46:54 2018 +0800

When I revert to using the original code I wrote this bug doesn't occur.

@zhongwuzw Do you remember why you made the changes?

**Comment by SD10** [comment]
@nathantannar4 That commit was to fix https://github.com/MessageKit/MessageKit/issues/569

**Comment by nathantannar4** [comment]
@SD10 ok, ill work on a fix that solves both

**Comment by nathantannar4** [comment]
This is fixed in the `development` branch, will be included in the next release
