### ISSUE TITLE
MessageKit Updates with Modified Pod Files

### ISSUE THREAD

**Issue by svm1** [MessageKit/MessageKit#790]
I have a general question about updating MessageKit. I've been using the library for a project, and some functions, like using custom cells and certain UI/appearance tweaks, required me to edit a number of the locked pod files. I have made many changes to a lot of these, most of which are appearance-related to fit the theme of my project, and only now realized that a MessageKit update would wipe all these custom changes. Is there anything I can do to avoid this while still getting the updated version when it is released, or will I have to reapply all my changes?

**Comment by nathantannar4** [comment]
You should fork MessageKit to your own repo and then make the edits there. That way you can sync up with our repo when we make updates. Then in your pod file, load MessageKit from your GitHub repo
