### ISSUE TITLE
Confusing Bug : Space at bottom of collectionView or Above of InputBarMenu

### ISSUE THREAD

**Issue by ProKashif** [MessageKit/MessageKit#792]
I'm using first time MessageKit and facing this space issue since 3 days.

Explanation:
 
![simulator screen shot - iphone 8 plus - 2018-08-02 at 12 16 26](https://user-images.githubusercontent.com/33416799/43568756-e806950c-964e-11e8-9d87-528d6dbf68a3.png)

When i try to open keyboard automatically add space at bottom of collectionView or Above of InputBarMenu i don't have idea what's going on. i have check all solutions but didn't get proper solution for this .

Thanks in Advance

**Comment by ProKashif** [comment]
when i press return from keyboard CollectionView Jerking and go to up and add space

**Comment by nathantannar4** [comment]
Sorry I think the language barrier is preventing me from understanding what your saying. I don't understand what the issue is, can you try and be more clear on what your doing? Also is this reproducible in the ChatExample app. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ProKashif** [comment]
OK, what I', trying to say is that when press return, new line is added inside input view but at the same time some space is added just below the last message, as visible in picture.

**Comment by SD10** [comment]
Very difficult to debug without an example app. It _could_ be related to the inset bug but I think this is more likely to be an error in your code. Are you subclassing `MessageInputBar`? Have you set `extendedLayoutIncludesOpaqueBars = false`?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ProKashif** [comment]
i have solved this issue. The issue was in my code (IQKeyboard) library was creating problem in my code Thanks for your help

**Comment by SD10** [comment]
Maybe we should add something to the [FAQs](https://github.com/MessageKit/MessageKit/blob/master/Documentation/FAQs.md) about using MessageKit + IQKeyboard. Many people run into this problem
