### ISSUE TITLE
Upgrade Guide

### ISSUE THREAD

**Issue by jjochen** [MessageKit/MessageKit#793]
Is there a guide what has to be done when upgrading to version 1.0?

(Alamofire is a nice [example](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Alamofire%204.0%20Migration%20Guide.md))

**Comment by SD10** [comment]
Hey @jjochen, no migration guide unfortunately. If anyone wants to make one that would be great 👍 We do keep a very robust CHANGELOG though 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kinoroy** [comment]
Closing since outdated.
