### ISSUE TITLE
Action popup on long message tap

### ISSUE THREAD

**Issue by ichikmarev** [MessageKit/MessageKit#797]
My question is pretty simple:
Is there any option to add additional actions for long tap on messages. Like 'Copy' on this screen
Or any others way to implement it?

![image](https://user-images.githubusercontent.com/19555744/43643040-8b60f6e6-9732-11e8-9c88-ac5a4cc2cef6.png)

**Comment by kpsdeveloper** [comment]
Same question for me, anyone please advise. Thanks
<img width="152" alt="screen shot 2018-08-10 at 3 55 43 pm" src="https://user-images.githubusercontent.com/14867309/43948749-e10d2546-9cb5-11e8-94fb-d1fa2252ab53.png">

**Comment by nathantannar4** [comment]
Yes it involves overriding the canPerformSelector of the collection view. If you check previous GitHub issues you will find one where this was discussed. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ichikmarev** [comment]
@nathantannar4 @kpsdeveloper found this thread: https://github.com/MessageKit/MessageKit/issues/706

This topic can be closed!
