### ISSUE TITLE
Dismissing keyboard using endEditing(true) also dismisses the inputBar

### ISSUE THREAD

**Issue by georgepedrosa** [MessageKit/MessageKit#798]
### General Information

My MessageViewController is embedded in a tab bar controller. I dismiss the keyboard when accessing the tab bar using endEditing(true). When I try to go back to the MessageViewController, the inputBar does not appear anymore.

MessageKit Version: 1.0.0

iOS Version(s): 11.0

Swift Version: 4.1

Devices/Simulators: iPhone 6, 8, X

Reproducible in ChatExample? (Yes/No): No

### What happened?

As described, my MessageViewController is embedded in a tab bar controller. I dismiss the keyboard when accessing the tab bar using endEditing(true). When I try to go back to the MessageViewController, the inputBar does not appear anymore.

This is shown in the sequence below:

![captura de tela 2018-08-03 as 15 07 56](https://user-images.githubusercontent.com/12752556/43659600-dd3d7e1c-9732-11e8-850c-283662c52e63.png)

![captura de tela 3](https://user-images.githubusercontent.com/12752556/43660697-23be3388-9736-11e8-9d85-9f9c2a9aa0c6.png)

![captura de tela 2018-08-03 as 15 08 24](https://user-images.githubusercontent.com/12752556/43659624-f3279dfc-9732-11e8-8ae9-d2a5bbd304b9.png)

I use the endEditing(true) inside the viewWillAppear method of the tab bar controller as such: 

override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.slideMenuController()?.mainViewController?.view.endEditing(true)
}

**Comment by nathantannar4** [comment]
You need to make your MessagesViewController the first responder again. 

Personally I wouldn't recommend forcefully resigning the first responder with `endEditing`. Use `resignFirstResponder`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
