### ISSUE TITLE
Question about how this pod recognizes and displays content of the message.

### ISSUE THREAD

**Issue by asaplee** [MessageKit/MessageKit#799]
Hi!
So sorry for what may seem like a very basic question for many of you more experienced developers on here- I am quite new to IOS development and Swift, and I was wondering... which delegate method allows this library to get the message text and display it? Also, since content isn't a required property of messageType, how do I handle implement this in a project? (ie, what do I name it, in which delegate method should I access the text)
Thanks so much :)

**Comment by SD10** [comment]
Hey @asaplee,
You may want to check out our [getting started guide](https://github.com/MessageKit/MessageKit/blob/master/Documentation/QuickStart.md)

**Comment by asaplee** [comment]
@SD10  Thanks for the advice. I have looked at it. Still- I am a bit confused on how to implement the content. I know there is a way to specify what kind of information each message contains- but not sure where to input the actual message content.
