### ISSUE TITLE
Question about a different UI

### ISSUE THREAD

**Issue by MervinFlores** [MessageKit/MessageKit#800]
Hi guys! thanks for this repo.

I got a question: its possible do this chats exactly with all layouts in this Pod? 
<img width="405" alt="screen shot 2018-08-08 at 7 28 03 pm" src="https://user-images.githubusercontent.com/25008671/43869637-89234f42-9b41-11e8-837b-cbf11235809a.png">

Hope that can help me. Thanks!

**Comment by nathantannar4** [comment]
Possible? Yes! but it would require some work on your side as all those cells are custom. A good way to start is by checking out how to make custom cells. There is another issue where it's outlined how to do this. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
