### ISSUE TITLE
Align bubbles on bottom

### ISSUE THREAD

**Issue by fotiDim** [MessageKit/MessageKit#801]
- What version of MessageKit are you using?
1.0.0
- What version of iOS are you running on?
11
- What version of Swift are you running on?
4.1
- What device(s) are you testing on? Are these simulators?
iPhone 6s
- Is the issue you're experiencing reproducable in the example app?
yes

It would be nice to be possible to align the message bubbles on the bottom of the screen instead of the top. Note that this issue only affects the alignment not the insertion of the new messages which should still happen in the bottom.

**Comment by brandon-haugen** [comment]
@fotiDim, sorry, I am having a bit of a hard time understanding what you mean by

> possible to align the message bubbles on the bottom of the screen instead of the top

Here is a screenshot of the ChatExample, do you think you could use this to help explain what you are looking to do?

<img width="545" alt="screen shot 2018-08-09 at 1 23 44 pm" src="https://user-images.githubusercontent.com/182728/43918089-b684e09a-9bd7-11e8-8b9b-4bab6c4b337b.png">

**Comment by fotiDim** [comment]
Instead of this: 
![align top](https://user-images.githubusercontent.com/2326415/43960045-03386a7c-9cb1-11e8-9f1c-34599f1c5618.png)

This:
![align bottom](https://user-images.githubusercontent.com/2326415/43960043-031a6fb8-9cb1-11e8-8c17-dfd8627cce06.png)

**Comment by SD10** [comment]
Ah, you mean reversing the order of messages in the collectionView. There’s no first class support in MessageKit for this, but you should be able to work something out. Let us know if you do!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fotiDim** [comment]
Not really. Order is still the same. It's just that they originate from the
bottom instead of the top. If you have any hints please let me know where
to start looking from.

**Comment by nathantannar4** [comment]
@fotiDim Originating from the bottom means reversing the order of the collection view datasource layout. Similar to what the Slack app does. You could try to do this with some clever `content.top` trickery

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by charvoa** [comment]
e
