### ISSUE TITLE
How to populate with php-mysql API with alamofire/swiftyJSON

### ISSUE THREAD

**Issue by bhorvinayak** [MessageKit/MessageKit#804]

**Comment by bhorvinayak** [comment]
Hi SD10,
Thank you so much for creating such a great pod
With Firebase, it works well but I am trying to use PHP-MySQL API into the chat view controller. Then how to pass data into Sender struct, MessageData and MessageType.I tried with Chatto library but in that library having some issue and jsqmessanger was deprecated.
Please guide me for the solving this issue.
If any documentation or reference available please let me know.

Thanks in advance.

**Comment by nathantannar4** [comment]
What's your MessageKit specific question? We cannot help with saving data models to your database. For them to work with MessageKit they need to conform to the `MessageType` protocol

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
