### ISSUE TITLE
Customization of input bar

### ISSUE THREAD

**Issue by asaplee** [MessageKit/MessageKit#805]
HI!
So sorry for what may be a basic question, but I am new to swift and was wondering if I could get a bit of advice on how to customize the input bar. Where should I start I’d say I want to change the shape or perhaps add a circular button instead of the current text button- is there any documentation on this currently? Should I create a new messageinputbar and make it conform to a protocol. Thanks so much- I’m super lost on this :)

**Comment by SD10** [comment]
Hey @asaplee, you can check our example app in the `Example` directory. This shows a couple different stylings of the `MessageInputBar`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
