### ISSUE TITLE
Question about sizing the messagesCollectionView

### ISSUE THREAD

**Issue by asaplee** [MessageKit/MessageKit#806]
Is there a method I can use to change the size of the messageCollectionView- I would like to add a UIView at the top of my view controller. Thanks!

**Comment by nathantannar4** [comment]
@asaplee You should add `MessagesViewController` as a child view controller to another and in that view controller add your UIView on top. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by asaplee** [comment]
Ah yes, thanks @nathantannar4 - I was able to do that. The problem I am experiencing now is that the messages go under the view. Is there a way I can set the scrollable view so that this doesn't happen
Thanks!!!

**Comment by nathantannar4** [comment]
You are I correctly setting the `MessagesViewController` view frame. Don't set it such that they overlap. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by asaplee** [comment]
Ah yes- it works. There's one last problem though, which is that for some reason my messageInput Bar disappears. I think this is because everything is being pushed down. But when I try to resize everything by doing messageInputBar.frame, to change its location, this doens't seem to work. Any thoughts? @nathantannar4?

**Comment by SD10** [comment]
@asaplee 

**Why doesn't the `MessageInputBar` appear in my controller?**

If you're using the `MessagesViewController` as a child view controller then
you have to call `becomeFirstResponder()` on your view controller. The
reason is because the `MessageInputBar` is the `inputAccessoryView` of the
`MessagesViewController`. This means that it is not in the view hierarchy of
`MessagesViewController`'s root view.

```Swift
class ParentVC: UIViewController {
    override func viewDidLoad() {
       super.viewDidLoad()
       let childVC = MessagesViewController()
       addChildViewController(childVC)
       self.view.addSubview(childVC.view)
       childVC.didMove(toParentViewController:self)
       self.becomeFirstResponder()
    }
}
```

**Comment by nathantannar4** [comment]
To add, it's actually better if you just set the InputAccessoryView of the ParentVC to the InputAccessoryView of the `MessageViewController`. Be sure to also override, canBecomeFirstResponder to true

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by asaplee** [comment]
Thanks for all the help! For some reason, setting the inputAccessoryView wasn't working. I did, however, find setContentInsets in an earlier issue. The problem, is however, in the image attached. I would not like for the messages to be visible while they are under the UIView. Thoughts on how to fix this? Thanks so much!
<img width="421" alt="screen shot 2018-08-11 at 1 11 29 am" src="https://user-images.githubusercontent.com/41351290/43989672-7f22b276-9d03-11e8-881b-1d557963491c.png">

**Comment by nathantannar4** [comment]
As I mentioned earlier, you are incorrectly setting frames. Layout the frames such the they do not overlap. You have to set the frame of the MessageViewController so it starts below your view. 


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
