### ISSUE TITLE
How to set unread message status?

### ISSUE THREAD

**Issue by evgzor** [MessageKit/MessageKit#807]
Could u please explain how to set read/unread message?

- version of MessageKit are you using : 1.0.0
- version of iOS are you running on: ios 11
-  version of Swift are you running on: Swift 4
- device(s) are you testing on? Are these simulators? : iOS simulator
- Is the issue you're experiencing reproducable in the example app?

**Comment by nathantannar4** [comment]
Use the footer text of a MessageCell (which we show how to set in the example) or implement a custom cell. When to set a message as seen/unseen is the trickier part but that you would have to implement client side. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
@evgzor In my app we use the footer text of the cell as @nathantannar4 has mentioned above. If we receive a notification that the message status has changed, we update the label. This is a very client specific issue

**Comment by tobitech** [comment]
@SD10 Please how do you add status to the MessageType... is there a way to create a Message model that would have "status" that can be used by the MessagesViewController datasource?

**Comment by nathantannar4** [comment]
You can use .custom

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
