### ISSUE TITLE
how can I add button in the message 

### ISSUE THREAD

**Issue by omarfoz** [MessageKit/MessageKit#811]
Hi,

how can I add button in the message if I want to do some action like to open a link

I know their method called "didTapMessage" but this will do action if I press to any other message 
If you could help me with that.

**Comment by svm1** [comment]
I don't think it's possible to directly add buttons within a text-based message, but I got around that by creating a custom message-cell type (see #686). You can add any kind of UIView elements to the `contentView` of the custom cell, including buttons.

Though if you just want this for clicking links, I think links are auto-highlighted and selectable in text-based messages.
