### ISSUE TITLE
Today/Tomorrow/Days of Week are cut off and underlined.

### ISSUE THREAD

**Issue by kennyshaw** [MessageKit/MessageKit#812]
Attaching photo below.
![img_3f386d843b88-1](https://user-images.githubusercontent.com/30164240/44062642-1d449360-9f12-11e8-826c-580c4cbf3189.jpeg)

When sending messages, the words "Today" "Tomorrow" and any day of the week (Monday, Tuesday etc) are cut off and underlined. In addition to that, if the word is used in a sentence, the last word is invisible. 

It seems this may be some "smart context" feature, where it captures you are talking about a date and underlines it to emphasize. Is that correct? If so, is there a way to turn off this feature?

**Comment by SD10** [comment]
Hey @kennyshaw, you can turn the detector types off using this method:

https://messagekit.github.io/Protocols/MessagesDisplayDelegate.html#/s:10MessageKit23MessagesDisplayDelegateP16enabledDetectorsSayAA12DetectorTypeOGAA0aI0_p3for_10Foundation9IndexPathV2atAA0C14CollectionViewC2intF

As for the font sizing, if you're not using `MessageKind.attributedText(NSAttributedString)`, you need to set the proper font size on `textMessageSizeCalculator` in `MessagesCollectionViewFlowLayout`

**Comment by kennyshaw** [comment]
Any reason as to why it is cutting off whole words if they are following the detected DetectorType or letters of that word if nothing follows? See "Sunda" (Sunday) from above, or "Tomorrow is         " (Tomorrow is weird).

**Comment by SD10** [comment]
@kennyshaw I'm going to close this one, we're tracking the cut off text in #816. Not sure what could be the issue though
