### ISSUE TITLE
Japanese Emoji are not displayed.

### ISSUE THREAD

**Issue by yokochi** [MessageKit/MessageKit#816]
For example. Enter the following.
Ꮚ˘̴͈́ꈊ˘̴͈̀Ꮚ⋆✩

![img_1076](https://user-images.githubusercontent.com/545241/44135450-1a23ec74-a0a4-11e8-99a7-01fa19322b90.jpg)

It not displayed from the middle.

I used [example app](https://github.com/MessageKit/MessageKit/tree/master/Example).

MessageKit Version
1.0.0

iOS Version
11.4.1

Swift Version
4.1.2

Device
iPhone X

**Comment by SD10** [comment]
@nathantannar4 Any idea on this one?

**Comment by nathantannar4** [comment]
No idea, can you try using `NSAttributedString`?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
I also see something similar in https://github.com/MessageKit/MessageKit/issues/812. Maybe 1.1 will resolve it. Not sure what's happening

**Comment by gungorbasa** [comment]
@SD10  It's totaly a weird issue. In `ConversationViewCOntroller.swift` Replacing;
```
let attributedText = NSAttributedString(string: text, attributes: [.font: UIFont.systemFont(ofSize: 18), .foregroundColor: UIColor.blue])
```

with 

```
let font = UIFont.systemFont(ofSize: 18)
let attributedText = NSAttributedString(string: text, attributes: [.font: UIFont(name: font.fontName, size: 18), .foregroundColor: UIColor.blue])
```

solves the issue. Also, I have tried with other fonts as well. It all works with `UIFont(name: font.fontName, size: 18)`

**Comment by kinoroy** [comment]
~~Closing since fixed by #1~~ Made a mistake, the PR is still living on a fork.

**Comment by gomfucius** [comment]
I confirmed https://github.com/yokochi/MessageKit/pull/1 does fix the issue. Maybe @yokochi can submit a PR?

**Comment by RomanPodymov** [comment]
> I confirmed [yokochi#1](https://github.com/yokochi/MessageKit/pull/1) does fix the issue. Maybe @yokochi can submit a PR?

Hello @gomfucius 
I did it in https://github.com/MessageKit/MessageKit/pull/1819, please check it.
