### ISSUE TITLE
Dismiss MessageInputBar?

### ISSUE THREAD

**Issue by svm1** [MessageKit/MessageKit#820]
Just a small question - I was wondering how to dismiss the MessageInputBar and have it reappear when desired. I saw that clicking the hand button in the top right that opens the UIAlertController causes the MessageInputBar to slide down and then back up once the menu is dismissed, how could I use/implement this sliding up/down myself?

**Comment by nathantannar4** [comment]
Call `resignFirstResponder()` 

Please always look at previous GitHub issues as this has been asked before. 

Cheers

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by svm1** [comment]
Hey, thanks for the response. I already tried that, but it doesn't seem to work. I'm trying to show a splash animation before loading the messages' view controller, and therefore want to hide the `MessageInputBar` until the animation is complete. 

I call the `resignFirstResponder()` but it seems to have no effect. I know this might be specific to my project, but do you have any ideas about why this might be happening?

**Comment by nathantannar4** [comment]
🤔 hmm, could be do to when you are calling it. In which function? As a fallback, you could also try overriding the `canBecomeFirstResponder` to false until your splash animation is done. For example,

```
var showSplashScreen: Bool = true

var canBecomeFirstResponder: Bool {
     return !showSplashScreen
}
```

Then when you have shown the splash screen, set it show to false and call `becomeFirstResponder` on the `UIViewController`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by svm1** [comment]
Thanks for the idea, pretty clever workaround! Unfortunately, it does not seem to work - now it successfully disappears but fails to reappear when called. Thanks though, don't wanna trouble you more with this. I'll keep messing around and update if anything works!

**Comment by nathantannar4** [comment]
Try calling becomeFirstResponder on the MessageInputBar or look into reloadInputViews on the view controller

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by experion-tibin** [comment]
> Try calling becomeFirstResponder on the MessageInputBar or look into reloadInputViews on the view controller
> 
> Sent with [GitHawk](http://githawk.com)

reloadInputViews works.Thanks!
