### ISSUE TITLE
How to add UITapGestureRecognizer for messagesCollectionView?

### ISSUE THREAD

**Issue by kmitj** [MessageKit/MessageKit#821]
after adding UITapGestureRecognizer for messagesCollectionView didTapMessage and didTapAvatar not working.  I need to handle tap in messagesCollectionView.

**Comment by nathantannar4** [comment]
Hey @michael-snow ,

Try setting the delegate of your new tap gesture to always allow for simultaneous gestures. 
https://developer.apple.com/documentation/uikit/touches_presses_and_gestures/coordinating_multiple_gesture_recognizers/allowing_the_simultaneous_recognition_of_multiple_gestures

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kmitj** [comment]
Thanks, it works.
