### ISSUE TITLE
MessageBox  HeaderView question 

### ISSUE THREAD

**Issue by topslave** [MessageKit/MessageKit#822]
I added chat functionality into the app I am building,  the chat part needs to have a top bar seperate with a few buttons. I can either implement this as a CollectionViewHeaderView or adding a top view to the chat app. If I add top UIView then I will need to re align the chat side. What would be the best way to do ? At this stage I can not use UINavigationBar because of the other features in the app.

Many thanks in advance

**Comment by SD10** [comment]
@CurItUK I would probably overlay a UIView on to of the `MessagesCollectionView` and then adjust the top inset of the collectionView to take into account the size of the header view

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by topslave** [comment]
Yes, 
I have done that way too,  worked like a charm. Many thanks.
