### ISSUE TITLE
images not shown after insertin a new message with an UIimage

### ISSUE THREAD

**Issue by kjoe07** [MessageKit/MessageKit#825]
im download a image to insert into the messages array and after the insert the image is not shown in the conversation.
```
self.downloadImage(at: url) { image in
	print("the image is \(image!)")
	//guard let `self` = self else { return }
	//guard let image = image else { return }
	let myMessage = message(sender: sender, messageId: id, sentDate: newDate, data: MessageData.photo(image!), body: "", senderName: sender.displayName, senderId: sender.id, recipientId: String(describing: recipientId), id: id, date: sentDate.description, delivered: delivered, sent: sent, attachment: AttachmentTypes(rawValue: attachmentType), selected: selected, imageURL: url.absoluteString, imagen: image!)
	//message.image = image
	if !(self.messages.contains(myMessage)){
		print("is not inside adding a new message \(myMessage)")
		self.insertNewMessage(myMessage)
	}
}
```
the console ouput is this 

> message(sender: MessageKit.Sender(id: "123", displayName: "Chab1"), messageId: "-LKRzmsc5vPBxeJdneNQ", sentDate: 2018-08-21 142:59:11 p. m. +0000, data: MessageKit.MessageData.photo(<UIImage: 0x1c04a4320> size {720, 1280} orientation 0 scale 1.000000), body: Optional(""), senderName: Optional("Chab1"), senderId: Optional("123"), recipientId: Optional("121"), id: Optional("-LKRzmsc5vPBxeJdneNQ"), date: Optional("1534863551851"), delivered: Optional(false), sent: Optional(true), attachment: Optional(roomatch.AttachmentTypes.IMAGE), selected: Optional(false), imageURL: Optional("https://firebasestorage.googleapis.com/v0/b/roomatch-209023.appspot.com/o/RooMatch%2FImage%2FIMG-20180816-WA0000.jpeg?alt=media&token=688f8d78-5419-4986-8b21-1e030a0b9da4"), imagen: Optional(<UIImage: 0x1c04a4320> size {720, 1280} orientation 0 scale 1.000000))
and the result shown in the conversation windows is this. 
![img_e1180](https://user-images.githubusercontent.com/3653060/44492741-977e9b80-a633-11e8-98ef-64757ed95a7b.JPG)
any idea what i'm missing to show the image. correctly.
```swift
 version  0.13.5
ios 11.4.1
swift 4.1
iphone 7 plus
```

**Comment by nathantannar4** [comment]
@kjoe07 How are you inserting the message? Are you reloading the collection view or inserting with batch updates ? 

Also, What `MessageKind` are you using for your `message.init`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kjoe07** [comment]
this is how i make the message `let myMessage = message(sender: sender, messageId: id, sentDate: newDate, data: MessageData.photo(imagen), body: "", senderName: sender.displayName, senderId: sender.id, recipientId: String(describing: recipientId), id: id, date: sentDate.description, delivered: delivered, sent: sent, attachment: AttachmentTypes(rawValue: attachmentType), selected: selected, imageURL: url.absoluteString, imagen: imagen)`
after the inser im reloading the collectionView.
`self.messages.sort()
self.messagesCollectionView.reloadData()`
