### ISSUE TITLE
Pods-ChatExample.debug.xcconfig

### ISSUE THREAD

**Issue by rjk79** [MessageKit/MessageKit#827]
Hi, I'm trying to build and run the current Example workspace, as is, but this Error is preventing it:
(I'm using Xcode 10.0, Swift 4, simulating on iPhone 8 Plus)

/Users/asdfghj/Downloads/MessageKit-master/Example/Pods/Target Support Files/Pods-ChatExample/Pods-ChatExample.debug.xcconfig: unable to open file (in target "ChatExample" in project "ChatExample") (in target 'ChatExample')

The issue in ChatExampleUITests also says there is "no such file".

I navigated around Terminal and it does show the file exists in that location.  I was wondering if maybe I'm setting it up wrong? (even though it seems straight forward)

**Comment by nathantannar4** [comment]
We recently updated the example, can you try running `pod install`?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rjk79** [comment]
Thank you for your swift response! I changed the Build Settings for Always Embed Swift Standard Libraries > Debug and Release to $(Inherited) and it worked.
