### ISSUE TITLE
JSQMESSagesViewController

### ISSUE THREAD

**Issue by reginaagst** [MessageKit/MessageKit#830]
Hi I am  trying to  create a message app using swift 4 , messageKit 9.0   my problem happened when I created a new file to put in my xcode project  called ChatViewController I used JSQMESSagesViewController as the subclass but when the file loads up I get allot of errors because of the sub class 
JSQMESSagesViewController. I tried to import message kit in this file but errors still did not go away my question is I'm assuming JSQMESSagesViewController subclass  
![screen shot 2018-08-29 at 12 35 27 am](https://user-images.githubusercontent.com/38174510/44789603-fd56b000-ab6a-11e8-92a6-49209b7360a4.png)
is deprecated and that messageKit is the replacement . I tried to substitute message kit I put under import uilit  after I imported message kit in to my file but I don't have the sub class of message kit. My question is how can I fix the errors . I am attaching an image so that you can see the errors I am getting any help will do thanks .

**Comment by brandon-haugen** [comment]
Hey @reginaagst, yes, the `JSQMessagesViewController` does not exist in *MessageKit* and it has been replaced with `MessagesViewController`. You might want to take a look at the Quickstart guide if you have not already, please find it [here](https://github.com/MessageKit/MessageKit/blob/master/Documentation/QuickStart.md#subclassing-messagesviewcontroller).

You should also make sure you have added MessageKit to your project, either through CocoaPods or Carthage (although I am not sure Carthage support is up yet, it is documented in the README). To see an example of including MessageKit via CocoaPods/Carthage, please take a look at the README section on [Installation](https://github.com/MessageKit/MessageKit#installation).

MessageKit also provides an example project that I found really helpful when I first started using MessageKit in a project. You can view it [here](https://github.com/MessageKit/MessageKit/tree/master/Example).

**Comment by reginaagst** [comment]
Thanks

**Comment by reginaagst** [comment]
hi I had another issue I was not able to open the example project is there any way I could open the example project? https://github.com/MessageKit/MessageKit/tree/master/Example

**Comment by nathantannar4** [comment]
@reginaagst run `pod install` in the example directory

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by reginaagst** [comment]
in the past when I would click on the example project from GitHub I was able to see th option to clone it and then open the Xcode project but when I click on the example project I sends me to another page and I donot see were I can view the example project in Xcode.
<img width="790" alt="screen shot 2018-08-31 at 7 20 35 pm" src="https://user-images.githubusercontent.com/38174510/44939447-4ff2c080-ad53-11e8-97d8-13b5c77a88cf.png">
![Uploading Screen Shot 2018-08-31 at 7.20.49 PM.png…]()
![Uploading Screen Shot 2018-08-31 at 7.20.56 PM.png…]()

**Comment by reginaagst** [comment]
im not sure on how to add the other entry to update the example

**Comment by nathantannar4** [comment]
Closing as you made a new issue already #836  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
