### ISSUE TITLE
ChatExample.xcodeproj 

### ISSUE THREAD

**Issue by reginaagst** [MessageKit/MessageKit#836]

**Comment by reginaagst** [comment]
Hi I wanted to use JSQMessagesViewController in my project which is a GitHub repository. the JSQMessagesViewController has been deprecated and MessadeKit is its replacement . I see an example Xcode project in the messageKit but I am not able to open the project my question is there a way I could open it. Here is the link https://github.com/MessageKit/MessageKit/tree/master/Example

The name of the example project is ChatExample.xco . normally I would click on the project and I would see the clone option and then I would be prompted to download zip file onto my computer but I am not seeing the option were I can download it.

**Comment by nathantannar4** [comment]
Run `pod install` and open the workspace file

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
Clone the repo or download it as a zip from https://github.com/MessageKit/MessageKit

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
