### ISSUE TITLE
ChatExample project main.storyboard

### ISSUE THREAD

**Issue by reginaagst** [MessageKit/MessageKit#838]

**Comment by reginaagst** [comment]
In the ChatExample project I do not see the main.storyboard file.  I am able to run the project and It works fine but when I take a look at the example files I notice main.storyboard file is missing . My other question is how is the project able to run with out the file being included?

**Comment by nathantannar4** [comment]
There are two ways to create views. Programmatically or with storyboards. Our approach is with the former. See the AppDelegate where we create the window programmatically

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by reginaagst** [comment]
Ok thanks
