### ISSUE TITLE
MessageLabel: How to set/change detector (.link) foreground colour?

### ISSUE THREAD

**Issue by ymisal** [MessageKit/MessageKit#840]
We have configured MessageKit 1.0.0 in Swift 4 running iOS 11.4.1.

So we need to change the only detected link foreground colour of MessageLabel text.
If you can help to change the colour of detected link will be appreciated. 

Thanks in advance!

**Comment by bejeri4** [comment]
in MessagesDisplayDelegate


`            func detectorAttributes(for detector: DetectorType, and message: MessageType, at indexPath: IndexPath) -> [NSAttributedString.Key: Any] {
         
        switch detector {
         
        case .hashtag, .mention: return [.foregroundColor: UIColor.blue]
         
        case .url: return [.foregroundColor: UIColor.red]
         
        default: return MessageLabel.defaultAttributes
         
        }
     
    }`
