### ISSUE TITLE
Issue in using Custom Collectionview cell within MessageViewController

### ISSUE THREAD

**Issue by benhas999** [MessageKit/MessageKit#844]
•	MessageKit Version:  1.0.0
        •	 iOS Version(s): All 
	•	Swift Version: Swift 4.1 
	•	Devices/Simulators: All 
	•	Reproducible in ChatExample? (Yes/No): Yes

I tried to implement custom cell by Extending UICollectionViewCell

issues i encountered is that
1* Bubble arrows missing on custom cell
2* CellSizeCalculator has no effect in Bubble width
3* No way to handle click on messages, did select delegate of collectionview has no effect
4* Did MessageContentCell extension method requires total reconstruction of all views.., or any other method to handle it..??

thanks for your concern in advance

![skype_picture](https://user-images.githubusercontent.com/30899497/45032456-7f653e00-b06f-11e8-85ee-a4b98b7ffc86.jpeg)

**Comment by nathantannar4** [comment]
@benhas999 You cannot simply subclass a `UICollectionViewCell` as it does not have the requirements to fit with the `MessagesCollectionViewLayout`. Please checkout the example project under the `development` branch to see how to use custom cells. #803 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by benhas999** [comment]
Thanks for your concern,


```
open override func layoutSubviews() {
        super.layoutSubviews()
        label.frame = contentView.bounds
      
    }
```

its the single function i think matters to resize the cell item in development code, it works.. but avatar and bubble with arrows are missing. hope you recognise the issue. is it needs additional refactorisation of elements or have any branch links.


my addition was

```
  open override func layoutSubviews() {
        super.layoutSubviews()
        collection_test.frame = CGRect(x: 0, y: 0, width: 80, height: 120)
    }

```


![skype_picture 1](https://user-images.githubusercontent.com/30899497/45073367-ae75c100-b0fc-11e8-8fae-4330deabb5f5.jpeg)

**Comment by nathantannar4** [comment]
>  it works.. but avatar and bubble with arrows are missing. hope you recognise the issue

Again @benhas999, this is not a MessageKit issue. There is no issue here that we need to fix. You still are not properly subclassing custom cells and that why there is no Avatar or bubble. Again, please look at the Example project in the `development` branch thoroughly. You should be able to answer most of your questions there. 

We cannot guide you through every question you have. Try to do your best to solve it first on your own.
