### ISSUE TITLE
need to create identifier in message kit

### ISSUE THREAD

**Issue by reginaagst** [MessageKit/MessageKit#845]

**Comment by reginaagst** [comment]
I followed along the example project so that I could assign a user identification to the users in my project  
I first create the messagedatasource in my chatViewcontroller file to create the identification for the user but I am getting error messages . when I try to pass on the unique id's in my other classes
<img width="980" alt="screen shot 2018-09-04 at 4 05 31 pm" src="https://user-images.githubusercontent.com/38174510/45055130-fba25600-b05c-11e8-83b2-29654575428f.png">
<img width="1329" alt="screen shot 2018-09-04 at 4 05 45 pm" src="https://user-images.githubusercontent.com/38174510/45055132-fba25600-b05c-11e8-9842-29d42668fe8d.png">

**Comment by reginaagst** [comment]
my question is how can I fix the error "Cannot assign to value: 'isFromCurrentSender' returns immutable value"?

**Comment by reginaagst** [comment]
her3e is the beginning of the code in my chatViewController project.
<img width="1153" alt="screen shot 2018-09-04 at 4 12 11 pm" src="https://user-images.githubusercontent.com/38174510/45055297-66539180-b05d-11e8-9a17-2b8a71eed67e.png">

**Comment by nathantannar4** [comment]
`isFromCurrentSender` is function, not a parameter

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by reginaagst** [comment]
isFromCurrentSender and currentSender are both functions I notice the parameters in the example projects we're not specified.

**Comment by reginaagst** [comment]
Both the  currentSender and isFromCurrentSender are throwing that error .

**Comment by brandon-haugen** [comment]
@reginaagst, to be clear, `currentSender` and `isFromCurrentSender` are not throwing errors, they are indicating that you have compile errors that prevent your project from building.

`MessagesViewController` does not have any property on it that allows you to specify who the current `Sender` is. In your `ChatViewController`, you need to determine how it is best to store the current `Sender` just like the Example for MessageKit does (the Example stores this in a `SampleData` class). You could just make a property on `ChatViewController` that you can set when segueing to it. Something as simple as

```Swift
class ChatViewController: {
   // other stuff

  var sender: Sender?

  // more stuff
}
```

could work depending on what your application is actually going to do.

Then in your implementation of `MessagesDataSource`s `currentSender()`, you would return your `sender` property. This will allow `isFromCurrentSender` to operate correctly.

Hopefully, this helps you get further along with MessageKit!
