### ISSUE TITLE
JSQMessagesBubbleImage replacement

### ISSUE THREAD

**Issue by reginaagst** [MessageKit/MessageKit#846]

**Comment by reginaagst** [comment]
is there a replacement for JSQMessagesBubbleImage on Messagekit

**Comment by reginaagst** [comment]
Also I wanted to know what a #selector is?

**Comment by SD10** [comment]
@reginaagst Please fill out the body of the issue template if you're going to ask a question on the MessageKit repository 😞 It takes a lot of time to answer people's questions and it's not very nice that we have to try and answer these with such little information

You can use the method of `MessagesDisplayDelegate` for this:
```Swift
    func messageStyle(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> MessageStyle {
        return .bubble
    }
```

> Also I wanted to know what a #selector is?

A selector is a reference to a function that is used to call that function at runtime. You can probably find a better explanation or an article on them from Google

**Comment by reginaagst** [comment]
Thanks also I not this in sample code what is selector?

**Comment by SD10** [comment]
@reginaagst See my comment above. Selectors are part of iOS/Swift development in general. Unfortunately, a better place to ask this question would be Google or StackOverflow -- we try to keep the MessageKit discussions to MessageKit related topics
