### ISSUE TITLE
how to get media detail on tap of image  like url , image n all ?

### ISSUE THREAD

**Issue by bandalrahul** [MessageKit/MessageKit#848]

**Comment by bandalrahul** [comment]
how i can access media or message on didSelectMessage?
if messageData.contains("location"){
showMapApps()
}

not fulfill requirement I am using MockMesage model

**Comment by samsidd** [comment]
i am facing the same issue, can't access the media of the message tapped

**Comment by SD10** [comment]
@bandalrahul There is a `MessageCellDelegate` for this
