### ISSUE TITLE
allow users to set view from start of messageContainer

### ISSUE THREAD

**Issue by shahid-rasheed** [MessageKit/MessageKit#849]
How can we add view at start of the message?

<img width="580" alt="screen shot 2018-09-05 at 11 24 33 am" src="https://user-images.githubusercontent.com/1671779/45080800-5f309000-b0fe-11e8-87aa-01bf61cc495e.png">

**Comment by SD10** [comment]
@shahid-rasheed Hey, I'm not sure I follow what you're trying to do here. Can you elaborate a bit more in greater detail?

**Comment by shahid-rasheed** [comment]
@SD10     
I'm wondering how can we display error view (send again view) when message fails to deliver?
There is an accessory view but my intention is  to use that for message forwarding.
        
Any view similar to accessory view just before the avatar view? 
e.g. the red error icon in the attached screen.

**Comment by shahid-rasheed** [comment]
@SD10 My apologies for bad explanation but is it clear to you?

**Comment by SD10** [comment]
@shahid-rasheed I would use the bottom label of the cell for this

**Comment by shahid-rasheed** [comment]
@SD10 thanks, I'll use the bottom label.
