### ISSUE TITLE
configureAvatarView not called

### ISSUE THREAD

**Issue by stasian23** [MessageKit/MessageKit#850]
Hi guys, i'm trying to hide avatars in my app, i setted the messagesDisplayDelegate,  and i'd love to have "configureAvatarView" function to be called, so i could do the logic there, but it's not beeing called. That is strange, because of func messageHeaderView function is beeing called. When i'm declaring the function, i get warning from the attached screenshot 
<img width="914" alt="screen shot 2018-09-06 at 16 57 21" src="https://user-images.githubusercontent.com/34062859/45162308-58854400-b1f6-11e8-95e9-c5ec104309b8.png">

**Comment by SD10** [comment]
Have you tried the fixit suggestion @stasian23?

**Comment by stasian23** [comment]
@SD10 sure, it just added private for the function, but it didn't start to be called

**Comment by brandon-haugen** [comment]
@stasian23 did you recently change the version of MessageKit that you are using? I believe I ran into something similar when upgrading from a version < 1.0 to a version > 1.0

The fixit suggestion that Xcode provides is just wrong in this case, it seems like Xcode is confused about the function signature and I suspect it is an issue with old build artifacts being left around.

Have you tried cleaning your project and rebuilding? Maybe even reinstall MessageKit pod if you are using cocoapods.

**Comment by stasian23** [comment]
@brandon-haugen, i'm using MessageKit 1.0, tried cleaning derived data and doing project clean

**Comment by brandon-haugen** [comment]
@stasian23 wow! I would have expected one of those to resolve the issue for you. I can't find any other issue with the snippet of code you have in the screenshot, it matches exactly what is in the project I work on that uses MessageKit.

```swift
func configureAvatarView(_ avatarView: AvatarView, for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView)
```

Is the project you are using MessageKit in configured to use Swift 4? Maybe conflicting Swift versions would cause this warning to be shown as well? You would probably have other issues though as well if this was the case I would imagine.

The last obvious thing I can think of, which you probably have tried already, is simply deleting the function declaration in your extension and try creating it again with auto complete.

**Comment by SD10** [comment]
I suspect you're using the wrong MessageKit version @stasian23 🤔 Are you using CocoaPods? Try running `pod update` and `pod install` again to make sure

**Comment by stasian23** [comment]
@brandon-haugen, thanks for the reply, project is configured for swift 4.1, and i don't have any other warnings.

@SD10, i tried to do it i removed MessageKit, did 'pod install' then cleaned project, and then installed MessageKit again, it didn't help at all

**Comment by nathantannar4** [comment]
Where are you setting the display delegate? Are you using custom cells? Have you overridden any function and not called super? Have you actually returned a message such that a cell needs to be rendered ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by calindru** [comment]
I experience the same issue.

**Comment by galblank** [comment]
same here

**Comment by galblank** [comment]
any luck @calindru ?

**Comment by skull8888888** [comment]
any progress?

**Comment by nathantannar4** [comment]
Those experiencing this please provide more context.   This isn't something we can reproduce on the example.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by skull8888888** [comment]
> Those experiencing this please provide more context. This isn't something we can reproduce on the example.
> 
> Sent with [GitHawk](http://githawk.com)

When I put delegate methods in the extension the warning appears and the default implementation with "?" is being called instead.

When I put delegate methods in the class the warning doesn't appear but still "?" is being called.

My project set for 4.2. I just added the 'MessageKit' and run 'pod install'

**Comment by skull8888888** [comment]
> Where are you setting the display delegate? Are you using custom cells? Have you overridden any function and not called super? Have you actually returned a message such that a cell needs to be rendered ?
> 
> Sent with [GitHawk](http://githawk.com)

Setting display delegate in the viewDidLoad, No, No, Yes, using the 'messageForItem'

**Comment by nathantannar4** [comment]
@skull8888888 the view controller you are extending, does it already have a predefined function for that? It seems as though you might have multiple definitions. Is your entire code for the controller sharable?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by skull8888888** [comment]
> @skull8888888 the view controller you are extending, does it already have a predefined function for that? It seems as though you might have multiple definitions. Is your entire code for the controller sharable?
> 
> Sent with [GitHawk](http://githawk.com)

`
class AGChatViewController: MessagesViewController {
    
    var messages: [Message] = []
    var member: Member!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.member = Member(name: "r", color: .red)
        
        
        self.messagesCollectionView.messagesDataSource = self
        self.messagesCollectionView.messagesLayoutDelegate = self
        self.messagesCollectionView.messagesDisplayDelegate = self
    
        self.messageInputBar.delegate = self
        self.messageInputBar.sendButton.setTitleColor(.primary, for: .normal)
        
    }
    
}
`

**Comment by skull8888888** [comment]
> @skull8888888 the view controller you are extending, does it already have a predefined function for that? It seems as though you might have multiple definitions. Is your entire code for the controller sharable?
> 
> Sent with [GitHawk](http://githawk.com)

No predefined functions, it is as simple as it is. Interesting thing, the warning appears only for configureAvatarView

**Comment by skull8888888** [comment]
@nathantannar4 seems that the problem is related to my project since when I created another test project with just MessageKit pod in it everything worked just fine. Any ideas what may be wrong with my project settings since at this point it is impossible to transfer all the files to the new one.

**Comment by skull8888888** [comment]
@stasian23 did you solve the problem?

**Comment by rnkyr** [comment]
ok, we faced today exactly the same issue. the thing is that we have`AvatarView` class in our project, so the one used in the method resolved to be ours

**Comment by toannd23** [comment]
I have the same issue in version 3.8.0. Did you solve the problem? @rnkyr

**Comment by rnkyr** [comment]
yes, I did resolve the problem by specifying the target from which to take AvatarView class. the problem was related to namespacing
As far as I recall you can just prefix `MessageKit.AvatarView` types in this delegate method
