### ISSUE TITLE
Other user's message goes to the right of the view

### ISSUE THREAD

**Issue by av8ramit** [MessageKit/MessageKit#851]
- What version of MessageKit are you using? 1.0.0
- What version of iOS are you running on? 11.4.1
- What version of Swift are you running on? 4
- What device(s) are you testing on? Are these simulators? iPhone 8+ emulator / real iPhone 7
- Is the issue you're experiencing reproducable in the example app? No

In some cases it can be really helpful to provide a short example of your code.
If so, please wrap these code blocks in backticks, like this:

I don't think my code snippet is the issue. But I can provide my overriding implementation of functions if need be.

For some reason sometimes a message where the bubble tail is to the left indicating it's a message from another user shows up at the right portion of the view as opposed to the expected left. It's also only consistently one message that is loaded as more messages are loaded by scrolling up.

![image](https://user-images.githubusercontent.com/5588272/45256884-8763fd00-b351-11e8-9982-6c72ede8054f.png)

**Comment by nathantannar4** [comment]
Hmm, try debugging your app by setting a break point in `isCurrentSender` method. If that is ever returning the wrong value that could be your issue

**Comment by av8ramit** [comment]
Thanks for the suggestion @nathantannar4. I tried that but it seems to be working fine. It's also weird because I figured if that were the method at fault, then the text color and bubble arrow would be on the wrong side too.

**Comment by DanishRehma** [comment]
I have used indexPath.section in messageForItem and it is working perfectly for me.

**Comment by chauhan130** [comment]
I still face this issue. I shall try to reproduce the steps and post my findings here once I get those.
