### ISSUE TITLE
How to set MessageStyle.bubbleOutline's outline width 

### ISSUE THREAD

**Issue by chiahsien** [MessageKit/MessageKit#852]
- What version of MessageKit are you using?
1.0.0
- What version of iOS are you running on?
iOS 10-12
- What version of Swift are you running on?
4.1

I set `MessageStyle` to `bubbleOutline` and the outline border is too thin for me. Is there any way to change it?

**Comment by chiahsien** [comment]
Never mind, my original goal is to make border clear. I can achieve this by darken border outline color.
But if there is way to customize outline width, please share with me!

**Comment by AlexeyShevchenko** [comment]
@chiahsien 
Try to override this func:
`func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize`
