### ISSUE TITLE
No function for inputTextView didBeginEditing()

### ISSUE THREAD

**Issue by AdamLee321** [MessageKit/MessageKit#853]
I have added a custom button to the messageInputBar, when the button is pressed a uiView slides up like the keyboard, however if the UIView is still visible when the keyboard slides up the view gets all messed up, hiding the UIView just before the keyboard appears would solve this issue however there seems to be no function for this.

Does anyone have a solution to this?

I am using the latest version of MessageKit and Swift4

**Comment by nathantannar4** [comment]
Use `NotificationCenter` and add an observer for the event `UITextViewDidBeginEditing`.

Alternatively, in MessageKit each `InputBarButtonItem` can be assigned actions for a variety of "hooks"

```
private var onTouchUpInsideAction: InputBarButtonItemAction?
    private var onKeyboardEditingBeginsAction: InputBarButtonItemAction?
    private var onKeyboardEditingEndsAction: InputBarButtonItemAction?
    private var onTextViewDidChangeAction: ((InputBarButtonItem, InputTextView) -> Void)?
    private var onSelectedAction: InputBarButtonItemAction?
    private var onDeselectedAction: InputBarButtonItemAction?
    private var onEnabledAction: InputBarButtonItemAction?
    private var onDisabledAction: InputBarButtonItemAction?
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
