### ISSUE TITLE
messagesCollectionView scroll delegate

### ISSUE THREAD

**Issue by shahid-rasheed** [MessageKit/MessageKit#857]
How I can observe the change in visible cells of message collection view.
I want to add 'scroll to bottom' button if user is away from the last X messages. 

Could you please expose the 'scrollViewDidEndDecelerating' method of scrollview or may be we should add the 'scrolls to bottom' button in the messagekit.

thanks.

**Comment by svm1** [comment]
MessagesCollectionView does indeed have a `scrollToBottom` method that scrolls to the bottom of the collection view to show the most recent messages. 

You could add a button to the `messageInputBar` that calls `messagesCollectionView.scrollToBottom()`on tap.

**Comment by shahid-rasheed** [comment]
MessagesCollectionView: how to detect when scrolling has stopped?

I want to add 'scrollToBottom' button only when user is away from the most recent messages.

Similar Question:
https://stackoverflow.com/questions/14868269/uicollectionview-how-to-detect-when-scrolling-has-stopped/44654947

**Comment by shahid-rasheed** [comment]
@svmadiraju Could we please add delegate methods for scrolling events.

**Comment by nathantannar4** [comment]
@shahid-rasheed `MessagesViewController` conforms to `UICollectionViewDelegateFlowLayout` which inherits from `UIScrollViewDelegate` so all the methods should be available
