### ISSUE TITLE
Can you create sample code  for action sheet too send messages

### ISSUE THREAD

**Issue by reginaagst** [MessageKit/MessageKit#858]

**Comment by reginaagst** [comment]
I understand the concept for sending the chat messages using MessageKIT but I am not able to implement chat in code .
I understand we need to create the user , date 
We need to have data source delegate and we need to create a bubble image which is set to zero but appears on screen when the user  selects the send option . My question is do you have a simple test code so that when I would write in text bar and select the send option I see the code show up  in the action sheet.

**Comment by svm1** [comment]
The Example project seems to be a perfect reference for what you're looking for - it allows you to type in the text field and see the message appear on screen in the collection view. Take a look at the Example project to see what's going on there. 

I saw your other questions as well and it seems that you're having a lot of issues with getting this to work. I know you already have previous code and you don't want to just toss that. but I highly recommend using the Example as a starting point for your own project, sort of like a boilerplate. Sometimes, at least in my experience, trying to merge from one framework to another makes for messier/more complicated code and more headaches and confusion than simply scraping the old project and starting fresh.

I myself originally used another messaging framework and was hesitant to start over from scratch with MessageKit when the former didn't satisfy my needs, but starting from the Example project as a baseline made it a lot easier than you'd think. It already has what you're asking for, working perfectly (typing messages -> appear on screen), so you just have to add your networking (which you can probably more or less take from your previous project) and whatnot and customize it a bit. 

I recommend you try that. Feel free to ask more questions, I'd be happy to help.

**Comment by reginaagst** [comment]
I do have a previous project that worked fine with JSQMESSagesViewController most of the code in JSQ was built in before it got deprecated. I took what you said and I tried to implement some of the code from  the example project into my  project but I  received allot of error messages indicating that xcode cannot identify some  of the code. My question is do I need to do a pod  install of the example projects pod file into my project.

**Comment by nathantannar4** [comment]
@reginaagst do not copy and paste your code from JSQ. There will be a lot of errors because MessageKit is JSQ. You need to take the time to look at the MessageKit example and rebuild what you currently have. We don't have the same properties and functions as JSQ so of course xcode can't identify it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
