### ISSUE TITLE
Height For Location syntax needed because the extension didn't conform.

### ISSUE THREAD

**Issue by lauriejhouse** [MessageKit/MessageKit#859]
- What version of MessageKit are you using? - .0.13.5
- What version of iOS are you running on? 11.4
- What version of Swift are you running on? 9.4.1
- What device(s) are you testing on? Are these simulators? Simulator: iPhone 8
- Is the issue you're experiencing reproducible in the example app? Not sure, I'm using another tutorial.

`
extension ChatViewController: MessagesLayoutDelegate {
    func heightForLocation(message: MessageType, at indexPath: IndexPath, with maxWidth: CGFloat, in messagesCollectionView: MessagesCollectionView) -> CGFloat {
        return
   }`

Trying to get a tutorial to work, and I'm running into an issue with my extensions. I'm wondering how to complete the height for location code?

**Comment by nathantannar4** [comment]
@lauriejhouse can you be more specific? You need to return a height from that function. I recommend using the latest version of MessageKit

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
Uhhhh it’s embarrassing because I don’t use location messages in my app. I don’t think that function is used anymore? The `LocationItem` protocol for the associated value of `MessageKind.location` handles the sizing I think 🤔 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
Yea it's not used in 1.0, use the size calculator instead. I can't remember if 0.13.5 still used it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
