### ISSUE TITLE
Build fails when implementing MessagesDisplayDelegate in Swift 3.4 project (Xcode 10 GM)

### ISSUE THREAD

**Issue by KevinQuisquater** [MessageKit/MessageKit#861]
Hi all,

I am using MessageKit (version: 1.0.0), installed with CocoaPods, in a mixed Objective-C/Swift 3 app, using Xcode 10 GM.

I added the recommended snipped to the Podfile to make sure MessageKit works with Swift 3 (_config.build_settings['SWIFT_VERSION'] = '4.0'_). All files using MessageKit are written in Swift. In the build settings, Swift language version is set to Swift 3.

Everything works fine until I implement the MessagesDisplayDelegate. The build fails with the following error:

> Type 'MyViewController' cannot conform to protocol 'MessagesDisplayDelegate' (compiled with Swift 4.1.50) because it has requirements that could not be loaded in Swift 3.4

Has anyone encountered a similar issue?

Thank you,
Kevin

**Comment by KevinQuisquater** [comment]
**Update**: I could not find a fix, and upgraded my entire project and pods to 4.2 (and then manually edited MessageKit's files to support Swift 4.2).

However, if anyone knows how I could have solved that issue without upgrading, I would be very interested to learn about that.

Thanks for reading
Kevin

**Comment by SD10** [comment]
@KevinQuisquater I don't support anything below Swift 4 for MessageKit. We're a little behind on updating to Swift 4.2 but that's the goal

**Comment by KevinQuisquater** [comment]
Makes complete sense. Thanks for taking the time to answer, Steven.
