### ISSUE TITLE
Add support another X devices

### ISSUE THREAD

**Issue by yauhenipakala** [MessageKit/MessageKit#866]
Hi everyone!

Look at this:
https://github.com/MessageKit/MessageKit/blob/6374b87992447e203eb313fafc3c6d56722e4f62/Sources/Controllers/MessagesViewController%2BKeyboard.swift#L96-L98

New iPhone X devices have another display height:

iPhone XR - 1792px
iPhone XS Max - 2688px

For fix, look at this: https://stackoverflow.com/a/47067296

**Comment by SD10** [comment]
@nathantannar4 More device bounds logic to haunt us :trollface:

**Comment by austinwright** [comment]
Is this still a bug? I believe `iPhoneXBottomInset` was removed (in 2.0.0 ?).

**Comment by nathantannar4** [comment]
I don't think it is

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gwynantj** [comment]
This was fixed in: https://github.com/MessageKit/MessageKit/pull/787
