### ISSUE TITLE
Sticky header for dates

### ISSUE THREAD

**Issue by ghost** [MessageKit/MessageKit#868]
Hello,

I use this library, it's an amazing one congrats

I want to know if it's possible to add a sticky headers for dates like slack on a web browser ?
I also want to know if I can custom completly the design ? 

Thanks for you help,
Have a good day

**Comment by hoeness2** [comment]
+1

**Comment by hoeness2** [comment]
Hello,

if i call this
```
let layout = messagesCollectionView.collectionViewLayout as? MessagesCollectionViewFlowLayout
layout?.sectionHeadersPinToVisibleBounds = true
```
it will first displayed but not as sticky and on scrolling up it will after few items crash

**Comment by ghost** [comment]
@hoeness2  Thanks for your help I'll try

**Comment by hoeness2** [comment]
Got it working
You need to make some change in the source code of MessageKit.

1. You need to edit MessagesCollectionViewFlowLayout.swift and comment out the function "shouldInvalidateLayout" this function blocks the sticky header to be working.
2. You need to convert your CollectionSource data in section holds messages for same day not section holds one message by default.

To see a working example i have uploaded the edited MessageKit example project to dropbox for you so you can download and see the changes that i have made.

It has the exactly whatsapp message group sorting algorithm that i have researched over weeks.

Cheers

https://www.dropbox.com/s/c7g6cx18rqk4vi9/MessageKit-master.zip?dl=0

**Comment by tobitech** [comment]
@hoeness2 please can you point out where you made the changes?

**Comment by hoeness2** [comment]
Which changes do you mean ?
Do you mean Messagekit changes or for the Example project changes ?

**Comment by tobitech** [comment]
@hoeness2 i'm talking about the MessagesCollectionViewFlowLayout.swift changes

**Comment by hoeness2** [comment]
You need to comment out the function shouldInvalidateLayout completely and that’s it. They are no more changes made in the MessageKit module.

**Comment by tobitech** [comment]
Thanks, it worked fine. Thanks for the source code you shared as well, it helped me implement the grouping of messages

**Comment by tobitech** [comment]
@hoeness2 i used your code for grouping messages, somehow, the header only shows for one section while `groupedMessageList.count` returns more than one in `numberOfSections`.

**Comment by jayjac** [comment]
This solution used to work, but now it seems like it is impossible to have sticky section headers anymore (using MessageKit 3.0.0)
Is there a new way to stick section headers like WhatsApp does ?
As it stands, sectionHeadersPinToVisibleBounds = true seems to be "confusing" the collectionView :
the header that is visible when the collection view first appears will be displayed close to the top bound. But then when the user scrolls, all the headers will scroll like all the other cells. And that initial top header will scroll but remains misplaced.

![simulatorrecording](https://user-images.githubusercontent.com/13017301/59612449-653bae80-911d-11e9-939c-ef6b15043c56.gif)

**Comment by Devinsomnia** [comment]
@hoeness2 Can you update the link of the sample project?
