### ISSUE TITLE
MessageCollectionView : Reload only bottom label 

### ISSUE THREAD

**Issue by shahid-rasheed** [MessageKit/MessageKit#872]
Is there a way to reload only bottom label in message collection view?

Consider below operations are being executed in real time without any delay. 
The other user is live and there is no network latency. 

messagesCollectionView.insertSections([messageList.count - 1]) // message created
messagesCollectionView.reloadSections([row]) // sent
messagesCollectionView.reloadSections([row]) // delivered 
messagesCollectionView.reloadSections([row]) // read

reloadSections loads the message cell completely and I can see the flickering. consider  attachment.

Sorry are we using supplementary views for top & bottom label?

Something similar.
https://stackoverflow.com/questions/26998761/uicollectionview-is-there-a-way-to-reload-only-the-supplementary-views

![flickering](https://user-images.githubusercontent.com/1671779/45747392-68495300-bc0e-11e8-84c8-ef4f624fc481.gif)

**Comment by SD10** [comment]
@shahid-rasheed You could try changing the text of the label without reloading it if you want to avoid that slight flicker -- but the short answer is no. The label is part of the cell so the entire cell needs to be reloaded

**Comment by tflin** [comment]
It is a very common problem that MessageKit users have. Previously I had also reported this issue on https://github.com/MessageKit/MessageKit/issues/474
Hopefully @SD10 or other core team members can give us a standard solution for this issue. Thanks.

**Comment by nathantannar4** [comment]
@tflin @shahid-rasheed Why not just reload the index path without animation? Its just a `UICollectionView` so there are many methods to reload data, 
https://stackoverflow.com/questions/14094684/avoid-animation-of-uicollectionview-after-reloaditemsatindexpaths
