### ISSUE TITLE
Showing default inputView before custom

### ISSUE THREAD

**Issue by ichikmarev** [MessageKit/MessageKit#875]
Then controller is opening, first is default inputView appears, then custom, which was set in viewDidLoad method. How to do it right way, cause it show weird animation?

https://gph.is/2Nvf8XZ

**Comment by nathantannar4** [comment]
You should override the `inputAccessoryView: UIView` property of your subclassed view controller

**Comment by ichikmarev** [comment]
> You should override the `inputAccessoryView: UIView` property of your subclassed view controller

is missing something but got "Cannot override with a stored property 'inputAccessoryView'" - error

**Comment by nathantannar4** [comment]
Can you show me your code? I don't understand what your doing. You shouldn't be overriding the `MessageInputBar`, but the `InputAccessoryView` which is a `get` property only. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ichikmarev** [comment]
> Can you show me your code? I don't understand what your doing. You shouldn't be overriding the `MessageInputBar`, but the `InputAccessoryView` which is a `get` property only.
> 
> Sent with [GitHawk](http://githawk.com)

Ye, didn't get you answer. Here is my code:

`{ DispatchQueue.main.async {

            self.messageInputBar.isTranslucent = false
            self.messageInputBar.backgroundView.backgroundColor = .white
            self.messageInputBar.separatorLine.isHidden = false
            self.messageInputBar.inputTextView.backgroundColor = UIColor.clear
            self.messageInputBar.inputTextView.layer.borderWidth = 1
            self.messageInputBar.inputTextView.layer.cornerRadius = 15

            self.messageInputBar.inputTextView.placeholderTextColor = UIColor(red: 0.6, green: 0.6, blue: 0.6, alpha: 1)
            self.messageInputBar.inputTextView.placeholder = "Message"
            self.messageInputBar.inputTextView.layer.masksToBounds = true
            self.messageInputBar.inputTextView.scrollIndicatorInsets = UIEdgeInsets(top: 8, left: 0, bottom: 8, right: 0)
            self.messageInputBar.textViewPadding.left = 12

            self.messageInputBar.setLeftStackViewWidthConstant(to: 12, animated: true)
            let tmp = InputBarButtonItem.init()

            tmp.image = #imageLiteral(resourceName: "attachment")
            tmp.backgroundColor = .clear
            tmp.title = nil

            tmp.contentEdgeInsets = UIEdgeInsets(top: 2, left: 2, bottom: 2, right: 2)
            tmp.setSize(CGSize(width: 36, height: 36), animated: true)
            tmp.imageView?.layer.cornerRadius = 16
            tmp.backgroundColor = .white
            tmp.tintColor = .white

            tmp.contentHorizontalAlignment = .center
            self.messageInputBar.setStackViewItems([own], forStack: .left, animated: true)
        }
    }`

**Comment by nathantannar4** [comment]
1) don't place it in an asynchronous block. 
2) don't animate the changes, set animated to false

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ichikmarev** [comment]
> 1. don't place it in an asynchronous block.
> 2. don't animate the changes, set animated to false
> 
> Sent with [GitHawk](http://githawk.com)

After this, this glitch with weird setup of inputTextBar is still here

**Comment by nathantannar4** [comment]
Again, please show your code. Otherwise it's quite hard to help find where the mistake was made.  Are you using any custom containers?

Have you looked at the example? I show how to change the style and the glitch doesn't happen 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ichikmarev** [comment]
Closing the for now.
The problem was in messageInput bar setup method. Need to call setStackViewItems right before buttons setup.
