### ISSUE TITLE
Choppy scroll on iPhone 6

### ISSUE THREAD

**Issue by binloan** [MessageKit/MessageKit#876]
I do have the same issue as @guarland. I reference his issue [#810](https://github.com/MessageKit/MessageKit/issues/810).

However I have more in depth information and I can reproduce the issue. It seems to be a problem inside the label sizing of MessageKit. See the attached image for some profiler information:

<img width="1277" alt="profiler" src="https://user-images.githubusercontent.com/2640637/45932058-15a5c900-bf77-11e8-8a8f-9eaf97319336.png">

You can reproduce the issue with the example project by deleting or zeroing both of the below values in the `MessagesLayoutDelegate`

```swift
func messageTopLabelHeight(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> CGFloat {
 return 16 //16 is smooth scrolling. Setting both to 0 results in choppy scrolling.
}
    
func messageBottomLabelHeight(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> CGFloat {
 return 16 //16 is smooth scrolling. Setting both to 0 results in choppy scrolling.
}
```

Obviously showing both top and bottom labels all time is not really nice. So a way to hide them selectivly without creating this lag would be much appreciated.

**Comment by nathantannar4** [comment]
@binloan Are you using the attributed string message type? I believe it should have a bit better performance

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by binloan** [comment]
@nathantannar4 I did try that, but I did not change anything related to performance. As said, the moment one of both is bigger than zero for each bubble, performance is good. However if one bubble should show "none" of both e.g. setting both to a height of 0, it starts lagging.

**Comment by nathantannar4** [comment]
Try setting to` .leastNonZeroValue`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
@binloan What version of MessageKit?

**Comment by binloan** [comment]
@nathantannar4 setting it to `.leastNonzeroMagnitude` does still create choppy scrolling.

@SD10 I'm using Carthage without any version restriction so the latest commit which is available to Carthage. Last build was two days ago.

Does it help if I attach the Instruments `.trace` file which I collected?

**Comment by SD10** [comment]
> Does it help if I attach the Instruments .trace file which I collected?

@binloan Not really, there's nothing that I see that strikes me as odd. The `setTextStroage(shouldParse:)` method will always be a heavy operation. Try turning off/limiting the data detector types you use. It's really easy to make `UICollectionView` perform badly so there could be so many things causing this -- both in MessageKit and your code

**Comment by binloan** [comment]
Okay so I think I got it tracked down.

What happened was in the `configureAvatarView(_:)` delegate method I defined the avatar like the following:

```swift
func configureAvatarView(_ avatarView: AvatarView, for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) {
 if let msg = chat.get(messageFor: message){
  avatarView.image = msg.sentBy.image
  avatarView.initials = initialsFromString(string: msg.sentBy.name)
 }
}
```

As you can see I set the image as well as the initials, not knowing that setting the initials will basically create an image based on the string (inside MessageKit). This led to a huge effort while scrolling since each chat bubble currently still has its own avatar view. Result was the choppy scrolling. I'll close this bug. However as an enhancement this might be pointed out clearer in either the examples or the docs. Thanks @nathantannar4 @SD10 for your help.
