### ISSUE TITLE
MessageKit not compiling under Swift 4.2

### ISSUE THREAD

**Issue by jdriselvato** [MessageKit/MessageKit#878]
- What version of MessageKit are you using? 1.0.0
- What version of iOS are you running on? 12.0
- What version of Swift are you running on? 4.2
- What device(s) are you testing on? Are these simulators? Both
- Is the issue you're experiencing reproducable in the example app? Yes

**Comment by ludoded** [comment]
This is a temporal workaround I'm using in my Podfile

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "MessageKit"
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end 
    end
end
```

**Comment by SD10** [comment]
Yeah, still no Swift 4.2 support. I haven't had time to even finish a 2.0 release, to be honest. Things at work have not been stable for a couple months

**Comment by nathantannar4** [comment]
I will work on a 4.2 update 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lauriejhouse** [comment]
> This is a temporal workaround I'm using in my Podfile
> 
> ```
> post_install do |installer|
>     installer.pods_project.targets.each do |target|
>         if target.name == "MessageKit"
>             target.build_configurations.each do |config|
>                 config.build_settings['SWIFT_VERSION'] = '4.0'
>             end
>         end 
>     end
> end
> ```

Do you put this after the `pod firebase` or whatever pods you're using? or before.

**Comment by ludoded** [comment]
> Do you put this after the `pod firebase` or whatever pods you're using? or before.

Put this snippet in the end of your pod file, after you define pods for your project.

**Comment by talanov** [comment]
https://github.com/MessageKit/MessageKit/pull/883

**Comment by nathantannar4** [comment]
Use the `development` branch for now, 1.1 release onwards will be on Swift 4.2
