### ISSUE TITLE
MessageFooter settings in example

### ISSUE THREAD

**Issue by fmarco1** [MessageKit/MessageKit#882]
- What version of MessageKit are you using? 1.0.0
- What version of iOS are you running on? 11
- What version of Swift are you running on? 4
- What device(s) are you testing on? Are these simulators? Simulator
- Is the issue you're experiencing reproducible in the example app? Yes

Hi,
[](url)
In issue #807 , @nathantannar4 refers to an example of a footer in the example code. However, I cannot seem to find this in the example at all - either in the code or when executed. I just see bottom and top labels. Can anyone point me in the right direction to find the footers in the example?

Thanks!

**Comment by nathantannar4** [comment]
It's on the `development` branch

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
@fmarco1 I don't show how to implement this feature as it is largely client based, I said that to do so you could use the footer label

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
