### ISSUE TITLE
Messages are going to down and MessageInputBar showing to all Child ViewControllers

### ISSUE THREAD

**Issue by SreekanthGudisi** [MessageKit/MessageKit#884]
- Latest MessageKit
- iOS 10
- Swift 4.1?
- iPhone 8 on simulator
- Using MessageKit Example code

Messages are going to down .. How can i get rid of going down  those messages ? Please look at below image,
<img width="344" alt="screen shot 2018-09-30 at 9 58 20 pm" src="https://user-images.githubusercontent.com/23524697/46260002-5dd86480-c4fe-11e8-809a-7d30d5e160be.png">

In MainViewControIler 3 buttons is there...When clicked on 1st button ChatViewController Comes, When clicked on 2nd button SomeViewController Comes and same also 3rd button....I have given **ClipToBounce = true** to MainViewControIler and also 3 child viewControllers....But, How can i remove MessageInputBar from when clicked 2nd & 3rd buttons? Please look at below image

<img width="382" alt="screen shot 2018-09-30 at 10 16 22 pm" src="https://user-images.githubusercontent.com/23524697/46260019-8d876c80-c4fe-11e8-9a83-a54dadc7ffca.png"> 

Any suggestions would be helpful.

**Comment by nathantannar4** [comment]
This is the contentInset bug that exists for child VCs (ie custom containers). Will be fixed in the next release very soon!

**Comment by talanov** [comment]
+1

**Comment by Dwayne28** [comment]
+1

**Comment by KrillioSokolov** [comment]
Any issues for this problem?

**Comment by SreekanthGudisi** [comment]
@KrillioSokolov are u asking to me?
