### ISSUE TITLE
InputBar Placeholder

### ISSUE THREAD

**Issue by llKoull** [MessageKit/MessageKit#886]
Hi!

Since i'm using Xcode 10 i noticed that the placeholder of the messageInputBar is not disappearing when i write. I'm using the development branch and i've juts updated the library today (i saw that there was an update to Swift 4.2) but the problem  persists.

I attach a screenshoot so you can see the issue.

![img_0019](https://user-images.githubusercontent.com/5525265/46293553-27e5bf80-c594-11e8-8679-da08d2991c5a.PNG)

Thanks and best regards!

**Comment by nathantannar4** [comment]
If you are using the pre release Branch development you will also need to specify the latest 0.4.0 version of `MessageInputBar`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by llKoull** [comment]
Hi @nathantannar4 !

Thanks for your answer i'm not specifying any version of MessageInputBar in my podfile. I've just did:

    pod 'MessageKit', :git => 'https://github.com/MessageKit/MessageKit', :branch => 'development'

What should i add?

Best regards!

**Comment by nathantannar4** [comment]
In the next upcoming release `MessageInputBar` is being split into it's own repo. You need to add `MessageInputBar` to your pod file and specify the `master` branch.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by llKoull** [comment]
Hi @nathantannar4 !

I added MessageInputbar pod doing:

pod 'MessageInputBar', :git => 'https://github.com/MessageKit/MessageInputBar', :branch => 'master'
pod 'MessageKit', :git => 'https://github.com/MessageKit/MessageKit', :branch => 'development'

But the issue persists. Cocoapods says that i'm using MessageInputBar 0.4.0 and MessageKit 1.0.0.

Thanks and best regards!

**Comment by llKoull** [comment]
Hi @nathantannar4!

I've recompiled and it just started to work!!

Thanks for your help! ^_^
