### ISSUE TITLE
Bubble size not rendering correctly when adding image to NSAttributedText

### ISSUE THREAD

**Issue by ioronamakingsense** [MessageKit/MessageKit#887]
I am using the latest version of the library, with Xcode 9.2 and iOS 11.2 with Swift 4

Basically I am trying to add an icon to a message bubble, but when the library calculated the bubble size, I guess it is not taking into account the image, and gets rendered like this:

![screen shot 2018-10-01 at 11 37 47](https://user-images.githubusercontent.com/36961517/46295726-28b82a80-c56f-11e8-8576-481624d25699.png)

Anybody know a work around to getting the size right? I've tried adding more text "manually" but with no luck so far. Thanks!

**Comment by JulienKode** [comment]
Hi @ioronamakingsense 

To integrate images in the bubbles. I create a custom cell especially for that.

I made a custom class that inherit from `MessagesCollectionViewFlowLayout`, in this object I register a custom class that inherit from `MessageSizeCalculator`

Here is an example:

`
open class CustomMessagesFlowLayout: MessagesCollectionViewFlowLayout {

    // MARK: - Attributes

    open lazy var customMessageSizeCalculator = CustomMessageSizeCalculator(layout: self)

    /// Here we map the incoming data to custom cell calculator
    open override func cellSizeCalculatorForItem(at indexPath: IndexPath) -> CellSizeCalculator {
        let message = messagesDataSource.messageForItem(at: indexPath, in: messagesCollectionView)

        // Here you can add a custom cell message calculator
        if case .custom(let data) = message.kind {
            switch data {
            case is MyCustumData:
                return customMessageSizeCalculator
            default:
                return super.cellSizeCalculatorForItem(at: indexPath)
            }
        }
        return super.cellSizeCalculatorForItem(at: indexPath)
    }

    /// Here we register our custom cell calculator
    open override func messageSizeCalculators() -> [MessageSizeCalculator] {
        var superCalculators = super.messageSizeCalculators()
        superCalculators.append(customMessageSizeCalculator)
        return superCalculators
    }
}
`

After that, In your own `MessageSizeCalculator` you can calculate the size of your text and you image, you can override the `messageContainerSize` method to calculate your view with the text + an image

Inside the original `MessageSizeCalculator` the method `labelSize ` calculate the size of the text and consider a maximum width:
`
func labelSize(for attributedText: NSAttributedString, considering maxWidth: CGFloat) -> CGSize {
        let constraintBox = CGSize(width: maxWidth, height: .greatestFiniteMagnitude)
        let rect = attributedText.boundingRect(with: constraintBox, options: [.usesLineFragmentOrigin, .usesFontLeading], context: nil).integral
        return rect.size
}
`
You can use a method like that to know the size of you text and add the size of you image may be

I do not know if it is the best way to manage the layout of a custom cell 
Maybe @nathantannar4 or @SD10 know more about that
