### ISSUE TITLE
Scroll to bottom doesn't correctly work with containerview in tabbar

### ISSUE THREAD

**Issue by donpironet** [MessageKit/MessageKit#894]
- What version of MessageKit are you using?
1.0.0
- What version of iOS are you running on?
12
- What version of Swift are you running on?
4.2
- What device(s) are you testing on? Are these simulators?
Simulator iPhone 8
- Is the issue you're experiencing reproducable in the example app?
No because there is no tabbar

I'm using the example in as a ChildViewController that is first full screen and pinned to the bottom layout guide. Now sometimes I change the layout of the MessageViewController (red backgroundcolor) to put a view under (white background color -> the yes / no view on the screenshot). This because I want to have a sort of quick replies instead of letting the user type.

Now when I change the layout and then tell scroll to bottom it doesn't show the whole chat bubble (like you can see on the screenshot)
![simulator screen shot - iphone 8 - 2018-10-05 at 11 23 22](https://user-images.githubusercontent.com/6583650/46527459-91661680-c891-11e8-94f2-98117fd32fec.png)

It seems to me that the MessageViewController doesn't know of the new height? 

Any idea how to solve this?

**Comment by nathantannar4** [comment]
Will be fixed in version 1.1 currently fixed on the `development` branch

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by donpironet** [comment]
Thanks. Do you know when this version is going to be released?
