### ISSUE TITLE
Scroll to bottom fails

### ISSUE THREAD

**Issue by hamzaozturk** [MessageKit/MessageKit#895]
I am using NSFetchedResultsController and i am populating my data in viewdidload method.
After the fetch is performed If i call self.messagesCollectionView.scrollToBottom(), it does not work since collectionViewLayout.collectionViewContentSize.height = 0.

JSQ also had a similar issue.

[https://github.com/jessesquires/JSQMessagesViewController/issues/256](url)

**Comment by nathantannar4** [comment]
Are you setting your results to an array that you feed to the datasource methods? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hamzaozturk** [comment]
Yes

**Comment by hamzaozturk** [comment]
Try to use this method instead of yours in the chat example. You will see that it will not scroll to the bottom if you call the data synchronously.


`func loadFirstMessages() {`
`         let count = UserDefaults.standard.mockMessagesCount()`
`         SampleData.shared.getMessages(count: count) { messages in`
`            self.messageList = messages`
`            self.messagesCollectionView.reloadData()`
`            self.messagesCollectionView.scrollToBottom()`
`        }`
`    }`
