### ISSUE TITLE
Message showing improper on top

### ISSUE THREAD

**Issue by ChandraPrakashJangid** [MessageKit/MessageKit#896]
When I tap on input field my messages scrolled bit up and hide behind top bar. If I don't click it shows perfectly. For more reference I am sharing screenshot after issue. 
![simulator screen shot - iphone 8 plus - 2018-10-06 at 15 47 58](https://user-images.githubusercontent.com/4987368/46570298-930e0800-c97f-11e8-8de4-04a42173177e.png)

**Comment by ichikmarev** [comment]
This is common issue, will be fixed in next release as @nathantannar4 said here: [https://github.com/MessageKit/MessageKit/issues/884](#884 )

**Comment by ChandraPrakashJangid** [comment]
@ichikmarev Thanks for update.

**Comment by nathantannar4** [comment]
Resolved in `2.0.0-beta1`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
