### ISSUE TITLE
MessageKit not working on swift 4.2

### ISSUE THREAD

**Issue by Shrutimittal91** [MessageKit/MessageKit#901]
Hi,
 
I have updated my project to swift 4.2 and i am using MessageKit (1.0.0) through cocoapods. But when i try to compile my code Message kit is giving error and is not getting compiled for the same.
<img width="280" alt="screen shot 2018-10-09 at 12 29 00 pm" src="https://user-images.githubusercontent.com/8266611/46652024-7233f580-cbbf-11e8-9813-0362cda18204.png">

**Comment by ChandraPrakashJangid** [comment]
In my view you have to use latest library. I am also using in Swift 4.2

**Comment by Shrutimittal91** [comment]
> In my view you have to use latest library. I am also using in Swift 4.2

I am using latest only. Can you please let me know the version? Mine is at 1.0.0

**Comment by alexnivanov** [comment]
I am having the same issue!

**Comment by nathantannar4** [comment]
You will have to use the `development` branch until the official release is made

**Comment by hkim777** [comment]
How can I set development branch with cocoapod?
Sorry, I'm novice.

**Comment by charvoa** [comment]
@hkim777 
Add this line in your Podfile : 
`pod 'MessageKit', :git => 'git@github.com:MessageKit/MessageKit.git', :branch => 'development'`

**Comment by hkim777** [comment]
@charvoa 
Thx.. Ill try it.

**Comment by SD10** [comment]
This will be resolved by #910

**Comment by ghost** [comment]
Adding the line:
pod 'MessageKit', :git => 'git@github.com:MessageKit/MessageKit.git', :branch => 'development'
with Swift 4.2 still not working:(

**Comment by vishal07malvi** [comment]
> Adding the line:
> pod 'MessageKit', :git => '[git@github.com](mailto:git@github.com):MessageKit/MessageKit.git', :branch => 'development'
> with Swift 4.2 still not working:(

did you find any solution ?

**Comment by ArunIOSM** [comment]
pod 'MessageInputBar'
Since MessageKit 2.0.0 you have to install MessageInputBar
