### ISSUE TITLE
Showing error on reload of messageCollectionView

### ISSUE THREAD

**Issue by ChandraPrakashJangid** [MessageKit/MessageKit#902]
When I reload the collection view I am getting following error:
`Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of sections.  The number of sections contained in the collection view after the update (1) must be equal to the number of sections contained in the collection view before the update (0), plus or minus the number of sections inserted or deleted (0 inserted, 0 deleted).'`

**Comment by nathantannar4** [comment]
What are you calling to reload your data? Sounds like its in an inconsistent state. You may find this helpful: https://stackoverflow.com/questions/19199985/invalid-update-invalid-number-of-items-on-uicollectionview

**Comment by ChandraPrakashJangid** [comment]
I found the solution for this. Actually I was passing wrong values before reload.
