### ISSUE TITLE
Is there a way to implement own detectors?

### ISSUE THREAD

**Issue by ichikmarev** [MessageKit/MessageKit#903]
I know, that's it not ready for current state of library, but may be some way to do it for detect hashtags or something?

**Comment by SD10** [comment]
@ichikmarev There's no way to do this currently. It's on the roadmap if anyone has a good solution. It's also related to #764

**Comment by JulienKode** [comment]
#913 should solve this

**Comment by vjoomens** [comment]
Hi, nice option to create custom detectortype using regex, but I need something with a callback / closure, so I can match my from data.

**Comment by nathantannar4** [comment]
@vjoomens You would have to fetch the detectors you need before displaying your messages, or reload your messages after you know the result of the callback 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
Check out the latest version of MessageKit 💯
