### ISSUE TITLE
How to get indexPath for tapped message

### ISSUE THREAD

**Issue by ChandraPrakashJangid** [MessageKit/MessageKit#904]
I have implemented MessageKit in my app. Now I need to get indexPath of message. I used following code:
```
func didTapMessage(in cell: MessageCollectionViewCell) {
        //Call Method to Show Action Picker
        guard let indexPath = messagesCollectionView.indexPath(for: cell) else { return }
        print(indexPath.row)
        
    }
```
But when I print this row number it is always returning 0 I am not getting where I am wrong.

**Comment by Sherlouk** [comment]
Have you tried checking the section as well? I believe they use a combination of sections for each message and rows for different parts of the message (top label, main message, bottom label, etc)

**Comment by hamzaozturk** [comment]
You can use indexPath.section

**Comment by SD10** [comment]
MessageKit is section based, meaning each cell is in it's own section (as others have pointed out above). You will need to use `indexPath.section`
