### ISSUE TITLE
How to replace the inputTextView with my custom view?  I need to add a button instead

### ISSUE THREAD

**Issue by hadiidbouk** [MessageKit/MessageKit#906]

**Comment by nathantannar4** [comment]
You shouldn't be using the MessageInputBar if that is your goal. Consider creating your own InputAccessoryView that has a single button. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hadiidbouk** [comment]
I set a microphone button to record the user's voice, it's working fine, but I don't want to show the inputTextView I want to show a cancel button or even more than that like voice wave.

**Comment by nathantannar4** [comment]
The `InputTextView` is built into the `MessageInputBar`, aside from setting it to hidden you can't remove it. Maybe consider using the top or bottom stack views to show the audio wave?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hadiidbouk** [comment]
I see... I don't know why the `InputTextView` it's not added to a `UIStackView` also.

**Comment by nathantannar4** [comment]
Why would we want the `InputTextView` in a stack view? We need to be able to control things such as its width and have it auto grow without the interference of other views in the stack view. 

Have you tried adding subviews to the `InputTextView`?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
