### ISSUE TITLE
messageInputBar hiding on tapping Navigation bar

### ISSUE THREAD

**Issue by faizy-ahmed** [MessageKit/MessageKit#908]
The issue details are as follows:

- MessageKit version is: 1.0.0
- iOS version is 11.2
- Swift version 4.0
- I have tested on 6s (real device) and 6s (simulator)
- No, the example app has not this issue but when i am implementing with same guidelines, the issue appears.

The Sample Code is as below:
```swift
class FriendsChatVC: MessagesViewController
{
    // MARK: - Outlets
    @IBOutlet weak var blackShadeView: UIView!
    
    // MARK: - Class Level Variables
    var specificDialogId: String? = nil
    
    
    // MARK: - View life Cycle
    override func viewDidLoad()
    {
        super.viewDidLoad()
    }
    
    override func viewWillAppear(_ animated: Bool)
    {
        super.viewWillAppear(animated)
        
        // Show the navigation bar on the this view controller
        self.navigationController?.setNavigationBarHidden(false, animated: animated)
    }
    
    override func viewWillDisappear(_ animated: Bool)
    {
        super.viewWillDisappear(animated)
        
        // Hide the navigation bar on the this view controller
        self.navigationController?.setNavigationBarHidden(true, animated: animated)
    }

    override func didReceiveMemoryWarning()
    {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
}
```

Details of the issue:
- When i am **tapping the navigation bar, messageInputBar hides**.
- I have also tested after all the implementation of code as in the example.

**Comment by faiqmustaqeem** [comment]
I am also facing this issue , can you please tell me is it resolved yet ?

**Comment by Saad-Umar** [comment]
Facing the same, unable to resolve, tried everything but no luck. Weird thing is that the exact same code is working flawlessly in the sample app but doesn't work as expected when I implement it in my project. Am I missing anything?

**Comment by iamzakikhan** [comment]
Facing same issue! If someone have figured out this hack, please share it.
