### ISSUE TITLE
Scrolling UICollection view when keyboard showing.

### ISSUE THREAD

**Issue by iBolom** [MessageKit/MessageKit#91]
Hi,
So when keyboard showing we can scroll collection view with method scrollToBottom but i think it's not good solution because if we are positioning on the middle of chat history and expand keyboard it will scroll to end of the chat history. So WhatsApp/Viber has some different solution to move entire view up when keyboard showing on the screen. What do you think about it, for me it sounds good.

**Comment by etoledom** [comment]
I know what you mean, I was thinking a similar thing. But do they literally move the whole view up?.
If we want to implement that, it might be better to calculate a new content offset and animate it alongside the keyboard

**Comment by iBolom** [comment]
@etoledom So you are right we can calculate new content offset and move collection view for keyboard height.

**Comment by SD10** [comment]
@BojanAnox Is this a question? I'm not sure if I understand but let me know if we can close this as it seems it's been resolved 🤗

**Comment by iBolom** [comment]
@SD10 So the problem is if you are in the middle of chat history and expand keyboard with method scrollToBottom() it will scroll chat history to the bottom. If we are on the last message in the chat and expand keyboard and if we use method scrollToBottom() it will works fine(we will see last message) but if we don't use this method keyboard will overlap the last message in chat. So we need to find solution how to fix it.

**Comment by etoledom** [comment]
As I understand, basically the feature requested is to scroll the messages alongside the keyboard, so whatever text that was a the bottom on the screen without keyboard will still be visible with the keyboard. It works like that in Telegram, WhatsApp, Facebook messenger and some others.

I think it would be good at least to put it somewhere in the roadmap.

**Comment by SD10** [comment]
@BojanAnox @etoledom I see that iMessage scrolls to bottom regardless of your position in the scroll view. I didn't add this behavior by default because personally, I don't like it and I think others may not want this behavior as well. I can look into maintaining the offset.

**Comment by iBolom** [comment]
Ok, so offset will be also good solution for this issue.

**Comment by hyouuu** [comment]
It would be great to provide a config toggle for this - I'd also like the scroll to bottom behavior just like iMessage ;)

**Comment by SD10** [comment]
Version 0.12.0 will have the following functionality:
`maintainPositionOnKeyboardFrameChanged: Bool`
`scrollsToBottomOnKeyboardDidBeginEditing: Bool`
`messagesCollectionView.scrollToBottom()`
`messagesCollectionView.reloadDataAndKeepOffset()`
