### ISSUE TITLE
Replace static assets with custom drawing assets

### ISSUE THREAD

**Issue by emmanuelay** [MessageKit/MessageKit#915]
This library looks really promising and I want to get involved. I was wondering if it would be relevant for you all to replace the assets with custom self-drawing views.

In practice this would mean replacing all the @1x, @2x, @3x files with UIViews that uses Core Graphics to draw the underlying chat-bubbles etc. This would completely remove the need to bundle assets into MessageKit - and it would open a host of new customization possibilities regarding how to style the chat bubbles (gradients, outlines, fill etc).

[Medium-article](https://medium.com/@dima_nikolaev/creating-a-chat-bubble-which-looks-like-a-chat-bubble-in-imessage-the-advanced-way-2d7497d600ba) about the concept.
[Github](https://github.com/dima-nikolaev/ChatBubbleAdvanced) example with the concept implemented.

**Comment by emmanuelay** [comment]
Possible duplicate #307 ?

**Comment by nathantannar4** [comment]
@emmanuelay using static graphics has a faster render time than CoreGraphics. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
@emmanuelay Fwiw, you can use `MessageStyle.custom` if you want to do some custom styling for your bubbles. We explored using CoreGraphics but it turned out to be less performant than using images as @nathantannar4 mentioned
