### ISSUE TITLE
Can I show message sent date for custom message type?

### ISSUE THREAD

**Issue by himanthmaddi** [MessageKit/MessageKit#917]
- What version of MessageKit are you using -> 1.0.0
- What version of iOS are you running on -> 12.0.1
- What version of Swift are you running on? -> 4.2
- What device(s) are you testing on? Are these simulators? -> iPhone 6

In the example app, I can see message sent date for every 3 messages on cellTopLabel. But it is not considering custom messages.

I want to show the date for custom messages like a new user has joined or somebody left. 

How can I do that?

**Comment by nathantannar4** [comment]
That's entirely up to you. If your using .custom it won't use the default text message cell which has the top and bottom labels. Add a label. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by faizy-ahmed** [comment]
You can customise your text in 'cellTopLabelHeight' of 'MessagesLayoutDelegate' method.

**Comment by nathantannar4** [comment]
@faizy-ahmed those labels only exists for the default text message cell. Custom cells don't have those labels. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by clay-mindoula** [comment]
can a bottom label be added to a custom cell?

**Comment by nathantannar4** [comment]
Its a custom cell so you could add anything you want 😊 You are just responsible for its configuration and layout
