### ISSUE TITLE
MessageKit 2.0.0-beta1 ViewController disappears after showing for sometime.

### ISSUE THREAD

**Issue by umairali612** [MessageKit/MessageKit#919]

**Comment by umairali612** [comment]
When I do this, It is being added to view and doesn't call viewWilldisappear but input edittext is not being shown:
let helloController=ConversationViewController()
addChild(helloController)
        self.view.addSubview(helloController.view)
        helloController.didMove(toParent: self)

**Comment by nathantannar4** [comment]
Not quite sure what your saying the issue is here? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by umairali612** [comment]
Sorry mate. I was calling popviewcontroller from parent's willdisappear and it was popping chatviewController. Dumb mistake.
