### ISSUE TITLE
Message states: retry, sending

### ISSUE THREAD

**Issue by talanov** [MessageKit/MessageKit#921]
- What version of MessageKit are you using?
2.0.0 beta

Idea for future enhancements:
'Retry' button.

State: 'Send' button touched

* Message is shown @ tableview with no date.
* Status: sending (custom background etc)

State: Failed to send message

* Message is shown @ tableview with no date.
* Instead of date there's 'retry' button

**Comment by JulienKode** [comment]
@talanov I think we can implement this feature using the `accessoryView` ?

**Comment by nathantannar4** [comment]
This is rather hard to implement in a library. How do we know if the message was sent successfully? 

This is something that is very client specific. The correct approach would be to edit the title of the send button yourself, and as Julien said, possibly leverage the accessory view. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
I agree with Nathan and Julien. It could be implemented by using one of the cell's accessory labels or the accessory view itself. The logic for this is way too client specific
