### ISSUE TITLE
how can i add view to inputAccessoryView and switch keyboard ?

### ISSUE THREAD

**Issue by c941010623** [MessageKit/MessageKit#925]
Sorry, but i love this and i am new use swift.
how can i add custom view to inputAccessoryView and switch keyboard ??
Can anyone help me ? please~

**Comment by nathantannar4** [comment]
Hi @c941010623, do you mean MessageInputBar? `inputAccessoryView` is a property. And what do you mean by switch keyboard?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by c941010623** [comment]
Dear @nathantannar4 ,  I want add a button can switch keyboard (display / hide)
when hide the keyboard the custom view will display, i am new player so i need have
simple example code.

sorry, but i wish have someone taught me, please and thanks

like this:
![image](https://user-images.githubusercontent.com/4303823/47836202-441e8b80-dde2-11e8-8f9c-5720421a4234.png)

**Comment by nathantannar4** [comment]
Are you asking how can this be achieved with MessageInputBar? That looks like a collection view that could be placed in the bottomStackView

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by c941010623** [comment]
@nathantannar4 Yes, i want it
I speak English not very well. Sorry about that

**Comment by nathantannar4** [comment]
Yes you will probably want to use the bottom stack view and a UICollectionView. See the slack keyboard example in the ChatExample project for starters 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by c941010623** [comment]
@nathantannar4 
ok, i will try it and thank you
If I have any questions, please help me.

**Comment by c941010623** [comment]
@nathantannar4 
ok, i will try it and thank you
but i didn't find the slack keyboard example in the ChatExample project

**Comment by JulienKode** [comment]
@c941010623 I think it’s on the 1.0.0 branch 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by c941010623** [comment]
@JulienKode thank you and I will try and find it, thank you again.

**Comment by c941010623** [comment]
Dear all:
How to know that the InputTextView is clicked ??

**Comment by c941010623** [comment]
ok i use NotificationCenter.default.addObserver
now can switch keyboard and show the custom view
thank you all

**Comment by fukemy** [comment]
hello, i can not find the 1.0.0 example for the slack keyboard, can you help? I need to show gif sticker as custom keyboard below messageInputBar, as the question.
