### ISSUE TITLE
how add view to bottomStackView

### ISSUE THREAD

**Issue by c941010623** [MessageKit/MessageKit#926]
i used the code want to add custom view in bottomStackView

want to do like sticker panel , but it's not work ....

code:
let testUI = UIView()
                testUI.frame = CGRect(x: 0, y: 0, width: self.view.frame.width, height: 200)
                testUI.backgroundColor = .red
                self.messageInputBar.bottomStackView.addArrangedSubview(testUI)

but it not show, why ??

Where am I doing something wrong?

**Comment by nathantannar4** [comment]
The layout of the stack views subviews is based on their instrinsic content size. You need to override that on your custom view class it add some autolayout constraints

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
