### ISSUE TITLE
disable sliding off the keyboard

### ISSUE THREAD

**Issue by c941010623** [MessageKit/MessageKit#927]
how can i do disable sliding off the keyboard?

i want disable the sliding down close keyboard

how can i do ?

**Comment by nathantannar4** [comment]
Change `messagesCollectionView.keyboardDismissMode`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by c941010623** [comment]
@nathantannar4 thank you very much ^^
