### ISSUE TITLE
Inputview flickering issue

### ISSUE THREAD

**Issue by pawankmrai** [MessageKit/MessageKit#928]
- What version of MessageKit are you using?
   **MessageKit (1.0.0)**
- What version of iOS are you running on?
   **iOS 12.1**
- What version of Swift are you running on?
  **Swift 4.0**
- What device(s) are you testing on? Are these simulators?
  **iPhone 7 & Simulator 6s & 7**
- Is the issue you're experiencing reproducable in the example app?
  **No**

[fickering issue link](https://cl.ly/6e1fa0a1e8e1)

**Source code**

```swift
private func prepareDelegates() {
		messagesCollectionView.messagesDataSource = self
		messagesCollectionView.messagesLayoutDelegate = self
		messagesCollectionView.messagesDisplayDelegate = self
		messagesCollectionView.messageCellDelegate = self
		messageInputBar.delegate = self
	}
	
	private func prepareInputField() {
		//
		messageInputBar.sendButton.tintColor = UIColor(red: 69/255, green: 193/255, blue: 89/255, alpha: 1)
		scrollsToBottomOnKeybordBeginsEditing = true // default false
		maintainPositionOnKeyboardFrameChanged = true // default false
		
		// Refresh
		messagesCollectionView.addSubview(refreshControl)
		refreshControl.addTarget(self, action: #selector(ChatViewController.observeMessages), for: .valueChanged)
		
		// Customisation
		defaultStyle()
	}
	
	func defaultStyle() {
		let newMessageInputBar = MessageInputBar()
		newMessageInputBar.sendButton.tintColor = UIColor(red: 69/255, green: 193/255, blue: 89/255, alpha: 1)
		newMessageInputBar.delegate = self
		messageInputBar = newMessageInputBar
		reloadInputViews()
	}
```
all these methods are called in **viewdidload**.

**Comment by c941010623** [comment]
Do you use IQKeyboardManager ?

**Comment by nathantannar4** [comment]
^ I have seen this before and IQKeyboardManager can be a reason. If not, please try MessageKit 2.0

**Comment by pawankmrai** [comment]
Yes, that's correct.
It's due to IQKeyboardManager.
Thanks, @nathantannar4 @c941010623  for quick help.
