### ISSUE TITLE
Can't run ChatExample

### ISSUE THREAD

**Issue by OuSS-90** [MessageKit/MessageKit#930]
What version of MessageKit are you using?
**MessageKit (2.0.0)**
What version of iOS are you running on?
**iOS 12**
What version of Swift are you running on?
**Swift 4.2**
What device(s) are you testing on? Are these simulators?
**iPhone 8 Plus**

I can't run "ChatExample" project, I have this error: 

```
Linting 'CustomMessageFlowLayout.swift' (1/19)
Could not cast value of type 'Swift.Int64' (0x10aa8cf90) to 'Swift.String' (0x10aa934e8).
Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by nathantannar4** [comment]
You should be using Swift 4.2 for MessageKit 2.0

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by OuSS-90** [comment]
Yes, I am using Swift 4.2 sorry

**Comment by nathantannar4** [comment]
You seem to be using some kind of linter? It does not look like a build error. Clean the build and if it helps delete what's in your xcodes DerivedData folder. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
