### ISSUE TITLE
Custom Message Bubble

### ISSUE THREAD

**Issue by Skornos** [MessageKit/MessageKit#934]
- What version of MessageKit are you using? **MessageKit 2.0.0**
- What version of iOS are you running on? **iOS 12.1**
- What version of Swift are you running on? **Swift 4.2**

I am trying to set my custom message bubble following `.custom MessageStyle`. from the example project.

I would like to mask the resulting view with the shape of my custom `UIImage` since I haven't found a way how to pass my own images to the library. The following code results in the badly stretched image.

```
        return .custom { view in
            let shapeLayer = CAShapeLayer()
            shapeLayer.contents = R.image.bubble()?.cgImage
            shapeLayer.frame = view.bounds
            view.layer.mask = shapeLayer
        }
```

![message bubble](https://i.imgur.com/NJuwIDU.png)

Is there a way how to display my own message bubble image?

Thanks 👍

**Comment by JulienKode** [comment]
Have you try that answer ? https://github.com/MessageKit/MessageKit/issues/945
