### ISSUE TITLE
"Scroll to bottom" button

### ISSUE THREAD

**Issue by jayaditaslim** [MessageKit/MessageKit#935]
Hi all, I'm currently experimenting with MessageKit (a very nice project!) and hit upon a wall. I'm currently using MessageKit v2.0.

I'm trying to implement a floating button on the top and right side of the input bar which will scroll the collection view to the very bottom (can be found in most common instant messaging applications). Below is a screenshot of the floating button that I tried to implement:

![sample](https://user-images.githubusercontent.com/23491708/48297686-6f3f6400-e4e1-11e8-8cb5-e284f707ed03.png)

**What I have tried:**

This is how I created the button like the screenshot - I've tried to implement a custom MessagesControllerView and added a styled InputBarButtonItem (I'll call it the goToBottom button from now on) in the inputAccessoryView (which is the MessageInputBar). I added some constraints so that it appears on top and right side of the input bar. It appears nicely upon any layout changes, however it fails to listen on click. Instead, clicks are responded by the collection view.

I have also tried adding the goToBottom button directly to messagesCollectionView. It renders nicely and is registering the clicks. However, I do have to hard-code the constraint constant and the button will disappear if i open the keyboard.

I have also considered to add the goToBottom button to the topStackView of the inputBar but I think it might not be a good idea since topStackView can be used for other utilities.

This button might be a nice feature to have into MessageKit. I would be glad if there are some guidances to apply this goToBottom button. I'm new to iOS development, so I am really sorry if this ends up as a very easy thing to do that I missed! Cheers!

**Comment by nathantannar4** [comment]
Thank you for a well detailed report! Makes it easy for us to help. By the sounds of things, your adding this button to the MessageInputBar but anchoring such that it's outside the bounds of the MessageInputBar. I'm not positive but because it's outside the bounds this could be causing the button to not receive taps. 

If I were you, I would add this floating button as a subview of your subclassed MessagesViewController.  You can anchor it to the bottom right of the view and use the delegate method of the MessageInputBar to detect when the MessageInputBar changes its size. You can then use this size to update the constraints constants of your flowing view to keep it above the MessageInputBar. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jayaditaslim** [comment]
Thank you for suggestion, and sorry for the late reply!

Yes, the goToBottom might be out of the MessageInputBar's bound since I put its bottom anchor to the inputBar's top anchor with a minus 5 constant. Guess that's why it didn't register any click.

I tried to implement your suggestion and overrode the messageInputBarDelegate:didChangeIntrinsicContentTo with some anchor logic. It is now placed nicely and can listen to the click! 

However, when keyboard is shown, the goToBottom button is then overlapped. I looked into MessageViewController+Keyboard and see that I might override handleKeyboardDidChangeState and add a little bit of my anchor positioning logic there. Bad news is that it is a private function.

As not to tamper with the original MessageKit, I temporarily added a new observer for keyboardDidShow in my custom MessagesControllerView which will update the goToBottom constraint. Everything's working great so far!

On the side note, are you going to implement this feature in the next iteration of MessageKit?

**Comment by nathantannar4** [comment]
A scroll to bottom button? No something like that is too much of a customizable and so it wouldn't be added to the library

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jayaditaslim** [comment]
Fair point. Again, thank you fore your help! I'll close this issue.

**Comment by johnharutyunyan** [comment]
@jayaditaslim , Can you please share your code of implemetantion Floating Button?
Thanks

**Comment by shadzik** [comment]
It's pretty simple to add such a floating button:

`
view.keyboardLayoutGuide.followsUndockedKeyboard = true
scrollToBottomButton.translatesAutoresizingMaskIntoConstraints = false
scrollToBottomButton.widthAnchor.constraint(equalToConstant: buttonWidth).isActive = true
scrollToBottomButton.heightAnchor.constraint(equalToConstant: buttonWidth).isActive = true
scrollToBottomButton.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -trailingMargin).isActive = true

scrollToBottomButton.bottomAnchor.constraint(equalTo: view.keyboardLayoutGuide.topAnchor, constant: -bottomMargin).isActive = true
`
