### ISSUE TITLE
Chat screen content goes under input bar

### ISSUE THREAD

**Issue by moldovaniosif** [MessageKit/MessageKit#936]
Hi,

I wanted to find a way to avoind scroll to bottom flicker when the chat screen is first time presented. The only solution I was able to find is to preload the chat screen then push it to navigation stack. 
I had replace the next line from `LaunchViewController`:
```swift
navigationController?.pushViewController(AdvancedExampleViewController(), animated: true)
```
with
```swift
let advanceViewController = AdvancedExampleViewController()
advanceViewController.view.frame = CGRect.init(x: 1000,
                                               y: 0,
                                           width: advanceViewController.view.frame.size.width,
                                          height: advanceViewController.view.frame.size.height)
self.view.addSubview(advanceViewController.view)
DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 0.4) {
        advanceViewController.view.removeFromSuperview()
        self.navigationController?.pushViewController(advanceViewController, animated: true)
}
```
I know this is a hacky way to do it but I wasn't able to find any other solution. The problem here is after I push the `ChatViewController` its content goes under input bar, see the image below:
![figure_1](https://user-images.githubusercontent.com/32193308/48333168-1269b800-e65f-11e8-86c3-16891406909c.png)

I had tried to use  `additionalBottomInset` property to ajust bottom inset, like follow
```swift
advanceViewController.additionalBottomInset = 80
```
which indeed solve this issue but it leds me to other issue, when the keyboard is presented the chat content size has extra 80 px see the image below:
![screen shot 2018-11-12 at 09 51 25](https://user-images.githubusercontent.com/32193308/48333561-97090600-e660-11e8-8d5a-1747a3165e1e.png)

I've made some investigation and I find out for the case when chat screen is preloaded the `inputAccessoryView` height is zero and that's why the chat screen content height is wrong. Below I print the method where the the chat screen content is computed.
```swift
    internal func requiredInitialScrollViewBottomInset() -> CGFloat {
        guard let inputAccessoryView = inputAccessoryView else { return 0 }
        return max(0, inputAccessoryView.frame.height + additionalBottomInset - automaticallyAddedBottomInset)
    }
```
I wan't able to find out why the `inputAccessoryView` height is zero. 

MessageKit version:  I used the branch from development
iOS version: 12.0, 10.0
Swift version: 4.2
devices: iPhone Xs, iPhone 6, simulator iPhone 7
This issue is 100% reproductible if you replace the code from `LaunchViewController` with the preload chat screen code.

**Comment by nathantannar4** [comment]
Hmm, I think there might be a better way to fix the flicker as this hacky method seem to lead to more issues. I can say that the InputAccessoryView height is 0 when you are checking it because the accessory hasn't been added yet since the ChatViewController has yet to become the first responder. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jayaditaslim** [comment]
I also had this problem. My current workaround (may not suit your requirements) is adding a small logic check in viewDidAppear on ChatViewController. 

What I did is check whether the last item's index path is visible. If so, call the scrollToBottom method. Below is the sample code:

```
if messagesCollectionView.indexPathsForVisibleItems.contains(IndexPath(row: 0, section: yourDataArray.count - 1)) {
    messagesCollectionView.scrollToBottom(animated: true)
}
```
