### ISSUE TITLE
How can I activate taps and long taps in custom cell?

### ISSUE THREAD

**Issue by k2tt** [MessageKit/MessageKit#938]
Hi.

+ What version of MessageKit are you using? 2.0.0
+ What version of iOS are you running on? 12.0
+ What version of Swift are you running on? 4.2.1
+ Is the issue you're experiencing reproducable in the example app? Yes

![image](https://user-images.githubusercontent.com/7380350/48410467-ff033d80-e781-11e8-8c67-0e68e89ccf4e.png)

I tried but I could not do it well.
Could you please teach a solution :bow:

Thank you for making great products.

**Comment by nathantannar4** [comment]
It is a custom cell, therefore you will be to add your own tap gestures. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by k2tt** [comment]
@nathantannar4 
Thank you for your quick reply! 
I thought so, I tried the means to think, but I couldn't do it :cry:

If you don't mind, could you give me hints or sample code?

Thank you.

**Comment by k2tt** [comment]
I still can not work the UIMenuItem by long press normally.
I want to give custom cells behave like normal cells.
Please help someone 🙏

**Comment by JulienKode** [comment]
What is your current code  @k2tt  ?
