### ISSUE TITLE
I want to dismiss keyboard after the sending message. But I can't do that using existing library .If anyone knows how to do that or another way answer to this.

### ISSUE THREAD

**Issue by NaleenDissanayake** [MessageKit/MessageKit#940]

**Comment by nathantannar4** [comment]
You need to resign the first responder of the InputTextView

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NaleenDissanayake** [comment]
How to do that . I tried but didn't change

**Comment by c941010623** [comment]
in the send button action use the:
self.messageInputBar.inputTextView.resignFirstResponder()
