### ISSUE TITLE
How to use Messagekit with a custom cell ?

### ISSUE THREAD

**Issue by chunxige** [MessageKit/MessageKit#945]
i  want to regiser a custom cell type in collectionView,how should i do

**Comment by JulienKode** [comment]
Hi @chunxige 

To make a custom cell, you have to make a cell that inherit from `UICollectionViewCell`. 
Once you have your cell, you need to tell the size of your cell. How can to do that ?

You have to make a class that inherit from `MessageSizeCalculator` or `CellSizeCalculator` to make a custom cell size calculator

You have to make a class that inherit from `MessagesCollectionViewFlowLayout` and add you custom size calculator that will calcul the size of your cell.

You must override two method to achieve that:

- `messageSizeCalculators()` to add your custom cell size calculator
- `cellSizeCalculatorForItem(at indexPath: IndexPath)` to choose with which cell you will use your custom cell calculator


You can see this example from the development branch:

```swift
open class CustomMessagesFlowLayout: MessagesCollectionViewFlowLayout {
    
    open lazy var customMessageSizeCalculator = CustomMessageSizeCalculator(layout: self)
    
    open override func cellSizeCalculatorForItem(at indexPath: IndexPath) -> CellSizeCalculator {
//        if isSectionReservedForTypingBubble(indexPath.section) {
//            return typingMessageSizeCalculator
//        }
        let message = messagesDataSource.messageForItem(at: indexPath, in: messagesCollectionView)
        if case .custom = message.kind {
            return customMessageSizeCalculator
        }
        return super.cellSizeCalculatorForItem(at: indexPath)
    }
    
    open override func messageSizeCalculators() -> [MessageSizeCalculator] {
        var superCalculators = super.messageSizeCalculators()
        // Append any of your custom `MessageSizeCalculator` if you wish for the convenience
        // functions to work such as `setMessageIncoming...` or `setMessageOutgoing...`
        superCalculators.append(customMessageSizeCalculator)
        return superCalculators
    }
}

open class CustomMessageSizeCalculator: MessageSizeCalculator {
    
    public override init(layout: MessagesCollectionViewFlowLayout? = nil) {
        super.init()
        self.layout = layout
    }
    
    open override func sizeForItem(at indexPath: IndexPath) -> CGSize {
        guard let layout = layout else { return .zero }
        let collectionViewWidth = layout.collectionView?.bounds.width ?? 0
        let contentInset = layout.collectionView?.contentInset ?? .zero
        let inset = layout.sectionInset.left + layout.sectionInset.right + contentInset.left + contentInset.right
        return CGSize(width: collectionViewWidth - inset, height: 44)
    }
  
}

```

**Comment by chunxige** [comment]
thanks

**Comment by NikKovIos** [comment]
For people who implement custom cells and spend time like me:

1) Check AdvancedExampleViewController in Example folder.
2) Notice that there is the accessory view. `func configureAccessoryView(_ accessoryView: UIView, for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView)`
