### ISSUE TITLE
Not an issue, question to community

### ISSUE THREAD

**Issue by neodave** [MessageKit/MessageKit#946]
Quick question. This looks amazing and we are beginning to implement it for our iOS project. Has anyone worked with a similar Android framework they can recommend?

Apologies if this is not the right place to post this.

**Comment by JulienKode** [comment]
https://github.com/stfalcon-studio/ChatKit can be an equivalent for Android

**Comment by neodave** [comment]
Thank you so much for the quick reply.

**Comment by JulienKode** [comment]
No problem @neodave 
Hope it will help you
