### ISSUE TITLE
How to create a custom bubble cell

### ISSUE THREAD

**Issue by NikKovIos** [MessageKit/MessageKit#947]
Hello guys. I watched https://github.com/MessageKit/MessageKit/issues/788 https://github.com/MessageKit/MessageKit/issues/543 and other issues, but didn't understand:

What is the way to create custom bubble cell? I need to merge the time label and text bubble into one place, and think that the only way for this is to create the new cell type. Please place the example here. I hope the answer for my question will help a lot and prevent other related issues :)
![2018-11-19 17 51 32](https://user-images.githubusercontent.com/16647690/48714666-36f7fe00-ec24-11e8-9328-b05d6f3c0f82.png)

**Comment by JulienKode** [comment]
Have you try that solution ? https://github.com/MessageKit/MessageKit/issues/945
