### ISSUE TITLE
Bubble chat like whatsapp

### ISSUE THREAD

**Issue by giuseppeVacatello** [MessageKit/MessageKit#948]
Hi,
is there a way to have a chat bubble whatsapp style?
For example with the timestamp label at the bottom inside the bubble.
Any advice to do it?
Thanks a lot.

**Comment by nathantannar4** [comment]
Yes it is possible through the use of custom cells. It would require some extra work on your side to design the cell and write the layout code to look like what's app

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by giuseppeVacatello** [comment]
Thank you @nathantannar4 :)

So I have to write at least two classes:

- class MyCustomCell: UICollectionViewCell { ... }

- class MyCustomMessagesFlowLayout: MessagesCollectionViewFlowLayout { ... }

Can you confirm me?
All from code or even with xib files?

Thank you very much

**Comment by JulienKode** [comment]
Yes you also have to make another class I think. Something like

`MyCustomMessageSizeCalculator: CellSizeCalculator { ... }`
and register it inside your `MyCustomMessagesFlowLayout`

**Comment by giuseppeVacatello** [comment]
A little example with just two label? One for main text and one for footer would be more useful, not only for me, but for everyone. I think it's a feature that they want to use in many.
thank you so much

**Comment by JulienKode** [comment]
You can see that one https://github.com/MessageKit/MessageKit/issues/945
