### ISSUE TITLE
MessageKit is no OK with my SWIFT 4.2

### ISSUE THREAD

**Issue by Mike4ftv** [MessageKit/MessageKit#949]
Hello,

I am new in developper IOS World, and I try to use MessageKit in an app but there is lots of errors at the beginning.

I use SWIFT 4.2 and I download MessageKit with cocopoads with : pod 'MessageKit' but it is no OK
after, I have created another project and with cocopoad I have written : pod 'MessageKit' and pod'MessageInputBar' but it is always no OK.

Could you please help me and said me what line of command I must write in cocopoads ?

Thanks in advance

**Comment by JulienKode** [comment]
Which version of MessageKit did you use ? 

Did you have some error message ?

**Comment by Mike4ftv** [comment]
this is version 1.0.0
if i good understanding, I must download 2.0.0 or 2.0.0-beta1, but I don't know in cocoa pods what I must write...
i have written pod'MessageKit' and for me the download was the last version (2.0.0) while it is not the case ;-)

**Comment by JulienKode** [comment]
You right you need to use at least the 2.0 version, 1.0 is not compatible with Swift 4.2

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JulienKode** [comment]
Have you try running `pod update` ? Or `pod repo update` 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
^ likely your repo as @JulienKode pointed out. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Mike4ftv** [comment]
I will try this afternoon. I will give you feedback

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>

________________________________
De : Julien K <notifications@github.com>
Envoyé : samedi, novembre 24, 2018 19:12
À : MessageKit/MessageKit
Cc : Mike4ftv; Author
Objet : Re: [MessageKit/MessageKit] MessageKit is no OK with my SWIFT 4.2 (#949)


Have you try running pod update ? Or pod repo update

Sent with GitHawk<http://githawk.com>

**Comment by Mike4ftv** [comment]
I have just created new project and and I tried to add Message kit with Cocoapods with this action : 
pod 'MessageKit' ~> '2.0'
and I have an error message : see below 
![image](https://user-images.githubusercontent.com/40462055/48979069-cdf60780-f0b5-11e8-8b48-8312859d94b6.png)

**Comment by JulienKode** [comment]
You can change the version to 2.0.0 please


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Mike4ftv** [comment]
same error message, perhaps I should try to do it without cocoa pods but directly in terminal

**Comment by JulienKode** [comment]
Have you try pod repo update ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Mike4ftv** [comment]
I don't know do it ;-(

**Comment by JulienKode** [comment]
Just type `pod repo update` in your terminal 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Mike4ftv** [comment]
Great ! it is OK now !
Thanks for your help @JulienKode

**Comment by JulienKode** [comment]
@Mike4ftv Glad it's resolved
