### ISSUE TITLE
Different avatar sizes for different indexPaths

### ISSUE THREAD

**Issue by Elshad** [MessageKit/MessageKit#951]
Hi!
How can i set different avatar size for incoming messages for exp. if this messages from admin of group? I mean bigger avatar size for admin than for other users.

I came from version 0.13.2
There was `avatarSize(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> CGSize` for avatar size

**Comment by SD10** [comment]
@Elshad Yeah we changed this in 1.0. Here's how you would do it now:

```swift
let adminSize = CGSize(width: 40, height: 40)
if let layout = messagesCollectionView.collectionViewLayout as? MessagesCollectionViewFlowLayout {
  layout.setMessageIncomingAvatarSize(adminSize)
}
```

**Comment by Elshad** [comment]
@SD10 But this code will set same size to all incoming avatars, i want set different sizes for incoming avatars.
How can i replace below code?
<img width="774" alt="screen shot 2018-12-07 at 17 09 17" src="https://user-images.githubusercontent.com/2334731/49649564-f0d3d480-fa42-11e8-8959-5b0cf7847614.png">

**Comment by Elshad** [comment]
Is there easy way to do this like previous version or i must extend `MessageSizeCalculator` and `MessagesCollectionViewFlowLayout`?

**Comment by SD10** [comment]
@Elshad If you want to make this dynamic you probably want to override this function in `MessageViewController`:
```
override func collectionView(_ collectionView: UICollectionView, 
                      layout collectionViewLayout: UICollectionViewLayout, 
               sizeForItemAt indexPath: IndexPath) -> CGSize
```

This method gives you access to the layout object for each index path

**Comment by Elshad** [comment]
@SD10 I has followed `extend class` way.

<img width="890" alt="screen shot 2018-12-11 at 12 08 14" src="https://user-images.githubusercontent.com/2334731/49786488-799d8980-fd3d-11e8-88be-26eb7ad3eadf.png">


In `viewDidLoad` add:
<img width="923" alt="screen shot 2018-12-11 at 12 04 44" src="https://user-images.githubusercontent.com/2334731/49786383-fd0aab00-fd3c-11e8-8983-55aa13cc6fff.png">

Result:
<img width="346" alt="screen shot 2018-12-11 at 11 51 09" src="https://user-images.githubusercontent.com/2334731/49786435-3f33ec80-fd3d-11e8-825f-b23b1aa2fcc2.png">

If we will use media and location, then we also must extend and add same `override` functions to `MediaMessageSizeCalculator` and `LocationMessageSizeCalculator`.

At now i think this solution is more clear solution

**Comment by SD10** [comment]
Yeah @Elshad I can definitely see how this got more difficult with MessageKit 1.0+

Technically, we're able to support that old `protocol` based API again -- I don't think we'll go that direction though. Maybe we can add more methods to the layout object to make this easier 🤔
