### ISSUE TITLE
Pod outdated?

### ISSUE THREAD

**Issue by BassApps** [MessageKit/MessageKit#953]
I've set up Pods only for this rep because it was the recommended way to install. However, it did install version 0.13.5. I suppose this shouldn't be happening? Might also be a layer 8 problem idk

```
pod install
Analyzing dependencies
Downloading dependencies
Installing MessageKit (0.13.5)
```

**Comment by SD10** [comment]
What does your podfile look like @BassApps? Try running `pod update`

**Comment by nathantannar4** [comment]
Try running `pod repo update` first

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BassApps** [comment]
Hey thanks for your replies guys, I've switched to Carthage now but when I have the time I will try again and report back to you
