### ISSUE TITLE
Help to extend MessageType

### ISSUE THREAD

**Issue by ichikmarev** [MessageKit/MessageKit#954]
We have 'public protocol MessageType'. Trying to extend it for my variables

Here is look like: `extension MessageType {
    var isSent: Bool { get }
}`

And of course it getting the error. If I try to define values before like this:

`extension MessageType {    
    var isSent: Bool {
        return false
    }
}`

They are not overriding. What a good practice here?

**Comment by nathantannar4** [comment]
I don't think you need to define `isSent` as a get

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
