### ISSUE TITLE
ChatView start from bottom message

### ISSUE THREAD

**Issue by kornha** [MessageKit/MessageKit#958]
Hello,

I looked hard to see this issue asked but haven't found anywhere. I am using MessageKit with Twilio chat. I call to load the messages, and try to immediately scroll to the bottom as follows:

```
    func loadMessages() {
        messages.removeAll()
        if channel.synchronizationStatus == .all {
            channel.messages?.getLastWithCount(100) { (result, items) in
                self.addMessages(newMessages: Set(items!))
            }
        }
    }
    
    func addMessages(newMessages:Set<TCHMessage>) {
        messages =  messages.union(newMessages)
        sortMessages()
        DispatchQueue.main.async {
            self.messagesCollectionView.reloadData()
            self.messagesCollectionView.scrollToBottom(animated: false)
        }
    }
```

However, instead of 'starting' at the bottom message, it 'blinks' and then scrolls down to the bottom.
No matter where I call these methods-eg viewDidLoad, same problem.

Happy to give more info. Thanks in advance.

- What version of MessageKit are you using?
2.0.0
- What version of iOS are you running on?
10.0
- What version of Swift are you running on?
4.2
- What device(s) are you testing on? Are these simulators?
iPhone X, XR, XS
- Is the issue you're experiencing reproducable in the example app?
Not sure

**Comment by brycezhang** [comment]
I have the same problem

**Comment by gmckee1** [comment]
I have the same issue. I've attempted to get around it temporarily with the following in viewWillAppear, although there seems to be an issue offsetting it the total amount, it won't go any further than just above the second to last message, regardless of how high I set the offset.

`let contentSize: CGSize = messagesCollectionView.contentSize
        if contentSize.height > messagesCollectionView.bounds.size.height {
           
            let keyboardHeight = messageInputBar.intrinsicContentSize.height + messageInputBar.padding.top + messageInputBar.padding.bottom
            let targetContentOffset = CGPoint(x: 0, y: contentSize.height - messagesCollectionView.bounds.size.height + navigationController!.navigationBar.bounds.height + keyboardHeight + 10)
            messagesCollectionView.contentOffset = targetContentOffset
            messagesCollectionView.setContentOffset(targetContentOffset, animated: animated)
        }`

**Comment by nathantannar4** [comment]
One way I have found that you can easily have messages render from the bottom upwards (like Slack), is by applying rotation transformations to the view and the cells.

The `UICollectionView` should have a transform of
`CGAffineTransform(rotationAngle: -.pi)`

And then each cell,  should have a transform of
`CGAffineTransform(rotationAngle: .pi)`

Things to note about this approach:
1. Your message list should be in reverse order to have the newest messages at the bottom
2. Default placement of the refresh control is now at the bottom.
3. Performance impacts? Not sure, haven't run benchmarks and idk how transforms effect performance

![simulator screen shot - iphone xs - 2018-12-28 at 09 50 51](https://user-images.githubusercontent.com/15272998/50523741-a2848500-0a86-11e9-91fe-0abef83dc8b7.png)

**Comment by kornha** [comment]
This is a serious bug and no one has addressed it. Sigh.

**Comment by kornha** [comment]
The only way to do this properly is to load about 20 messages from the chat client.

**Comment by jinkim22** [comment]
Hi guys,

Apparently, after MessageKit 2.0.0 was released, some collectionview methods were removed and some had trouble flipping the message cells. The new solution is to flip the cell in MessagesCollectionViewFlowLayout, specifically in the functions layoutAttributesForElements and layoutAttributesForItem. 

By calling attributes.transform = CGAffineTransform(scaleX: 1, y: -1) in these two functions, you should be able to rotate the cells!

**Comment by yspreen** [comment]
@jinkim22 Any chance to get this working with large titles?  
With double y-axis flipping, it looks very off: https://youtu.be/LLNT0DQMmBQ

**Comment by jinkim22** [comment]
Hey @yspreen,
From the video, it seems like the off look comes from the large title expanding a little too much when you scroll down, is that correct?

If so, I think the solution may be to disable bounce on scroll, which would not allow you to stretch the large title as much. You can do this on storyboard by unchecking bounce on scroll or by doing: yourCollectionView.alwaysBounceVertical = false

 I hope this helps, or let me know if I didn't understand your question correctly.

**Comment by yspreen** [comment]
The scrolling seems very broken when the keyboard opens too. The list doesn't automatically move up like you'd expect @jinkim22

**Comment by jinkim22** [comment]
@yspreen we ran into that issue too, you have to adjust all the methods from messagekit that performs of scrolling to the bottom to now actually scroll to the top of your collectionview since your collectionview is now upside down. I think for scrollToBottom i had:

public func scrollToBottom(animated: Bool = true) {
        performBatchUpdates(nil) { _ in
            self.scrollRectToVisible(CGRect(0.0, 0.0, 1.0, 1.0), animated: animated)
        }
}

cheers!

**Comment by yspreen** [comment]
I really dont see any way to get the keyboard events working @jinkim22 ...  
Overriding the methods in an extension is prohibited since `handleKeyboardDidChangeState` uses internal parameters. And because all the methods to change the keyboard are private, you cannot override `addKeyboardObservers` either.

**Comment by jinkim22** [comment]
@yspreen I directly edited MessagesViewController in MessageKit's pod files. As I mentioned before, it's important to adjust the content offset and inset depending on what action you're doing. here's a link for reference on offset vs. inset https://medium.com/better-programming/contentoffset-contentinset-and-contentsize-of-a-uiscrollview-5ae8beb0f1db

for me, I think I had to change the following functions:
scrollToBottom in messagesCollectionView: To make sure handleTextViewDidBeginEditing in MessagesViewController scrolls to the content offset that we want
handleTextViewDidBeginEditing in MessagesViewController: I think I put scrollToBottom here to 
handleKeyboardDidChangeState in MessagesViewController: We need to push the messages far up enough by adjusting the inset to be able to see all the messages.

There may be more files or functions to change, it'll be based off of how you're implementing your messagekit. I hope this helps!

**Comment by RomanMagellan** [comment]
Found [here](https://stackoverflow.com/a/57433832) some solution, maybe this can help somebody as to me. 
Call this after calling reloadData():

```
func updateCollectionContentInset() {
    let contentSize = yourCollectionView.collectionViewLayout.collectionViewContentSize
    var contentInsetTop = yourCollectionView.bounds.size.height

        contentInsetTop -= contentSize.height
        if contentInsetTop <= 0 {
            contentInsetTop = 0
    }
    yourCollectionView.contentInset = UIEdgeInsets(top: contentInsetTop,left: 0,bottom: 0,right: 0)
}
```
