### ISSUE TITLE
Show keyboard by default 

### ISSUE THREAD

**Issue by ios4vn** [MessageKit/MessageKit#959]
Sorry for inconvinien, but anyone can tell me how to show  the keyboard at initial ChatViewController

**Comment by TomWFox** [comment]
I'm not sure if I fully understand what you want to do but if you want the keyboard to be showing when the view appears you could do this:
```
override func viewWillLayoutSubviews() {
        messageInputBar.inputTextView.becomeFirstResponder()
}
```
You could also do this in `viewDidLayoutSubviews()` or `viewDidAppear()` but this won't work in `viewWillLoad()`, `viewDidLoad()` or `viewWillAppear()`.
