### ISSUE TITLE
Chat Bubble Animations

### ISSUE THREAD

**Issue by ByCyril** [MessageKit/MessageKit#961]
- What version of MessageKit are you using? 
2.0

- What version of iOS are you running on? 
iOS 12

- What version of Swift are you running on?
4.2

I was wondering if there is a way to animate the chat bubbles? I couldn't find anything about animations in the documentation so I'm assuming it doesn't support it. Any advice on how I can implement this myself?

**Comment by nathantannar4** [comment]
Can you be a bit more specific as to what you want to animate? Since we use a collection view you could implement I wide range of animations

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
