### ISSUE TITLE
The MessageInputBar moves up when pressing return key on the keyboard

### ISSUE THREAD

**Issue by n1schal** [MessageKit/MessageKit#962]
- What version of MessageKit are you using?
2.0.o
- What version of iOS are you running on?
12.1
- What version of Swift are you running on?
4.0
- What device(s) are you testing on? Are these simulators?
iPhone 6 (Device), iPhone 8(Simulator)
- Is the issue you're experiencing reproducable in the example app?
No

I have two issues. First : The MessageInputBar keeps moving up when I press Return until the bar reaches the Status Bar and keeps on adding white space below it. 

Once it reaches the top, it returns back to its usual position.

After going through some issues listed here, I removed IQKeyboardManager and then tried running my app, but the issue didn't go away.

Also, when I dismiss the TextInputView by dragging it down, the MIB seems to rise above.

I've attached the video of my issues. Please take a look and suggest steps to resolve these.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15378179/50373258-13015100-0604-11e9-8632-a8ebfb272f67.gif)

I have a custom navigation bar I created from XIB to match my needs and added it with the addSubView method.

```swift
 override func viewDidLoad() {
        super.viewDidLoad()

//         Do any additional setup after loading the view.
        let frame = CGRect.init(x: 0, y: 0, width: ScreenSize.SCREEN_WIDTH, height: AppDimensions.ConversationHeaderHeight)
        headerView = ConversationHeaderView.init(frame: frame)
        view.addSubview(headerView)
        headerView.btnBack.addTarget(self, action:#selector(onBackButtonTap), for: .touchUpInside)

        headerView.senderImageView.sd_setImage(with: URL(string: "https://heroichollywood.b-cdn.net/wp-content/uploads/2017/09/Batman_Ben_Affeck.jpg?x42694"), placeholderImage: UIImage(named: "user"))
        headerView.senderNameLabel.text = "Bruce Wayne"
        headerView.senderActiveLabel.text = "Active \(23)\("min") ago"
        
        
//        updateTitleView(title: "Bruce Wayne", subtitle: "Active \(23)\("min") ago")
//        setupAvatar()
//        setupBackButton()
        
        scrollsToBottomOnKeyboardBeginsEditing = true
        maintainPositionOnKeyboardFrameChanged = true
        
        
        messagesCollectionView.register(ConversationCollectionViewCell.self)
        messagesCollectionView.messagesDataSource = self
        messagesCollectionView.messagesLayoutDelegate = self
        messagesCollectionView.messagesDisplayDelegate = self
        
        configureMessageInputBar()
    }

func configureMessageInputBar(){
        messageInputBar.isTranslucent = false
        messageInputBar.separatorLine.isHidden = true
        messageInputBar.inputTextView.tintColor = AppTheme.Color.lightGrayText
        messageInputBar.inputTextView.backgroundColor = AppTheme.Color.veryLightGray
        messageInputBar.inputTextView.placeholder = "Send a Chat"
        messageInputBar.inputTextView.placeholderLabel.font = AppTheme.Font.regularFont16
        messageInputBar.inputTextView.placeholderTextColor = AppTheme.Color.lightGrayText
        messageInputBar.inputTextView.textContainerInset = UIEdgeInsets(top: 8, left: 16, bottom: 8, right: 36)
        messageInputBar.inputTextView.placeholderLabelInsets = UIEdgeInsets(top: 8, left: 20, bottom: 8, right: 36)
        messageInputBar.inputTextView.layer.borderColor = AppTheme.Color.clear.cgColor
        messageInputBar.inputTextView.layer.borderWidth = 1.0
        messageInputBar.inputTextView.layer.cornerRadius = 16.0
        messageInputBar.inputTextView.layer.masksToBounds = true
        messageInputBar.inputTextView.scrollIndicatorInsets = UIEdgeInsets(top: 8, left: 0, bottom: 8, right: 0)
        configureInputBarItems()
    }

private func configureInputBarItems() {
        messageInputBar.setRightStackViewWidthConstant(to: 36, animated: false)
        messageInputBar.sendButton.imageView?.backgroundColor = .clear
        messageInputBar.sendButton.contentEdgeInsets = UIEdgeInsets(top: 2, left: 2, bottom: 2, right:2)
        messageInputBar.sendButton.setSize(CGSize(width: 36, height: 36), animated: false)
        messageInputBar.sendButton.image = UIImage.init(named: "send")
        messageInputBar.sendButton.title = nil
        messageInputBar.textViewPadding.right = -38
    }

```

Also, how do i get rid of the grey background of the MIB ? I want to style it so that the only thing that has a background is the inputTextView, which I have achieved, but I haven't quite figured out how to  have a fully transparent MIB.

**Comment by nathantannar4** [comment]
To make it see through set the `backgroundView` color to clear. As for it moving up, I've see than before and it's IQKeyboardManager so double check that you have turned it off

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by n1schal** [comment]
Thanks.

Turns out, just having IQKeyboardManager pod installed is enough to cause the issue. I had only commented out the initialisers and saw the issue, so thought it wasn't due to IQKeyboardManager

**Comment by nathantannar4** [comment]
@n1schal I think you can still use `IQKeyboardManager`, there is a way to disable it for a specific `UIViewController` (I think)
