### ISSUE TITLE
[Solved] TopLabel not appearing after setting

### ISSUE THREAD

**Issue by xan-a-a** [MessageKit/MessageKit#963]
Thank you for this repo. It is awesome.

I am trying to show sender names. I found those two methods that I've implemented
```
    func messageTopLabelAttributedText(for message: MessageType, at indexPath: IndexPath) -> NSAttributedString? {
        print(">>>>>>>>>>")
        return NSAttributedString(string: "asd", attributes: [NSAttributedString.Key.font: UIFont.boldSystemFont(ofSize: 10), NSAttributedString.Key.foregroundColor: UIColor.darkGray])

    }
    func cellTopLabelAttributedText(for message: MessageType, at indexPath: IndexPath) -> NSAttributedString? {
         print(">>>>>>>>>>1111")
        return NSAttributedString(string: "asd", attributes: [NSAttributedString.Key.font: UIFont.boldSystemFont(ofSize: 10), NSAttributedString.Key.foregroundColor: UIColor.darkGray])
}

```
Both get printed but there is nothing appearing on them, I still see them just like I did prior to adding those functions. Is there any "hidden" property that I have to set to false? I have also set the delegates if that helps

```
        messagesCollectionView.messagesDataSource = self
        messagesCollectionView.messagesLayoutDelegate = self
        messagesCollectionView.messagesDisplayDelegate = self
        messagesCollectionView.messageCellDelegate = self
```

If this is an actual bug I will provide more info (latest version everything) but I feel like I am just missing something

**Comment by xan-a-a** [comment]
Sorry I found it, missing `messageTopLabelHeight` was the issue.
Maybe set a default if not specified and not empty? Just a suggestion

**Comment by SD10** [comment]
@xan-a-a I think it would be pretty difficult to provide a default size because then there could be unexpected behavior in the other direction. People would provide some text and then it would not fit

**Comment by xan-a-a** [comment]
What do you mean with "other direction"? There is the `sizeWithFont` function to estimate label size by string and font.

Not trying to argue, I get where you are coming from but maybe you haven't thought of that one.

**Comment by nathantannar4** [comment]
@xan-a-a I think what Steven means is that since it wasn't an original feature of MessageKit there are already many using the library without the TopLabel, so making the TopLabel appear by default would be confusing to those who update MessageKit and not know that its a new feature
