### ISSUE TITLE
Parse Server example

### ISSUE THREAD

**Issue by jumper4000** [MessageKit/MessageKit#964]
Does anyone have an example of how to get this to work with Swift 4, Parse Server, and Parse LiveQuery? That'll greatly be appreciated.

**Comment by JulienKode** [comment]
Hi, @jumper4000 It's something related to [ParseLiveQuery-iOS-OSX](https://github.com/parse-community/ParseLiveQuery-iOS-OSX) and not MessageKit 

If you have question about theses library you will find better ressources on Stackoverflow or the GitHub repository of parse
