### ISSUE TITLE
How to add a slider inside custom cell and slide properly

### ISSUE THREAD

**Issue by vincent1332** [MessageKit/MessageKit#966]
- What version of MessageKit are you using?
1.0.0
- What version of iOS are you running on?
11
- What version of Swift are you running on?
Swift 4.0
- What device(s) are you testing on? Are these simulators?
iPhone 6 
- Is the issue you're experiencing reproducable in the example app?

Hi, 

I am trying to add a UISlider inside a custom cell, when I try to slide, it is intercepted by the tap gesture in ```MessageCollectionView``` and I cannot get any where near the slider. 

I tried to override ```handleTapGesture``` in my custom cell and detect, act on the touch with the following 

```
let touchLocation = gesture.location(in: self)
let translateTouchLocation = convert(touchLocation, to: messageContainerView)
let progressViewTouchArea = CGRect(x: progressView.frame.origin.x, y: progressView.frame.origin.y - 10,
                                          width: progressView.frame.width, height: progressView.frame.height + 20)
if progressViewTouchArea.contains(translateTouchLocation) {
    let point = gesture.location(in: progressView)
    let thumbWidth = progressView.thumbRect(forBounds: progressView.bounds,
                                            trackRect: progressView.bounds, value: progressView.value).size.width
    var value: Float = 0.0
    if (point.x <= thumbWidth / 2) {
        value = progressView.minimumValue
    } else if (point.x >= self.bounds.size.width - thumbWidth / 2) {
        value = progressView.maximumValue
    } else {
        let percentage = Float((point.x - thumbWidth / 2) / (progressView.bounds.size.width - thumbWidth))
        let delta = percentage * (progressView.maximumValue - progressView.minimumValue)
        value = progressView.minimumValue + delta
    }
    self.progressView.value = value
}
```

But I can only get the slider to go to the tapped position, wondering if there is a way to allow the slider to interact properly? 

Thank you.

**Comment by vincent1332** [comment]
Just realized I set the wrong ```isUserInteractionEnabled```, should set on ```messageContainerView``` instead of contentView of the cell.

**Comment by ahmedkoshek** [comment]
@vincent1332 Did you find a fix for this?
