### ISSUE TITLE
Syncing images and media messages in the MessageKit

### ISSUE THREAD

**Issue by ntvhouston** [MessageKit/MessageKit#967]
I am able to sync the firebase Firestore to retrieve the messages already existing on the server. I am having problem in showing up image messages.

What I am doing is while sending the message, I am replacing the message with imageURL in key and pushing the Firebase Storage url in the value for imageurl.

While retrieving I am able to retrieve images too and using kingfisher to download the images.

**The issue :-** When user tap on the person's cell to chat with that person, the messages download instantly but images do not appear whereas if that user goes on step back in the chat menu and again open the chat second time, the images show up at the right place.

**My approach:-**

```
let image = UIImageView()

// ImageURL is the url fetched from firebase
image.kf.setImage(with: URL(imageURL))

// Assigning UIImage to add to the message model and using insert message method from the example to add to the model
let messageImage = MessageModel(image: image.image!, sender: sender, messageId: messageID, date: date)

self.insertMessage(imageMessage)
```
**This approach does work but not able to sync the images on time which is when the user tap on chat**

**_I have found a solution in the issues section but it needs a url to download the images and the solution is as follows:-_**

```
func configureMediaMessageImageView(_ imageView: UIImageView, for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView)
{
    switch message.kind {
    case .photo(let photoItem):

        /// if we don't have a url, that means it's simply a pending message
        guard let url = photoItem.url else {
            imageView.kf.indicator?.startAnimatingView()
            return
        }
        imageView.kf.indicatorType = .activity
        imageView.kf.setImage(with: url)

    default:
        break
    }
}
```
But to implement this I need to have image url which I do have from the firebase but I am having issue on how to add it to the message model because message model have a specific image method which needs a UIImage and not a string.

How can I send image url to the message data model so that I can further use it in **configureMediaMessageImageView method.**

**NOTE: MessageModel is exactly the same file which is mock messages file in example. I am using it as my message data model.**

Thanks

**Comment by nathantannar4** [comment]
You can't use the exact same image message model we use in the example as it's what is causing you to require a UIImage. `MessageKind.image` Has the associated type `MediaItem` which is a protocol that has a URL property

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ntvhouston** [comment]
Thanks for the reply. I managed to get the perfect behavior I was looking for and thanks a lot for supporting such a great repo.

I just have a last question how can I add a progress bar onto the image view while the image is still downloading.

I have a solution for this is by adding the kingfisher progress bar onto the image view and I am sure it will work perfectly but the issue is that the imageview I have in configuremediamessageimageview method is a constant and therefor the kingfisher have a method which sets the property like this: 
imageView.kf.indicatorType = .activity
which in this case won't work so is it possible to change the imageview from Let to a var or there is a default method to add progress bar in imageview?

Thanks again

**Comment by nathantannar4** [comment]
Sorry I don't see the problem as to why you can't use kf on the image view in the config method? Nor do I see how changing it to var would help something like this. Can you explain it more clearly? Perhaps with an example?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jksjaz** [comment]
Well for example I have a imageview and to apply the indicator on the image view while downloading the image the kf have a property which we set as such:
    imageView.kf.indicatortype = .activity
So as this is a set property attribute and therefor it need a variable to set this whereas the image view is a constant.

**Comment by ntvhouston** [comment]
@nathantannar4 looking for some solution. Thanks

**Comment by nathantannar4** [comment]
Did something in Kingfisher change? I could have sworn I've done this before. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ntvhouston** [comment]
Well I have tried this with kingfisher before too and this use to work the same way and still does work the same way now. It needs a var for indicatortype to be assigned. Maybe if they changed something I would have no idea. I really appreciate if we can get it working by any chance.
Thanks

**Comment by nathantannar4** [comment]
@ntvhouston I will keep it in mind for the next release but things are a bit busy for us right now. For the time being I would use an older version of Kingfisher.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ntvhouston** [comment]
Ok got solution from kingfisher guys : 

**You can just either make the image view mutable or the kf mutable:**

```
var i = imageView
i.kf.indicatorType = .activity

var kf = imageView.kf
kf.indicatorType = .activity
```

Thanks a lot.

**Comment by nathantannar4** [comment]
@ntvhouston ah this seems like a kf issue then. It's the kf object that is immutable. Even if we changed the image view to var since it's passed into a function that reference is constant. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
