### ISSUE TITLE
Questions about MessageKit capabilities/functionality

### ISSUE THREAD

**Issue by bmt2018** [MessageKit/MessageKit#968]
I need to add a chat capability to an existing app and I've been researching a few different frameworks that provide this functionality.  MessageKit looks like a great fit for me but I have two questions about using it:

1. Is it possible to add a couple of icons/buttons at the bottom of each chat bubble (or just below each chat bubble) such that the user can tap on these to perform a certain action?

2. Is it possible to create a custom bubble type for a "new" type of message?  I need to support audio messages (similar to the existing photo and video messages).

Thanks for any information!

**Comment by nathantannar4** [comment]
Yes to both but it will require some extra work on your end to add custom cells. There are already a few archived issues that ask how to make custom cells or you can look to the ChatExample project in the repo. 

1. Either make a custom cell that is subclasses from the default text message cell or override the cellForRowAt and numberOfItemsInSection methods to return an extra cell below the bubble. 

2. You can use the `MessageKind.custom(Any)` if you need something custom 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bmt2018** [comment]
Thanks for the quick reply, Nathan!  I appreciate the info.
