### ISSUE TITLE
Properties on MessagesCollectionView never set. How come?

### ISSUE THREAD

**Issue by hhanesand** [MessageKit/MessageKit#969]
- What version of MessageKit are you using? 2.0.0

```swift
// MARK: - Properties
open weak var messagesDataSource: MessagesDataSource?
open weak var messagesDisplayDelegate: MessagesDisplayDelegate?
open weak var messagesLayoutDelegate: MessagesLayoutDelegate?
open weak var messageCellDelegate: MessageCellDelegate?
```
It doesn't seem to me that these are being set anywhere in the 2.0.0 release, meaning the collection view will be unable to display anything. At least a search for `.messagesDataSource =` doesn't show anything. Am I missing something? Should I set these properties myself?

**Comment by nathantannar4** [comment]
Those are properties that you are to set. They are the method of interfacing/providing data to MessageKit. See the ChatExample

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hhanesand** [comment]
Thanks! I'll submit a PR adding this to the quick start, since it's missing there.

**Comment by nathantannar4** [comment]
I'm not sure if that's warranted. The `dataSource` / `delegate` pattern is common in UIKit such as in `UITableView`/`UICollectionView`. What was the confusion you had?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hhanesand** [comment]
Only this. I assumed MessageKit would set the delegate and datasource to be the chat view controller subclass. Agreed it's a very common pattern, but could be nice to mention still? Up to you.
