### ISSUE TITLE
Sender should be a protocol rather than a concrete type

### ISSUE THREAD

**Issue by AttilaTheFun** [MessageKit/MessageKit#970]
MessageType being a protocol rather than a struct implies that consumers of the library should adapt their existing models for use by MessageKit, rather than mapping them into a concrete message type. But because Sender is a concrete type, that means that either it would have to be generated on the fly in a computed property getter, or people should be making their own concrete types which implement MessageType which has a Sender field. I propose instead the Sender struct be replaced with a SenderType protocol:

```
protocol SenderType {
  var id: String { get }
  var displayName: String { get }
}
```

And the Sender struct can stick around as a concrete implementer of that protocol:
```
struct Sender: SenderType { ... }
```

But people could also adapt their own types like so:

```
extension User: SenderType {
  // user already has an id field
  var displayName: String {
    return self.firstName + " " + self.lastName
  }
}
```

**Comment by nathantannar4** [comment]
Duplicate of #628. Proposed solution in #909

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
