### ISSUE TITLE
Messages hid behind navigation bar when keyboard toggled.

### ISSUE THREAD

**Issue by tnylee** [MessageKit/MessageKit#972]
- What version of MessageKit are you using? 2.0.0
- What version of iOS are you running on? 12.0
- What version of Swift are you running on? 4.2
- What device(s) are you testing on? Are these simulators? iPhone XR simulator/iPhone 7 device/iPhone XR device all running iOS 12.0
- Is the issue you're experiencing reproducable in the example app? No

I found 2 issues when the keyboard toggled:
1. When scrolled to top, first message hid behind navigation bar.
2. When scrolled to bottom, there's space between last message and `MessageInputBar`

Might be the same issue with #300 

I screen recorded gif:
https://gph.is/2RA65GU

Here's how I show my `TNMessagesViewController`:
```
// in TNInboxViewController
let messagesViewController = TNMessagesViewController()
self.navigationController?.pushViewController(messagesViewController, animated: true)
```

All I did in my `TNMessagesViewController` was setting the collection view's datasource and delegate just like the example provided.

I found that if I initially set `prefersLargeTitles` to `TNInboxViewController` navigation controller navigation bar, the issue disappears. But being in messages view controller, I think its best to not show large titles as it will take up too much space.

```
inboxNavigationController.navigationBar.prefersLargeTitles = true // if set, issue disappears
```

**Comment by caglarcakar** [comment]
Problem still exists and setting "chatViewController.navigationController?.navigationBar.prefersLargeTitles = true" not solving the issue.

**Comment by alielsokary** [comment]
@tnylee @caglarcakar 
and anyone looking for a fix
Are you using **IQKeyboardManager**? 
If so then you can fix the issue simply by adding this in `AppDelegate` `didFinishLaunchingWithOptions`: 

`IQKeyboardManager.shared.disabledDistanceHandlingClasses.append(YourChatViewController.self)` 

😉
