### ISSUE TITLE
Custom cell doesn't appear right or left 

### ISSUE THREAD

**Issue by lalfuturedev** [MessageKit/MessageKit#973]
- MessageKit 2.0
- IOS 12.1
- Swift 4.2
- tested on both simulator and real device

I test custom cell inspired from AdvanceChatExampleViewController and custom view always appear on center.I want custom view to set left or right like normal messages.

**Comment by nathantannar4** [comment]
You need to write the layout code for how the cell will be aligned. Cells always span the width of the screen, we just use the MessageCollectionViewFlowAttributes to align it based on isCurrentCenter.

From a high level point of view, MessageKit has no idea what views are in your custom cell so it can't adjust the layout. They are custom. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lalfuturedev** [comment]
Thanks @nathantannar4

**Comment by sagar-winjit** [comment]
Does anyone got the solution to appear custom cell on right or left with some example code?
