### ISSUE TITLE
keyboardWillShowNotification

### ISSUE THREAD

**Issue by tulssinep** [MessageKit/MessageKit#977]
Due to a bit of iPad incompatibility in #976 I am adding the inputBar manually on iPad. When the keyboard goes up, it covers the inputBar so I've added this:

```
        NotificationCenter.default.addObserver(self, selector: #selector(self.keyboardWillShow), name: UIResponder.keyboardWillShowNotification, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(self.keyboardWillHide), name: UIResponder.keyboardWillHideNotification, object: nil)
}

    @objc func keyboardWillShow(notification: NSNotification) {
        print("KEYBOARD WILL SHOW") //gets called when the ViewController gets loaded without a keyboard being present

    }
    @objc func keyboardWillHide(notification: NSNotification) {
         print("KEYBOARD WILL HIDE") //gets called after opening and closing the keyboard manually
    }
```
Do you know why this happens? I don't have an external keyboard attached so I don't get why this is being triggered. Right now I store a bool to make it ignore the first call but this doesn't feel right

**Comment by austinwright** [comment]
I believe that the inputAccessoryView is 'part' of the keyboard. The view controller becomes first responder when it loads for the first time which displays the inputAccessoryView. Even if you are not using the inputAccessoryView I believe the MessagesViewController sets things up this way.
