### ISSUE TITLE
does not conform to protocol 'MessagesDataSource'

### ISSUE THREAD

**Issue by eiei** [MessageKit/MessageKit#978]
Plz kindly check my issue
![screen shot 2019-01-24 at 9 54 22 am](https://user-images.githubusercontent.com/3841273/51652584-907eff00-1fbe-11e9-800d-64d315f9bb74.png)

**Comment by nathantannar4** [comment]
Your `ChatViewController` needs to implement the methods defined in `MessagesDataSource`
