### ISSUE TITLE
accessoryView is not correctly recycled

### ISSUE THREAD

**Issue by justmaaarco** [MessageKit/MessageKit#983]
- What version of MessageKit are you using?
   2.0.0
- What version of iOS are you running on?
   12.1
- What version of Swift are you running on?
   4.2
- What device(s) are you testing on? Are these simulators?
   Simulator, iPhone 8 plus
- Is the issue you're experiencing reproducable in the example app?
   I don't think so

Hello again!
I'm facing a strange issue on MessageKit: I tried to implement the accessory view as a "tap to resend" button in case the message has not been sent but the view is actually appearing randomly in the cells and it's not following the right logic.
This is the code I wrote down to manage it:

`func configureAccessoryView(_ accessoryView: UIView, for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) {
        // Cells are reused, so only add a button here once. For real use you would need to
        // ensure any subviews are removed if not needed
        //accessoryView.subviews.forEach { $0.removeFromSuperview() }
        let msg = messages[indexPath.section]
         if isNotSentYet(message: msg) {
            let button = UIButton(type: .infoLight)
            button.tintColor = Colours.errorRed
            button.isUserInteractionEnabled = false
            button.frame = accessoryView.bounds
            accessoryView.addSubview(button)
            accessoryView.layer.cornerRadius = accessoryView.frame.height / 2
            accessoryView.backgroundColor = Colours.errorRed.withAlphaComponent(0.3)
        }
        else {
            accessoryView.removeFromSuperview()
        }
    }
}`

This is basically what happens when I scrolldown and up:

https://imgur.com/a/qOKF8e8

**Comment by nathantannar4** [comment]
@Nem2s cells are reused, it is your responsibility to clear the accessory view

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by justmaaarco** [comment]
@nathantannar4 what should I do to clear the view correctly? I tried to remove the view if it doesn't match the condition: `else { accessoryView.removeFromSuperview() }` but it's still showed. Is there any other function to implement to do that? Thanks in advance.

**Comment by nathantannar4** [comment]
Wouldn't you want to be removing the accessory view's subviews?

**Comment by justmaaarco** [comment]
I thought by removing the entire object all the subviews would be removed as well. Anyways I ended up by using the `alpha` parameter of the accessoryView to hide/show it properly without managing the views themselves. Thank you for your help boss @nathantannar4
