### ISSUE TITLE
Add "TwoApp for Whatsapp" to the list of apps using this library | license disclaimer?

### ISSUE THREAD

**Issue by xan-a-a** [MessageKit/MessageKit#984]
Apple hast just approved TwoApp, an app employing this library to display conversations.

It isn't too feature-rich in this first version but maybe you want to add it to the list of apps using this libraries.

Whatsapp for some reason won't make an iPad(/ second iPhone) app, probably because enough developers covered that with their third-party apps already. However, while just displaying the Whatsapp Web interface on the iPad makes it feel like a bad implementation of a web app, it's completely unusable on iPhone. This is why I decided to display the data in a native interface written in Swift - MessageKit was awesome for that. Needed to apply some ugly tweaks in order for it to work properly in my very situation but I'm very thankful for this repo. 

It also does some stuff like syncing your Whatsapp contacts' pictures to your "Contacts" app (something I never bothered even starting for my closest friends) but the main focus is the chat interface, MessageKit was an incredible help. Thank you. (not attaching pictures here cuz I don't want people to think this post is for advertising purposes haha)

App Store link: https://itunes.apple.com/us/app/twoapp-for-whatsapp/id1450671265

One question tho, I don't know much about licenses to be honest - is the app supposed to mention MessageKit from within the app or its description/ website? If so, where should I put the info?

**Comment by nathantannar4** [comment]
Congrats on your app launch! Please feel free to make a PR adding it into the list of apps using this.

As for your question on licenses, usually apps that employ open source libraries have an acknowledgments page somewhere in the app where it lists the open-source frameworks that were used.
