### ISSUE TITLE
firstResponder Warning

### ISSUE THREAD

**Issue by Michele404** [MessageKit/MessageKit#987]
- What version of MessageKit are you using? = Last version
- What version of iOS are you running on? = 12.1.4
- What version of Swift are you running on? = 4.2
- What device(s) are you testing on? Are these simulators? = All devices
- Is the issue you're experiencing reproducable in the example app? Yes

To reproduce it just write a message into the chat

The warning is:
First responder warning: '<MessageInputBar.InputTextView: 0x7f9a78922400; baseClass = UITextView; frame = (0 4; 353 38); text = ''; clipsToBounds = YES; gestureRecognizers = <NSArray: 0x600000af4360>; layer = <CALayer: 0x60000040bf40>; contentOffset: {0, 0}; contentSize: {125, 36.333333333333336}; adjustedContentInset: {0, 0, 0, 0}>' rejected resignFirstResponder when being removed from hierarchy

**Comment by Michele404** [comment]
up

**Comment by austinwright** [comment]
So this is just a warning, not a crash?

**Comment by Michele404** [comment]
Its a warning. Everytimes that I write some messages, it appear
