### ISSUE TITLE
Is it compatible with Swift 3 Project ?

### ISSUE THREAD

**Issue by tugsjargal1** [MessageKit/MessageKit#988]
Hi guys,

Is it compatible with Swift 3 Project ? I see the installation tips for swift 3 project:
```
target 'TARGET_NAME' do
    pod 'MessageKit'
    ...
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            if target.name == 'MessageKit'
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = '4.0'
                end
            end
        end
    end
end

```
But compiler error throws in "MessageInputBar" library. I think "MessageInputBar" is compatible with Swift 4.0. 

Do you have any compatible version with Swift 3 project ? Or another solution to run with Swift 3.0 project ?

Thank you.

**Comment by aqeelaslam** [comment]
I tried using it a swift 3 project as well but it's giving too many errors in MessageInputBar.

**Comment by subdiox** [comment]
Could you try the code below? This code builds MessageInputBar with Swift 4.0 as well as MessageKit.
```
target 'TARGET_NAME' do
    pod 'MessageKit'
    pod 'MessageInputBar'
    ...
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            if target.name == 'MessageKit' || target.name == 'MessageInputBar'
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = '4.0'
                end
            end
        end
    end
end
```

**Comment by tugsjargal1** [comment]
Hey guys,

Finally only one solution is to use Swift4. So, we need to integrate the project Swift3 to Swift4.

Thanks.
