### ISSUE TITLE
Text in message bubble not centered

### ISSUE THREAD

**Issue by zoufishanmehdi** [MessageKit/MessageKit#990]
- What version of MessageKit are you using?
      2.0.0. 
- What version of iOS are you running on?
      12.1
- What version of Swift are you running on?
       4.2 
- What device(s) are you testing on? Are these simulators?
      iPhone 7
- Is the issue you're experiencing reproduceable in the example app?
      Not sure

Hi, 

The text in message bubble doesn't appear to be centered. There's more space to the left compared to the right. Please refer to the screenshot below. 

![chat22](https://user-images.githubusercontent.com/12058032/53050322-0f087880-3467-11e9-93b3-eb8c1d366fcb.png)

**Comment by nathantannar4** [comment]
Looks like this is a custom example. Do you know how to reproduce this in say the ChatExample project?

**Comment by zoufishanmehdi** [comment]
Not sure. We are parsing html as an attributed string and then displaying it in the bubble. However, our website is using the same html and it's not showing off center there.

**Comment by nathantannar4** [comment]
I would check the attributed string attributes that are applied and ensure that message doesn't have a space. Google.com message looks fine so it seems isolated to that message 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yspreen** [comment]
@nathantannar4 There's no custom logic needed really. If you just implement the most basic version of MessageKit, it looks exactly like this. I'm not sure how to resolve it, and I've had the same issue in multiple projects...

**Comment by yspreen** [comment]
All that's needed to showcase this bug is to switch the example from tailed bubble to bubble. https://github.com/yspreen/MessageKit-off-center/commit/025c6c162943b8dbbf82eb58475cf679ce8cae98

I'll open a new issue for this too, since this one is closed.

**Comment by yspreen** [comment]
@zoufishanmehdi Did you ever fix this?

**Comment by monstermac77** [comment]
For those who come across, this can be used to have even padding for the cells: https://github.com/MessageKit/MessageKit/issues/1385#issuecomment-663943893

**Comment by monstermac77** [comment]
I believe the key is the label offsets and adjusting the frame of the message container. This is the code I'm using: https://github.com/MessageKit/MessageKit/issues/1385#issuecomment-1480355202

![Simulator Screen Shot - iPhone 14 Pro - 2023-03-22 at 18 45 31](https://user-images.githubusercontent.com/3255298/227055535-87e48570-dbd4-4b49-bac1-fa9476fa3b7b.png)
