### ISSUE TITLE
issue extending 'MessageType' 

### ISSUE THREAD

**Issue by RaghavBr1** [MessageKit/MessageKit#992]
Hi, this is my first time with MessageKit. I am trying out an example I found online. I am getting this error - "Inheritance from non-protocol type 'MessageType'" when trying to extend MessageType. 
I am using MessageKit 2.0.0, Swift 4.2 and iOS version 10.
Here's the code:

import Foundation
import UIKit
import MessageKit

struct Member {
    let name: String
    let color: UIColor
}

struct Message {
    let member: Member
    let text: String
    let messageId: String
}

extension Message: MessageType {
    var sender: Sender {
        return Sender(id: member.name, displayName: member.name)
    }
    
    var sentDate: Date {
        return Date()
    }
    
    var kind: MessageKind {
        return .text(text)
    }
}

**Comment by nathantannar4** [comment]
Only classes can confirm to `MessageType`, you defined `Message` as a struct. Classes are generally more efficient in swift
