### ISSUE TITLE
How to add quick replies?

### ISSUE THREAD

**Issue by codemonza** [MessageKit/MessageKit#995]
This is a request related to https://github.com/MessageKit/MessageKit/issues/511. However I would like the quick replies be displayed in the chat window instead of the input bar, similar to how it's implemented in LinkedIn.

**Comment by nathantannar4** [comment]
I would put a custom view in the `topStackView` of the `MessageInputBar`, or you could add a subview to the `MessagesViewController` but you will then have to manage its position/size/etc

**Comment by codemonza** [comment]
FYI: As documented in #511, I am facing this problem when placed the custom view in topStackView. 
Placed a CollectionView with 3 Button (which when pressed prints a statement) on topStackView. When the CollectionView is "standalone", the print statements work. On topStackView they didn't.

How the button actions are set:- In the CollectionViewController's _cellForItemAt_:

```
         abutton.addTarget(self, action: #selector(buttonAction), for: .touchUpInside)
         return abutton
         }()    
        cell.addSubview(button)
```
There is also now this error when I type into the inputbar and press Send. The three buttons disappeared and chat screen became inaccessible. Before putting anything on topStackView of course the inputbar was working fine.
```API error: <_UIKBCompatInputView: 0x101a5d770; frame = (0 0; 0 0); layer = <CALayer: 0x282c6fac0>> returned 0 width, assuming UIViewNoIntrinsicMetric```

**Comment by nathantannar4** [comment]
I remember seeing that you created a UIViewController and then inserted it's collection view. Im not positive but adding a UIViewController as a target when it's not presented could be a problem. You should just create a UIView subclass. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
I think that API error is a simulator bug if it's the same one Ives seen before. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codemonza** [comment]
Woohoo! It's working without the UIViewController as suggested! Thank you so much Nathan :)
> I remember seeing that you created a UIViewController and then inserted it's collection view. Im not positive but adding a UIViewController as a target when it's not presented could be a problem. You should just create a UIView subclass.

**Comment by codemonza** [comment]
Haven't seen this error since changed to CollectionView and not CollectionViewController, on same device.
> I think that API error is a simulator bug if it's the same one Ives seen before

**Comment by codemonza** [comment]
Hi Austin, please reopen the issue. Problem starts showing up when implementing the rest of the action. Specifically, now there's fatal error saying the QuickReplyCollectionView is not a MessageCollectionView, even though addArrangedSubview(UIView). And after I made the QuickReplyCollectionView conforms to the MessageCollectionView and assigned MessageLayoutDelegate (another requirement for referenceSizeForHeaderInSection()), now the quick reply buttons are not working...

**Comment by nathantannar4** [comment]
Why does the quick reply need to be a MessageCollectionView? If you are going that route the error is because it's not subclassed from MessageCollectionView

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codemonza** [comment]
The fatal error about QuickReplyCollectionView is not a MessageCollectionView started to show up after I implemented QuickReplyCollectionViewDelegate. And when I subclass QuickReplyCollectionView to MessageCollectionView instead of UICollectionView, that error went away (came the second error about MessageLayoutDelegate not set). That's why.

**Comment by nathantannar4** [comment]
Ya you need to set the display delegate

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codemonza** [comment]
@nathantannar4 I am not sure how to proceed at this point.. With QuickReplyCollectionView: MessagesCollectionView, MessagesDisplayDelegate, MessagesLayoutDelegate {}, the quick reply buttons are not responding. Is this the right approach to go forward with? Making a  QuickReplyCollectionViewDelegate so that the ChatViewController can get the quick reply info and insert that message in the chat window? Or do you have other suggestions?

**Comment by codemonza** [comment]
Hi again, any comments?

**Comment by nathantannar4** [comment]
You have probably mis configured something. There is really little for me to go on to help you debug this. I'm not sure why you are duplicating a messages view for quick reply rather than using a simple view with a few buttons 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
