### ISSUE TITLE
Replacement for MessageCellLayoutContext?

### ISSUE THREAD

**Issue by whoyawn** [MessageKit/MessageKit#996]
- What version of MessageKit are you using? 2.0.0 (was 0.13.0)
- What version of iOS are you running on? 11
- What version of Swift are you running on? 4.0
- What device(s) are you testing on? Are these simulators? N/A
- Is the issue you're experiencing reproducable in the example app? Yes

```swift
*your code goes here*

/// Overriding this to set size of message container for custom types
    override func messageContainerSize(for attributes: MessageIntermediateLayoutAttributes) -> CGSize {
        if let message = attributes.message as? ConvoMessage {
            switch message.type {
            case .missedCall:
                return CGSize(width: Int(attributes.messageContainerMaxWidth),
                                        height: TRMissedCallCell.cellHeight)
            default: break
            }
        }

        return super.messageContainerSize(for: attributes)
    }
```

I'm trying to update from 0.13.0. I could not find any documentation on these changes, and it looks like the replacement, `MessageCellLayoutContext`, has also been removed. How do I set the container size?

**Comment by nathantannar4** [comment]
You can specify cell size using the cell size calculators in the MessageCollectionViewLayout. You would have to subclass one and then set it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by whoyawn** [comment]
`MessageCollectionViewLayout`? I don't see that anywhere in the repo. Are you referring to a different class?

**Comment by nathantannar4** [comment]
There is only one layout class. Sorry I'm on my phone and didn't recall the name exactly

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by whoyawn** [comment]
No worries, is it this one?

https://messagekit.github.io/Classes/MessagesCollectionViewLayoutAttributes.html

There's also MessageSizeCalculator: https://messagekit.github.io/Classes/MessageSizeCalculator.html

Both seem similar. Which one do I use?

**Comment by nathantannar4** [comment]
Neither. It's the layout class in the layout folder. MessagesCollectionViewLayout. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by whoyawn** [comment]
Ah, `MessagesCollectionViewFlowLayout`. Thanks!
