### ISSUE TITLE
Can't import MessageInputBar

### ISSUE THREAD

**Issue by usama3355** [MessageKit/MessageKit#998]
It's not importing MessageInputBar. How can i build the project?

**Comment by nathantannar4** [comment]
What version are you using? Carthage or Cocoapods? Have you tried rebuilding dependencies

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Thomdev46** [comment]
Same problem on xcode 10 and 10.1, swift 4.2 and messageKIT 2.0.0. Installing pod 'MessageInputBar' (0.4.1) (as suggested [here](https://stackoverflow.com/questions/53378904/swift-messagekit-problems-running-swift-4-2)) isn't solving anything.

**Comment by ratulSharker** [comment]
You should import 'MessageKit' that should import all the classes inside the MessageKit.
